### ISSUE TITLE
如何在前端监听数据表单的submit事件？

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#1003]
Dcat Admin Version: 1.7.7

### Description:

因为业务逻辑需要在前端监听数据表单的 `submit` 事件进行一些处理。

我在控制器中添加了下面的代码

```
            $formId=$form->getElementId();  
    
            Admin::script(<<<JS
                console.log($("#{$formId}"));
                $("#{$formId}").on("submit",function(event){
                    console.log("test");
                });
            JS);
```
通过 Chrome DevTools 观察，打开数据表单页面时，第一个 `console.log` 执行功能了
但数据表单提交时，第二个 `console.log `并没有执行。
通过 查看页面的 `view-source`，发现，我使用 `Admin::script` 添加的js代码 会比 `Dcat\Admin\Form\Builder` 中的 `addSubmitScript` 方法添加的js代码早插入。直觉觉得 `addSubmitScript` 初始代 form 时，把我添加的监听事件给清除了。

通过查看 `addSubmitScript` 的方法得知，dcatadmin 并没有提供方法，在前端监听数据表单的submit事件。
希望后续可以提供添加数据表单的前端监听事件的方法，谢谢

**Comment by jqhph** [comment]
使用下面的方法禁用默认的表单提交功能，然后参考文档JS组件章节，自定义表单提交功能
```php
$form->ajax(false);
```
