### ISSUE TITLE
数据表格资料删除问题

### ISSUE THREAD

**Issue by pkkbkraa** [jqhph/dcat-admin#1006]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.16

### Description:
想请教一下，如何在数据表格删除资料或批次删除时，先做额外的判断，回传true时才执行删除，谢谢

**Comment by jqhph** [comment]
表单有`deleting`事件，可以拦截删除请求，参考文档表单事件章节

**Comment by pkkbkraa** [comment]
试过了，没办法中断后又回传新的confirm
所以后来我做新的删除按钮取代原本的，这样就可以了，感谢
