### ISSUE TITLE
关于$grid->get() 优化

### ISSUE THREAD

**Issue by privarepan** [jqhph/dcat-admin#1007]
文件位置 vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php
文件位置 vendor/dcat/laravel-admin/src/Repositories/QueryBuilderRepository.php

![image](https://user-images.githubusercontent.com/26546738/105575061-b2750d00-5da3-11eb-935b-f69fb695abb1.png)
public function get(Grid\Model $model)
    {
        $this->setSort($model);
        $this->setPaginate($model);

        $query = $this->newQuery();

        if ($this->relations) {
            $query->with($this->relations);
        }

        $model->query = $query->clone();
        $model->getQueries()->unique()->each(function ($value) use (&$query,$model) {
            if ($value['method'] === 'paginate') {
                $model->query = $query->getQuery()->clone();
                $value['arguments'][1] = $this->getGridColumns();
            } elseif ($value['method'] === 'get') {
                $model->query = $builder->getQuery()->clone();
                $value['arguments'] = [$this->getGridColumns()];
            }
            $query = call_user_func_array([$query, $value['method']], $value['arguments'] ?? []);
        });

        return $query;
    }

这样可以更方便的获取到当前模型查询的builder；方便统计，或者其他自定义查询

**Comment by jqhph** [comment]
这个方法可能会影响模型的其他使用，造成意想不到的后果，建议你自定义数据仓库，然后重写这个get方法即可。
