### ISSUE TITLE
$form->isCreating()和$form->isEditing()点击编辑时一直为true

### ISSUE THREAD

**Issue by zhaohongrui** [jqhph/dcat-admin#1008]
- Laravel Version: 5.8
- PHP Version: 7.4,1
- Dcat Admin Version: v2.0.16-beta

### $form->isCreating()和$form->isEditing()点击编辑时一直为true，编辑按钮重新append的,但是按路由来的不会有问题
![image](https://user-images.githubusercontent.com/33904482/105631249-854e5a80-5e88-11eb-9a48-2847f353c4f3.png)
![image](https://user-images.githubusercontent.com/33904482/105631278-b595f900-5e88-11eb-94a2-d95e1b5a8f32.png)

![image](https://user-images.githubusercontent.com/33904482/105631392-3ead3000-5e89-11eb-8082-1772b65d3e4f.png)

**Comment by jqhph** [comment]
表单代码需要写在闭包里面才能生效

**Comment by zhaohongrui** [comment]
> 表单代码需要写在闭包里面才能生效

好的，谢谢
