### ISSUE TITLE
同页面多个 Grid 不支持多个快捷创建

### ISSUE THREAD

**Issue by xiaogezzz** [jqhph/dcat-admin#1012]
- Dcat Admin Version: 1.7.9

### Description:
如果在同一个页面在多个 Grid 中同时使用快捷创建 `quickCreate` 时会出现提交事件被覆盖的情况，包括快捷创建表单 `action url`  只能为第一个快捷创建的 url 。 

更正：查看源代码后原因是快捷创建表单没有自己的独立的类选择器，建议为每个表单添加和 `button` 相同的 `uniqueName`

**Comment by jqhph** [comment]
当页面存在多个表格时需要给`grid`设置不同名称

```php
$grid->setName('xxx');
```

**Comment by xiaogezzz** [comment]
> 当页面存在多个表格时需要给`grid`设置不同名称
> 
> ```
> $grid->setName('xxx');
> ```

好的感谢回复已解决😂
