### ISSUE TITLE
关联数据表的排序问题

### ISSUE THREAD

**Issue by pkkbkraa** [jqhph/dcat-admin#1014]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.16

### Description:
对关联资料做排序会没有反应
例：
return Grid::make(new Product(['category']), function (Grid $grid) {
    $grid->column('category.name'))->sortable();
});

Model的belongsTo已经有写好了

**Comment by jqhph** [comment]
无法重现，你可以看下sql自己排查一下

**Comment by jqhph** [comment]
确实有问题，`v2.0.20-beta`已修复这个问题，其他版本需要先with
```php
$grid->model()->with('...');
```
