### ISSUE TITLE
「問題」$form->date 如何設定組件可選範圍以及默認值？

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#1015]
- Dcat Admin Version: 2.0.x-dev

### Description:
eg. 日期選擇組件只可選擇 2000年 ~ 至今，且用戶點開的可以選擇的起始值為 2002 年，要如何實現呢？

**Comment by jqhph** [comment]
参考文档 https://getdatepicker.com/4/

**Comment by faydanube** [comment]
Thanks a lot!
