### ISSUE TITLE
行内编辑，对关联表的字段使用 radio 时，保存不生效

### ISSUE THREAD

**Issue by zhou0818** [jqhph/dcat-admin#1016]
- Laravel Version: 8.21
- PHP Version: 7.4
- Dcat Admin Version: 2.0.16-beta

### Description:

行内编辑对关联表使用 `radio` 时，保存无法生效。只有对当前表的字段使用时才能保存。只能换成 `select` 了

**Comment by jqhph** [comment]
form表单是否有定义相同字段？
