### ISSUE TITLE
「問題」通過底部的捐助鏈接，進行個人捐助(美元)您是否能收到呢？

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#1017]
![image](https://user-images.githubusercontent.com/8817046/105858089-e9f2ec00-6025-11eb-964a-8f3b43f1502a.png)

**Comment by faydanube** [comment]
![image](https://user-images.githubusercontent.com/8817046/105858045-e0698400-6025-11eb-90c5-4ddb89e14430.png)

**Comment by jqhph** [comment]
感谢支持！心领了，还没绑卡
