### ISSUE TITLE
布局优化

### ISSUE THREAD

**Issue by qingfeng1024** [jqhph/dcat-admin#1019]
- Laravel Version: 6.1.0
- PHP Version: 7.4.1
- Dcat Admin Version: 2.0.16

### Description:
bootstrap4里 如果css类col后面不带数值 ，默认是等分的，这个特性可以加到dcat里面吗，这样就解决了12不能整除某些数的麻烦了。

**Comment by jqhph** [comment]
已有同学提交PR #1018
