### ISSUE TITLE
数据统计卡片继承柱状图卡片时,如只使用柱状图左侧将会有大片空白

### ISSUE THREAD

**Issue by aFUZHOU** [jqhph/dcat-admin#1021]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: 2.0.16

### Description:
数据统计卡片继承柱状图卡片时
如只使用柱状图左侧将会有大片空白
已使用`$this->contentWidth(0,12);`

![image](https://user-images.githubusercontent.com/35911837/105969448-3b9d8400-60c3-11eb-8e84-5220138c3e7d.png)

**Comment by jqhph** [comment]
这个需要自己调整，参考文档图表以及数据卡片章节
