### ISSUE TITLE
模型树tree组件拖动更改排序保存时报SQL insert into错误

### ISSUE THREAD

**Issue by RaneeXu** [jqhph/dcat-admin#1025]
- Laravel Version: 8.16
- PHP Version: 7.3.24
- Dcat Admin Version: 2.0.16

### Description:
模型树tree组件随便拖动某一个节点更改排序后，点击保存时，报insert into错误：
SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value (SQL: insert into `departments` (`updated_at`, `created_at`) values (2021-01-29 00:59:47, 2021-01-29 00:59:47))
这个不是应该update吗？怎么会报insert into错误呢？

### Steps To Reproduce:

Department Model:
~~~php
use Dcat\Admin\Traits\ModelTree;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    use HasFactory, ModelTree;

    protected $fillable = ['parent_id', 'order', 'title', 'description'];
}
~~~

DepartmentController：
~~~php
use App\Models\Department;
use Dcat\Admin\Form;
use Dcat\Admin\Http\Controllers\AdminController;
use Dcat\Admin\Layout\Content;
use Dcat\Admin\Layout\Row;
use Dcat\Admin\Tree;

class DepartmentController extends AdminController
{
  public function index(Content $content)
      {
          return $content
              ->title($this->title)
              ->description(__('admin.list'))
              ->body(function (Row $row) {
                  $tree = new Tree(new Department());
  
                  $tree->disableCreateButton();
                  $tree->disableQuickCreateButton();
                  $tree->disableEditButton();
  
                  $tree->branch(function ($branch) {
                      return "{$branch['id']} - {$branch['title']}";
                  });
                  $row->column(12, $tree);
              });
      }
}
~~~

![01](https://user-images.githubusercontent.com/56422571/106172914-501a7300-61ce-11eb-9b16-e373c68a89cb.JPG)

![02](https://user-images.githubusercontent.com/56422571/106173929-74c31a80-61cf-11eb-92b7-fe084c123c32.JPG)
![03](https://user-images.githubusercontent.com/56422571/106173938-78ef3800-61cf-11eb-9cd2-2445a17f48b5.JPG)

**Comment by jqhph** [comment]
你的表单是否有事件回调？

**Comment by fplun** [comment]
怎么解决的
