### ISSUE TITLE
[问题]如何在新增页面中手动更新HasMany()表单组件

### ISSUE THREAD

**Issue by a157147899** [jqhph/dcat-admin#1026]
- Laravel Version: 8.20.1
- PHP Version: 7.3.5
- Dcat Admin Version: 2.0.16-beta

### Description:
如截图在一个新增表单页面中使用了HasMany()->UseTable()组件，因为这个关系数据使用到了map组件，所需的数据比较复杂，所以又使用了表单弹窗来新增这个关系数据。

需求：在表单弹窗新增关系数据后需回显到HasMany()组件上
问题：表单弹窗中新增后，如何将数据**回传到新增表单中并更新**HasMany()组件？
尝试：查看了API可以通过HasMany()->Value()来手动更新，但目前不知如何回传和更新数据。

新增页面：
![image](https://user-images.githubusercontent.com/1812136/106338687-4fcac680-62f9-11eb-84df-c6f4b08150f7.png)

新增页面中的表单弹窗：
![image](https://user-images.githubusercontent.com/1812136/106338934-f1521800-62f9-11eb-84fe-664fbb3ac452.png)

**Comment by jqhph** [comment]
看你的hasMany表单字段不多，建议在弹窗表单新增成功后写`js`触发回显操作，比如手动触发`hasMany`按钮的点击事件
