### ISSUE TITLE
$form设置渲染类实例时，无法获取getKey()

### ISSUE THREAD

**Issue by korykim** [jqhph/dcat-admin#1029]
- Laravel Version: 8.12
- PHP Version: 8.0
- Dcat Admin Version: v2.0.16-beta

### Description:
```
$form->text('title');
$form->selectTable('to')
            ->title('选择用户')
            ->dialogWidth('50%') // 弹窗宽度，默认 800px
            ->from(BuyerPeopleTable::make(['id'=>$form->getKey()])) // 设置渲染类实例，并传递自定义参数
            ->model(BuyerPeopleTableAdministrator::class, 'id', 'name'); // 设置编辑数据显示
```

### Steps To Reproduce:
- 在这个代码中 ['id'=>$form->getKey()] 传递过去后是 null。并非是 ResourceId。
还有就是如何可以获取到 $form->text('title'); 值呢？

**Comment by jqhph** [comment]
1.需要写在闭包中

```php
return new Form(new Model, function ($form) {
    $id = $form->getKey();
});
```

2.参考文档表单事件 `$title = $form->input('title');`

**Comment by korykim** [comment]
> ```
> $id = $form->getKey();
> ```



> $form->input('title')

原因找到了。因为我是在create的时候获取`$form->getKey()`，在这个时候是没办法获取到的。只有创建完成后编辑时才能获取到！
那么新的问题来了，如何在create时可以获取到`$form->model()->title`呢？

**Comment by jqhph** [comment]
$form->model() 是编辑数据，create的时候肯定获取不到

**Comment by korykim** [comment]
> $form->model() 是编辑数据，create的时候肯定获取不到

##找到解决方案
- 使用JS写入Cookie值，再用[BuyerPeopleTable]获取Cookie值，来达到create时传递参数。
- 使用JS fetch方法给后台发送保存到数据表，[BuyerPeopleTable]再查询表获取参数。
