### ISSUE TITLE
Laravel observer not working

### ISSUE THREAD

**Issue by mintzhao** [jqhph/dcat-admin#1031]
- Laravel Version: 7.29
- PHP Version: 7.2
- Dcat Admin Version: 2.x

### Description:
我使用了observer,也注册了，但是没起作用，用saved事件是可以的。

但是还是想用observer。

**Comment by jqhph** [comment]
贴下代码看看

**Comment by mintzhao** [comment]
这怎么贴呢？

php artisan make:observer Models\xxxmodel

然后在AppServiceProvider里的register注册 xxxModel->observe(xxxxObserver::class)

**Comment by mintzhao** [comment]
应该是使用了EloquentRepository，在中间屏蔽了。

我如何在model里统一定义事件呢？有可能不只在Form里修改

**Comment by mintzhao** [comment]
在boot里，知道了
