### ISSUE TITLE
Grid Batch Action fail to return selected ID

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#1032]
Laravel Version: 8
PHP Version: 8
Dcat Admin Version: 2.x

### Description:

`class BatchApprove extends BatchAction
{

    protected $title = 'Approve';

    protected $id;

    public function render()
    {
        $form = BatchUpdateShipmentStatusForm::make()->payload([
            'id' => $this->getKey(),
            'status' => 1
        ]);

        return Modal::make()
            ->lg()
            ->title($this->title)
            ->body($form)
            ->button($this->title);

    }

    public function authorize($user): bool
    {

        if (!can('shipment-approve')) {
            return false;
        }

        return true;

    }

}`

I am unable to pass selected **id** to the payload. The $this->getKey() don't return the selected ids

**Comment by jqhph** [comment]
```php
<?php

namespace App\Admin\Actions\Grid;

use App\Admin\Forms\ResetPassword as ResetPasswordForm;
use Dcat\Admin\Widgets\Modal;
use Dcat\Admin\Grid\BatchAction;

class BatchResetPassword extends BatchAction
{
    protected $title = '修改密码';

    public function render()
    {
        // 实例化表单类
        $form = ResetPasswordForm::make();

        return Modal::make()
            ->lg()
            ->title($this->title)
            ->body($form)
            // 因为此处使用了表单异步加载功能，所以一定要用 onLoad 方法
            // 如果是非异步方式加载表单，则需要改成 onShow 方法
            ->onLoad($this->getModalScript())
            ->button($this->title);
    }

    protected function getModalScript()
    {
        // 弹窗显示后往隐藏的id表单中写入批量选中的行ID
        return <<<JS
// 获取选中的ID数组
var key = {$this->getSelectedKeysScript()}

$('#reset-password-id').val(key);
JS;
    }
}
```
