### ISSUE TITLE
VUE自定义页面可以使用吗？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1034]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

自定义页面可以使用vue吗？可以的话 希望以后能增加文档参考 谢谢。

**Comment by jqhph** [comment]
可以，参考文档自定义页面章节

**Comment by shunhua** [comment]
> 可以，参考文档自定义页面章节

可以实现效果与默认列表页一样吗？

**Comment by jqhph** [comment]
可以，看你对前端的熟悉程度

**Comment by shunhua** [comment]
> 可以，看你对前端的熟悉程度

我现在主要是疑惑在vue页面中怎么使用 $grid的相关属性 ，比如各种按钮、查询过滤、分页等

**Comment by jqhph** [comment]
你用过vue吗？我建议你先去学习一下vue，用vue写写东西

**Comment by shunhua** [comment]
> > 可以，看你对前端的熟悉程度
> 
> 我现在主要是疑惑在vue页面中怎么使用 $grid的相关属性 ，比如各种按钮、查询过滤、分页等

我看了相关文档 https://learnku.com/docs/dcat-admin/2.x/custom-page/8473
好像里面介绍的只有使用流程，没有相关属性使用的介绍

**Comment by shunhua** [comment]
> 你用过vue吗？我建议你先去学习一下vue，用vue写写东西

我的意思是 @include('admin::grid.table-toolbar')

    {!! $grid->renderFilter() !!}

    {!! $grid->renderHeader() !!} 这些属性写法，不是vue ，是Dcat中的属性
