### ISSUE TITLE
自定义页面分页无效

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1035]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
http://103.39.211.179:8080/admin/grid/custom?_view_=list&per_page=10&page=1
demo地址

**Comment by jqhph** [comment]
这个是假数据，其实没有分页功能

**Comment by shunhua** [comment]
> 这个是假数据，其实没有分页功能

哦哦 我现在想实现自定义页面跟默认的列表页一样 该怎么实现呢？能实现吗？
