### ISSUE TITLE
在Dcat admin中有类似消息弹出吗？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1036]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
类似laravel-admin中的这种
$error = new MessageBag([
      'title'   => '提示',
      'message' => $error,
  ]);
  return back()->with(compact('error'));

**Comment by shunhua** [comment]
> * Laravel Version: #.#.#
> * PHP Version: #.#.#
> * Dcat Admin Version: #.#.#
> 
> ### Description:
> 类似laravel-admin中的这种
> $error = new MessageBag([
> 'title' => '提示',
> 'message' => $error,
> ]);
> return back()->with(compact('error'));
> 
> ### Steps To Reproduce:

admin_alert('更新成功', 'success'); ？？

**Comment by shunhua** [comment]
Admin::script(
                    <<<SCRIPT
                    admin_toastr('新报数据');
                    
        SCRIPT
        );    
script中可以使用吗？

**Comment by jqhph** [comment]
参考文档帮助函数

**Comment by shunhua** [comment]
Dcat 中除了Dcat.reload，还有没有局部刷新的方法



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jiang Qinghua <notifications@github.com&gt;
发送时间: 2021年2月3日 17:14
收件人: jqhph/dcat-admin <dcat-admin@noreply.github.com&gt;
抄送: bryant <2399315737@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[jqhph/dcat-admin] 在Dcat admin中有类似消息弹出吗？ (#1036)

**Comment by jqhph** [comment]
没有了

**Comment by shunhua** [comment]
哦哦
