### ISSUE TITLE
如何让其它设备上的 Session 失效？

### ISSUE THREAD

**Issue by izqx** [jqhph/dcat-admin#1037]
- Laravel Version: 6.20.16
- PHP Version: 8.0.1
- Dcat Admin Version: 2.0.16

### Description:
在Laravel的文档中有 **让其它设备上的 Session 失效** 的方法 **Auth::logoutOtherDevices($password);**
在Dcat Admin中好像没有直接提供类似的方法，所以想有没有啥简单的方法实现此功能

### Steps To Reproduce:
同一个账号在两个浏览器上登录后一个修改密码后另一个没有自动退出，还可以使用。
个人觉得有点不太合理，应该修改密码后其他设备登录失效才对。

**Comment by jqhph** [comment]
试试
```php
Admin::guard()->logoutOtherDevices();
```

**Comment by izqx** [comment]
> 
> 
> 试试
> 
> ```
> Admin::guard()->logoutOtherDevices();
> ```

我这行不通，web组里的中间件也取消注释了，执行后数据库的密码加密后的值会变化，其他浏览器账号都没有退出

**Comment by izqx** [comment]
好了，此问题终结，自己搞出来了😀

**Comment by TELstatic** [comment]
@izqx 请教下实现原理 Admin::guard()->logoutOtherDevices(); 我这边也没用
