### ISSUE TITLE
dcat 中使用Dcat.info，总是出现多条？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1038]
- Laravel Version: 8.5.2
- PHP Version: 7.4.1
- Dcat Admin Version: 1.7.8

### Description:
结合使用 Pusher
Dcat.info('您有新的数据上报('+data+')');
![image](https://user-images.githubusercontent.com/11988030/106838028-7d878500-66d6-11eb-9844-3501bb148281.png)
这个总是出现多条，多出的是之前的消息，这个能每次弹出之前把以前旧的先清除掉吗？或者有没有解决方案

**Comment by jqhph** [comment]
有防抖功能
```js
var alert = Dcat.helpers.debounce(function (msg) {
        Dcat.info(msg);
 }, 500)

alert('上报');
```

**Comment by shunhua** [comment]
> 有防抖功能
> 
> ```js
> var alert = Dcat.helpers.debounce(function (msg) {
>         Dcat.info(msg);
>  }, 500)
> 
> alert('上报');
> ```

我试了 效果一样 还是一直累加的条数显示

**Comment by jqhph** [comment]
自己调整延时时间

**Comment by shunhua** [comment]
我在想 是不是因为pusher 的监听原因啊？
`Admin::script(
                    <<<SCRIPT
                    Pusher.logToConsole = true;

                    var pusher = new Pusher('xxxxxx', {
                    cluster: 'ap1'
                    });

                    var channel = pusher.subscribe('my-channel');
                    channel.bind('my-event', function(data) {
                    // alert(JSON.stringify(data));
                    var alert = Dcat.helpers.debounce(function (msg) {
                            Dcat.info(msg);
                    }, 500)
                    
                    alert('您有新的数据上报('+data+')');
                    //Dcat.info('您有新的数据上报('+data+')');
                    Dcat.reload()
                    });
                    
        SCRIPT
        );    `

**Comment by shunhua** [comment]
> 自己调整延时时间

延迟时间？？哪个的 目前没设置时间

**Comment by jqhph** [comment]
你把500改成3000

**Comment by shunhua** [comment]
> 你把500改成3000

改了  还是一样的多条，好疑惑啊

**Comment by jqhph** [comment]
那不能用防抖功能解决了，用layer弹窗提示吧自己百度用法

**Comment by shunhua** [comment]
> 那不能用防抖功能解决了，用layer弹窗提示吧自己百度用法

嗯嗯 dcat 中 有没有哪个辅助函数弹出消息 自动消失的，或者消息显示页面上的辅助函数

**Comment by shunhua** [comment]
> > 那不能用防抖功能解决了，用layer弹窗提示吧自己百度用法
> 
> 嗯嗯 dcat 中 有没有哪个辅助函数弹出消息 自动消失的，或者消息显示页面上的辅助函数

Dcat.info   Dcat.success等等 还有其他的方法可以调用吗？文档上没看到呢

**Comment by jqhph** [comment]
参考JS组件

**Comment by shunhua** [comment]
> 参考JS组件

嗯 好的
