### ISSUE TITLE
grid filter使用select组件ajax加载无效

### ISSUE THREAD

**Issue by abovesky** [jqhph/dcat-admin#1039]
- Laravel Version: 8.15
- PHP Version: 7.4
- Dcat Admin Version: v2.0.16-beta

### Description:
表格筛选使用select组件ajax()不加载数据
`$filter->equal('column')->select('api/users');`

**Comment by jqhph** [comment]
ajax要输入至少1个字符串才会请求接口

**Comment by otwin** [comment]
试试这样写：
$filter->equal('column')->select()->ajax('api/users');
