### ISSUE TITLE
表单文件字段删除时，由于数据库字段不允许为空，在做修改删除文件后，会报无法更新字段为null错误

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1042]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

表单修改时，进行文件删除时，由于数据库文件字段不允许为空，在删除文件后，会报无法更新字段为null错误，请问这个如何解决，如何在删除时，设置字段为空字符串而不是null？

**Comment by jqhph** [comment]
参考 https://learnku.com/articles/44386

**Comment by dmskys** [comment]
非常感谢！
