### ISSUE TITLE
使用markdown之后，无法正常显示

### ISSUE THREAD

**Issue by YangGuu** [jqhph/dcat-admin#1047]
- Laravel Version: 7.0
- PHP Version: 7.3
- Dcat Admin Version: v2.0.17-beta

### Description:
本地正常，部署至服务器之后，进入新增，编辑页面报错
create:389 Uncaught SyntaxError: Unexpected token '<'

![Xnip2021-02-07_14-04-32](https://user-images.githubusercontent.com/57345469/107138150-a36a8f00-694d-11eb-9a6c-a4e1d76c5ec5.jpg)

**Comment by jqhph** [comment]
贴下代码看看

**Comment by YangGuu** [comment]
protected function form()
    {
        return Form::make(new News(), function (Form $form) {
            $form->display('id');
            $form->text('title');
            $form->textarea('describe');
            $form->image('cover')->uniqueName()->autoUpload();
            $form->select('tag')->options([1 => '行业新闻',2 => '公司动态']);
            $form->markdown('content');

            $form->display('created_at');
            $form->display('updated_at');

        });
    }

**Comment by jqhph** [comment]
自定义 @markdown 模板标签产生冲突
