### ISSUE TITLE
dcat-admin 2.0.17beta 进行路由缓存出错！

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1050]
执行命令：php artisan route:cache
 Unable to prepare route [users] for serialization. Another route has already been assigned name [dcat.admin.users.index].

**Comment by jqhph** [comment]
是否使用了多应用？

**Comment by dmskys** [comment]
嗯 使用了api和后台管理端不同的域名绑定

**Comment by jqhph** [comment]
在子应用路由文件中指定路由别名的前缀

```php
Route::group(['as' => '别名前缀'], function () {

})
```

**Comment by dmskys** [comment]
thanks
