### ISSUE TITLE
自定义创建的页面导入问题

### ISSUE THREAD

**Issue by korykim** [jqhph/dcat-admin#1051]
- Laravel Version: 8.12
- PHP Version: 8.0
- Dcat Admin Version: v2.0.16-beta
### Description:
我在`App/Admin`目录下创建了`Ext`目录，并在该目录下创建了`Controllers`和`views`目录。

├─Actions
│  ├─form
│  └─grid
├─Controllers
├─Ext
│  ├─Controllers
│  └─views
├─Metrics
│  └─Examples
├─Renderable
└─Repositories

- 在`views`目录下创建了`mypage.blade.php`,代码如下：
```
<div class="my-class">
    <h3>my page</h3>
</div>


<script init=".my-class">
    // js代码也可以放在模板里面
    console.log('过年了!!!');

    // $this.on('click', function () {
    // ...
    // });
</script>


```
- 在`Controllers`目录下创建了`MyPage.php`,代码如下：
```
<?php

namespace App\Admin\Ext\Controllers;

use Illuminate\Contracts\Support\Renderable;


class MyPage implements Renderable
{
    public function render()
    {
        
        return admin_view(在这里怎么指定上面的views目录下的mypage);
    }
}


```

#### 我把文件放到`vendor/dcat/laravel-admin/resources/views`的pages目录下，可以正常导入
- `return admin_view('admin::pages.mypage');` 
#### 但这不是我想要的，我想导入我自定义目录下的页面文件。

**Comment by jqhph** [comment]
你这种属于自定义视图目录，需要注册laravel的视图namepace

```php
View::addNamespace('test', __DIR__.'/../views');
```

**Comment by korykim** [comment]
> 你这种属于自定义视图目录，需要注册laravel的视图namepace
> 
> ```
> View::addNamespace('test', __DIR__.'/../views');
> ```

非常感谢！
