### ISSUE TITLE
發現有的時候會一直轉圈圈，部分功能無法正常使用

### ISSUE THREAD

**Issue by slps970093** [jqhph/dcat-admin#1052]
- Laravel Version: 8.27.0
- PHP Version: 7.4
- Dcat Admin Version: 1.7.9

### Description:

當我嘗試點選其他頁面的功能時，有時候會出現 新增 功能無法正常使用，但操作內的功能大多都正常，若發現無法正常使用後 按下重新整理即可正常操作
![圖片](https://user-images.githubusercontent.com/8385770/107619123-a4712880-6c8d-11eb-9398-37bcc0dd3ff2.png)

**Comment by jqhph** [comment]
出现这个报错可能是没按步骤升级，请看版本升级文档；另外可能是浏览器插件影响
