### ISSUE TITLE
上传文件 / 图片后展示时域名的拼接

### ISSUE THREAD

**Issue by wangjikill** [jqhph/dcat-admin#1055]
- Laravel Version: 6.x
- PHP Version: 7.2
- Dcat Admin Version: 2.0.17-beta

### Description:
上传文件 / 图片后展示时域名的拼接
https://learnku.com/docs/dcat-admin/2.x/picture-file-upload/8106#f6f462
参考了这一个章节的帮助手册后，没有看明白，请各位大神提供一个思路。谢谢

### Steps To Reproduce:
1.文件/图片使用自定义上传方法，上传到了独立的文件服务器
2.保存时，只保存文件/图片的路径，不包含服务器地址
3.Grid 、Detail 和 Form 展示时，如何拼接服务器地址

**Comment by jqhph** [comment]
需要参考laravel文件存储功能文档使用
```php
class User extends Model
{
    public function getAvatar()
    {
        if (! $this->avatar) {
            return;
        }

        return Storage::disk('admin')->url($this->avatar);
    }
}
```
使用
```php
$grid->column('avatar')->display(function () {
    return $this->getAvatar();
})->image();
```

**Comment by wangjikill** [comment]
谢谢。目前我是这样处理的

`
$grid->column('img')->image('http://xxx.com');
$show->img()->image('http://xxx.com');

//config/filesystems.php 下 disks.admin配置为
'admin' => [
            'driver'     => 'local',
            'root'       => public_path('uploads'),
            'visibility' => 'public',
            'url'        => env('IMAGE_SERVER_URL', 'http://xxx.com'),
        ],

//表单中，自动可带上服务器头
$form->image('img')->url('upload/images')
`
