### ISSUE TITLE
grid width 無效

### ISSUE THREAD

**Issue by 15118035159** [jqhph/dcat-admin#1056]
- Laravel Version: 7.30
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.17 - beta

### Description:
![image](https://user-images.githubusercontent.com/48081338/108325084-a8f48e80-7203-11eb-8a97-f53bfe935f08.png)
![image](https://user-images.githubusercontent.com/48081338/108325108-aeea6f80-7203-11eb-8d64-9f874023cc73.png)

**Comment by itliusha** [comment]
应该是把订单编号当成一个字符处理了，一个字符没完时不会换行造成的，你可以利用display方法自定义显示样式
`$grid->column('order_no')->display(function($order) {
    return str_limit($order, 5, '...');
});`
闭包里面还可以直接返回HTML代码，这样就可以随心所欲的控制了
