### ISSUE TITLE
上传文件成功，删除文件时报错 Uncaught TypeError: a.request.delete is not a function

### ISSUE THREAD

**Issue by itliusha** [jqhph/dcat-admin#1058]
- Laravel Version: 8.12
- PHP Version: 7.3
- Dcat Admin Version: v2.0.17-beta

### Description: 上传成功后，删除文件时前端报错，具体错误如下：

![image](https://user-images.githubusercontent.com/37198584/108387265-643f1680-7248-11eb-948e-ebffff651ec7.png)

![image](https://user-images.githubusercontent.com/37198584/108387743-d7488d00-7248-11eb-9e29-b24a5b29e98d.png)

**Comment by jqhph** [comment]
重新发布资源并清理浏览器缓存

**Comment by itliusha** [comment]
> 重新发布资源并清理浏览器缓存

你好，经过实验还是不行，换浏览器，把静态资源包删除重新发布都试了。结果已变不变😁
在向file表单添加了relainable方法后，不在报错，点击删除按钮页面上的dom对应删除了，但服务器资源无法删除。
`$form->file('file')->retainable();`

因此我有一个猜想，会不会是上传成功后后台返回路径有问题导致的。

![image](https://user-images.githubusercontent.com/37198584/108581716-36ea8980-736a-11eb-9c9e-612ea2e639a6.png)

**Comment by jqhph** [comment]
确实有问题，已修复，今晚会发布新版本

**Comment by itliusha** [comment]
> 确实有问题，已修复，今晚会发布新版本

好的。辛苦！！
