### ISSUE TITLE
apexcharts 图表dataLabels 如何设置格式化formatter 百分比展示数据

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1060]
apexcharts 图表dataLabels 如何设置格式化formatter
设置如下配置无效：
 'dataLabels' => [
                    'enabled' => true,
                    'offsetX' => -6,
                    'formatter' => function ($val,$options) {
                        return $val . '%';
                    }
                ],

**Comment by jqhph** [comment]
```php
use Dcat\Admin\Support\JavaScript;

'dataLabels' => [
'enabled' => true,
'offsetX' => -6,
'formatter' => JavaScript::make(
    <<<JS
function (val, options) {
return val +'%';
}
JS
)
],
```

**Comment by dmskys** [comment]
非常感谢
