### ISSUE TITLE
2.x文档中Grid的用法无效，并且全局搜索php无此方法

### ISSUE THREAD

**Issue by 15118035159** [jqhph/dcat-admin#1062]
- Laravel Version: 7.30
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.17 - beta

### Description:
![image](https://user-images.githubusercontent.com/48081338/108584429-512d6300-737c-11eb-91dd-a8d009580d7e.png)
![image](https://user-images.githubusercontent.com/48081338/108584436-715d2200-737c-11eb-8a41-bafc4a31d1d5.png)

**Comment by jqhph** [comment]
这个功能已经废弃了，我更新下文档
