### ISSUE TITLE
select下拉选框如何实时获取当前选中的value值？

### ISSUE THREAD

**Issue by itliusha** [jqhph/dcat-admin#1063]
- Laravel Version: 8.12
- PHP Version: 7.3
- Dcat Admin Version:  v2.0.17-beta

### Description: 
select选框切换时如何实时获value值。
我的业务逻辑是这样的：根据分类字段选择的不同值来获取分类表对应的size的值，此值是用来限定上传图片时图片长宽尺寸的，截图如下：
![image](https://user-images.githubusercontent.com/37198584/108587678-fc93e300-738f-11eb-87ce-884a46563deb.png)

获取select值的时机不在creating/created/submitted/saving/saved......之列，故事件没法用了。
翻遍了文档，就是获取不到select的value, 难道是用js获取吗？果真这样是否更复杂了呢？百思不得解，求教？

**Comment by jqhph** [comment]
想要实时获取只能通过js获取，监听change事件

**Comment by itliusha** [comment]
> 想要实时获取只能通过js获取，监听change事件

这样的话就直接定义一个H5的验证器进行图片上传验证了。我想着我描述的这个业务逻辑有没有现成的方法可解决，感觉挺实用的
