### ISSUE TITLE
when函数控制动态显示字段的问题

### ISSUE THREAD

**Issue by dds813** [jqhph/dcat-admin#1066]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
![image](https://user-images.githubusercontent.com/23622494/108717464-43ccd000-7558-11eb-97fb-4e73dc939e89.png)

如图所示，当使用when字段时，如果每个type控制的都是同一个字段，当type==1时answer为radio选项，当type==2时，answer为checkbox选项，当type==3时，answer为true or false，由于when实际上只是使用了display：none来控制字段的动态显示，这样导致当type==1时其实页面上还是有当type==2和type==3时的form内容，最后提交的answer始终都是type==3时候的answer,这个when只是实现了显示上的动态，但是逻辑上还是没法满足需求

**Comment by jqhph** [comment]
是的，不能使用相同的字段名，`when`只是动态控制表单显示

**Comment by jqhph** [comment]
逻辑上的稍稍变通就能满足你的需求，交换变量总会吧
