### ISSUE TITLE
树状表格怪异现象——title->tree()不显示字段内容

### ISSUE THREAD

**Issue by itliusha** [jqhph/dcat-admin#1067]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: v2.0.19-beta

### Description:
原始字段 ’name‘
`
 protected $titleColumn = 'name';
$grid->title->tree();`
按照此法设置后，title字段内容不显示，如图：
![image](https://user-images.githubusercontent.com/37198584/108800090-2ab23680-75cd-11eb-9483-0c5dd2f58402.png)

修改为：`$grid->column('name')->tree(true);`后显示正常，怪异，这是BUG吗？隐约记得在使用 V1.7.*的时候也出现过类似问题
![image](https://user-images.githubusercontent.com/37198584/108800219-87155600-75cd-11eb-900e-c8c7b828f3b8.png)

**Comment by jqhph** [comment]
你的理解有误，下面的用法才是正确的

**Comment by itliusha** [comment]
> 你的理解有误，下面的用法才是正确的

OK，多谢！！
可不可以将文档的表述修改一下，这一块刚接触的时候确实不注意，一波操作下来还不报错，以为合适了，结果就出现这个问题，自己还不知怎么回事；还有tree(true/false)的值的文档表述，感觉理解上有些歧义，刚才看issues的时候发现，别的人也有理解有误的。
