### ISSUE TITLE
升级到2.0.19后报与规则不匹配

### ISSUE THREAD

**Issue by hongbinhsu** [jqhph/dcat-admin#1070]
- Laravel Version: 8.29.0
- PHP Version: 8.0.1
- Dcat Admin Version: 2.0.19-bate

### Description:
使用 regex:/^[a-zA-Z0-9_-]{4,16}$/
输入 systen_config  报与规则不匹配；未来使用Dcat Admin版本前是正常的

**Comment by jqhph** [comment]
贴下代码看看

**Comment by hongbinhsu** [comment]
> 贴下代码看看
