### ISSUE TITLE
树状表格删除子栏目时跳转到空白页面

### ISSUE THREAD

**Issue by itliusha** [jqhph/dcat-admin#1071]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: v2.0.19-beta

### Description:
树状表格删除子栏目时跳转到子栏目的页面
`URL::  /goods-categories?_children_page_54=1&_depth_=1&_parent_id_=54`
![image](https://user-images.githubusercontent.com/37198584/108974233-3a5e7780-76c0-11eb-9575-2015577c8ee9.png)

![image](https://user-images.githubusercontent.com/37198584/108974119-19962200-76c0-11eb-92a4-a50bf7962f59.png)

**Comment by jqhph** [comment]
感谢反馈，已修复，可先更新到开发版本

```php
composer require dcat/laravel-admin:"2.0.x-dev"
```
