### ISSUE TITLE
json表单是否支持表头key/value翻译

### ISSUE THREAD

**Issue by itliusha** [jqhph/dcat-admin#1074]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version:  v2.0.19-beta

### Description:
json表单是否支持表头key/value翻译呢？试了一下惯例，在翻译文件里面各种映射没有作用

![image](https://user-images.githubusercontent.com/37198584/109239591-bc5db600-7810-11eb-97dd-d230f56f626d.png)

**Comment by jqhph** [comment]
创建文件`resources/lang/zh_CN.json`，写入
```json
{
    "Key": "xxx",
    "Value": "xxx"
}
```

**Comment by itliusha** [comment]
> 创建文件`resources/lang/zh_CN.json`，写入
> 
> ```json
> {
>     "Key": "xxx",
>     "Value": "xxx"
> }
> ``多谢！
