### ISSUE TITLE
上传到服务器后，路由文件内容读取不到了

### ISSUE THREAD

**Issue by 99lucky** [jqhph/dcat-admin#1075]
- Laravel Version: 8.18.1
- PHP Version: 7.4.15
- Dcat Admin Version: 2.0.11

### Description:

本地环境是window+phpstudy,nginx，dcat-admin,多后台运行，是可以使用的。打包上传到服务器后dcat-admin的多后台都访问不到，php artisan route:list 查看路由发现dcat-admin的路由找不到，只能看到dcat-admin的api路由，所以后台访问出现了404页面错误，一直没有找到原因，求教。服务器环境是centos8+nginx
服务器上可以看到的路由
| POST     | gears/dcat-api/action                          | Dcat\Admin\Http\Controllers\HandleActionController@handle        |
| POST     | gears/dcat-api/editor-md/upload                | Dcat\Admin\Http\Controllers\EditorMDController@upload            |
| POST     | gears/dcat-api/form                            | Dcat\Admin\Http\Controllers\HandleFormController@handle          |
| POST     | gears/dcat-api/form/destroy-file               | Dcat\Admin\Http\Controllers\HandleFormController@destroyFile     |
| POST     | gears/dcat-api/form/upload                     | Dcat\Admin\Http\Controllers\HandleFormController@uploadFile      |
| GET|HEAD | gears/dcat-api/render                          | Dcat\Admin\Http\Controllers\RenderableController@handle          |
| POST     | gears/dcat-api/tinymce/upload                  | Dcat\Admin\Http\Controllers\TinymceController@upload             |
| POST     | gears/dcat-api/value                           | Dcat\Admin\Http\Controllers\ValueController@handle               |

本机环境里可以看到的路由如下：还有很多
| GET|HEAD                               | gears                                                | App\Admin\Controllers\HomeController@index                       |
| GET|HEAD                               | gears/ads/advertisement                              | App\Admin\Controllers\GgController@index                         |
| POST                                   | gears/ads/advertisement                              | App\Admin\Controllers\GgController@store                         |
| GET|HEAD                               | gears/ads/advertisement/create                       | App\Admin\Controllers\GgController@create                        |
| DELETE                                 | gears/ads/advertisement/{advertisement}              | App\Admin\Controllers\GgController@destroy                       |
| GET|HEAD                               | gears/ads/advertisement/{advertisement}              | App\Admin\Controllers\GgController@show                          |
| PUT|PATCH                              | gears/ads/advertisement/{advertisement}              | App\Admin\Controllers\GgController@update                        |
| GET|HEAD                               | gears/ads/advertisement/{advertisement}/edit         | App\Admin\Controllers\GgController@edit                          |
| POST                                   | gears/ads/position                                   | App\Admin\Controllers\GgPlaceController@store                    |
| GET|HEAD                               | gears/ads/position                                   | App\Admin\Controllers\GgPlaceController@index                    |
| GET|HEAD                               | gears/ads/position/create                            | App\Admin\Controllers\GgPlaceController@create                   |
| GET|HEAD                               | gears/ads/position/{position}                        | App\Admin\Controllers\GgPlaceController@show                     |
| PUT|PATCH                              | gears/ads/position/{position}                        | App\Admin\Controllers\GgPlaceController@update                   |
| DELETE                                 | gears/ads/position/{position}                        | App\Admin\Controllers\GgPlaceController@destroy                  |
| GET|HEAD                               | gears/ads/position/{position}/edit                   | App\Admin\Controllers\GgPlaceController@edit                     |
| GET|HEAD                               | gears/api/topics                                     | App\Admin\Controllers\InformationSpecialController@topics        |
| GET|HEAD                               | gears/auth/extensions                                | Dcat\Admin\Http\Controllers\ExtensionController@index            |
| POST                                   | gears/auth/extensions                                | Dcat\Admin\Http\Controllers\ExtensionController@store            |
| PUT|PATCH                              | gears/auth/extensions/{extension}                    | Dcat\Admin\Http\Controllers\ExtensionController@update           |
| GET|HEAD                               | gears/auth/login                                     | App\Admin\Controllers\AuthController@getLogin                    |
| POST                                   | gears/auth/login                                     | App\Admin\Controllers\AuthController@postLogin                   |
| GET|HEAD                               | gears/auth/logout                                    | App\Admin\Controllers\AuthController@getLogout                   |

**Comment by jqhph** [comment]
是否使用了路由缓存？

**Comment by 99lucky** [comment]
没有使用路由缓存，清除了路由也是遇到的一样的问题，然后直接在服务器上创建多应用也是不能使用，404

**Comment by 99lucky** [comment]
问题解决了，没有认真看文档。多应用是命名的问题。不过，windows下面可以使用，linux下有问题
