### ISSUE TITLE
multipleSelect的load方法传参的时候能否把所有选择的数据都传过去

### ISSUE THREAD

**Issue by ycymycym** [jqhph/dcat-admin#1076]
- Laravel Version: 8.28.1
- PHP Version: 7.3.27
- Dcat Admin Version: v2.0.19-beta

### Description:
目前multipleSelect的load方法导入数据，传参只传最后一次选择的数据，能否把所有选中的数据一起传过去。
另外，radio,checkbox是否考虑也加入load方法？这两个也是经常要用来动态加载数据用的。
还有弹窗的传参怎么传，如果一个select先中一个项，弹窗时怎么把这个值 传进去？
你说的onchange是指自己写JS监听，还是dcat本身有这个方法/？

**Comment by jqhph** [comment]
已修复，可以先更细开发分支版本 

```
composer require dcat/laravel-admin:"2.0.x-dev"
```
