### ISSUE TITLE
Dcat自带模型构造函数的问题

### ISSUE THREAD

**Issue by Totn** [jqhph/dcat-admin#1078]
- Laravel Version: 6.x
- PHP Version: 7.2
- Dcat Admin Version: 2.x

### Description:
Dcat的自定义模型如 `Models/Administrator`，`Models/Menu`等，其构造函数的处理不是很恰当
以Administrator为例，其构造函数为
```php
    public function __construct(array $attributes = [])
    {
        $connection = config('admin.database.connection') ?: config('database.default');

        $this->setConnection($connection);

        $this->setTable(config('admin.database.menu_table'));

        parent::__construct($attributes);
    }

```
这样的写法对于覆写造成了麻烦，举例：

```php

Class NewAdministrator extends Administrator
{
    public function __construct(array $attributes = [])
    {
        $this->setTable('new_admin_users');

        parent::__construct($attributes);
    }
}

```
如果这样，显然是不合理的，`$this->table`的值会被 `parent::__construct`的里值所覆盖，造成
`$this->setTable('new_admin_users');`的操作无效。
目前有效的做法是这样

```php

Class NewAdministrator extends Administrator
{
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable('new_admin_users');
    }
}

```

这样写就有一个隐患，` parent::__construct($attributes);`如果有不可逆操作时，后续的覆写无效。

建议把初始化部分抽离出来，写成这样

```php
    public function __construct(array $attributes = [])
    {
        $this->dcatInit();

        parent::__construct($attributes);
    }
    public function dcatInit()
    {
        $connection = config('admin.database.connection') ?: config('database.default');

        $this->setConnection($connection);

        $this->setTable(config('admin.database.menu_table'));
    }

```

这样后续继承覆写只需要重写`dcatInit()`方法，完美解决`__contruct`方法存在不可逆操作的隐患。

`repository`同理

### Steps To Reproduce:
none

**Comment by jqhph** [comment]
下面这个 `$this->setTable('new_admin_users');` 可以在配置文件修改，不需要在模型中更改

```php
Class NewAdministrator extends Administrator
{
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setTable('new_admin_users');
    }
}
```

**Comment by Totn** [comment]
> 下面这个 `$this->setTable('new_admin_users');` 可以在配置文件修改，不需要在模型中更改
> 
> ```
> Class NewAdministrator extends Administrator
> {
>     public function __construct(array $attributes = [])
>     {
>         parent::__construct($attributes);
> 
>         $this->setTable('new_admin_users');
>     }
> }
> ```

多应用A（原Admin应用）和B（新增应用），在A应用下管理B的用户时，B的`Administrator`模型里的`setTable`必须要覆写，不然实例出来就不是B的`Administrator`而是A的`Administrator`。

**Comment by jqhph** [comment]
好的后续优化一下这个功能

**Comment by jqhph** [comment]
已调整
