### ISSUE TITLE
如何动态生成字段，通过select选择不同的值动态生成对应字段

### ISSUE THREAD

**Issue by itliusha** [jqhph/dcat-admin#1080]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: v2.0.19-beta

### Description:
使用when方法，无法动态获取select的当前值，
利用js的change时间获取到select值，但要怎样生成动态字段呢

**Comment by jqhph** [comment]
动态生成是比较复杂的，不建议这么做，这个没法细说，简单来说就是用js拼接字符串然后append到对应的表单节点里面

**Comment by itliusha** [comment]
现在的需求如下：
栏目表数据结构：
![image](https://user-images.githubusercontent.com/37198584/109459451-c219fc80-7a99-11eb-9609-d55c87a6fab6.png)

现在添加商品时要根据栏目添加商品属性，每个栏目都是可变的，如果不动态生成的话该怎么做呢？

**Comment by jqhph** [comment]
你这个用`when`实现不就行了，字段名变一下，提交的时候再重新赋值
