### ISSUE TITLE
 selecttable弹层回调的时候，能不能加个load，因为很多时候需要用这个动态加载数据。

### ISSUE THREAD

**Issue by ycymycym** [jqhph/dcat-admin#1083]
Laravel Version: 8.28.1
PHP Version: 7.3.27
Dcat Admin Version: v2.0.19-beta

### Description:
 selecttable弹层回调的时候，能不能加个load，因为很多时候需要用这个动态加载数据。

**Comment by jqhph** [comment]
selectTable有个隐藏域表单，可以先自己监听这个hidden表单的change事件实现

**Comment by jqhph** [comment]
已支持这个功能

**Comment by terranc** [comment]
@jqhph 这个load怎么使用？如果selectTable中是用的异步Renderable，要如何将参数动态传进去？
