### ISSUE TITLE
使用 $form->block + $form->row 提交及重置按钮不见了

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#1090]
![截圖 2021-03-08 上午2 36 06](https://user-images.githubusercontent.com/16574141/110250602-14d24780-7fb7-11eb-8cab-11c3973e9063.png)
`protected function form()
    {
        return Form::make(new Discount(), function (Form $form) {
            $form->block(12, function (Form\BlockForm $form) {
                $form->row(function (Form\Row $form) {
                    $form->width(4)->text('min_spending')->default(0)->help('0表示无最低金额限制')->required();
                    $form->width(12)->hidden('discount_for')->value('all');
                });
            });
        });
    }`

**Comment by jqhph** [comment]
文档有
```php
$form->block(8, function (Form\BlockForm $form) {
    // 设置标题
    $form->title('基本设置');

    // 显示底部提交按钮
    $form->showFooter();

    // 设置字段宽度
    $form->width(9, 2);

    $form->column(6, function (Form\BlockForm $form) {
        $form->display('id');
        $form->text('name');
        $form->email('email');
        $form->image('avatar');
        $form->password('password');
    });

    $form->column(6, function (Form\BlockForm $form) {
        $form->text('username');
        $form->email('mobile');
        $form->textarea('description');
    });
});
```

**Comment by kevin700523** [comment]
好的 谢谢！
