### ISSUE TITLE
数据表格 - limit 截取文字功能异常

### ISSUE THREAD

**Issue by shijie1991** [jqhph/dcat-admin#1091]
- Laravel Version: 8.28.1
- PHP Version: 7.4.2
- Dcat Admin Version: v2.0.19-beta

### Description:
数据表格 - 根据条件显示不同的组件

![image](https://user-images.githubusercontent.com/11606404/110280207-66112400-8015-11eb-879a-f5fc2b503283.png)

设置如果是文字情况下截取字符 

默认显示正常 , 点击后文字并未展开 而是 消失了

![image](https://user-images.githubusercontent.com/11606404/110280521-e9cb1080-8015-11eb-8241-3bbf273799f0.png)

**Comment by jqhph** [comment]
已修复，感谢反馈
