### ISSUE TITLE
$form->block + $form->row 左右margin间距有问题

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#1092]
![截圖 2021-03-09 上午2 22 36](https://user-images.githubusercontent.com/16574141/110364362-a1940880-807e-11eb-916e-63995f3b1f99.png)

使用$form->block + $form->row 左右margin间距有问题

**Comment by jqhph** [comment]
贴一下代码看看

**Comment by kevin700523** [comment]
`            $form->block(12, function (Form\BlockForm $form) {
                $form->row(function (Form\Row $form) {
                    $form->width(12)->html(badge_form_title('规则'));
                    $form->width(4)->text('min_spending')->default(0)->help('0表示无最低金额限制')->required();
                    $form->width(12)->hidden('discount_for')->value('product');
                    $form->width(12)->radio('product_type')->options([ 'cate' => '多种商品分类', 'product' => '多种商品',])->default('cate');
                    $form->width(12)->multipleSelect('specific_cate')->options($this->cate)
                    ->saving(function ($value) {
                        return json_encode($value);
                    });
                    $form->width(12)->multipleSelect('specific_product')->options($this->product)->saving(function ($value) {
                        return json_encode($value);
                    });;
                });
            });`

**Comment by jqhph** [comment]
你用的版本是？

**Comment by kevin700523** [comment]
老大 请问这个问题 下个版本会修复吗？

**Comment by jqhph** [comment]
已修复，周末发布新版本，可以先更新开发分支代码，感谢反馈
```
composer require dcat/laravel-admin:"2.0.x-dev"
```
