### ISSUE TITLE
关于管理员页面 同时存在两个编辑按钮的问题

### ISSUE THREAD

**Issue by hkj1994** [jqhph/dcat-admin#1093]
![image](https://user-images.githubusercontent.com/41996511/110427955-798ac080-80e3-11eb-801c-40f2ba2aff82.png)

在 `vendor\dcat\laravel-admin\src\Http\Controllers\UserController.php `代码中 打开快速编辑按钮，但是普通编辑按钮未关闭，漏调用了 ` $grid->disableEditButton();`

![image](https://user-images.githubusercontent.com/41996511/110428026-a212ba80-80e3-11eb-96b9-bcfebfa072ab.png)

如果设计如此，请忽略我的问题。

**Comment by jqhph** [comment]
是的默认是没有禁用普通编辑按钮的
