### ISSUE TITLE
自定义表单后，handle方法仅能接收到表单前3个值，后面的字段和值均无法获取。

### ISSUE THREAD

**Issue by wqsacy** [jqhph/dcat-admin#1096]
- Laravel Version: 5.8
- PHP Version: 7.3
- Dcat Admin Version: ^2.0

### Description:
php artisan admin:form Setting 后，生成表单类，在form方法中，自定义表单，例如：

            // 工作日配置
            $this->checkbox( 'day' , '工作日' )
                 ->options( [
                     1 => '周一' ,
                     2 => '周二' ,
                     3 => '周三' ,
                     4 => '周四' ,
                     5 => '周五' ,
                     6 => '周六' ,
                     7 => '周日' ,
                 ] )
                 ->canCheckAll();

            // 工作时间配置
            $this->timeRange( 'start_time' , 'end_time' , '时间范围' );

            //频率
            $this->range( 'min' , 'max' , '间隔频率' )
                 ->help( '单位：秒' );
            
            ....

可以正确渲染页面，并且可以进行页面操作，但是在保存结果时，通过handle方法，打印 $input，仅仅可以得到前3个表单值，尝试把 range提前到timeRange前，也仅仅能到到range的值，timeRange和之后的值均无法获取。

###得到的值
array:3 [
  "day" => array:1 [
    0 => "1"
  ]
  "start_time" => "01:33:44"
  "end_time" => "17:33:31"
]

**Comment by jqhph** [comment]
请问是2.x哪个版本？

**Comment by jqhph** [comment]
旧版本range后面的表单值确实无法获取到

**Comment by wqsacy** [comment]
@jqhph  反馈：
1.版本确定是 1.7.9
2. range置与表单最后，确实可以获取到值，不过因为我这边的需求，需要使用多个range，看来只能尝试升级到最新的开发版了。
3. 请问2.0的正式版大概的时间点有吗？

**Comment by wqsacy** [comment]
> 旧版本range后面的表单值确实无法获取到

反馈：
1.版本确定是 1.7.9
2. range置与表单最后，确实可以获取到值，不过因为我这边的需求，需要使用多个range，看来只能尝试升级到最新的开发版了。
3. 请问2.0的正式版大概的时间点有吗？
