### ISSUE TITLE
希望增加删除文件时不自动删除保存在数据库中的路径

### ISSUE THREAD

**Issue by Lexluth0r** [jqhph/dcat-admin#1097]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.0.20-beta

### Description:
在页面中删除文件成功时会更新对应的数据库字段，如果数据库字段设置为非空会导致删除失败。
希望在删除文件时不更新数据库只清空页面上的值。

**Comment by Lexluth0r** [comment]
> 文档有
> 
> ```
> $form->file(...)->removable(false);
> ```

那可能 removable 存在bug，使用`removable(false)`后，数据库字段依然被更新

**Comment by jqhph** [comment]
removable就是只清空页面的值

**Comment by Lexluth0r** [comment]
> removable就是只清空页面的值

使用如下代码，页面删除文件时会更新数据库字段，是否为用法错误。如非用法问题请确认是否为bug~
`  $form->image('cover')->maxSize(1024)->required()->autoSave(false)->removable(false);`

**Comment by jqhph** [comment]
代码没有问题，功能也是正常的，没有BUG

**Comment by Lexluth0r** [comment]
找到问题为升级版本没有重新发布静态资源，为使用问题。非常感谢回复。
