### ISSUE TITLE
composer require dcat/laravel-admin:"2.*" -vvv failed

### ISSUE THREAD

**Issue by shanezhiu** [jqhph/dcat-admin#1098]
- Laravel Version: 8.x
- PHP Version:7.4
- Dcat Admin Version:2.x

### Description:
I created a project with command `composer create-project --prefer-dist laravel/laravel roomReservation -vvv`,  and then I run `composer create-project --prefer-dist laravel/laravel roomReservation -vvv`.

I got a error :
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dcat/laravel-admin 2.*, found dcat/laravel-admin[2.0.0-beta, 2.0.1-beta, 2.0.2-beta, 2.0.3-beta, 2.0.4-beta, 2.0.5-beta, 2.0.6-beta, 2.0.7-beta, 2.0.8-beta, 2.0.9-beta, 2.0.10-beta, 2.0.11-beta, 2.0.12-beta, 2.0.13-beta, 2.0.14-beta, 2.0.15-beta, 2.0.16-beta, 2.0.17-beta, 2.0.18-beta, 2.0.19-beta, 2.0.20-beta, 2.0.x-dev] but it does not match your minimum-stability.
```

**Comment by jqhph** [comment]
Add `"minimum-stability": "dev"` to the end of the composer.json

**Comment by shanezhiu** [comment]
> Add `"minimum-stability": "dev"` to the end of the composer.json

It did not work for me.

**Comment by shanezhiu** [comment]
> Add `"minimum-stability": "dev"` to the end of the composer.json

and I got this resolved with running "composer require dcat/laravel-admin:*". But it really a bad choice with any version constraint.
