### ISSUE TITLE
请教一个表格显示其他字段信息的问题

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1099]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
由于运营人员要想在日报表中显示其他表的数据，单日期字段存储格式不一样一个是字符串 Y-m-d 存储，一个是int存储 Ymd,所以无法进行表关联查询，目前想到可以根据当前表日期，去查询其他表的数据进行展示，但是只想到了在字段display中查询，但是很多个字段每次都查询，又觉得不够优雅，请问这个有没有什么好的解决方案？

**Comment by dmskys** [comment]
> 可以用关联模型实现，比如
> 
> ```
> $grid->model()->with('profile');
> 
> $grid->column('profile.avatar');
> ```
我关联模型的字段值不相等，日期一个是2021-03-01 一个是 20210301这种 没办法关联呀

**Comment by jqhph** [comment]
可以重写数据仓库的`get`方法，自己把数据查好组装好返回；也可以在表格相关事件中组装好数据返回

**Comment by dmskys** [comment]
嗯 看来只能用数据仓库了
