### ISSUE TITLE
表格选择器 (selectTable)只能选择一个， 没有多选的弹层选择器吗？

### ISSUE THREAD

**Issue by ycymycym** [jqhph/dcat-admin#1105]
- Laravel Version: 8
- PHP Version: 7
- Dcat Admin Version: 2019

### Description:
表格选择器 (selectTable)只能选择一个，
没有多选的弹层选择器吗？是不是可以出一个multipleSelect 的Table?

**Comment by jqhph** [comment]
有的，`multipleSelectTable`，参考文档表单字段的使用
