### ISSUE TITLE
v2.0.20版本在“编辑”页面中表单验证好像无法使用

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#1107]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: v2.0.20-beta

### Description:
在“编辑”页面中表单验证好像无法使用

**Comment by jqhph** [comment]
代码或环境问题

**Comment by ygcool** [comment]
完整form页面代码：
拿到新增页面中测试，rules验证有效

`protected function form()
    {
        return Form::make(new User(), function (Form $form) {
            if ($form->isEditing()) {
                $form->display('id');
                $form->display('mobile');
                $form->text('nickname');
                $form->password('new_password')->rules(['sometimes', 'bail', 'required', 'alpha_dash', 'min:8', 'max:20'])->help('不改密码就不输入值');
                $form->password('new_asset_password')->rules(['sometimes', 'bail', 'required', 'digits:6'])->help('不改密码就不输入值');
                $form->radio('state')->options($this->state_us);
                $form->hidden('password');
                $form->hidden('asset_password');
            }
            $form->submitted(function (Form $form){
                if ($form->isEditing()) {
                    // 更新登录密码
                    $new_pwd = $form->input('new_password');
                    $form->deleteInput('new_password');
                    if (!empty($new_pwd)) {
                        $form->password = Hash::make($new_pwd);;
                    } else {
                        // 删除用户提交的数据
                        $form->deleteInput('password');
                    }

                    // 更新资金密码
                    $new_asset_pwd = $form->input('new_asset_password');
                    $form->deleteInput('new_asset_password');
                    if (!empty($new_asset_pwd)) {
                        if (!is_numeric($new_asset_pwd) || strlen($new_asset_pwd)) {
                            $form->responseValidationMessages('new_asset_password', '格式错误,6位纯数字');
                        }
                        $form->password = Hash::make($new_asset_pwd);;
                    } else {
                        // 删除用户提交的数据
                        $form->deleteInput('asset_password');
                    }
                }
            });
        });
    }`
