### ISSUE TITLE
hasmany的移除按钮貌似没有起作用

### ISSUE THREAD

**Issue by ringzxw** [jqhph/dcat-admin#1111]
- Laravel Version: 8.31.1
- PHP Version: 7.4
- Dcat Admin Version: 2.0.20-beta

### Description:
表单里面的hasmany的移除按钮貌似没有起作用，保存后没有删除many表里面对应的数据
hasmany的column布局没有起效果

**Comment by jqhph** [comment]
删除操作是提交到后端才进行的，column布局没问题应该是你改过模板导致的
