### ISSUE TITLE
Dcat下面出现莫名其面的js内容？ 是Dcat自带的么？

### ISSUE THREAD

**Issue by mark630235** [jqhph/dcat-admin#1113]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

![image](https://user-images.githubusercontent.com/17892109/111604546-65943c80-8810-11eb-8781-2a00cdad9da9.png)

搭建一个网站，总出现这些js内容， 是Dcat自带的么？  怎么去除？

**Comment by jqhph** [comment]
不是的，dcat没有带这个东西
