### ISSUE TITLE
请教一下，如何在编辑页面设置默认值？

### ISSUE THREAD

**Issue by xiajinjun** [jqhph/dcat-admin#1115]
- Laravel Version: #.#.#
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.*

### Description:
文档中写了：
此方法仅在新增页面有效，如果编辑页面也需要设置默认值，可以参考以下方法
$form->text('xxx')->default('默认值', true);

但是我试了没有用，依然显示的是数据库里面取出的值。

请教一下，如何在编辑页面设置默认值？
谢谢

**Comment by jqhph** [comment]
2.x版本才支持这个功能
