### ISSUE TITLE
在渲染饼状图时出现乱码

### ISSUE THREAD

**Issue by Millyn** [jqhph/dcat-admin#1116]
- Laravel Version: 7.0
- PHP Version: 7.4
- Dcat Admin Version: 1.7.4

### Description:
![image](https://user-images.githubusercontent.com/7987563/111753312-aef89080-88d1-11eb-863f-33e25dbb10c8.png)

### Steps To Reproduce:
Hi ， 请教下。
我们有一个页面有多个饼图，其中一个饼图渲染时出现了乱码。

之前是正常的，现在是突然出现的。

这个饼图里的数据来源是
![image](https://user-images.githubusercontent.com/7987563/111753177-840e3c80-88d1-11eb-8632-063fdb6108ec.png)

**Comment by jqhph** [comment]
检查写入图表的数据是否有问题
