### ISSUE TITLE
Grid 构建表格，开启行内编辑，可进行xss攻击

### ISSUE THREAD

**Issue by szlijia** [jqhph/dcat-admin#1117]
- Laravel Version: 8
- PHP Version: 8
- Dcat Admin Version: 2.0.20-beta

### Description:
如题

### Steps To Reproduce:
一：构建表格时，使用editable开启行内编辑功能
二：输入<script>alert(1)</script>
三：保存

**Comment by jqhph** [comment]
这个需要自行过滤
