### ISSUE TITLE
dcat-admin 里date组件联动select实现问题

### ISSUE THREAD

**Issue by shanezhiu** [jqhph/dcat-admin#1118]
- Laravel Version: 8.32
- PHP Version: 7.4
- Dcat Admin Version: 2.0.20-beta

### Description:

需求描述：

选择指定日期(date组件)，然后根据指定日期生成开始时间和关闭时间。

问题：
1. 我现在能想到的办法是自己写Js, 然后使用Admin::script()方法注入js到页面。

2. 上面这个方式能解决问题，但是存在一个问题是，内部嵌入了JS,无法使用工具本身的一些函数，我的问题是：

dcat-admin本身是否存在监听组建点击，焦点这些方法，尽量不让开发者内嵌js的那种？

**Comment by shanezhiu** [comment]
我翻了dcat-admin文档以及laravel-admin的文档，异步表单联动只对有限地表单组建有效，date组建不在其中。

**Comment by jqhph** [comment]
不存在，内置的联动也是通过`js`实现的，后续会增加更多表单直接的联动

**Comment by shanezhiu** [comment]
好的。
