### ISSUE TITLE
user permissions dialog-tree can not show

### ISSUE THREAD

**Issue by NinoPanic** [jqhph/dcat-admin#1122]
- Laravel Version: 8.31.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.20

### Description:
when I init the application, visit the route `auth/users`, click the **permissions view button** , the dialog-tree modal is always loading.
so I look into the source code of DialogTree.
```
 parentId = v[parentColumn] || '#';
            if (!parentId) {
                parentId = '#';
            } else {
                parentIds.push(parentId);
            }
```
when v[parentColumn] is "0",  we can't  get a "#" value parentId

And 
```
  v['state']['selected'] = true;
```
value true is not working. I tried to set the 'selected' to value 'selected', it works.

btw, same situation exists in dcat-demo and dcat-admin(version 1.7)

thanks for your hard work!

**Comment by jqhph** [comment]
The `JsTree` requires the value of the root node to be "#", so the value of `parent_id` will be converted to "#" when  it is "0"

![image](https://user-images.githubusercontent.com/20312339/112118607-80dbbf00-8bf7-11eb-8945-d58bed59c769.png)

**Comment by NinoPanic** [comment]
```parentId = v[parentColumn] || '#';```
when v[parentColumn] is `'0'`, parentId is `'0'`
but `! parentId` is `false`, so parentId is still '0'

**Comment by jqhph** [comment]
The problem has been fixed, thanks for the report
