### ISSUE TITLE
表单报错没有进行翻译

### ISSUE THREAD

**Issue by 2494911084** [jqhph/dcat-admin#1126]
- Laravel Version: 8.3~
- PHP Version: 7.4
- Dcat Admin Version: 2.*

### Description:
表单报错没有进行翻译

### Steps To Reproduce:
使用的 "overtrue/laravel-lang": "~3.0",  扩展包 ，config设置的是zh_CN , Dcat登录到主界面都翻译成中文了，  之后在表单验证时 显示的是英文，在将'locale' 修改为 'zh-CN',后 Dcat变为英文 Dcat内的表单验证变为中文。

**Comment by LazyBaby** [comment]
这个报错信息还是英文你可以参考laravel-admin的，文档上有说的，或者直接百度，都有答案的
