### ISSUE TITLE
tab 标签如何支持 iframe 打开

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1129]
想在一个导航中，使用tab标签展示页面，然后如果用代码直接生成页面，多个页面的搜索条件会有问题，请问如果构建tab里面使用iframe打开其他控制器页面？或者有更好的方式？

**Comment by dmskys** [comment]
主要是iframe可以保留原来的表格数据记录，可以进行数据对比

**Comment by jqhph** [comment]
参考 #211
