### ISSUE TITLE
Scaffold 不支持pgsql 吗

### ISSUE THREAD

**Issue by liweijie0812** [jqhph/dcat-admin#1130]
- Laravel Version: 8.34.0
- PHP Version: 8.0.3
- Dcat Admin Version: v2.0.20-beta

### Description:
数据使用pgsql13版本，进入Scaffold  页面很慢，要等待很久才进去，数据库表也无法列出

**Comment by jqhph** [comment]
是的，暂不支持

**Comment by chareice** [comment]
什么时候可以支持pgsql?
