### ISSUE TITLE
管理员头像无法修改,上传图片must be an image

### ISSUE THREAD

**Issue by coolert** [jqhph/dcat-admin#1133]
- Laravel Version: 6.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0

### Steps To Reproduce:
管理员头像无法修改，上传图片时提示 头像must be an image，上传的头像是jpg格式大小12kb
![image](https://user-images.githubusercontent.com/18160314/112758594-d3671200-9021-11eb-8d35-b5cf80fb1ef3.png)

**Comment by jqhph** [comment]
这个是`Laravel 5.x`版本`image`规则的`bug`，如果没有升级`symfony/mine`是不会有影响的，解决方法要么升级`laravel`要么降级`symfony/mine`

![Uploading image.png…]()

**Comment by MrJoker1991** [comment]
vendor\laravel\framework\src\Illuminate\Validation\Concerns\ValidatesAttributes.php

line:1014 ,array add 'jpg' can solve this problem

return $this->validateMimes($attribute, $value, ['jpg','jpeg', 'png', 'gif', 'bmp', 'svg', 'webp']);

![jpgerror](https://user-images.githubusercontent.com/26448433/127972466-29283c00-c5f0-4b74-956e-6b17b8d04cd8.png)
