### ISSUE TITLE
使用数据仓库进行表格展示后，进行当前页excel导出，出现bug

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1134]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 最新版本

### Description:
使用下面代码，在展示时没有问题，但是在导出当前页时，而且在第二页的时候，也是获取不到$perPage， $currentPage数据值都为null，导致无法查询数据，问题主要在 $model->makePaginator 时获取不到默认值。希望查看一下
`

public function get(\Dcat\Admin\Grid\Model $model)
    {
        // 当前页数
        $currentPage = $model->getCurrentPage();
        // 每页显示行数
        $perPage = $model->getPerPage();

        $cur_date_start = $model->filter()->input('cur_date.start');
        $cur_date_end = $model->filter()->input('cur_date.end');
        $offset = ($currentPage - 1) * $perPage;

        $data = app(OrderDayReportRepository::class)->pageList($cur_date_start, $cur_date_end, $offset, $perPage);

        return $model->makePaginator(
            $data['total'] ?? 0, // 传入总记录数
            $data['data'] ?? [] // 传入数据二维数组
        );
    }

`

**Comment by jqhph** [comment]
导出时的url参数是？

**Comment by dmskys** [comment]
> 导出时的url参数是？

 这个问题请问能解决吗？

**Comment by jqhph** [comment]
无法复现，只有禁用了分页 $perPage， $currentPage才会获取不到
