### ISSUE TITLE
建议开发一个带选择选择器的文件上传

### ISSUE THREAD

**Issue by Weliam-xin** [jqhph/dcat-admin#1135]
类似于下面截图这样的选择器，方便选择以前上传过的图片、文件或视频
![image](https://user-images.githubusercontent.com/75171868/112845954-0a97fa80-90d8-11eb-967a-daa4a5af56ad.png)

**Comment by jqhph** [comment]
可以参考下这个 https://github.com/deatil/dcat-form-media

**Comment by Weliam-xin** [comment]
好的，非常感谢
