### ISSUE TITLE
未登录menu.js报错,代码生成器无法使用，提示CSRF token mismatch

### ISSUE THREAD

**Issue by deaningo** [jqhph/dcat-admin#1141]
- Laravel Version: 8.0
- PHP Version: 8.0
- Dcat Admin Version: v2.0.21-beta

### Description:
未登录menu.js报错
![image](https://user-images.githubusercontent.com/58157679/113128990-fd504c80-924c-11eb-92f7-d842de228ea5.png)

代码生成器无法使用，提示CSRF token mismatch
![image](https://user-images.githubusercontent.com/58157679/113129071-11944980-924d-11eb-8f33-a506a957f382.png)

**Comment by jqhph** [comment]
已发布`v2.0.22-beta`版本，升级即可
```bash
composer remove dcat/laravel-admin
composer require dcat/laravel-admin:"2.0.22-beta"
php artisan admin:update
```
