### ISSUE TITLE
表单 tags 一次最多只能输入两个单词

### ISSUE THREAD

**Issue by vavo-cake** [jqhph/dcat-admin#1144]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
请问如何复现？

**Comment by vavo-cake** [comment]
> 请问如何复现？

比如我想加个标签内容是 `laravel is art`，但是当我在 `is` 后再输入空格时这个标签就结束了，也就是说一个标签内只能有一个空格
