### ISSUE TITLE
目前有个这样的需求 dcat-admin 中能实现吗？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1146]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
就是我选择完 类型 回生成不同的类型，这个表单设计 和 保存的数据结构 怎么处理好些？
![image](https://user-images.githubusercontent.com/11988030/113372285-e3248480-939a-11eb-9939-841e942fac96.png)

![image](https://user-images.githubusercontent.com/11988030/113372297-eae42900-939a-11eb-8a11-9bf809b9609a.png)

**Comment by jqhph** [comment]
建议使用字段扩展功能自行实现 https://learnku.com/docs/dcat-admin/2.x/field-management/8108

**Comment by shunhua** [comment]
好的
新增行操作按钮 用哪个好些？
