### ISSUE TITLE
树形节点设置exceptParentNode(false)后，也仅在所有子节点全部选中后才会保存它的一个父节点，如何设置去保存它及所有父节点

### ISSUE THREAD

**Issue by scbing** [jqhph/dcat-admin#1147]
- Laravel Version: 8.35.1
- PHP Version: 7.4.13
- Dcat Admin Version: v2.0.22-beta

### Description:

```php
$form->tree('categories')
->nodes((new Category)->allNodes())
->setTitleColumn('title')
->exceptParentNode(false)
->customFormat(function ($v) {
      return array_column($v, 'id');
}),
```
树形节点在禁用父节点过滤后，仍然不能获取到当前选中节点的所有父节点，仅在所有子节点全部选中后，才会获取到仅一个父节点。

请问如何设置在选中子节点后，能保存当前子节点和它的所有的上级节点。
另外一个multipleSelectTable组件，也仅能保持最上层节点，无法保存子节点。

需求源于查询某个节点时，能够显示它所有下级节点的产品。

保存时可以额外操作去循环当前选中节点的所有上级节点并保存，这时候的组件显示时就会全部勾选了，因此才问问看看方法。

**Comment by jqhph** [comment]
目前使用的`jstree`不支持此功能

**Comment by jqhph** [comment]
如果你需要这种功能需要用multipleSelect

```php
$form->multipleSelect('parent_id', trans('admin.parent_id'))->options($menuModel::selectOptions());
```

**Comment by scbing** [comment]
> 如果你需要这种功能需要用multipleSelect
> 
> ```
> $form->multipleSelect('parent_id', trans('admin.parent_id'))->options($menuModel::selectOptions());
> ```

使用multipleSelect组件在选择上和选后显示不太友好。

multipleSelectTable 组件目前不支持选择下级，作者你有支持计划吗？如果有，请透露下预计完善的大概时间。
