### ISSUE TITLE
现在的版本select无法联动到checkbox吗

### ISSUE THREAD

**Issue by MiaNaNa** [jqhph/dcat-admin#1151]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
现在的版本select无法联动到checkbox吗，选择select后checkbox相应的改变数据，如若不可以联动的话我可以如何实现呢。

**Comment by jqhph** [comment]
写js实现，监听select表单的change事件
