### ISSUE TITLE
行内新增按钮，如何实现？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1152]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
在行内加一新列，触发新操作 类似这种
![image](https://user-images.githubusercontent.com/11988030/113829274-e1522b00-97b7-11eb-90d2-570035558f24.png)

**Comment by jqhph** [comment]
参考文档快捷创建章节

**Comment by shunhua** [comment]
快捷创建 好像不能吧  我的意思是在每行内新增
