### ISSUE TITLE
「Request」能否追加後臺操作日志功能？

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#1156]
事故頻發的時候日志是必不可少的，目前是單獨進行配置，希望可以在新版本支持在 `config/admin.php` 中定義與加載。

很久之前使用 Laravel-admin 時記得是可以配置記錄的，

**Comment by jqhph** [comment]
安装这个扩展 https://github.com/dcat-admin/operation-log 或者自己实现
