### ISSUE TITLE
数据库中没有的字段，模型中有的属性，怎么使用sortable()

### ISSUE THREAD

**Issue by running8gubin** [jqhph/dcat-admin#1160]
- Laravel Version: 8.36.2
- PHP Version: 7.4.12
- Dcat Admin Version: 2.0.22

### Description:
表格  results
字段  score1,score1  直接使用sortable()
模型中增加了一个属性：total 
对这个total 属性，如何在表格中使用 sortable()  来排序？

**Comment by jqhph** [comment]
这种是不支持的，`sortable`是数据库的排序，必须是用`sql`统计出来的字段才可以用`sortable`排序
