### ISSUE TITLE
地图组件 静态资源无法自动转换https

### ISSUE THREAD

**Issue by gantoday** [jqhph/dcat-admin#1162]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
我的域名配置好了https。
在设置里也加上了ADMIN_HTTPS=true。
但是测试发现地图静态文件没有自动转换为https地址。导致了地图组件无法使用。

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/7780154/114490475-84d38d80-9c47-11eb-8b01-00e0298b4fb8.png)

![image](https://user-images.githubusercontent.com/7780154/114490794-062b2000-9c48-11eb-8383-dc5f8e6b0275.png)
![image](https://user-images.githubusercontent.com/7780154/114490793-062b2000-9c48-11eb-83d1-fd0e78f481d1.png)

**Comment by gantoday** [comment]
@jqhph 哥。这个有救吗

**Comment by jqhph** [comment]
你先本地重写下这个地图字段，后续版本会修复这个问题

**Comment by gantoday** [comment]
好的。谢谢。

**Comment by gantoday** [comment]
@jqhph 大哥。无法解决啊。怎么办。我改了无效。
麻烦你帮忙修复下好吗。

**Comment by gantoday** [comment]
百度地图搞不定。改用马化腾家的接口。可以用了。
