### ISSUE TITLE
这个地方颜色能换不？加个颜色啥的

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1163]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
![image](https://user-images.githubusercontent.com/11988030/114517862-510d5d80-9c71-11eb-8c9e-04719f3529dd.png)

**Comment by abovesky** [comment]
直接写html标签：
`<span class="text-danger">666666</span>`

**Comment by shunhua** [comment]
我试了好像不行 我的这个值是变量

**Comment by shunhua** [comment]
> 直接写html标签：
> `<span class="text-danger">666666</span>`

![image](https://user-images.githubusercontent.com/11988030/114639243-e820f680-9cff-11eb-9a9c-8874b87f67bf.png)

**Comment by shunhua** [comment]
> 我试了好像不行 我的这个值是变量

![image](https://user-images.githubusercontent.com/11988030/114639377-4057f880-9d00-11eb-95d7-40d48c8706a1.png)

**Comment by jqhph** [comment]
那就写css

**Comment by shunhua** [comment]
> > 我试了好像不行 我的这个值是变量
> 
> ![image](https://user-images.githubusercontent.com/11988030/114639377-4057f880-9d00-11eb-95d7-40d48c8706a1.png)

![image](https://user-images.githubusercontent.com/11988030/114639431-6d0c1000-9d00-11eb-89ae-3315608bf02f.png)
也是不行啊 原生css 也试过 style=“color：red”  不解析 。

**Comment by jqhph** [comment]
多看看文档，入门栏目的至少要过一遍

**Comment by shunhua** [comment]
> 多看看文档，入门栏目的至少要过一遍

没找到哈 ，确认有这个功能没

**Comment by abovesky** [comment]
> > 多看看文档，入门栏目的至少要过一遍
> 
> 没找到哈 ，确认有这个功能没

![image](https://user-images.githubusercontent.com/5986216/114640684-31bf1080-9d03-11eb-8613-ebc7f6af654c.png)
![image](https://user-images.githubusercontent.com/5986216/114640768-5ca96480-9d03-11eb-9f5c-97ef0ca239bd.png)
我一直这么写的，没任何问题

**Comment by shunhua** [comment]
> > > 多看看文档，入门栏目的至少要过一遍
> > 
> > 
> > 没找到哈 ，确认有这个功能没
> 
> ![image](https://user-images.githubusercontent.com/5986216/114640684-31bf1080-9d03-11eb-8613-ebc7f6af654c.png)
> ![image](https://user-images.githubusercontent.com/5986216/114640768-5ca96480-9d03-11eb-9f5c-97ef0ca239bd.png)
> 我一直这么写的，没任何问题

我试了还是不行  版本1.7.8的

**Comment by shunhua** [comment]
> > > 多看看文档，入门栏目的至少要过一遍
> > 
> > 
> > 没找到哈 ，确认有这个功能没
> 
> ![image](https://user-images.githubusercontent.com/5986216/114640684-31bf1080-9d03-11eb-8613-ebc7f6af654c.png)
> ![image](https://user-images.githubusercontent.com/5986216/114640768-5ca96480-9d03-11eb-9f5c-97ef0ca239bd.png)
> 我一直这么写的，没任何问题

你引用的啥头部

**Comment by Warrens-yg** [comment]
单双引号问题？

**Comment by shunhua** [comment]
> 单双引号问题？

应该不是 我换过  一样
