### ISSUE TITLE
Form中通过multipleFile上传文件后无法下载

### ISSUE THREAD

**Issue by Max-Liu** [jqhph/dcat-admin#1164]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.0

### Description:

![Screen Shot 2021-04-13 at 4 13 26 PM](https://user-images.githubusercontent.com/1518955/114520196-c37f3d00-9c73-11eb-8e23-c8b40d824004.png)

Form中的multipleFile 是否能支持downloadable()方法？在Form中上传文件后无法下载预览，能否提供个实现思路？

**Comment by Max-Liu** [comment]
<img width="667" alt="Screen Shot 2021-04-14 at 12 53 58 AM" src="https://user-images.githubusercontent.com/1518955/114590951-f0574280-9cbb-11eb-8da8-b2c42b17f992.png">

先注入js解决了，期待未来增加multipleFile->downloadable()方法

**Comment by jqhph** [comment]
好的，后续会增加下载功能

**Comment by Warrens-yg** [comment]
请问这个功能增加了吗，我看2.0文档上有，不知道是不是我的版本低了， 我是2.0.23-beta
