### ISSUE TITLE
多选框的值最后会多出null

### ISSUE THREAD

**Issue by ZHOU-JIA-WEI** [jqhph/dcat-admin#1165]
- Laravel Version: 7.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0
![QQ图片20210414094955](https://user-images.githubusercontent.com/59349609/114642567-ba8b7b80-9d06-11eb-9df2-fa92ea81f468.png)

### Description:

多选框最后会多出null

**Comment by jqhph** [comment]
这个`null`在表单保存之前会自动去掉

**Comment by ZHOU-JIA-WEI** [comment]
> 这个`null`在表单保存之前会自动去掉

我自定义表单 并不会去掉 还是保存在了数据库

**Comment by jqhph** [comment]
那说明你用法有问题
