### ISSUE TITLE
关于Dcat-Admin 底部信息的建议

### ISSUE THREAD

**Issue by ZHOU-JIA-WEI** [jqhph/dcat-admin#1167]
- Laravel Version: 7.0.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.22

### Description:

尾部直接定死，用户只是修改个尾部信息，相关的处理太过麻烦，作为一个方便开发者的框架，将尾部配置加在配置文件里不是更好吗？下个版本会给他加上吗

![image](https://user-images.githubusercontent.com/59349609/114673054-626d6d00-9d38-11eb-8b5e-44056a38575b.png)

**Comment by jqhph** [comment]
改页脚的方法太多了，比如写css或者js都可以，也可以通过section自定义等等...

**Comment by ZHOU-JIA-WEI** [comment]
是很多  但是最基本的 用户只想和 网站logo  网站名字 那样子的 修改网站页脚 这个不考虑吗

**Comment by jqhph** [comment]
`dcat-admin`是完全开源并且免费的，不开放这个页脚自定义也是希望大家可以尽量保留版权信息。当然如果不方便想要去掉那也没问题，方法很多也不复杂

**Comment by ZHOU-JIA-WEI** [comment]
那实际上就是说  想要最大可能的让用户去看到这个标示并且点击  因为他是开源免费的 是这个道理吧  您要实现这个目前多推广您的项目是很正常的，我表示支持，但是我更支持大部分的开源网站允许最大可能的修改使用的框架去自定义自己的网站，由于使用了这种框架，也可以一眼看出来，这个项目是基于什么来实现的，也可实现您这种效果

**Comment by ZHOU-JIA-WEI** [comment]
您不应该拿开源免费作为搪塞，感谢您的回答，这个issue我关闭了
