### ISSUE TITLE
表格展示全部字段出错

### ISSUE THREAD

**Issue by LazyBaby** [jqhph/dcat-admin#1168]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 2.0.22-beta

### Description:

1.表格数据展示字段出错（当前问题是从v2.0.20直接升级到v2.0.22后出现的）

![image](https://user-images.githubusercontent.com/15863793/114697995-27c3fe80-9d51-11eb-9b28-54fbd94ab1ee.png)

2.模态窗和复制功能同时使用时，点击复制会同时打开模态窗（这个问题是一直存在）
![image](https://user-images.githubusercontent.com/15863793/114698596-dcf6b680-9d51-11eb-8bbd-2b711af7ef08.png)

**Comment by jqhph** [comment]
管理员页面是否会有报错的情况？

**Comment by LazyBaby** [comment]
> 管理员页面是否会报错？

今天没有了，应该是我昨天刚升级资源发布后缓存问题（当时新开的一个浏览器也报错了，两个浏览器分别是Google和Safari），第二条问题依然存在，点击复制的时候会同时触发模态窗

**Comment by LazyBaby** [comment]
> > 管理员页面是否会报错？
> 
> 今天没有了，应该是我昨天刚升级资源发布后缓存问题（当时新开的一个浏览器也报错了，两个浏览器分别是Google和Safari），第二条问题依然存在，点击复制的时候会同时触发模态窗

如果已确认问题麻烦帮我关闭，谢谢

**Comment by jqhph** [comment]
第二个问题可以试试先调用 modal 再 copyable

**Comment by LazyBaby** [comment]
> > 管理员页面是否会报错？
> 
> 今天没有了，应该是我昨天刚升级资源发布后缓存问题（当时新开的一个浏览器也报错了，两个浏览器分别是Google和Safari），第二条问题依然存在，点击复制的时候会同时触发模态窗

抱歉我早上测试出问题了，第一个问题JS报错依然存在，我正在找复现方法

**Comment by LazyBaby** [comment]
> 第二个问题可以试试先调用 modal 再 copyable

先调用modal的话会出现下列情况
![image](https://user-images.githubusercontent.com/15863793/114811848-6e613980-9de1-11eb-9721-9835b1c3fe7f.png)

代码：
![image](https://user-images.githubusercontent.com/15863793/114811894-83d66380-9de1-11eb-9398-4780f126ecb3.png)

**Comment by LazyBaby** [comment]
JS报错复现出来了，我有个字段是组合字段，正常情况下没有问题（组合字段不显示，没做隐藏），一但要显示这个字段，js就会报错（在不对该字段做显示、隐藏、全选操作时没有问题，其他字段可以正常操作显示或隐藏），是否是现在这种写法不再支持了？
代码如下：
![image](https://user-images.githubusercontent.com/15863793/114813776-62777680-9de5-11eb-9437-3f4f3f346a6d.png)

**Comment by jqhph** [comment]
正常是没有影响的

**Comment by LazyBaby** [comment]
> 正常是没有影响的

复制会触发模态窗这个影响不大，再关掉就是了；
这个JS报错影响很大的，因为我要把几个字段放一个字段中显示，JS报错导致我这个字段显示不出来了

**Comment by LazyBaby** [comment]
@jqhph 设置一个场景，我一个字段表示4种类类别的开关，需要用到位运算，转化成开关不知道怎么转，用display转化值就会出现这种情况，页面字段不显示，字段选择器中选中就会JS报错

**Comment by abovesky** [comment]
试试用displayUsing实现，参考官方扩展页面源码

**Comment by LazyBaby** [comment]
> 试试用displayUsing实现，参考官方扩展页面源码

抱歉这几天事比较多没有回复，文档上没有找到displayUsing的使用方法，翻看源码和系统上的示例，最后还是没成功弄出来，不过我还是用display解决了位运算，至于字段不显示的问题，我舍去了列展开，使用了模态窗代替，感谢提供思路，这个displayUsing后续再研究下怎么用。
效果：
![image](https://user-images.githubusercontent.com/15863793/115334090-5157ac80-a1cd-11eb-91a9-a4a5c5b7405b.png)

代码非常简单：

![image](https://user-images.githubusercontent.com/15863793/115334206-8a901c80-a1cd-11eb-975f-5f5bc212eb30.png)
