### ISSUE TITLE
上传文件时可不可以先将原文件名保存到数据库

### ISSUE THREAD

**Issue by jiangyou0998** [jqhph/dcat-admin#1169]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.7.0

### Description:
请问上传文件时可不可以先将原文件名保存到数据库某个字段,再将文件随机命名后保存到path字段上?

**Comment by jqhph** [comment]
可以通过文件上传相关事件把原始文件名设置到隐藏域表单中，然后实现保存功能，参考https://learnku.com/docs/dcat-admin/2.x/picture-file-upload/8106

**Comment by qq447665722** [comment]
同样问题,没有解决题主问题
