### ISSUE TITLE
grid filter checkbox

### ISSUE THREAD

**Issue by outer199** [jqhph/dcat-admin#1173]
- Laravel Version: 6.20.5
- PHP Version: 7.2.27
- Dcat Admin Version: 2.0.15-beta

### Description:
filter checkbox 页面无法回显, 并且样式有点问题, 是我的用法有问题吗?

### Steps To Reproduce:
```
$filter->equal('groupBys[]', 'Breakdowns')->checkbox([
                    'a'      => 'Day',
                    'b' => 'Week',
                    'c' => 'Month',
                ])->ignore();
```
![image](https://user-images.githubusercontent.com/23118182/114874160-a0e55380-9e2e-11eb-9e7b-f8e18cca2db6.png)

**Comment by outer199** [comment]
![image](https://user-images.githubusercontent.com/23118182/114897264-a600cd80-9e43-11eb-99dc-7dbc7b96a2e2.png)

多次点击 查询 按钮, 传参会变多

**Comment by jqhph** [comment]
```php
$filter->in('groupBys', 'Breakdowns')->checkbox([
                    'a'      => 'Day',
                    'b' => 'Week',
                    'c' => 'Month',
                ])->ignore();
```

**Comment by outer199** [comment]
依旧不行, url 里的参数名不是 groupBys[] 所以后台只可以获取到一个选中的值
![image](https://user-images.githubusercontent.com/23118182/114977662-9d97a980-9eba-11eb-9beb-1663819adcf6.png)

**Comment by outer199** [comment]
`views/filter/checkbox.blade.php`

![image](https://user-images.githubusercontent.com/23118182/114988250-b4dd9380-9ec8-11eb-9628-1890ea128405.png)
