### ISSUE TITLE
执行`php artisan admin:install`的建议

### ISSUE THREAD

**Issue by liamhao** [jqhph/dcat-admin#1177]
https://github.com/jqhph/dcat-admin/blob/08667f11282cfbfb49fd16493efac3f6719c10fc/src/Console/InstallCommand.php#L52

在执行迁移的时候，`Dcat\Admin\Console\InstallCommand@initDatabase()`中能否只迁移 dcat-admin 需要的数据库？现在这一股脑全部迁移的做法，会使我迁移过的数据库再迁移一遍，从而导致`php artisan admin:install`执行失败。

**Comment by jqhph** [comment]
会使我迁移过的数据库再迁移一遍

--------------------------

migration文件不是只能执行一遍吗？如果会执行多遍，那说明你的代码或者migration表记录有问题

**Comment by liamhao** [comment]
ok，回去我再研究下哪里有问题。
