### ISSUE TITLE
有没有办法将多个js资源合并成一个？

### ISSUE THREAD

**Issue by liamhao** [jqhph/dcat-admin#1178]
- Laravel Version: 8.25.0
- PHP Version: 8.0.0
- Dcat Admin Version: 2.0.22

### Description:
第一个打开页面，看到网络请求中有好多js资源在排队（个人测试服务器配置低，带宽小），页面加载很慢。如果能将多个js资源合并成一个，那就太好了！有没有什么办法？
![image](https://user-images.githubusercontent.com/31812811/115134128-2724b400-a040-11eb-9a0f-7d3471660981.png)

![image](https://user-images.githubusercontent.com/31812811/115134121-17a56b00-a040-11eb-802b-d714da328d7c.png)

**Comment by jqhph** [comment]
不支持合并，可以把静态资源放到CDN服务器如果有的话
