### ISSUE TITLE
过滤器是否支持动态显示？

### ISSUE THREAD

**Issue by adgad2** [jqhph/dcat-admin#1179]
- Dcat Admin Version: 1.6.5

### Description:
比如有个select过滤器，一个input的过滤器

是否支持监听select选择的值，来决定这个input的过滤器显示与否

看了文档，表单是通过when方法来实现动态显示的，但是过滤器$filter好像并不支持这种写法

**Comment by jqhph** [comment]
不支持，只能自己写JS
