### ISSUE TITLE
请问 如何在自定义的页面中使用 form selectTable 组件呢?

### ISSUE THREAD

**Issue by outer199** [jqhph/dcat-admin#1180]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
请问 如何在自定义的页面中使用 form selectTable 组件呢?

**Comment by jqhph** [comment]
```php
$form = new MyForm();

return admin_view('...', ['myForm' => $myForm]);
```

模板

```html
<div>
 {!! $myForm !!}
</div>
```

**Comment by outer199** [comment]
@jqhph 谢谢大佬, 是这样我的 form 表单个性化比较高, 没办法用 PHP 代码组装 form 元素拼不出来我要的表单样式. 因此我想在自定义的视图中用 js 的方式调用 selectTable, 应该怎么操作呢

**Comment by jqhph** [comment]
其实完全可以，表单是可以自定义view的

**Comment by outer199** [comment]
@jqhph 怎么在页面里直接使用 SelectTable 呢? 我是想使用此插件选择图片. 选完后, 返回选择的图片地址.

**Comment by outer199** [comment]
最终使用 js 的方式解决. 在页面中渲染出 selectTable 组件, 通过 js 模拟点击, 监控 selectTable 输入框的 cahnge 事件
