### ISSUE TITLE
Custom asset, js and css not contained on that specific view, after called will load on all pages

### ISSUE THREAD

**Issue by jay2success** [jqhph/dcat-admin#1181]
- Laravel Version: 8.36.2
- PHP Version: 7.4.6
- Dcat Admin Version: 2.0.20-beta

### Description:
Hello, 

Thanks for this amazing package, i am enjoying using it.
The issue is when you add custom asset, js, css, etc

- admin_css()
- admin_js()
- admin_script()
- admin_style()
- admin_require_assets()

Add any of those functions to specific controller or view, it should loaded on that view only.
But after loading that view and you move to other menu/controller, that assets are still there and it's causing css/js issue.

For example: 
I have custom vue component and only load on specific controller/view.
These vue component need font-awesome 5. 
Since dcat-admin use font-awesome 4 then there is icon conflict and some menus are missing the icons. 
Same with custom js or npm package needed on vue, it can cause js/css issue as well.
It's important issue because if other controller has custom assets then it will keep stacking and can cause css/js and performance issue.
Please help, thanks again for this awesome package.

### Steps To Reproduce:

```
class PageController extends Controller
{
public function create(Content $content)
    {
        admin_js(asset('assets/js/app.js'));
        admin_css(asset('assets/css/app.css'));
        admin_require_assets(['@tinymce5']);
        admin_inject_section(Admin::SECTION['HEAD'], function () {
            return '
            <meta name="csrf-token" content="'.csrf_token().'">
            <script>
                window._locale = "'. app()->getLocale().'";
                window._translations = '. cache('translations') .';
            </script>';
        });

        return $content
            ->title($this->title())
            ->body(view('admin.pages.create'));
    }
}
```

**Comment by jqhph** [comment]
I’m not sure I fully understand your question, you can try add `Admin::pjax(false)` to the `app/Admin/bootstrap.php`

**Comment by jay2success** [comment]
Hi,

Ok here's example:
I have 3 menu:

1. Pages
2. Posts
3. Categories

On menu - pages (PageController), i added "summernote js" asset. 
Then i click on menu - posts.
On menu - posts (PostController), the "summernote js" asset still loaded. 
You can use chrome - inspect to check the loaded sources and the "summernote js" still there.

It should only loaded on menu - pages cause i only add the asset on PageController right?.

I will try the pjax option.
What is the downside of using pjax false?

**Comment by jay2success** [comment]
Hi,

Just try the pjax false and its throwing error.

Non-static method Dcat\Admin\Admin::pjax() should not be called statically

I checked the source and its not static function so its throwing error.

Using 
`Admin::disablePjax();`
also throw same error.

So what should i do?

**Comment by jqhph** [comment]
> What is the downside of using pjax false?

See https://github.com/defunkt/jquery-pjax , and try `Admin::context()->pjaxContainerId = false;`

**Comment by jay2success** [comment]
Ok it's working now, thanks a lot.

For future dev, it might be useful to add method to remove or reset asset, custom js and css so we can still use pjax.

Thanks again, have a nice day.
