### ISSUE TITLE
Form 表单使用 hasMany 再次编辑提交后会重复添加

### ISSUE THREAD

**Issue by cbjason** [jqhph/dcat-admin#1182]
- Laravel Version: 8.36.2
- PHP Version: 7.3.9
- Dcat Admin Version: v2.0.23-beta

### Description:
创建完去编辑，不修改任何字段，直接提交，hasMany 组件的内容会重复生成

**Comment by jqhph** [comment]
没有重现，请描述清楚操作步骤

**Comment by cbjason** [comment]
```
$form->hasMany('atts', function ($form) {
      $form->file('url')->url('files/upload')->retainable();
  })->useTable();
  ```
  
编辑页面 ``` atts ``` 在已有一个 url 的情况下，直接点提交重复出现了一个相同的 url，每点击保存就会重复出现一次

![20210420175741](https://user-images.githubusercontent.com/7694765/115377386-263b8000-a202-11eb-9c5c-f01157c0eb13.jpg)
![20210420175834](https://user-images.githubusercontent.com/7694765/115377399-29367080-a202-11eb-9461-b30e4e72d73b.jpg)

**Comment by jqhph** [comment]
无法重现

**Comment by cbjason** [comment]
> 无法重现

不好意思是我自己的问题，我在 model 里设置了 visible 导致主键 id 不可见以致于保存后重复添加
