### ISSUE TITLE
Form 表单在使用Json表单（array 组件）里使用 select when 在新增页面显示异常

### ISSUE THREAD

**Issue by cbjason** [jqhph/dcat-admin#1183]
- Laravel Version: 8.36.2
- PHP Version: 7.3.9
- Dcat Admin Version: v2.0.23-beta

### Description:
Form 表单在使用Json表单（array 组件）里使用 select when 在**新增页面**（编辑页面未出现）时，第二个 select 的字段会联动改变第一个select里的字段
```
$form->array('extra', function ($form) {
    $form->select('type')
        ->options([1 => '文字', 2 => '图片'])
        ->default(1)
        ->when(1, function ($form) {
            $form->text('content')->rules('max:255');
        })->when(2, function ($form) {
            $form->image('cover')->url('files/upload')->retainable();
        });
})->saveAsJson();
```
第一个select
![20210420180224](https://user-images.githubusercontent.com/7694765/115377848-9518d900-a202-11eb-82ce-5005dd41694c.jpg)

第二个select 会影响第一个select
![20210420180322](https://user-images.githubusercontent.com/7694765/115377995-b679c500-a202-11eb-91df-730850e0dd7e.jpg)

**Comment by jqhph** [comment]
不支持，需要自己写js控制。

```php
    $form->select('action')->options(['change-payment' => 'Change Payment']);

    $form->html('<div class="action-forms change-payment d-none">')->plain();

    $form->select('payment')->options(...);

    $form->html('</div>')->plain();
```

添加js
```php
$actions = collect($form->model()->actions)->pluck('action')->filter()->toJson();

Admin::script(
            <<<JS
(function () {
    var actions = {$actions};
    var listenFieldEvent = function () {
        $('.field_action').on('change', function () {
            var parent = $(this).parents('.has-many-actions-form');
            
            parent.find('.action-forms').addClass('d-none');
            parent.find('.'+this.value).removeClass('d-none');
        });
    };
    
    $('.has-many-actions .add').on('click', function () {
        setTimeout(listenFieldEvent, 10);
    });
    
     listenFieldEvent();
     
     for (var i in actions) {
         var parent = $('[name="actions['+(parseInt(i)+1)+'][action]"]').parents('.has-many-actions-form');
         parent.find('.'+actions[i]).removeClass('d-none')
     }
})()
JS
        );
```

**Comment by cbjason** [comment]
> 不支持，需要自己写js控制。
> 
> ```
>     $form->select('action')->options(['change-payment' => 'Change Payment']);
> 
>     $form->html('<div class="action-forms change-payment d-none">')->plain();
> 
>     $form->select('payment')->options(...);
> 
>     $form->html('</div>')->plain();
> ```
> 
> 添加js
> 
> ```
> $actions = collect($form->model()->actions)->pluck('action')->filter()->toJson();
> 
> Admin::script(
>             <<<JS
> (function () {
>     var actions = {$actions};
>     var listenFieldEvent = function () {
>         $('.field_action').on('change', function () {
>             var parent = $(this).parents('.has-many-actions-form');
>             
>             parent.find('.action-forms').addClass('d-none');
>             parent.find('.'+this.value).removeClass('d-none');
>         });
>     };
>     
>     $('.has-many-actions .add').on('click', function () {
>         setTimeout(listenFieldEvent, 10);
>     });
>     
>      listenFieldEvent();
>      
>      for (var i in actions) {
>          var parent = $('[name="actions['+(parseInt(i)+1)+'][action]"]').parents('.has-many-actions-form');
>          parent.find('.'+actions[i]).removeClass('d-none')
>      }
> })()
> JS
>         );
> ```

好的，谢谢
