### ISSUE TITLE
表单中加入自动获取信息功能？

### ISSUE THREAD

**Issue by wai523** [jqhph/dcat-admin#1190]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
表单中需要加入一键获取按钮，在输入框里输入企业名称点击一键获取后可以将数据接口获取的工商信息自动填入对应字段中。

**Comment by jqhph** [comment]
自己写js

**Comment by wai523** [comment]
> 
> 
>     * Laravel Version: #.#.#
> 
>     * PHP Version: #.#.#
> 
>     * Dcat Admin Version: #.#.#
> 
> 
> ### Description:
> 
> 表单中需要加入一键获取按钮，在输入框里输入企业名称点击一键获取后可以将数据接口获取的工商信息自动填入对应字段中。
> ### Steps To Reproduce:
