### ISSUE TITLE
2.0.22 升级到 2.0.23 后 Grid 渲染多出一列

### ISSUE THREAD

**Issue by windyson2008** [jqhph/dcat-admin#1196]
- Laravel Version: 7.x
- PHP Version: 5.4
- Dcat Admin Version: 2.0.23

### Description:
2.0.22 升级到 2.0.23 后 Grid 渲染多出一列，请参看下图
![image](https://user-images.githubusercontent.com/4033451/115758346-fb0b8900-a3d9-11eb-8126-82741c6e98cd.png)

### Steps To Reproduce:
我项目的Grid，启用了固定列，组合表头特性
另外，Actions 没有使用 Dropdown 方式

**Comment by jqhph** [comment]
代码有点问题吧

**Comment by jqhph** [comment]
感谢反馈，可以先更新开发分支代码
```
composer require dcat/laravel-admin:"2.0.x-dev"
```
