### ISSUE TITLE
layouts页面是否可以自定义显示

### ISSUE THREAD

**Issue by ColdJk** [jqhph/dcat-admin#1202]
- Laravel Version: 8.5.*
- PHP Version: 7.4.*
- Dcat Admin Version: 2.*.*

### Description:
layouts页面可以自定义显示吗，比如说将页面底部的标注去除

![QQ截图20210424183105](https://user-images.githubusercontent.com/38715073/115955784-539e6b80-a52b-11eb-9ea6-5a38126f1a86.png)

**Comment by jqhph** [comment]
可以通过css或js去除页脚

**Comment by ColdJk** [comment]
> 可以通过css或js去除页脚

怎么重写页脚页面

**Comment by SmallRuralDog** [comment]
```js
document.querySelector(".main-footer .d-block").remove()
```

**Comment by kingofzihua** [comment]
- 准备自定义的显示页面
    复制文件 ```vendor/dcat/laravel-admin/resources/views/layouts/container.blade.php``` 
    到     ```resources/views/admin/layouts/container.blade.php```

- 替换页面
    ```php 
    # 在 app/Admin/bootstrap.php 页面加入下面代码
    view()->prependNamespace('admin',resource_path('views/admin'));
    ```
