### ISSUE TITLE
列表按钮样式无法正常显示

### ISSUE THREAD

**Issue by nicesome** [jqhph/dcat-admin#1205]
- Laravel Version: 8.x
- PHP Version: 8.0
- Dcat Admin Version: 2.x

### Description:
列表按钮样式无法正常显示，已被覆盖。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/27793619/115980060-5006f500-a5bc-11eb-9ace-25168438d176.png)

**Comment by jqhph** [comment]
目前固定列功能不兼容DropdownActions
