### ISSUE TITLE
Pjax disabled cause redirect to index page after save on create or update page not working

### ISSUE THREAD

**Issue by jay2success** [jqhph/dcat-admin#1208]
- Laravel Version: 8.36.2
- PHP Version: 7.4.6
- Dcat Admin Version: 2.0.20-beta

### Description:
I disabled pjax because of asset issue
#1181 

The problem is when i disabled it, after save action on create/update page, it should redirect back to index but it is not, it stays on the same page.

### Steps To Reproduce:
bootstrap.admin.php
`Admin::context()->pjaxContainerId = false;`

Go to any Controller, do create/update, after save, it does not redirect to index page (grid page).

Please help, thanks.

**Comment by jqhph** [comment]
Run `composer remove dcat/laravel-admin` and `composer require dcat/laravel-admin:"2.0.x-dev"`
