### ISSUE TITLE
我想在表格展示的一列中，自定义多个api操作逻辑，这个该如何实现。

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1212]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
我有一个用户管理列表，比如要显示用户的相册列表，然后想对相册的图片进行多个操作，比如设置为头像，设置为背景，或者是删除，现在想在遍历图片的时候，加上多个超链接进行处理不同的api接口逻辑。请问这个该如何实现？
![111](https://user-images.githubusercontent.com/5857415/116346992-eb4ad500-a81d-11eb-9c34-cfb9f46f7ab9.jpg)

**Comment by jqhph** [comment]
自己写HTML
