### ISSUE TITLE
安装出错

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1213]
- Laravel Version: 7.*|8.*
- PHP Version: 7.4
- Dcat Admin Version: 2.0.23-beta

### Description:
![image](https://user-images.githubusercontent.com/13138164/116411686-85d00600-a868-11eb-8f7e-959d9312de85.png)

**Comment by jqhph** [comment]
laravel版本与php版本不匹配

**Comment by Ya-hui** [comment]
php7.4  laravel 应该装那个版本？看文档 laravel8 7 都是支持php7.4的
