### ISSUE TITLE
一对一表单创建提示500 Internal Server Error

### ISSUE THREAD

**Issue by ThankRain** [jqhph/dcat-admin#1215]
- Laravel Version: 8.x
- PHP Version: 8.0.2
- Dcat Admin Version: 2.0.23-beta

### Description:
一对一表单创建提示500 Internal Server Error
控制台信息提示Array to string conversion

### Steps To Reproduce:
按照一对一示例创建数据表，用代码生成器生成其模型，数据仓库和控制器，并根据文档修改，当form中包含了profile.xx字段时，提示500错误，不包含则能够正常创建
提交的post数据为
name=nickname&email=1@qq.com&profile[age]=15&profile[gender]=18&created_at=2021-04-29+13:00:50&updated_at=2021-04-29+13:00:51&_token=xx3hBbeVIiQ6oLd0Y4Z3kx0QUb7179l4QCAsYT1A
![Screenshot_2021-04-29-13-28-59-085_mark via](https://user-images.githubusercontent.com/36541432/116506208-616b3c80-a8ef-11eb-9e61-bec5043862dc.jpg)

**Comment by jqhph** [comment]
代码有问题，对照表单关联关系文档使用

**Comment by ThankRain** [comment]
> 代码有问题，对照表单关联关系文档使用

重新走了一遍，发现代码确实有问题，现在已经好了😅
