### ISSUE TITLE
后台有没有单独设置用户权限

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1216]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
不用设置用户角色的，单独给用户设置权限，有时候比较灵活

**Comment by jqhph** [comment]
需要自己增加这个功能

**Comment by howye** [comment]
感谢，那我自己来加吧

**Comment by howye** [comment]
![image](https://user-images.githubusercontent.com/26995286/117101512-f2875b00-ada8-11eb-9f92-b46d856be06f.png)
![image](https://user-images.githubusercontent.com/26995286/117101529-fc10c300-ada8-11eb-8e59-e52189a2178f.png)
访问一个没有权限的页面后，再次访问一个有权限的页面，也会出现一个无权限的alert，但是页面可以访问

**Comment by Ynwaspectre** [comment]
@howye 同遇到
