### ISSUE TITLE
在app/Admin/routes.php 新建路由 报404，自带路由可以正常访问

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1217]
- Laravel Version:  8.12
- PHP Version: 7.4
- Dcat Admin Version: 2.0.23

### Description:

根据这篇文档 一步一步来的

https://learnku.com/docs/dcat-admin/2.x/quick-start/8082#2e680a

在app/Admin/routes.php 新建路由 报404

![image](https://user-images.githubusercontent.com/13138164/116642596-d7c87700-a9a1-11eb-97c2-ee65c17eeecb.png)

访问方式 /admin/users

dcat-admim自带的页面路由都是可以访问的

nginx配置：
![image](https://user-images.githubusercontent.com/13138164/116642708-1100e700-a9a2-11eb-8b95-4a2ce60a0aba.png)

**Comment by jqhph** [comment]
可能安装步骤有问题，或者是使用了路由缓存导致的

**Comment by Ya-hui** [comment]
我刚把缓存都清除了一下还是不行， 安装步骤没发现问题 ，也没产生错误
我刚在外层定义了一下路由 是可以访问的
![image](https://user-images.githubusercontent.com/13138164/116643582-f3348180-a9a3-11eb-965d-a3132ef96b98.png)

访问方式
/transfer
