### ISSUE TITLE
bug: 无法使用代码生成

### ISSUE THREAD

**Issue by aogg** [jqhph/dcat-admin#1227]
- Laravel Version: 8
- PHP Version: 7.2
- Dcat Admin Version: 2

### Description:
还是保留之前的代码生成，不是最新填写的

![image](https://user-images.githubusercontent.com/8998031/116889438-23f40f80-ac5f-11eb-955d-c1601f684e80.png)

**Comment by aogg** [comment]
而且提交后，图片里的“创建表迁移文件”和“创建数据表”都没有勾选了，本来是勾选了的

**Comment by aogg** [comment]
不勾选创建表才成功

**Comment by liangyh2000** [comment]
同样问题。
