### ISSUE TITLE
如果用这个框架做ERP，有没有什么要注意得地方啊

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#123]
问题同标题

**Comment by jqhph** [comment]
可以参考下这篇文章[dcat-admin 开源框架在 erp 项目中的应用
](https://learnku.com/articles/44139)

**Comment by Warrens-yg** [comment]
非常感谢，这篇文章对我帮助很大，另外还有一个问题，覆写内置视图得时候不起作用，laravel-admin官方上这个地方被划掉了。
![批注 2020-05-17 165326](https://user-images.githubusercontent.com/46614146/82142950-2d803e00-987b-11ea-87b9-506d4e505af3.jpg)

**Comment by jqhph** [comment]
这个功能是正常的，但不是很推荐覆写视图，如果不行可以尝试
```php
view()->replaceNamespace('admin', resource_path('views/admin'));
```

**Comment by Warrens-yg** [comment]
Ok，replaceNamespace 正常工作了。
