### ISSUE TITLE
最上面的header到底怎么替换的

### ISSUE THREAD

**Issue by aogg** [jqhph/dcat-admin#1230]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: 2

### Description:
![image](https://user-images.githubusercontent.com/8998031/117024705-cf1eca80-ad2c-11eb-88ff-3b2cbeb86fbd.png)
![image](https://user-images.githubusercontent.com/8998031/117024781-e3fb5e00-ad2c-11eb-91e6-a7920b3b5476.png)

**Comment by aogg** [comment]
```
    public function __construct()
    {
        $this->title = '这么改'
    }
```

这个有文档说明吗？感觉不明显，而又重要的

**Comment by Warrens-yg** [comment]
你没表达清楚，不知道如何回答你

**Comment by aogg** [comment]
我发的图片里的JsonIdJsonAdmin，这个英文要手动在控制器修改，要怎么改

**Comment by Warrens-yg** [comment]
/**
     * Index interface.
     *
     * @param Content $content
     *
     * @return Content
     */
    public function index(Content $content)
    {
        return $content
            ->translation($this->translation())
            ->title($this->title())
            ->description($this->description()['index'] ?? trans('admin.list'))
            ->body($this->grid());
    }
这里的title

**Comment by Warrens-yg** [comment]
你可以看一下你现在controller继承的 AdminController，如果只是修改标题，只需要在你现在的controller中覆盖变量 protected $title;即可

**Comment by aogg** [comment]
> 你可以看一下你现在controller继承的 AdminController，如果只是修改标题，只需要在你现在的controller中覆盖变量 protected $title;即可

所以啊


这个有文档说明吗？感觉文档说明不明显，而功能又极其重要的


文档麻烦补充下，很重要的说

**Comment by jqhph** [comment]
文档在`开发前必读`栏目，新手请务必过一遍`入门`栏目的文档
