### ISSUE TITLE
apexcharts的饼图要怎么设置啊？

### ISSUE THREAD

**Issue by 2494911084** [jqhph/dcat-admin#1231]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
apexcharts的饼图要怎么设置啊？  柱状图和曲线图我修改类型字段就可以了。 饼图修改类型后 还是柱状图。 这个要怎么设置啊

**Comment by jqhph** [comment]
参考apexcharts官方文档，其实就是options参数不同而已
