### ISSUE TITLE
bug，setConstraints，列表详情没有带参数

### ISSUE THREAD

**Issue by aogg** [jqhph/dcat-admin#1232]
- Laravel Version: 8
- PHP Version: 7
- Dcat Admin Version: 2

### Description:
![image](https://user-images.githubusercontent.com/8998031/117163134-f42b4000-adf5-11eb-9a9c-f8a0c7fd72de.png)
![image](https://user-images.githubusercontent.com/8998031/117163210-05744c80-adf6-11eb-850d-534b3426dbff.png)

这里设置了公共参数后，编辑有带参数，但详情没有带参数
```
            $grid->model()->setConstraints([
                'type' => $this->getRequestType(),
            ]);
```

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/117166318-d6130f00-adf8-11eb-8363-0135999cc101.png)
![image](https://user-images.githubusercontent.com/8998031/117166366-e0350d80-adf8-11eb-80a5-1976b8413e2c.png)
这两处代码是不是应该统一一下，只做edit和show的区别

**Comment by aogg** [comment]
form和shuo也支持下setConstraints方法吧，否则列表支持了，其他没支持也很痛苦

**Comment by jqhph** [comment]
> form和shuo也支持下setConstraints方法吧，否则列表支持了，其他没支持也很痛苦

好的
