### ISSUE TITLE
json字段，在casts定义后form通过embeds保存会出现两次json_encode后存进mysql

### ISSUE THREAD

**Issue by aogg** [jqhph/dcat-admin#1233]
- Laravel Version: 8
- PHP Version: 7
- Dcat Admin Version: 2

### Description:
![image](https://user-images.githubusercontent.com/8998031/117171141-3310c400-adfd-11eb-88b1-187e32614687.png)

**Comment by aogg** [comment]
->saveAsJson()用这个

**Comment by jqhph** [comment]
模型指定`casts`之后就不需要`saveAsString`了
