### ISSUE TITLE
关于json表单，使用array或table保存字段后数据结构问题

### ISSUE THREAD

**Issue by abovesky** [jqhph/dcat-admin#1234]
- Laravel Version: 8.33.1
- PHP Version: 7.4.8
- Dcat Admin Version: 2.0.23-beta

### Description:
我只用了title和content两个字段，但是保存到数据库却多出了好几个字段。
而且移除后虽然_remove_字段变为了1，但是编辑页面依旧显示
![image](https://user-images.githubusercontent.com/5986216/117234433-8fa0cd00-ae57-11eb-906d-f8188a7ef5ef.png)
想问一下，是故意如此设计还是此处有问题？
![image](https://user-images.githubusercontent.com/5986216/117234496-b2cb7c80-ae57-11eb-917f-d4d2a3ef0f5a.png)

**Comment by jqhph** [comment]
其他字段保存之前会过滤

**Comment by abovesky** [comment]
> 其他字段保存之前会被过滤掉

实际情况是全保存到数据库了，没有过滤

**Comment by jqhph** [comment]
那说明你的表单代码有问题

**Comment by abovesky** [comment]
找到问题了，content字段重复
