### ISSUE TITLE
创建一个子账号登录后，只勾了部分权限，想要子账号在创建的角色时候只在该账号拥有的权限中去选择

### ISSUE THREAD

**Issue by yhhhhh** [jqhph/dcat-admin#1235]
- Laravel Version: 8.25.0
- PHP Version: 7.3.4
- Dcat Admin Version: 2.*

### Description:
创建一个子账号登录后，只勾了部分权限，想要子账号在创建的角色时候只在该账号拥有的权限中去选择。

### Steps To Reproduce:
尝试在form->nodes中修改allnodes，添加条件查询，也试过重写allnodes，返回的数据格式都一样，但是都无法正常显示，一直显示loding。
要怎样实现这个功能

**Comment by jqhph** [comment]
无法正常显示可能是因为parent_id有对不上的情况
