### ISSUE TITLE
后台权限小问题，多后台（多应用）共享登录态

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1238]
- Laravel Version: 8.4.0
- PHP Version: 7.4.3
- Dcat Admin Version: 2.0.23-beta

### Description:
1、用的还是角色权限，访问一个没有权限的页面后，再次访问一个有权限的页面，也会出现一个无权限的alert，但是页面可以访问；
![image](https://user-images.githubusercontent.com/26995286/117521737-e9cd9980-afe1-11eb-9c3c-e4a429ab2110.png)
![image](https://user-images.githubusercontent.com/26995286/117521741-efc37a80-afe1-11eb-984a-401a155ed81c.png)

2、多后台（多应用）情况下怎么能共享登录态（session或redis）呢？

**Comment by howye** [comment]
好吧，那第一个问题无权限的弹窗是我的配置有问题吗？

**Comment by howye** [comment]
好的

**Comment by ruziyi** [comment]
这个问题并没有解决啊
