### ISSUE TITLE
【BUG】Full Page 父页面跟随子页面滚动

### ISSUE THREAD

**Issue by QThans** [jqhph/dcat-admin#124]
iframe里面滚动，外层也会跟着滚动

![image](https://user-images.githubusercontent.com/18275400/82147887-6de3ba00-9883-11ea-9802-664365620e28.png)

解决方案：

https://www.zhangxinxu.com/wordpress/2015/12/element-scroll-prevent-parent-element-scroll-js/

子页面加上对应代码即可阻止父页面跟随滚动

**Comment by jqhph** [comment]
感谢反馈，这个问题已经发现了，后续版本中会优化这个问题。

**Comment by jqhph** [comment]
这个功能已经优化了，升级到最新版本即可
