### ISSUE TITLE
搜索是否可以自动隐藏

### ISSUE THREAD

**Issue by xmy1024** [jqhph/dcat-admin#1244]
![image](https://user-images.githubusercontent.com/14902717/117613179-0bbd4c80-b199-11eb-9879-772a1645e9a9.png)

**Comment by jqhph** [comment]
可以
```php
        $grid->rows(function () use ($grid) {
            $grid->filter()->expand(false);
        });
```

**Comment by xmy1024** [comment]
> 可以
> 
> ```
>         $grid->rows(function () use ($grid) {
>             $grid->filter()->expand(false);
>         });
> ```

如果想全局禁用怎么实现呢

**Comment by IceBay** [comment]
```php
// app\Admin\bootstrap.php
Filter::resolving(function (Filter $filter) {
    $filter->expand(false);
});
```
