### ISSUE TITLE
我想在表格的某列中，多加一个弹框表单操作，应该如何做？

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1246]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
原有的只能在操作栏添加弹框操作，我的需求是一个用户列表里面展示了一列图片列表，在没有图片的时候，可以添加图片，需要弹框显示表单添加图片提交。看demo都是一列只能放一个按钮，我是想自定义html内容，添加图片操作按钮。但是不知道这个弹框要怎么渲染上去？
![1620641111968](https://user-images.githubusercontent.com/5857415/117642810-54d1c880-b1ba-11eb-9ce9-1fb9046df533.jpg)

**Comment by jqhph** [comment]
没看明白，不过列的显示是可以通过条件判断去使用不同组件的，参考文档 https://learnku.com/docs/dcat-admin/2.x/display-and-expansion-of-columns/8091

**Comment by dmskys** [comment]
> 没看明白，不过列的显示是可以通过条件判断去使用不同组件的，参考文档 https://learnku.com/docs/dcat-admin/2.x/display-and-expansion-of-columns/8091

就是我这一列的显示是用的自定义的display输出的html标签显示的，删除图片就是js绑定一个ajax请求事件，现在我想多加一个添加图片的操作，是弹出模式框添加，就不知道怎么添加构造这个model弹框表单。我看文档只能在操作那一栏添加操作弹框，我这个是根据不同的条件添加这个删除图片按钮。

**Comment by jqhph** [comment]
参考文档表单弹窗

**Comment by dmskys** [comment]
> 参考文档表单弹窗

看了，表单弹框必须要要跟一个控制器关联，而且需要绑定模型，我现在需要的是可以自定义表单，想用工具表单构建，但是这个如何绑定到一个html的点击事件上去？我看工具表单只能更行action绑定。

**Comment by ttken** [comment]
太过复杂的还是自己直接写代码吧。
![image](https://user-images.githubusercontent.com/66815206/119586954-46adba00-be00-11eb-854d-061110d428f1.png)
有些页面还是要自己写的， 这个框架可以解决大部分后台问题。

**Comment by ttken** [comment]
~~~
use Dcat\Admin\Layout\Content;
public function pay(Content $content)
    {
        return  $content->body($this->payForm()); 
    }
~~~
body里面是字符串就行了。

**Comment by jqhph** [comment]
> > 没看明白，不过列的显示是可以通过条件判断去使用不同组件的，参考文档 https://learnku.com/docs/dcat-admin/2.x/display-and-expansion-of-columns/8091
> 
> 就是我这一列的显示是用的自定义的display输出的html标签显示的，删除图片就是js绑定一个ajax请求事件，现在我想多加一个添加图片的操作，是弹出模式框添加，就不知道怎么添加构造这个model弹框表单。我看文档只能在操作那一栏添加操作弹框，我这个是根据不同的条件添加这个删除图片按钮。

你还是没理解`Modal`组件的用法，多看看文档的示例代码吧

**Comment by ttken** [comment]
字段弹出窗口，里面什么功能自己随便写，不用绑定model
~~~
 $grid->column('shops')->display('查看') // 设置按钮名称
                ->modal(function ($modal) {
                    // 设置弹窗标题
                    $modal->title('服务门店 ');
                    $modal->icon('');
                    $all = $this->all_shops;
                    $str = "";
                    foreach ($all as $v) {
                        $str .= "<tr>";
                        $str .= "<td>" . $v . "</td>";
                        $str .= "<tr>";
                    }

                    return "<div style='padding:10px 10px 0'><table class=\"table table-bordered\">
                    <thead>
                      <tr>
                        <th scope=\"col\">门店名称</th> 
                      </tr>
                    </thead>
                    <tbody>
                     " . $str . "
                    </tbody>
                  </table></div>";
                });
~~~

**Comment by dmskys** [comment]
> 字段弹出窗口，里面什么功能自己随便写，不用绑定model
> 
> ```
>  $grid->column('shops')->display('查看') // 设置按钮名称
>                 ->modal(function ($modal) {
>                     // 设置弹窗标题
>                     $modal->title('服务门店 ');
>                     $modal->icon('');
>                     $all = $this->all_shops;
>                     $str = "";
>                     foreach ($all as $v) {
>                         $str .= "<tr>";
>                         $str .= "<td>" . $v . "</td>";
>                         $str .= "<tr>";
>                     }
> 
>                     return "<div style='padding:10px 10px 0'><table class=\"table table-bordered\">
>                     <thead>
>                       <tr>
>                         <th scope=\"col\">门店名称</th> 
>                       </tr>
>                     </thead>
>                     <tbody>
>                      " . $str . "
>                     </tbody>
>                   </table></div>";
>                 });
> ```

你这个字段只能显示一个弹框，我是这一列有多个展示，你看我的图片，我的是这一列有操作，又有相册展示，我的操作没有弹框的时候是绑定ajax事件，但是现在我想多加一个添加相册功能也要放在这一列，我就是不知道怎么构造弹框，绑定弹框。

**Comment by dmskys** [comment]
> > > 没看明白，不过列的显示是可以通过条件判断去使用不同组件的，参考文档 https://learnku.com/docs/dcat-admin/2.x/display-and-expansion-of-columns/8091
> > 
> > 
> > 就是我这一列的显示是用的自定义的display输出的html标签显示的，删除图片就是js绑定一个ajax请求事件，现在我想多加一个添加图片的操作，是弹出模式框添加，就不知道怎么添加构造这个model弹框表单。我看文档只能在操作那一栏添加操作弹框，我这个是根据不同的条件添加这个删除图片按钮。
> 
> 你还是没理解`Modal`组件的用法，多看看文档的示例代码吧

我看了，但是不满足我的需求呀。。。只能绑定一个字段，我的是这样渲染的。
`   // 显示多图
        $grid->column('albums')->display(function ($albums) {
            $albums_show = '';
            foreach ($albums as $album) {
                /** @var UserAlbum $album */
                $id = $album->id;
                $albums_show .= '<img data-action="preview-img" src="' . $album->image . '" style="max-width:100px;max-height:100px;cursor:pointer" class="img img-thumbnail">';
                $albums_show .= '<button style="margin-left:10px;" class="btn btn-primary btn-sm grid-row-album-delete" data-id="' . $id . '">' . trans('delete picture') . '</button>'; //这里我多加了一个删除事件，用ajax绑定 .grid-row-album-delete 删除，现在我想多加个一个按钮绑定一个弹框表单，进行添加相册，请问这个怎么实现？
            }
            return $albums_show;
        });`

**Comment by dmskys** [comment]
> 太过复杂的还是自己直接写代码吧。
> ![image](https://user-images.githubusercontent.com/66815206/119586954-46adba00-be00-11eb-854d-061110d428f1.png)
> 有些页面还是要自己写的， 这个框架可以解决大部分后台问题。

如果自己写这些页面，视图是怎么构建的，这个文档好像没说明呢？
