### ISSUE TITLE
英文文档连结失效

### ISSUE THREAD

**Issue by pkkbkraa** [jqhph/dcat-admin#1249]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
请问有英文的文档吗?目前看英文文档是连不上的

**Comment by jqhph** [comment]
目前官网还没上线，暂时关闭了，可以先自行构建 https://github.com/dcat-admin/docs/tree/master/en-2.x
