### ISSUE TITLE
Grid inside the form

### ISSUE THREAD

**Issue by attentive20** [jqhph/dcat-admin#1252]
- Laravel Version: 8.xx
- PHP Version: 7.4
- Dcat Admin Version: 2.0.24

### Description:
Hello! Is it possible to fit a table into a form? In laravel-admin it looks like this:
![Laravel-AdminDemoPost1](https://user-images.githubusercontent.com/71190913/118048523-0f152b80-b385-11eb-9956-e7cf8480037a.jpg)
In the controller:
![Laravel-AdminDemoPost](https://user-images.githubusercontent.com/71190913/118048668-4683d800-b385-11eb-9909-da91e6fc91f1.jpg)

**Comment by jqhph** [comment]
Yes, but with a slight difference
```php
    public function edit($id, Content $content)
    {
        return $content
            ->title('...')
            ->row($this->form()->edit($id))
            ->row(new Grid(PostComment::where('post_id', $id), function (Grid $grid) {
                $grid->setName('comment');
                $grid->setResource('post-comments');
                $grid->title('comment');
                $grid->description('...');
                
                ...
            }));
    }
```

**Comment by attentive20** [comment]
Great, it's okay, thanks.
