### ISSUE TITLE
列过滤支持二级或者多级显示吗？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1254]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
比如这种
![image](https://user-images.githubusercontent.com/11988030/118102478-6f4eb080-b40b-11eb-971a-c498f0879d97.png)
支持 类似这种显示吗？
![image](https://user-images.githubusercontent.com/11988030/118102722-b3da4c00-b40b-11eb-8445-c0b9782d0930.png)

**Comment by jqhph** [comment]
不支持，可以参考源码自己实现

**Comment by shunhua** [comment]
> 不支持，可以参考源码自己实现

嗯 好的
