### ISSUE TITLE
Analogue of the totalRow method. Reaction to filters.

### ISSUE THREAD

**Issue by attentive20** [jqhph/dcat-admin#1255]
- Laravel Version: 8.xx
- PHP Version: 7.4
- Dcat Admin Version: 2.0.24

### Description:

I cannot understand from the documentation if there is an analogue of the totalRow method, which allows you to get totals for columns with sums. If I try to apply something like this

`$grid->header(function ($collection) use ($grid) {
                 $query = Model::query();
                  return $query->sum('sum');
});`

the amount is calculated, but does not respond to filters. In laravel-admin, a similar construction allowed getting a dynamic result based on the selected filters.

**Comment by jqhph** [comment]
try
```php
$grid->header(function ($collection) use ($grid) {
    $query = Model::query();

    $grid->model()->getQueries()->unique()->each(function ($value) use (&$query) {
        if (in_array($value['method'], ['paginate', 'get', 'orderBy', 'orderByDesc'], true)) {
            return;
        }

        $query = call_user_func_array([$query, $value['method']], $value['arguments'] ?? []);
    });

    $data = $query->sum('sum');

    ...
});
```

**Comment by attentive20** [comment]
Thanks It works.

**Comment by attentive20** [comment]
Are there any plans to make a method similar to totalRow to simplify the calculation of totals?
