### ISSUE TITLE
提个问题：权限 场景1，

### ISSUE THREAD

**Issue by cnPauLi** [jqhph/dcat-admin#126]
提个问题：权限 场景1，创建的权限是数据库中的，但是标识是写在代码中的，假如数据库被删除了，那重新创建的话就不太好找标识了，建议使用反射的方式，通过注释标注每个方法，然后后台直接扫描所有方法，按模块，类、方法的方式分级，最后给于权限分配，存入数据库，这样不管什么情况下，都可以调整权限，

**Comment by jqhph** [comment]
建议你可以把权限标识定义成常量，这样就不会不好找了。
