### ISSUE TITLE
关于表单弹窗的使用。

### ISSUE THREAD

**Issue by bkdlee** [jqhph/dcat-admin#1262]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
感谢你提供的这个项目，非常好用。
基于你的项目，我在开发公司的后台管理系统。
碰到了一个问题，不知道怎么实现。

使用fullCalendar.js https://fullcalendar.io/ 做一个日历显示的页面。
想做成一个点击日历事项 弹出修改表单的效果。
在单独使用 Form::dialog 时没有问题。

但是在使用fullCalendar 提供的drop和resize 功能之后，弹窗效果就失效了。
试着使用 Dcat.triggerReady() 也没有作用。使用的方法是按照 Tree.js 里的示例来写的。

**Comment by bkdlee** [comment]
不使用Form::dialog生成 Javascript 代码。直接用Dcat.DialogForm(opts); 并且用 fullCalendar 提供的eventAfterAllRender 来调用，可以解决问题。是不是可以在DialogForm里增加一个reload用以在页面dom改变的情况下，重新载入表单弹窗。

**Comment by jqhph** [comment]
你需要这个`reload`用来实现什么功能？因为我想不到这个`reload`的使用场景

**Comment by bkdlee** [comment]
谢谢回复。我的问题是Form::dialog如何绑定动态生成的内容？
`Form::dialog('New')->click('.fc-event')->success('Dcat.reload()');`
我需要绑定的.fc-event是动态生成的。可能我用Dcat.triggerReady(); 的方法不对。或者是我没有找到合适的方法。

**Comment by jqhph** [comment]
那你还是自己写js吧

**Comment by bkdlee** [comment]
哦，了解了，谢谢回复。
