### ISSUE TITLE
关于多后台的建议

### ISSUE THREAD

**Issue by seth-shi** [jqhph/dcat-admin#1264]
- Laravel Version: 7.x
- PHP Version: 7.4
- Dcat Admin Version: 1.7.9

### Description:
现在使用到多后台, 但是感觉功能还是不够完善.
有一下几个建议, 
* `admin:app` 增加一个参数 `--migration` 生成新的迁移文件.
* `config/*admin.php`的`database`增加一个表后缀/前缀的参数, 这样子就不用修改这么多表名
* 内置的所有模型如`Administrator`获取配置时不要简单的`config()`, 而是自己实现`$this->config()`, 然后如果用户想自定义模型, 就可以继承`Dcat`的模型,然后快速进行多后台管理

****

不知道作者是否愿意对这些功能进行参考, 如果可以的话, 我会提交一个 PR

**Comment by jqhph** [comment]
感谢建议，欢迎提交PR~

**Comment by seth-shi** [comment]
刚翻了源码, 才看到有一个 switch app 的操作. 是我之前肤浅了.
我还在心想, 多后台重新了模型类, 然后还要自定义表名
![image](https://user-images.githubusercontent.com/28035971/118583784-324a3b80-b7c8-11eb-87e4-72fd6522d06b.png)
