### ISSUE TITLE
Set Admin Auth to use the same as Laravel Front End Auth (guard: web) cause logged out issue

### ISSUE THREAD

**Issue by jay2success** [jqhph/dcat-admin#1266]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
Hi, i want the auth to be linked to Front End. If logged into Admin, it will also logged in into FE and vice versa.
I already try this on z-song laravel admin and its working but on dcat-admin, it keeps logging out when i go to Front End.
My steps is changing guard on admin as web and use User model.
Please guide how to set this so it doesn't cause logging out issue.

### Steps To Reproduce:
config/admin.php

'auth' => [
        'guard' => 'web'
        'guards' => [
            'admin' => [
                'driver'   => 'session',
                'provider' => 'admin',
            ],
        ],

        'providers' => [
            'admin' => [
                'driver' => 'eloquent',
                'model'  => App\Models\User::class,
            ],
        ],
],

**Comment by jqhph** [comment]
Set the value of the configuration variable `admin.route.enable_session_middleware` to `true`
