### ISSUE TITLE
在异步表格中想做一个添加功能，加了一个工具按钮，但是按钮不能正常使用。

### ISSUE THREAD

**Issue by yhhhhh** [jqhph/dcat-admin#1267]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
在异步表格中想做一个添加功能，加了一个工具按钮，但是按钮不能正常使用。
要如何正确使用？

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/31406137/118780384-92230e00-b8be-11eb-88bb-babe982930a2.png)
![image](https://user-images.githubusercontent.com/31406137/118779981-2ccf1d00-b8be-11eb-8cf6-0f3eb581cb9b.png)

**Comment by ceo404** [comment]
兄弟解决了么
