### ISSUE TITLE
dcat中怎么按关联表中的字段排序？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1269]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
比如用户表和分类表 怎么在用户列表按照分类表中的字段排序呢？

**Comment by shunhua** [comment]
![image](https://user-images.githubusercontent.com/11988030/118906566-939d1680-b950-11eb-9688-10485ea50eb0.png)
就是类似这种

**Comment by shunhua** [comment]
按照文档写了关联表字段排序 一对多时候 是不是无效的啊？
![image](https://user-images.githubusercontent.com/11988030/118931220-4da87880-b979-11eb-8c60-ffd7a9044cef.png)
![image](https://user-images.githubusercontent.com/11988030/118931251-59943a80-b979-11eb-875f-f8fb4c69ddb7.png)

**Comment by jqhph** [comment]
仅支持一对一关联关系字段排序，参考文档 https://learnku.com/docs/dcat-admin/2.x/use-and-extension-of-columns/8090

**Comment by shunhua** [comment]
> 仅支持一对一关联关系字段排序，参考文档 https://learnku.com/docs/dcat-admin/2.x/use-and-extension-of-columns/8090

一对多的不支持？那一对多的怎么处理好些呢

**Comment by shunhua** [comment]
> 仅支持一对一关联关系字段排序，参考文档 https://learnku.com/docs/dcat-admin/2.x/use-and-extension-of-columns/8090

![image](https://user-images.githubusercontent.com/11988030/118934840-661a9200-b97d-11eb-8e58-3e17bf7376b3.png)
文档里 说的支持的啊 。。。

**Comment by shunhua** [comment]
> 仅支持一对一关联关系字段排序，参考文档 https://learnku.com/docs/dcat-admin/2.x/use-and-extension-of-columns/8090

那 hasMany 不支持的话 ，怎么处理我这种情况啊

**Comment by jqhph** [comment]
你可以考虑一下用sql怎么写出一对多关联字段的排序，能写成sql的dcat就能支持

**Comment by shunhua** [comment]
这个后期版本会考虑加上吗？或者有合适的处理方案？

**Comment by shunhua** [comment]
sortable  能在 a字段 上排序 b字段吗？  比如排序按钮在a字段  实际处理的是按b字段排序的

**Comment by jqhph** [comment]
最好在当前表加一个字段排序，像这种一对多的是没办法直接排的

**Comment by jqhph** [comment]
> sortable 能在 a字段 上排序 b字段吗？ 比如排序按钮在a字段 实际处理的是按b字段排序的

这个功能已经有了，你自己看里面的参数或者文档

**Comment by shunhua** [comment]
> 最好在当前表加一个字段排序，像这种一对多的是没办法直接排的

我现在已经是按同表排序了 但是显示多一列 比较难受  所以考虑在原字段对新加字段排序

**Comment by shunhua** [comment]
> sortable

sortable(这里面的参数吗？)

**Comment by shunhua** [comment]
> > sortable 能在 a字段 上排序 b字段吗？ 比如排序按钮在a字段 实际处理的是按b字段排序的
> 
> 这个功能已经有了，你自己看里面的参数或者文档
![image](https://user-images.githubusercontent.com/11988030/119077725-6e2f0c00-ba27-11eb-90e7-85ac6a20a02e.png)

我这样写  无效啊 ，record_time为虚拟字段  是不是不能与 display一起使用啊？

**Comment by shunhua** [comment]
试了新版本 是可以的  没问题  ，我用的 v1.7.8版本的 一直是按虚拟字段排序
