### ISSUE TITLE
表格筛选能交互希望能支持常规的模式

### ISSUE THREAD

**Issue by terranc** [jqhph/dcat-admin#127]
现在的筛选交互方式虽然很炫酷，但在实际项目中会有个痛点，就是在筛选一些条件后，在表格里操作一番后，会发现不知道现在筛选的条件是什么，还得再去点一下筛选按钮才知道，而laravel-admin虽然默认筛选是收起的，但可以支持调用expand方法默认展开的。

![image](https://user-images.githubusercontent.com/224353/82173217-023f3280-98ff-11ea-9d14-4188c3e9bc55.png)

![image](https://user-images.githubusercontent.com/224353/82173358-842f5b80-98ff-11ea-9b21-6a70e56318f7.png)

**Comment by jqhph** [comment]
支持常规模式的，文档有些

**Comment by terranc** [comment]
能支持在resolving里给全局的grid设置模式吗？不然每个页面都要去设置有点烦，而且多人团队开发的时候，得一个个去叮嘱，毕竟默认生成的代码是边栏模式。

**Comment by jqhph** [comment]
可以

**Comment by terranc** [comment]
好像平铺的模式不能用colmun了，会导致筛选项比较多时很占用页面空间

**Comment by jqhph** [comment]
你可以设置表单字段的宽度
