### ISSUE TITLE
列表 bug

### ISSUE THREAD

**Issue by chowjiawei** [jqhph/dcat-admin#1271]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
好几个页面都是这样子，点了之后，其余才会正常
![image](https://user-images.githubusercontent.com/59349609/119068734-5bacd680-ba17-11eb-82a7-3aee5bbfb7a6.png)

![image](https://user-images.githubusercontent.com/59349609/119068723-564f8c00-ba17-11eb-9536-635384a6b0da.png)

**Comment by jqhph** [comment]
这个目前没找到解决方法
