### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by attentive20** [jqhph/dcat-admin#1274]
- Laravel Version: 8.xx
- PHP Version: 7.4
- Dcat Admin Version: 2.0.24

### Description:
When I perform some action (for example from the grid), I need to see a description of the error that has occurred. But all I see is this:
![500_error](https://user-images.githubusercontent.com/71190913/119239309-efce8900-bb50-11eb-89b6-7c16b2d4fdb8.jpg)
For example, in laravel-admin with a similar configuration, there was a description:
![500_error_laravel-admin](https://user-images.githubusercontent.com/71190913/119239383-505dc600-bb51-11eb-8f72-ef024169d07a.jpg)
This also applies to forms. If an error occurs while saving, I need to see its description, but I see "500 ..."
In the config file .env `APP_DEBUG=true`
Is it possible to influence this the settings?

**Comment by jqhph** [comment]
You can see the full error message in the log `storage/logs/*`

**Comment by attentive20** [comment]
I can look at it in the process of debugging, this is not a problem. The question of how to display this on the screen is similar to what I described above.

**Comment by jqhph** [comment]
Not supported

**Comment by attentive20** [comment]
Got it, thanks.
