### ISSUE TITLE
What's wrong with the deletion?

### ISSUE THREAD

**Issue by attentive20** [jqhph/dcat-admin#1275]
- Laravel Version: 8.xx
- PHP Version: 7.4
- Dcat Admin Version: 2.0.24

### Description:

The delete function does not work for me anywhere. For example:
Grid
![Delete_1](https://user-images.githubusercontent.com/71190913/119240384-d4b34780-bb57-11eb-93b8-377666a43f79.jpg)
Forms
![Delete_forms](https://user-images.githubusercontent.com/71190913/119240395-dda41900-bb57-11eb-90dc-8c5a9eedbf6c.jpg)
File selection
![Delete_files](https://user-images.githubusercontent.com/71190913/119240399-e4329080-bb57-11eb-9c6b-1c50c78a0968.jpg)
When I click on this function, nothing happens, nothing at all. As if it is not there or it is blocked. All other functions work fine. What am I doing wrong? Could it be the permissions?

**Comment by jqhph** [comment]
Press `F12` , then switch to the `Network` tab to see network activity

**Comment by attentive20** [comment]
This is what I see
![Delete_error_screen](https://user-images.githubusercontent.com/71190913/119284610-c6912400-bc48-11eb-8851-e6c8f3bcff58.jpg)

**Comment by jqhph** [comment]
Add to the `resources/lang/{locale}/admin.php`

```php
    'client' => [
        'delete_confirm'    => 'Are you sure to delete this item ?',
        'confirm'           => 'Confirm',
        'cancel'            => 'Cancel',
        'refresh_succeeded' => 'Refresh succeeded !',
        'close'             => 'Close',
        'selected_options'  => ':num options selected',
        'exceed_max_item'   => 'Maximum items exceeded.',
        'no_preview'        => 'No preview available.',

        '500' => 'Internal server error !',
        '403' => 'Permission deny !',
        '401' => 'Unauthorized !',
        '419' => 'Page expired !',
    ],
```

**Comment by attentive20** [comment]
It worked, thanks!
