### ISSUE TITLE
form中使用的自己的页面,怎么传值

### ISSUE THREAD

**Issue by yhhhhh** [jqhph/dcat-admin#1278]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.7

### Description:
表单用的自己的页面,怎么传值到页面中

**Comment by jqhph** [comment]
`1.x`版本只能使用`view()->share([xxx => xxx])`进行传值

**Comment by yhhhhh** [comment]
![image](https://user-images.githubusercontent.com/31406137/119316152-30411a80-bca9-11eb-991e-c13133d5bb3c.png)
会报错
![image](https://user-images.githubusercontent.com/31406137/119316172-36cf9200-bca9-11eb-9d39-c5f91d23d1eb.png)

**Comment by jqhph** [comment]
建议你先看看laravel的视图相关文档
