### ISSUE TITLE
表格排序bug

### ISSUE THREAD

**Issue by tingfeng-key** [jqhph/dcat-admin#1280]
- Laravel Version: 8.31.0
- PHP Version: ^8.0
- Dcat Admin Version: 2.1.0

### Description:

如果数据中排序字段order的值都为同一个数值时，排序无法保持
### Steps To Reproduce:
表格代码：
![image](https://user-images.githubusercontent.com/13976521/119430734-e0fbf800-bd43-11eb-8827-3c0569bdae41.png)
模型代码：
![image](https://user-images.githubusercontent.com/13976521/119430765-efe2aa80-bd43-11eb-9ad8-9a27160efb84.png)
数据表：
![image](https://user-images.githubusercontent.com/13976521/119430837-0d177900-bd44-11eb-8c57-5016b03c932b.png)
实际出问题的代码：
![image](https://user-images.githubusercontent.com/13976521/119430897-25879380-bd44-11eb-973e-0b4817d881c3.png)

`$swapWithModel`打印出来为null

**Comment by jqhph** [comment]
是的，目前用的排序的包不支持，需要所有数据都用model create创建
