### ISSUE TITLE
有JS报错Uncaught TypeError: $(...).iCheck is not a function

### ISSUE THREAD

**Issue by ttken** [jqhph/dcat-admin#1281]
Uncaught TypeError: $(...).iCheck is not a function

![image](https://user-images.githubusercontent.com/66815206/119459153-06066000-bd70-11eb-8aeb-c3456fe40805.png)

![image](https://user-images.githubusercontent.com/66815206/119459245-16b6d600-bd70-11eb-8308-bbecdfdaa7e4.png)

**Comment by jqhph** [comment]
dcat-admin没有使用icheck，你这个代码自己加的？

**Comment by ttken** [comment]
不是我加的，我查查，这里面还有pajax。

**Comment by ttken** [comment]
不去细研究了，最近忙项目，直接添加对应的代码，让icheck能用。
感谢回复 。
~~~
Admin::js('https://cdn.bootcdn.net/ajax/libs/iCheck/1.0.3/icheck.min.js');
Admin::css('https://cdn.bootcdn.net/ajax/libs/iCheck/1.0.3/skins/all.min.css');
~~~
