### ISSUE TITLE
2.0版本 操作日志没了么，这个可以有么

### ISSUE THREAD

**Issue by running8gubin** [jqhph/dcat-admin#1282]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 2.1.0

### Description:
升级后发现，少了操作日志  这个表也没有，admin_operation_log

**Comment by jqhph** [comment]
操作日志已经移出来了，可以自己实现，或者安装这个扩展 https://github.com/dcat-admin/operation-log

**Comment by ttken** [comment]
纯代码那种日志意义不大，需要自己写个日志类，记录有用的信息。
比如
用户  更新了文章-1   时间 
这种还是需要自己来写，方便一些。
