### ISSUE TITLE
关于表单验证error tips的显示位置

### ISSUE THREAD

**Issue by terranc** [jqhph/dcat-admin#129]
报错的tips是不是在输入框的下方美观点？也避免输入框的抖动。

![image](https://user-images.githubusercontent.com/224353/82237249-efad1380-9967-11ea-8dd4-fe0ff1bcaad8.png)

改后：
![image](https://user-images.githubusercontent.com/224353/82238398-cab9a000-9969-11ea-81d0-ff425980cd59.png)

**Comment by terranc** [comment]
![image](https://user-images.githubusercontent.com/224353/82238214-7f9f8d00-9969-11ea-8ada-9fcd48e04bb8.png)
当把help-block放在下面来以后，还顺带解决了label和form组件水平对不齐的问题

**Comment by jqhph** [comment]
好的感谢建议，这个会考虑优化；

另外关于对其这点是不会去做的，因为如果像是textare这样比较高的表单对其了会很难看。

**Comment by terranc** [comment]
对比看了下laravel-admin的，对齐是没这个问题的，错误也是放上面，之前都没这个强烈的感觉，所以可能还是对齐的问题。
应该与textarea没关系。
![image](https://user-images.githubusercontent.com/224353/82273084-0d519b80-99af-11ea-855c-711d3f79bb5f.png)

**Comment by jqhph** [comment]
好的，我会优化下这个功能，让label往下移一点
