### ISSUE TITLE
Uncaught TypeError: Dcat.wait is not a function

### ISSUE THREAD

**Issue by yexk** [jqhph/dcat-admin#1290]
- Laravel Version: v8.43.0
- PHP Version: 7.4.16
- Dcat Admin Version: 2.1.0-beta

### Description:
![image](https://user-images.githubusercontent.com/19749521/119758343-f6eef180-bed8-11eb-8da8-83d0ead1fe58.png)

### Steps To Reproduce:
update from 2.0.22-bate to 2.1.0-beta

**Comment by jqhph** [comment]
升级步骤不对，请仔细阅读升级文档

**Comment by yexk** [comment]
嗯呢。谢谢。已经找到了。
```
php artisan admin:update
```
