### ISSUE TITLE
Laravel Octane 在laravel版本是5.8的dcat上能不能使用

### ISSUE THREAD

**Issue by LazyBaby** [jqhph/dcat-admin#1291]
- Laravel Version: 5.8
- PHP Version: 7.2
- Dcat Admin Version: 2.1.0-beta

Laravel Octane 是laravel 8 才有的(因为我只在8上面找到了文档)，但是我看到dcat文档说已经兼容Octane了，我没有看懂，因为dcat兼容laravel 5.5 ~ 8的版本，说的是PHP版本>=7.1是满足laravel5.5版本和dcat的最低要求，如果laravel版本是8的话PHP版本是不能低于7.3的，那么dcat文档说docat 2.0.23版本开始兼容Octane，是只有laravel 8版本的dcat兼容还是所有的dcat都兼容？之前都是直接装的swool扩展，现在想用官方的

**Comment by jqhph** [comment]
看看laravel octane支持的最低laravel版本是什么，依据这个安装就行了

**Comment by LazyBaby** [comment]
> 看看laravel octane支持的最低laravel版本是什么，依据这个安装就行了
好的

**Comment by LazyBaby** [comment]
> 看看laravel octane支持的最低laravel版本是什么，依据这个安装就行了

好的
