### ISSUE TITLE
权限管理中无法添加http路径

### ISSUE THREAD

**Issue by bylucky** [jqhph/dcat-admin#1297]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.1

### Description:
<img width="666" alt="image" src="https://user-images.githubusercontent.com/9688263/120066481-3a985580-c0a9-11eb-942f-5e71d30d4398.png">
大牛好，我遇到一个问题，如上图：权限管理中无法添加http路径，新建和修改都无法选择，请问是什么问题？

**Comment by jqhph** [comment]
键入 空格+回车 可以添加新的路径

**Comment by bylucky** [comment]
已经修复
原因：admin.route.prefix 设置成了: / 
代码：src/Http/Controllers/PermissionController.php：153行
`           if (! Str::startsWith($uri = $route->uri(), $prefix) && $prefix) {
                return;
            }`

此处未对 prefix == "/" 时进行处理

**Comment by bylucky** [comment]
@jqhph  对开源者致以崇高的敬意

**Comment by jqhph** [comment]
> 已经修复
> 原因：admin.route.prefix 设置成了: /
> 代码：src/Http/Controllers/PermissionController.php：153行
> ` if (! Str::startsWith($uri = $route->uri(), $prefix) && $prefix) { return; }`
> 
> 此处未对 prefix == "/" 时进行处理

感谢反馈
