### ISSUE TITLE
如何获取form表单中select的值？并根据选择的值动态增加form表单中的行

### ISSUE THREAD

**Issue by coderdavi** [jqhph/dcat-admin#1298]
- Laravel Version: 8.*
- PHP Version: 7.3
- Dcat Admin Version: 2.0

### Description:
![1](https://user-images.githubusercontent.com/54616280/120076817-16a13800-c0da-11eb-8f17-337291bfb008.png)
form表单中选择平台名，根据选择的平台名从数据库中查询出平台所需要的参数名，类似于下面的App/Secret，选择不同的平台参数的数量可能不同，form表单相应的增加多行。
我现在的实现方式是使用form中when方法，提前把平台id写好，实际上应该是form->select选择的结果。想请教下是否有更好的实现方式呢
![2](https://user-images.githubusercontent.com/54616280/120076992-c24a8800-c0da-11eb-9aba-cf8c26fff0d2.png)

**Comment by jqhph** [comment]
```php
$platField = $form->select('plat_id')->...;

Admin::script(
    <<<JS
$('{$platField->getElementClassSelector()}').on('change', function () {
    // 获取选中值 
    var value = this.value;

     ....
});
JS
);
```

**Comment by coderdavi** [comment]
> ```
> $platField = $form->select('plat_id')->...;
> 
> Admin::script(
>     <<<JS
> $('{$platField->getElementClassSelector()}').on('change', function () {
>     // 获取选中值 
>     var value = this.value;
> 
>      ....
> });
> JS
> );
> ```

jq获取plat_id这个我已经实现了 但是不会动态增加form中的行，还请抽空帮忙指点一下 谢谢

**Comment by changanbeilu39hao** [comment]
> > ```
> > $platField = $form->select('plat_id')->...;
> > 
> > Admin::script(
> >     <<<JS
> > $('{$platField->getElementClassSelector()}').on('change', function () {
> >     // 获取选中值 
> >     var value = this.value;
> > 
> >      ....
> > });
> > JS
> > );
> > ```
> 
> jq获取plat_id这个我已经实现了 但是不会动态增加form中的行，还请抽空帮忙指点一下 谢谢

请问有解决吗
