### ISSUE TITLE
详情动作中，不能获取模型

### ISSUE THREAD

**Issue by ztj1993** [jqhph/dcat-admin#130]
- Laravel Version: 7.11.0
- PHP Version: 1.3.4
- Dcat Admin Version: 7.4.3

### Description:
我创建了详情动作，但不能获取模型。

### Steps To Reproduce:
我创建了详情动作，但不能获取模型。
http://www.dcatadmin.com/docs/master/action-show.html

```
$show->tools(function (Show\Tools $tools) {
    $tools->append(new Copy());
});
```
```
dump($this->parent);  //null
```

请更新一下此处的文档

**Comment by jqhph** [comment]
文档其实有demo，你可以参考下 #69
