### ISSUE TITLE
roles, permissions 404 not found

### ISSUE THREAD

**Issue by attentive20** [jqhph/dcat-admin#1300]
- Laravel Version: 8.xx
- PHP Version: 7.4
- Dcat Admin Version: 2.1.0

### Description:

http://localhost/admin/auth/users - ok
http://localhost/admin/auth/menu - ok 

http://localhost/admin/auth/roles - 404 not found
http://localhost/admin/auth/permissions - 404 not found

Can you please tell me what's wrong?

**Comment by jqhph** [comment]
Check if `config('admin.permission.enable')` return `false`

**Comment by attentive20** [comment]
> Check if `config('admin.permission.enable')` return `false`

Yes, `false`. If I change to `true`, also `404 not found` for http://localhost/admin/auth/roles and http://localhost/admin/auth/permissions, and access to other sections is denied.
![permission](https://user-images.githubusercontent.com/71190913/120160147-9a544500-c1fe-11eb-8923-6d0912fd3787.jpg)
I want to configure the permissions, but I cannot get to the page.

**Comment by jqhph** [comment]
Did you deleted the super admin role that `slug=administrator`?

**Comment by attentive20** [comment]
> Did you delete the super admin role that `slug=administrator`?

Yes, you are right, after restoring this role, access is OK, but the 404 problem is not resolved - links http://localhost/admin/auth/roles and http://localhost/admin/auth/permissions do not work...

**Comment by attentive20** [comment]
The problem has been resolved. I added an entry with a slug `auth-management` to the table `admin_permissions` and everything worked.
