### ISSUE TITLE
表单编辑成功后，能否拿到表单保存前的记录信息

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#1301]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
由于在表单保存后，需要对之前的数据做一些资源处理，需要拿到表单保存前的数据，请问这个能获取到吗？

**Comment by jqhph** [comment]
可以的，通过saving事件在把数据存储到某个变量中，然后在saved事件中获取到这个变量

**Comment by dmskys** [comment]
> 可以的，通过saving事件在把数据存储到某个变量中，然后在saved事件中获取到这个变量

请问这个怎么存储？文档没看到。

**Comment by hetoo** [comment]
https://learnku.com/docs/dcat-admin/2.x/event/8113

**Comment by dmskys** [comment]
> https://learnku.com/docs/dcat-admin/2.x/event/8113

如何在saving事件中把数据存储到某个变量？

**Comment by fangmuke** [comment]
> > https://learnku.com/docs/dcat-admin/2.x/event/8113
> 
> 如何在saving事件中把数据存储到某个变量？

![image](https://user-images.githubusercontent.com/26641510/134303259-dfeb4d79-d318-42e3-99c7-29a646f1e9f6.png)
不可以啊 @jqhph

**Comment by fangmuke** [comment]
> > https://learnku.com/docs/dcat-admin/2.x/event/8113
> 
> 如何在saving事件中把数据存储到某个变量？

![image](https://user-images.githubusercontent.com/26641510/134305837-f9ad9b1d-24d7-4ba1-8b73-9f3b25650214.png)
@jqhph 不可以啊
