### ISSUE TITLE
一个表单中如果有多个 multipleImage 或 multipleFile 字段的话，上传拖拽功能仅生效一次

### ISSUE THREAD

**Issue by windyson2008** [jqhph/dcat-admin#1314]
- Laravel Version: 7.x
- PHP Version: 5.x
- Dcat Admin Version: 2.1.0

### Description:
一个表单中如果有多个 multipleImage 或 multipleFile 字段的话，上传拖拽功能仅生效一次。后续添加图片或文件时，拖拽功能失效。

对于表单空间image, file 而言，其 blade 为 file.blade.php ，其中对于 webuploader 的拖拽功能来讲，目前代码中使用的是嵌入 dnd-area 的 css 样式，并在 js 中指定其 dnd 的 dom。但是有多个 dnd-area 标签的话会失效的感觉。

如果可以的话请修复，谢谢。
### Steps To Reproduce:
在一张表单里设定多个 multipleImage 或 multipleFile 字段。

**Comment by jqhph** [comment]
好的，我看下这个问题

**Comment by loumzy** [comment]
+1
