### ISSUE TITLE
怎么监听switch 变化

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1316]
- Laravel Version: 5.8.*
- PHP Version: 7.2
- Dcat Admin Version: 2.1.0-beta

### Description:
如图：
![image](https://user-images.githubusercontent.com/13138164/120946749-22db6400-c770-11eb-92c6-c844f628e5d6.png)

怎么监听switch 变化，去做一些其他处理。

**Comment by jqhph** [comment]
在form表单的`saving`事件中可以取到更新的值

**Comment by Ya-hui** [comment]
那怎么判断switch是否更新了呢？
