### ISSUE TITLE
copyable and editable

### ISSUE THREAD

**Issue by attentive20** [jqhph/dcat-admin#1322]
- Laravel Version: 8.xx
- PHP Version: 7.4
- Dcat Admin Version: 2.1.0

### Description:
Hello! If you use the copyable and editable methods together, you get the following (the impression that this is incorrect, an example from the demo):
![editable_copyable1](https://user-images.githubusercontent.com/71190913/121777939-338b4000-cb9d-11eb-8b24-b25750cfa271.jpg)
![editable_copyable2](https://user-images.githubusercontent.com/71190913/121777949-4aca2d80-cb9d-11eb-870c-7091b047a7ba.jpg)
![editable_copyable3](https://user-images.githubusercontent.com/71190913/121777967-62a1b180-cb9d-11eb-820d-afc222f76152.jpg)

**Comment by jqhph** [comment]
`copyable` and `editable` cannot be called together
