### ISSUE TITLE
文件导出抛异常

### ISSUE THREAD

**Issue by 775397252** [jqhph/dcat-admin#1324]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 2.*
### Description:
文件导出抛出异常
![image](https://user-images.githubusercontent.com/7972945/122005827-b0f6c080-cde8-11eb-81cf-15511be1022e.png)

### Steps To Reproduce:
执行到admin_exit();时候抛出异常，使用是自带的导出扩展。

![image](https://user-images.githubusercontent.com/7972945/122006335-498d4080-cde9-11eb-9028-01c8c9f63151.png)

**Comment by jqhph** [comment]
升级最新版本可以解决

**Comment by 775397252** [comment]
@jqhph 你好，我想知道怎么导致的？这个在有些环境是正常的，有些是会抛异常，升级版本可能会导致其他扩展不兼容

**Comment by 775397252** [comment]
验证数据量大的时候就会出现导出错误，
![image](https://user-images.githubusercontent.com/7972945/122349412-d289b080-cf7e-11eb-83b4-2424d68f9b8e.png)

**Comment by 775397252** [comment]
我自己再想想
