### ISSUE TITLE
关于工具按钮，有一个新的需求，您看看现有的功能是否可以实现？

### ISSUE THREAD

**Issue by ztj1993** [jqhph/dcat-admin#133]
- Laravel Version: 7.11.0
- PHP Version: 1.3.4
- Dcat Admin Version: 7.4.3

### Description:
假设，我详情页，有一个按钮：锁定用户。

点击锁定按钮，显示一个输入框，输入锁定的备注，然后点击确认，将备注和状态写入到数据表。

我设想的是通过弹窗表单实现，请问有没有好的解决方案？

**Comment by jqhph** [comment]
这个功能很容易实现，请查看文档工具表单章节
