### ISSUE TITLE
表单布局的bug hasmany和array下面不显示

### ISSUE THREAD

**Issue by ajiader** [jqhph/dcat-admin#1333]
- Laravel Version: 6.#.#
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.9

### Description:
![image](https://user-images.githubusercontent.com/4979798/122661324-b58df100-d1bb-11eb-8fcb-0264c16de7a9.png)
按照文档操作 表单点击新增按钮不显示对应的表单内容
![image](https://user-images.githubusercontent.com/4979798/122661353-fbe35000-d1bb-11eb-9387-23a62b88db11.png)

**Comment by jqhph** [comment]
这个是`2.x`版本的功能，`1.x`版本不支持这个功能
