### ISSUE TITLE
时间控件如何实现分钟时间间隔，只有选择0或者半小时这两个时间选择

### ISSUE THREAD

**Issue by pengwei1986** [jqhph/dcat-admin#1336]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
请问时间控件如何实现分钟时间间隔，只有选择0或者半小时这两个时间选择

**Comment by yaoxiang** [comment]
可以修改 `options` 属性实现。

更多设置请参考插件配置 [Datepicker v4 Docs](https://getdatepicker.com/4/Options)

### Example:

以下是参考样例

```PHP
namespace App\Admin\Controllers;
use Dcat\Admin\Grid;
...
$form->datetime('foo1')->options([
    'stepping'=>30
]);
...
```

页面效果如下

![image](https://user-images.githubusercontent.com/6754490/125205383-89dec200-e2b4-11eb-8cf9-8e9ac0b5ccf4.png)
![image](https://user-images.githubusercontent.com/6754490/125205422-b98dca00-e2b4-11eb-8ed9-a9d1b226ae07.png)
![image](https://user-images.githubusercontent.com/6754490/125205430-c4485f00-e2b4-11eb-9082-cb0af4202473.png)

**Comment by pengwei1986** [comment]
@yaoxiang 非常感谢，还想问下您，能设置只显示几个时间点吗？比如只有12点和18点可选
