### ISSUE TITLE
表单一对多控件，使用逻辑判断无法隔离单个case的逻辑显示

### ISSUE THREAD

**Issue by yaoxiang** [jqhph/dcat-admin#1338]
- Laravel Version: 8.45.1
- PHP Version: 7.3.26
- Dcat Admin Version: 2.1.0-beta

### Description:

1. 在Form\NestedForm匿名函数中，使用Form\NestedForm::when()方法对case表单项按需显示，出现单个case表单change事件后 ， 其他case表单项也被一同切换的情况。

### Steps To Reproduce:

以下是代码段样例
```php
namespace App\Admin\Controllers;
use Dcat\Admin\Form;

$form->hasMany('cases', function (Form\NestedForm $form) {
    ...
    $form->select('foo')
        ->options(['foo1'=>'foo1','foo2'=>'foo2'])
        ->when('foo1', function (Form\NestedForm $form) {
            $form->select('bar')->options(['bar1'=>'bar1','bar2'=>'bar2']);
        })->required();
   ...
});
```
> 说明 : 分别当添加2组case, new-1 和 new-2 ,  case[new-1][foo] 选择foo1值，case[new-1][bar] 状态 显示，case[new-2][foo] 选择 foo2值 case[new-1][bar] 和 case[new-2][bar] 都为隐藏

**Comment by jqhph** [comment]
暂不支持这种用法，需要自己写js控制
