### ISSUE TITLE
树形表格异步加载无极分类的时候，模态框类型的action除了根节点，其他的节点均失效

### ISSUE THREAD

**Issue by BigmasterU** [jqhph/dcat-admin#1339]
- Laravel Version: 5.7
- PHP Version: 7.2
- Dcat Admin Version: 1.7

### Description:
树形表格异步加载无极分类的时候，模态框类型的action除了根节点，其他的节点均失效，按钮是有的，但是按钮对应的模态框没有创建出来。

--------------------------根节点-----------------------------
![根节点action](https://user-images.githubusercontent.com/17021362/123062979-94d5cd80-d43f-11eb-9234-a6cc9b8ece77.png)
![根节点modal](https://user-images.githubusercontent.com/17021362/123063049-a323e980-d43f-11eb-8a49-83aef013fe83.png)

-------------------------子节点-------------------------------
![子节点action](https://user-images.githubusercontent.com/17021362/123063082-ad45e800-d43f-11eb-92c1-68d781f1a8f0.png)
![子节点modal](https://user-images.githubusercontent.com/17021362/123063132-ba62d700-d43f-11eb-87de-dccfcb0d12d2.png)

**Comment by jqhph** [comment]
1.x版本不支持，如果需要可以升级到2.x版本
