### ISSUE TITLE
1、表单字段动态显示；2、嵌套路由

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1343]
1、表单字段动态显示：
一个页面同时存在新增表单和弹窗编辑时（如菜单页），如果存在字段动态显示，就会出现切换一个另一个也切换的问题，应该是元素冲突。我暂时使用命名不同的字段，再在saving里面赋值来规避这个问题；
![image](https://user-images.githubusercontent.com/26995286/123244567-a211bb80-d516-11eb-848e-81f2bdec8281.png)

2、嵌套路由编辑问题：
 如果使用laravel的嵌套路由，在编辑、显示、删除子路由数据时（show/edit/destroy时），不能准备的找到参数，总是会去找上级路由的参数。例如嵌套路由路径为 parent/{parent}/child/{child}，在child路由列表，操作时，总是将id参数认为是parent，而不是chlid；暂时用重写相关方法手动获取参数
![image](https://user-images.githubusercontent.com/26995286/123245356-527fbf80-d517-11eb-9004-8a7e751c02c5.png)
![image](https://user-images.githubusercontent.com/26995286/123245394-5dd2eb00-d517-11eb-9f66-8caee5084454.png)

**Comment by jqhph** [comment]
1、你的处理方法没有错
2、不要继承`AdminController`，自己实现`resource`路由的相关增删改查方法
