### ISSUE TITLE
多库操作

### ISSUE THREAD

**Issue by feilongjump** [jqhph/dcat-admin#1345]
- Laravel Version: 8.48.1
- PHP Version: 8.0.2
- Dcat Admin Version: 2.1.0-beta
- stancl/tenancy Version: 3.4.4

### Description:
添加操作报错，这个扩展包是多租户的，所以，在添加的时候会创建新的数据库。
![image](https://user-images.githubusercontent.com/48574176/123406058-17e05a80-d5dd-11eb-9e41-9f9e6378270e.png)

如果在这段代码中注释事务，那么则是成功的，我只能用数据源的方式去处理还是说这是一个问题。
![image](https://user-images.githubusercontent.com/48574176/123406226-43634500-d5dd-11eb-998d-856800edc69b.png)

**Comment by jqhph** [comment]
`stancl/tenancy`我也在用，没有这个问题，你这个是租户中间件下的创建的话就不会报错

**Comment by feilongjump** [comment]
```
use App\Models\Tenant;

protected function form(): Form
{
    return Form::make(new Tenant(), function (Form $form) {
        $form->text('id', '标识')
            ->required()
            ->rules('alpha|max:20|unique:tenants,id')
            ->help('此标识用于访问地址，仅可使用英文字母');

        $form->text('name')->required();

        $form->hasMany('domains', function (Form\NestedForm $form) {
            $form->text('domain', '访问地址')
                ->required()
                ->rules('unique:domains,domain');
        });
    });
}
```
这个是创建租户的代码，开发环境相同的两台电脑，一台会报错但是创建成功，一台不会报错同样也是创建成功，这实在令我纳闷🤔

**Comment by ly2ang** [comment]
我也遇到了 这个问题，请问是怎么解决的。试过租户中间件也是一样的问题
` InitializeTenancyByDomain::class,
    PreventAccessFromCentralDomains::class`

**Comment by 726555132** [comment]
> ```
> use App\Models\Tenant;
> 
> protected function form(): Form
> {
>     return Form::make(new Tenant(), function (Form $form) {
>         $form->text('id', '标识')
>             ->required()
>             ->rules('alpha|max:20|unique:tenants,id')
>             ->help('此标识用于访问地址，仅可使用英文字母');
> 
>         $form->text('name')->required();
> 
>         $form->hasMany('domains', function (Form\NestedForm $form) {
>             $form->text('domain', '访问地址')
>                 ->required()
>                 ->rules('unique:domains,domain');
>         });
>     });
> }
> ```
> 
> 这个是创建租户的代码，开发环境相同的两台电脑，一台会报错但是创建成功，一台不会报错同样也是创建成功，这实在令我纳闷🤔

请问你 后来是怎么解决的呢

**Comment by ly2ang** [comment]
@feilongjump 请问你后来是怎么解决的呢，麻烦帮忙解答一下T_T

**Comment by feilongjump** [comment]
> @feilongjump请问你这是怎么解决的呢，麻烦帮忙解决一下T_T
我不知道你的是什么问题，我的问题在重新安装包（有可能是因为修复了某些 bug）后，可以解决了，不过我也没有继续用下去。

**Comment by ly2ang** [comment]
> > @feilongjump请问你这是怎么解决的呢，麻烦帮忙解决一下T_T
> > 我不知道你的是什么问题，我的问题在重新安装包（有可能是因为修复了某些 bug）后，可以解决了，不过我也没有继续用下去。

好的，我再去试试，感谢你的解答
