### ISSUE TITLE
字段动态显示加了验证规则以后，用Ajax 表单提交后，报错

### ISSUE THREAD

**Issue by hetoo** [jqhph/dcat-admin#1346]
- Laravel Version: #.#.#
- PHP Version: 8.0
- Dcat Admin Version: 2.1.0-beta

### Description:
表单中加了动态字段显示，并添加了验证规则
然后禁用了默认ajax表单提交 $form->ajax(false);
JS中添加提交动作，出现报错信息
```
$("#save_form").click(function() {
      $('#{$form->getElementId()}').submit();
});
```
如下：
`Error: Can only throw objects in file /home/vagrant/code/********/vendor/dcat/laravel-admin/src/Http/Middleware/Pjax.php on line 51`

### Steps To Reproduce:
正常提交，则可以正常显示验证信息，并提交成功

**Comment by jqhph** [comment]
为什么要去掉ajax提交？这样很多功能都没办法使用

**Comment by hetoo** [comment]
已经通过其他方案，解决了，谢谢你
