### ISSUE TITLE
动态监听元素生成 js代码 在form表单中 一对多子项中 select2插件UI部分节点会丢失

### ISSUE THREAD

**Issue by yaoxiang** [jqhph/dcat-admin#1347]
- Laravel Version: 8.45.1
- PHP Version: 7.3.26
- Dcat Admin Version: 2.1.0-beta

### Description:
动态监听元素生成 js代码 在form表单中 select2插件UI部分节点会丢失

### Steps To Reproduce:
以下是代码样例：
```PHP
namespace App\Admin\Controllers;
use Dcat\Admin\Form;

$form->hasMany( 'cases' , function (Form\NestedForm $form) {
    ...
    $form->select( 'foo' )->option( ['foo1'=>'foo1'] )->required();
    ...
});

$formId = $form->getElementId();

admin_script(<<<EOF
    Dcat.init( '#$formId [name$="][foo]' , function ( \$this, id ) {
           \$this.on( 'change' , function () {
                console.log( $(this) )
                ...
           });
    });
EOF
);
...
```

以下是图例：
这是没加js代码的UI展示
![image](https://user-images.githubusercontent.com/6754490/123514622-7fbea000-d6c6-11eb-90df-1f344e6daa3b.png)
这是加了js代码的UI展示
![image](https://user-images.githubusercontent.com/6754490/123514998-5c94f000-d6c8-11eb-80a9-f7c70feb8fb5.png)

假如代码改为 $.off().on()是ok的。
```PHP
$formId = $form->getElementId();

admin_script(<<<EOF
    $( '#$formId' ).off( 'change' , '[name$="][foo]' ).on( 'change' , '[name$="][foo]' ), function (e) {
                console.log($(this))
                ...
    });
EOF
);
...
```

**Comment by jqhph** [comment]
`Dcat.init`一般是在自定义`Form`表单组件中使用的，你用下面那个正常的代码就好
