### ISSUE TITLE
表格中用了link的话如果不实体化 可以直接运行XSS

### ISSUE THREAD

**Issue by ceo404** [jqhph/dcat-admin#1349]
- Laravel Version: 6.X.X
- PHP Version: 7.4.2
- Dcat Admin Version: #.#.#

### Description:
如果表格中使用Link方法并且 此方法的显示标题为XSS 或 HTML 代码
不进行手动处理的话回导致XSS注入 HTML代码运行

实体化后效果
![image](https://user-images.githubusercontent.com/31309806/123604020-05f4f680-d82d-11eb-8c4e-4bf7ccd67e5c.png)

**Comment by jqhph** [comment]
用`display`方法自己转义一下，或者自己写`a`标签代码

**Comment by ceo404** [comment]
自己已经解决了 提交一下这个 感觉这个影响可有可无 服务验证不到位的话还是有点危险

**Comment by jqhph** [comment]
好的，感谢建议，可能后面会加个参数控制是否转义
