### ISSUE TITLE
关于权限方面的问题

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#135]
有一个问题，如果用户（User）有多种职业（Job，如：教师，高管......），不同的职业有不同的身份（Role，如：老师，项目经理），但是同一时间用户只能属于一种身份，需要根据这个身份判断用户的权限。现在能想到的就是 Job 和 Role 需要有一层关系，这样才能获取到对应 Job 的 Role。如果框架里去实现得话，请问还有没有更好得方式。如果只能这样去修改得话，我应该改动框架里获取权限的方法嘛 ，还是另有他处可以覆盖默认的权限获取方式，我在文档上没有找到途径，请帮助一下，谢谢。

**Comment by jqhph** [comment]
没太明白你的需求，你要覆写权限模块最直接的就是覆写权限模块的路由；另外配置文件的参数你也可以过一遍，可以直接改默认用户系统的控制器和模型等等。
```php
$router->resource('auth/roles', 'xxx');
```

**Comment by Warrens-yg** [comment]
现在获取用户权限途径不是通过admin_role_users表获取用户对应的角色，再通过admin_role_permissions获取角色的权限吗？我说的那种可能需要再加一张表，通过 admin_user_departments获取对应的 department，然后再根据 department 去获取 对应的 role，之后再获取权限。不知道你说的那种可以解决这种情况吗。

**Comment by jqhph** [comment]
可以实现，只是你可能需要覆写整个用户系统，你最好都不要用我现在提供的用户系统，全部自己实现可能更快一点，当然代码上你可以参考内置的实现。

**Comment by jqhph** [comment]
如果你花点时间看一下现在的角色和权限的代码，也可以比较轻松的实现这个功能，只是有很多人没有看源码的习惯。

**Comment by Warrens-yg** [comment]
心有余而力不足啊，以前只处理业务逻辑，对这些了解的太少了，不知道能不能理解到。不过这也是提高的一个方式，总不看源码总也提高不了，多谢建议。

**Comment by Warrens-yg** [comment]
上次的场景不知道如何解决了，请教一下，像下面图上的情景还有更好的方式实现吗：
![批注 2020-05-27 094159](https://user-images.githubusercontent.com/46614146/82963708-8465e000-9ffe-11ea-818b-23bdc26b107e.jpg)

**Comment by jqhph** [comment]
> 上次的场景不知道如何解决了，请教一下，像下面图上的情景还有更好的方式实现吗：
> ![2](https://user-images.githubusercontent.com/46614146/82963785-b414e800-9ffe-11ea-9aa7-40f3738c6f9f.jpg)

你这种需要只能通过覆写用户系统的路由去解决，覆写一下管理员、角色和权限的路由，全部自己写就行了，只是多了层关系而已。

**Comment by Warrens-yg** [comment]
可能是我没有描述清楚，我的意思是这种设计方式合理吗，以前没见过用关系表再建关系的情况，不知道你有什么其他建议吗

**Comment by jqhph** [comment]
你的需求就是这样，那就是这样设计，没毛病

**Comment by Warrens-yg** [comment]
确定要重新写了，请问有没有具体的覆写方法，或者我该看哪些内容

**Comment by jqhph** [comment]
直接覆写路由就行了，权限判断会复杂一点点，你需要看下内置的权限中间件的实现
```php
$router->resource('auth/users', '控制器');
```

**Comment by Warrens-yg** [comment]
如果要覆写框架的Models里的内容，我该怎么做，因为要对用户获取权限的方式加一条链，也要加一些关系。这一块不太清楚。

**Comment by jqhph** [comment]
直接继承旧的model覆写就好了啊

**Comment by Warrens-yg** [comment]
忘记这一茬了，一语惊醒梦中人。
