### ISSUE TITLE
如图，树形表格最后一级报错

### ISSUE THREAD

**Issue by wen-gg** [jqhph/dcat-admin#1351]
- Laravel Version: 8.48.2
- PHP Version: 8.0.7
- Dcat Admin Version: 2.1.0-beta

![image](https://user-images.githubusercontent.com/17865026/123895821-0d361480-d993-11eb-8764-5d6b87716a67.png)

**Comment by jqhph** [comment]
问题已修复，可以先更新开发分支代码
```
composer update dcat/laravel-admin:"2.0.x-dev"
```
