### ISSUE TITLE
建议去掉菜单栏的 扩展 菜单

### ISSUE THREAD

**Issue by ddGuo** [jqhph/dcat-admin#1352]
- Laravel Version:8.x
- PHP Version: 7.4
- Dcat Admin Version: 2.1

### Description:
在多后台的时候，扩展怎么处理？也分多个目录？一个目录，那怎么控制？
就算关闭开发工具菜单，扩展菜单一样是可以打开的，并不是404
###重点  这个框架不是CMS，使用的人都是程序员，现在都是composer。搞个扩展菜单，还能开启关闭？啥意思

**Comment by jqhph** [comment]
你可以自己在菜单管理中删除这个菜单
