### ISSUE TITLE
hidden 字段赋值是我用法有问题吗

### ISSUE THREAD

**Issue by hetoo** [jqhph/dcat-admin#1353]
需求：新增和编辑页面都默认为1
表单布局为 多列布局 (column)
// 状态 0 草稿;1 待审核;2 已审核;
`$form->hidden('status')->value(1);`
比如说一篇文章的status为0，
但现在的情况是，新增页面status能默认为1，但是到了编辑页面，status调用的是0，并不是默认的1

**Comment by jqhph** [comment]
改成`$form->hidden('status')->default(1, true);`
