### ISSUE TITLE
这种筛选方案应该怎么实现，希望指点一下

### ISSUE THREAD

**Issue by hetoo** [jqhph/dcat-admin#1356]
在筛选这块有点卡住了，不知道该采用什么方案实现
上面红框部分可以采用规格筛选器，但下面还有个关键词搜索框
一时间不知道该如何实现，能否指点一下，谢谢
![QQ图片20210703105045](https://user-images.githubusercontent.com/7521166/124341099-b9266c80-dbec-11eb-9c78-29b4f5e7cfb5.png)

**Comment by jqhph** [comment]
不是有快捷搜索吗？

**Comment by hetoo** [comment]
> 不是有快捷搜索吗？

我想组合成这种样式，下面的搜索框可以和上面的筛选联合查询

**Comment by jqhph** [comment]
只能自己写view了这种

**Comment by hetoo** [comment]
> 只能自己写view了这种

```
$grid->filter(function ($filter) {
    $filter->view('xxx');

    ...
});
```

这种方式？

**Comment by jqhph** [comment]
不是，你可以往`$grid->header()`里面自己渲染，参考下默认规格筛选器的实现

**Comment by hetoo** [comment]
> 不是，你可以往`$grid->header()`里面自己渲染，参考下默认规格筛选器的实现

好的，我试试，谢谢
