### ISSUE TITLE
线性趋势图卡片label问题

### ISSUE THREAD

**Issue by kalepan** [jqhph/dcat-admin#1358]
你好， 请问线性趋势图卡片中的label可以对每个数据进行自定义？ 比如我想把每个数据对应的日期加上去
![image](https://user-images.githubusercontent.com/2187612/124410542-4e586b00-dd7d-11eb-8d83-5dd5da2263e7.png)

**Comment by fanhengyuan** [comment]
可以的 看文档： https://learnku.com/docs/dcat-admin/2.x/chart/8129
Apexcharts Line Chart:  https://apexcharts.com/javascript-chart-demos/line-charts/dashed/
