### ISSUE TITLE
安装时出现的问题

### ISSUE THREAD

**Issue by endstar125** [jqhph/dcat-admin#136]
- Laravel Version: 7.10.3
- PHP Version: 7.3.17
- Dcat Admin Version:1.4

### Description:
基于laradock,windows搭建的环境，执行php artisan admin:install报错：  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: ֪  (SQL: select * from information_schema.tables where table_schema = blog and table_name = migrations and table_type = 'BASE TABLE')
数据库是连通的但是DBHOST写的是容器名，猜测可能是这里的问题，不知道怎么解决。。

**Comment by jqhph** [comment]
`DBHOST`无法访问，百度

**Comment by Everan-1994** [comment]
如果你用的是后台 代码生成器，创建数据表那一项不要勾选，最后提交完之后，你再去容器里面项目根目录手动执行数据迁移。

**Comment by endstar125** [comment]
> `DBHOST`无法访问，百度

感谢

**Comment by endstar125** [comment]
> 如果你用的是后台 代码生成器，创建数据表那一项不要勾选，最后提交完之后，你再去容器里面项目根目录手动执行数据迁移。

感谢
