### ISSUE TITLE
multipleSelect 选择的值会自动排序，可以不要自动排序吗

### ISSUE THREAD

**Issue by vavo-cake** [jqhph/dcat-admin#1362]
- Laravel Version: 8.28.1
- PHP Version: 7.4.19
- Dcat Admin Version: 2.1.0-beta

![select](https://user-images.githubusercontent.com/40254156/124580504-c78db600-de82-11eb-9001-7dcf5c6f8648.gif)

**Comment by jqhph** [comment]
这个目前没有测试过怎么排序的，应该是按options设置的数组排的
