### ISSUE TITLE
关于Grid表格中，选中行后换页想要保持check状态的问题

### ISSUE THREAD

**Issue by windyson2008** [jqhph/dcat-admin#1363]
- Laravel Version: 7.x
- PHP Version: 5.x
- Dcat Admin Version: 2.1.0

### Description:
查了一圈issues貌似没有提到过关于Grid表格中，选中行后换页想要保持check状态的问题
请问有什么解决方案能够支持换页后保持checkbox的选中状态，谢谢

**Comment by jqhph** [comment]
这个功能需要自己写js实现，selectTable表单就是通过js实现的换页保存选中状态，比较麻烦
