### ISSUE TITLE
类找不到的问题

### ISSUE THREAD

**Issue by jorry2008** [jqhph/dcat-admin#1364]
- Laravel Version: 8.49.1
- PHP Version: 7.3.0
- Dcat Admin Version: 2.1.0 beta

### Description: 在 \vendor\dcat\laravel-admin\src\Repositories\EloquentRepository.php 类中无法找到此路径的类：
use Dcat\Laravel\Database\SoftDeletes as DcatSoftDeletes;

**Comment by jqhph** [comment]
这个是兼容了这个扩展包 https://github.com/jqhph/laravel-softdeletes 

如果用户没有安装也不影响使用

**Comment by jorry2008** [comment]
get到了，这个新拓展的思路极好，对性能方面有要求的非常合适，感谢
