### ISSUE TITLE
如何给表格的每行显示从1开始的序号？

### ISSUE THREAD

**Issue by vavo-cake** [jqhph/dcat-admin#1365]
- Laravel Version: 8.28
- PHP Version: 7.4
- Dcat Admin Version: 2.1.0-bate

### Description:
比如这样的
![image](https://user-images.githubusercontent.com/40254156/124718117-5c062000-df38-11eb-8d87-5128b679228b.png)

**Comment by jqhph** [comment]
`$grid->number();`

**Comment by vavo-cake** [comment]
> ```
> $grid->number();
> ```

这条个分页之后会重置编号，有办法往下递增吗

**Comment by kpsanmao** [comment]
`            $grid->column('名次')->display(function () use($grid) {
                $page = request('page')?:1;
                $startIndex = ($page-1)*$grid->getPerPage();
                return $this->_index + 1 +$startIndex;
            });`
