### ISSUE TITLE
只有上传jpg会错误，其他图片格式都没问题

### ISSUE THREAD

**Issue by sym134** [jqhph/dcat-admin#1369]
- Laravel Version: 8.4
- PHP Version: 7.4
- Dcat Admin Version: 2.1.0

### Description:
上传jpg会出现下面错误
The 封面 must be an image.", type: "error"

试过网上图片、截图jpg都不行，

### Steps To Reproduce:
$form->image('cover')->compress()->uniqueName()->saveAsString();

**Comment by jqhph** [comment]
Laravel的`image`验证规则有问题，参考 #1133

**Comment by sym134** [comment]
> 拉维尔 · 瓦德 · 瓦德 ·[瓦德， #1133](https://github.com/jqhph/dcat-admin/issues/1133)`image`

这个问题最后发现和laravel无关，我已经更新到最新版

实测问题是：
$form->image('image')->compress(true)  // 这个时候jpg无法上传，而且会偶然可以传，原因没找到
解决办法是修改为数组配置就可以了
$form->image('image')->compress(['width' => 750, 'quality' => 90,])

**Comment by MrJoker1991** [comment]
vendor\laravel\framework\src\Illuminate\Validation\Concerns\ValidatesAttributes.php

line:1014 ,array add 'jpg' can solve this problem

return $this->validateMimes($attribute, $value, ['jpg','jpeg', 'png', 'gif', 'bmp', 'svg', 'webp']);
![jpgerror](https://user-images.githubusercontent.com/26448433/127972686-a8b53651-cb63-4e32-8d30-0d0b69e18192.png)
