### ISSUE TITLE
安装时没有创建admin用户

### ISSUE THREAD

**Issue by mmhubcn** [jqhph/dcat-admin#137]
- Laravel Version: 7.0
- PHP Version: 7.1.3
- Dcat Admin Version: 1.4

### Description:
完成安装命令后，数据库的users表并没有产生admin用户，所以无法登录

### Steps To Reproduce:
请问有什么办法解决

**Comment by jqhph** [comment]
重复执行`php artisan admin:install`命令即可

**Comment by mmhubcn** [comment]
> 重复执行`php artisan admin:install`命令即可

是的，我看错了表，但是无法用admin和密码admin登陆，显示0 error

**Comment by jqhph** [comment]
> > 重复执行`php artisan admin:install`命令即可
> 
> 是的，我看错了表，但是无法用admin和密码admin登陆，显示0 error

请贴上完整的错误报文

**Comment by mmhubcn** [comment]
> > > 重复执行`php artisan admin:install`命令即可
> > 
> > 
> > 是的，我看错了表，但是无法用admin和密码admin登陆，显示0 error
> 
> 请贴上完整的错误报文

VM196:1 Mixed Content: The page at 'https://pfcloud.app/admin/auth/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://pfcloud.app/admin/auth/login'. This request has been blocked; the content must be served over HTTPS.

应该是我使用valet开启了https，而设置中是默认http，设置成`https' => env('ADMIN_HTTPS', true),`就可以登陆了，谢谢了大神
