### ISSUE TITLE
每次使用代码生成器和菜单都要强制刷新一下才会生效

### ISSUE THREAD

**Issue by dds813** [jqhph/dcat-admin#1370]
- Laravel Version: #8#40#
- PHP Version: #7#4#
- Dcat Admin Version: #2#1#0#

### Description:
每次使用代码生成器的时候，第一次进入输入表名不会自动生成下面相应的文件名，
每次使用菜单的时候，第一次进入图标里面都是空的，
都要强制刷新一下才会好用

**Comment by jqhph** [comment]
是不是js报错了，你用的dcatadmin是什么版本的
