### ISSUE TITLE
在编写扩展时，发现 Dcat\Admin\Extension 类不存在

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#1381]
- Laravel Version: 8.49.2
- PHP Version: 7.4.14
- Dcat Admin Version: 2.1.0-beta

### Description:
![image](https://user-images.githubusercontent.com/18269031/125582705-014704bd-69a5-4354-bbb1-ab4c29726073.png)

请问怎么解决？文档上找不到相关的解释？有 2.1.0 的 Field扩展可以参考吗？

**Comment by jqhph** [comment]
2.x版本的扩展没有这个类了，你是不是看错文档了？https://learnku.com/docs/dcat-admin/2.x/basic-use/8128

**Comment by jqhph** [comment]
扩展可参考 https://github.com/dcat-admin/form-step

**Comment by kunrui** [comment]
> 2.x版本的扩展没有这个类了，你是不是看错文档了？https://learnku.com/docs/dcat-admin/2.x/basic-use/8128

请问静态资源有图片怎么加载？在resources 目录下放png图片，在控制器和视图中怎么调用？
