### ISSUE TITLE
弹窗界面在切换菜单时不会关闭

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#1385]
- Laravel Version: 8.49.2
- PHP Version: 7.4.14
- Dcat Admin Version: 2.1.0-beta

### Description:
弹窗界面在切换菜单时不会关闭。
[Video_2021-07-15_164004.zip](https://github.com/jqhph/dcat-admin/files/6821599/Video_2021-07-15_164004.zip)

在开发扩展时也有这个问题，是否可以让前端获得一个页面切换的回调事件呢？
![image](https://user-images.githubusercontent.com/18269031/125758800-41bc3dfd-0198-4357-a218-5ce78b8ef744.png)

**Comment by jqhph** [comment]
参考下面的代码
```js
Dcat.onPjaxComplete(function () { // 跳转新页面时移除弹窗
    $('.content-body').prepend('<div class="row"><div class="col-md-12">'+response.content+'</div></div>');
});
```

**Comment by cyanogenic** [comment]
我的问题正好相反...
我想请教一下怎么让表单弹窗在跳转新页面时不会关闭，这样可以实现类似草稿的功能
