### ISSUE TITLE
筛选框在 暗黑模式下 border-top 白色

### ISSUE THREAD

**Issue by lichen-y** [jqhph/dcat-admin#1387]
- Laravel Version: 6.0
- PHP Version: 7.3.1
- Dcat Admin Version: 2.1.0-beta

### Description:
$filter->panel(); 
在暗黑主题下.
``
.filter-box {
    border-top: 1px solid #eee;  //建议更新颜色
    margin-top: 10px;
    margin-bottom: -.5rem!important;
    padding: 1.8rem;
}
``

**Comment by jqhph** [comment]
好的，感谢反馈
