### ISSUE TITLE
表单保存前初始化新字段问题

### ISSUE THREAD

**Issue by Gelaku** [jqhph/dcat-admin#1388]
- Laravel Version: 8.40
- PHP Version: 7.3
- Dcat Admin Version: 2.0

### Description:
表单保存前，对一个新字段处理后保存数据库失败

`protected function form()
    {
        return Form::make(ModelsRepository::make(), function (Form $form) {
            $form->display('id');

            $form->text('model_class')->required();
            $form->textarea('description');

            $form->display('created_at');
            $form->display('updated_at');

        })->saving(function (Form $form) {
           /***************** 出问题的位置，跟文档上的方法有出入 ***********************/
            if ($form->input('model_class')) {
                //table_name值写入数据库失败
                $form->input('table_name', 'Marry');
                //table_name值写入数据库成功
                $form->model()->table_name ='Marry';
            }
        });
    }`

**Comment by jqhph** [comment]
需要定义隐藏域表单，否则前端用户传什么就保存什么，太危险了
```php
$form->hidden('model_class');
```

**Comment by Gelaku** [comment]
谢谢
