### ISSUE TITLE
权限管理会不会继续升级

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#139]
基于RBAC的3种扩展模式，不知道以后您有没有计划升级为其中一种，还是保留现在最基本的RBAC形式。

**Comment by jqhph** [comment]
现在的权限功能已经能满足后台绝大多数的场景了，不知道你说的3种扩展模式是怎么个扩展法？

**Comment by Warrens-yg** [comment]
RBAC1模型：
此模型引入了角色继承(Hierarchical Role)概念,即角色具有上下级的关系,角色间的继承关系可分为一般继承关系和受限继承关系。一般继承关系仅要求角色继承关系是一个绝对偏序关系，允许角色间的多继承。而受限继承关系则进一步要求角色继承关系是一个树结构，实现角色间的单继承。这种设计可以给角色分组和分层，一定程度简化了权限管理工作。

RBAC2模型：
基于核心模型的基础上，进行了角色的约束控制,RBAC2模型中添加了责任分离关系,其规定了权限被赋予角色时，或角色被赋予用户时，以及当用户在某一时刻激活一个角色时所应遵循的强制性规则。责任分离包括静态责任分离和动态责任分离。主要包括以下约束:
互斥角色: 同一用户只能分配到一组互斥角色集合中至多一个角色，支持责任分离的原则。互斥角色是指各自权限互相制约的两个角色。比如财务部有会计和审核员两个角色,他们是互斥角色,那么用户不能同时拥有这两个角色,体现了职责分离原则
基数约束: 一个角色被分配的用户数量受限；一个用户可拥有的角色数目受限；同样一个角色对应的访问权限数目也应受限，以控制高级权限在系统中的分配
先决条件角色: 即用户想获得某上级角色,必须先获得其下一级的角色

RBAC3模型：即最全面的权限管理,它是基于RBAC0,将RBAC1和RBAC2进行了整合

**Comment by Warrens-yg** [comment]
另外推荐一个 Eloquent 的扩展包，可以支持更多的关联 https://github.com/staudenmeir/eloquent-has-many-deep

**Comment by jqhph** [comment]
> RBAC1模型：
> 此模型引入了角色继承(Hierarchical Role)概念,即角色具有上下级的关系,角色间的继承关系可分为一般继承关系和受限继承关系。一般继承关系仅要求角色继承关系是一个绝对偏序关系，允许角色间的多继承。而受限继承关系则进一步要求角色继承关系是一个树结构，实现角色间的单继承。这种设计可以给角色分组和分层，一定程度简化了权限管理工作。
> 
> RBAC2模型：
> 基于核心模型的基础上，进行了角色的约束控制,RBAC2模型中添加了责任分离关系,其规定了权限被赋予角色时，或角色被赋予用户时，以及当用户在某一时刻激活一个角色时所应遵循的强制性规则。责任分离包括静态责任分离和动态责任分离。主要包括以下约束:
> 互斥角色: 同一用户只能分配到一组互斥角色集合中至多一个角色，支持责任分离的原则。互斥角色是指各自权限互相制约的两个角色。比如财务部有会计和审核员两个角色,他们是互斥角色,那么用户不能同时拥有这两个角色,体现了职责分离原则
> 基数约束: 一个角色被分配的用户数量受限；一个用户可拥有的角色数目受限；同样一个角色对应的访问权限数目也应受限，以控制高级权限在系统中的分配
> 先决条件角色: 即用户想获得某上级角色,必须先获得其下一级的角色
> 
> RBAC3模型：即最全面的权限管理,它是基于RBAC0,将RBAC1和RBAC2进行了整合

学习了，这些功能是不会考虑集成到系统的，如果有也是做成插件的形式。因为大部分用户并不需要这么复杂的功能，集成进来会增加学习成本。
