### ISSUE TITLE
表单：radio使用disable()时，默认值取不到，返回的是null，我想要取默认值怎么办？

### ISSUE THREAD

**Issue by loveloving** [jqhph/dcat-admin#1390]
<img width="940" alt="bug" src="https://user-images.githubusercontent.com/81601240/126498310-909df368-7580-4190-b228-a1f7b2b32b71.png">

**Comment by vavo-cake** [comment]
既然已经 disable 了，那就不需要从提交的值中取了吧，不就直接用默认值吗😂

**Comment by jqhph** [comment]
加了`disable`属性，浏览器提交表单时会自动忽略

**Comment by loveloving** [comment]
👌
