### ISSUE TITLE
如何构建可新增、编辑的modal框

### ISSUE THREAD

**Issue by WangQuanTang** [jqhph/dcat-admin#1391]
- Laravel Version: 8.40
- PHP Version: 7.4.11
- Dcat Admin Version: v2.1.1-beat

### Description:
- 关联关系：
A模型hasMany B模型；
- 需求：
在A页面点击自定义列打开弹窗显示B页面内容，并且可以在弹窗实现对B的增删改查。

尝试使用LazyRenderable的方式进行构建后可以显示基本显示列的需求，在没有关闭action操作的时候和正常页面显示是一样的：

![image](https://user-images.githubusercontent.com/52555689/126622989-f5eb6acc-58b2-4d02-acb9-6a2923f920ea.png)

但是无新增，在别的地方添加完数据后，尝试modal框中的编辑/快速编辑显示404（肯定是404）：
![000](https://user-images.githubusercontent.com/52555689/126623309-8e1747b6-f36c-44e8-8c9f-d5be28086011.png)

也尝试过直接把B页面代码搬过来，但是都无法实现。

之前使用过layer构建过类似的功能，点击行操作，传入一个参数(一般是用id)到指定的B页面中，使用id查询关联数据显示。
请问modal框是否有类似的实现思路或者方法？

**Comment by jqhph** [comment]
需要在弹窗表格中更改路由前缀
```php
$grid->setResource('auth/users');
```

**Comment by WangQuanTang** [comment]
> 需要在弹窗表格中更改路由前缀
> 
> ```
> $grid->setResource('auth/users');
> ```

好的，非常感谢
