### ISSUE TITLE
编辑树形选择器没有自动选中，有办法手动赋值吗

### ISSUE THREAD

**Issue by vavo-cake** [jqhph/dcat-admin#1392]
- Laravel Version: 8
- PHP Version: 7
- Dcat Admin Version: 2.1

### Description:
![image](https://user-images.githubusercontent.com/40254156/126733487-aa61264d-4980-4647-8cf8-e9740649a6f1.png)
![image](https://user-images.githubusercontent.com/40254156/126733550-6b722bf4-b9d7-4ef6-8685-aa55549877fb.png)

**Comment by jqhph** [comment]
在`customerFormat`回调中返回选中的ID数组就行
