### ISSUE TITLE
form表单里面使用if某些情况会报错

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1395]
![image](https://user-images.githubusercontent.com/26995286/126770655-517a0192-3995-4fa1-9200-321fba89a3f9.png)
如上图，如果这样动态显示表单，在上传图片时就会失败，没搞清楚是哪里影响的，还是说不能这样动态显示（只能使用when来显示）

**Comment by jqhph** [comment]
这个会有问题，提交的时候这个type参数不存在了，导致图片字段没有定义，就上传不了。解决方法建议把type参数提交的时候也带上，比如可以增加个隐藏域表单
```php
$form->hidden('type')->default($type, true);
```
