### ISSUE TITLE
在使用$filter->month('created_at')

### ISSUE THREAD

**Issue by susan319** [jqhph/dcat-admin#1396]
在使用$filter->month('created_at')的时候  比如2021年7月    库里有7月份的数据，  可是查询不到     我看了他执行的SQL语句是select count(*) as aggregate from `post` where month(`created_at`) = '2021-07'    所以他查询不到

**Comment by jqhph** [comment]
使用where闭包查询
```php
$filter->where('created_at', function ($q) {
    $q->where(...);
})->date();
```
