### ISSUE TITLE
是否可以用这个包做普通用户PC端的后台？

### ISSUE THREAD

**Issue by sprklinginfo** [jqhph/dcat-admin#1398]
刚发现这个包，管理后台加基本的权限管理很棒，谢谢！请问可以用来开发普通用户的PC端后台吗？快速扫了眼文档，是否可以用**多应用 (多后台)**的功能做？如果可以的话， 就要花时间好好学习了， 所以想先确认这个方法是否可行。

**Comment by jqhph** [comment]
可以的，权限跟多应用功能没什么关联，普通PC后台并不需要用到多应用功能
