### ISSUE TITLE
使用simplePaginate,翻页后http query参数没有保留

### ISSUE THREAD

**Issue by kphcdr** [jqhph/dcat-admin#1399]
- Laravel Version: 6.20.23
- PHP Version: 7.2.33
- Dcat Admin Version: 2.1.1-beta

### Description:

使用simplePaginate,翻页后http query参数没有保留

### Steps To Reproduce:

Grid 中 设置         $grid->simplePaginate(); 
比如 搜索订单状态   url.xx/order?status=0  
预期翻页后url 为 url.xx/order?status=0&page=2
实际   url.xx/order?page=2

**Comment by jqhph** [comment]
已修复，感谢反馈
