### ISSUE TITLE
Form表单一对多（hasMany）创建报错和编辑不显示“多”模型的信息

### ISSUE THREAD

**Issue by garethhwang** [jqhph/dcat-admin#14]
1.表单一对多创建保存报错，提示Undefined index: _remove_。注释掉此行代码是创建保存成功了，但不过不知道为什么要unset，注释掉后很有可能会影响其他代码。
protected function prepareToSave($input)
    {
        $form = $this->buildNestedForm($this->column, $this->builder);

        return array_values(
            collect($form->setOriginal($this->original, $this->getKeyName())->prepare($input))
                ->reject(function ($item) {
                    return $item[NestedForm::REMOVE_FLAG_NAME] == 1;
                })
                ->map(function ($item) {
                    unset($item[NestedForm::REMOVE_FLAG_NAME]);//注释掉

                    return $item;
                })
                ->toArray()
        );
    }

2.表单一对多创建成功后进入编辑模式，看不到新增对应“多”的模型数据，并没有添加到field里面，只有“一”的模型数据，setFieldValue没有看到关联模型的信息。

**Comment by jqhph** [comment]
你好，感谢反馈，这个项目正在更换UI框架，我们将会在新版本中修复这个问题。

新版本的界面将采用Bootstrap4+JQ3开发，界面更加美观，代码也更规范，目前已经到完工阶段，预计下周发布。

**Comment by jqhph** [comment]
master分支已合并了修复代码
