### ISSUE TITLE
表单显示放大图片的建议

### ISSUE THREAD

**Issue by tingfeng-key** [jqhph/dcat-admin#1400]
- Laravel Version: v8.45..1
- PHP Version: 7.3.4
- Dcat Admin Version: v2.1.0-beta

### Description:

在编辑表单中点击图片下方的放大按钮，默认会以屏幕的宽高来显示，建议设置成可自定义宽高的。如果能支持多张图片有预览图，且可以左右切换的最好

![image](https://user-images.githubusercontent.com/13976521/127088059-d5b06b12-02d1-4a02-9fe6-036b07d7769d.png)

**Comment by jqhph** [comment]
不是按屏幕，是按图片的宽高去展示的，也可以鼠标点击弹窗的边缘进行放大缩小

**Comment by zwping** [comment]
@jqhph 存在一个bug, 图片宽高大于浏览器宽高，无法关闭，也没有xx按钮？

可以重写文件实现右上角x按钮的关闭吗？或者esc取消也行
