### ISSUE TITLE
multipleFile 多文件上传保存的时候字段是数组提示类型错误

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#1404]
![屏幕截图 2021-07-30 111805](https://user-images.githubusercontent.com/46614146/127589963-2b453c7a-ff92-45db-b552-abb97fd59117.png)

**Comment by jqhph** [comment]
参考文档常见问题

**Comment by Warrens-yg** [comment]
文件上传是可以的，是表单在保存的时候出现的问题
