### ISSUE TITLE
文件下载属性设置问题

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#1405]
![屏幕截图 2021-07-30 112919](https://user-images.githubusercontent.com/46614146/127590835-38e10efa-5603-488b-b4dd-6fb7bf5192fc.png)
上面查找的是 downloadable , 第一次上传文件的时候属性是 download，所以并不会显示下载按钮，在启用排序后，上下移动之重新查找的是 download，此时才显示下载按钮

**Comment by jqhph** [comment]
已修复，感谢反馈
