### ISSUE TITLE
表单详情中的filesize方法失效，$show->field('file_size')->filesize();

### ISSUE THREAD

**Issue by Gelaku** [jqhph/dcat-admin#1409]
- Laravel Version: 8.40
- PHP Version: 7.3
- Dcat Admin Version: 2

### Description:
显示文件尺寸
如果字段数据是表示文件大小的字节数，可以通过调用filezise方法来显示更有可读性的文字

$show->field('file_size')->filesize();
这样数值199812019将会显示为190.56 MB

**Comment by jqhph** [comment]
好的我看下感谢反馈
