### ISSUE TITLE
分步表单上传图片，会自动提交

### ISSUE THREAD

**Issue by keacefull** [jqhph/dcat-admin#1411]
- Laravel Version: 8.5.20
- PHP Version: 8.0.5
- Dcat Admin Version: 2.1.2

### Description:
分步表单上传图片。会自动提交。

### Steps To Reproduce:

> return Form::make(new Good(), function (Form $form) {
            $form->title('分步表单');
            $form->action('good');
            $form->disableListButton();
            $form->multipleSteps()
                ->remember() 
                ->width('950px')
                ->add('基本信息', function ($step) {
                    $step->text('name', '姓名')->required()->maxLength(20);
                    $step->image('cover','头像');
                })
                ->done(function () use ($form) {
                        return "success";
                });
        });

![微信截图_20210802141440](https://user-images.githubusercontent.com/8847289/127812697-76130c0c-ee2c-4921-b1f7-330838de34f7.png)

**Comment by hetoo** [comment]
**自动上传 (autoUpload)**
开启这个功能之后选择完文件之后会立即自动上传，页面将不再显示上传按钮，使用方法如下

```
$form->file('file')->autoUpload();
$form->image('img')->autoUpload();
```
https://learnku.com/docs/dcat-admin/2.x/picture-file-upload/8106

**Comment by jqhph** [comment]
可以禁用这个功能，例如
```php
$step->file(...)->autoSave(false);
```
