### ISSUE TITLE
如何实现Policy权限策略的功能

### ISSUE THREAD

**Issue by wai523** [jqhph/dcat-admin#1416]
- Laravel Version: 8
- PHP Version: 8
- Dcat Admin Version: 2.0.23

### Description:
如何实现Policy权限策略的功能，项目需要加入审核权限，审核后的信息发布者不可以在编辑或查看等操作。
用户只能增删改查操作自己发布的信息，不可删改查操作其他人发布数据。
目前通过角色权限无法实现，急需解决。

**Comment by jqhph** [comment]
`Policy`我没在系统中用过，现在的权限也可以实现，用`Admin::user()->can('view-users')`这样在代码中自己判断是否有权限，没有的话做相应的限制就行
