### ISSUE TITLE
一对多关联表单

### ISSUE THREAD

**Issue by feilongjump** [jqhph/dcat-admin#1417]
- Laravel Version: 8.53.0
- PHP Version: 8.0.2
- Dcat Admin Version: 2.1.2-bate

### Description:
```php
return Form::make(Business::with(['contacts']), function (Form $form) {
    $form->tab('基础信息', function (Form $form) {

        $form->text('name')->required();

    })->tab('联系人信息', function (Form $form) {

        $form->hasMany('contacts', '', function (Form\NestedForm $form) {

            $form->text('contacts.name')->required();

        })->useTable()->width(12);

    });
});
```
两个问题：
* 在上述代码中，有一个 `hasMany` 的关联方式，然而我需要使用自动翻译功能，所以我需要在其中增加关联方式而令其自动获取翻译 `$form->text('contacts.name')->required();` ，但是问题来了，它却无法获取到数据。
* 在这一段代码中：`$form->hasMany('contacts', '', function (Form\NestedForm $form) {});`  对比文档中（下图）
![image](https://user-images.githubusercontent.com/48574176/128482222-ab8e2b39-babe-41a2-8767-727cad957462.png)
这是可以直接使用两个参数即可，但我却出现了如下报错：
![image](https://user-images.githubusercontent.com/48574176/128482423-de7acd27-2820-421d-a2ef-ac64dc20ffc7.png)
我有尝试过不使用 tab 表单的方式，但是还是不行。

**Comment by jqhph** [comment]
改成`$form->text('name'， admin_trans_field('contacts.name'))->required();`

**Comment by feilongjump** [comment]
> 改成`$form->text('name'， admin_trans_field('contacts.name'))->required();`

是的,您这种方式是可以获取到翻译的,您的意思是不是说 `hasMany` 是无法使用自动翻译呢?
