### ISSUE TITLE
图片能否在表单送出再上传

### ISSUE THREAD

**Issue by Xuan-Goldenf** [jqhph/dcat-admin#1418]
- Laravel Version: 8.x.x
- PHP Version:7.4.x
- Dcat Admin Version: 2.1.x

### Description:
图片上传能否在form post 的时候才上传呢？

因为需要在form post的时候取得某栏位后将 图片放置在指定的目录
![image](https://user-images.githubusercontent.com/40749214/128586623-53beea8c-8950-4df4-90f8-cbe244ef7cd4.png)

**Comment by jqhph** [comment]
不支持，这个需要通过上传组件的相关事件实现，参考文档 https://learnku.com/docs/dcat-admin/2.x/picture-file-upload/8106
