### ISSUE TITLE
419 CSRF token mismatch - Page expired

### ISSUE THREAD

**Issue by Allen-Hung-owl** [jqhph/dcat-admin#1419]
- Laravel Version: 8.37.0
- PHP Version: 7.4.21
- Dcat Admin Version: 1.7.8

### Description:
與下列提問相同問題，
https://github.com/jqhph/dcat-admin/issues/652#issue-734314139
執行指令 php artisan admin:publish --assets --force
功能即恢復正常。

想請問於正式Server(非本機)是否須將指令納入建置流程，於每次建置時都執行指令，
還是只需要於首次建置手動執行該指令一次即可？

另外，若升級至2.X可否解決此問題，
謝謝。

![image](https://user-images.githubusercontent.com/69564839/128668654-8389ede0-6256-4923-a542-da564de16b88.png)

**Comment by jqhph** [comment]
可能是cookie冲突了，清除下浏览器cookie试试

**Comment by forecho** [comment]
同样遇到这种错误，清除下浏览器 cookie 就推出登录了，再次登录同样报错
