### ISSUE TITLE
模型的访问器好像在 Grid 中不能正常使用

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#142]
- Laravel Version: 7.11.0
- PHP Version: 7.2
- Dcat Admin Version: 1.4.0

### Description:
模型的访问器好像在 Grid 中不能正常使用

在我访问模型访问器中定义的方法：
public function getAreaNameAttribute()
 {
        return  'test';
 }

在 Grid 方法中调用

$grid->area_name;

**Comment by jqhph** [comment]
grid访问器不支持空字段，你可以用这种方式处理
```php
$grid->area_name->display(function () {
    return 'test';
});
```

**Comment by kunrui** [comment]
@jqhph 能用到访问器，值一般都不是固定的，我这里是关联地区模型中的值。

**Comment by jqhph** [comment]
> @jqhph 能用到访问器，值一般都不是固定的，我这里是关联地区模型中的值。

你可以参考下这个 #71

**Comment by kunrui** [comment]
@jqhph ，可以了，谢谢

**Comment by kunrui** [comment]
@jqhph 建议优化改良一下，毕竟访问器还是比较常用的。现在这种写法代码比较繁琐。

**Comment by lilashih** [comment]
你得把你的accessor加到$appends裡

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
    protected $appends = ['area_name'];  // here

    public function getAreaNameAttribute()
    {
        return 'test';
    }
}
```

**Comment by kunrui** [comment]
@lilashih 首先这种方法不错，减少了代码量，感谢。但也有一个问题，如果我在不需要area_name字段的时候，他也会去默认去调用getAreaNameAttribute方法，导致产生不必要的关联查询（sql），产生资源浪费。

**Comment by lilashih** [comment]
那改成這樣試試

```php
public function getAreaNameAttribute()
{
    if ($this->relationLoaded('area')) {
        return $this->area->name;
    }
    return '';
}
```
這樣就只有用eager loading時才會去下查詢

```php
protected function grid()
{
    $grid = new Grid(new Model());
    $grid->model()->with(['area']);
}
```

[use-relationship-in-model-accessor-in-laravel](https://stackoverflow.com/questions/43862597/use-relationship-in-model-accessor-in-laravel)

**Comment by kunrui** [comment]
@lilashih 也是个解决方法，多谢

**Comment by jqhph** [comment]
2.0已支持
