### ISSUE TITLE
控制器指定翻译文件无效

### ISSUE THREAD

**Issue by peimengc** [jqhph/dcat-admin#1420]
- Laravel Version:  8.53.1
- PHP Version:  7.4.9 
- Dcat Admin Version: 2.1.2

### Description:
在控制器使用 `protected $translation = “dy-video”` 指定翻译文件无效，还是根据控制器名称，默认使用 `video`
```
class VideoController extends AdminController
{
   protected $translation = 'dy-video';
.
.
.
}
```

**Comment by jqhph** [comment]
无法复现
