### ISSUE TITLE
使用了bootstrapNumber后，绑定事件（例如：on）失效

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1421]
具体代码如下：
<input type='number' name='goods_num' value='1' min='1' max='45' class='form-control'>

Dcat.ready(function () {
         Dcat.init('input[name="goods_num"]', function ($this) {
            
            $this.bootstrapNumber({
                'upClass': 'success btn-sm shadow-0',
                'downClass': 'light btn-sm shadow-0'
           });

            $this.on('input', function () {
                console.log(123);
            });
        });
 });
应该是动态元素绑定时间失效了，因为bootstrapNumber里面有用到replaceWith。
我在其他地方使用动态插入元素后，绑定事件也失效了

**Comment by jqhph** [comment]
如果不用`Dcat.init`呢？
