### ISSUE TITLE
表单一对多内嵌表格

### ISSUE THREAD

**Issue by feilongjump** [jqhph/dcat-admin#1426]
- Laravel Version: 8.53.0
- PHP Version: 8.0.2
- Dcat Admin Version: 2.1.2-bate

### Description:
- 表单内嵌表格是否没办法控制每一列的宽度？
- 当内嵌表格列数太多，会超出页面的宽度。
![image](https://user-images.githubusercontent.com/48574176/128869489-5585aa3c-bc37-467e-99c3-e3773e296736.png)

**Comment by jqhph** [comment]
是的建议采用`$form->array()` + `column`布局
