### ISSUE TITLE
Dcat.wait is not a function 和  $(...).select2 is not a function

### ISSUE THREAD

**Issue by ceo404** [jqhph/dcat-admin#1427]
- Laravel Version: 6.20.27
- PHP Version: 7.4.2
- Dcat Admin Version: 2.1.2-beta

### Description:
Dcat.wait 点击菜单栏目报错
![26D450E1BBA615B7EA103ED07F6EF57E](https://user-images.githubusercontent.com/31309806/128917769-bcc45b18-fcd7-4bf2-9c17-a85f1eda53ff.jpg)
通过对比旧版本 2.0.24
这个文件在 
vendor/dcat/laravel-admin/resources/views/layouts/content.blade.php
vendor/dcat/laravel-admin/resources/views/layouts/full-content.blade.php
vendor/dcat/laravel-admin/resources/views/layouts/form-content.blade.php
vendor/dcat/laravel-admin/src/Http/Controllers/RenderableController.php
vendor/dcat/laravel-admin/src/Admin.php
中添加过Dcat.wait()
在旧版本 2.0.24 均为 Dcat.pjaxResponded()
这个是因为版本问题还是什么原因请老板查明

$(...).select2 is not a function
错误不详
![image](https://user-images.githubusercontent.com/31309806/128918446-65dedb13-74c4-4827-acda-34bbed051f94.png)

**Comment by jqhph** [comment]
重新发布资源，清理浏览器缓存
