### ISSUE TITLE
为何上传文件组件不用 bootstrap-fileinput 呢

### ISSUE THREAD

**Issue by edwinhuish** [jqhph/dcat-admin#1430]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: 2.1.2-beta

### Description:

为何上传组件使用 webuploader？ 看了一下GitHub，有2.4K issues 未解决，且readme注明不再解决issues。最近的更新也是好几年的了。

对比 bootstrap fileinput, 一直在保持更新，且只有几个issues。

laravel-admin 本来就是用 fileinput 的。请问作者是出于什么考虑改为 webuploader 的呢？ @jqhph

**Comment by jqhph** [comment]
当时使用`bootstrap fileinput`实现异步上传的时候有些体验不是很好，不过确实webuploader有很大的问题，后面可能也会更换其他上传组件
