### ISSUE TITLE
构造方法获取当前登录用户信息为空

### ISSUE THREAD

**Issue by WangQuanTang** [jqhph/dcat-admin#1431]
- Laravel Version: 8.49.1
- PHP Version: 7.4.11
- Dcat Admin Version: 2.1.0-beat

### Description:
使用：
```
use Dcat\Admin\Admin;
Admin::user();

```
获取用户信息，获取到的用户信息为null，查看源代码：
```
public static function guard()
{
    return Auth::guard(config('admin.auth.guard') ?: 'admin');
}
```
`config('admin.auth.guard')`的值为：
```
'guard' => 'admin',
```
按照父类，子类，父类构造方法，子类构造方法加载顺序，父类没有构造方法，子类构造方法应当是能获取到用户信息的，之前使用laravel-admin的时候，构造方法里获取当前登录用户信息是可以的，请问这样的情况下需要怎么去修改，以此来实现构造方法获取登录用户信息？

**Comment by jqhph** [comment]
这个是laravel的问题，别在构造器获取登录用户，具体原因你自己百度下

**Comment by WangQuanTang** [comment]
> 这个是laravel的问题，别在构造器获取登录用户，具体原因你自己百度下



> 别在构造器获取登录用户

好的，非常感谢，我关闭这个问题！
