### ISSUE TITLE
文件组件接入远程OSS时产生的矛盾问题

### ISSUE THREAD

**Issue by jorry2008** [jqhph/dcat-admin#1435]
- Laravel Version: 8.49.0
- PHP Version: 7.3.4
- Dcat Admin Version: 2.1.2 beata

### Description:
举例：
$form->image('GLOBAL_site_logo', 'LOGO')
           ->disk('oss')
            ->autoUpload()
            ->uniqueName()
            ->default(admin_setting('GLOBAL_site_logo'))
当oss一切正常，能获取默认图片值的情况下，显示是Ok的，
但当oss出现网络或资源不存在的情况，oss组件是会直接异常的，
比较使用这个质量比较好的包：https://github.com/jacobcyl/Aliyun-oss-storage
它对资源的所有操作如果出了异常，它是直接抛出的！
而Dcat确又是直接get、delete等操作，而没有捕获并整合进调试模式区别对待，
这样就导致因为资源找不到，确让整个程序奔溃，而我又无能为力。

下一个问题是：
到底是第三方oss改，还是dcat改，我觉得是dcat改，因为oss层级更高，它负责抛出异常是正常操作。
而作为dcat使用这种网络层的操作，应该引入调试模式或异常捕获。

**Comment by jqhph** [comment]
这个oss的包有问题，用这个包吧https://github.com/iiDestiny/laravel-filesystem-oss
