### ISSUE TITLE
自定義視圖不能切換以及dcat-api/render 500  Class "" not found 

### ISSUE THREAD

**Issue by kaikaisd** [jqhph/dcat-admin#1436]
- Laravel Version: 8.54.0
- PHP Version: 8.0.9
- Dcat Admin Version: 2.1.2-beta

### Description:
在本地用artisan serve什麼事都沒有發生時，上到Production Server（nginx + php8 ＋ HTTPS (with Cloudflare CDN)）
修改ADMIN_ROUTE_DOMAIN到指定DOMAIN(即不跟APP_URL)和打開了ADMIN_HTTPS後，自定義視圖不能切換，Modal Form會出現dcat-api/render 錯誤500

**Comment by jqhph** [comment]
截图下请求参数

**Comment by kaikaisd** [comment]
這個是Online(套了Cloudflare): <img width="399" alt="圖片" src="https://user-images.githubusercontent.com/16899686/130043583-23ae2300-0a55-4627-841e-b00c68a7572b.png">
&nbsp; &nbsp;
這個是Local: <img width="383" alt="圖片" src="https://user-images.githubusercontent.com/16899686/130043740-5e8d2cfe-ab7c-4fb0-9ab9-f6bdb6ca9531.png">

**Comment by kaikaisd** [comment]
找出問題所在了，是我NGINX 配錯了
