### ISSUE TITLE
上传图片会内存溢出

### ISSUE THREAD

**Issue by Zdowson** [jqhph/dcat-admin#1440]
- Laravel Version: 7.3
- PHP Version: 7.3
- Dcat Admin Version: 2.1.0

### Description:
上传图片超过3M就内存溢出,
代码:
$form->image('background_image')->autoSave(false)->removable(false)->uniqueName()->retainable()->autoUpload()->saveFullUrl()->help('尺寸必须是1125×1500');

php.ini
memory_limit = 128M

memory_limit设置更大的话就会报502

报错如下,
Allowed memory size of 134217728 bytes exhausted (tried to allocate 213022424 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 134217728 bytes exhausted (tried to allocate 213022424 bytes) at /alidata/wwwroot/aschaibao/vendor/league/mime-type-detection/src/FinfoMimeTypeDetector.php:68)

**Comment by jqhph** [comment]
没复现，你本地和线上都报错吗

**Comment by Abbotton** [comment]
`memory_limit = 128M`略小，建议调大一些。
