### ISSUE TITLE
許願 grid中的filter 對多標簽搜索的處理

### ISSUE THREAD

**Issue by clock1129** [jqhph/dcat-admin#1441]
- Laravel Version: 8.#.#
- PHP Version: 7.4.#
- Dcat Admin Version: 2.1.2-beta

### Description:
在grid當中的filter，如果要搜索標簽(一條記錄有多個標簽，字段中用json設計，存成array，非一對多table)，想要實現的需求：同時輸入2個標簽(a,b)時，有可能是希望找出"一筆記錄同時有兩個標簽a,b的"，也可能是希望找出"包含標簽a或標簽b"的。目前的filter沒有找到方便的函式可用(in無法用在json字段)，希望可以為這樣的需求擴展如injson()這樣的函式，並且能用group將上述對兩個以上標簽的and/or做分組。(我已試著自己用where實現以上的需求，但需要分成兩條filter，但無法在group寫where讓它分組)。

謝謝

### Steps To Reproduce:
![a](https://user-images.githubusercontent.com/19473195/130027706-5edc2498-a102-4ea4-b7e3-0cc225560937.jpg)

**Comment by Abbotton** [comment]
感觉表结构不太合理，应该是多对多才对吧，您这需求属于个性化需求，跟Dcat Admin关系不大。

**Comment by clock1129** [comment]
是有特殊原因决定不采用多对多的，最主要的原因是tags并非是预先固定的，有点类似微博的#可以动态因为内容增加的，不想每次增加新的tag时都一定要去新增关联表，不过如果能做成自动化新增关联表倒也是可以的。而标签搜索，如一部电影可以同属"爱情"、"喜剧"，甚至还有其他tag(或分类)，当我要搜索tag时输入"爱情"、"喜剧"，有可能是希望找出"爱情"且"喜剧"的电影，也可能是想找出爱情或喜剧的电影。本想着说透过group让两条搜索合在一起，但试了下又不行，能否请教这种情况建议怎么实现？如果模型是一般多对多的话，是否能建议我用哪些个组件实现易于管理呢？谢谢

**Comment by edwinhuish** [comment]
> 是有特殊原因决定不采用多对多的，最主要的原因是tags并非是预先固定的，有点类似微博的#可以动态因为内容增加的，不想每次增加新的tag时都一定要去新增关联表，不过如果能做成自动化新增关联表倒也是可以的。而标签搜索，如一部电影可以同属"爱情"、"喜剧"，甚至还有其他tag(或分类)，当我要搜索tag时输入"爱情"、"喜剧"，有可能是希望找出"爱情"且"喜剧"的电影，也可能是想找出爱情或喜剧的电影。本想着说透过group让两条搜索合在一起，但试了下又不行，能否请教这种情况建议怎么实现？如果模型是一般多对多的话，是否能建议我用哪些个组件实现易于管理呢？谢谢

@clock1129 这种形式不建议用json，请用分隔符分割形式，比如逗号分割。

如 ``` ,tag1,tag2,tag3, ``` ， 前后都有逗号，然后 SQL查询的时候，就可以 ``` ... WHERE tag LIKE '%,tag1,%' OR tag LIKE '%,tag3,%' ```

对应为 ``` Dcat Admin ``` 则应该是：
``` 
$filter->where('tags', function($query){
    foreach($this->input as $tag){
        $query->orWhere('tags', 'like', "%,{$tag},%");
    }
});
```

**Comment by jqhph** [comment]
你可以尝试自己扩展这种过滤器
