### ISSUE TITLE
请问一下如何不点击删除按钮，通过js或者其他方法清空表单中已上传的文件和图片

### ISSUE THREAD

**Issue by hexianqi1959** [jqhph/dcat-admin#1444]
![QE2W{94}N$XL}{}JQF`81SE](https://user-images.githubusercontent.com/35123159/130035676-d11ff711-4094-47c3-be1a-f527bbe5290e.png)
如图

**Comment by caserwiki** [comment]
no zuo no die

**Comment by hexianqi1959** [comment]
done
