### ISSUE TITLE
使用树状表格后，回收站中无法显示软删除的数据

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#1447]
- Laravel Version: 8.54.0
- PHP Version: 7.4.15
- Dcat Admin Version: 2.1.2-beta

### Description:
使用树状表格后，且使用了软删除功能，回收站中无法显示删除后的数据

**Comment by Warrens-yg** [comment]
这个需求有点奇怪,删除之后的数据不存在上下级关系,回收站应该把删除的数据按一维表格显示

**Comment by jorry2008** [comment]
如果按照这个思路下去，树状表格应该在完整显示树状之后，再将剩下的不完整树状数据显示在底部，这样：
1.即能在查看界面查看到未删除但又不在树状结构中的数据
2.也能查看到回收站的所有数据
也就是树状结构展示表格，包含两种类型的数据，从而实现兼容

**Comment by jorry2008** [comment]
我们设计的系统里，本来也打算，全局数据都不能真删除，结果遇到树状数据时，就出现特殊处理的情况，其实也是有点无语的，也希望官方出个合理的方案出来，让我们实现全站软删除支持

**Comment by ygcool** [comment]
已解决。
```
if (request('_scope_') == 'trashed') {
    $grid->column('name');
} else {
    $grid->column('name')->tree();
}
```
