### ISSUE TITLE
form checkbox 不支持 spatie\tags

### ISSUE THREAD

**Issue by dlsimple** [jqhph/dcat-admin#1456]
- Laravel Version: 8.56.0
- PHP Version: 8.0.9
- Dcat Admin Version: 2.1.2-beta

### Description:

使用Spatie\Tags 作为Tag 组件
因为Spatie的Tag支持翻译，所以name里的值是json 类似  {"zh_CN": "套餐"}
在Form中使用  

$form->checkbox('tags')->options(Tag::pluck('name', 'id'));

当进入Create / Edit 页面时，报错 Array to string conversion

### Steps To Reproduce:

经跟踪得知

Form/Field/Select.php:230

没有对类似的情况进行处理

在没有找到更好的解决办法之前，手动加了如下代码。

public function value($value = null)
    {
        
        if (is_null($value)) {
            if (
                $this->value === null
                || (is_array($this->value) && empty($this->value))
            ) {
                
                return $this->default();
            }
            
            //----start
            // if(is_array($this->value)) {
            //     $this->value = Arr::pluck($this->value,'id');
            // }
            //----end
            
            return $this->value;
        }
        

        $this->value = value($value);

        return $this;
    }

**Comment by jqhph** [comment]
用`customFormat`转化一下就好，参考表单相关文档以及表单关联关系文档
