### ISSUE TITLE
form表单里面的tab不能正常显示错误提示

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1458]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: v2.1.2-beta

### Description:
![image](https://user-images.githubusercontent.com/26995286/131203902-e199a6c0-b556-4047-b3d8-ceb74c5fbdd0.png)
![image](https://user-images.githubusercontent.com/26995286/131203908-12306796-1ed2-4e75-a760-eec48b60eca4.png)
![image](https://user-images.githubusercontent.com/26995286/131203919-5101c1bd-ca32-45f9-ab29-315a55c57e51.png)

**Comment by jqhph** [comment]
这种情况建议不要使用`required`方法，因为这个是浏览器H5验证，建议改成`$form->text(...)->setLabelClass(['asterisk'])->rules('required');`
