### ISSUE TITLE
在使用腾讯地图，第一次进入编辑页面都会报错

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#146]
- Laravel Version: 7.11.0
- PHP Version: 7.2
- Dcat Admin Version: 1.4.0

### Description:
报错误内容如下：
![](https://ftp.bmp.ovh/imgs/2020/05/9893e0ad2de77c35.png)

**Comment by kunrui** [comment]
会导致第一次进入编辑页面地图不显示

**Comment by jqhph** [comment]
是使用内置的地图组件吗？请贴下代码

**Comment by kunrui** [comment]
是的

代码如下：

**Comment by kunrui** [comment]
是的，使用内置的地图组件
form方法代码如下：
protected function form()
{
        return Form::make(new ServiceHall(), function (Form $form) {
            $form->text('code')->required();
            $form->text('service_hall_name')->required();;
            $form->map('latitude', 'longitude', '经纬度');
｝

**Comment by kunrui** [comment]
我看源码，大概分析了一下，地图的js是懒加载的，js还没有加载完成，编辑页面已经在调用 地图控件的方法了

**Comment by jqhph** [comment]
感谢反馈，确实是这个问题，你可要先这样处理一下，在你的`app/Admin/bootstrap.php`中加入以下代码
```php
Form\Field\Map::collectAssets();
```
