### ISSUE TITLE
laravel octane 下 excel 导出的问题

### ISSUE THREAD

**Issue by yun3948** [jqhph/dcat-admin#1462]
- Laravel Version: 8.5
- PHP Version: 8.0
- Dcat Admin Version: 2.1.2

### Description:
新项目，测试使用了 laravel octane  roadrunner ，使用导出功能异常，想尝试保存本地后跳转下载文件也无法生效。想请问有没有简单的解决办法？

**Comment by yun3948** [comment]
最后使用自定义异常。抛出异常，返回响应文件下载来实现了

**Comment by nbzhugq** [comment]
@yun3948 代码有吗，我也想上octane

**Comment by yun3948** [comment]
> @yun3948 代码有吗，我也想上octane

抱歉最近没看。这个项目最终没有用，思路就是重写导出那块的代码，把文件保存到本地，手动抛出异常信息附带保存的文件的url，然后外层捕获异常进行处理
