### ISSUE TITLE
多后台 可以共用一个登录吗

### ISSUE THREAD

**Issue by hongxinjie** [jqhph/dcat-admin#1464]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
现在有两个应用，两个应用共用一个用户表、角色表，我想让用户在登录时通过判断用户角色进入到对应的后台。比如：现有一个管理员后台和一个普通成员后台，登录用的是管理员的登录页面。当登录的账号是普通用户时，跳到普通成员的后台，而不需要再次弹出普通用户的登录页让其登录。

**Comment by jqhph** [comment]
不可以，需要自己实现
