### ISSUE TITLE
English Documentation missing - instaling / updating to V2

### ISSUE THREAD

**Issue by radumro** [jqhph/dcat-admin#1465]
Hi,
i love what you did with this admin.

the link to the english documentation is not working.

how can i install the v2 of the admin?
if i try to instal with the methods described i get the 1.7 version.

if i try to update the laravel app crashes

please let me know

**Comment by yun3948** [comment]
this is the chinese document  for install dcat-admin v2 
1. create laravel project  
` composer create-project --prefer-dist laravel/laravel  project`
2. edit .env file  , connect the database
3.  install dcat-admin
```
cd project 
composer require dcat/laravel-admin:"2.*" -vvv
```
