### ISSUE TITLE
form表单添加时入库sql语句 为？号

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1467]
- Laravel Version: 5.8.38
- PHP Version: 7.4
- Dcat Admin Version: 2.1.2

### Description:
![image](https://user-images.githubusercontent.com/13138164/132088904-29b4c487-deb3-4c49-9a52-c3742610b200.png)
这两字段在数据库设置的禁止为null, 默认值为空。

当我不填写值 提交表单时，入库报错

SQLSTATE[HY000]: General error: 1364 Field 'user_id' doesn't have a default value (SQL: insert into `admin_apps` (`line_id`, `call_unit_price`, `callback_url`, `record_callback_url`, `updated_at`, `created_at`) values (4, 0.04, ?, ?, 2021-09-04 16:50:55, 2021-09-04 16:50:55))

变成了问号？

**Comment by jqhph** [comment]
只是日志的显示问题，实际上不是问号

**Comment by Ya-hui** [comment]
我字段设置的禁止为null,  入库时该字段是null  。如果让入库时把null 变为空字符串呢？

**Comment by jqhph** [comment]
`$form->text(...)->saveAsString()`
