### ISSUE TITLE
Composer 无法同时安装 easy-excel

### ISSUE THREAD

**Issue by nyufeng** [jqhph/dcat-admin#1475]
- Laravel Version: v8.60.0
- PHP Version: 8.0.0
- Dcat Admin Version: 2.1.2-beta

运行 ``composer require dcat/easy-excel``
![image](https://user-images.githubusercontent.com/9927289/132658337-c0ce1565-6399-4551-baa3-8b1f1c9451b6.png)
运行 ``composer require dcat/laravel-admin:"2.*"``
![image](https://user-images.githubusercontent.com/9927289/132658447-ef084e0d-db6a-4e37-bef3-aa78e50894ed.png)

**Comment by jqhph** [comment]
先安装dcatadmin在安装excel
