### ISSUE TITLE
分页表单上传文件失败

### ISSUE THREAD

**Issue by pyx02502** [jqhph/dcat-admin#1477]
- Laravel Version: 8.53.1
- PHP Version: 7.4.3
- Dcat Admin Version: 2.*

### Description:
首先非常感谢开发大大的精心维护
我现在需要在上传文件时传入form中其他input值，然后想用分页然后提取前一个页面的session来实现
现在可以正确提取到session中的值
但上传
一直提示上传失败，请问应该怎么调试解决
![1631259363](https://user-images.githubusercontent.com/87053660/132817864-f6a69357-c15b-4a09-a753-f1caf4762dcb.png)

**Comment by jqhph** [comment]
接口返回什么

**Comment by pyx02502** [comment]
> 接口返回什么

这是页面返回
![1631857556(1)](https://user-images.githubusercontent.com/87053660/133732313-ee778c49-3a2c-41fb-8635-16e893e9280f.png)
Error: Object of class Illuminate\View\Factory could not be converted to string in file vendor/dcat/laravel-admin/src/Support/Helper.php on line 108

若上传组件不放在分页表单中则能正常上传，但没法给组件传表单参数
