### ISSUE TITLE
如何隐藏开发者工具，只让admin可以看到，其他权限不可以看到

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1478]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 2.1.2

如何隐藏开发者工具，只让特定角色可以看到，其他角色不可以看到

**Comment by jqhph** [comment]
APP_DEBUG设置为false

**Comment by Ya-hui** [comment]
这样的话 admin超级管理员也是看不到的

**Comment by ihsj** [comment]
正常来说，也不会在生产环境编码吧，这个是在dev环节才开启的功能呀
