### ISSUE TITLE
Form表单编辑时使用Checkbox的checked方法无效

### ISSUE THREAD

**Issue by jesse7866** [jqhph/dcat-admin#1479]
- Laravel Version: 8.54.0
- PHP Version: 7.4.3
- Dcat Admin Version: 2.1.2-beta

### Description:
表单编辑中，使用 `checkbox` 的 checked 时，传入参数无效
```php
$form->checkbox('field')->options([...])->checked([...]);
```

查看 [Checkbox 源码](https://github.com/jqhph/dcat-admin/blob/5abb9fe9e9be0896583554e973ecc08767027985/src/Form/Field/Checkbox.php#L98)
使用的是 $this->value() 并没有用到 $this->checked，故导致checked传参无效
```php
$checkbox
            ->inline($this->inline)
            ->check($this->value())
            ->class($this->getElementClassString())
            ->size($this->size);
```

### Steps To Reproduce:
麻烦看看是否可以把 `$this->value()` 改成 `$this->checked` ?

**Comment by jqhph** [comment]
你应该使用`default`方法`$form->checkbox(...)->default([1, 2, 3], true)`

**Comment by jesse7866** [comment]
收到，谢谢

**Comment by chenjiabin** [comment]
请问一下。 我好像想禁用[1,2,3]不给点击 diabled， 应该如何设置
