### ISSUE TITLE
when显示正常，提交没有反应

### ISSUE THREAD

**Issue by warmup413** [jqhph/dcat-admin#1489]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.1.2

### Description:
显示正常，就是保存的时候没有任何反应，控制台也没有报错

### Steps To Reproduce:

`
private $lab_days = [6 => '6天', 7 => '7天'];

$form->radio('days')
                ->when(6, function ($form) {
                    $form->embeds('task_data', function (EmbeddedForm $form) {
                        $form->select('day1', '第1天')->options($this->task)->width(2)->required();
                        $form->select('day2', '第2天')->options($this->task)->width(2)->required();
                    });
                })
                ->when(7, function ($form) {
                    $form->embeds('task_data', function (EmbeddedForm $form) {
                        $form->select('day1', '第1天')->options($this->task)->width(2)->required();
                        $form->select('day2', '第2天')->options($this->task)->width(2)->required();
                        $form->select('day3', '第3天')->options($this->task)->width(2)->required();
                    });
                })->options($this->lab_days)->default(6);
`

**Comment by jqhph** [comment]
完整的代码是什么样的
