### ISSUE TITLE
右键操作菜单无法使用

### ISSUE THREAD

**Issue by datangkang123** [jqhph/dcat-admin#149]
laravel-admin中全局开启右键操作菜单是这样的：
`    /*
    |--------------------------------------------------------------------------
    | 设置数据表格的操作列显示类
    |--------------------------------------------------------------------------
    */
    'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,`

但在dcat中设置无效。
`    //右键操作菜单
	'grid_action_class' => \Dcat\Admin\Grid\Displayers\ContextMenuActions::class,`

**Comment by jqhph** [comment]
这个功能将在后续版本中支持。

**Comment by jqhph** [comment]
这个功能已增加，升级到`1.4.5`版本即可
