### ISSUE TITLE
在某些布局下无法显示侧栏折叠按钮

### ISSUE THREAD

**Issue by betaxab** [jqhph/dcat-admin#1501]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: latest

### Description:

在某些布局下无法显示侧栏折叠按钮，没法收起侧栏，这给使用带来一些不便，希望可以适配一下，谢谢。

### Steps To Reproduce:

请看截图：

![screenshot_2021-09-23_10-25-29](https://user-images.githubusercontent.com/30405429/134446464-4b148814-3e2e-4f82-8341-2cdc0251f87a.png)

**Comment by jqhph** [comment]
这个是adminlte自适应功能自动隐藏的，你改下css就行
