### ISSUE TITLE
多文件上传如何随post一起发出，而不是单独的上传？

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1503]
- Laravel Version: 8.*
- PHP Version: 7.4
- Dcat Admin Version: 2.*

![image](https://user-images.githubusercontent.com/13138164/134626487-aa3226b4-9785-4592-b7f1-345c85775e3d.png)

如上面图 ，我想在点击提交的再把所有图片传给后端，而不是一个一个的搞上传

**Comment by edwinhuish** [comment]
https://learnku.com/docs/dcat-admin/1.x/picture-file-upload/8106#b6329f
