### ISSUE TITLE
模型属性修改器无法上传图片

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#1508]
- Laravel Version: 6.0
- PHP Version: 7.3
- Dcat Admin Version: 1.6.5

### Description:
有个字段是用来存贮图片信息的，再模型里设置属性修改之后，后台无法上传图片了

模型方法
/**
     * @param $value
     */
    public function setThumbAttribute($value)
    {
        $this->attributes['thumb'] = setImagePath($value);
    }

    /**
     * @param $value
     * @return string
     */
    public function getThumbAttribute($value)
    {
        return getImagePath($value);
    }

**Comment by jqhph** [comment]
不要用获取器，建议定义成其他方法
```php
public function getThumb()
{
     return getImagePath($this->thumb);
}

$model->getThumb()

```

**Comment by joey2017** [comment]
好的，多谢百忙之中抽空答复
