### ISSUE TITLE
设置模型修改器之后无法上传图片了

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#1513]
Laravel Version: 6.0
PHP Version: 7.3
Dcat Admin Version: 1.6.5
Description:
有个字段是用来存贮图片信息的，再模型里设置属性修改之后，后台无法上传图片了，显示上传成功，路径也对，但是图片没有显示出来

模型方法
/**
* @param $value
*/
public function setThumbAttribute($value)
{
$this->attributes['thumb'] = setImagePath($value);
}

/**
 * @param $value
 * @return string
 */
public function getThumbAttribute($value)
{
    return getImagePath($value);
}

**Comment by jqhph** [comment]
Duplicate of #1508
