### ISSUE TITLE
从 2.1.1-beta 升级到 2.1.5-beta 后，表单验证出现问题

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#1516]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: 2.1.5-beta

### Description:
从 2.1.1-beta 升级到 2.1.5-beta 后，表单验证出现问题，如果表单提交的是附加表字段的数据更新，如 post_mata.rank，

```
$form->text('post_meta.rank')->rules('numeric', ['numeric' => '排序权重须是数字']);
```

则提交时会报错：**post meta 必须是一个数字**

感觉应该是 vendor/dcat/laravel-admin/src/Form/Concerns/HasFieldValidator.php 这个更新的问题，第 371行改为：

```
Arr::set($rules, $this->column, $fieldRules);
```

这个以后，$rules 规则变成了这样

```
[
    "post_meta" => [
        "rank" => [
            0 => "numeric"
        ]
    ]
]
```

是否应该是 

```
[
    "post_meta.rank" => [
        0 => "numeric"
    ]
]
```

希望能帮忙看看，谢谢！

**Comment by jqhph** [comment]
你这个字段是一对一表单还是json字段？

**Comment by patrick-zhao-51** [comment]
一对一表单，不是json字段

**Comment by jqhph** [comment]
好的我看下这个问题

**Comment by patrick-zhao-51** [comment]
> 好的我看下这个问题

谢谢

**Comment by jqhph** [comment]
确实有问题，感谢反馈，本周会发布新版本

**Comment by patrick-zhao-51** [comment]
> 确实有问题，感谢反馈，本周会发布新版本

谢谢
