### ISSUE TITLE
currency和number默认值不生效

### ISSUE THREAD

**Issue by warmup413** [jqhph/dcat-admin#1518]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version:2.1.5

### Description:
currency设置默认值依然为空
number设置默认值依然为0

### Steps To Reproduce:
$form->currency('price')->default(100)->symbol('￥');
$form->number('days')->default(12)

**Comment by jqhph** [comment]
编辑页面需要设置第二个参数
$form->currency('price')->default(100, true);

**Comment by warmup413** [comment]
好的，谢谢
