### ISSUE TITLE
表单回调，删除前deleting和删除后deleted都无法获取到数据

### ISSUE THREAD

**Issue by datangkang123** [jqhph/dcat-admin#152]
`$form->deleting(function (Form $form, $result) {
    // 获取待删除行数据，这里获取的是一个二维数组
    $data = $form->model()->toArray();

    // 通过 $result 可以判断数据是否删除成功
    if (! $result) {
        return $this->error('数据删除失败');
    }

    // 跳转
    return $form->redirect('auth/user', [
        'message' => '操作成功',
    ]);

});`

**Comment by jqhph** [comment]
获取数据功能是正常的。

文档有点失误，`deleting`事件是没有`$result`参数的，我修正一下。
