### ISSUE TITLE
有时候操作会自动退出登录，回到登录页面

### ISSUE THREAD

**Issue by leogit-jf** [jqhph/dcat-admin#1524]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 1.7.8

### Description:
最近经常发现，进去操作后会经常退出登录

**Comment by jqhph** [comment]
cookie冲突了会出现这种情况

**Comment by leogit-jf** [comment]
> cookie冲突了会出现这种情况
请问应该如何解决这种情况呢

**Comment by zanwaa** [comment]
如果不是配置在域名根目录的，比如xxx.com/admin这种，可以试下修改config/session.php中，'path' => '/' 改为'path' => '/admin'

**Comment by leogit-jf** [comment]
> 如果不是配置在域名根目录的，比如 xxx.com/admin 这种，可以试下修改config/session.php中，'path' => '/' 改为'path' => '/admin'

谢谢，已解决

**Comment by leogit-jf** [comment]
> cookie冲突了会出现这种情况

谢谢，已解决
