### ISSUE TITLE
select 过滤如何自定义sql语句

### ISSUE THREAD

**Issue by Ya-hui** [jqhph/dcat-admin#1529]
- Laravel Version: 8.*
- PHP Version: 7.4
- Dcat Admin Version: 2.*

在使用select 过滤时如何自定义sql语句

$filter->equal('record_url')->select([0 => '无录音', 1 => '有录音']);

在表里  record_url  是个url地址， 当选择0时查询  record_url 为空的数据， 当选1 时 显示record_url 不为空的数据

**Comment by jqhph** [comment]
具体使用参考文档
$filter->where('record_url', function ($q) {  $q->where(...) })->select([0 => '无录音', 1 => '有录音']);
