### ISSUE TITLE
数据详情

### ISSUE THREAD

**Issue by Everan-1994** [jqhph/dcat-admin#153]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.3.4

> 问题

```
$show->panel()
    ->style('danger')
    ->title('post基本信息...');
```

这里的 ```style``` 貌似不起作用。

![image](https://user-images.githubusercontent.com/33532865/82720674-4a3bcc00-9ce8-11ea-988a-6a4bbb996666.png)

**Comment by jqhph** [comment]
这个功能已经废弃了，后面会删除掉
