### ISSUE TITLE
获取selectTable其他列的数据

### ISSUE THREAD

**Issue by AilonHuang** [jqhph/dcat-admin#1531]
- Laravel Version: 8.4
- PHP Version: 8.0
- Dcat Admin Version: 2.1

### Description:
请问怎么获取selectTable其他列的数据，想要获取其他列的数据显示在表单上

**Comment by jqhph** [comment]
文档有的

**Comment by AilonHuang** [comment]
> 文档有的

可能我没表达清楚，我看到文档上只能获取两个字段，一个作为key，一个作为value。
我现在的需求是：假设是用户表的selectTable，字段有id，name，age，我想要选择的时候显示name，在另外一个输入框显示age的值

**Comment by webceoboy** [comment]
> > 文档有的
> 
> 可能我没表达清楚，我看到文档上只能获取两个字段，一个作为key，一个作为value。 我现在的需求是：假设是用户表的selectTable，字段有id，name，age，我想要选择的时候显示name，在另外一个输入框显示age的值

也是这个需求
