### ISSUE TITLE
数据表格怎么实现按照复杂排序

### ISSUE THREAD

**Issue by hlf2016** [jqhph/dcat-admin#1532]
- Laravel Version: 6
- PHP Version: 7
- Dcat Admin Version: 2

### Description:
数据表格怎么实现按照复杂排序

### Steps To Reproduce:
如 在用户列表中 按照用户当月成功订单数排序

**Comment by jqhph** [comment]
$grid->model()->withCount('orders');

$grid->column('orders_count')->sortable();

**Comment by hlf2016** [comment]
谢谢大佬  太赞了
还有一个问题哈 
就是怎么可以在筛选的时候 根据查出来的聚合值进行筛选
比如 一个 `users` 表和一个 `orders` 表，我需要在这个用户列表的地方有个筛选按钮可以筛选出已经成功下过订单的用户
