### ISSUE TITLE
为什么新增操作验证失败要删除所有图片，还不支持配置

### ISSUE THREAD

**Issue by JH-Y** [jqhph/dcat-admin#1534]
- Laravel Version: 8.54
- PHP Version: 8.0
- Dcat Admin Version: 2.1.5

为什么新增操作验证失败要删除所有图片，删除了没有任何提醒，图片还是存在，最后保存成功，图片却不展示

**Comment by jqhph** [comment]
没理解你的意思，验证失败不会删除图片，麻烦贴下代码描述更详细一点

**Comment by JH-Y** [comment]
![image](https://user-images.githubusercontent.com/20234987/138799555-dcc4a7ba-52c1-4680-a9f3-d8abccc6141f.png)
表单验证方法，如果其他有字段验证失败并且是新增操作，就会把上传的文件都删除掉，然而前端图片还显示，保存后图片就不展示了
