### ISSUE TITLE
EloquentRepository 中 updateRelation 时会重复 prepareUpdate

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#1535]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: 2.1.5-beta

### Description:

在存储关联表的数据时，发现有重复 prepareInputValue 的问题，这个重复处理在处理一般字段不会报错，但如果是 keyValue 的时候，就会报错，因为原来已经把数据处理为 [ key => value ] 的数组了，再处理的时候会报错 **Undefined index: keys**，因为在 src/Form/Field/KeyValue.php 的 **prepareInputValue** 方法中 return array_combine($value['keys'], $value['values']); 时，keys 这个键名不存在。

仔细查看了一下代码，发现应该这样发生的：

src/Form.php 的 update 方法中 prepareUpdate (798 行) 后，在 src/Repositories/EloquentRepository.php 的 updateRelation 时，因为是 $oneToOneRelation，又被 prepareUpdate (829 行) 了一次。

不知道这个 oneToOneRelation 为什么还要做一次 prepareUpdate？是否是一个 BUG

**Comment by jqhph** [comment]
keyValue是json表单，没有兼容model关联关系

**Comment by patrick-zhao-51** [comment]
您的意思是不能在一对一的关系表中存储 json 数据时使用 keyValue 这种 field？

那用什么字段类型存储这个自定义的 json 数据呢？

https://learnku.com/docs/dcat-admin/2.x/json-form/8746#9f83eb

用 table ？

**Comment by patrick-zhao-51** [comment]
使用 table 处理可以，谢谢！
