### ISSUE TITLE
下拉选框联动问题

### ISSUE THREAD

**Issue by loveloving** [jqhph/dcat-admin#1536]
![image](https://user-images.githubusercontent.com/81601240/138549459-d2a2f74f-9b78-4b33-af8e-79fbf6dbfd53.png)

### 问题

不支持 两个load 事件, 希望新版本 支持一下

**Comment by jqhph** [comment]
有loads方法，可以支持联动多个字段

**Comment by loveloving** [comment]
好的, 👍🏻👍🏻
