### ISSUE TITLE
切换行操作按钮显示方式配置为Dcat\Admin\Grid\Displayers\ContextMenuActions::class时发生的错误显示

### ISSUE THREAD

**Issue by kan-din** [jqhph/dcat-admin#1542]
- Laravel Version: 8.5
- PHP Version: 8.0.2
- Dcat Admin Version: 2.1.5

### Description:

        /*
        |--------------------------------------------------------------------------
        | The global Grid action display class.
        |--------------------------------------------------------------------------
        */
        'grid_action_class' => Dcat\Admin\Grid\Displayers\ContextMenuActions::class,

当配置表格:切换行操作按钮显示方式配置为 _Dcat\Admin\Grid\Displayers\ContextMenuActions::class_ 会发生重叠，我不得不使用 **_Dcat\Admin\Grid\Displayers\DropdownActions_** 下拉菜单方式

当切换右侧菜单栏时会发生如下图效果：
这是正常的
![image](https://user-images.githubusercontent.com/48144651/139407901-65c3754c-ec9f-4adc-8ec3-61d53b0fc83f.png)

这是不正常的：因为这个表格是没有禁用操作按钮的
![image](https://user-images.githubusercontent.com/48144651/139408888-c418a9e7-37ea-483a-8f45-3f71629bae5f.png)

**Comment by cyanogenic** [comment]
我也遇到了同样的问题
