### ISSUE TITLE
分步表单报错

### ISSUE THREAD

**Issue by smarteng** [jqhph/dcat-admin#1545]
- Laravel Version: v6.20.36
- PHP Version: 7.4.25
- Dcat Admin Version: 2.1.5-beta

### Description:
分步表单报错
![image](https://user-images.githubusercontent.com/663786/139853906-7e29f67e-9335-46b8-9590-5dbb9d5562e8.png)
Field type [multipleSteps] does not exist.

**Comment by NaturalGao** [comment]
怎么解决的？
