### ISSUE TITLE
[BUG] 编辑模式-图片上传缩略图消失

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#1556]
在新建模式
图片上传缩略图都正常
但在编辑模式
如果又添加新图片或是图片重新排序
原图还在但缩略图会不见

```
$form->multipleImage('photos')
->uniqueName()->sortable()->autoUpload()
->saving(function ($paths) {
     return json_encode($paths);
})
->fit(1000, 1000)
->thumbnail([
    's' => [300, 300],
    'm' => [600, 600],
    'thumb' => [100, 100],
])
```

**Comment by rcc03461** [comment]
1,
.env 
APP_URL=

2,
php artisan storage:link

**Comment by kevin700523** [comment]
跟这些设定无关喔, 新增图片都是没问题的
只有在编辑时选继续添加，或是排序调整后

![截圖 2021-11-10 下午5 22 57](https://user-images.githubusercontent.com/16574141/141086302-3b916502-9443-4a7b-8a61-1090dba7b5a8.png)

原先的缩略图会消失

**Comment by kevin700523** [comment]
@jqhph 
老大 可以帮忙看一下这个问题吗? 
只有编辑场景
进行图片排序或是再添加图片才会出现这个问题 

新建都不会

**Comment by jqhph** [comment]
好的，你是什么版本？

**Comment by kevin700523** [comment]
是 v2.1.5

**Comment by kevin700523** [comment]
@jqhph 老大 请问有找到问题吗？

**Comment by jqhph** [comment]
本周发布新版本解决这个问题

**Comment by jqhph** [comment]
已修复

**Comment by kevin700523** [comment]
感谢老大
