### ISSUE TITLE
分块布局不支持 multipleSelect 、image、checkbox 等表单组件编辑状态的数据获取

### ISSUE THREAD

**Issue by XinJiangQingMang** [jqhph/dcat-admin#156]
- Laravel Version: ^7.0
- PHP Version: 7.3.x
- Dcat Admin Version: master

### Description:
```
  $form->setDefaultBlockWidth(7);
            $form->block(5, function (Form\BlockForm $form) {

})
```

分块布局 内不支持 `multipleSelect` 、`image`、`checkbox` 等表单组件编辑状态的数据获取

**Comment by jqhph** [comment]
感谢反馈，确实有这个问题

**Comment by jqhph** [comment]
已修复，可以先更新master分支代码
