### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by pianqifei** [jqhph/dcat-admin#1560]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
是否可开发一款类似 https://github.com/laravel-admin-extensions/media-player.git 的多媒体播放组件用于后台多媒体文件预览展示 目前后台对应多媒体文件的预览支持不是太友好 用户上传一个视频 想要预览一下也不方便

**Comment by edwinhuish** [comment]
你可以看看这个扩展： [Dcat PHPer / dcat-media-selector](https://gitee.com/dcat-phper/dcat-media-selector)
