### ISSUE TITLE
HasMany 移除无效

### ISSUE THREAD

**Issue by byeivan** [jqhph/dcat-admin#1565]
- Laravel Version: 6.2
- PHP Version: 7.4
- Dcat Admin Version: 2.1.5

### Description:

form页面 HasMany嵌套Column 点击移除按钮后 _remove_参数还是为null 
测试删除Column后可以移除 包含Column就移除不了
没有更改过模版

**Comment by jqhph** [comment]
感谢反馈

**Comment by jqhph** [comment]
重新试了下，复现不出来了，能否贴下你的完整表单代码？

**Comment by byeivan** [comment]
> 重新试了下，复现不出来了，能否贴下你的完整表单代码？

            $form->block(12, function (Form\BlockForm $form){

                $form->showFooter();
                
                $form->hasMany('products', '', function ($form) {
                    
                    $form->column(6, function ($form) {
    
                        $form->text('remark');
                    });
                });
            });
