### ISSUE TITLE
有没有考虑做一个go版本的dcat

### ISSUE THREAD

**Issue by kilvn** [jqhph/dcat-admin#1573]
### Description:
我是从laravel-admin过来的，感觉还是dcat成熟好用。现在用go开发项目苦于没有类似dcat的成熟后台，go-admin不好用，不知道作者有没有想法做个go版本的。

### Steps To Reproduce:
No.

**Comment by jqhph** [comment]
go可以用前后端分离，go-admin已经做得不错了，再怎么做体验也比不上PHP
