### ISSUE TITLE
请问删除数据后有什么方法可以重定向到其他页面？

### ISSUE THREAD

**Issue by sprklinginfo** [jqhph/dcat-admin#1581]
Laravel Version: 8.73.1
PHP Version: 7.4.16
Dcat Admin Version: 2.1.5-beta

### Description:
数据表格或表单中使用‘delete’ 按钮后，怎样可以实现重定向到其它不同的页面啊？试验了在表单事件deleting, deleted or controller@destroy 中用redirect()都不行。

**Comment by NinoPanic** [comment]
Form的event的deleted事件 我尝试了下是有效的.
<code>deleted(function (Form $form){
            return $form->response()->redirect(admin_url('/'));
        });</code>
