### ISSUE TITLE
关于多对多  multipleSelectTable

### ISSUE THREAD

**Issue by AzureSkyHuHu** [jqhph/dcat-admin#1596]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: 2.15

### Description:

现在选完直接是一个 多选下拉框的魔改。
![image](https://user-images.githubusercontent.com/30387020/145588557-f075b5e6-2933-4f0f-b8ba-ade106866fb3.png)
![image](https://user-images.githubusercontent.com/30387020/145588593-26d47ca1-fe7a-4f37-a9eb-2f92c953da5e.png)
这样想要排序 以及做一些修改属实有点困难。。。

不知道是否已经实现 类似 https://laravel-admin.org/docs/zh/2.x/model-form-relationships
laravel-admin 的  $form->belongsToMany('collaborators', Users::class, __('协作者')); 方法
就是选完之后显示是一个表格。。

我找了下代码 未发现这个类 请问是改名了还是暂未移植过来。
如果暂未移植 请问有什么思路我可以自己改成类似的么。
如能告知 十分感谢

**Comment by jqhph** [comment]
目前没有移植这个功能
