### ISSUE TITLE
表单功能非常不错，表格这块还会加新功能吗

### ISSUE THREAD

**Issue by shenfanzi** [jqhph/dcat-admin#160]
我是不是可以期待一个既好看功能又全的表格的诞生啊

**Comment by jqhph** [comment]
表格的功能也非常全呀，不知道你想要的是什么功能？

**Comment by shenfanzi** [comment]
合并行没找到方式，复杂表头的导出我试了好像不行唉

**Comment by jqhph** [comment]
合并行不支持，这种功能现在的模式实现不了，你可以写自定义页面，或者重写Grid的view就行了

**Comment by shenfanzi** [comment]
这个OK，复杂表头已经实现了，是不是可以再配合一个导出啊

**Comment by jqhph** [comment]
> 这个OK，复杂表头已经实现了，是不是可以再配合一个导出啊

emmmmmm...这个功能用的人不是很多，你可以通过扩展导出功能自己实现
