### ISSUE TITLE
dcat v1.7.8, apexchart 雷达图显示不了，其他人能正常显示吗

### ISSUE THREAD

**Issue by skyhaydn** [jqhph/dcat-admin#1601]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by skyhaydn** [comment]
没有问题，已解决

**Comment by candivan** [comment]
> 没有问题，已解决

怎么解决的 火狐的显示不了 其他浏览器可以
