### ISSUE TITLE
列表页面Action出现混乱

### ISSUE THREAD

**Issue by xxwangel** [jqhph/dcat-admin#1608]
- Laravel Version: 8.65
- PHP Version: 7.3.0
- Dcat Admin Version: 2.1.6-beta

### Description:
两个不同页面使用不同Action呈现方式的时候，在两个页面之间切换后会出现问题

### Steps To Reproduce:
A页面用Grid\Displayers\ContextMenuActions，B页面用Grid\Displayers\Actions
当访问A页面后，再访问B页面，B页面的列表将出现右键Action菜单，并且会出现点击菜单内的动作后出现A页面对应的内容

**Comment by cyanogenic** [comment]
我也出现了同样的问题
