### ISSUE TITLE
form hasMany 为json字段时添加的时候没有问题,修改的时候显示不出来

### ISSUE THREAD

**Issue by ahjie** [jqhph/dcat-admin#161]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.4.5

### Description:
$form->hasMany('info', function (Form\NestedForm $form) {
                $form->select('type')->options(InformationType::pluck('title', 'id'));
                $form->number('num')->attribute('min', 0)->attribute('max', 10);;
                $form->currency('amount')->symbol('￥');
            })->customFormat(function ($v) {
                return Helper::array($v);
            })->saving(function ($v) {
                return json_encode($v);
            });

**Comment by ahjie** [comment]
提交数据时候 莫名的多了一条空数据
[{"id": null, "num": 1, "type": "1", "amount": "980.00", "_remove_": null}, {"id": null, "num": "0", "type": null, "amount": null, "_remove_": "1"}]
id 也不是我添加的

**Comment by ahjie** [comment]
提交数据时候 莫名的多了一条空数据
[{"id": null, "num": 1, "type": "1", "amount": "980.00", "_remove_": null}, {"id": null, "num": "0", "type": null, "amount": null, "_remove_": "1"}]
id 也不是我添加的

**Comment by ahjie** [comment]
数据库字段不能是 json 类型..

**Comment by jqhph** [comment]
嗯这个存json的时候需要自己过滤一下，`"remove": "1"`是界面上点击了删除的数据
