### ISSUE TITLE
一个 currency 引起的血案

### ISSUE THREAD

**Issue by ahu** [jqhph/dcat-admin#1611]
- Laravel Version:  8.6.5
- PHP Version: 7.4.23
- Dcat Admin Version: 2.x -> dev-master

### Description:

一开始用的是 2.x， 从 laravel-admin 转过来的。最近一段时间运气比较差。先是发现 laravel-admin 疑似作者已经弃更，其2.x版本问题不少，去年用的时候还没什么问题，前阵子用的时候差点让项目直接报废——各种报错，不得已各种魔改。。。话说我是 laravel-admin 的老用户了，多少也产出好几个系统了。不知道今年 @z-song 发生了什么变故...

不得已来尝试一下 dcat。早前有所耳闻，一年多没见有了独立官网，还在 learnku 有了文档，感觉很不错的样子。
知道是在 laravel-admin 基础上二开的，只不过发现变化还不小。这几天没少弯弯绕...不过基本可以理解。直到刚才一刻，一口老血啊啊啊...

其实新项目已经开发得差不多了，说自测一下吧，往一个 currency 字段写了个 10000，自动格式化为 10,000.00 了，感觉很秀。结果提交时报 bcmul 的数据 not well-formated ，不应该呀？啥情况！而且还发现 !empty(这个 currency 字段) 竟然报了 false 百思不得姐...啊是其解...直接 dd 一看我整个人都不好了：这个字段的值竟然是 10,000.00 而不是我预期中的 10000.00 

于是上来一搜，看到了这个：https://github.com/jqhph/dcat-admin/issues/98 和我的问题一模一样！问题是这是去年的 Issue，最新的2.x 版本还没改吗？好吧，按照提示升 dev-master 吧，这时惨案终于酿成！

首先是直接报错，AdminController 不见了。。。看代码，原来是去掉了 Http 路径，repulish 静态资源后，界面也不显示中文了...
只好一顿操作猛如虎，各种魔改...好嘛，现在又报Call to a member function count() on array  我天，这是要闹哪样？！

说了这么多，没有别的意思。老实说，能花大力气搞出来 dcat 给大伙用，感谢都还来不及。只不过我感觉玩开源真的不能太任性了，要不然像我这样的水货同行都混不下去了-_-|||

不多废话，继续魔改去了。

**Comment by ahu** [comment]
https://learnku.com/docs/dcat-admin/2.x/1-x-upgrade-guide/9645

这里显示从1.x 升 2.x 要全局更改命名空间

全局搜索命名空间 Dcat\Admin\Controllers 并替换为 Dcat\Admin\Http\Controllers
全局搜索命名空间 Dcat\Admin\Auth 并替换为 Dcat\Admin\Http\Auth

————————————————

dev-master 是又改回去了吗？

**Comment by ahu** [comment]
再补充发现：currency 字段出现带逗号值现象是在$form->saving 时出现的，$form正常提交是没问题的

**Comment by edwinhuish** [comment]
如果你点开源码，或者用xdebug断点调试一下，你就会发现，saving 事件，在 field 的 prepare 之前触发的。

如果你需要使用 saving，那拿到的就是前端直接发送过来的值。

![image](https://user-images.githubusercontent.com/5207925/147772506-0801801a-d746-442f-84d4-c490105d06b0.png)

**Comment by edwinhuish** [comment]
另外，对于开源，特别是MIT的开源，少点抱怨，多点贡献，世界会更美好。遇到BUG，翻翻代码，解决它，并顺带提个PR，这个才是应有的开源精神。

**Comment by ahu** [comment]
谢谢点评！主要是能力有限，见笑。
