### ISSUE TITLE
如何自定义菜单UI布局

### ISSUE THREAD

**Issue by ly2ang** [jqhph/dcat-admin#1623]
- Laravel Version: 8.7
- PHP Version: 8.0
- Dcat Admin Version: 2.1.7

### Description:
现在我想自定义菜单多栏布局，该如何操作？类似下面这样:
![image](https://user-images.githubusercontent.com/37921490/147638464-827f5288-080c-4506-a0e0-8cd4aa318684.png)

**Comment by jqhph** [comment]
参考文档[区块](https://learnku.com/docs/dcat-admin/2.x/basic-use/8138)章节，里面有更改菜单view的方法

**Comment by ly2ang** [comment]
> 参考文档[区块](https://learnku.com/docs/dcat-admin/2.x/basic-use/8138)章节，里面有更改菜单view的方法

感谢答复，我会去尝试一下
