### ISSUE TITLE
多应用使用第三方包启用插件后/admin不存在

### ISSUE THREAD

**Issue by taobali32** [jqhph/dcat-admin#1638]
- Laravel Version: 8.75.0
- PHP Version: 7.4.0
- Dcat Admin Version: 2.1.7-beta

### Description:
多应用启用三方插件后/admin路由都无法访问

### Steps To Reproduce:
1.根据文档创建NewAdmin多应用

2.下载`abbotton/dcat-sku-plus` 或`dcat-admin.operation-log`包，并启用

3./admin就不能访问了404，排查原因在`vendor/dcat/laravel-admin/src/Extend/ServiceProvider.php`
```php
        if ($routes = $this->getRoutes()) {
            $this->registerRoutes($routes);
        }
```
当我把这里注销掉的时候就可以用了，  在追进去未找到最终解决办法

**Comment by jqhph** [comment]
已修复，感谢
