### ISSUE TITLE
请问是否支持多个后台，比如商家后台和管理员后台？

### ISSUE THREAD

**Issue by iPhonePKAndroid** [jqhph/dcat-admin#164]
请问是否支持多个后台，比如商家后台和管理员后台？

**Comment by jqhph** [comment]
支持，文档有。

**Comment by iPhonePKAndroid** [comment]
恢复速度这么快，点赞

**Comment by iPhonePKAndroid** [comment]
Error: Call to a member function exists() on bool in file /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Form/Field/UploadField.php on line 96

#0 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Form/Field/UploadField.php(186): Dcat\Admin\Form\Field\File->renameIfExists(Object(Illuminate\Http\UploadedFile))
#1 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Form/Concerns/HasFiles.php(50): Dcat\Admin\Form\Field\File->upload(Object(Illuminate\Http\UploadedFile))
#2 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Form.php(796): Dcat\Admin\Form->handleUploadFile(Array)
#3 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Form.php(750): Dcat\Admin\Form->beforeUpdate(1, Array)
#4 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Controllers/AuthController.php(129): Dcat\Admin\Form->update(1)
#5 [internal function]: Dcat\Admin\Controllers\AuthController->putSetting()
#6 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#7 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\Routing\Controller->callAction('putSetting', Array)
#8 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Admin\Controllers\AuthController), 'putSetting')
#9 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\Routing\Route->runController()
#10 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\Routing\Route->run()
#11 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#12 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/WebUploader.php(30): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#13 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\WebUploader->handle(Object(Illuminate\Http\Request), Object(Closure))
#14 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/Session.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#15 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\Session->handle(Object(Illuminate\Http\Request), Object(Closure))
#16 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/Permission.php(38): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\Permission->handle(Object(Illuminate\Http\Request), Object(Closure))
#18 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/Bootstrap.php(17): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#19 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#20 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/LogOperation.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#21 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\LogOperation->handle(Object(Illuminate\Http\Request), Object(Closure))
#22 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#23 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/Authenticate.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Session\Middleware\StartSession->handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#34 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#37 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/a/Downloads/admin/vendor/dcat/laravel-admin/src/Middleware/Application.php(15): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Dcat\Admin\Middleware\Application->handle(Object(Illuminate\Http\Request), Object(Closure), 'admin')
#41 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#42 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#43 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#44 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#45 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#46 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#47 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#48 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#51 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#52 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /Users/a/Downloads/admin/vendor/fruitcake/laravel-cors/src/HandleCors.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#57 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fruitcake\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#58 /Users/a/Downloads/admin/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#60 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#61 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(140): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#62 /Users/a/Downloads/admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(109): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#63 /Users/a/Downloads/admin/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#64 /Users/a/Downloads/admin/server.php(21): require_once('/Users/a/Downlo...')
#65 {main}

**Comment by iPhonePKAndroid** [comment]
后台用户头像上传出现错误

**Comment by jqhph** [comment]
参考文档常见问题

**Comment by iPhonePKAndroid** [comment]
http://127.0.0.1:8000/admin/helpers/scaffold
没能成功进入，admin可以，也有系统菜单显示，这个该怎么办

**Comment by jqhph** [comment]
看文档，开发工具

**Comment by iPhonePKAndroid** [comment]
感谢恢复弱智问题，耽误了你的时间，你回复的好快，真牛逼，微信打赏请大神喝杯咖啡，现在我这边计划用您的这款后台做快速开发，就避免耽误前端同事的时间，还在上手中，请多指教。


另外你这个可能没有查看用户那种页面，没有看到演示，类似这样，看用户相关信息的那种页面，希望有个DEMO，我们这样设计给用户体验好一些
![https://static.zaixiakefu.com/files/gfr4mUrpfCXRh7j0LL4pe07W1VMsY8y6XI4uvBBm.png](https://static.zaixiakefu.com/files/gfr4mUrpfCXRh7j0LL4pe07W1VMsY8y6XI4uvBBm.png)

**Comment by jqhph** [comment]
感谢支持！详情页就是这种查看用户的页面。你截图的这种页面需要自定义，定制起来也不难，可以参考文档开发前必读。

**Comment by Warrens-yg** [comment]
> 感谢回复无脑问题，耽误了你的时间，你回复的好快，真牛逼，微信打赏请大神喝杯咖啡，现在我这边计划用您的这款后台做快速开发，避免避免误误前端同事的时间，还在上手中，请多指教。
> 
> 另外你这个可能没有查看用户那种页面，没有看到演示，类似这样，看用户相关信息的那种页面，希望有个DEMO，我们这样的设计给用户体验好一些
> ![https://static.zaixiakefu.com/files/gfr4mUrpfCXRh7j0LL4pe07W1VMsY8y6XI4uvBBm.png](https://camo.githubusercontent.com/dd7dc87a162885d0f6e06d7109a7398a1d969000/68747470733a2f2f7374617469632e7a61697869616b6566752e636f6d2f66696c65732f676672346d5572706643585268376a304c4c34706530375731564d7359387936584934757642426d2e706e67)

请问一下，你这个页面的Tab头是自己写的吗

**Comment by iPhonePKAndroid** [comment]
> > 感谢回复无脑问题，耽误了你的时间，你回复的好快，真牛逼，微信打赏请大神喝杯咖啡，现在我这边计划用您的这款后台做快速开发，避免避免误误前端同事的时间，还在上手中，请多指教。
> > 另外你这个可能没有查看用户那种页面，没有看到演示，类似这样，看用户相关信息的那种页面，希望有个DEMO，我们这样的设计给用户体验好一些
> > ![https://static.zaixiakefu.com/files/gfr4mUrpfCXRh7j0LL4pe07W1VMsY8y6XI4uvBBm.png](https://camo.githubusercontent.com/dd7dc87a162885d0f6e06d7109a7398a1d969000/68747470733a2f2f7374617469632e7a61697869616b6566752e636f6d2f66696c65732f676672346d5572706643585268376a304c4c34706530375731564d7359387936584934757642426d2e706e67)
> 
> 请问一下，你这个页面的Tab头是自己写的吗

哪个tab头，d2框架改的，

**Comment by iPhonePKAndroid** [comment]
NewUsers演示图标块哪里，查看数据只能查看数量，比如最近30天注册的用户，只能看到格式【比标签名：x.0】能不能自定义成2020-11-22：2人这种格式？前面的标签没见到能改，好像暂时不支持呢

**Comment by Warrens-yg** [comment]
> > > 感谢回复无脑问题，耽误了你的时间，你回复的好快，真牛逼，微信打赏请大神喝杯咖啡，现在我这边计划用您的这款后台做快速开发，避免避免误误前端同事的时间，还在上手中，请多指教。
> > > 另外你这个可能没有查看用户那种页面，没有看到演示，类似这样，看用户相关信息的那种页面，希望有个DEMO，我们这样的设计给用户体验好一些
> > > ![https://static.zaixiakefu.com/files/gfr4mUrpfCXRh7j0LL4pe07W1VMsY8y6XI4uvBBm.png](https://camo.githubusercontent.com/dd7dc87a162885d0f6e06d7109a7398a1d969000/68747470733a2f2f7374617469632e7a61697869616b6566752e636f6d2f66696c65732f676672346d5572706643585268376a304c4c34706530375731564d7359387936584934757642426d2e706e67)
> > 
> > 
> > 请问一下，你这个页面的Tab头是自己写的吗
> 
> 哪个tab头，d2框架改的，

就是可删除的 tab 页签那部分，我看框架里只提供的普通的 tab 组件

**Comment by iPhonePKAndroid** [comment]
NewUsers演示图标块哪里，查看数据只能查看数量，比如最近30天注册的用户，只能看到

**Comment by iPhonePKAndroid** [comment]
> NewUsers演示图标块哪里，查看数据只能查看数量，比如最近30天注册的用户，只能看到

@jqhph

**Comment by iPhonePKAndroid** [comment]
> > > > 感谢回复无脑问题，耽误了你的时间，你回复的好快，真牛逼，微信打赏请大神喝杯咖啡，现在我这边计划用您的这款后台做快速开发，避免避免误误前端同事的时间，还在上手中，请多指教。
> > > > 另外你这个可能没有查看用户那种页面，没有看到演示，类似这样，看用户相关信息的那种页面，希望有个DEMO，我们这样的设计给用户体验好一些
> > > > ![https://static.zaixiakefu.com/files/gfr4mUrpfCXRh7j0LL4pe07W1VMsY8y6XI4uvBBm.png](https://camo.githubusercontent.com/dd7dc87a162885d0f6e06d7109a7398a1d969000/68747470733a2f2f7374617469632e7a61697869616b6566752e636f6d2f66696c65732f676672346d5572706643585268376a304c4c34706530375731564d7359387936584934757642426d2e706e67)
> > > 
> > > 
> > > 请问一下，你这个页面的Tab头是自己写的吗
> > 
> > 
> > 哪个tab头，d2框架改的，
> 
> 就是可删除的 tab 页签那部分，我看框架里只提供的普通的 tab 组件

你如果需要可以加我微信，那是我们公司的项目，我给你看哪个地方怎么写，不是我写的，

**Comment by jqhph** [comment]
> NewUsers演示图标块哪里，查看数据只能查看数量，比如最近30天注册的用户，只能看到

这个数据卡片的内容你想怎么显示都行，你点进去NewUsers看看就明白了

**Comment by iPhonePKAndroid** [comment]
> NewUsers

我就是点击进去了，然后不会定义，
<img width="1552" alt="截屏2020-05-27 下午2 00 52" src="https://user-images.githubusercontent.com/44493686/82983335-7c1f9c00-a022-11ea-8a37-333b71bfc1fb.png">

**Comment by jqhph** [comment]
> > NewUsers
> 
> 我就是点击进去了，然后不会定义，
> <img alt="截屏2020-05-27 下午2 00 52" width="1552" src="https://user-images.githubusercontent.com/44493686/82983335-7c1f9c00-a022-11ea-8a37-333b71bfc1fb.png">

你可以看下这个图表的文档，看看支不支持https://apexcharts.com/

**Comment by iPhonePKAndroid** [comment]
请问作者有没有像你这种框架，做用户管理的推荐，你这个做后台方便没毛病，用户那边需要电脑手机自适应，你这边有没有推荐？

**Comment by jqhph** [comment]
> 请问作者有没有像你这种框架，做用户管理的推荐，你这个做后台方便没毛病，用户那边需要电脑手机自适应，你这边有没有推荐？

这个我也不太清楚，手机自适应，一般都需要自己做点兼容。

**Comment by iPhonePKAndroid** [comment]
<img width="1552" alt="截屏2020-05-27 下午3 32 52" src="https://user-images.githubusercontent.com/44493686/82990846-606ec280-a02f-11ea-9714-5839c653bb72.png">

错别字

**Comment by iPhonePKAndroid** [comment]
列表数据是查看的时候，字段是json，模型转换了array没办法显示，有什么办法没？

**Comment by jqhph** [comment]
你看下文档列的显示，你可以在`display`方法的闭包中转化数据格式

**Comment by iPhonePKAndroid** [comment]
> display
在     protected function detail($id)
 里面，不会弄呀、，

```php
            $show->display('data')->with(function ($value) {
                return json_encode($value);
            });
```

**Comment by jqhph** [comment]
看下文档数据详情基本使用

```php
$show->as(function () {

})
```

**Comment by iPhonePKAndroid** [comment]
可以了，

**Comment by iPhonePKAndroid** [comment]
请教构建用户控制台有没有快速方法？

**Comment by jqhph** [comment]
什么控制台，没懂

**Comment by iPhonePKAndroid** [comment]
就像构建后台一样，构建用户中心，快速开发，我就不用写前端页面了

**Comment by jqhph** [comment]
> 就像构建后台一样，构建用户中心，快速开发，我就不用写前端页面了

你是说类似CMS这样的是吧，这个后期会开发CMS插件，现在不支持这样的功能

**Comment by iPhonePKAndroid** [comment]
> > 就像构建后台一样，构建用户中心，快速开发，我就不用写前端页面了
> 
> 你是说类似CMS这样的是吧，这个后期会开发CMS插件，现在不支持这样的功能

那现在有没有推荐呢？

**Comment by jqhph** [comment]
laravel的话目前我也没发现有成熟的，其他的比如WordPress、thinkcmf都可以看看

**Comment by iPhonePKAndroid** [comment]
好吧

**Comment by Warrens-yg** [comment]
October算吗

**Comment by iPhonePKAndroid** [comment]
创建数据的时候如何处理password密码哪里？还有更新

**Comment by lzpfmh** [comment]
> 支持，文档有。

文档链接http://www.dcatadmin.com/docs/master/multi-app.html
