### ISSUE TITLE
按钮权限？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#1646]
有计划添加 按钮权限吗？
![image](https://user-images.githubusercontent.com/11988030/150447272-65844af5-7431-46f5-b919-489fa76a502c.png)

**Comment by jqhph** [comment]
这种需要自己改

**Comment by shunhua** [comment]
> 这种需要自己改

目前权限只到  meau 是吧？

**Comment by jqhph** [comment]
不是，你可以自己写代码控制

**Comment by shunhua** [comment]
> 不是，你可以自己写代码控制

哦
