### ISSUE TITLE
laravels 内存泄漏问题

### ISSUE THREAD

**Issue by roiwk** [jqhph/dcat-admin#1647]
- Laravel Version: 8.73.1
- PHP Version: 7.4.22
- Dcat Admin Version: 2.1.7
- Laravels Version: 3.7.30
- Swoole Version: 4.8.5

### Description:

如上环境，前后台项目，laravels配置文件，按文档配置了
```
'register_providers' => [
        \Dcat\Admin\AdminServiceProvider::class,
    ],
'cleaners' => [
        Hhxsv5\LaravelS\Illuminate\Cleaners\SessionCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\AuthCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\JWTCleaner::class,
        Hhxsv5\LaravelS\Illuminate\Cleaners\DcatAdminCleaner::class,
   ],
```

### Steps To Reproduce:

按推荐配置后，发现内存一直在上升，前后台接口都是。 
1.但把’register_providers‘的配置去掉，ab压测，前台的请求不会有明显的内存持续增加，后台还会，后台会菜单栏消失。
  1.1处理了一下菜单栏消失的问题，在Admin/bootstrap.php
```
\Dcat\Admin\Admin::menu()->register();
\Dcat\Admin\Admin::extension()->register();

```
    产生了新问题， 扩展里我用到了lightbox扩展，又加载不成功了。
搞了两天，最终放弃，回到了推荐配置。

有没有好的解决方案，或者有谁碰到类似问题，有搞出来处理方法？

**Comment by seth-shi** [comment]
https://www.shiguopeng.cn/posts/2022010510/  作者说之后会修复这个问题.
这里有总结原因无非就是重复注册的问题. 自己写一个服务提供者代替掉自带的服务提供者.
