### ISSUE TITLE
laravel9 什么时候支持一下

### ISSUE THREAD

**Issue by wyzheng1997** [jqhph/dcat-admin#1658]
laravel9 什么时候支持一下

**Comment by laradocs** [comment]
已经支持了

**Comment by laradocs** [comment]
下个发布版本支持 laravel 9
你现在要支持 laravel 9 可以这么做(二选一)：
1. 把 `root/resources/lang` 文件夹 手动移动到 `root/lang`(附：root 为项目根目录)
2. 在 composer.json 文件中把版本改成 `2.0.x-dev` 然后执行 `composer update`，最后运行 `php artisan admin:publish` 重新发布文件就好了。
