### ISSUE TITLE
admin.https改为true，倒是其他外链的http图片无法显示

### ISSUE THREAD

**Issue by augustpluscn** [jqhph/dcat-admin#1662]
- Laravel Version: 8.48
- PHP Version: 7.3
- Dcat Admin Version: 2.1.0

### Description:
网站设置ssl，admin.https也改为true。
外链的http图片无法显示。
查看结果发现，实际请求的是https。

请教下，这种状况要如何处理，谢谢

**Comment by MutouLee** [comment]
.env里的app.url改为https了吗？
