### ISSUE TITLE
求教，dcat admin 如何实现授权的账号只能查看和修改权限地区的数据

### ISSUE THREAD

**Issue by weeee4** [jqhph/dcat-admin#1666]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
比如新增一个账号beijing，设置只能查看修改北京的数据，我的数据表里每一条都有区域字段。账号beijing只能查看和修改区域为 “北京” 的数据条，其他地区的数据条不展示。这个应该在dcat内应该如何实现。谢谢！！

**Comment by Robi-KenyaAA** [comment]
这个问题貌似没有解决办法（我也在寻找答案） 。

我有个想法 
登入后    写入一个  地域限制的 Session 参数
然后查询数据的时候 将这个 地域限制的Session 参数加入其中。
