### ISSUE TITLE
新的版本所有的错误都不正常显示了是什么原因呀

### ISSUE THREAD

**Issue by heartshuai** [jqhph/dcat-admin#1668]
Symfony\Component\ErrorHandler\Error\FatalError
Method Dcat\Admin\Grid::__toString() must not throw an exception, caught ParseError: syntax error, unexpected 'dd' (T_STRING) 不显示代码行数了 只显示这个grid

**Comment by heartshuai** [comment]
似乎在新的版本中加入了__string 这个魔术方法会导致不抛出异常，是不是可以在这里判断一下现在是否开启了debug模式

**Comment by jqhph** [comment]
看trace

**Comment by heartshuai** [comment]
![企业微信截图_02e0385d-26c7-4378-89d5-0430bf6912f5](https://user-images.githubusercontent.com/33921414/154913283-d41ecee9-e428-4536-91f4-fd67b0d93a36.png)

**Comment by heartshuai** [comment]
是不是这个原因导致的大佬 https://github.com/symfony/symfony/issues/6354
