### ISSUE TITLE
执行代码生成出现错误

### ISSUE THREAD

**Issue by 85636682** [jqhph/dcat-admin#1669]
- Laravel Version: 9.0
- PHP Version: 8.1
- Dcat Admin Version: 2.2.0.beta

### Description:
```
laravel.test_1  | [Tue Feb 22 02:38:24 2022] PHP Fatal error:  Declaration of Dcat\Admin\Scaffold\MigrationCreator::populateStub($name, $stub, $table) must be compatible with Illuminate\Database\Migrations\MigrationCreator::populateStub($stub, $table) in /var/www/html/vendor/dcat/laravel-admin/src/Scaffold/MigrationCreator.php on line 61
laravel.test_1  | [Tue Feb 22 02:38:24 2022] PHP Fatal error:  Declaration of Dcat\Admin\Scaffold\MigrationCreator::populateStub($name, $stub, $table) must be compatible with Illuminate\Database\Migrations\MigrationCreator::populateStub($stub, $table) in /var/www/html/vendor/dcat/laravel-admin/src/Scaffold/MigrationCreator.php on line 61
```

**Comment by xuchunyang** [comment]
我也出现了

```
[Mon Feb 28 16:01:56 2022] 127.0.0.1:64935 Accepted
[Mon Feb 28 16:01:57 2022] PHP Fatal error:  Declaration of Dcat\Admin\Scaffold\MigrationCreator::populateStub($name, $stub, $table) must be compatible with Illuminate\Database\Migrations\MigrationCreator::populateStub($stub, $table) in /Users/xcy/src/try_dcat_admin/vendor/dcat/laravel-admin/src/Scaffold/MigrationCreator.php on line 61
[Mon Feb 28 16:01:57 2022] 127.0.0.1:64935 Closing
```

代码生成器设置如下：

![CleanShot 2022-02-28 at 16 02 40](https://user-images.githubusercontent.com/4550353/155946473-05e0dd7d-5aea-4526-9e8b-bda7848a19c2.png)

**Comment by baozilala** [comment]
同样出现了问题

**Comment by mengxiao-ac** [comment]
![Uploading EB5BF7CB0C6B7B55457DE9DADF4CF7AE.jpg…]()会不会是继承父类的Illuminate\Database\Migrations\MigrationCreator出现的问题。

**Comment by mengxiao-ac** [comment]
<img width="707" alt="image" src="https://user-images.githubusercontent.com/20436006/159229152-c89110a4-b6ff-4baa-870e-76e877b97e9c.png">
<img width="641" alt="image" src="https://user-images.githubusercontent.com/20436006/159229355-fa48d28f-5708-4fc0-bb33-6116794100c9.png">


会不会是继承父类的Illuminate\Database\Migrations\MigrationCreator出现的问题。

**Comment by MutouLee** [comment]
对laravel9的适配还有问题

**Comment by baozilala** [comment]
[https://github.com/jqhph/dcat-admin/blame/56d62aa85f2451bdb7587d23b3710bf68baa610b/src/Scaffold/MigrationCreator.php](url)
github已经提交过修改了,可以先手动修复一下试试

**Comment by baozilala** [comment]
终于看到了Success

**Comment by MutouLee** [comment]
> 

测试了还是报错啊

**Comment by MutouLee** [comment]
> 终于看到了Success

按照提交记录里的修改后，成功了。但是composer包没更新
