### ISSUE TITLE
扩展页面创建扩展错误

### ISSUE THREAD

**Issue by lovemintblue** [jqhph/dcat-admin#1671]
- Laravel Version: 9.0
- PHP Version: 8.0
- Dcat Admin Version: 2.x

### Description:
Declaration of Dcat\\Admin\\Support\\OutputFormatter::format($message) must be compatible with Symfony\\Component\\Console\\Formatter\\OutputFormatter::format(?string $message): ?string

**Comment by ecshoper** [comment]
OutputFormatter::format($message) 改成  OutputFormatter::format($message):string 好像强制了 返回类型

**Comment by jqhph** [comment]
感谢反馈，我修复一下
