### ISSUE TITLE
文档建议配置为 auth/users*，提供的选项是 auth/users/*

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#168]
![批注 2020-05-28 155902](https://user-images.githubusercontent.com/46614146/83109320-2e776200-a0fc-11ea-8fe9-0dcc3dcafd33.jpg)
![Admin _ 权限 - Google Chrome 2020-05-28 16 00 27](https://user-images.githubusercontent.com/46614146/83109436-5ff02d80-a0fc-11ea-86bb-775d9b814f2f.png)

``` PHP
return collect(app('router')->getRoutes())->map(function ($route) use ($prefix) {
            if (! Str::startsWith($uri = $route->uri(), $prefix)) {
                return;
            }
            return Str::replaceFirst($prefix, '', preg_replace('/{.*}+/', '*', $uri));
        })->filter()->all();
```
看一下这里，另外恭喜 Stars 破千~

**Comment by jqhph** [comment]
你可以修改，修改完之后按 `空格` + `回车` 就行了，提供的选项是根据路由生成的

**Comment by Warrens-yg** [comment]
模型关联关系不支持下面这种吗

User → many to many → Role → many to many → Permission
``` PHP
class User extends Model
{
    use \Staudenmeir\EloquentHasManyDeep\HasRelationships;

    public function permissions()
    {
        return $this->hasManyDeep('App\Permission', ['role_user', 'App\Role', 'permission_role']);
    }
}
```
使用的话 `Admin::user()->permissions` 就可以了。

**Comment by jqhph** [comment]
这个有需求你自己改不就好了，默认的用户系统不需要用这么复杂的关系

**Comment by almas1992** [comment]
> 这个有需求你自己改不就好了，默认的用户系统不需要用这么复杂的关系

是否考虑把权限体系抽离出来以插件的形式提供？

**Comment by jqhph** [comment]
> > 这个有需求你自己改不就好了，默认的用户系统不需要用这么复杂的关系
> 
> 是否考虑把权限体系抽离出来以插件的形式提供？

现在这个也是跟插件差不多，可以禁用和覆写，后续有兴趣的可以开发更复杂的权限系统插件

**Comment by jqhph** [comment]
@Warrens-yg 权限配置这个功能在最新版本已经优化了，请升级到1.4.8版本
