### ISSUE TITLE
maatwebsite/excel:^3.1

### ISSUE THREAD

**Issue by lovemintblue** [jqhph/dcat-admin#1682]
- Laravel Version: 9
- PHP Version: 8.0
- Dcat Admin Version: 2.x

### Description:
使用maatwebsite/excel:^3.1 虽然能够正常导出 但是日志里面会有错误 
错误：
local.ERROR: Call to a member function firstItem() on null {"view":{"view":"/Users/zcy/Code/php/dcat-admin-crm/vendor/dcat/laravel-admin/resources/views/grid/table-pagination.blade.php","data":{"errors":"<pre class=sf-dump id=sf-dump-2036873985 data-indent-pad=\"  \"><span class=sf-dump-note>Illuminate\\Support\\ViewErrorBag</span> {<a class=sf-dump-ref>#1676</a><samp data-depth=1 class=sf-dump-expanded>
  #<span class=sf-dump-protected title=\"Protected property\">bags</span>: []
</samp>}

**Comment by hongbaotong** [comment]
您是怎么写的？我这里同样报这个错误，但是没法正常导出

**Comment by lovemintblue** [comment]
> 您是怎么写的？我这里同样报这个错误，但是没法正常导出

<?php
/**
 * 客户导出
 */
namespace App\Admin\Extensions;

use Dcat\Admin\Grid\Exporters\AbstractExporter;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class CustomerExporter extends AbstractExporter implements WithMapping, WithHeadings, FromCollection
{
    use Exportable;

    protected string $fileName = '客户数据';

    protected $titles = [];

    public function __construct()
    {
        $this->fileName .= '_' . Str::random(6) . '.xlsx';
        $this->titles = [
            'id' => '客户编码',
            'created_at' => '注册时间',
            'customer_category_id' => '客户分类',
            'customer_source_id' => '客户来源',
            'name' => '客户姓名',
            'phone' => '电话',
            'address' => '地址',
            'wechat' => '微信号',
            'is_add_wechat' => '是否添加微信',
            'is_success' => '是否成交',
            'follow_at' => '最新跟进时间',
            'follow_tag_id' => '跟进标签',
            'admin_user_id' => '归属工号',
        ];
        parent::__construct();
    }

    public function export()
    {
        $this->download($this->fileName)->prepare(request())->send();
    }

    public function collection()
    {
        return collect($this->buildData());
    }

    public function headings(): array
    {
        return $this->titles();
    }

    public function map($row): array
    {
        return [
            $row['id'],
            $row['created_at'],
            $row['customer_category_id'],
            $row['customer_source_id'],
            $row['name'],
            $row['phone'],
            $row['address'],
            $row['wechat'],
            $row['is_add_wechat'],
            $row['is_success'],
            $row['id'],
            $row['follow_at'],
            $row['follow_tag_id'],
            $row['admin_user_id'],
        ];
    }
}

**Comment by lovemintblue** [comment]
> 您是怎么写的？我这里同样报这个错误，但是没法正常导出

我这样写可以导出

**Comment by hongbaotong** [comment]
我用你的这个写法，在 `$this->download()->prepare()->send();` 再加一个 `exit;` 就可以了，你试试
