### ISSUE TITLE
使用octane, 导出功能报错

### ISSUE THREAD

**Issue by wilbur-yu** [jqhph/dcat-admin#1686]
- Laravel Version: 9.5.1
- PHP Version: 8.0.16
- Dcat Admin Version: 2.2.0-beta

在grid中启用export
```php
function (Grid $grid) {
      $grid->export()->xlsx();
      $grid = $this->filter(
          $grid,
          ['student', 'items', 'items.lesson', 'items.sku', 'ski'],
      );
}
```
启动应用
```bash
➜ composer start-dev
> php artisan octane:start --watch --port=9821

   INFO  Server running…

  Local: http://127.0.0.1:9821

  Press Ctrl+C to stop the server

```

访问报错信息
<img width="1904" alt="image" src="https://user-images.githubusercontent.com/7148309/158792739-2f8c1f2f-dccd-47fc-8903-06e7d2b0c6c7.png">

**Comment by microvencn** [comment]
同样遇到了这个问题。
这是因为返回响应后是由 Octane 再次转发到 Swoole/RoadRunner 服务器的，而因为 `export()` 是强制发送了响应（而不是返回一个响应对象由 Octane 捕获然后转发），所以 Octane 在读取响应内容的时候会直接读到文件内容。另外原生的 `export()` 方法里面也使用了 `exit`，也导致了 `swoole exit` 的异常。

**Comment by cnbattle** [comment]
+1

**Comment by uniteweiwei** [comment]
有解决方案没?同样碰到这个导出的问题了

**Comment by microvencn** [comment]
有解决方案，放在 learnku 了












吴博维
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月28日(周二) 晚上6:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jqhph/dcat-admin] 使用octane, 导出功能报错 (Issue #1686)




 
有解决方案没?同样碰到这个导出的问题了

**Comment by uniteweiwei** [comment]
![image](https://user-images.githubusercontent.com/19373139/221825936-720557de-5092-4d73-919e-3d6195fed2eb.png)
![image](https://user-images.githubusercontent.com/19373139/221826029-f87915f5-9fe3-4f0e-8692-33093f228fe6.png)
![image](https://user-images.githubusercontent.com/19373139/221826107-679decef-f6f4-415f-96e1-649a4f99e5f6.png)
![image](https://user-images.githubusercontent.com/19373139/221826382-100a2fa8-6f24-4293-b529-7a5dec9e025f.png)

更改之后还是无效,我用的是laravel-s,照道理来说是一样的,代码应该是没问题的,按照learnku一样的敲下来的

**Comment by cnbattle** [comment]
我的目的是 打包docker image， 
之前用octane swoole 打包， 现在改为  nginx php的方式， 用基于 webdevops/php-nginx 打包, 最终image 大了很多，但功能正常了 0.0

**Comment by uniteweiwei** [comment]
尝试了好多遍,没有方法,这个exit太厉害了...用laravel-s这个包,再用dcat-admin做导出是没有好的办法的

**Comment by whd-source** [comment]
![image](https://user-images.githubusercontent.com/19921310/223647530-e0756f2a-6c34-4432-8aee-cf330be3c192.png)
![image](https://user-images.githubusercontent.com/19921310/223648864-4124fa50-35fb-407a-9a8f-ea648d97554e.png)
![image](https://user-images.githubusercontent.com/19921310/223649001-33723407-051f-4cb6-8360-dbff42474e22.png)
octane swoole 模式下已解决
