### ISSUE TITLE
（文章）编辑界面，上传图片成功之后，保存（文章）刚刚上传的图片就被删除

### ISSUE THREAD

**Issue by liyangphp** [jqhph/dcat-admin#169]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
（文章）编辑界面，上传图片成功之后，保存（文章）刚刚上传的图片就被删除，上传就提交了一次编辑，再去保存就在编辑一次可是问什么要删除图片呢？搞不懂

**Comment by jqhph** [comment]
贴上完整的表单代码，以及安装的版本

**Comment by liyangphp** [comment]
php 7.2.30 laravel 6.2 Dcat Admin Version 1.3

ArticleController form 这一块
    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new Article(), function (Form $form) {
            $form->display('id');
            $form->text('author');
            $form->text('title');
            $form->select('category_id')->options('/api/category');
            $form->image('img');
            $form->editor('content');
            $form->number('watches');
            $form->select('status')->options([0 => '禁用', 1 => '正常'])->default(1);
        
            $form->display('created_at');
            $form->display('updated_at');
        });
    }

**Comment by jqhph** [comment]
你是不是没有点上传按钮

**Comment by jqhph** [comment]
另外推荐你升级到最新版本

**Comment by liyangphp** [comment]
点击了  之后有保存的  点击之后  图片上传到服务器，更新文章图片对不对，然后在保存的时候 上传的图片就消失了  本地图片就不见了

**Comment by liyangphp** [comment]
我更新的试试吧

**Comment by jqhph** [comment]
试了下，最新版本没有发现你这种情况，建议你升级到最新版本再试试。

**Comment by liyangphp** [comment]
嗯嗯  明白

**Comment by liyangphp** [comment]
是model层的问题  只要设置getImgAttr这个属性  编辑图片就会有问题  我刚开始不怎么明白  好像懂了
