### ISSUE TITLE
如何改造批量上传为web直传AliOSS？

### ISSUE THREAD

**Issue by juvenileL** [jqhph/dcat-admin#1691]
- Laravel Version: 8.0
- PHP Version: 8.0
- Dcat Admin Version:  2

如何改造当前的上传组件为前端直传ALiOSS，我尝试了增加vue组件上传，但是因为表单的结构，会造成vue的script标签在div内导致报错，是否有其他的方法可以便捷实现该功能？

**Comment by laradocs** [comment]
打开 `config/admin.php` 文件，找到以下内容：

```
'upload' => [

        // Disk in `config/filesystem.php`.
        'disk' => 'public', // 将 `public` 改成你需要的驱动

    ],
```
