### ISSUE TITLE
文件上传 重复命名

### ISSUE THREAD

**Issue by fangmuke** [jqhph/dcat-admin#1692]
- Laravel Version: 9.5.1
- PHP Version: 8.0.2
- Dcat Admin Version: 2.0.0

### Description:
https://github.com/jqhph/dcat-admin/blob/5d706631af7afdab955771103779038ee0d01a36/src/Form/Field/UploadField.php#L197

希望在此处增加可选配置，用于控制是否覆盖文件。

**Comment by laradocs** [comment]
上传文件之后如果有重复的文件会生成随机文件名

**Comment by fangmuke** [comment]
就是不想要随礼文件名，文件名需要固定格式。
> 上传文件之后如果有重复的文件会生成随机文件名

**Comment by laradocs** [comment]
已解决

**Comment by laradocs** [comment]
更改详情见 [PR#1704](https://github.com/jqhph/dcat-admin/pull/1704)
