### ISSUE TITLE
自定义头部导航条内容输出两遍

### ISSUE THREAD

**Issue by Gwill** [jqhph/dcat-admin#1695]
- Laravel Version: 9.5.1
- PHP Version: 8.1
- Dcat Admin Version: 2.2.0-beta

### Description:

bootstrap.php 中自定义导航条

![image](https://user-images.githubusercontent.com/692980/159859661-48e93055-fe90-43ef-8252-92d1d05fdcca.png)

显示情况

![image](https://user-images.githubusercontent.com/692980/159859713-c021851f-ac56-486a-83c7-70eeccd4e52a.png)

内容被输出两遍

**Comment by laradocs** [comment]
我这边是正常的，执行 ```composer update -oW``` 试试

**Comment by Gwill** [comment]
> 我这边是正常的，执行 `composer update -oW` 试试

不行，还是输出两次

**Comment by Gwill** [comment]
找到原因了，我用了 spatie/laravel-settings 包，他默认会自动发现载入配置，所以会执行一次 bootstrap.php
