### ISSUE TITLE
markdown 编辑器中应用的cdn无法访问

### ISSUE THREAD

**Issue by lonycn** [jqhph/dcat-admin#1697]
- Laravel Version: 8.65
- PHP Version: 7.3
- Dcat Admin Version: 2.2.0-beta

### Description:

markdown 编辑器中应用的cdn无法访问。能否改成本地资源？

### Steps To Reproduce:
<img width="2347" alt="image" src="https://user-images.githubusercontent.com/29355918/160221353-793f048b-a0ed-4748-8fa0-7c7e8d3f179b.png">

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/29355918/160221377-3d2b2c5d-2029-4002-9af3-bfcaf2b0ccd7.png">

**Comment by laradocs** [comment]
区域问题

**Comment by laradocs** [comment]
你的区域不能访问，你可以在 `app/Admin/bootstrap.php` 里面自己引入一个
