### ISSUE TITLE
文档中自定义头部导航条出的demo代码无法正常执行

### ISSUE THREAD

**Issue by zxdstyle** [jqhph/dcat-admin#17]
- Laravel Version:  7.3
- PHP Version: 7.2
- Dcat Admin Version:  dev

### Description:
![image](https://user-images.githubusercontent.com/38398954/77916812-42554200-72cc-11ea-909e-8b107033868d.png)

### 报错
![image](https://user-images.githubusercontent.com/38398954/77916881-5e58e380-72cc-11ea-9c81-0832821481af.png)

更换为 `\Dcat\Admin\Layout\Navbar` 可正常执行

**Comment by jqhph** [comment]
感谢反馈，文档目前还在调整当中，很多地方都还不完善。

**Comment by jqhph** [comment]
[文档](http://www.dcatadmin.com/docs/master/custom-navbar.html)已更新，并且这个设置导航栏内容的方法也优化了，代码在master分支
