### ISSUE TITLE
数据列表的 switch 显示

### ISSUE THREAD

**Issue by Everan-1994** [jqhph/dcat-admin#170]
> 当前的

![image](https://user-images.githubusercontent.com/33532865/83317833-65678800-a262-11ea-9c65-9210ed433f77.png)

> 想要的效果

![image](https://user-images.githubusercontent.com/33532865/83317855-9a73da80-a262-11ea-9dfd-24937a4ebdb1.png)

**说明**：就是可以在 switch 开关上加上文字说明

**Comment by jqhph** [comment]
现在用的这个插件不支持设置文字说明，需要文字说明建议用`select`代替`switch`

**Comment by Everan-1994** [comment]
@jqhph  好的
