### ISSUE TITLE
数据表单一对多，保存正常，再编辑时不显示关联的数据

### ISSUE THREAD

**Issue by suzhiF** [jqhph/dcat-admin#1710]
- Laravel Version:  8.83.6
- PHP Version: 7.4.3
- Dcat Admin Version: 2.2.0

**Comment by laradocs** [comment]
截个图看看

**Comment by yavana** [comment]
如图，二次编辑时，一对多的省市县联动，数据应该填充进去，然后又被load给置为空了，且不同行数据 要干扰？
![微信截图_20220519192206](https://user-images.githubusercontent.com/13197932/169282445-46186ef8-5673-413e-a354-af5ddd4bcd06.png)
![微信截图_20220519192615](https://user-images.githubusercontent.com/13197932/169282791-fa7baf3b-1dce-4043-bce6-92e8a39df1fb.png)

**Comment by yavana** [comment]
> 

帮看看

**Comment by yavana** [comment]
$form->hasMany('addr',"继续添加工作地点", function ($form) {
                    $form->row(function (Form\Row $form) {
                        $form->width(3)
                            ->select('province_id','省份')
                            ->options('/getProvince')
                            ->placeholder('选择省份')
                            ->load('city_id', '/getCity')
                            ->required();
                        $form->width(3)
                            ->select('city_id','城市')
                            ->placeholder('选择城市')
                            ->load('district_id', '/getDistrict')
                            ->required();
                        $form->width(3)
                            ->select('district_id','区县')
                            ->placeholder('选择区县')
                            ->required();
                    });
                });

**Comment by keepanote** [comment]
需要model先with，参考表单关联关系文档
eg:
$builder = new Inbound(['items']);
return Form::make($builder, function (Form $form) {
}
