### ISSUE TITLE
升级Laravel 9之后出现代码生成器的创建表迁移文件的一个bug

### ISSUE THREAD

**Issue by xiaoluome** [jqhph/dcat-admin#1712]
- Laravel Version: 9.6.0
- PHP Version: 8.0.2
- Dcat Admin Version: 2.2.0

### Description:

代码生成器的创建表迁移文件出现一个bug

`Declaration of Dcat\Admin\Scaffold\MigrationCreator::populateStub($name, $stub, $table) must be compatible with Illuminate\Database\Migrations\MigrationCreator::populateStub($stub, $table) `

这个是我升级laravel 9之后出现的bug，populateStub方法跟Laravel的populateStub方法冲突了。

### Steps To Reproduce:

**Comment by laradocs** [comment]
这个 bug 被修复了，但是没有发布

**Comment by myhui0926** [comment]
临时修复方案参照这个issue：https://gitee.com/jqhph/dcat-admin/issues/I52KIU

**Comment by laradocs** [comment]
在 composer.json 文件中把 dcat/laravel-admin 版本改成2.0.x-dev 执行 composer update 就好了
