### ISSUE TITLE
number字段添加disable方法后,字段两侧的加减号仍然可以点击

### ISSUE THREAD

**Issue by cyanogenic** [jqhph/dcat-admin#1717]
- Laravel Version: 8.7.5
- PHP Version: 7.4.3
- Dcat Admin Version: 2.2.0-beta
### Description:
数据表单中给number字段添加disable方法后，字段两侧的加减号仍然可以点击
`$form->number('test')->disable();`
效果如下图
![test](https://user-images.githubusercontent.com/13376066/162598904-7c30ec34-a478-4c7a-9211-52fa982f6557.png)

**Comment by baozilala** [comment]
我也发现这个问题了,却是存在

**Comment by laradocs** [comment]
Fixed #1771
