### ISSUE TITLE
使用分页 select 时, 无默认列表选项, 只能通过搜索获取列表

### ISSUE THREAD

**Issue by getda** [jqhph/dcat-admin#1728]
- Laravel Version: 8.83.3
- PHP Version: 8.0.9
- Dcat Admin Version: 2.2.0-beta

### Description:
在没有搜索前应该如下代码展示 10 条默认数据, 然而现在只能通过搜索获取到数据
#### Form
```
$form->select('category_id')
                ->options(fn() => Model::take(10)->pluck('name', 'id'))
                ->ajax('api/categories/select');
```
#### Api
```
public function select()
{
    $q = request('q');
    return Model::where('name', 'like', "%$q%")->paginate(null, ['id', 'name as text']);
}
```

#### 搜索前
![image](https://user-images.githubusercontent.com/25134062/163592433-e4508ae0-780c-4c98-b056-c136d0e2ec82.png)

#### 搜索后
![image](https://user-images.githubusercontent.com/25134062/163592524-3964fdd1-b82b-468a-b96a-7d7b9d3d7b22.png)

#### 参考文档测试同样得结果
![image](https://user-images.githubusercontent.com/25134062/163592682-7cfdf23f-94f3-4974-9456-5da7fc429e9e.png)

**Comment by pyx02502** [comment]
遇到了同样的问题,请问题主解决了吗

**Comment by laradocs** [comment]
> 遇到了同样的问题,请问题主解决了吗

丢个 demo 出来看看

**Comment by pyx02502** [comment]
> 
我这想显示拼接后的结果
**Form**
```
$form->select('softwares_id')->options(function ($id) {
    $software = Software::find($id);
    if ($software) {
        return [$software->id => $software->name.' '.$software->version];
    }
})
->ajax('api/softwares');
```
**Api**
```public function sPaginate(Request $request)
    {
        $q = $request->get('q');
        return Software::where('name', 'like', "%$q%")->paginate(null, ['id', 'name as text']);
    }
```
@laradocs

**Comment by getda** [comment]
> 遇到了同样的问题,请问题主解决了吗

没有解决

**Comment by getda** [comment]
你们谁解决了可以分享一下😂

**Comment by wxfjamdc** [comment]
不改变源码得情况下，在ajax()后面增加
```
->config('minimumInputLength',0)
```
执行无参数请求获取对应列表
