### ISSUE TITLE
请问有像Laravel-admin的模型表格固定列的功能吗 $grid->fixColumns(3, -2);

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#173]
当表格的字段特别多时，当前界面只能显示一部分，剩下的都要靠滚动条拖动。     
Laravel-Admin可以用 `$grid->fixColumns(3, -2);` 来固定首尾的列。  
但是Dcat-Admin没有找到类似的方法，请问有什么好的处理建议吗。

**Comment by jqhph** [comment]
可以用`responsive`方法显示滚动条，或者手动写css
```php
Admin::style(
    <<<'CSS'
.table-responsive {
    overflow-x: auto;
}
CSS
);
```

**Comment by metanoia1989** [comment]
> 可以用`responsive`方法显示滚动条，或者手动写css
> 
> ```
> Admin::style(
>     <<<'CSS'
> .table-responsive {
>     overflow-x: auto;
> }
> CSS
> );
> ```

底部是有横向滚动条的，但是默认表格有20行的时候，需要翻动到页面底部，像Laravel-Admin可以固定列，最重要的是尾部的行操作按钮。
![表格末尾](https://i.imgur.com/hEnTaRQ.png)
![滑动到页面底部](https://i.imgur.com/dMpJ9B7.png)

下面是Laravel-Admin固定列的效果，可以很方便的处理行操作。
![这个是Laravel-admin的效果](https://i.imgur.com/sKLIDsx.png)

**Comment by jqhph** [comment]
嗯后续会支持fixColumn的，操作列的话你可以改成右键显示的方式，就不用拉到最右边了

**Comment by jqhph** [comment]
另外推荐你升级到最新版本，你这个版本是不支持鼠标右键显示操作列下拉菜单的

**Comment by metanoia1989** [comment]
> 嗯后续会支持fixColumn的，操作列的话你可以改成右键显示的方式，就不用拉到最右边了

谢谢回复，我用的这个版本是`"dcat/laravel-admin": "^1.4",`，支持右键显示，不过全部默认配置的是下拉菜单方式。

固定列，Laravel-Admin 好像也是通过 `Admin::style()` 和 `Admin::script()` 方式实现的：<https://github.com/z-song/laravel-admin/blob/master/src/Grid/Tools/FixColumns.php>

参考Laravel-Admin的实现应该能够解决我的问题。
