### ISSUE TITLE
右边弹出筛选菜单搜索按钮不显示问题

### ISSUE THREAD

**Issue by woodynew** [jqhph/dcat-admin#1730]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: #.#.#

### Description:
苹果浏览器，夸克浏览器
表格筛选右边弹出方式，弹出后搜索按钮不显示，前端代码都有，可能是渲染问题，也有占位

### Steps To Reproduce:

苹果浏览器打开表格页面，筛选通过右边弹出

**Comment by laradocs** [comment]
截图发出来看看
