### ISSUE TITLE
dactadmin 没有 totalRow 么

### ISSUE THREAD

**Issue by lingzhiyanna** [jqhph/dcat-admin#1734]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.0

### Description:

[dactadmin 没有 totalRow 么] 
怎么是实现这个功能 每列 最下面 数据求和

**Comment by laradocs** [comment]
没有

**Comment by laradocs** [comment]
数据求和可以放在 title 里面，或者你找找有没有更好的方法
