### ISSUE TITLE
laravel5.5安装dcat2.*报错

### ISSUE THREAD

**Issue by xiaojian520** [jqhph/dcat-admin#1736]
- Laravel Version: 5.5.50
- PHP Version: 7.1.12
- Dcat Admin Version: #.#.#

### Description:
安装报错:
 Problem 1
    - Root composer.json requires dcat/laravel-admin 2.*, found dcat/laravel-admin[2.0.0-beta, ..., 2.2.0-beta] but it does not match your minimum-stability.

### Steps To Reproduce:
composer require dcat/laravel-admin:"2.*"

**Comment by mbdmt** [comment]
我覺得你這php版本可能只能裝1.x
不然至少得上php7.3  建議上7.4
