### ISSUE TITLE
datetimeRange设置默认值无效

### ISSUE THREAD

**Issue by leogit-jf** [jqhph/dcat-admin#1737]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 2.*

### Description:
使用default(['start' => '2022-03-12 12:23:32','end' => '2022-03-12 12:23:33'])设置默认值无效

**Comment by laradocs** [comment]
把版本切换到 `2.0.x-dev` 试试，我这边是有效的。
