### ISSUE TITLE
json表单 embeds 上传图片问题

### ISSUE THREAD

**Issue by killjin** [jqhph/dcat-admin#1742]
- Laravel Version: #9.#.#
- PHP Version: #8.#.#
- Dcat Admin Version: #.#.#

### Description:
json表单 embeds ，图片 image 有问题，指定一个字段名，不能上传，必须指定一个已经存在的字段。

```
form->embeds('employ_security', function ($table) {

                $table->image('image1111', 'xxx')  //这个image111不存在这个字段则不能上传
                ->uniqueName()
                ->accept('jpg,png,gif,jpeg', 'image/*')
                ->removable(false)
                ->autoUpload();

            })->saving(function ($v) {
                // 转化为json格式存储
                return json_encode($v);
            });
```

**Comment by killjin** [comment]
如果指定 image字段存在，会覆盖 image字段，导致image上传不成功

**Comment by mouyong** [comment]
将你的 field 字段用不同名字取展示。

在 saving 阶段获取所有数据，删除自定义的字段名。

然后重新设置 input 里面的数据。根据需要使用 saved函数，并 use ($data) 进行额外操作。

![image](https://user-images.githubusercontent.com/10336437/170180981-7f16f1a3-afb2-4389-bf64-d4ce29f67b07.png)

**Comment by laradocs** [comment]
使用 $form->image('options.avatar'); 指定一下试试

**Comment by laradocs** [comment]
Fixed [#1766](https://github.com/jqhph/dcat-admin/pull/1766/files)
