### ISSUE TITLE
Image::resolving 里面设置removable(false)无效

### ISSUE THREAD

**Issue by doooocli** [jqhph/dcat-admin#1744]
- Laravel Version: 8
- PHP Version: 74
- Dcat Admin Version: 2.*

### Description:
bootstrap.php 文件
```
Image::resolving(function (Image $image) {
    $image->removable(false);
});
```
无效

原因是
在调用`$this->callResolving()`之后才调用`$this->setUpDefaultOptions()` 会将 `options`  存在的key覆盖掉

望修复

**Comment by laradocs** [comment]
Hi, @ShyRogue 
在不确定有重复类名的情况下，记得请补全 use 引用，
这样我们都能节省一些不必要的时间。

**Comment by laradocs** [comment]
Fixed.
