### ISSUE TITLE
在larave9中lang文件夹存放在根目录下

### ISSUE THREAD

**Issue by Longfei-Yan** [jqhph/dcat-admin#1745]
- Laravel Version: 9.5.1
- PHP Version: 8.1.3
- Dcat Admin Version: 2.2.0

### Description:

在laravel9中，dcat发布lang文件夹依然到了resource中

### Steps To Reproduce:
php artisan admin:publish
<img width="760" alt="截屏2022-05-14 23 04 17" src="https://user-images.githubusercontent.com/34568927/168434986-0d957d71-c8b8-4aa8-9afc-0222571886c2.png">

**Comment by laradocs** [comment]
Hi, @Longfei-Yan 
dcat-admin 还没发布新版本，2.0.x-dev 版本已经修复了这个 bug
