### ISSUE TITLE
文件上传，没限制格式，上传docx时，前端直接提示”对不起，不允许上传此类型文件“

### ISSUE THREAD

**Issue by singi2016cn** [jqhph/dcat-admin#1749]
- Laravel Version: 8.83.11
- PHP Version: 7.4.3 
- Dcat Admin Version: 2.2.0-beta

### Description:
文件上传，没限制格式，上传docx时，前端直接提示”对不起，不允许上传此类型文件“

### Steps To Reproduce:

```
$form->file('file');
```

> 新建的空docx文件，名称是"a.docx"

![image](https://user-images.githubusercontent.com/16513603/168719922-5daf0c55-2d6b-4599-ad0d-372c89d6eeaf.png)
![image](https://user-images.githubusercontent.com/16513603/168719693-272f3787-2249-4b7d-a8b3-c1cc8c856800.png)

**Comment by laradocs** [comment]
Hi, @singi2016cn
把 dcat-admin 版本换成 `2.0.x-dev` 就好了

**Comment by singi2016cn** [comment]
感谢回复，但是，能否在 `v2.2.0-beta` 的版本中修复呢。需要回退到 `2.0.x-dev`，总感觉不太好。

**Comment by laradocs** [comment]
有很多版本问题在 `2.0.x-dev` 已经修复了，`2.0.x-dev` 是最新版，也是默认版本。

**Comment by singi2016cn** [comment]
谢谢，解决了。

**Comment by singi2016cn** [comment]
同样的问题又出现了！！！

**Comment by singi2016cn** [comment]
原因找到了：因为这个配置是写入到页面JS里的做判断的，然后laravel默认有缓存页面，如果改了代码，还要删除对应页面缓存，最新配置才能生效。

```shell
php artisan view:clear
```
