### ISSUE TITLE
行操作采用下拉菜单方式时，最后一条记录的操作项无法显示全面

### ISSUE THREAD

**Issue by chinkiver** [jqhph/dcat-admin#175]
- Laravel Version: 7.14.1
- PHP Version: 7.3.12
- Dcat Admin Version: 1.4.7

### Description:
行操作采用下拉菜单方式时，最后一条记录的操作项无法显示全面
<img width="1440" alt="截屏2020-06-03 下午4 03 25" src="https://user-images.githubusercontent.com/13643790/83611913-3e87b980-a5b4-11ea-968f-aa5a23d1ee91.png">

**Comment by jqhph** [comment]
这个问题已经修复了，这两天会有个新版本，到时候更新就好了。

**Comment by chinkiver** [comment]
😊

**Comment by jqhph** [comment]
> 😊

新版本已发布，请升级到1.4.8版本即可
