### ISSUE TITLE
[BUG] 行内编辑时，输入 script 内容，会立刻在当前页面执行脚本。

### ISSUE THREAD

**Issue by lizengwei-poper** [jqhph/dcat-admin#1752]
- Laravel Version:  ^8.12
- PHP Version: 7.3
- Dcat Admin Version: 2.1.7-beta

### Description:
当行内编辑时，输入内容含有 scirpt 时，会在当前页面直接执行该脚本
![image](https://user-images.githubusercontent.com/93499617/168973270-a44ee4e7-0750-427e-83d4-1eb25241d51f.png)
![image](https://user-images.githubusercontent.com/93499617/168973345-1e03fa19-e859-4c4c-ae64-23739671cea8.png)

相关代码位于：   vendor/dcat/laravel-admin/resources/views/grid/displayer/editinline/template.blade.php:165

浏览了 laravel-admin 的相关行为没有发现这个现象，因为它对特殊字符进行了转译

```
function html_encode(str)  
{  
  var s = "";  
  if (str.length == 0) return "";  
  s = str.replace(/&/g, "&gt;");  
  s = s.replace(/</g, "&lt;");  
  s = s.replace(/>/g, "&gt;");  
  s = s.replace(/ /g, "&nbsp;");  
  s = s.replace(/\'/g, "&#39;");  
  s = s.replace(/\"/g, "&quot;");  
  s = s.replace(/\n/g, "<br>");  
  return s;  
}  
```

### Steps To Reproduce:

在 grid 中，编辑一个 editable column, 输入 `text<script>alert('Error');</script>`

**Comment by laradocs** [comment]
Hi, @lizengwei-poper 
Bug 已修复，把版本切换到 2.0.x-dev 就可以使用了。
