### ISSUE TITLE
数据表格行内编辑，关联表字段使用下拉选框会出错！

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#176]
- Laravel Version: 6.2
- PHP Version: 7.3
- Dcat Admin Version: 1.4

# Description:
数据表格使用行内编辑功能，当展示的是关联模型的字段时，使用`editable()`是可以正常显示的，但是无法更新数据。使用 `select()` 页面展示都有问题了。 

数据表格的部分代码如下：
```php
    protected function grid()
    {
        $grid = new Grid(Student::with(['clazz', 'lecturer', 'invoice']));
        ......
        $grid->column('xzgrade', __('Xzgrade'));
        $grid->column('student_name', __('Student name'));
        $grid->column('student_phone', __('Student phone'));
        $grid->column('identity_card', __('Identity card'))->hide();
        $grid->column('invoice.money', __('Amount collected'))->editable();  // 收款金额
        // $grid->column('invoice.billing_type', __('Billing type'))->editable(true);
        $grid->column('invoice.billing_type', __('Billing type'))->select(['普票' => '普票', '专票' => '专票','收据'=>'收据','无'=>'无']);  // 发票类型  
        return $grid
   }
```

这个是没有加`select()`方法的表格，是正常显示的，但是没有办法更新数据。
![不加select](https://i.imgur.com/aLMMfGR.png)

这个是加了`select()`方法的表格，样式直接错乱了，并且Chrome还有报错信息。

![加了select](https://i.imgur.com/A40Qycl.png)

Chrome控制台报错：
```js
Uncaught SyntaxError: Unexpected token '.'
```
报错信息详情截图如下
![报错信息](https://i.imgur.com/BXbKrra.png)

**Comment by jqhph** [comment]
很好办，你在`Form`表单的`saving`事件中转化一下就好了，把这个值转化成数组格式，具体你可以参考以下表单提交一对一的字段的格式

**Comment by metanoia1989** [comment]
> 很好办，你在`Form`表单的`saving`事件中转化一下就好了，把这个值转化成数组格式，具体你可以参考以下表单提交一对一的字段的格式

上面我发的有两个问题：
1. 数据表格显示关联表字段，使用行内编辑的`select()`下拉选项，渲染会出错。
2. 直接使用`editable()` ，渲染正常，但是无法保存数据。

问题1要怎么处理呢？
问题2按你说的方式我研究一下。

**Comment by jqhph** [comment]
这两天会有个新版本到时候我优化下这个问题

**Comment by metanoia1989** [comment]
> 这两天会有个新版本到时候我优化下这个问题

非常感谢，辛苦你了。

我是准备从Laravel-Admin迁移到Dcat-Admin，这个行内编辑关联表字段在Laravel-Admin是没有问题的，可以参考一下。

**Comment by jqhph** [comment]
不能吧，我刚看了laravel-admin现在的实现跟我这个是一样的

**Comment by metanoia1989** [comment]
> 不能吧，我刚看了laravel-admin现在的实现跟我这个是一样的

Laravel-Admin 里，我的代码形式如下：
```php
        $grid->column('invoice.billing_type', __('Billing type'))->editable('select',['普票' => '普票', '专票' => '专票','收据'=>'收据','无'=>'无']);
        $grid->column('invoice.invoicing_situation',__('Invoicing situation'))->editable('select',['未开票' => '未开票','已开票' => '已开票','暂不开票' => '暂不开票','暂不寄出' => '暂不寄出', '已寄出' => '已寄出']);
```
是可以实现关联表字段下拉选框编辑更新的。

**Comment by jqhph** [comment]
嗯select的实现是一样的，editable因为升级到了bootstrap4所以不兼容旧的方式

**Comment by jqhph** [comment]
新版本已发布，请更新到1.4.8版本即可
