### ISSUE TITLE
select与listbox联动Bug

### ISSUE THREAD

**Issue by wk1025** [jqhph/dcat-admin#1760]
- Laravel Version: 8.12
- PHP Version: 7.3.9
- Dcat Admin Version:  v2.2.0-beta

### Description:
请问select可以联动listbox吗？select load加载之后一直不显示，需要点击几次组件才能显示，选中listbox左侧任意一个选项，左侧选项会全部移到右侧select 中。

### Steps To Reproduce:
$form->select('resource_id', '资源')
            ->options(Resource\Resource::all()->pluck('name', 'id'))
            ->load('field_ids', admin_url('api/get_fields_by_resource_id'));
            
$form->listbox('field_ids', '授权字段');

public function getFieldsByResourceId(Request $request) {
        $resource_id = $request->get('q', '');
        return Resource\Field::where('resource_id', $resource_id)->get(['id', \DB::raw('name as text')]);
}

**Comment by laradocs** [comment]
检查一下是不是写法上面有问题，我这边是正常的

> 推荐使用 `2.0.x-dev` 版本

**Comment by shacky** [comment]
Use this workaround in JS to refresh the bootstrap dual listbox after ajax load:

```js
$(document).on('change', "select[multiple]._normal_", function () {
    if($(this).prev().is('.bootstrap-duallistbox-container'))
        $(this).bootstrapDualListbox('refresh');
});
```
