### ISSUE TITLE
列表右上角 翻译不完全

### ISSUE THREAD

**Issue by Polarisjiumengyichang** [jqhph/dcat-admin#1764]
- Laravel Version: 6.20.26
- PHP Version: 7.3.*
- Dcat Admin Version: 2.*

### Description:
列表右上角 翻译不完全
如下：
主页/Auth/Roles
![微信图片_20220524175039](https://user-images.githubusercontent.com/106150667/170003792-2b5413e2-1d9f-40f8-b585-abe85c9665ad.png)

**Comment by laradocs** [comment]
在 `lang/admin.php` 文件里面添加对应的翻译就好了。
