### ISSUE TITLE
HasMany 验证规则，把删除的也加上了

### ISSUE THREAD

**Issue by xianlinzhang** [jqhph/dcat-admin#1765]
- Laravel Version: 8.83.3
- PHP Version: 74
- Dcat Admin Version: 2.2.0-beta

### Description:
![image](https://user-images.githubusercontent.com/30235909/170282399-27b38ed0-69c8-4adc-b6db-efb2ae974132.png)

HasMany 验证规则，把删除的也加了验证
@ihipop 
### Steps To Reproduce:
新建未提交->删除->提交

**Comment by laradocs** [comment]
把版本切换到 `2.0.x-dev` 试试，在 `composer.json` 文件中修改即可
记得执行 `composer update` 命令

**Comment by xianlinzhang** [comment]
> 把版本切换到 `2.0.x-dev` 试试，在 `composer.json` 文件中修改即可 记得执行 `composer update` 命令

试过了 `2.0.x-dev` 也存在同样的问题

顺便问下，
- 现在的版本更新是怎么个更新法？
- 版本2相对稳定的是哪个版本？

**Comment by laradocs** [comment]
稳定版是 1.7.9
版本 2.0 都不是稳定版
2.0.x-dev 是 2.0 分支
也就是说 2.0.x-dev 版本有 bug 修复合并之后你只需要执行 `composer update dcat/laravel-admin` 就可以同步了。

**Comment by laradocs** [comment]
我这边测试并没有发现问题，你可能要多提供一些你那边的情况

**Comment by xianlinzhang** [comment]
> 我这边测试并没有发现问题，你可能要多提供一些你那边的情况

感谢回答！这边试了还是存在问题，复现如下步骤

Steps To Reproduce:
1. 新建
![企业微信截图_16540053397015](https://user-images.githubusercontent.com/30235909/171190955-888ee2de-2b74-4e0e-8908-015559c34527.png)

2.删除
![企业微信截图_16540054617088](https://user-images.githubusercontent.com/30235909/171191870-55d39490-7d4f-48cc-8b19-f45751727e8c.png)

3.提交
![企业微信截图_16540055703331](https://user-images.githubusercontent.com/30235909/171191906-df270c3d-00d7-4650-adc4-07a967aece8c.png)

**Comment by xianlinzhang** [comment]
> 2.0.x-dev
也就是说，目前2.0版本修复的bug都会合并到`2.0.x-dev`？

**Comment by laradocs** [comment]
好的，明天我测试一下

**Comment by laradocs** [comment]
> > 2.0.x-dev
> > 也就是说，目前2.0版本修复的bug都会合并到`2.0.x-dev`？

是的，每次修复的 bug 都会合并到 `2.0.x-dev` 版本

**Comment by laradocs** [comment]
试过了，我这边还是没有问题，要不你把代码贴出来看看吧

**Comment by xianlinzhang** [comment]
> 试过了，我这边还是没有问题，要不你把代码贴出来看看吧

```bash
protected function form()
{
    return Form::make(Branch::with('tran'), function (Form $form) {
        $form->column(12, function (Form $form) {
            $form->hasMany('tran', admin_trans_label('contact_info'), function (Form\NestedForm $form) {
                $form->column(6, function(Form\NestedForm $form) {
                    $form->hidden('tran_id');
                    $form->text('tran_name','姓名')->required();
                });
            })->width(10, 1);
        });
    });
}
```
Branch 和tran是一对多的关系

**Comment by laradocs** [comment]
你应该早点贴代码的，我没想到你会这么去写....
明天晚上帮你处理这个问题。
