### ISSUE TITLE
Grid中配置的排序字段，与实际排序字段不符

### ISSUE THREAD

**Issue by pianzhou2021** [jqhph/dcat-admin#1768]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
Grid中配置的排序字段，与实际排序字段不符，逻辑上比较混乱，理论上直接字段上面配置xxxx字段后，排序字段就需要以xxxx字段为准
$grid->column('xxxx')->orderable();

    protected $sortable = [
        // 设置排序字段名称
        'order_column_name' => 'order',
        // 是否在创建时自动排序，此参数建议设置为true
        'sort_when_creating' => true,
    ];

**Comment by laradocs** [comment]
大佬，你是不是忽略了以下代码

```php
$grid->model()->orderBy('order');
```

[可排序 (orderable)](https://learnku.com/docs/dcat-admin/2.x/display-and-expansion-of-columns/8091#49dadd)
