### ISSUE TITLE
hasmany中获取 model 数据

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#177]
关于在hasmany中调用 model 的问题，
已经检查过关联模型了
![螢幕快照 2020-06-03 下午5 38 31](https://user-images.githubusercontent.com/16574141/83621594-70534d00-a5c1-11ea-9783-f2f7cdd83fa6.png)
![螢幕快照 2020-06-03 下午5 40 43](https://user-images.githubusercontent.com/16574141/83621601-734e3d80-a5c1-11ea-9d04-1147693d7504.png)

折腾了好久实在试不出来，想请教一下应该如何获取数据

![螢幕快照 2020-06-03 下午5 30 55](https://user-images.githubusercontent.com/16574141/83620523-04bcb000-a5c0-11ea-9931-f717e37b9627.png)
![螢幕快照 2020-06-03 下午5 22 07](https://user-images.githubusercontent.com/16574141/83620533-071f0a00-a5c0-11ea-90f6-60dd4561a048.png)

看了文档在 form中 获取数据是使用 $form->model()-> xxxx 表单名

我想要获取关联表 items 的当前 product_id (如上图)
$form->model()->product_id
$form->model()->items->product_id
这两种方式都不行

能否请您指点下，谢谢

**Comment by jqhph** [comment]
同学你这个基础有点不太行呀，你关联数据都拿到了那拿里面的字段还不好处理吗？
```php
$productIds = collect($form->model()->items)->pluck('product_id');
```

**Comment by kevin700523** [comment]
老大 感谢您的回答

用 pluck和 collect 拿资料这我知道，但这会拿到全部的 product IDs

我只需要当前一笔 items 的 product_id
就像 $form->getKey() 一样只拿到当前 key

例如 拿到当前的product_id, 
做 一些查询
$total = product::find( product_id  )->pluck(amount);
然后放在表单中

 $table->text('total_amount', '数量')->disable()->default($total);

再请老大指点下 谢谢

**Comment by jqhph** [comment]
所以说要描述清楚问题和你想实现的效果，这样双方都节省时间。你这个解决的思路就不对，参考下下面的方法
```php
$table->text('total_amount', '数量')->disable()->customFormat(function ($v) {
    dd($this->toArray());
    return $v;
});
```

**Comment by kevin700523** [comment]
感谢老大
