### ISSUE TITLE
Grid关联表筛选排序问题

### ISSUE THREAD

**Issue by SimaRyan** [jqhph/dcat-admin#1772]
- Laravel Version: 8.5
- PHP Version: 8.0
- Dcat Admin Version: 2.2

问题特征：
grid在有关联表的情况下进行筛选后因为关联表有同名字段无法进行sorable排序，找遍官方文档也无相关的处理方案，请问是否有解决方案？
表A
id, user, name, password, status
表B
id, user_id, balance, award, status

当grid搜索了表a status=1的结果时，需要排序表B的balance，数据库提示同名字段错误，需要定义status是哪个表的。

**Comment by laradocs** [comment]
定义一个别名

**Comment by SimaRyan** [comment]
> 定义一个别名

我尝试过在关联表中定义别名，但他在查询时好像不起作用。
