### ISSUE TITLE
expand 点击过快会出现点不开的情况

### ISSUE THREAD

**Issue by pianzhou2021** [jqhph/dcat-admin#1774]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
<img width="140" alt="ECA735AAF5C72CE0157EE0F74C3621FB" src="https://user-images.githubusercontent.com/97172071/170916768-e70bbe08-7b59-454f-9a26-5c59a35f2ce2.png">
expand 点击过快会出现点不开的情况

**Comment by andyzu** [comment]
我也遇到同样的问题
