### ISSUE TITLE
一对多关联新增报错 array_key_exists(): Argument #2 ($array) must be of type array, string give

### ISSUE THREAD

**Issue by daichongweb** [jqhph/dcat-admin#1777]
https://learnku.com/laravel/t/68397

**Comment by laradocs** [comment]
贴个 Demo 啊

**Comment by daichongweb** [comment]
protected function form(): Form
    {
        return Form::make(new FareTemplate(), function (Form $form) {
            $form->display('id');
            $form->text('name');
            $form->radio('type', '邮费类型')->options(FareTemplate::TYPE_MAP)->default(0)->when(1, function (Form $form) {
                $form->tree('conditions', '不包邮区域')
                    ->nodes((new RegionService())->provinces())
                    ->setTitleColumn('title');
                $form->number('freight', '运费')->required();
            })->when(0, function (Form $form) {
                $form->number('freight', '运费')->required();
            });
            $form->text('storehouse', '发货仓')->default('')->placeholder('杭州仓库');
            $form->text('delivery_time', '发货时间')->default('')->placeholder('24小时内发货');
        });
    }
// templateModel
public function conditions(): HasMany
{
        return $this->hasMany(FareTemplateCondition::class, 'template_id');
}

// templateConditionModel
public function template(): BelongsTo
{
        return $this->belongsTo(FareTemplate::class, 'template_id');
}

**Comment by daichongweb** [comment]
`protected function form(): Form
    {
        return Form::make(new FareTemplate(), function (Form $form) {
            $form->display('id');
            $form->text('name');
            $form->radio('type', '邮费类型')->options(FareTemplate::TYPE_MAP)->default(0)->when(1, function (Form $form) {
                $form->tree('conditions', '不包邮区域')
                    ->nodes((new RegionService())->provinces())
                    ->setTitleColumn('title');
                $form->number('freight', '运费')->required();
            })->when(0, function (Form $form) {
                $form->number('freight', '运费')->required();
            });
            $form->text('storehouse', '发货仓')->default('')->placeholder('杭州仓库');
            $form->text('delivery_time', '发货时间')->default('')->placeholder('24小时内发货');
        });
    }
// templateModel
public function conditions(): HasMany
{
        return $this->hasMany(FareTemplateCondition::class, 'template_id');
}

// templateConditionModel
public function template(): BelongsTo
{
        return $this->belongsTo(FareTemplate::class, 'template_id');
}`

**Comment by daichongweb** [comment]
```
protected function form(): Form
    {
        return Form::make(new FareTemplate(), function (Form $form) {
            $form->display('id');
            $form->text('name');
            $form->radio('type', '邮费类型')->options(FareTemplate::TYPE_MAP)->default(0)->when(1, function (Form $form) {
                $form->tree('conditions', '不包邮区域')
                    ->nodes((new RegionService())->provinces())
                    ->setTitleColumn('title');
                $form->number('freight', '运费')->required();
            })->when(0, function (Form $form) {
                $form->number('freight', '运费')->required();
            });
            $form->text('storehouse', '发货仓')->default('')->placeholder('杭州仓库');
            $form->text('delivery_time', '发货时间')->default('')->placeholder('24小时内发货');
        });
    }
// templateModel
public function conditions(): HasMany
{
        return $this->hasMany(FareTemplateCondition::class, 'template_id');
}

// templateConditionModel
public function template(): BelongsTo
{
        return $this->belongsTo(FareTemplate::class, 'template_id');
}
```

**Comment by daichongweb** [comment]
不使用模型关联，自定义了一个fares，并且模型fillable没有设置fares字段"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fares' in 'field list' (SQL: insert into `goods_fare_template` (`name`, `type`, `fares`, `freight`, `storehouse`, `delivery_time`, `updated_at`, `created_at`) values (\u5317\u4eac\u4e0d\u5305\u90ae, 1, [\"120000\",\"130000\",\"140000\",\"150000\",\"210000\",\"220000\",\"230000\",\"310000\",\"320000\",\"330000\",\"340000\",\"350000\",\"360000\",\"370000\",\"410000\",\"420000\",\"430000\",\"440000\",\"450000\",\"460000\",\"500000\",\"510000\",\"520000\",\"530000\",\"540000\",\"610000\",\"620000\",\"630000\",\"640000\",\"650000\",\"810000\",\"820000\",\"830000\"], 0, \u676d\u5dde\u4ed3\u5e93, 24\u5c0f\u65f6\u53d1\u8d27, 2022-06-01 10:42:31, 2022-06-01 10:42:31))",
    "exception": "Illuminate\\Database\\QueryException",

**Comment by daichongweb** [comment]
想换种方式实现这个功能也不行
