### ISSUE TITLE
对于代码中html存在的优化建议

### ISSUE THREAD

**Issue by aoeng** [jqhph/dcat-admin#178]
最好将html代码放到一个文件里面,小的html片段可以用方法的形式返回插入,比直接写在页面上好看

**Comment by jqhph** [comment]
感谢建议，一般只有很少量的HTML才没有放在模板文件里，因为没必要，麻烦还影响性能。

**Comment by aoeng** [comment]
嗯,帅是一辈子的事,优雅也是如此
