### ISSUE TITLE
select框从编辑页退回列表页未清除

### ISSUE THREAD

**Issue by Creyar** [jqhph/dcat-admin#1784]
- Laravel Version: 8.6.5
- PHP Version: 8.0.11
- Dcat Admin Version: 2.1.7-beta

### Description:

进入编辑页 点击select框 再点击网页后退按钮到列表页 select框未被消除
### Steps To Reproduce:
![1](https://user-images.githubusercontent.com/40223330/172291397-79dd21ad-5fdd-4c8a-9cd7-0c5800436e96.png)

**Comment by laradocs** [comment]
pjax 渲染出 bug 了。
