### ISSUE TITLE
 form的select组件的load 联动bug

### ISSUE THREAD

**Issue by trkjoy** [jqhph/dcat-admin#1785]
- Laravel Version:6.20.44
- PHP Version:  7.4.21
- Dcat Admin Version: 2.2.0-beta

### Description:
                $form->select('cmd','指令')
                    ->options($this->options)
                    ->load('description',admin_url('/selectd'))
                    ->default(1);

### Steps To Reproduce:
 form的select组件的load 函数,设定的路由方法没生效，admin_url('/selectd') 路由设置的是调用控制器中的 selectd 方法
请求却调用到了控制器中的 detail 方法。detail 方法都不存在，莫名就调用到这个方法上去了
（控制器继承了AdminController）

**Comment by laradocs** [comment]
AdminController 里面有 detail 方法，你需要在路由把 detail 的路由覆盖掉
