### ISSUE TITLE
腾讯云图片上传，链接有时效

### ISSUE THREAD

**Issue by slarksnake** [jqhph/dcat-admin#1786]
- Laravel Version: 8.4
- PHP Version: 8.0.12
- Dcat Admin Version: v2.2.0-beta

<img width="693" alt="image" src="https://user-images.githubusercontent.com/11405082/172550814-22ef50ee-a57f-462a-924e-ca46e076f844.png">

未到失效时间富文本框中的图片还是失效了image中没有失效

**Comment by laradocs** [comment]
不明白你在说什么，还请你再描述清楚些。

检查一下返回的路径是否正确

**Comment by slarksnake** [comment]
使用freyo/flysystem-qcloud-cos-v5插件上传腾讯云cos
$form->editor()editor富文本框中上传的图片时效性很短 半小时后就消失了
$form->image('imahe')->disk('cosv5')这种使用方式就不会有时效性
