### ISSUE TITLE
Form中存在多个Radio时when功能失效

### ISSUE THREAD

**Issue by fangmuke** [jqhph/dcat-admin#1788]
- Laravel Version: 9.17
- PHP Version: 8.0
- Dcat Admin Version: 2.0.x-dev

### Description:
#1776 问题是由这个PR引起的

https://user-images.githubusercontent.com/26641510/172759152-605a1f9d-98bb-484d-9223-f40fd8c27a3e.mov

**Comment by laradocs** [comment]
把版本切换到 `2.0.x-dev` 即可
记得执行 composer update dcat/laravel-admin

**Comment by laradocs** [comment]
直接改 composer.json 文件

**Comment by fangmuke** [comment]
> 把版本切换到 `2.0.x-dev` 即可 记得执行 composer update dcat/laravel-admin

写错了，现在就是`2.0.x-dev`
我现在composer.json指定的`2.0.x-dev#5156f8836739f6e47ad68581f5a3629f63d517dd`是正常的

**Comment by laradocs** [comment]
没问题就好，最后 1776 最后一次 PR 是我提交的:joy:

**Comment by fangmuke** [comment]
> 没问题就好，最后 1776 最后一次 PR 是我提交的😂

我知道，就是这个PR有问题😂

**Comment by laradocs** [comment]
> 我知道，就是这个PR有问题😂

你用 `2.0.x-dev` 版本发现有问题？

**Comment by fangmuke** [comment]
![image](https://user-images.githubusercontent.com/26641510/172761217-7eae190c-5686-4fad-a301-4dbbc32835d3.png)

**Comment by fangmuke** [comment]
> > 我知道，就是这个PR有问题😂
> 
> 你用 `2.0.x-dev` 版本发现有问题？

是的

**Comment by fangmuke** [comment]
视频中就是`2.0.x-dev`

**Comment by laradocs** [comment]
等我吃饱饭改改:joy:

**Comment by laradocs** [comment]
遛了遛了，我解决不了:joy:
解决你这个问题他那个问题又出 bug 了:cry:
附：#1775

**Comment by fangmuke** [comment]
> 遛了遛了，我解决不了😂 解决你这个问题他那个问题又出 bug 了😢 附：#1775

不行就给array单独做一个

**Comment by rainhon** [comment]
刚想提个新问题没想到这个问题还是不行哇，重新检查了一下，之前用fields-group去查找选中项就会出现这个问题了，试了下改用form-field可以解决
```
    protected function getFormFrontValue()
    {
        switch (get_class($this)) {
            case Select::class:
            case MultipleSelect::class:
                return 'var checked = $(this).val();';
            case Radio::class:
                return <<<JS
var checked = \$this.closest('.form-field').find(':checked').val();
JS;
            case Checkbox::class:
                return <<<JS
var checked = \$this.closest('.form-field').find(':checked').map(function(){
  return $(this).val();
}).get();
JS;
            default:
                throw new RuntimeException('Invalid form field type');
        }
    }
```
