### ISSUE TITLE
json表单 table图片无法上传

### ISSUE THREAD

**Issue by fangmuke** [jqhph/dcat-admin#1792]
- Laravel Version: 9.17
- PHP Version: 8.0
- Dcat Admin Version: 2.0.x-dev#5156f8836739f6e47ad68581f5a3629f63d517dd

### Description:
目前已回滚到`2.0.x-dev#8634ec282259ac751892ef6f5e7f475221cfa1bd` 两个commit对比[compare](https://github.com/jqhph/dcat-admin/compare/8634ec282259ac751892ef6f5e7f475221cfa1bd...5156f8836739f6e47ad68581f5a3629f63d517dd)

问题是由这个issue (#1742) 引起的两个pr (#1766 #1770 ) 造成的

**Comment by laradocs** [comment]
embeds 那里确实是有很大的问题存在。

![2A0707928F4B74DD409E1C869D123321](https://user-images.githubusercontent.com/49741756/173177687-7b5fd45d-8aaf-4283-9ba6-1e8287a2438e.gif)

**Comment by fangmuke** [comment]
> embeds 那里确实是有很大的问题存在。
> 
> ![2A0707928F4B74DD409E1C869D123321](https://user-images.githubusercontent.com/49741756/173177687-7b5fd45d-8aaf-4283-9ba6-1e8287a2438e.gif) [ ](https://user-images.githubusercontent.com/49741756/173177687-7b5fd45d-8aaf-4283-9ba6-1e8287a2438e.gif) ![2A0707928F4B74DD409E1C869D123321](https://user-images.githubusercontent.com/49741756/173177687-7b5fd45d-8aaf-4283-9ba6-1e8287a2438e.gif) [ ](https://user-images.githubusercontent.com/49741756/173177687-7b5fd45d-8aaf-4283-9ba6-1e8287a2438e.gif)

改embeds影响到了table的。。

**Comment by laradocs** [comment]
丢个 Demo 看看

**Comment by fangmuke** [comment]
```php
$form->table('ads', '广告图', function (NestedForm $table) {
    $table->image('img', '图片')->override()->autoUpload();
});
```

分别测试`"dcat/laravel-admin": "2.0.x-dev"` 和 `"dcat/laravel-admin": "2.0.x-dev#8634ec282259ac751892ef6f5e7f475221cfa1bd"`

**Comment by laradocs** [comment]
你看看这个 PR #1780 能不能帮到你

**Comment by lyhuanuo** [comment]
在 Dcat\Admin\Http\Controllers\HandleFormController 中的方法 getField 增加判断
 if(is_string($relation) && strpos($relation,',') !== false){
            $relation = explode(',',$relation);
 }
原因在于 提交参数 _relation不是原来的数组
![1655436175939](https://user-images.githubusercontent.com/44084515/174218858-7486964c-afcc-4e8c-a401-d031b1753881.jpg)

**Comment by laradocs** [comment]
Fixed #1802
