### ISSUE TITLE
新增权限无法选择HTTP路径问题

### ISSUE THREAD

**Issue by IamComing3** [jqhph/dcat-admin#1793]
- Laravel Version: 9.11
- PHP Version: 8.0
- Dcat Admin Version: 2.2

### Description:
现有如下路由
![image](https://user-images.githubusercontent.com/16791768/173180213-8d54fd0b-c16b-495d-9bb1-8dc6aba564bf.png)
新增权限时不能提供完整的可选项
![image](https://user-images.githubusercontent.com/16791768/173180255-79466b5b-988f-4676-bc26-23f6e15b6cc7.png)

**Comment by Ynwaspectre** [comment]
去路由里加下

**Comment by IamComing3** [comment]
> 去路由里加下

路由里面有，上面截图了
