### ISSUE TITLE
Dcat Admin在其他非admin环境的场景下，也会初始化dcat相关配置

### ISSUE THREAD

**Issue by pianzhou2021** [jqhph/dcat-admin#1795]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
Dcat Admin在其他非admin环境的场景下，也会初始化dcat相关配置，不仅浪费资源，并且会导致某些未知错误

比如：在调用api的情况下，dcat环境同样会加载
建议解决方案：直接在AdminServiceProvider中，只在admin环境和console环境下加载

**Comment by ghost** [comment]
+1
