### ISSUE TITLE
请问数据导出能像laravel-admin那样使用map修改数据，使用registerEvents注册事件吗

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#180]
- Laravel Version: 6.2
- PHP Version: 7.3
- Dcat Admin Version: 1.4

# Description:
🧡首先感谢开发者的精勤更新维护。🧡 
🤲赞助了50块，略表心意🤲

我在从laravel-admin迁移到dcat-admin中，发现两者的数据导出有些不兼容。
在laravel-admin中，可以通过实现`WithMapping`接口然后重写`map()`方法来修改数据。
参见文档 <https://laravel-admin.org/docs/zh/model-grid-export#%E6%95%B0%E6%8D%AE%E4%BF%AE%E6%94%B9>
dcat-admin中关于这部分的文档非常简略，我不太懂怎么处理。

并且在laravel-admin中，可以实现` WithEvents`接口然后重写`registerEvents`事件，在这里处理单元格格式。
以下是laravel-admin处理数据导出的相关代码：
```php
<?php
namespace App\Exports;

use Encore\Admin\Grid\Exporters\ExcelExporter;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\DefaultValueBinder;
use Maatwebsite\Excel\Events\AfterSheet;
use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;

class GrabNumberExport extends ExcelExporter implements  WithMapping, WithEvents, WithHeadings, WithCustomValueBinder
{
    protected $fileName = '实操抢号记录.xlsx';

    public function __construct()
    {
        parent::__construct();
        $this->fileName = '实操抢号记录'.date('Y-m-d').'.xlsx';
    }

    /**
     * 自定义头部
     *
     * @return array
     */
    public function headings() : array
    {
        return [
            '序号',
            '考试月份',
            '抢号日期',
            '考试日期',
            '等级',
            '客户名称',
            '学员名称',
            '身份证号码',
            '电话',
            '考试分数',
            '是否通过',
            '是否缺考',
        ];
    }

    /**
     * 将数值转换为字符串
     *
     * @param \PhpOffice\PhpSpreadsheet\Cell\Cell $cell
     * @param mixed $value
     * @return boolean
     */
    public function bindValue(\PhpOffice\PhpSpreadsheet\Cell\Cell $cell, $value)
    {
        // 重写数据类型的判断规则
        if (is_numeric($value) && strlen($value) > 5 && preg_match('/^[\+\-]?(\d+\\.?\d*|\d*\\.?\d+)([Ee][\-\+]?[0-2]?\d{1,3})?$/', $value)) {
            $cell->setValueExplicit($value, DataType::TYPE_STRING);
            return true;
        }
        // 继承DefaultValueBinder
        $default = new DefaultValueBinder();
        return $default->bindValue($cell, $value);
    }

    /**
     * 对字段的数据进行预处理
     *
     * @param array $item 实操抢号信息
     * @return array
     */
    public function map($grab) : array
    {
        # 提取每个抢号记录的关联学员数据
        $grabNumber= $grab->with(['grabstudents', 'grabstudents.student', 'grabstudents.student.examtest'])
            ->where('id', $grab->id)
            ->get()->first();
        $students = $grabNumber->grabstudents->map(function ($item) use ($grabNumber) {
                .... 处理关联数据
        });

        # 统计数据
        $pass_num = $students->filter(function ($item) {
            return data_get($item, 'score') > 60 ? true : false;
        })->count(); // 通过人数
        $absend_num = $students->filter(function ($item) {
            return data_get($item, 'score') === 0 ? true : false;
        })->count(); // 缺考人数
        $all_num = $students->count(); // 总人数
        $attend_num = $all_num - $absend_num; // 参加考试人数
        $throughput_rate = number_format($pass_num / $all_num* 100, 0, '.', '').'%';
        $throughput_rate_high = $attend_num == 0 ? 0 : number_format($pass_num / $attend_num * 100, 0, '.', '').'%';

        $row1 = [
            'pass_num' => "通过人数：". $pass_num,
            'absend_num' => "缺考人数：". $absend_num,
        ];
        $row2 = [
            'throughput_rate' => "含缺考通过率：". $throughput_rate,
            'last_fill' => '',
        ];
        $row3 = [
            'throughput_rate_high' =>  "不含缺考通过率：".$throughput_rate_high,
            'last_fill' => '',
        ];
        // 一行有12个字段，不够需要进行补齐
        $statistic_data[] = array_values(array_merge(array_fill(0, 10, ''), $row1));
        $statistic_data[] = array_values(array_merge(array_fill(0, 10, ''), $row2));
        $statistic_data[] = array_values(array_merge(array_fill(0, 10, ''), $row3));
        // 抹平$students 中元素的键，然后再合并统计数据
        return $students->map(function ($item) {
            return $item->values();
        })->merge($statistic_data)->toArray();
    }

    public function identity_card($id){
        return (string)$id.' ';
    }

    public function registerEvents(): array
    {
        return [
            AfterSheet::class    => function(AfterSheet $event) {
                // 所有表头-设置字体为12
                $cellRange = 'A1:Z1';
                $event->sheet->getDelegate()->getStyle($cellRange)->getFont()->setSize(12);

                // 文字居中
                $lastrow = $event->sheet->getDelegate()->getHighestRow();
                $event->sheet->getDelegate()->getStyle('A1:L'.$lastrow)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

                // 设置统计数据的样式
                $lastcolumn = 12;
                for ($col = 11; $col <= $lastcolumn; $col++) {
                    for ($row = 1; $row <= $lastrow; $row++) {
                        $cell = $event->sheet->getDelegate()->getCellByColumnAndRow($col, $row);
                        $value = $cell->getValue();
                        $is_statistics = false;

                        if (strpos($value, "通过人数") !== false || strpos($value, "缺考人数") !== false) {
                            $is_statistics = true;
                            $cell->getStyle()->getFill()->setFillType(Fill::FILL_SOLID)
                                ->getStartColor()->setARGB('ffff00');
                        }
                        if (strpos($value, "含缺考通过率") !== false || strpos($value, "不含缺考通过率") !== false) {
                            $is_statistics = true;
                            $cell->getStyle()->getFill()->setFillType(Fill::FILL_SOLID)
                                ->getStartColor()->setARGB('92d050');
                        }
                        if ($is_statistics) {
                            $cell->getStyle()->getAlignment()->setHorizontal(Alignment::HORIZONTAL_LEFT);
                        }
                    }
                }

                // 将设置表格宽度,ShouldAutoSize
                $event->sheet->getDelegate()->getColumnDimension('A')->setWidth(10);
                $event->sheet->getDelegate()->getColumnDimension('B')->setWidth(10);
                ........
                $event->sheet->getDelegate()->getColumnDimension('K')->setWidth(25);
                $event->sheet->getDelegate()->getColumnDimension('L')->setWidth(20);
               // 设置 A1:D4 范围内文本自动换行
                $event->sheet->getDelegate()->getStyle('I1:M1000')
                    ->getAlignment()->setWrapText(true);
            },
        ];
    }
}
```

导出的excel文件显示如下：
![导出效果](https://i.imgur.com/fYrtOQ3.png)

我感觉laravel-admin对laravel-excel适配的非常好，实现其相关的 `Export concerns`都能做到，但是在dcat-admin我不太明白怎么处理。

能给我一些建议吗？非常感谢🙏

**Comment by jqhph** [comment]
看数据导出的文档，里面就有使用laravel-excel的例子，总体跟laravel-admin的用法没什么区别

**Comment by metanoia1989** [comment]
> 看数据导出的文档，里面就有使用laravel-excel的例子，总体跟laravel-admin的用法没什么区别

我将相关的命名空间修改为 dcat的。
```php
use Dcat\Admin\Grid\Exporters\ExcelExporter;

class GrabNumberExport extends ExcelExporter implements  WithMapping, WithEvents, WithHeadings, WithCustomValueBinder 
{
      ......
}
```

结果导出的数据是有问题的，感觉dcat-admin相关的变动很多。
![数据](https://i.imgur.com/KAPydcl.png)

我看dcat-admin文档中的示例是重写 export 方法，也跟着重写了，数据能够导出来，但是最后的事件都没有效果。
```php
class GrabNumberExport extends ExcelExporter implements  WithMapping, WithEvents, WithHeadings, WithCustomValueBinder
{
    use Exportable;

    protected $extension = 'xlsx';

    public function __construct()
    {
        parent::__construct();
    }

    public function getFilename()
    {
        return '实操抢号记录'.date('Y-m-d');
    }

    public function export()
    {
        $filename = $this->getFilename().'.'.$this->extension;
        $exporter = Excel::export();
        $data = collect($this->buildData())->map(function ($item) {
            $item = new Fluent($item);
            return $this->map($item);
        });
        $exporter->data($data->toArray()[0]);
        $exporter->headings($this->headings())->download($filename);
        exit;
    }
   ....
}
```

导出效果如下：
![](https://i.imgur.com/PF0FBy1.png)

**Comment by jqhph** [comment]
`buildData`拿到的就是数据库查出来的数据，在里面做转化就好了，我没怎么用过laravel-excel，你自己琢磨琢磨

**Comment by jqhph** [comment]
谢谢你的赞助

**Comment by jqhph** [comment]
如果你只是转换数据格式，完全不需要扩展导出功能，文档有更简单的方式实现

**Comment by metanoia1989** [comment]
> 如果你只是转换数据格式，完全不需要扩展导出功能，文档有更简单的方式实现
> 
> ```
> $grid->export()->rows(function (array $rows) {
>     // 转换要导出的数据格式
>     foreach ($rows as $index => &$row) {
>         $row['name'] = $row['first_name'].' '.$row['last_name'];
>     }
> 
>     return $rows;
> });
> ```

不仅仅是扩展字段，我要从一条记录里提取关联数据，生成多行。上面那个excel导出的数据就是从一条记录里提取处理的。

并且我还需要设置单元格格式，如样式、宽度相关的。

dcat-admin对laravel-excel的`Export concerns`好像并没有支持。
Laravel-Excel Export concerns： <https://docs.laravel-excel.com/3.1/exports/concerns.html>

**Comment by jqhph** [comment]
这个你自己琢磨下，buildData拿到的就是数据，然后根据laravel-excel的文档用法去处理一下

**Comment by metanoia1989** [comment]
弄了快一天了，终于解决了，我哭了。😭 
如果要使用Laravel-Excel导出数据，并且使用相关 `Export concerns`，在继承 AbstractExporter 之后需要重写 export 方法，并且不能使用FormQuery【Laravel-Admin的默认方式】获取数据，而要使用FromCollection，好像是因为model有变化，相关代码如下：
```php
namespace App\Exports;

use Illuminate\Support\Fluent;
use Dcat\Admin\Grid\Exporters\AbstractExporter;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class GrabNumberExport extends AbstractExporter implements WithMapping, WithEvents, WithHeadings, WithCustomValueBinder, FromCollection
{
    use Exportable;

    protected $fileName = '实操抢号记录.xlsx';

    public function __construct()
    {
        parent::__construct();
        $this->fileName = '实操抢号记录'.date('Y-m-d').'.xlsx';
    }

    public function collection()
    {
        return collect($this->buildData());  // 使用dcat-admin的buildData获取数据
    }

    /**
     * {@inheritdoc}
     */
    public function export()
    {
        // 导出空白很有可能的是上面的方法getQuery没有查询到数据，用laravel-admin的相关的方法不行，因为model好像被变更了。=_=
        // 使用 collection() 就可以了。
        $this->download($this->fileName)->prepare(request())->send();
        exit;
    }
}
```

**Comment by jqhph** [comment]
> 弄了快一天了，终于解决了，我哭了。😭
> 如果要使用Laravel-Excel导出数据，并且使用相关 `Export concerns`，在继承 AbstractExporter 之后需要重写 export 方法，并且不能使用FormQuery【Laravel-Admin的默认方式】获取数据，而要使用FromCollection，好像是因为model有变化，相关代码如下：
> 
> ```
> namespace App\Exports;
> 
> use Illuminate\Support\Fluent;
> use Dcat\Admin\Grid\Exporters\AbstractExporter;
> use Maatwebsite\Excel\Concerns\Exportable;
> use Maatwebsite\Excel\Concerns\FromCollection;
> use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
> use Maatwebsite\Excel\Concerns\WithEvents;
> use Maatwebsite\Excel\Concerns\WithHeadings;
> use Maatwebsite\Excel\Concerns\WithMapping;
> 
> class GrabNumberExport extends AbstractExporter implements WithMapping, WithEvents, WithHeadings, WithCustomValueBinder, FromCollection
> {
>     use Exportable;
> 
>     protected $fileName = '实操抢号记录.xlsx';
> 
>     public function __construct()
>     {
>         parent::__construct();
>         $this->fileName = '实操抢号记录'.date('Y-m-d').'.xlsx';
>     }
> 
>     public function collection()
>     {
>         return collect($this->buildData());  // 使用dcat-admin的buildData获取数据
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     public function export()
>     {
>         // 导出空白很有可能的是上面的方法getQuery没有查询到数据，用laravel-admin的相关的方法不行，因为model好像被变更了。=_=
>         // 使用 collection() 就可以了。
>         $this->download($this->fileName)->prepare(request())->send();
>         exit;
>     }
> }
> ```
不错，可以当个案例哈哈哈

**Comment by Warrens-yg** [comment]
导出的时候支持自定义多级表头吗

**Comment by pengwei1986** [comment]
请问registerEvents设置表格表格没有效果是什么原因呢？

**Comment by zhaoshl** [comment]
> 弄了快一天了，终于解决了，我哭了。😭
> 如果要使用Laravel-Excel导出数据，并且使用相关 `Export concerns`，在继承 AbstractExporter 之后需要重写 export 方法，并且不能使用FormQuery【Laravel-Admin的默认方式】获取数据，而要使用FromCollection，好像是因为model有变化，相关代码如下：
> 
> ```
> namespace App\Exports;
> 
> use Illuminate\Support\Fluent;
> use Dcat\Admin\Grid\Exporters\AbstractExporter;
> use Maatwebsite\Excel\Concerns\Exportable;
> use Maatwebsite\Excel\Concerns\FromCollection;
> use Maatwebsite\Excel\Concerns\WithCustomValueBinder;
> use Maatwebsite\Excel\Concerns\WithEvents;
> use Maatwebsite\Excel\Concerns\WithHeadings;
> use Maatwebsite\Excel\Concerns\WithMapping;
> 
> class GrabNumberExport extends AbstractExporter implements WithMapping, WithEvents, WithHeadings, WithCustomValueBinder, FromCollection
> {
>     use Exportable;
> 
>     protected $fileName = '实操抢号记录.xlsx';
> 
>     public function __construct()
>     {
>         parent::__construct();
>         $this->fileName = '实操抢号记录'.date('Y-m-d').'.xlsx';
>     }
> 
>     public function collection()
>     {
>         return collect($this->buildData());  // 使用dcat-admin的buildData获取数据
>     }
> 
>     /**
>      * {@inheritdoc}
>      */
>     public function export()
>     {
>         // 导出空白很有可能的是上面的方法getQuery没有查询到数据，用laravel-admin的相关的方法不行，因为model好像被变更了。=_=
>         // 使用 collection() 就可以了。
>         $this->download($this->fileName)->prepare(request())->send();
>         exit;
>     }
> }
> ```
> 
> 完整的代码见：https://gist.github.com/metanoia1989/e2e852fc290da11d3dc2e6c2a2bfc757

完整代码已经看不见了，我来补充一下我使用经验，测试发现FormQuery也是可以用的
<?php

namespace App\Exports;

use App\Models\User;
use Dcat\Admin\Grid\Exporters\AbstractExporter;
use Maatwebsite\Excel\Concerns\Exportable;
use Maatwebsite\Excel\Concerns\FromQuery;
use Maatwebsite\Excel\Concerns\WithHeadings;

class UserExport extends AbstractExporter implements WithHeadings, FromQuery
{
    use Exportable;

    protected $fileName = '用户列表.xlsx';

    public function __construct()
    {
        parent::__construct();
        $this->fileName = '用户列表_' . date('Y-m-d') . '.xlsx';
    }

    public function headings(): array
    {
        return [
            'Name',
            'Gender',
            'Email'
        ];
    }

    public function query()
    {
        return User::query()->select(['name','gender','email']);
    }

    public function export()
    {
        return $this->download($this->fileName)->prepare(request())->send();
    }
}
