### ISSUE TITLE
selectTable选中后如何用选中项更新表单其他字段

### ISSUE THREAD

**Issue by zhujingxiu** [jqhph/dcat-admin#1803]
- Laravel Version: 8||9
- PHP Version: 7||8
- Dcat Admin Version: 2.1^

### Description:selectTable选中后如何用选中项更新表单其他字段，
现在只有选中后显示的操作，这个实际情况其实应该和autocomplete一样有联动操作，
js操作不太熟，不知作者有空可以指导下不。

`$input.on('change', function () {}` 这个里面只有选中的value，如果需要获取其他字段数据去更新表单内容，该如何获取值呢

**Comment by keepanote** [comment]
selectTable 有个隐藏域，用css 选择器：
```php
$containerCodeClass = static::FIELD_CLASS_PREFIX . 'container_code';
```

```javascript
var container_code = $(this).closest('.fields-group').find(".$containerCodeClass input:hidden");
```
