### ISSUE TITLE
Image::resolving 里面设置maxSize(...)无效

### ISSUE THREAD

**Issue by jesse7866** [jqhph/dcat-admin#1804]
- Laravel Version: 8.83.15
- PHP Version: 7.4.3
- Dcat Admin Version: 2.2.0-beta

### Description:
在 `app/Admin/bootstrap.php` 文件中设置：

```php
use Dcat\Admin\Form;

Form\Field\Image::resolving(function (Form\Field\Image $image) {
    $image->downloadable()->uniqueName()->autoUpload()->retainable()->saveFullUrl()
        ->removable(false)->maxSize(20 * 1024);
});

```

业务代码：
```php
$form = new Form(new Model());
$form->image('url', '图片');
```

图片上传限制大小还是默认的：10MB

和 #1744 有点像，

关键代码：

https://github.com/jqhph/dcat-admin/blob/7da6c5d5480a87e58423f14a0b18d7280c173efa/src/Form/Field/File.php#L29

https://github.com/jqhph/dcat-admin/blob/7da6c5d5480a87e58423f14a0b18d7280c173efa/src/Form/Field/WebUploader.php#L225

### Steps To Reproduce:
`setUpDefaultOptions` 方法里写的固定： 10

**Comment by laradocs** [comment]
这个 Bug 在 `2.0.x-dev` 版本中已被修复。

**Comment by jesse7866** [comment]
预计什么时候发布到 `2.2.*` 呢？

**Comment by laradocs** [comment]
快了:joy:

**Comment by jesse7866** [comment]
这个bug修复的发布了吗？

**Comment by laradocs** [comment]
> 这个bug修复的发布了吗？

嗯，修复并发布了，使用 `v2.2.2` 版本就好了
