### ISSUE TITLE
菜单页面报错

### ISSUE THREAD

**Issue by michelleyaoyao** [jqhph/dcat-admin#1806]
- Laravel Version: 9.11
- PHP Version: 8.0.2
- Dcat Admin Version: 2.*

### Description:
点开菜单页面 编辑 报错

### Steps To Reproduce:

> **menu:1586 TypeError: Cannot read properties of null (reading 'submit')
>     at new e (DialogForm.js:23:25)
>     at e.DialogForm (dcat-app.js:72:16)
>     at menu:677:10
>     at HTMLDocument.<anonymous> (menu:678:3)
>     at e (eval at <anonymous> (vendors.min.js?v2.2.0-beta:2:1), <anonymous>:1:29453)
>     at t (eval at <anonymous> (vendors.min.js?v2.2.0-beta:2:1), <anonymous>:1:29755)**

**Comment by michelleyaoyao** [comment]
![企业微信截图_16558895978782](https://user-images.githubusercontent.com/12317120/174993547-a21064ea-429a-4fed-b998-ed544c4b81dd.png)

**Comment by michelleyaoyao** [comment]
而且我 设置了   'locale' => 'zh_CN',
但是语言还是上图的英文。 不知道哪里有问题。 这次是升级之后的很多问题。之前都很好的。

**Comment by laradocs** [comment]
你试试 `2.0.x-dev` 版本
在 `composer.json` 文件修改 `dcat/laravel-admin: 2.0.x-dev`
然后执行 ```composer update dcat/laravel-admin``` 即可。

**Comment by laradocs** [comment]
现在发布新版本了，你可以试试新版本还有没有上面的问题

**Comment by taozhipeng1990** [comment]
2.2.2-bate 还是有这个问题
![image](https://github.com/jqhph/dcat-admin/assets/3894069/151170dd-7a9e-49e4-aebe-54a59cb2bd35)

**Comment by taozhipeng1990** [comment]
vendor/dcat/laravel-admin/src/Admin.php 大约545行

        $jsVariables['lang'] = __('admin.client') ?: [];  期望得到一个数组。
        但 返回的是个字符串。
        
       laravel 版本 9.52.15 或者大于。
