### ISSUE TITLE
英文数据时列的宽度设置不生效

### ISSUE THREAD

**Issue by anyuhanfei** [jqhph/dcat-admin#1808]
- Laravel Version: 9.0.*
- PHP Version: 8.0.2
- Dcat Admin Version: 2.*

### Description:
我将列表中的某一列设置为宽60%，输入很长一段中文后，超出宽度就正常换行了。然后又将此列中的数据修改为很长的一段英文，回将此列的宽度拉宽。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/26684974/175274539-7a109751-e418-4a5c-9a69-b18b5d61e144.png)
![image](https://user-images.githubusercontent.com/26684974/175274660-7b212f3a-b774-48c1-9bb6-71193fc4d351.png)
![image](https://user-images.githubusercontent.com/26684974/175274954-3d766d6f-49da-4697-8105-8f3203446443.png)

**Comment by laradocs** [comment]
做成点击弹出查看更合理

**Comment by anyuhanfei** [comment]
经过测试，添加 word-break:break-all  这个css样式即可解决这个问题。
![image](https://user-images.githubusercontent.com/26684974/175440725-5919d7c1-c6b4-4c0b-b435-c0edaea0f51e.png)
![image](https://user-images.githubusercontent.com/26684974/175440656-3ad4cd80-61ca-41e9-b3a2-ee11eccebde5.png)
目前是在列上使用了setAttributes()方法解决了问题：
```
$grid->column('value')->editable()->width("60%")->setAttributes(['style'=> 'word-break:break-all;']);
```

**Comment by jqhph** [comment]
浏览器问题，连续的英文或数字就会这样
