### ISSUE TITLE
Permission::check('XXX')参数如果是字符串的话不会返回true

### ISSUE THREAD

**Issue by shenfanzi** [jqhph/dcat-admin#181]
![批注 2020-06-04 151233](https://user-images.githubusercontent.com/53527350/83721426-e40c4e80-a5ef-11ea-9b40-94d5d9818c33.jpg)
我想检查是否具有某个权限的时候，发现并不能返回true，不知道是不是逻辑上有问题
如果是用法不对，请告知合适的用法。

**Comment by jqhph** [comment]
用法不对，`Permission::check('xxx')`如果没有权限页面会直接显示错误信息，你应该这么使用
```php
Admin::user()->can('xxx');
```

**Comment by shenfanzi** [comment]
哦,我想是我没有描述清楚,并且我知道问题的原因了,我需要check直接显示错误信息的功能,如文档里的使用方式一样
![批注 2020-06-04 152531](https://user-images.githubusercontent.com/53527350/83723417-8843c480-a5f3-11ea-8328-1da5c82e8299.jpg)
可是我验证放在了Request层中统一处理,所以导致 check 方法的不适用
![批注 2020-06-04 152628](https://user-images.githubusercontent.com/53527350/83723717-f4bec380-a5f3-11ea-95eb-e805deb6c357.jpg)
