### ISSUE TITLE
v2.2.1-beta 版本数值为0时 列表不显示

### ISSUE THREAD

**Issue by itapers** [jqhph/dcat-admin#1812]
- Laravel Version: 9.1
- PHP Version: 8.0
- Dcat Admin Version:v2.2.1-beta

### Description:
![image](https://user-images.githubusercontent.com/28970916/175849744-3c7954c3-89e7-4d89-a57e-812c94624dc6.png)

v2.2.0-beta 版本是可以的

**Comment by jqhph** [comment]
请贴下grid表格的完整代码
