### ISSUE TITLE
能不能新增一个表格统计行的功能呢？

### ISSUE THREAD

**Issue by SedgeWarbler** [jqhph/dcat-admin#1814]
像laravel-admin一样
totalRow();
在表格底部跟随列对应这个字段统计这一列的数据

感觉这个功能应该挺多人需要使用的

**Comment by laradocs** [comment]
这个等作者来回答吧

**Comment by abovesky** [comment]
![screenshot-learnku com-2022 06 29-14_53_30](https://user-images.githubusercontent.com/5986216/176371174-e61f6c0c-b49c-402e-a130-eff40b641bc0.png)
能实现你说的功能

**Comment by jeavenguitar** [comment]
我也很期待这个功能，不知道何时上线
