### ISSUE TITLE
表单类返回html报错

### ISSUE THREAD

**Issue by kingdom0077** [jqhph/dcat-admin#1818]
- Laravel Version: 8.83.8
- PHP Version: 7.4.23 (cli)
- Dcat Admin Version: 2.2.0-beta

创建表单类，在handle方法中返回html，前台js报错
F12 debug，发现 form.js (asset/dcat/js/extensions/form.js) 调用的方法
```
Dcat.handleJsonResponse(response)
```

而该方法源码在 Ajax.js(asset/dcat/js/extensions/Ajax.js)中：
```
handleJsonResponse(response, options) {
       ...
        if (typeof response.html === 'string' && response.html && options.target) { //报错的位置
       ...
}
```
参数options未传，导致后面的执行报错。

这应该是个bug吧，能尽快修复吗

**Comment by laradocs** [comment]
什么版本？

**Comment by seth-shi** [comment]
同样的问题, 
Dcat Admin Version: 2.2.3-beta
