### ISSUE TITLE
Grid的progressBar设置max值无法生效

### ISSUE THREAD

**Issue by dairidong** [jqhph/dcat-admin#182]
- Laravel Version: 6.18.10
- PHP Version: 7.3.16
- Dcat Admin Version: 1.4.7

### Description:
Grid的progressBar组件无法设置max值，清除缓存后无效，看了一下源码，貌似没有应用设置的max参数

**Comment by jqhph** [comment]
感谢反馈确实有这个问题

**Comment by jqhph** [comment]
已修复

**Comment by magicgdc** [comment]
在使用进度条组件时仍然不能自定义设置max，读源码发现有个  style="width:{$this->value}%" 这里的百分数在bootstrap里应该就是value值占max值的百分数，考虑此处应该是类似于  style="width:{($this->value / $max) * 100}%" 的形式
