### ISSUE TITLE
2.2.2-beta新增数据时$form->model()无效

### ISSUE THREAD

**Issue by howye** [jqhph/dcat-admin#1821]
- Laravel Version: 8.x
- PHP Version: 7.4.28
- Dcat Admin Version: 2.2.2-beta

### Description:
在form的saved事件里面，新增数据时$form->model()无效，$form->repository()->model()有效，我记得一开始的时候是可以的，隔了一段时间$form->model()这个功能导致saved里面有的数据获取不了

->saved(function (Form $form) {
          dd($form->model(), $form->repository()->model());
 });

**Comment by laradocs** [comment]
刚试了一下低版本的，发现也拿不到模型
