### ISSUE TITLE
表單saving 新增欄位寫入問題

### ISSUE THREAD

**Issue by chino7913** [jqhph/dcat-admin#1822]
- Laravel Version: 8.83.16
- PHP Version: 7.4.16
- Dcat Admin Version: 2.2.0

### Description:
當我想在saving()裡設置一個表單上沒有的欄位寫入 , 一定得在表單放一個已存在欄位
目前我是放$form->hidden('fieldname')

### Steps To Reproduce:
例如可能表單上是 firstname lastname 這兩個欄位 到saving()做合併到 yourname 做寫入
這時候表單一定要有個$form->hidden('yourname') 
才能讓我在saving()裡用
$form->input('yourname', $form->firstname.' '.$form->lastname)
不然會沒寫東西進去yourname

**Comment by laradocs** [comment]
你可以在外部写一个 saving 触发

**Comment by chino7913** [comment]
> 你可以在外部写一个 saving 触发

請問外部是指哪裡? 目前是在function form裡面處理
例如這樣
```
protected function form(){
if ($form->isCreating()) {
   $form->hidden('orderNo');
}

$form->saving(function (Form $form) {
   if ($form->isCreating()) {
      $form->input('orderNo', date("YmdHis").Utility::randomkeys(3));
   }
});
}

```
以這個來說我要寫入一個訂單編號
前面也得先設定一個$form->hidden('orderNo');
不然saving裡無法寫入orderNo這個欄位資料

**Comment by laradocs** [comment]
可以在模型里面覆盖 boot 实现
