### ISSUE TITLE
form 表单，submit 提交前，想加一个 预览画面，如何实现？

### ISSUE THREAD

**Issue by f-wangbaoshi** [jqhph/dcat-admin#1823]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by de-memory** [comment]
可以使用表单[自定义内容 (html组件)](https://learnku.com/docs/dcat-admin/2.x/use-of-fields/8107#163605)

$form->html('你的html内容,这里也可以用view', '预览');
