### ISSUE TITLE
grid中使用弹出静态框(modal)弹出的表格删除按钮失效

### ISSUE THREAD

**Issue by lyne007** [jqhph/dcat-admin#1828]
- Laravel Version: 8.5.*
- PHP Version: 7.4
- Dcat Admin Version: v2.2.2-beta

### Description:
[弹出静态框](https://learnku.com/docs/dcat-admin/2.x/display-and-expansion-of-columns/8091#201d61) 异步加载表格，表格操作删除按钮无反应，控制台也无报错
<img width="501" alt="image" src="https://user-images.githubusercontent.com/28702327/178443616-00e59369-9352-44c5-95a6-6fad9e238265.png">
这种方式点击3个点也没反应（连下拉框都没有打开）
<img width="501" alt="image" src="https://user-images.githubusercontent.com/28702327/178446346-87b68ac3-29fe-4276-ba2a-33254b59edf4.png">

### Steps To Reproduce:
```
$grid->column('关联商品')->display('查看')->modal(function ($modal) {
          // 设置弹窗标题
          $modal->title('商品列表');
          // 自定义图标
          $modal->icon('feather icon-align-right');
          return ProductTable::make();
 });

// $grid->setResource('products/1');

```
```
<?php

namespace App\Admin\Renderable;

use App\Models\Product;
use Dcat\Admin\Grid;
use Dcat\Admin\Grid\LazyRenderable;

class ProductTable extends LazyRenderable
{
    public function grid(): Grid
    {
        // 获取外部传递的参数
        return Grid::make(Product::with(['vendor']), function (Grid $grid) {
            $grid->column('id');
            $grid->column('goods_code');
            $grid->column('goods_name');
            $grid->column('vendor.name');
            $grid->simplePaginate();
            $grid->paginate(10);
            $grid->disableFilterButton();
            $grid->setActionClass(Grid\Displayers\Actions::class);
        });
    }
}

```

**Comment by laradocs** [comment]
我觉得不能删除是合理的，这就有点像 PHPStorm 的查看功能

**Comment by lyne007** [comment]
> 我觉得不能删除是合理的，这就有点像 PHPStorm 的查看功能

我想应该是grid冲突导致的问题，不是刻意为之的

**Comment by laradocs** [comment]
你把 pjax 关掉试试，我猜这个应该是 pjax 导致的:joy:

**Comment by lyne007** [comment]
> 你把 pjax 关掉试试，我猜这个应该是 pjax 导致的😂

咋关闭？😅

**Comment by laradocs** [comment]
在 `app/Admin/bootstrap.php` 中添加以下代码：
```php
Admin::disablePjax();
```

**Comment by lyne007** [comment]
> 你把 pjax 关掉试试，我猜这个应该是 pjax 导致的😂

不行 😂

**Comment by wilbur-yu** [comment]
楼主解决了吗? 我也遇到了相同的问题, 在grid中, 使用modal异步加载了grid, 然后异步加载出来的grid, modal无效, action无效, 自定义action都是无效的

**Comment by sqrt-cat** [comment]
我也遇到同样问题了，哎，感觉是监听被off掉了，不知道怎么挂
