### ISSUE TITLE
统计卡片,控件问题

### ISSUE THREAD

**Issue by pyx02502** [jqhph/dcat-admin#1829]
- Laravel Version: 9.0
- PHP Version: 8.0
- Dcat Admin Version: v2.2.2-beta

### Description:
目前统计卡片好像只支持下拉控件
如果想引入别的控件,要怎么实现前后端的交互呢
![lx_clip1657619492552](https://user-images.githubusercontent.com/87053660/178463362-bf2c6beb-dd1b-4460-a741-6f7191828b6e.png)
比如这样

**Comment by laradocs** [comment]
可以这么做，也可以自定义触发 select

**Comment by pyx02502** [comment]
> 可以这么做，也可以自定义触发 select

请问下大大, 我这里只是加了静态控件, 具体的ajax应该写在哪, 需要怎么传到后端呢:joy:

**Comment by laradocs** [comment]
你可以用 blade 实现之后引入 dcat 中
