### ISSUE TITLE
FROM表单使用json表单，联动select组件时，如果同时定义list和keyValue格式，【新增】按钮无法正确控制

### ISSUE THREAD

**Issue by wqsacy** [jqhph/dcat-admin#1835]
- Laravel Version: 8.5
- PHP Version: 7.4
- Dcat Admin Version: 2.2.2

### Description:
FROM表单使用json表单，联动select组件时，如果同时定义list和keyValue格式，【新增】按钮无法正确控制

### Steps To Reproduce:

$form->select( 'type' , '类型' )->options( [ 1 => '键值对' , 2 => '索引数组' , 3 => '关联数组' , 4 => '自定义json' ] )->required()
                 ->when( 1 , function ( Form $form )
                 {
                     $form->text( 'content' );
                 } )->when( 2 , function ( Form $form )
                {
                    $form->list( 'content' );
                } )->when( 3 , function ( Form $form )
                {
                    $form->keyValue( 'content' );
                } )->when( 4 , function ( Form $form )
                {
                    $form->textarea( 'content' );
                } );

以上为后端代码，type定义content的值类型，需要同时支持list 和 keyValue，但是当select选中3时，【新增】按钮其实控制了list，因为list在keyValue之前，虽然没有测试删除逻辑，但是应该也会受影响

**Comment by laradocs** [comment]
字段设置一样会被污染
