### ISSUE TITLE
TinyMCE 弹窗层级问题

### ISSUE THREAD

**Issue by lurenbeia** [jqhph/dcat-admin#1840]
- Laravel Version:  9.15.0
- PHP Version: 8.0.11
- Dcat Admin Version: 2.2.2-beta

### Description:
在弹窗中使用 TinyMCE，如：
$grid->enableDialogCreate();
$grid->showQuickEditButton();
中，如果点击富文本插件上的上传图片等弹窗操作会无法使用，因为富文本插件的弹窗层级没有新增或编辑的窗口层级高。

**Comment by de-memory** [comment]
可以在app/Admin/bootstrap.php或在form表单中添加，增加一下代码(选择任意一种方式即可)

1、第一种方式。设置tinymce和jsonEditor文本编辑器工具栏，弹框z-index
Admin::style(<<<CSS
    .tox-tinymce-aux, .jsoneditor-modal{
        z-index: 19892000 !important;
     }
CSS
);
2、第一种方式(推荐)。单独设置tinymce文本编辑器工具栏，弹框z-index
Admin::style(<<<CSS
    .tox, .tox-editor-header{
        z-index: 19892000 !important;
    }
CSS
);

**Comment by lurenbeia** [comment]
感谢🙏
