### ISSUE TITLE
TinyMCE 粘贴图片的问题

### ISSUE THREAD

**Issue by lurenbeia** [jqhph/dcat-admin#1842]
- Laravel Version: 9.15.0
- PHP Version: 8.0.11
- Dcat Admin Version: 2.2.2-beta

### Description:
在使用 TinyMCE 过程中，我发现，直接复制粘贴过来的图片，会自动上传到本地，但是数据库保存的还是 base64 格式。
另外，这种时候每次打开富文本页面，都会再次上传一遍。

**Comment by lurenbeia** [comment]
已解决，重写了模板文件
![image](https://user-images.githubusercontent.com/49217897/179198193-5904054c-e996-4eb3-a8cf-6cd1e30ad18b.png)

**Comment by 8khp035ug5y6** [comment]
感谢大佬

**Comment by 8khp035ug5y6** [comment]
解决了,感谢
