### ISSUE TITLE
Dcat-admin安装失败php artisan admin:install

### ISSUE THREAD

**Issue by godingchen** [jqhph/dcat-admin#1847]
- Laravel Version: #.#.#
- > laravel9
- PHP Version: #.#.#
- php8
- Dcat Admin Version: #.#.#
2.x
### Description:
![image](https://user-images.githubusercontent.com/49898961/179715578-e7a72d57-afed-42f8-b8e2-1120780b1d53.png)

laravel社区问题链接
https://learnku.com/laravel/t/69863

**Comment by laradocs** [comment]
检查一下数据库

**Comment by godingchen** [comment]
> 查看数据库一下
![image](https://user-images.githubusercontent.com/49898961/179717937-8be4336e-3541-4ab3-b583-840be32882ef.png)
![image](https://user-images.githubusercontent.com/49898961/179718019-2994387a-ab4f-40a8-a9aa-562b04fd931b.png)

有数据库

**Comment by godingchen** [comment]
问题已解决，pdo_mysql的问题，具体解决办法
https://learnku.com/laravel/t/69863
