### ISSUE TITLE
图片上传生成缩略图

### ISSUE THREAD

**Issue by fsc020915** [jqhph/dcat-admin#1856]
![image](https://user-images.githubusercontent.com/87160919/180678248-67fa6d4e-de93-4663-b4a3-13a3f6f0753f.png)
这里面$photo是引用的什么变量
求大佬指点一下怎么写

**Comment by PorygonCN** [comment]
第一个参数是缩略图tag  第二个是字段名称   tag对应上面thumbnail()参数 数组里的key
`$photo`就是model的实例 查询结果

**Comment by fsc020915** [comment]
> 第一个参数是缩略图tag 第二个是字段名称 tag对应上面thumbnail()参数 数组里的key `$photo`就是model的实例 查询结果
![image](https://user-images.githubusercontent.com/87160919/180709715-1bed60e7-66f3-4204-92fd-bb2b65df7e41.png)
请问是这样写吗

**Comment by fsc020915** [comment]
> > 第一个参数是缩略图tag 第二个是字段名称 tag对应上面thumbnail()参数 数组里的key `$photo`就是model的实例 查询结果
> > ![图片](https://user-images.githubusercontent.com/87160919/180709715-1bed60e7-66f3-4204-92fd-bb2b65df7e41.png)
> > 请问是这样写吗
![image](https://user-images.githubusercontent.com/87160919/180709880-4d749eec-38fd-48c0-94a5-d22b4ea25475.png)
是不是还要composer包啊

**Comment by fsc020915** [comment]
> 

composer require intervention/image   解决了
