### ISSUE TITLE
Uncaught TypeError: Dcat.wait is not a function

### ISSUE THREAD

**Issue by betaxab** [jqhph/dcat-admin#1858]
- Laravel Version: 6.20.44
- PHP Version: 7.4.30
- Dcat Admin Version: v2.2.2-beta

### Description:

后台管理页面会出现 Uncaught TypeError: Dcat.wait is not a function 错误。

ReferenceError: Switchery is not defined

Error: <g> attribute transform: Expected number, "translate(NaN, 0)".

TypeError: $(...).off(...).select2 is not a function

一个比较难以理解的 bug 就是，资源有时候明显感觉没加载全，出现的比如开关按钮、输入框变成那种特别原始的风格、上传窗口不加载“添加文件”按钮，然后就会导致业务功能出现异常。

但是经过刷新页面以后，这些功能又能正常加载出来。并且页面刷新后，上述报错也不会出现。

实在是不知道如何解决，我没有修改 dcat 部分的源码。

### Steps To Reproduce:

清空浏览器资源，然后打开页面。

![2022-07-25_11-51-48](https://user-images.githubusercontent.com/30405429/180695637-6360df4e-db6f-4856-b0ce-e89e135bfc34.png)

![2022-07-25_11-51-13](https://user-images.githubusercontent.com/30405429/180695673-f0cdb8c8-156d-47c3-8381-846ee71a6742.png)

![2022-07-25_11-42-09](https://user-images.githubusercontent.com/30405429/180695679-1f8187d0-e32d-4c51-bc03-0210c9fac26e.png)

**Comment by laradocs** [comment]
从来没遇到过，不太好处理

**Comment by betaxab** [comment]
问题我找到了，在执行 composer update 后，vendor/dcat-admin 中的 dcat-apps.js 并没有更新成功。必须把 dcat-admin 文件夹彻底删除了再重新更新才能成功。
@laradocs @jqhph

**Comment by laradocs** [comment]
这个升级说明里面已经写了
https://learnku.com/docs/dcat-admin/2.x/version-upgrade/8209#89f06e
