### ISSUE TITLE
使用浏览器回退，出现页面卡顿

### ISSUE THREAD

**Issue by caoyuyan** [jqhph/dcat-admin#1859]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.0.16

### Description:
通过列表进入到文章的编辑页，然后使用浏览器的返回，在返回到列表页的时候，会出现一直加载的情况，
![image](https://user-images.githubusercontent.com/57203493/180941016-29efcef8-76fb-43ac-902d-e507f299b4ac.png)
![image](https://user-images.githubusercontent.com/57203493/180941330-88469c40-c232-40e9-b8fd-4712b818e05b.png)

**Comment by laradocs** [comment]
换个浏览器:joy:

**Comment by caoyuyan** [comment]
> 换个浏览器😂

换了,谷歌,火狐,edge都不行

**Comment by laradocs** [comment]
我这边从来没遇到过这种问题，你执行 `php artisan view:clear` 命令试试

**Comment by caoyuyan** [comment]
> 

没有用,算了直接用自带的列表页返回吧
