### ISSUE TITLE
批量操作动作跟工具表单一起使用，如何将选中行的主键数组传递给工具表单

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#186]
- Laravel Version: 6.2
- PHP Version: 7.3
- Dcat Admin Version: 1.4

# Description:
🧡首先感谢大大的精勤更新和热情回复。🧡

> 行操作基类 (RowAction)，可以通过`$this->row`获取到当前行数据内容。
> 批量操作基类 (BatchAction) 通过 getSelectedKeysScript 方法可以生成获取选中的行的主键数组的JS代码。

但是创建一个批量操作类，如何将选择行的主键数组传递给工具表单呢，只有`getSelectedKeysScript`方法我不太懂怎么处理。

**Comment by jqhph** [comment]
我写个demo吧，这个有点麻烦

**Comment by jqhph** [comment]
文档已更新，请参考[工具表单 - 批量操作弹窗](http://www.dcatadmin.com/docs/master/widgets-form.html#batch-modal)
