### ISSUE TITLE
表格grid如何对多对多关系进行where条件筛选？

### ISSUE THREAD

**Issue by totoro52** [jqhph/dcat-admin#1860]
- Laravel Version: 8.75
- PHP Version: 7.3
- Dcat Admin Version: 2.*

### Description:
我新建了一个管理员控制器，用来单独显示一组拥有某个角色的表格，所以我用代码生成器生成了控制器。
按照官方文档的方式，在grid方法添加如下代码：
```
$grid = new Grid(Administrator::with(['roles']));
$grid->model()->where('slug','123');
```
按照这个方式添加条件后条件确实添加了，但同时报了SQL错误：
```
SQL: select count(*) as aggregate from `admin_users` where `slug` = 123
```
说明这个取到的模型并不是联表模型，然后我又重新写了一个数据仓库，复写了get方法，并添加如下代码：
```
        if ($this->relations) {
            $query->with($this->relations);
            $query->where('slug','123');
        }
```
此时代码没有任何报错，但where条件不起效，列表还是显示出了全部数据，但如果我把字段改成一个不存在的值就会报SQL错误，证明确实是执行了查询，但最终结果却不一致。
### Question
我想知道表格如何在渲染前自定义一些连表的where条件，文档的方法全部都尝试了，也尝试了laravel-admin的文档，全部都没办法实现这个功能，感谢回复！

**Comment by totoro52** [comment]
已解决，解决方案最后参考文档的复杂SQL实现，复写了get，直接不使用ORM模型使用DB函数进行了连表并返回分页对象即可。

**Comment by totoro52** [comment]
参考文档：https://learnku.com/docs/dcat-admin/2.x/data-source/8096#7ed861

**Comment by kriston001** [comment]
> 参考文档：https://learnku.com/docs/dcat-admin/2.x/data-source/8096#7ed861

有没有你写的案例，能发出来参考一下吗，我也遇到了同样的问题

**Comment by totoro52** [comment]
> > 参考文档：https://learnku.com/docs/dcat-admin/2.x/data-source/8096#7ed861
> 
> 有没有你写的案例，能发出来参考一下吗，我也遇到了同样的问题

根据我提供的文档就可以实现了，复写数仓的get方法，返回一个分页对象即可，不要使用ORM模型，使用DB去做连表， ORM模型连表非常的难用。

例如：
```
$users = DB::table('users')
            ->join('contacts', 'users.id', '=', 'contacts.user_id')
            ->join('orders', 'users.id', '=', 'orders.user_id')
            ->select('users.*', 'contacts.phone', 'orders.price')
            ->paginate($model->getPerPage());
```
get方法直接return这个对象即可。
