### ISSUE TITLE
form 表单动态字段无效

### ISSUE THREAD

**Issue by Liuxiaom** [jqhph/dcat-admin#1861]
- Laravel Version: 6.x
- PHP Version: 7.3
- Dcat Admin Version: 2.2.2-beta

### Description:
$form->radio('is_free_shipping','是否免邮')->when('no', function (Form $form) {
                $form->text('shipping_template','运费模板');
            })->options(['no'=>'否','yes'=>'是'])->default('yes');

**Comment by laradocs** [comment]
把 options 写在 when 前面试试

**Comment by laradocs** [comment]
预期正常了没？

**Comment by laradocs** [comment]
那我先给你关了哈
