### ISSUE TITLE
使用http访问，js css等资源自动加上了https,导致样式显示异常

### ISSUE THREAD

**Issue by trkjoy** [jqhph/dcat-admin#1862]
- Laravel Version: 6.20.44
- PHP Version: 7.4.21
- Dcat Admin Version: v2.2.2-beta

### Description:
后台使用 http 访问，但是 js,css等资源文件 自动使用了https，导致后台无法正常显示样式
![image](https://user-images.githubusercontent.com/12812086/181241650-2bf80d4f-6c16-4690-bd37-e2977f82f827.png)
### Steps To Reproduce:
我的 .env 中已经设置了
APP_URL=http://xxx
ADMIN_HTTPS=false

缓存也已经清除过了，想请教一下这种问题是该怎么处理呢？谢谢

**Comment by de-memory** [comment]
服务器是不是开启了https呢？
