### ISSUE TITLE
有迁移文件的扩展，安装报错

### ISSUE THREAD

**Issue by de-memory** [jqhph/dcat-admin#1864]
- Laravel Version: ^8|^9
- PHP Version: ^7.3|^8.0
- Dcat Admin Version: 2.2.2

[创建迁移文件章节](https://learnku.com/docs/dcat-admin/2.x/basic-use/8128#77f6b7)

```
<?php

return [
    '1.0.0' => [
        '版本变化描述1',
        '版本变化描述2',
        'create_opration_log_table.php', // 迁移文件名称，安装或更新版本时会自动执行
    ],
];
```

安装的时候 HTTP 500 Internal Server Error

```
exception: "PDOException"
file: "E:\\www\\codeup_aliyun\\dev\\dlcss_admin\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Concerns\\ManagesTransactions.php"
line: 45
message: "There is no active transaction"
```
[复现错误，可以使用官网的操作日志扩展](https://github.com/dcat-admin/operation-log)

**Comment by de-memory** [comment]
卸载扩展的时候也是一样

**Comment by laradocs** [comment]
确实有这个情况，但不影响正常使用。

第一次点安装的时候会提示 `There is no active transaction` 字样
第二次点安装执行成功
卸载有问题检查是不是在启用状态操作的
<img width="119" alt="image" src="https://user-images.githubusercontent.com/49741756/182054405-735b3aa1-9107-461e-a751-9763b084bf87.png">

**Comment by WillieOng-HK** [comment]
> 

試試在`Schema::create` 和 `Schema::dropIfExists` 前 執行 `\DB::commit();`

**Comment by dds813** [comment]
顶，应该是dcat-admin使用了事务的隐式提交，但是不知道应该如何解决

**Comment by dds813** [comment]
我在dcat-admin中使用stanle/tenant这个包在创建租户的时候，tenant会去新建一个数据库，在这个过程中所有的数据库操作都可以正常完成，但是也是会报There is no active transaction这个错误，laravel 10 php 8.1 dcat-admin 2.2.2 beta,网上查到的是php8以后对事务的处理进行了修改，好像是隐式提交事务会报这个错误，不知道如何解决
