### ISSUE TITLE
新建页面其他字段验证失败导致上传图片丢失

### ISSUE THREAD

**Issue by chengmingtian** [jqhph/dcat-admin#1868]
- Laravel Version: 8.83.3
- PHP Version: 7.3.4
- Dcat Admin Version: 2.2.0-beta

### Description:
新建页面其他字段验证失败导致上传图片丢失
issue参考
#1534 
#1748 
我按照#1748回答更新到dev版本，问题没有解决
我参考了下laravel-admin这边回答，[https://github.com/z-song/laravel-admin/issues/2728](url)，这个问题可能确实没办法解决，删文件问题不大，但是可不可以同时删除界面上的图片好让用户重新上传，现在是文件删了，界面上图片还在，还能通过验证添加成功，但实际图片已经不存在了，数据库保存一个失效的图片地址

麻烦您帮忙看下有解决方案吗

**Comment by SangBoy** [comment]
可以自定义上传接口，这样可以避免这个问题。
[查看文档](https://learnku.com/docs/dcat-admin/2.x/picture-file-upload/8106#3b2626)
