### ISSUE TITLE
[Question] grid filter 如何实现给定一个默认值并且生效筛选

### ISSUE THREAD

**Issue by Gwill** [jqhph/dcat-admin#1871]
类似这样：

```php
            $grid->filter(function (Grid\Filter $filter) {
                $currentDate = Carbon::today();
                $filter->date('date')->default($currentDate->toDateString());
            });
```

使用 default 方法，只能让输入框默认填入，但是并不能生效过滤条件，还需要自己点击确定。如何能设置默认值并且直接生效？

**Comment by SangBoy** [comment]
```
$grid->model()->where('date', '=', date('Y-m-d'));
```
或者
```
$grid->filter(function (Grid\Filter $filter){
    $filter->model()->where('date', '=', date('Y-m-d'));
});
```

**Comment by rsj123** [comment]
> ```
> $grid->model()->where('date', '=', date('Y-m-d'));
> ```
> 
> 或者
> 
> ```
> $grid->filter(function (Grid\Filter $filter){
>     $filter->model()->where('date', '=', date('Y-m-d'));
> });
> ```

使用此方案后若仍想使用filter该如何操作呢，例如date默认为当前年月，但若后续filter查询上个月之类的，似乎无法使用

**Comment by rsj123** [comment]
> > ```
> > $grid->model()->where('date', '=', date('Y-m-d'));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 或者
> > ```
> > $grid->filter(function (Grid\Filter $filter){
> >     $filter->model()->where('date', '=', date('Y-m-d'));
> > });
> > ```
> 
> 使用此方案后若仍想使用filter该如何操作呢，例如date默认为当前年月，但若后续filter查询上个月之类的，似乎无法使用

已在其他issue中找到：#1089
