### ISSUE TITLE
请问 dcat admin 有没有如下功能

### ISSUE THREAD

**Issue by andyzu** [jqhph/dcat-admin#1873]
请问 dcat admin 有没有如下功能：

前言：我们给学校做了个班级管理，总管理人员将学校里的所有班级录入到后台系统里【就用 dcat admin 默认的 $grid, $show, $form 实现】。

需实现：总管理人员给子管理员分配权限，每个子管理员进入后台之后，发布任何内容，都从属于该子管理人员所管理的班级。

举例：
1、总管理员 admin 建立的班级有：1 年级 1 班，1 年级 2 班，1 年级 3 班….. ，然后建立一个子管理员 andyzu , 并将 andyzu 的权限划分到 1 年级 3 班。
2、andyzu 登录后台系统后，可以发布通知通告，发布班级照片，都将自动从属于 1 年级 3 班，而不是在发布通知通告或者班级照片的时候通过 select 来进行选择，防止误发到其他班级。

各位看官大神，该需求如何解决？

https://learnku.com/laravel/t/70642

**Comment by dreamdesky** [comment]
子管理员有没有可能管理多个班级？如果有这种情况，建议在表单的班级字段加以控制，只有一个班级就显示一个选项、有多个班级就显示多个选项，安全起见，还要加个表单验证，判断下子管理员有没有这个班级的权限

**Comment by mbdmt** [comment]
> 



> 请问 dcat admin 有没有如下功能：
> 
> 前言：我们给学校做了个班级管理，总管理人员将学校里的所有班级录入到后台系统里【就用 dcat admin 默认的 $grid, $show, $form 实现】。
> 
> 需实现：总管理人员给子管理员分配权限，每个子管理员进入后台之后，发布任何内容，都从属于该子管理人员所管理的班级。
> 
> 举例： 1、总管理员 admin 建立的班级有：1 年级 1 班，1 年级 2 班，1 年级 3 班….. ，然后建立一个子管理员 andyzu , 并将 andyzu 的权限划分到 1 年级 3 班。 2、andyzu 登录后台系统后，可以发布通知通告，发布班级照片，都将自动从属于 1 年级 3 班，而不是在发布通知通告或者班级照片的时候通过 select 来进行选择，防止误发到其他班级。
> 
> 各位看官大神，该需求如何解决？
> 
> https://learnku.com/laravel/t/70642

1, 先建一個子管理員角色及單元權限, 把所有子帳號都建好
2. 建班級, 將A班級指定給A子帳號,以此類推 
3. 发布通知或照片資料庫加入一欄adminid紀錄是那個子帳號id
4. 列表頁Grid預設加入adminid條件 , 所以顯示出來就會自當前子管理员自己的數據 
$grid->model()->where("adminid", Admin::user()->username)->orderBy('id', 'desc');

5.新增/編輯頁面處理
可以在 $form->saving(function (Form $form) 這裡加入adminid的欄位寫入Admin::user()->username
偷懶一點可以加入一個隱藏欄位 去放adminid 就能記錄該子帳號數據
$form->hidden('adminid')->value(Admin::user()->username);

Admin::user()->username <=這個是抓帳號的名稱
Admin::user()->getKey() <=這個是抓帳號的序號id
看你要記錄那個都行
大致上這樣應該就能處理

**Comment by andyzu** [comment]
> > 
> 
> > 请问 dcat admin 有没有如下功能：
> > 前言：我们给学校做了个班级管理，总管理人员将学校里的所有班级录入到后台系统里【就用 dcat admin 默认的 $grid, $show, $form 实现】。
> > 需实现：总管理人员给子管理员分配权限，每个子管理员进入后台之后，发布任何内容，都从属于该子管理人员所管理的班级。
> > 举例： 1、总管理员 admin 建立的班级有：1 年级 1 班，1 年级 2 班，1 年级 3 班….. ，然后建立一个子管理员 andyzu , 并将 andyzu 的权限划分到 1 年级 3 班。 2、andyzu 登录后台系统后，可以发布通知通告，发布班级照片，都将自动从属于 1 年级 3 班，而不是在发布通知通告或者班级照片的时候通过 select 来进行选择，防止误发到其他班级。
> > 各位看官大神，该需求如何解决？
> > https://learnku.com/laravel/t/70642
> 
> 1, 先建一個子管理員角色及單元權限, 把所有子帳號都建好 2. 建班級, 將A班級指定給A子帳號,以此類推 3. 发布通知或照片資料庫加入一欄adminid紀錄是那個子帳號id 4. 列表頁Grid預設加入adminid條件 , 所以顯示出來就會自當前子管理员自己的數據 $grid->model()->where("adminid", Admin::user()->username)->orderBy('id', 'desc');
> 
> 5.新增/編輯頁面處理 可以在 $form->saving(function (Form $form) 這裡加入adminid的欄位寫入Admin::user()->username 偷懶一點可以加入一個隱藏欄位 去放adminid 就能記錄該子帳號數據 $form->hidden('adminid')->value(Admin::user()->username);
> 
> Admin::user()->username <=這個是抓帳號的名稱 Admin::user()->getKey() <=這個是抓帳號的序號id 看你要記錄那個都行 大致上這樣應該就能處理
感谢细致的讲解！！ 再次真心感谢！
