### ISSUE TITLE
数据表格如何拼接不同数据源？

### ISSUE THREAD

**Issue by symfonyluxury** [jqhph/dcat-admin#188]
比如一个网站流量统计表格，当天实时从缓存中读取，历史从数据库中读，那么这个表格就是这两者读混合，请问如何实现？

**Comment by jqhph** [comment]
很好实现，请参考文档[表格数据源](http://www.dcatadmin.com/docs/master/model-grid-data.html)

**Comment by symfonyluxury** [comment]
好的，已参照建议解决
