### ISSUE TITLE
希望可以左侧菜单加入分组！

### ISSUE THREAD

**Issue by 8108905** [jqhph/dcat-admin#1883]
类似 Nova的分组

https://user-images.githubusercontent.com/1809081/44530891-281eaf80-a6f8-11e8-9768-8fa9e31f4fc5.png

**Comment by sunkangchina** [comment]
![image](https://user-images.githubusercontent.com/66815206/186370952-d2b6eefa-026c-4506-91a8-0f0817211554.png)
这种不行？
