### ISSUE TITLE
scaffold 创建migrations 时，报错，所传参数不一致

### ISSUE THREAD

**Issue by LeesinYii** [jqhph/dcat-admin#19]
- Laravel Version: 7.0+
- PHP Version: 7.2.9
- Dcat Admin Version: dev-master

### Description:
在使用scaffold 创建migrations 时，报错：
>ArgumentCountError:` Too few arguments to function Illuminate\Database\Migrations\MigrationCreator::__construct(), 1 passed in E:\php\gift-branch\gift_branch_backstage\vendor\dcat\laravel-admin\src\Controllers\ScaffoldController.php on line 119 and exactly 2 expected in file E:\php\gift-branch\gift_branch_backstage\vendor\laravel\framework\src\Illuminate\Database\Migrations\MigrationCreator.php on line 40

### 原因
>传参数量不一致

### Steps To Reproduce:
![图片](https://user-images.githubusercontent.com/25756554/78096708-ed6d1500-740c-11ea-865f-9f8c2a5fdf73.png)

**Comment by jqhph** [comment]
感谢反馈，laravel7确实有这个问题

**Comment by jqhph** [comment]
有时间的话也欢迎提交PR

**Comment by jqhph** [comment]
[已修复](https://github.com/jqhph/dcat-admin/commit/145ef5a727efbfb2fab8cc9a69824f315c4d37af)

**Comment by LeesinYii** [comment]
多谢大佬及时修复，要不就得改底层了，对于后续维护会很麻烦，这样我去更新下就好了，真是太感谢了

**Comment by jqhph** [comment]
现在的问题都会在正式版出来之前完全修复的，现在的只是预发布版本，可能会有点小问题。正式版很快就会发布，欢迎进群交流 704661955
