### ISSUE TITLE
非弹出层数据表单字段为row时，样式问题

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#190]
![批注 2020-06-07 153652](https://user-images.githubusercontent.com/46614146/83962079-f1b62280-a8d4-11ea-8ed5-cb6a74b16242.jpg)

**Comment by jqhph** [comment]
后续会优化这个问题

**Comment by Warrens-yg** [comment]
我现在是1.4.8版本，表格操作列出现这个情况
![批注 2020-06-07 154416](https://user-images.githubusercontent.com/46614146/83962140-c5e76c80-a8d5-11ea-964b-44ee39fd63fc.jpg)

**Comment by jqhph** [comment]
> 我现在是1.4.8版本，表格操作列出现这个情况
> ![批注 2020-06-07 154416](https://user-images.githubusercontent.com/46614146/83962140-c5e76c80-a8d5-11ea-964b-44ee39fd63fc.jpg)

是的，这个是因为表格的上一层显示了滚动条，如果你不用responsive就不会出现这个

**Comment by Warrens-yg** [comment]
我现在是没有启用responsive的状态，
#175  更新到最新版就可以了是吗

**Comment by jqhph** [comment]
> 我现在是没有启用responsive的状态，
> #175 更新到最新版就可以了是吗

你现在这个肯定是启用了responsive功能，滚动条往下拉就显示全了

**Comment by Warrens-yg** [comment]
这是我的表格部分代码，我没找到启用的地方，麻烦帮忙看一下
![批注 2020-06-07 163454](https://user-images.githubusercontent.com/46614146/83962943-d8b16f80-a8dc-11ea-8dc8-34bc26d7abaf.jpg)

**Comment by jqhph** [comment]
> 这是我的表格部分代码，我没找到启用的地方，麻烦帮忙看一下
> ![批注 2020-06-07 163454](https://user-images.githubusercontent.com/46614146/83962943-d8b16f80-a8dc-11ea-8dc8-34bc26d7abaf.jpg)

我明白了，你这个需要重新安装一下，先remove dcat/laravel-admin，再重新安装，然后重新发布资源就好了

**Comment by Warrens-yg** [comment]
https://monosnap.com/file/5FOnE34bM87WX6alHPZcUsxMpsrTrB

**Comment by jqhph** [comment]
不是，你得清理composer缓存composer clear-cache，重新发布资源，并清理浏览器缓存。实在不行你就更新master分支的代码

**Comment by Warrens-yg** [comment]
如果资源不删除，发布的时候不会覆盖是吗，刚才就是发布了没有作用，后来手动把public里的资源换掉就可以了。

**Comment by jqhph** [comment]
需要加参数--force，你去看一下文档版本升级须知吧
