### ISSUE TITLE
怎么隐藏导出按钮

### ISSUE THREAD

**Issue by anyexinyang** [jqhph/dcat-admin#1901]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
最新版本，我想用导出功能，按钮是自定义的工具类。所以自带的导出按钮想隐藏掉，请问有什么办法呢

**Comment by dogeow** [comment]
这个文档应该有吧

**Comment by joker9657** [comment]
[默认不开启导出功能。](https://learnku.com/docs/dcat-admin/2.x/data-export/8101#09d442)

**Comment by flc1125** [comment]
```php
$grid->export();
```

**Comment by jun5764** [comment]
你应该是想用导出功能但不想出那个按钮是吧，是调用了 $grid->export 就会出来按钮，试过全部禁掉都有个框框，
https://github.com/jqhph/dcat-admin/blob/eb8ed6390c4d9bd9e992958f4ba508fdbfce37bd/src/Grid/Tools/ExportButton.php#L113-L117
有个 _export_ 参数
https://github.com/jqhph/dcat-admin/blob/eb8ed6390c4d9bd9e992958f4ba508fdbfce37bd/src/Grid/Exporter.php#L34
带上会自动跑导出逻辑，允许的参数是：all、page、selected,
https://github.com/jqhph/dcat-admin/blob/eb8ed6390c4d9bd9e992958f4ba508fdbfce37bd/src/Grid/Exporter.php#L18-L20
具体的用法可以随便弄个页面，点击原来的导出看提交的参数变化就好。


用法：对应控制器加个 if 再 export 就不会出来按钮但可以用导出功能了
```
if (request()->get('_export_')) {
    $grid->export();
}
```
