### ISSUE TITLE
multipleFile 多文件上传 字段取名为file时 无法获取到上传文件的信息 其它字段名 可以获取到？

### ISSUE THREAD

**Issue by tongxxx777** [jqhph/dcat-admin#1908]
- Laravel Version: 8.5
- PHP Version: 8.0
- Dcat Admin Version: 2.x

### 问题描述:
我在使用多文件上传时 使用字段名为file 打印上传文件信息 返回[]
但是换成file1或其它字段名 就能获取到上传信息

请问作者是什么原因呢？？？这个功能有关键字不能取？
但是我的确就是上传文件 换个字段名 不合适啊 很无奈...

### 代码:
```
$form->multipleFile('file')->saving(function ($value) {
        dd($value);
        // 可以转化为由 , 隔开的字符串格式
        return implode(',', $value);
});
```

**Comment by ghost** [comment]
同样遇到这个bug了，排查了好一阵子，巨坑。
