### ISSUE TITLE
请问 hasMany中如何调用saving ?

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#191]
请教下

我的需求是在表单送出前  hasmany中要调用saving 检查库存
同时会用到 $form->warehouse_id , $table->product_id 去DB中检查
但不知为何saving都没有作用

想请大佬您指点一下，谢谢

![螢幕快照 2020-06-08 上午3 40 30](https://user-images.githubusercontent.com/16574141/83978411-d9c4ba00-a939-11ea-9f90-8799212c9263.png)

**Comment by jqhph** [comment]
`Form`对象才能调用`saving`方法`$form->saving`，把你的逻辑放在外面
