### ISSUE TITLE
使用固定列在数据条数不足时会出现遮挡滚动条的问题

### ISSUE THREAD

**Issue by 8khp035ug5y6** [jqhph/dcat-admin#1927]
- Laravel Version: 9.19
- PHP Version: 8.0.1
- Dcat Admin Version: 2.*
### Description:
使用固定列功能时,当数据条数的高度不超出屏幕,滚动条会被遮挡掉
![image](https://user-images.githubusercontent.com/88567748/195224303-c0e9ae08-c91a-4cc8-aebf-7e6489d904ab.png)

![image](https://user-images.githubusercontent.com/88567748/195223956-8039b39c-f0af-4a89-bd67-112abdd2d809.png)

超出后就是正常的了
![image](https://user-images.githubusercontent.com/88567748/195224239-0b4ca378-9bcc-495a-8b81-8abe1c02af15.png)

**Comment by balabalab** [comment]
+1

**Comment by balabalab** [comment]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/26957213/201119894-af04a945-d94d-49c3-905c-3bafabfeb35c.png">
我的是这样

**Comment by trkjoy** [comment]
+1
