### ISSUE TITLE
数据统计卡片是否可以提供灵活的额外参数注入方式？

### ISSUE THREAD

**Issue by Celaraze** [jqhph/dcat-admin#193]
- Laravel Version: ^7.0
- PHP Version: ^7.4.6
- Dcat Admin Version: 1.4.8

### Description:
我通过数据统计卡片制作三个区域的疫情数量统计：中国，美国，全球。按照案例中的做法是我需要新建三个卡片：
new ChinaCovid();
new AmericanCovid();
new GlobalCovid();
这样不酷，我想着通过对卡片注入参数的方式解决，比如：
new Covid('中国');
new Covid('美国');
new Covid('全球');
在对应的卡片类中使用：
```public function __construct($area){}```
但是报错：Unresolvable dependency resolving

### Steps To Reproduce:
Above.

**Comment by jqhph** [comment]
当然可以，统计卡片都是自定义的类，你想怎么处理都行

**Comment by jqhph** [comment]
你重写__construct方法的时候别忘了加上parent::__construct()

**Comment by jqhph** [comment]
还有构造器方法的参数需要加上默认值

**Comment by Celaraze** [comment]
我目前是这样：

    protected $test;

    public function __construct($test, $title = null, $icon = null)
    {
        parent::__construct($title, $icon);
        $this->test = $test;
    }

    /**
     * 处理请求
     * @param Request $request
     * @return mixed|void
     */
    public function handle(Request $request)
    {
        dd($this->test);  //在此报错Unresolvable dependency resolving
        //其它处理代码……
    }

但是有报错，希望给些指点，非常感谢。

**Comment by jqhph** [comment]
不是说了吗构造方法参数需要加默认值，另外handle方法是不支持使用test属性的

```php
/**
     * 返回请求附带的参数.
     *
     * @return array
     */
    public function parameters(): array
    {
        return ['test' => $this->test];
    }
```

**Comment by jqhph** [comment]
发现统计卡片中`parameters`方法无效，下个版本中会修复这个问题

**Comment by Celaraze** [comment]
> 发现统计卡片中`parameters`方法无效，下个版本中会修复这个问题

好的，谢谢大佬

**Comment by jqhph** [comment]
已修复，等新版本发布吧
