### ISSUE TITLE
Modal 如何可以自动弹出？例如新版本更新提示，如果有新版本自动弹出提示

### ISSUE THREAD

**Issue by 8108905** [jqhph/dcat-admin#1930]
默认需要点击 button
 
protected function modal1()
    {
        return Modal::make()
            ->lg()
            ->title('弹窗')
            ->body($this->table())
            ->button('<button class="btn btn-white"><i class="feather icon-grid"></i> 普通弹窗</button>');
    }

    protected function table()
    {
        Admin::style('.table td{padding: .85rem .55rem}');
        $data = [
            ['name' => 'PHP version', 'value' => 'PHP/' . PHP_VERSION],
            ['name' => 'Laravel version', 'value' => app()->version()],
            ['name' => 'CGI', 'value' => php_sapi_name()],
            ['name' => 'Uname', 'value' => php_uname()],
            ['name' => 'Server', 'value' => Arr::get($_SERVER, 'SERVER_SOFTWARE')],
            ['name' => 'Cache driver', 'value' => config('cache.default')],
            ['name' => 'Session driver', 'value' => config('session.driver')],
        ];
        return Table::make(['name', 'value'], $data);
    }

**Comment by nicesome** [comment]
同问

**Comment by 8108905** [comment]
仔细看一遍 文档可以解决

NiceSome ***@***.***>于2022年11月5日 周六00:00写道：
