### ISSUE TITLE
为什么会出现请求多次提交的问题

### ISSUE THREAD

**Issue by caoyuyan** [jqhph/dcat-admin#1932]
- Laravel Version: 8.5
- PHP Version: 8.0
- Dcat Admin Version: 2.2.2

### Description:

后台主页加了一个ajax请求,  如果第一次进入可以正常请求,  
但是如果切换到其他模块在切回到主页后,  
再次请求的时候会出现两次ajax请求的提交

**Comment by louislee0201** [comment]
请问最后怎么解决？ @caoyuyan 
版主好像停更了
