### ISSUE TITLE
为什么权限需不会自动生成基础的，需要一个个手动加？很费解，不能理解。

### ISSUE THREAD

**Issue by quejingshi** [jqhph/dcat-admin#1936]
既然支持按钮级的权限管理，为什么不在代码生成的时候就把这些一起生成了，一定要折磨用户，一个个添加，一个个改？页面一多，这后台没有任何优势啊

**Comment by nicesome** [comment]
很多东西都可以自己衍生的

**Comment by faydanube** [comment]
> 既然支持按钮级的权限管理，为什么不在代码生成的时候就把这些一起生成了，一定要折磨用户，一个个添加，一个个改？页面一多，这后台没有任何优势啊

期待你 fork 一份做個更完善的，大家一定都感謝你
