### ISSUE TITLE
grid新增如果开启enableDialogCreate, 则表单项autocomplete不生效

### ISSUE THREAD

**Issue by wilbur-yu** [jqhph/dcat-admin#1939]
- Laravel Version: 9.37
- PHP Version: 8.0
- Dcat Admin Version: 2.2.2

表单中使用自动完成field: autocomplete, 这时如果在grid中开启enableDialogCreate, 则autocomplete不会弹出选择列表.
将enableDialogCreate关闭, 则正常

**Comment by StechMY** [comment]
有解决方案了吗

**Comment by StechMY** [comment]
找到解决方案了 是因为被Dialog覆盖了 
添加CSS z-index 即可解决

`Admin::style(<<<CSS
                .autocomplete-suggestions{
                    z-index: 99999999 !important;
                }
            CSS);`
