### ISSUE TITLE
config配置中的route.prefix设置为空字符串，编辑或新增权限时，路由列表为空

### ISSUE THREAD

**Issue by dairidong** [jqhph/dcat-admin#194]
- Laravel Version:  6.18.10
- PHP Version: 7.3.16
- Dcat Admin Version: 1.4.8

### Description:
项目需求只需要后台，route.prefix设置为空字符，无法获取路由列表，只能手动输入标签，虽然也可以用，但是希望修复一下。

**Comment by jqhph** [comment]
描述清楚一点，无法获取到路由列表是什么意思

**Comment by jqhph** [comment]
明白你的意思了

**Comment by dairidong** [comment]
> 描述清楚一点，无法获取到路由列表是什么意思

![image](https://user-images.githubusercontent.com/48778797/84104341-f9e29f00-aa47-11ea-9bf1-131572862be1.png)
我直接上个图吧，只要prefix是空值，必定是空列表

**Comment by jqhph** [comment]
已修复，等新版本发布吧
