### ISSUE TITLE
能否自行修改head里的meta属性

### ISSUE THREAD

**Issue by wannabing** [jqhph/dcat-admin#1940]
- Laravel Version: 8.75
- PHP Version: 7.4
- Dcat Admin Version: 2.*

### Description:
开发地图选点功能的时候发现地图api的Autocomplete失效，但是在框架外面单独写html测试是有效的，经过两边的请求对比排查发现请求里面的reffer设置引起的（如下图）：
![image](https://user-images.githubusercontent.com/13937883/199140438-5fcbf76b-ac86-4e8b-9a93-bb02fdd7ee5a.png)
![image](https://user-images.githubusercontent.com/13937883/199140485-dfd3e12b-dcf1-4da9-a3ed-562b218638e6.png)

然后看到头部设置了`<meta name="referrer" content="no-referrer">`，最后我这边在当前页面加了js代码修改了它
`$('meta[name="referrer"]').attr('content','strict-origin-when-cross-origin')`
不知道大佬设置no-referrer的是为了哪个功能，我这样改会影响到什么功能？

**Comment by radumro** [comment]
add this to the `config/admin.php`

```   
   /*
    |--------------------------------------------------------------------------
    | Disable Meta Tag named Referer with content="no-referer"
    |--------------------------------------------------------------------------
    |
    | Whether to disable or not the meta name="referer" in the head section
    */
    'disable_no_referrer_meta' => true,
```

if you check the template files in the vendor you can see that the meta tag is inside a condition based on the config file

```
    @if(! config('admin.disable_no_referrer_meta'))
        <meta name="referrer" content="no-referrer"/>
    @endif
```

i do not know why this setting is not by default in the config file

**Comment by answer666** [comment]
> add this to the `config/admin.php`
> 
> ```
>    /*
>     |--------------------------------------------------------------------------
>     | Disable Meta Tag named Referer with content="no-referer"
>     |--------------------------------------------------------------------------
>     |
>     | Whether to disable or not the meta name="referer" in the head section
>     */
>     'disable_no_referrer_meta' => true,
> ```
> 
> if you check the template files in the vendor you can see that the meta tag is inside a condition based on the config file
> 
> ```
>     @if(! config('admin.disable_no_referrer_meta'))
>         <meta name="referrer" content="no-referrer"/>
>     @endif
> ```
> 
> i do not know why this setting is not by default in the config file

hello, 
After I configure it, && php artisan config:clear ,  go check the code， 

{{ dd(config('admin.disable_no_referrer_meta'))  }}  // null

this doesn't work for me.  

<img width="901" alt="image" src="https://github.com/jqhph/dcat-admin/assets/82018243/f0f483c2-2d1e-41b7-9b13-18b8ad876e2a">
<img width="1197" alt="image" src="https://github.com/jqhph/dcat-admin/assets/82018243/6a3da6e9-f114-4076-8ca6-a9db5a523d61">
