### ISSUE TITLE
XSS 漏洞

### ISSUE THREAD

**Issue by lurenbeia** [jqhph/dcat-admin#1942]
- Laravel Version: 8.83.14
- PHP Version: 8.0
- Dcat Admin Version: 2.2.0-beta

### Description:
系统菜单存在 XSS 漏洞。

### Steps To Reproduce:
菜单标题中输入 <script>alert('111')</script> 即可复现

**Comment by parse-code** [comment]
只要不是接受用户输入就行，写在代码里不叫xss漏洞

**Comment by lurenbeia** [comment]
> 只要不是接受用户输入就开始，写在代码里不叫xss漏洞

可能是我没有描述清楚，是后台用户添加菜时，在输入框中输入的。

**Comment by lurenbeia** [comment]
> > 只要不是接受用户输入就开始，写在代码里不叫xss漏洞
> 
> 可能是我没有描述清楚，是后台用户添加菜时，在输入框中输入的。

不好意思，又漏字了，是添加菜单时😓
