### ISSUE TITLE
multipleSelect Save报错 Array to string conversion

### ISSUE THREAD

**Issue by lochen** [jqhph/dcat-admin#195]
- Laravel Version: 6.1
- PHP Version: 7.2
- Dcat Admin Version: 1.4.0

### Description:
$form->width(6)->multipleSelect('country', __('Country'))->options(['SH' => 'SH','BJ'=>'BJ']);

> {
>     "message": "Array to string conversion",
>     "exception": "ErrorException",
>     "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Support/Str.php",
>     "line": 353,
>     "trace": [
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Support/Str.php",
>             "line": 353,
>             "function": "handleError",
>             "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/QueryException.php",
>             "line": 56,
>             "function": "replaceArray",
>             "class": "Illuminate\\Support\\Str",
>             "type": "::"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/QueryException.php",
>             "line": 39,
>             "function": "formatMessage",
>             "class": "Illuminate\\Database\\QueryException",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
>             "line": 665,
>             "function": "__construct",
>             "class": "Illuminate\\Database\\QueryException",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
>             "line": 624,
>             "function": "runQueryCallback",
>             "class": "Illuminate\\Database\\Connection",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
>             "line": 459,
>             "function": "run",
>             "class": "Illuminate\\Database\\Connection",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Connection.php",
>             "line": 411,
>             "function": "statement",
>             "class": "Illuminate\\Database\\Connection",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php",
>             "line": 32,
>             "function": "insert",
>             "class": "Illuminate\\Database\\Connection",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php",
>             "line": 2690,
>             "function": "processInsertGetId",
>             "class": "Illuminate\\Database\\Query\\Processors\\Processor",
>             "type": "->"
>         },
>         {
>             "file": "/Users/XXX/Workspaces/test/src/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php",
>             "line": 1353,
>             "function": "insertGetId",
>             "class": "Illuminate\\Database\\Query\\Builder",
>             "type": "->"
>         },

**Comment by jqhph** [comment]
你可以使用模型修改器转换下数据格式，也可以参考这篇文章中的方法 https://learnku.com/articles/44386
