### ISSUE TITLE
图片组件编辑提交后文件被删除

### ISSUE THREAD

**Issue by jin-null** [jqhph/dcat-admin#1956]
- Laravel Version: 9.19
- PHP Version: 8.1.2
- Dcat Admin Version: 2.*

### Description:
图片上传组件 自动上传后 文件存储目录下有文件 ，提交后文件被删除
### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/9098750/204423327-dafc089c-8510-4fc7-ae55-6d1a26e26162.png)
![image](https://user-images.githubusercontent.com/9098750/204423362-3766c235-6b64-48ce-acc8-8d72b928f20f.png)
提交后
![image](https://user-images.githubusercontent.com/9098750/204423517-cb916b63-0b34-484c-bb86-4c8d21228f6a.png)

**Comment by hetoo** [comment]
不要在模型设置 getXXXAttribute XXX为上传图片字段

**Comment by trkjoy** [comment]
这个问题有解决么? 目前遇到同样的问题

**Comment by trkjoy** [comment]
找到问题了- 使用 retainable (开启这个功能之后文件将不会从服务器删除)
