### ISSUE TITLE
How to redirect in form edit?

### ISSUE THREAD

**Issue by lochen** [jqhph/dcat-admin#196]
> if($form->model()->status=="DONE"){
>                 return redirect('admin/order');
>             }

这样转跳会空白

>  $form->text('order_no')->required();
>  $form->editing(function(Form $form) {
>        $form->text('order_no')->disable()
> });

怎样在编辑页時disable 某个栏位?

谢

**Comment by jqhph** [comment]
表单提交是`ajax`请求接口，不支持redirect函数跳转，如果要跳转请参考文档表单事件。

编辑时disable可以参考下面的代码，这些文档中都有
```php
if ($form->isEditing()) {
   ...
}
```

**Comment by lochen** [comment]
`protected function form()
    {

        return Form::make(new Order(), function (Form $form) {
            $form->isEditing(function (Form $form) {
                if($form->model()->status=="PENDING"){
                    return redirect('admin/order');
                }
            });
`
不行

**Comment by jqhph** [comment]
同学，仔细看文档editing事件不能用跳转明白吗？你这个需求需要在控制器的edit方法使用redirect函数
