### ISSUE TITLE
Expand 手风琴效果，双击的时候会出现问题

### ISSUE THREAD

**Issue by f-wangbaoshi** [jqhph/dcat-admin#1968]
- Laravel Version: 8.0
- PHP Version: 7.4.7
- Dcat Admin Version: 1.7

### Description:
form Expand
Expand 手风琴弹出来，如果是双击而不是单机 那么 弹出和 弹回 就会失效，弹出来就会立刻消失的bug

**Comment by f-liutao** [comment]
我也遇到了同样的问题,求修复

**Comment by fenrir-baoshi** [comment]
sorry 我也在偷懒，没有修复，等着看看有没有其他人有修复好的 直接用一下。😄
------------------------------------------------------------------
发件人：f-liutao ***@***.***>
发送时间：2023年1月4日(星期三) 16:08
收件人：jqhph/dcat-admin ***@***.***>
抄　送：王宝石 ***@***.***>; Author ***@***.***>
主　题：Re: [jqhph/dcat-admin] Expand 手风琴效果，双击的时候会出现问题 (Issue #1968)
我也遇到了同样的问题,求修复
