### ISSUE TITLE
图片上传后，点击保存会报错

### ISSUE THREAD

**Issue by codecodify** [jqhph/dcat-admin#197]
- Laravel Version: 7.0.0
- PHP Version: 7.2.#
- Dcat Admin Version: 1.4.#

### Description:
后台使用阿里云oss存储，在图片组件上点击上传可以正常上传图片并保存到数据库中，但是点击表单下面的提交按钮会报错，
`exception: "OSS\Core\OssException"
file: "D:\laragon\www\tenant\vendor\aliyuncs\oss-sdk-php\src\OSS\Core\OssUtil.php"
line: 226
message: "object name is empty"`

**Comment by codecodify** [comment]
已解决，不能使用图片访问器

**Comment by jqhph** [comment]
删除掉模型中的图片字段访问器
```php
public function getImageAttribute($value)
{
    return ...
}
```

更改成
```php
public function getImage()
{
    return ...
}
```
