### ISSUE TITLE
多应用的时候扩展使用多表有问题

### ISSUE THREAD

**Issue by seth-shi** [jqhph/dcat-admin#1979]
- Laravel Version: 9.33.0
- PHP Version: 8.0.26
- Dcat Admin Version: 2.2.2

### Description:
app 多应用切换是在中间件切换的,
假如我新应用 admin-xxx 的扩展表自定义表名是`admin_xx_extensions`表
但是扩展的数据获取是在 boot 启动的, 那时候还没有`switch app`, 会导致获取默认的扩展表数据

这个影响太大, 没改直接改. 估计得换一下启动流程

**Comment by chenjiabin** [comment]
@seth-shi 请问一下， 有解决方案么

**Comment by seth-shi** [comment]
> @seth-shi 请问一下， 有解决方案么

直接改源码启动流程
