### ISSUE TITLE
是不是停止更新了这个项目

### ISSUE THREAD

**Issue by ljyljy0211** [jqhph/dcat-admin#1980]
是不是停止更新了这个项目

**Comment by nyufeng** [comment]
beta 版一直在更新呀。https://learnku.com/docs/dcat-admin/2.x/beta-version-update-log/

**Comment by ljyljy0211** [comment]
> beta 版一直在更新呀。https://learnku.com/docs/dcat-admin/2.x/beta-version-update-log/

2022年了

**Comment by jqhph** [comment]
会持续维护哈，本周会发布新版本，支持laravel10

**Comment by bigbug-gg** [comment]
我要成为 laravel10 版本第一批用户 @jqhph

**Comment by licesun** [comment]
说好的新版本呢？

**Comment by jqhph** [comment]
> 说好的新版本呢？

有些事耽搁了，在准备了哈

**Comment by kpsanmao** [comment]
2 weeks ago

**Comment by imydou** [comment]
half year ago

**Comment by PuAlbert** [comment]
one year ago

**Comment by ljyljy0211** [comment]
一年半了，😄，看来得换一个了

**Comment by PuAlbert** [comment]
兄弟们， 现在都在用哪个

**Comment by imydou** [comment]
laravel-admin 也不更了。filamentphp好像还行，不支持2级以上菜单，别的还在看

**Comment by kpsanmao** [comment]
实在不行我下个项目准备换 fastadmin 了。

**Comment by yutao8** [comment]
2024 10. 9

**Comment by cityisempty** [comment]
> laravel-admin 也不更了。filamentphp好像还行，不支持2级以上菜单，别的还在看

filamentphp   菜单的确是个问题，但是总体设计还行，不行可以分panel 啊

**Comment by MustangZhong** [comment]
@jqhph  老哥~ 要是没时间维护，可以公开给社区共同维护呀
