### ISSUE TITLE
Laravel 10 release support

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#1981]
- Laravel Version: 10
- PHP Version: 8.1

**Comment by jqhph** [comment]
最近会更新哈

**Comment by faydanube** [comment]
> 最近会更新哈

thanks.

**Comment by faydanube** [comment]
> 最近会更新哈

1, would you consider using a relaxed versioning policy in composer?
2, Is it possible to just do a compatibility upgrade with fatal bug fixes and keep the latest stable version available?

Most version upgrades do not have many destructive changes and can be done almost without any compatibility upgrades, all my old projects have been upgraded from 9 to 10 with almost no changes.

I know I shouldn't ask for more, but I hope the project gets better and better, or at least stable!

**Comment by uyson** [comment]
什么时候发布新版本？  我也想升级L10

**Comment by kisexu** [comment]
@jqhph 

我看当前仓库里 `composer.json` 文件的依赖已经支持 Laravel 10.0 了，但是 `packagist.org` 上还没更新最新版本。

**Comment by alipeng** [comment]
> @jqhph
> 
> 我看当前仓库里 `composer.json` 文件的依赖已经支持 Laravel 10.0 了，但是 `packagist.org` 上还没更新最新版本。

composer require dcat/laravel-admin:2.0.x-dev -vvv

开发分支

**Comment by kisexu** [comment]
> > @jqhph
> > 我看当前仓库里 `composer.json` 文件的依赖已经支持 Laravel 10.0 了，但是 `packagist.org` 上还没更新最新版本。
> 
> composer require dcat/laravel-admin:2.0.x-dev -vvv
> 
> 开发分支

谢谢，没注意到还有 dev 分支
