### ISSUE TITLE
为什么后台控制器HomeController不是继承AdminController？

### ISSUE THREAD

**Issue by yangrongzhou** [jqhph/dcat-admin#1985]
- Laravel Version: 10.0.3
- PHP Version: 8.1.14
- Dcat Admin Version: 2.0.x-dev

###  为什么后台控制器HomeController不是继承AdminController？
通过Dcat脚手架生成的控制器都是继承 `Dcat\Admin\Http\Controllers\AdminController`，
唯独现存的控制器 `App\Admin\Controllers\HomeController` 继承了 `App\Http\Controllers\Controller`，而 `App\Http\Controllers\Controller` 是前台控制器基类。
将HomeController修改继承自 `Dcat\Admin\Http\Controllers\AdminController`，其功能并无影响，希望作者统一。

**Comment by nyufeng** [comment]
`AdminController`  实现了列表/详情/新建/编辑/删除 的接口 `HomeController` 并不需要这些东西。

**Comment by yangrongzhou** [comment]
> `AdminController` 实现了列表/详情/新建/编辑/删除 的接口 `HomeController` 并不需要这些东西。

如果是这个原因的话，HomeController继承`Illuminate\Routing\Controller`会更好吧，因为`App\Http\Controllers\Controller`作为前台控制器基类，我们通常会加上一些公共属性、方法，而后台是用不到的。

**Comment by nyufeng** [comment]
> > `AdminController` 实现了列表/详情/新建/编辑/删除 的接口 `HomeController` 并不需要这些东西。
> 
> 如果是这个原因的话，HomeController继承`Illuminate\Routing\Controller`会更好吧，因为`App\Http\Controllers\Controller`作为前台控制器基类，我们通常会加上一些公共属性、方法，而后台是用不到的。

`HomeController` 更像是一个示例，教你如何创建单页面。实际用的过程中继承关系需要你自己构思。`App\Http\Controllers\Controller` 也可以派生出去 前台与后台的对应及基类，后台也有写单页面的需求。
