### ISSUE TITLE
表单上传图片，将图片路径保存在另一张表里，如何让当前的表不保存图片ID？

### ISSUE THREAD

**Issue by chyj4747** [jqhph/dcat-admin#1993]
第1张表：食物
字段：id，name

第2张表：食物图片
字段：id，food_id，img

需求：每种食物对应多张图片，图片上传后，路径保存在表“食物图片”的img字段，同时food_id对应到表“食物”的id

看文档里的用法，只能是在表“食物”中建一个类似img_id的字段，图片上传后，把图片id填入img_id，但我想使用上述方式实现一对多，能做到吗？

**Comment by licesun** [comment]
这个属于关联关系中的一对多，请仔细阅读laravel 中关于这部分的描述，dcat-admin 文档中也有相应的解释。
