### ISSUE TITLE
Trait 'Dcat\EasyExcel\Support\Traits\Macroable' not found

### ISSUE THREAD

**Issue by BrianBi** [jqhph/dcat-admin#2]
vendor/dcat/laravel-admin/src/Widgets/Form.php
引用的这个Trait Dcat\EasyExcel\Support\Traits\Macroable不存在呢，是还没更新吗

**Comment by BrianBi** [comment]
应该把dcat/easy-excel加到依赖中的，给我一顿找

**Comment by jqhph** [comment]
目前尚未发版，通过composer安装的可能不是最新的代码。建议把master分支的代码clone到本地安装。

dcat/easy-excel是作为选用功能使用不太适合加入到依赖，只有在使用默认的导出功能时需要用到，用户可以自定义。
