### ISSUE TITLE
laravel10什么时候可以升级好呀?

### ISSUE THREAD

**Issue by lifetin** [jqhph/dcat-admin#2006]
非常期待.

**Comment by kpsanmao** [comment]
现在就可以吧，我新项目就在laravel 10下用的啊。

**Comment by lifetin** [comment]
你是新安装的吧?

**Comment by alipeng** [comment]
> 你是新安装的吧?

composer require dcat/laravel-admin:2.0.x-dev -vvv

**Comment by maxwellMyX** [comment]
php artisan admin:install 执行会报错
