### ISSUE TITLE
批量操作，弹出的工具表单，怎么获取被选中的行呢？

### ISSUE THREAD

**Issue by jasonencode** [jqhph/dcat-admin#2007]
- Laravel Version: 10.x
- PHP Version: 8.2
- Dcat Admin Version: 2.2.2

### Description:

批量操作，弹出的工具表单，怎么获取被选中的行呢？
说是有个demo，链接已失效了

**Comment by PorygonCN** [comment]
![image](https://github.com/jqhph/dcat-admin/assets/31176914/8080f6bc-393c-4c17-bd60-78dcbb78f61c)
