### ISSUE TITLE
Undefined variable: configData

### ISSUE THREAD

**Issue by leetotti** [jqhph/dcat-admin#202]
- Laravel Version: 5.8
- PHP Version:7.1
- Dcat Admin Version: 1.4

### Description:
Undefined variable: configData (View: /var/www/aj_vote/vendor/dcat/laravel-admin/resources/views/partials/sidebar.blade.php)

**Comment by jqhph** [comment]
卸载一切laravel-admin相关插件，如果你是从laravel-admin迁移过来的项目，配置文件需要重新生成，可以参考下这篇文章 https://learnku.com/articles/44235

**Comment by leetotti** [comment]
直接安装的  然后增加了 laravel-modules  就这样了

**Comment by jqhph** [comment]
本身就有多后台功能，你不需要laravel-modules，可能不兼容吧

**Comment by leetotti** [comment]
因为要把一些功能做成多个模块

**Comment by leetotti** [comment]
重新做了一次  又没有出现问题了
