### ISSUE TITLE
操作列怎么能展开显示，默认的是三个圆点

### ISSUE THREAD

**Issue by singi2016cn** [jqhph/dcat-admin#2023]
- Laravel Version: 8.83.27
- PHP Version: 7.4
- Dcat Admin Version: 2.2.2

### Description:
操作列怎么能展开显示，默认的是三个圆点，需要点一下才能看到操作。能否默认就展示，这样可以免除点击一次。

**Comment by phplaoyao** [comment]
$grid->setActionClass(Grid\Displayers\Actions::class);
