### ISSUE TITLE
尊敬的开发者您好，发现一处小问题，会加一个 "&nbsp;"  符号

### ISSUE THREAD

**Issue by wenhainan** [jqhph/dcat-admin#2024]
- Laravel Version: 8.x
- PHP Version: 7.4
- Dcat Admin Version: 2.x

### Description:
如图
http://cdn.waytomilky.com/QQ%E6%88%AA%E5%9B%BE20230509212531.png

show一个字段，会加一个 &nbsp； 符号

### Steps To Reproduce:

会导致用户复制的时候，多出一个无用字符。

**Comment by lokpui** [comment]
form 中的 display field也能這樣解決
