### ISSUE TITLE
Dcat-Admin Version<= 2.1.3-beta XSS Vulnerability

### ISSUE THREAD

**Issue by GgBoom-993** [jqhph/dcat-admin#2027]
- Laravel Version: 8.83.14
- PHP Version: 7.1
- Dcat Admin Version: 2.1.3-beta

### Description:
Dcat Admin Version: <= 2.1.3-beta have an Stored XSS vulnerability. Attackers can use the vulnerability to maintain permissions and steal credentials

### Steps To Reproduce:
We can change the logo or other image's file_url to trigger JS code injection. This feature applies to all versions of dcat-admin

![image](https://github.com/jqhph/dcat-admin/assets/55505202/440d1220-da8a-4591-8001-74952dea9bb4)

When we submit a request to insert malicious code, refreshing the page triggers the effect
![image](https://github.com/jqhph/dcat-admin/assets/55505202/4bd4ec42-a4ad-4c42-b3e7-75b860401d73)

**Comment by androiddisk** [comment]
请问有办法解决么
