### ISSUE TITLE
按手册安装完成后访问首页报symfony\console内的warning，127.0.0.1:[port]/admin访问报404

### ISSUE THREAD

**Issue by xiaochujie** [jqhph/dcat-admin#203]
- Laravel Version: 6.18.19
- PHP Version: 7.2.9
- Dcat Admin Version: 1.4

### Description:
感谢大佬开发出这么好用并且颜值这么高的后台构建工具。
我在按照官方手册一步步安装完遇到两个问题。请大佬解答一下，谢谢！
安装官方文档步骤安装完成并启动后，首页报警告
Warning: array_shift() expects parameter 1 to be array, null given in 
*\dcat-admin\vendor\symfony\console\Input\ArgvInput.php on line 56

Warning: Invalid argument supplied for foreach() in 
*\dcat-admin\vendor\symfony\console\Input\ArgvInput.php on line 282

另外在windows版的phpstudy8配置好网站后，首页可以正常访问，但是通过127.0.0.1:8848/admin访问就报404，而通过php artisan serve启动php自带的web服务器就可以通过127.0.0.1:8000/admin访问。

**Comment by jqhph** [comment]
你确定这个是首页的报错？看这个错误信息是命令行的错误，另外这么少的信息我无法判断是哪里有问题，请详细描述你的操作步骤以及贴上完整的错误报文。

phpstudy访问404很可能是伪静态的原因，建议你百度一下laravel项目的web配置方法。

**Comment by xiaochujie** [comment]
这个是报错截图&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jiang Qinghua"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午9:39
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"肖楚杰"<1484243756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 按手册安装完成后访问首页报symfony\console内的warning，127.0.0.1:[port]/admin访问报404 (#203)





 
你确定这个是首页的报错？看这个错误信息是命令行的错误，另外这么少的信息我无法判断是哪里有问题，请详细描述你的操作步骤以及贴上完整的错误报文。
 
phpstudy访问404很可能是伪静态的原因，建议你百度一下laravel项目的web配置方法。

**Comment by xiaochujie** [comment]
就运行了这几个命令，首页也是这个错误





------------------ 原始邮件 ------------------
发件人:&nbsp;"Jiang Qinghua"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午9:39
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"肖楚杰"<1484243756@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 按手册安装完成后访问首页报symfony\console内的warning，127.0.0.1:[port]/admin访问报404 (#203)





 
你确定这个是首页的报错？看这个错误信息是命令行的错误，另外这么少的信息我无法判断是哪里有问题，请详细描述你的操作步骤以及贴上完整的错误报文。
 
phpstudy访问404很可能是伪静态的原因，建议你百度一下laravel项目的web配置方法。

**Comment by jqhph** [comment]
什么都看不到，建议你花几十分钟看看这个[laravel入门教程](https://github.com/johnlui/Learn-Laravel-5)

**Comment by xiaochujie** [comment]
邮件看不到图片吗=.=||，好吧
配置了伪静态就可以了
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
用php artisan serve启动的，会报那个错误。用nginx的是正常的。谢谢大佬
