### ISSUE TITLE
搜索框select的ajax好像不生效

### ISSUE THREAD

**Issue by SedgeWarbler** [jqhph/dcat-admin#2033]
已经解决了

**Comment by Mr-wangwei** [comment]
请教一下怎么解决的？我也遇到了同样的问题

**Comment by Quekie** [comment]
坑啊 ajax ，文档没有提到 必须要分页 格式为：`{
    "total": 4,
    "per_page": 15,
    "current_page": 1,
    "last_page": 1,
    "next_page_url": null,
    "prev_page_url": null,
    "from": 1,
    "to": 3,
    "data": [
        {
            "id": 9,
            "text": "xxx"
        },
        {
            "id": 21,
            "text": "xxx"
        },
        {
            "id": 42,
            "text": "xxx"
        },
        {
            "id": 48,
            "text": "xxx"
        }
    ]
}`
