### ISSUE TITLE
Dcat Admin 动态显示的表单，提交时没有值

### ISSUE THREAD

**Issue by fishshadower** [jqhph/dcat-admin#2036]
- Laravel Version: 8.83.27
- PHP Version: 7.3
- Dcat Admin Version: 2.2.2

### Description:

我使用 Form::make 生成表单，部分表单的显示通过 URL 的参数显示，例如参数 category_id=1 就显示某个表单，实现动态表单功能。

简化代码如下：
其中 warehouse_report 字段并不存在于模型 Lease 中，而是自行设置的。

```php
protected function form()
    {
        return Form::make(\App\Models\Lease::class, function (Form $form) {
            $categoryId = request()->get('category_id');
            if ($categoryId == 1) {
                $form->multipleImage('warehouse_report', '验证报告')->autoUpload()->uniqueName();
            }
   });
    }
```
## 问题
我在没有使用 if 条件判断的时候，加载出页面，上传图片，提交表单，提交载荷中存在 warehouse_report 字段和它的值，但是使用 if 后，先设置 URL 中参数为 2（不显示表单），后来设置成 1（显示表单），此时上传图片提交内容，载荷中 warehouse_report 字段的值就是空的
为什么会这样呢？怎么才能表单有值？

## 截图
无判断
![image](https://github.com/jqhph/dcat-admin/assets/47311591/d4fc1dc5-2d33-4679-86a8-8d385669107f)

有判断
![image](https://github.com/jqhph/dcat-admin/assets/47311591/0b2f92a8-e733-43ad-9a89-3a29a2e82a46)

PS：为什么不用 when 做动态表单？
因为表单是必填的，提交时没有使用的隐藏表单会阻碍提交，且有同名 column 提交问题。

**Comment by fankiewing** [comment]
老哥可以参考一下我的万能表单做法：
![image](https://github.com/jqhph/dcat-admin/assets/47618346/95f0c34f-e55e-4186-98bd-d1192b3473c1)

实现过程中我也发现过某些情况下传参为空的现象（设置了某个form字段disable，因为不能修改）
![image](https://github.com/jqhph/dcat-admin/assets/47618346/4c4d9109-811e-4232-b34c-8e2e6a5c962d)
解决方法如下：
![image](https://github.com/jqhph/dcat-admin/assets/47618346/106c07bd-a59a-4f2c-8ae7-470115644c49)
