### ISSUE TITLE
multipleSelect 多选是否可以按照顺序选择？

### ISSUE THREAD

**Issue by ajaxcom** [jqhph/dcat-admin#2045]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

下拉框中  如果有2的情况，在选择1 [1,2] 1会跑到2前面
[2]                          
1---------
2---------
3---------

**Comment by pgyf** [comment]
同问

**Comment by phplaoyao** [comment]
我尝试了几个方法没成功 最后使用的NestedForm $table 形式实现多项排序

**Comment by easylolicon** [comment]
同问
