### ISSUE TITLE
【功能建议】为什么没有对表格的表头增加固定表格头部的功能？

### ISSUE THREAD

**Issue by youlinstar** [jqhph/dcat-admin#2050]
- Laravel Version: 9.52.8
- PHP Version: 8.1.0
- Dcat Admin Version: 2.2.2-beta

### Description: 

我认为在后台管理框架中，表格头部的那行，增加一个可固定的选项是个非常重要的
在日常后台表格内容展示的时候，通常表格内数据都是数字，而判断这个数字的依据则是依靠表格的头部那行
![image](https://github.com/jqhph/dcat-admin/assets/94352609/6ab81d41-d5b9-4761-b9af-060d7013be2e)
![image](https://github.com/jqhph/dcat-admin/assets/94352609/db0c14ee-bb21-4fe2-ba6a-2e7e6a1be6b1)

比如这个表格，如果数据很多很长，那么表头那行就必须要固定，否则都不知道里面的数据是啥

### 目前我的解决方案：
![image](https://github.com/jqhph/dcat-admin/assets/94352609/91e01bbc-6f13-4296-9eb5-dc2dbf5b372e)
```php
Admin::style(
            <<<CSS
tbody {
            display: block;
            max-height: 500px;
            overflow-y: scroll;
        }
        /*设置头与内容自动对齐*/
        table thead,tfoot,tbody tr {
            display: table;
            table-layout: fixed;
            /*来自coding的添加*/
            width:  100%;
            word-wrap:  break-word;
        }
        /*给滚动条预留宽度*/
        table thead,tfoot {
            width: calc( 100% - 1em);
            background: #EFF0F5;
        }
CSS
        );
```
只不过这种方案是现在表格的大小，而达到固定表头的

期待官方能够给出更好的优解

同样，我发现两个同样问题的issues 
#1276 
#1315

**Comment by taotecode** [comment]
**换个号回复一下**
# 个人方法解决
## 方案一【CSS解决】
```php
Admin::style(
            <<<CSS
tbody {
            display: block;
            /*设置表格内部容器高度*/
            max-height: 500px;
            overflow-y: scroll;
        }
        /*设置头与内容自动对齐*/
        table thead,tfoot,tbody tr {
            display: table;
            table-layout: fixed;
            /*来自coding的添加*/
            width:  100%;
            word-wrap:  break-word;
        }
        /*给滚动条预留宽度*/
        table thead,tfoot {
            width: calc( 100% - 1em);
            background: #EFF0F5;
        }
CSS
        );
```
### 预览
![image](https://github.com/jqhph/dcat-admin/assets/48904825/9f1e6502-cd60-4190-abd0-31853d3c7522)
![image](https://github.com/jqhph/dcat-admin/assets/48904825/d5b54bca-ba7e-47b7-b542-33a7dd117bf7)
## 方案二【JS解决】
```php
Admin::script(
            <<<JS
document.querySelector("#grid-table > thead").classList.add("sticky-top");
document.querySelector("#grid-table > thead").style.top = "0px";
//获取顶部导航的高度
var navHeight = document.querySelector("body > div.wrapper > nav").offsetHeight;
// 设置#grid-table > thead的top值
document.querySelector("#grid-table > thead").style.top = navHeight + "px";
// 设置#grid-table > thead的背景色为白色
document.querySelector("#grid-table > thead").style.backgroundColor = "#fff";
// 给#grid-table > thead添加顶部阴影
document.querySelector("#grid-table > thead").style.boxShadow = "rgba(0, 0, 0, 0.12) 0px -2px 1px 0px";
JS
);
```
### 预览
![image](https://github.com/jqhph/dcat-admin/assets/48904825/b2ac00e1-b2d3-4885-b1f9-59e5081022f3)
![image](https://github.com/jqhph/dcat-admin/assets/48904825/070e967e-6170-480c-a615-d064472d5b09)

**Comment by w344701119** [comment]
我也遇到了这个问题，用了固定表头的的css，但是有个问题，当列超出时候才能固定其他的不行
这种可以
![image](https://github.com/jqhph/dcat-admin/assets/18592220/b5367f7f-286f-43cc-b61a-e28bf1ff3995)
这种屏幕刚好够长的就不行，不知道有没有人遇到同样的问题！是怎么解决的，谢谢
![image](https://github.com/jqhph/dcat-admin/assets/18592220/9ee1bf65-cc42-4239-ade2-bcfd8c41a7be)
