### ISSUE TITLE
表单滑块条怎么用啊？BUG

### ISSUE THREAD

**Issue by suzhiF** [jqhph/dcat-admin#2051]
![image](https://github.com/jqhph/dcat-admin/assets/46362400/77293a6b-24f3-4ecb-aa64-8cb653ee1dfb)
![image](https://github.com/jqhph/dcat-admin/assets/46362400/d3c65fc0-8f9d-4ebf-b6a9-0102a43e16e5)
![image](https://github.com/jqhph/dcat-admin/assets/46362400/45f0e0dd-6635-487a-8ec9-b4ab47f2d703)

**Comment by phplaoyao** [comment]
帖上代码来看看
