### ISSUE TITLE
本机架设后反代出外网 加入https后  后台无法访问，postman get后台地址报错Error: socket hang up

### ISSUE THREAD

**Issue by oppsDayly** [jqhph/dcat-admin#2052]
- Laravel Version: 9
- PHP Version: 8.1
- Dcat Admin Version: 2.*

### Description:
服务器本地架设127.0.0.1
未启用https时服务器本机访问127.0.0.1前后台均正常

然后代理改服务器地址后，代理服务器启用了https，无论是否在config/admin.php中开启https     外网域名+httpsd均访问不了后台postman get后台地址报错Error: socket hang up

**Comment by dreamdesky** [comment]
这看起来是代理的锅，要不你排除下：只用一个简单的 php 文件，内容 echo ‘hello world!’ ，看看是否会报错。

**Comment by oppsDayly** [comment]
找到原因了，不知道是不是一个bug   在后台开启https后    用https键入后台  程序会location 跳转到http，然而代理未开启http访问   所以导致无法访问。
