### ISSUE TITLE
laravel9.19安装失败

### ISSUE THREAD

**Issue by WangQuanTang** [jqhph/dcat-admin#2062]
- Laravel Version: 9.19
- PHP Version: 8.0.9
- Dcat Admin Version: 2.*

### Description:
安装提示：
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires dcat/laravel-admin 2.*, found dcat/laravel-admin[2.0.0-beta, 2.0.1-beta, 2.0.2-beta, 2.0.3-beta, 2.0.4-beta, 2.0.5-beta, 2.0.6-beta, 2.0.7-beta, 2.0.8-beta, 2.0.9-beta, 2.0.10-beta, 2.0.11-beta, 2.0.12-beta, 2.0.13-beta, 2.0.14-beta, 2.0.15-beta, 2.0.16-beta, 2.0.17-beta, 2.0.18-beta, 2.0.19-beta, 2.0.20-beta, 2.0.21-beta, 2.0.22-beta, 2.0.23-beta, 2.0.24-beta, 2.0.x-dev, 2.1.0-beta, 2.1.1-beta, 2.1.2-beta, 2.1.3-beta, 2.1.4-beta, 2.1.5-beta, 2.1.6-beta, 2.1.7-beta, 2.2.0-beta, 2.2.1-beta, 2.2.2-beta] but it does not match your minimum-stability.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.

```
根据这篇文章：
[laravel 8.32无法安装dcat-admin 2.x](https://github.com/dcat-admin/docs/issues/46)的方法，去掉`"prefer-stable": true`后依旧提示错误。
删除`composer.lock`后运行`composer clearcache`清除缓存，再`composer update`后生成`composer.lock`再安装依旧提示上述错误。
尝试指定版本：
```
composer require dcat/laravel-admin:"2.2.2-beta*"

```
安装成功，但是在`config/app.php`中修改语言配置为：`local => zh_CN`后语言配置不生效。
最后尝试更换源也是一样报错。

### 总结:
问题1：按照文档流程安装提示`Your requirements could not be resolved to an installable set of packages`。
问题2：指定特定版本后，语言配置不生效。

**Comment by QQOQ** [comment]
composer.json里把`minimum-stability`的值改为`dev`
