### ISSUE TITLE
会一直请求数据库，执行 select * from `am_admin_extensions，是怎么回事呢

### ISSUE THREAD

**Issue by jiangzhangy** [jqhph/dcat-admin#2063]
- Laravel Version: 10.x.x
- PHP Version: 8.2.x
- Dcat Admin Version: 2.2.

### Description:
只要有请求过来，Dcat就是会执行一次 ‘select * from `am_admin_extensions’，这样的sql 查询 

### 期望
查找原因并修复一下，谢谢

**Comment by jiangzhangy** [comment]
我顺着摸下去，发现/vendor/dcat/laravel-admin/src/Extend/Manager.php 文件第441行有如下代码：
public function settings()
    {
        if ($this->settings === null) {
            try {
                $this->settings = ExtensionModel::all()->keyBy('name');
            } catch (\Throwable $e) {
                $this->reportException($e);

                $this->settings = new Collection();
            }
        }

        return $this->settings;
    }
    这以为着每次进入框架都会去查库吗？

**Comment by dreamdesky** [comment]
我们已经解决这个问题了，看这里：https://github.com/shanjing-inc/dcat-admin/commit/45d9a3460683137c09ad673cfdbf9cc269b4c9e9
