### ISSUE TITLE
$form->switch異常

### ISSUE THREAD

**Issue by mbdmt** [jqhph/dcat-admin#2065]
- Laravel Version: 8.#.#
- PHP Version: 7.4.#
- Dcat Admin Version: 2.2.2

### Description:

有時候這個switch一開始載入頁面 圖片會跑掉 如圖
編輯狀態設1 圖片卻是關閉
$form->switch('active')->default('1',true);

[https://upload.cc/i1/2023/08/03/nKypqb.jpg](https://upload.cc/i1/2023/08/03/nKypqb.jpg)

**Comment by laradocs** [comment]
不太明白你的要表达的意思

**Comment by mbdmt** [comment]
> 不太明白你的要表达的意思

就是预设开启的情况
圆点应该在右边且篮底
出问题的情况是进页面圆点在左边一样篮底
正常就算是关闭 也应该是白底
但点击保存一样是开没错
感觉js错乱
刷新页面会正常
但客户看着碍眼
