### ISSUE TITLE
字段列过滤器 filter() 与 异步加载async() 冲突，无法弹出列筛选的弹出层

### ISSUE THREAD

**Issue by xushenjie** [jqhph/dcat-admin#2066]
- Laravel Version: 10.15.0
- PHP Version: 8.1.20
- Dcat Admin Version: 2.*

### Description:
Laravel 10 使用列过滤器，点击过滤图标，无反应

### Steps To Reproduce:

<img width="1405" alt="image" src="https://github.com/jqhph/dcat-admin/assets/24131249/7a957f29-b44f-4fa7-87d1-c40b4e9a0504">
<img width="386" alt="image" src="https://github.com/jqhph/dcat-admin/assets/24131249/3397f5da-d654-4efc-be28-82a9bedec14b">

**Comment by laradocs** [comment]
请参考文档：[异步渲染 | 数据表格  |《Dcat Admin 中文文档 2.x》](https://learnku.com/docs/dcat-admin/2.x/asynchronous-rendering/11051)

### 表格异步渲染

当页面的表格展示的数据特别多（列多行多），并且加载的组件也较多时，可能会出现卡顿的现象，此时可以使用表格异步渲染功能，可以有效地减轻页面卡顿的情况：

```php
// 启用表格异步渲染功能
$grid->async();

// 禁用
$grid->async(false);

// 判断是否是异步渲染请求
if ($grid->isAsyncRequest()) {
    ...
}
```

> 需要注意的是，如果页面没有出现明显的卡顿现象，则无需启用此功能；并且如果页面中存在多个数据表格，那么也无法使用此功能。

开启此功能之后，表格工具栏 (toolbar) 以下的位置都会采用异步的方式进行渲染，换句话说，工具栏 (toolbar) 以及以上的位置只会刷新一次！在实际编码过程中需要注意有无特殊影响。
