### ISSUE TITLE
自定义页面 关于js渲染html没有闭合标签的问题

### ISSUE THREAD

**Issue by SedgeWarbler** [jqhph/dcat-admin#2067]
通过 $column->row(admin_view('admin.home.customer.overview')); 写了一个自定义页面

但是在自定义页面中<script>写html是没有闭合标签的
所以导致渲染到页面的时候也是没有闭合标签

基本上所有标签都会有这个问题，可以麻烦解决一下嘛

![QQ图片20230812163610](https://github.com/jqhph/dcat-admin/assets/32641989/9b46cffe-eeee-4feb-8ce3-88a3bdaf81c3)

**Comment by mengdodo** [comment]
把脚本提取到单独的js文件
