### ISSUE TITLE
Laravel10兼容吗

### ISSUE THREAD

**Issue by sw586** [jqhph/dcat-admin#2075]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by carlmama** [comment]
我已安裝在Laravel 10.22可運作，有些相容性問題自行修正一下就好

**Comment by marcoyan0814** [comment]
PHP v8.1.21
Laravel v10.21.1
Dcat Admin v2.2.2-beta
用一段時間了，沒遇到什麼大問題

**Comment by sw586** [comment]
谢谢

**Comment by masterwto** [comment]
> PHP v8.1.21 Laravel v10.21.1 Dcat Admin v2.2.2-beta 用一段時間了，沒遇到什麼大問題

请问如何安装？求知道

**Comment by marcoyan0814** [comment]
> > PHP v8.1.21 Laravel v10.21.1 Dcat Admin v2.2.2-beta 用一段時間了，沒遇到什麼大問題
> 
> 请问如何安装？求知道

https://learnku.com/docs/dcat-admin/2.x/install/8081
如果是Laravel10以下的話，基本上照著官方文件操作就可以了，Laravel 11的話目前應該還不支援
