### ISSUE TITLE
请教一下，如何监听页面跳转

### ISSUE THREAD

**Issue by whx** [jqhph/dcat-admin#2083]
我在一个数据表格页面加了一段js，我希望在跳转到别的页面的时候执行另一段js。由于是单页应用，所以常规的onbeforeunload事件不会触发，我现在的办法是在js里面监听页面特定的元素来判断是否已经跳转了页面。请教各位大佬，有没有更优雅的办法实现这一功能

**Comment by PorygonCN** [comment]
可以查询一下pjax的事件 其中包括点击 加载等相关事件 应该满足你的需求

**Comment by qiaohs** [comment]
```
Dcat.onPjaxLoaded(function(){
    console.log(1);
});
```
