### ISSUE TITLE
array_merge(): Argument #1 must be of type array, string given

### ISSUE THREAD

**Issue by zyenggook** [jqhph/dcat-admin#2087]
- Laravel Version: 10.10.#
- PHP Version: 8.2.#
- Dcat Admin Version:2.2.3-beta

### Description:
`     if ($variables !== null) {

            static::context()->jsVariables = array_merge(

                $jsVariables,

                $variables

            );

            return;

        }

        $sidebarStyle = config('admin.layout.sidebar_style') ?: 'light';

        $pjaxId = static::getPjaxContainerId();

        $jsVariables['pjax_container_selector'] = $pjaxId ? ('#'.$pjaxId) : '';

        $jsVariables['token'] = csrf_token();

        $jsVariables['lang'] = ($lang = __('admin.client')) ? array_merge($lang, $jsVariables['lang'] ?? []) : [];

        $jsVariables['colors'] = static::color()->all();

        $jsVariables['dark_mode'] = static::isDarkMode();

        $jsVariables['sidebar_dark'] = config('admin.layout.sidebar_dark') || ($sidebarStyle === 'dark');

        $jsVariables['sidebar_light_style'] = in_array($sidebarStyle, ['dark', 'light'], true) ? 'sidebar-light-primary' : 'sidebar-primary';

        return admin_javascript_json($jsVariables);

    }

`

### Steps To Reproduce:
大佬啥时候适配一下laravel10版本~切换回9.*不报错

**Comment by zhangchunsheng** [comment]
不解决了？

**Comment by Youngkingoo6** [comment]
临时解决方案：
1、先删除 lang 目录
2、运行 php artisan lang:publish
3、再运行 php artisan admin:publish
可以正常运行
