### ISSUE TITLE
一对一关联模型表单可以查询显示，无法编辑更新？

### ISSUE THREAD

**Issue by garethhwang** [jqhph/dcat-admin#21]
按照文档里表单一对多编写代码可以显示关联模型字段内容，但是无法更新关联模型字段值

**Comment by jqhph** [comment]
感谢反馈，请贴下代码

**Comment by jqhph** [comment]
[已修复。](https://github.com/jqhph/dcat-admin/commit/0beab1d569d8d1e351fcba42039601ed5fd98ab4)
