### ISSUE TITLE
列表頁查詢過濾 的文字太小

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#2100]
<img width="514" alt="image" src="https://github.com/jqhph/dcat-admin/assets/8817046/0c1c95e9-c028-4aca-944b-fb8d1b462a8e">

希望這裡的默認字體可以稍微大一些，有點看不清楚，自己改很麻煩的樣子，bootstrap.php 中實驗了很久都沒變動，最後去 vendor 裡面改的

**Comment by HailongGu** [comment]
同求解答
