### ISSUE TITLE
高版本的php和Laravel报错

### ISSUE THREAD

**Issue by jefferyjob** [jqhph/dcat-admin#2102]
- Laravel Version: 10.40.0
- PHP Version: 8.3.0
- Dcat Admin Version: 2.2.3-beta

### Description:

这些代码在我使用过程中一直提示 warning 类型的日志错误，一般的企业开发环境都会监控 warning 和 error 类型的如何，如果作者不解决这些问题，会对开发造成非常不友好的问题。辛苦麻烦看看这个问题。

```
Creation of dynamic property Dcat\Admin\Support\WebUploader::$file is deprecated in /www/vendor/dcat/laravel-admin/src/Support/WebUploader.php on line 36
```

```
Creation of dynamic property Dcat\Admin\Support\WebUploader::$upload_column is deprecated in /www/vendor/dcat/laravel-admin/src/Support/WebUploader.php on line 35
```

```
Creation of dynamic property Dcat\Admin\Support\WebUploader::$chunks is deprecated in /www/vendor/dcat/laravel-admin/src/Support/WebUploader.php on line 34
```

```
Creation of dynamic property Dcat\Admin\Support\WebUploader::$chunk is deprecated in /www/vendor/dcat/laravel-admin/src/Support/WebUploader.php on line 33
```

```
Creation of dynamic property Dcat\Admin\Support\WebUploader::$_id is deprecated in /www/vendor/dcat/laravel-admin/src/Support/WebUploader.php on line 32
```

**Comment by kikoshot** [comment]
PHP8.2弃用了类动态添加属性，在 PHP 8.2 及更高版本中，不推荐为未声明的类属性设置值，并在应用程序执行生命周期内首次设置该属性时发出弃用通知。
PHP 8.2在全局命名空间中引入了 #[AllowDynamicProperties]。使用此属性声明的类会指示 PHP 在为该类的对象设置动态属性时不发出任何弃用通知。
```php
#[AllowDynamicProperties]
 class User {
     private int $uid;
 }

 $user = new User();
 $user->name = 'Foo';
```

**Comment by aogg** [comment]
+1

**Comment by PorygonCN** [comment]
还请暂时使用 @yi4396 的方法，后续我们会尝试解决这个问题

**Comment by jefferyjob** [comment]
> PHP8.2弃用了类动态添加属性，在 PHP 8.2 及更高版本中，不推荐为未声明的类属性设置值，并在应用程序执行生命周期内首次设置该属性时发出弃用通知。 PHP 8.2在全局命名空间中引入了 #[AllowDynamicProperties]。使用此属性声明的类会指示 PHP 在为该类的对象设置动态属性时不发出任何弃用通知。
> 
> ```
> #[AllowDynamicProperties]
>  class User {
>      private int $uid;
>  }
> 
>  $user = new User();
>  $user->name = 'Foo';
> ```

具体加到哪个位置呢，难道我要直接改 vendor 吗 😂
