### ISSUE TITLE
工具表单按钮能动态传参吗

### ISSUE THREAD

**Issue by mbdmt** [jqhph/dcat-admin#2104]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.2

### Description:

例如先选 产品 取得id 传到Modal::make的payload中
我看好像页面载入时就已经把Modal按钮网址参数设死
参数如在按钮上还能复写 但只能设在php参数不知道有变通方式吗
谢谢

### Steps To Reproduce:

$table->select('product_id')->options($option);

$po_modal = Modal::make()
	->lg()
	->title('Options')
	->body(ProductOptions::make()->payload(['id' => '123'])) // 传递自定义参数
	->button('Options');

$table->display('optionss')->with(function() use ($po_modal){
	return $po_modal.Session('orderOptionModel');
});

**Comment by aboutboy** [comment]
我也遇到这个麻烦。因为我要通过弹窗快速编辑产品介绍，如果通过payload把产品名称、介绍等所有要显示在form的参数都传递过去，常常会因为产品介绍字段太大，导致浏览器报419 Request-URI too long错误。
我试了先传productid到Modal，再在default()中根据productid获取产品名、简介等其他参数，再return，但表单里面都是空。

**Comment by CoderHuu** [comment]
亲，这个是可以的哟。
