### ISSUE TITLE
数据表单的前端验证，如何增加多语言支持，如何自定义错误提示消息？

### ISSUE THREAD

**Issue by zhuman90** [jqhph/dcat-admin#2114]
![image](https://github.com/jqhph/dcat-admin/assets/12763586/0950b2b3-9c01-4a5a-802f-0f687ec863c5)

**Comment by zwping** [comment]
bootstrap-validator 支持多语言？

**Comment by zwping** [comment]
html原生属性setCustomValidity

`$form->mobile('phone')->required()->attribute('oninvalid', "setCustomValidity('请输入手机号 !')")->attribute('oninput', "setCustomValidity('')");`

**Comment by chillcollex** [comment]
感觉这个仓库不会再有更新了，任何问题我们只能查阅文档或 git issues, 大家互相抱团取暖吧 🥹

**Comment by faydanube** [comment]
> 感觉这个仓库不会再有更新了，任何问题我们只能查阅文档或 git issues, 大家互相抱团取暖吧 🥹

上個項目用的 filament
