### ISSUE TITLE
用https访问以后,登陆页面提交不了

### ISSUE THREAD

**Issue by dhl94050483** [jqhph/dcat-admin#2126]
- Laravel Version: 10.44.0
- PHP Version: 8.2.12
- Dcat Admin Version: 2.2.3-beta

### Description:
在配置https访问前,程序一切正常.配置完https访问以后,登陆页面访问get请求访问正常,但输入用户名及密码点击"登录"按钮以后,页面报错:
![11](https://github.com/jqhph/dcat-admin/assets/20162384/a126e294-5adf-4c22-9f1b-a5b9d53fd857)
我试了一下别的方法,貌似post请求都不好用了,跪求大神指点!
我的https配置如下:
.env文件:APP_URL=https://XXXXX
admin.php: 'https' => env('ADMIN_HTTPS', true),
 App\Providers\AppServiceProvider.php:URL::forceScheme('https');

**Comment by zwping** [comment]
empty_response

具体可以看log

**Comment by zwping** [comment]
登录对应的方法`AuthController#postLogin`

**Comment by dhl94050483** [comment]
好用了，原因是我所在的局域网里的请求被拦截了
