### ISSUE TITLE
请问怎么给动作设置权限?

### ISSUE THREAD

**Issue by hhniao** [jqhph/dcat-admin#213]
- Laravel Version: 7.0
- PHP Version: 7.2
- Dcat Admin Version: 1.4.7

希望有一个快捷方便的方式去设置动作的权限.

**Comment by hhniao** [comment]
看到动作确认时有发送一个请求到 
/admin/dcat-api/action

**Comment by jqhph** [comment]
参考文档[动作基本使用](http://www.dcatadmin.com/docs/master/action.html)
```php
protected function authorize($user): bool
{
    return $user->can('do-action');
}
```

**Comment by hhniao** [comment]
多谢大佬.
