### ISSUE TITLE
是否支持关联关系字段查询 $filter->equal('member.name')

### ISSUE THREAD

**Issue by 377123** [jqhph/dcat-admin#215]
$filter->equal('member.name','主播名')->width(3)->placeholder('请输入主播名...');

这样搜索貌似不行  laravel-admin 可以

**Comment by jqhph** [comment]
下个版本中会支持这个用法

**Comment by cpken** [comment]
使用 $filter->equal('user.username'); 的写法，报如下错误，求解：

Illuminate\Database\QueryException
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.username' in 'where clause' (SQL: select count(*) as aggregate from `recharge_flows` where `user`.`username` = 1)

**Comment by jqhph** [comment]
> 使用 $filter->equal('user.username'); 的写法，报如下错误，求解：
> 
> Illuminate\Database\QueryException
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'user.username' in 'where clause' (SQL: select count(*) as aggregate from `recharge_flows` where `user`.`username` = 1)

请升级到`1.5.0`版本
