### ISSUE TITLE
不太理解form表单的处理形式，可以解答一下吗

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#216]
以前的处理方式是根据前台获取的form表单数据进行构造，再根据对应的业务逻辑存储到对应的表中，现在这种处理方式对于复杂的场景不知道怎么使用了。比如同一组数据要存储到多个表中，这种情况该怎么定义。没接触过 laravel-admin 直接使用这个框架有很多点不知道怎么处理，有没有好的学习资源可以推荐一下吗

**Comment by jqhph** [comment]
其实表单处理流程非常简单啊，就是普通的表单提交流程

1. Form组件生成表单HTML
2. 填好数据提交到控制器`store`和`update`方法
3. 验证表单数据是否正确以及表单值转换处理
4. 最终把处理后的表单值提交到数据仓库的`store`和`update`方法进行保存操作


从第`2`个步骤开始你都可以完全自己控制了，你都拿到表单数据了，你想怎么存还不简单吗？另外推荐看一下文档表单数据源，最好是在数据仓库进行处理
