### ISSUE TITLE
时间控件里的值如何转为时间戳

### ISSUE THREAD

**Issue by running8gubin** [jqhph/dcat-admin#218]
- Laravel Version: 7.15.0
- PHP Version: 7.3.0
- Dcat Admin Version: 1.5.0

### Description:
$filter->between('column', $label)->datetime();
表格里是存的时间戳，有的是精确到秒，有的时候还是带毫秒（百分之一秒）的。
怎么转换过滤。
表单新建与编辑，也希望能自动转换成秒或毫秒的。

**Comment by jqhph** [comment]
```php
  $filter->between('column', $label)->datetime()->toTimestamp();
```
