### ISSUE TITLE
上传图片问题

### ISSUE THREAD

**Issue by bun520** [jqhph/dcat-admin#22]
- Laravel Version: 7.0
- PHP Version: 7.2
- Dcat Admin Version: 0.5.0

### Description:
上传图片组件 换成接口上传  图片可以正常传上去。但是提交表单后又会走一遍本地的上传。是我用错了方法还是怎么回事
还有saving里 写 redirect 如果有上传图片的组件 就必须要先把图片传上去后才可以

```php 
// upload/image 是接口  已经可以正常拿到图片了
$form->multipleImage('covers', '图片')->url('upload/image');
```

**Comment by jqhph** [comment]
已修复，感谢反馈
