### ISSUE TITLE
Question widget table

### ISSUE THREAD

**Issue by jouniikaheimo** [jqhph/dcat-admin#220]
How i can use the table widget?
if make custom view how i can get data to view from repository.

i want make user profile where left  user details and right orders and many others details..

examples for this image 
https://keenthemes.com/wp-content/uploads/2016/07/user-profile.jpg

**Comment by jqhph** [comment]
```php
$data = PostModel::where('user_id', $id)
            ->where('type', $type)
            ->get(['title', 'body', 'body', 'created_at'])
            ->toArray();

        $titles = [
            'User ID',
            'Title',
            'Body',
            'Created At',
        ];

        return Table::make($titles, $data);
```

**Comment by jouniikaheimo** [comment]
Ah thx that working now :)
can row make a link to details.. ex: /admin/customer/{customer_id}

**Comment by jqhph** [comment]
Of course

```php
$data = PostModel::where('user_id', $id)
            ->where('type', $type)
            ->get(['title', 'body', 'body', 'created_at'])
            ->map(function ($model) {
                 $url = admin_url('customer/{customer_id');
                 $model['view'] = "<a href='{$url}'></a>";

                 return $model;
           })
            ->toArray();
```

**Comment by jouniikaheimo** [comment]
Thx that work fine... i have one issue..
:where('role', 'default')->get(['firstname', 'lastname', 'created_at' ,'id'])

and i map that link to firstname 

->map(function ($model) {
                $url = admin_url('customer/'. $model->id);
                $model['firstname'] = "<a href='{$url}'> $model->full_name</a>";

                return $model;
            })

how i hide id in table? if i remove that from get $model->id in link not working without that ?

**Comment by jqhph** [comment]
```php
$data = PostModel::where('user_id', $id)
            ->get()
            ->map(function ($model) {
                 $url = admin_url('customer/{customer_id');
                 $model['view'] = "<a href='{$url}'></a>";

                 unset($model['id']);                 

                 return $model;
           })
            ->toArray();
```

**Comment by jouniikaheimo** [comment]
thx for that.. one question more can something form input float side by side.. or system support only 
one below another? and one more.. if i make widgetForm and then grid under that.. if form submit how i car refresh grid ?

**Comment by jqhph** [comment]
I think this is what you want

1.form row
```php
$form->row(function (Form\Row $form) {
    $form->width(4)->text('username')->required();
    $form->width(3)->text('title');
    ...
});

$form->row(function (Form\Row $form) {
    ...
});
```

2.widget form

```php
<?php

namespace App\Admin\Forms;

use Dcat\Admin\Widgets\Form;
use Symfony\Component\HttpFoundation\Response;

class Setting extends Form
{
    /**
     * Handle the form request.
     *
     * @param array $input
     *
     * @return Response
     */
    public function handle(array $input)
    {
        // dump($input);

        // return $this->error('Your error message.');

        return $this->success('Processed successfully.', '/the redirect url');
    }

    /**
     * Build a form here.
     */
    public function form()
    {
        $this->text('name')->required();
        $this->email('email')->rules('email');
    }

    /**
     * The data of the form.
     *
     * @return array
     */
    public function default()
    {
        return [
            'name'  => 'John Doe',
            'email' => 'John.Doe@gmail.com',
        ];
    }
}
```

**Comment by jouniikaheimo** [comment]
Thx that working fine, can i get repository customer details in variable... 

        return Show::make($id, new Customers, function (Show $show) {

that works yes... but i want take full customer information in variable...

$customerData = new Customers(); ? but how i can get by $id?

that is possible last one message because then i know all what i need todo my project :)

**Comment by jqhph** [comment]
```php
 return Show::make($id, new Customers, function (Show $show) {
    $customerData = $show->model()->toArray();
});
```

**Comment by jouniikaheimo** [comment]
again one question more :) how i get customer information in $content ->body 

i try to something this... but not working

 protected function detail(Content $content, $id)
    {

        $header = [
            'text' => 'Customers',
            'url' => admin_url('customers')
        ];
        $user = CustomerModel::find($id);

        var_dump($content);
        return $content
            ->header('Customers')
            ->breadcrumb($header)
            ->breadcrumb($user->full_name)
            ->description($user->full_name)
            ->body(function (Row $row) {
                $row->column(6, function (Column $column) {
                    $column->row($this->form());
                    $column->row($this->userData($user->id));

                });
                $row->column(6, function (Column $column) {
                    $column->row($this->grid());
                });
            });


    }

$user->id is invalid in body ->row ->column...

**Comment by jqhph** [comment]
```php
 return $content
        ->header('Customers')
        ->breadcrumb($header)
        ->breadcrumb($user->full_name)
        ->description($user->full_name)
        ->body(function (Row $row) use ($user) {
            $row->column(6, function (Column $column)  use ($user) {
                $column->row($this->form());
                $column->row($this->userData($user->id));

            });
            $row->column(6, function (Column $column) {
                $column->row($this->grid());
            });
        });
```
