### ISSUE TITLE
上传功能建议

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#221]
老大 
请教下上传功能下个版本会更新吗?
是不是上传后可以不出现"上传"的按钮 
 
![螢幕快照 2020-06-05 下午1 47 26](https://user-images.githubusercontent.com/16574141/84629597-29e4e300-af1d-11ea-8f82-b24138e8e78a.png)

**Comment by jqhph** [comment]
可以通过自动上传解决这个问题

**Comment by kevin700523** [comment]
老大 请问下个版本会更新吗?

**Comment by jqhph** [comment]
可以

**Comment by jqhph** [comment]
已支持这个功能

**Comment by kevin700523** [comment]
感谢大佬

**Comment by running8gubin** [comment]
升级到1.52
