### ISSUE TITLE
How can i pass the foreign ID value to related resource URL query string.

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#222]
Laravel Version: 7.*
PHP Version: 7.2.5
Dcat Admin Version: 1.5.0

### Description:

i am unable to pass the the `ticket_id` as a query string to ticket-comments resource

i was expecting the resource link of the button to add comment to be like this: `https://xxxx.test/dashboard/ticket-comments/create?ticket_id=23` 

but the resource link is like this : `https://xxxx.test/dashboard/tickets/ticket-comments/create` . 

 i can't pass the foreign ID value to the URL query string.

is there any solution available ?

the grid resource url is `https://xxxx.test/dashboard/tickets` 

````
protected function detail($id){

        return Show::make($id, new Ticket(), function (Show $show) {

            $show->field('subject', trans('admin.subject'));

            $show->field('content', trans('admin.comment'))->unescape();

            $show->comments(function ($model) {

                $grid = new Grid(new TicketComment());

                $grid->model()->where('ticket_id', $model->id);

                $grid->model()->latest();

                $grid->setResource('ticket-comments');

                $grid->column('content', trans('admin.content'))->display(function () {
                    return $this->content;
                });

                return $grid;

            });

        });

    }
````

**Comment by jqhph** [comment]
Try it
```php
$grid->model()->setConstraints([
    'ticket_id' => '$model->id',
]);
```

**Comment by chiwex** [comment]
Thank you. it is now working as expected
