### ISSUE TITLE
admin:extend翻译不生效

### ISSUE THREAD

**Issue by okami-chen** [jqhph/dcat-admin#225]
- Laravel Version: 7.15.0
- PHP Version: 7.4.7
- Dcat Admin Version: 1.5

### Description:
存在文件：`extension/okami-chen/dict/resources/lang/zh-CN/dict.php`
不起作用，将文件复制到`resources/lang/zh-CN/dict.php`生效

**Comment by jqhph** [comment]
插件的语言包默认是注册命名空间使用的
