### ISSUE TITLE
Form editor field with required rule don't work

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#226]
Laravel Version: 7.*
PHP Version: 7.2.5
Dcat Admin Version: 1.5.0

### Description:

`$form->editor('content', 'Content')->rules('required');`

when the form is filed, it keeps on displaying error message: 
` The Content Field Is Required.`

**Comment by jqhph** [comment]
Thanks for the report, we have a temporary solution
```php
$form->editor('content', 'Content')->required();
```
