### ISSUE TITLE
$model->getFilter()->input('name', ')  这里不行不知道怎么了帮指点一下谢谢

### ISSUE THREAD

**Issue by 377123** [jqhph/dcat-admin#227]
`class ChannelStatistics extends Repository{
public function get(Grid\Model $model){
$name = $model->getFilter()->input('name', ');//这里用法能否在指点一下
echo $name; 这里报错
}

}
`

**Comment by jqhph** [comment]
语法错误，改成
```php
$name = $model->getFilter()->input('name');
```

**Comment by 377123** [comment]
public function get(Grid\Model $model){
        $channel =$model->getFilter()->input('status');
        var_dump($channel);
        exit;

**Comment by 377123** [comment]
![image](https://user-images.githubusercontent.com/4208764/84853006-c8de1c00-b090-11ea-8ef1-11df559432d0.png)

**Comment by jqhph** [comment]
文档有点问题，filter方法名称改了
```php
$model->filter()->input(xxx)
```

**Comment by 377123** [comment]
request()
