### ISSUE TITLE
Can't Login into admin interface

### ISSUE THREAD

**Issue by yuetyeelo2855** [jqhph/dcat-admin#228]
- Laravel Version: 7.15.0
- PHP Version: 7.2
- Dcat Admin Version: 1.4.8

### Description:
1. Can't login to admin interface
2. 419 csrf token mismatch exception is throw when login admin interface by code.
`Admin::guard()->loginUsingId(mixed $id, bool $remember = false)`

### Steps To Reproduce:
1. Deploy as Sub-directory mode. 
[https://laravel-news.com/subfolder-install](Tutorial)

### Cause
Session is changed after using Session Middleware
https://github.com/jqhph/dcat-admin/blob/aaeeb2c152d9bc658b2b54421138ad13cb13dc99/src/Middleware/Session.php#L11-L19

### Temp Solution
Comment using Session Middleware

**Comment by jqhph** [comment]
Not support sub-directory mode
