### ISSUE TITLE
关联模型字段不能自动翻译吗？

### ISSUE THREAD

**Issue by sym134** [jqhph/dcat-admin#229]
- Laravel Version: 7.1.2
- PHP Version: 7.4.1
- Dcat Admin Version: 1.5.0

### Description:
关联模型字段不能自动翻译

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/32946251/84863690-ed91be00-b0a7-11ea-95c3-611cd7ef4bf1.png)
上面不能自动识别，两个模型的翻译都加了这个字段也不行
只能自己手动加
$grid->column('info.user_name','名字');
不知道是不是我没找到正确打开方式😄

**Comment by jqhph** [comment]
升级到1.5.0版本，然后在你的翻译文件中加上

```php
return  [
    'fields' => [
        'info' => [
            'user_name' => '名字',
        ],
    ],
];
```

**Comment by sym134** [comment]
可以了！非常感谢👍
