### ISSUE TITLE
Form表单select联动更新问题

### ISSUE THREAD

**Issue by QThans** [jqhph/dcat-admin#237]
1.5的版本以后：form的select组件的load 函数，$class = static::FIELD_CLASS_PREFIX.$field;，class的获取改成这个，导致之前不兼容。新的按照文档的格式也无法加载。

**Comment by QThans** [comment]
我看这边增加了一个常量用来给class增加上field，但是select渲染以后并没有给class加上field，input输入框貌似是有的。

**Comment by jqhph** [comment]
1.5表单联动我是测试过正常的，正常升级不会不兼容啊

**Comment by QThans** [comment]
```
 $table->select('type', '事件类型')->options(FormEvent::EVENT_TYPE)->load('name', route('bpm.formEvents'));
$table->select('name', '事件名称')->addElementClass('field_name');
```
上面这样写是OK的。

```
$table->select('type', '事件类型')->options(FormEvent::EVENT_TYPE)->load('name', route('bpm.formEvents'));
$table->select('name', '事件名称');
```
这样是没有联动的。

生成代码如下：
js部分
![image](https://user-images.githubusercontent.com/18275400/85160879-93ece780-b291-11ea-8650-993431bdc062.png)

html部分
![image](https://user-images.githubusercontent.com/18275400/85160992-c0a0ff00-b291-11ea-8b91-a905386f9af7.png)

**Comment by jqhph** [comment]
好的，我晚上试试，如果有问题会在明天晚上的小版本中修复

**Comment by jqhph** [comment]
你确定你是1.5.0版本的吗？我测试了下联动功能正常

```php
 $form->select('author_id')->options(['GET', 'POST', 'PUT'])->load('state', 'test/options');
$form->select('state');
```

![image](https://user-images.githubusercontent.com/20312339/85195379-58d7cc00-b304-11ea-8f21-638531737278.png)

**Comment by QThans** [comment]
是的 我晚上移除包，重新安装再试下。

**Comment by jqhph** [comment]
你应该是没有重新发布资源或者是没有清理浏览器缓存吧，看你这个html也有问题

**Comment by QThans** [comment]
还是不行 重新装了下。php artisan admin:publish --force 这个已经运行很多次了。

**Comment by jqhph** [comment]
截图下你的完整form表单代码

**Comment by QThans** [comment]
![image](https://user-images.githubusercontent.com/18275400/85195929-2a102480-b309-11ea-844a-160f11570044.png)

**Comment by jqhph** [comment]
感谢反馈，在`table`表单下确实有问题

**Comment by jqhph** [comment]
已修复，等明天新版本吧

**Comment by QThans** [comment]
另外建议select的default在未选中的时候可以被提交。上一个版本好像可以？昨晚更新以后貌似不行了。不确定。没影响是个我这边还没开发好的功能出现的。

**Comment by jqhph** [comment]
default方法编辑页面是不生效的，如果编辑页面需要，请用customFormat方法代替

**Comment by QThans** [comment]
谢谢！产品很棒！
