### ISSUE TITLE
selectResource选择器在非一对多的情况下失效了

### ISSUE THREAD

**Issue by QingHuanMoon** [jqhph/dcat-admin#238]
- Laravel Version: 7.15
- PHP Version: 7.4.7
- Dcat Admin Version: 1.5.0

### Description:
selectResource选择器在非一对多的情况下失效了
![image](https://user-images.githubusercontent.com/35555652/85186839-e3510900-b2cd-11ea-975c-2265607acdb9.png)

![image](https://user-images.githubusercontent.com/35555652/85186850-f19f2500-b2cd-11ea-8207-857a1fed4279.png)

**Comment by jqhph** [comment]
感谢反馈，明天晚上会有个小版本，到时候解决这个问题

**Comment by jqhph** [comment]
刚刚测试了一下，没发现问题，这个功能正常啊
