### ISSUE TITLE
當工具列只有新增按鈕時會跟下面的表格靠得太近

### ISSUE THREAD

**Issue by lilashih** [jqhph/dcat-admin#239]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
如下圖

![image](https://user-images.githubusercontent.com/55920306/85193681-60e03d80-b2fd-11ea-9f28-510897111354.png)

**Comment by jqhph** [comment]
感谢反馈，明天发布新版本，到时候会优化这个问题
