### ISSUE TITLE
Scaffold功能bug

### ISSUE THREAD

**Issue by Ghwolfzx** [jqhph/dcat-admin#24]
- Laravel Version: 7.4
- PHP Version: 7.3
- Dcat Admin Version: 0.5.0

### Description:
Scaffold 创建 migration 文件时异常，调用与定义参数数量不符
![image](https://user-images.githubusercontent.com/31129069/78969089-be575180-7b38-11ea-9efd-d205fb5faa4b.png)
![image](https://user-images.githubusercontent.com/31129069/78969112-cca56d80-7b38-11ea-83f4-e9cc183f497b.png)

**Comment by jqhph** [comment]
感谢反馈，这个问题已修复，今天提前发布先行版本，会合并这个代码。

**Comment by jqhph** [comment]
发布之后你更新最新版本就好了
