### ISSUE TITLE
文件上传表单验证的问题

### ISSUE THREAD

**Issue by Everan-1994** [jqhph/dcat-admin#240]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.5

如图，没上传之前，点击提交出现红色的错误提示，然后选择上传文件，错误提示没有被移除。
![image](https://user-images.githubusercontent.com/33532865/85195370-4362a200-b304-11ea-8088-6b6e96c255fd.png)

**Comment by jqhph** [comment]
好的，感谢反馈
