### ISSUE TITLE
如何同时连接多种类型数据库

### ISSUE THREAD

**Issue by okbeng2** [jqhph/dcat-admin#241]
- Laravel Version: 7.16.1
- PHP Version: 7.3.9
- Dcat Admin Version: 1.3
### Description:
 控制器, 数据仓库 语言包 怎么写呢

**Comment by jqhph** [comment]
在配置文件`config/database.php`中设置你的数据库连接信息，然后再模型文件中指定`connection`属性即可，具体使用建议参考laravel中文文档或者百度

**Comment by okbeng2** [comment]
数据仓库 怎么写呢

**Comment by jqhph** [comment]
数据仓库跟你的数据库连接没有直接关系呀，数据仓库还是使用`model`操作数据库，你在`model`中指定不同的数据库连接就好了。

**Comment by a157147899** [comment]
> 数据仓库跟你的数据库连接没有直接关系呀，数据仓库还是使用`model`操作数据库，你在`model`中指定不同的数据库连接就好了。

请问代码生成器中能配置多个数据吗？目前已经配置好了Laravel部分的多个数据库连接，谢谢。

**Comment by a157147899** [comment]
![image](https://user-images.githubusercontent.com/1812136/103476950-d2f21d00-4e1e-11eb-8027-397652731a90.png)
![image](https://user-images.githubusercontent.com/1812136/103476960-ed2bfb00-4e1e-11eb-96f8-c9f996a640bc.png)


.env中已配置多个数据库，controller已正常能访问多个数据库，但是代码生成器这里还是只能看到默认数据库

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/103494752-1d04ee00-4e73-11eb-823c-82c8e5898032.png)
@a157147899 多库配置方法如图
