### ISSUE TITLE
apexcharts异常值问题

### ISSUE THREAD

**Issue by Huelse** [jqhph/dcat-admin#244]
- Laravel Version: 7.*
- PHP Version: 7.3.19
- Dcat Admin Version: 1.5.0

### Description:
apexcharts抛出异常值，看起来是画图时，translate中第一个参数为NaN导致的
可能是js异步逻辑出了问题？
![error](https://i.loli.net/2020/06/21/4GdLXYoFsheUWBg.png)

### Steps To Reproduce:
当切换两个有图表的页面时有几率会出现，但页面内容看起来没有影响，也有时候不会出现
快速切换时出现概率较高

**Comment by jqhph** [comment]
原因尚未查清，不过这个报错不影响正常使用

**Comment by Huelse** [comment]
是不影响正常使用，希望未来能解决吧，个人不喜欢这种报错
