### ISSUE TITLE
树形表格增加行动作，script会重复加载

### ISSUE THREAD

**Issue by QThans** [jqhph/dcat-admin#246]
![image](https://user-images.githubusercontent.com/18275400/85232783-668c6f00-b434-11ea-8fb3-94bfcf4e4091.png)

如图，会重复的加载js进入页面。会导致展开下级以后，重复监听。

临时解决方法：用off移除下之前的click事件。

**Comment by jqhph** [comment]
这个目前也没有好的解决方案，只能是先解绑再重新绑定
