### ISSUE TITLE
菜单不设置权限 应该是所有人都能进  结果是所有人都不能进了

### ISSUE THREAD

**Issue by anyuzhe** [jqhph/dcat-admin#249]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

菜单不设置权限 应该是所有人都能进  结果是所有人都不能进了

**Comment by jqhph** [comment]
菜单的权限是控制菜单显不显示，路由访问权限跟菜单权限没有直接关系。
