### ISSUE TITLE
表格字段display之后不能使用copyable

### ISSUE THREAD

**Issue by cz0634** [jqhph/dcat-admin#253]
- Laravel Version: 7.x
- PHP Version: 7.1
- Dcat Admin Version: 1.5.2

### Description:
`$grid->column('link', '链接')->display(function ($link) {
                return 'http://' . $this->domain['domain'] . '/s/'.$this->id;
            })->copyable();`

表格中复制按钮的data-content为空，无法复制display中return的值

**Comment by jqhph** [comment]
这个功能已经优化了，可以先更新master分支代码
