### ISSUE TITLE
prepent添加图标功能没有效果

### ISSUE THREAD

**Issue by hiccup711** [jqhph/dcat-admin#254]
- Laravel Version: 6.18.2
- PHP Version: 7.3
- Dcat Admin Version: 1.5.2

### Description:
添加了`prepend`之后HTML样式名并没有变化

### Steps To Reproduce:

`
$form->text('test')->prepent('feather edit);
`

**Comment by jqhph** [comment]
好的，感谢反馈，这个功能确实有问题，你可以先更新master分支代码，用法是这样的

```php
$form->text('test')->prepent('<i class="feather  icon-eye"></i>');
```

**Comment by hiccup711** [comment]
> 好的，感谢反馈，这个功能确实有问题，现在已经修复了，你可以先更新master分支代码，用法是这样的
> 
> ```
> $form->text('test')->prepent('<i class="feather  icon-eye"></i>');
> ```

感谢！

**Comment by hiccup711** [comment]
> 好的，感谢反馈，这个功能确实有问题，现在已经修复了，你可以先更新master分支代码，用法是这样的
> 
> ```
> $form->text('test')->prepent('<i class="feather  icon-eye"></i>');
> ```

我更新了`master`分支代码，也`republush`了，但是好像还是没有效果，prepend中添加的`html`并没有在页面中被打印出来。

**Comment by jqhph** [comment]
你没更新成功，那就等新版本吧

**Comment by hiccup711** [comment]
> 你没更新成功，那就等新版本吧

好的，感谢回复！
