### ISSUE TITLE
如何给个人添加权限

### ISSUE THREAD

**Issue by ShynHan** [jqhph/dcat-admin#256]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

文档权限控制部分的描述

> 第二步可以把这个权限直接附加给**个人**或者角色，在用户编辑页面可以直接把上面创建好的权限附加给**当前编辑用户**，也可以在编辑角色页面附加给某个角色。

个人资料页面没有添加权限的地方，只能添加用户 `角色`
数据库中也没有 user - permission表（用户与权限的对应关系）

---

![image](https://user-images.githubusercontent.com/12025422/85519664-6ce93980-b634-11ea-98c9-bf196f962050.png)

菜单编辑页面可以给菜单添加 `权限` ，这里的权限是判断菜单是否显示的么？有权限权限实现，没有权限不显示？

**Comment by jqhph** [comment]
1. 用户不能直接绑定权限，只能绑定角色
2. 菜单绑定的权限只是控制是否隐藏，如果给菜单绑定了权限或者角色，那么没有相关权限和角色的用户将看不到这个菜单

**Comment by ShynHan** [comment]
1. 用户直接绑定权限功能取消了
2. 如果想让菜单显示，要么用户身份符合，要么用户身份所包含的权限符合。（如果菜单没有设置 `角色` 和 `权限` 对所有用户显示）

可以这么理解么

**Comment by jqhph** [comment]
1. 是的
2. 菜单不绑定权限和角色的话所有用户都能看到，绑定了那就只有有相关权限或角色的用户能看到
