### ISSUE TITLE
在控制器里使用 Validation 无效

### ISSUE THREAD

**Issue by Everan-1994** [jqhph/dcat-admin#257]
- Laravel Version: 7.*
- PHP Version: 7.3.*
- Dcat Admin Version: 1.5.2

>问题描述

我先自定义了一个后台的详情页面，然后涉及到表单提交，我需要校验表单的字段。
具体代码如图：
![image](https://user-images.githubusercontent.com/33532865/85524696-f865c900-b63a-11ea-99fe-ff9d73a834bc.png)

表单提交空数据过来，页面写的 $errors 变量不会显示错误信息。
![image](https://user-images.githubusercontent.com/33532865/85525137-5e525080-b63b-11ea-86f0-67fc316439f0.png)

我看了后台路由的中间件有使用到 ```Web```，
![image](https://user-images.githubusercontent.com/33532865/85525024-41b61880-b63b-11ea-8f1f-50b7bc9378ac.png)

```
 \Illuminate\View\Middleware\ShareErrorsFromSession::class, // 貌似没起作用 ？
```

**Comment by jqhph** [comment]
正确的用法是

```php
back()->withInput()->withErrors($validationMessages);
```
