### ISSUE TITLE
EloquentRepository导致访问model中的casts属性报json_decode错误

### ISSUE THREAD

**Issue by cyclegtx** [jqhph/dcat-admin#258]
- Laravel Version: 7.*
- PHP Version: 7.4
- Dcat Admin Version: 1.5.2

### Description:

EloquentRepository.php createDeletingModel函数将数组通过 setRawAttributes赋给model，导致将已经解析为array的属性直接赋值到model的attributes里，在访问该属性时导致传给json_decode的值为array，报错。此处setRawAttributes的值应该为未转换的string。

暂时的解决办法：放弃使用casts，改用set，get。在get方法里判断如果值为数组则不需要json_decode直接返回。
例如：

使用casts
```
protected $casts = [
        "array_list" => "array",
    ];
```
改为
```
public function getArrayListAttribute($value){
    if(is_array($value)){
        return $value;
    }else{
        return json_decode($value,true);
    }
}

public function setArrayListAttribute($value){
    $this->attributes['array_list'] = json_encode($array_list);
}
```

**Comment by jqhph** [comment]
感谢反馈，这个问题已修复，可以先更新master分支代码

```php
composer update dcat/laravel-admin:"dev-master"
```
