### ISSUE TITLE
刪除功能有問題

### ISSUE THREAD

**Issue by lilashih** [jqhph/dcat-admin#259]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.5.2

### Description:
最近更新後發現刪除功能好像有點問題

1. 如果model裡有append的話會無法刪除
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use SoftDeletes;

    protected $table = 'categories';
    protected $appends = ['selected']; // here

    public $selectName = 'name';

    public function getSelectedAttribute()
    {
        return "[{$this->{$this->primaryKey}}]. {$this->{$this->selectName}}";
    }
```

錯誤訊息如下
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'selected' in 'field list' ...
```

2. 如果表單裡有relation時，也會無法刪除
```php
    
    protected $model = PostRepository::class;

    protected function form(): Form
    {
        $form = new Form(new $this->model(['categories']));

        $form->tab(__('my.base_info_post'), function ($form) {

            $form->multipleSelect('categories', __('my.category')) // here
                 ->customFormat(function ($categories) {
                     return array_column($categories, 'id');
                 });

            $form->divider();
            $form->display('created_at', __('my.created_at'));
            $form->display('updated_at', __('my.updated_at'));
        });

        return $form;
    }
```

錯誤訊息如下
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'categories' in 'field list' ...
```

**Comment by jqhph** [comment]
好的，感谢反馈，错误报文能贴完整一点吗

**Comment by lilashih** [comment]
好的

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'selected' in 'field list' (SQL: update `categories` set `id` = 4, `order` = 0, `type` = post, `parent_id` = 0, `creator_admin` = 1, `updater_admin` = 1, `created_at` = 2020-06-25 17:21:11, `deleted_at` = ?, `selected` = [4]. , `categories`.`updated_at` = 2020-06-25 17:23:36 where `id` = 4) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'selected' in 'field list' (SQL: update `categories` set `id` = 4, `order` = 0, `type` = post, `parent_id` = 0, `creator_admin` = 1, `updater_admin` = 1, `created_at` = 2020-06-25 17:21:11, `deleted_at` = ?, `selected` = [4]. , `categories`.`updated_at` = 2020-06-25 17:23:36 where `id` = 4) at D:\\test\\vendor\\laravel\\framework\\src\\Illuminate\\Database\\Connection.php:671)

**Comment by jqhph** [comment]
这个跟 #258  是同一个问题

**Comment by jqhph** [comment]
感谢反馈，这个问题已修复，可以先更新master分支代码

```php
composer update dcat/laravel-admin:"dev-master"
```
