### ISSUE TITLE
autoUpload批量上传多图,只会上传两个

### ISSUE THREAD

**Issue by linechengchen** [jqhph/dcat-admin#262]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
![image](https://user-images.githubusercontent.com/25653824/85816812-e2711900-b79e-11ea-8801-8a11c2bdd89c.png)
 上传5个文件时候 
$form->width(12)->multipleImage('contract_accessory', "采购附件")->autoUpload()->url("image?id=" . $id . "&module=2&belong=" . $index->toarray()['id']);
 只会发起两个上传请求

**Comment by jqhph** [comment]
感谢反馈，这个问题已修复，可以先更新master分支代码

```
composer update dcat/laravel-admin:"dev-master"
```
