### ISSUE TITLE
请问演示站点的网站设置是咋弄的？

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#269]
- Laravel Version: 6.2
- PHP Version: 7.3.4
- Dcat Admin Version: 1.5.2

### Description:
大大你好，俺又来了。🥰

我看演示站点有网站设置可以切换主题啥的
![](https://i.imgur.com/NbNtXFe.png)

但是我本地用dcat-admin，咋没有，这个要咋弄，文档里好像都是直接改配置文件来切换主题的。
![](https://i.imgur.com/nrQJauP.png)

😁能说一下吗

**Comment by jqhph** [comment]
可以直接下载演示站的源码 https://github.com/jqhph/dcat-admin-demo
