### ISSUE TITLE
建议你把这个前段改成用vue的

### ISSUE THREAD

**Issue by zzhh9857** [jqhph/dcat-admin#27]
建议你把这个前段改成用vue的，这样就更完美了，我查了一下，有vue版本的这个admin 模板。

**Comment by jqhph** [comment]
### 为何不开发成前后端分离项目？

最近有许多同学问我为什么不采用前后端分离方案？现在`vue`和`react`这么好用，为啥还要用`jQuery`呢？回答这个问题之前首先要搞清楚两种方案的优劣势

#### 前后端分离技术的优势与劣势
**优势**
1. 从用户体验角度来说，前后端分离项目用户体验会更好一点
2. 从技术角度而言，前后端分离技术现在也已是主流，采用这个方案也更适合我们提升自己的前端技术熟练度

**劣势**
1. 前后端分离技术的学习成本会更高，要求使用者必须有`vue`和`react`经验，否则就要花许多精力去学习才能上手
2. 前后端分离技术的引入会是项目功能扩展变得复杂和艰难，可能页面增加一个小功能，也需要单独打包前端资源，这无疑是给自己找麻烦
3. 这种前后端技术并不是真正意义的从团队到技术的前后端分离，也就是说如果你的前端不懂PHP代码，基本是无法接手维护你的前端代码的，其实所有工作还是需要后端一个人完成

#### jQuery技术方案的优势与劣势

**优势**

`jQuery`项目的优点就是简单易用，效率高，学习成本极低，上手快；
扩展功能也非常非常简单和灵活，基本可以让开发者摆脱冗余的HTML代码。

**劣势**

`jQuery`项目从技术角度而言已经有点落伍，属于比较老旧的技术体系。

#### 总结
分析完上面的两种方案的优劣势，你们大概也明白我为啥要采用`jQuery`方案了，这个项目的定位就是一个对**后端开发友好**的项目，目的是要满足大多数人的需求，追求的就是**简单**、**易用**和**高效率**，而不是提升开发者的前端技术水平。

`jQuery`虽然不是前卫的技术，但是实用性并不差，前后端分离能实现的功能，`jQuery`也一样能实现。而且在这个项目里面，你还能更快、更省事、更容易上手。
如果你是想要提升前端技术，或是展示自己的前端技术水平，那么推荐去尝试下`Laravel nova`。

**Comment by zzhh9857** [comment]
感谢 jqhph 同学的开源项目！

**说明一下：这里只是表达观点，但并不是带有挟持性的评论，jqhph同学说的也是很有道理。**

jqhph 同学的解释里面主要是考虑网页开发门槛和扩展困难的问题，个人持有以下观点：
1、PHP开发基本上都是带前端属性的，会用JQ的人学习比如VUE这样的框架非常容易，会JQ就会DOM操作，VUE这样的框架使用起来完全没有问题。
2、能把PHP后端（Laravel门槛是框架里面算高的了）学好的同学学习前端非常容易，修改不是问题。
3、当下培训机构培训PHP课程大部分都都开始培训主流前端框架。
4、如果您的开源产品真的 好用、简单、高效率，我相信前端开发一定不是主要问题。
5、不会玩前端的应该也玩不转这么涉及绚丽多彩前端的后台，我相信使用过程中肯定会有前端阻力。
6、打包问题，其实不是问题，一般框架文档从上到下打下来基本上就会了。

我是一个从PHP初学PHPER过来的人。

**Comment by jqhph** [comment]
明白，都是理性讨论，大家各抒己见求同存异即可。

你认为上手不难很大程度上是因为自己已经熟悉vue的使用。你学习vue的过程也许并不艰难，但是对一个不熟悉前端的开发来说要熟悉vue框架的各种功能接口，学习成本和难度曲线绝对是比`jQuery`高很多的，因为这个还涉及到前端开发一系列工具的学习，比如webpack打包、ES6的语法与编译等等。这个对许多PHP开发者来说成本是比较高的，门槛会高许多，有些PHP开发者连CSS文本超出换行都不会写，你让这种开发者去学习vue，是比较费力气的哦。

而且大多数选择快速开发的，并不关心前端框架用的是什么，只要功能能达标，界面不太难看就可以了。

另外你说易用程度不会差多少，建议可以试用下`laravel nova`，即使界面要稍稍做点改动也得打包发布js，步骤繁多，而且界面定制非常麻烦，要去研究它那一套页面的构建的原理和细节，这对许多开发老鸟来说都很费劲。

**Comment by jqhph** [comment]
关于vue更容易维护，这个是对于大型项目而言的。我这个项目的后台组件都是封装成PHP对象，维护和扩展都非常方便，并且对开发者非常友好，只要封装一次，就不需要再重复写HTML和JS代码了。

**Comment by zzhh9857** [comment]
“建议可以试用下laravel nova” 好的，感谢推荐，我去看看。

我试用了一下 https://github.com/SmallRuralDog/laravel-vue-admin 这个项目，但其实步骤也不多，只是说如果想二次开发需要多学习丢丢知识。

其实说VUE只是一个抛砖引玉，并不是代表仅仅就是VUE，只是VUE在使用里面个人感觉是最简单、最好上手的。

”有些PHP开发者连CSS文本超出换行都不会写，你让这种开发者去学习vue，是比较费力气的哦“，这句观点我个人觉得，如果二次开发，使用CSS都会困难了，个人感觉已经不在定位的范畴了。

**Comment by zzhh9857** [comment]
另外您这项目如果是作为开源产品来讲的话，我觉得您应该有更多的亮点，和Laravel-admin定位还是重复的，当然您这项目的亮点就是界面比Laravel-admin漂亮。
关于列表展示这块我觉得如果作为一个后台表格可以线条紧凑明显些，内容多了感觉会看得眼睛累。

**Comment by jqhph** [comment]
这个项目我看过，基本上跟`laravel nova`的模式差不多，我前面说的`laravel nova`的缺点它基本也有。

我这个项目的定位就是对后端开发友好的项目，重点是对后端开发友好，即使是CSS文本超出换行都不会写的那种前端小白也是目标用户哦。

简单、易用、高效率是这个项目的设计主要方向。

**Comment by jqhph** [comment]
> 另外您这项目如果是作为开源产品来讲的话，我觉得您应该有更多的亮点，和Laravel-admin定位还是重复的，当然您这项目的亮点就是界面比Laravel-admin漂亮。
> 关于列表展示这块我觉得如果作为一个后台表格可以线条紧凑明显些，内容多了感觉会看得眼睛累。

感谢建议，我会考虑优化表格样式。

这个项目确实与laravel-admin重合，我很多功能细节上进行了改良和优化，增加了更多非常实用的功能，总的来说就是用的更爽，后续版本也有更重要的升级。

**Comment by zzhh9857** [comment]
还是非常支持您的项目，开源万岁。

**Comment by jqhph** [comment]
感谢支持！

**Comment by colour10** [comment]
多谢开发了这么好的产品

**Comment by syxchina** [comment]
支持作者想法，希望后端的同学一行前端都不要写，就可以做成好看实用的后面界面

还有前后分离，我直接上java，并发、生态比php好点

**Comment by ShuiPingYang** [comment]
> 感谢 jqhph 同学的开源项目！
> 
> **说明一下：这里只是表达观点，但并不是带有挟持性的评论，jqhph同学说的也是很有道理，但是我觉得想法过时，除非您这产品面向的是以前JQ时代的老程序员。**
> 
> jqhph 同学的解释里面主要是考虑网页开发门槛和扩展困难的问题，个人持有以下观点：
> 1、PHP开发基本上都是带前端属性的，会用JQ的人学习比如VUE这样的框架非常容易，会JQ就会DOM操作（JQ操作DOM有时候还是挺危险的，重复销毁和创建DOM使用不当就会内存溢出），VUE这样的框架使用起来完全没有问题。
> 2、能把Laravel后端框架（Laravel门槛是PHP框架里面算高的了）学好的同学学习前端非常容易，修改不是问题，如果说可以让PHP开发更专注后端代码，那前提是有前端配合，无论如何一个人完成工作都必须具备一定前端知识。
> 3、当下培训机构培训PHP课程大部分都都开始培训主流前端框架，基本上初学者都经历过培训和学习，从工作开始就会主流前端框架。
> 4、如果您的开源产品真的 好用、简单、高效率，我相信前端开发一定不是主要问题。
> 5、不会玩前端的应该也玩不转这么涉及绚丽多彩前端的后台，我相信使用过程中肯定会有前端阻力。
> 6、打包问题，其实不是问题，一般框架文档从上到下打下来基本上就会了。
> 
> 我也是一个从JQ时代的PHP初学PHPER过来的人，我个人觉得从您这后台的定位来看，其实前后端分离和不分离易用性来看，其实区别不大，但是从我个人开发角度来看，还是更喜欢前后分离，因为我觉得分离更易用和更易维护，PHP代码里面不会参杂太多前端代码。

作为一个后端，我来说说我的想法吧，这个项目是作为后台使用的，这个是关键，后台就要简单，稳定，我做了五年开发了，也接触过vue，说实话，很讨厌npm系，简单事情搞复杂了，动不动就莫名其妙报错，需要专人维护，如果作为后台的前端模块，对后端开发来说就是灾难。技术只有最合适的，没有过时一说。你看看物理，数学基础理论有过时的说法吗？开发来说一样的，只有最合适的，没有最好的。我也看过很多人写的代码，说实话大多都是写的很不好，非常不好维护。前端花样百出，但是代码也是千奇百怪。

**Comment by phpk80** [comment]
> 感谢 jqhph 同学的开源项目！
> 
> **说明一下：这里只是表达观点，但并不是带有挟持性的评论，jqhph同学说的也是很有道理，但是我觉得想法过时，除非您这产品面向的是以前JQ时代的老程序员。**
> 
> jqhph 同学的解释里面主要是考虑网页开发门槛和扩展困难的问题，个人持有以下观点：
> 1、PHP开发基本上都是带前端属性的，会用JQ的人学习比如VUE这样的框架非常容易，会JQ就会DOM操作（JQ操作DOM有时候还是挺危险的，重复销毁和创建DOM使用不当就会内存溢出），VUE这样的框架使用起来完全没有问题。
> 2、能把Laravel后端框架（Laravel门槛是PHP框架里面算高的了）学好的同学学习前端非常容易，修改不是问题，如果说可以让PHP开发更专注后端代码，那前提是有前端配合，无论如何一个人完成工作都必须具备一定前端知识。
> 3、当下培训机构培训PHP课程大部分都都开始培训主流前端框架，基本上初学者都经历过培训和学习，从工作开始就会主流前端框架。
> 4、如果您的开源产品真的 好用、简单、高效率，我相信前端开发一定不是主要问题。
> 5、不会玩前端的应该也玩不转这么涉及绚丽多彩前端的后台，我相信使用过程中肯定会有前端阻力。
> 6、打包问题，其实不是问题，一般框架文档从上到下打下来基本上就会了。
> 
> 我也是一个从JQ时代的PHP初学PHPER过来的人，我个人觉得从您这后台的定位来看，其实前后端分离和不分离易用性来看，其实区别不大，但是从我个人开发角度来看，还是更喜欢前后分离，因为我觉得分离更易用和更易维护，PHP代码里面不会参杂太多前端代码。



> ### Why not develop into a front and back end separation project?
> Recently, many students asked me why I didn&#39;t use the front and back separation scheme? Now?`vue` And`反应` Why use it so well`jQuery` What about it? Before answering this question, we should first clarify the advantages and disadvantages of the two options
> 
> #### Advantages and disadvantages of front and rear separation technology
> ** advantage**
> 
> 1. From the perspective of user experience, the user experience of the front-end and back-end separation project will be better
> 2. From a technical point of view, the front-end and back-end separation technology is now the mainstream, and adopting this scheme is more suitable for us to improve our front-end technical proficiency
> 
> ** inferiority**
> 
> 1. The learning cost of front-end separation technology will be higher, which requires users to have`vue` And`反应` Experience, otherwise you will have to spend a lot of energy to learn to start
> 2. The introduction of the front-end and back-end separation technology will make the project function expansion more complex and difficult. It may add a small function to the page, and also need to package the front-end resources separately, which is undoubtedly a trouble for yourself
> 3. This front-end and back-end technology does not really mean the separation of front-end and back-end from team to technology. In other words, if your front-end does not understand PHP code, it is basically impossible to take over and maintain your front-end code. In fact, all the work still needs to be done by one person in the back-end
> 
> #### Advantages and disadvantages of jquery
> ** advantage**
> 
> `jQuery` The advantages of the project are simple and easy to use, high efficiency, extremely low cost of learning, and quick to start;
> The extension function is also very simple and flexible, which can basically let developers get rid of redundant HTML code.
> 
> ** inferiority**
> 
> `jQuery` From a technical point of view, the project is a bit outdated and belongs to an old technology system.
> 
> #### summary
> After analyzing the advantages and disadvantages of the above two schemes, you probably understand why I should adopt them`jQuery` Project, the positioning of this project is a right** Back end development friendly** The purpose of the project is to meet the needs of the majority of people** simple** It&#39;s not** Easy to use** And** Effective rate** Instead of improving the front-end technology level of developers.
> 
> `jQuery` Although it is not an avant-garde technology, its practicability is not poor. The functions that can be realized by separating the front end and the rear end can be realized,`jQuery公司` It can also be achieved. And in this project, you can be faster, easier and easier to start.
> If you want to improve the front-end technology, or show your own front-end technology level, it is recommended to try it`Laravel nova` It&#39;s not



> 感谢 jqhph 同学的开源项目！
> 
> **说明一下：这里只是表达观点，但并不是带有挟持性的评论，jqhph同学说的也是很有道理，但是我觉得想法过时，除非您这产品面向的是以前JQ时代的老程序员。**
> 
> jqhph 同学的解释里面主要是考虑网页开发门槛和扩展困难的问题，个人持有以下观点：
> 1、PHP开发基本上都是带前端属性的，会用JQ的人学习比如VUE这样的框架非常容易，会JQ就会DOM操作（JQ操作DOM有时候还是挺危险的，重复销毁和创建DOM使用不当就会内存溢出），VUE这样的框架使用起来完全没有问题。
> 2、能把Laravel后端框架（Laravel门槛是PHP框架里面算高的了）学好的同学学习前端非常容易，修改不是问题，如果说可以让PHP开发更专注后端代码，那前提是有前端配合，无论如何一个人完成工作都必须具备一定前端知识。
> 3、当下培训机构培训PHP课程大部分都都开始培训主流前端框架，基本上初学者都经历过培训和学习，从工作开始就会主流前端框架。
> 4、如果您的开源产品真的 好用、简单、高效率，我相信前端开发一定不是主要问题。
> 5、不会玩前端的应该也玩不转这么涉及绚丽多彩前端的后台，我相信使用过程中肯定会有前端阻力。
> 6、打包问题，其实不是问题，一般框架文档从上到下打下来基本上就会了。
> 
> 我也是一个从JQ时代的PHP初学PHPER过来的人，我个人觉得从您这后台的定位来看，其实前后端分离和不分离易用性来看，其实区别不大，但是从我个人开发角度来看，还是更喜欢前后分离，因为我觉得分离更易用和更易维护，PHP代码里面不会参杂太多前端代码。

接手过vue前后端分离的项目，由于前端离职，兼职前端交互的编写，只会简单的数据渲染，遇到复杂的交互逻辑，路由，组件通信，完全不知道怎么下手，就算能摸索出来，也很费劲，要是换成jquery效率肯定高很多

**Comment by cc4dogman** [comment]
其实vue前后端分离还是比较简单，但是你需要花不少时间在交互处理上，如果只是做一下纯管理后台的，用dcat问题不大，技术首先考虑的不是多么新，而是技术复杂度和维护成本，一味的追新没好处，可以把最终用户使用的用vue或者reactjs实现，管理后端其实都是些crud的操作，没必要投入太多时间

**Comment by syxchina** [comment]
现在做php的都不想做页面只写接口了？

**Comment by BruceLiu3385** [comment]
我是找了三天时间，主要想找前后端分离的框架的。把github上star排名前2页都安装一遍后，果断还是选择了dcat-admin 。

**Comment by kingsun-he** [comment]
我做我公司的后台开发，使用这个就挺好的。前端VUE我也用过，比较废力气，特别是现在只有我一个人，项目也不大，实在不想废力气搞前端了。

**Comment by huazhengchao** [comment]
那些提议前后端分离的真是为了分离而分离，这种后台快速框架就是怎么快怎么来，让后端不必在像以前套模板之类的浪费时间，也省去了与前端对接，除非你本身是全栈，不然我想不到前后端分离的好处！

**Comment by haowuliaoa22** [comment]
不喜欢前后端分离的唯一原因就是不喜欢等编译

**Comment by loveloving** [comment]
VbenAdmin考虑一下，页面超好看，用到技术有Vue3.0、Vite、 Ant-Design-Vue 、TypeScript[链接](https://vvbin.cn/next)

**Comment by linkimfly** [comment]
管他 JQuery 还是 Vue React,每个人的想法都不一样，每家公司需求也不一样，众口难调，我200%个支持作者的理念和方向，以及考虑到受众群体，希望能一直这么坚持下去，我反正用的很爽，一行前端不用写，感谢作者！

**Comment by tingsen** [comment]
这套脚手架能，扩展成接口方式吗？

**Comment by colour10** [comment]
邮件已收到,灰常感谢

**Comment by TheBlueSkim** [comment]
> 感谢 jqhph 同学的开源项目！
> 
> **说明一下：这里只是表达观点，但并不是带有挟持性的评论，jqhph同学说的也是很有道理，但是我觉得想法过时，除非您这产品面向的是以前JQ时代的老程序员。**
> 
> jqhph 同学的解释里面主要是考虑网页开发门槛和扩展困难的问题，个人持有以下观点： 1、PHP开发基本上都是带前端属性的，会用JQ的人学习比如VUE这样的框架非常容易，会JQ就会DOM操作（JQ操作DOM有时候还是挺危险的，重复销毁和创建DOM使用不当就会内存溢出），VUE这样的框架使用起来完全没有问题。 2、能把Laravel后端框架（Laravel门槛是PHP框架里面算高的了）学好的同学学习前端非常容易，修改不是问题，如果说可以让PHP开发更专注后端代码，那前提是有前端配合，无论如何一个人完成工作都必须具备一定前端知识。 3、当下培训机构培训PHP课程大部分都都开始培训主流前端框架，基本上初学者都经历过培训和学习，从工作开始就会主流前端框架。 4、如果您的开源产品真的 好用、简单、高效率，我相信前端开发一定不是主要问题。 5、不会玩前端的应该也玩不转这么涉及绚丽多彩前端的后台，我相信使用过程中肯定会有前端阻力。 6、打包问题，其实不是问题，一般框架文档从上到下打下来基本上就会了。
> 
> 我也是一个从JQ时代的PHP初学PHPER过来的人，我个人觉得从您这后台的定位来看，其实前后端分离和不分离易用性来看，其实区别不大，但是从我个人开发角度来看，还是更喜欢前后分离，因为我觉得分离更易用和更易维护，PHP代码里面不会参杂太多前端代码。

首先php带有前端属性是你的偏见，特别是php7-8的时代，你既然追求前后端分离就更不应该持有这样的观点。其次，完全依赖内存操作的vue实际上远比jquery更容易造成内存溢出。 这个项目基于laraveladmin，其重心就是减少前端操作。

**Comment by colour10** [comment]
邮件已收到,灰常感谢

**Comment by code789** [comment]
前后端分离还是回到了之前套模板的时代, 
dcat-admin的好处是代码控制界面,省去了编写模板
多么省事

**Comment by code789** [comment]
> 那些提议前后端分离的真是为了分离而分离，这种后台快速框架就是怎么快怎么来，让后端不必在像以前套模板之类的浪费时间，也省去了与前端对接，除非你本身是全栈，不然我想不到前后端分离的好处！

一些前后端分离的框架也不用套模板了,也是后台生成界面

**Comment by terranc** [comment]
千万别前后端分离。其实想用一些vue组件，完全可以直接引用进来做一些自定义的功能，常规的curd现在这样的模式挺好

**Comment by colour10** [comment]
邮件已收到,灰常感谢

**Comment by wang-sitong** [comment]
什么前后端分离,jquery一样办得到,前端复杂化是我觉得最没有意义的一件事,我完全理解不了为什么有人喜欢vue这种东西,有最快的剑不用,非得拿小刀砍人.一个前端如果还有路由模型控制器我建议他去学后端.花里胡哨,完全是前端为了提升工资,和晋升的把戏.前端的第一性原理永远是美观的展示页面,其他的越费时间越是累赘,吹vue的别培训班教你们vue不教jquery 就黑jquery好么,多了解了解吧

**Comment by colour10** [comment]
邮件已收到,灰常感谢

**Comment by BruceLiu3385** [comment]
> 什么前后端分离,jquery一样办得到,前端复杂化是我觉得最没有意义的一件事,我完全理解不了为什么有人喜欢vue这种东西,有最快的剑不用,非得拿小刀砍人.一个前端如果还有路由模型控制器我建议他去学后端.花里胡哨,完全是前端为了提升工资,和晋升的把戏.前端的第一性原理永远是美观的展示页面,其他的越费时间越是累赘,吹vue的别培训班教你们vue不教jquery 就黑jquery好么,多了解了解吧

我之前也像你这样想，后来感觉还是得接触新的东西才行。是直接上的vue3，后来越来越感受到无论代码量，还是实现方式，确实更快速好用。

**Comment by sw586** [comment]
> 而且大多数选择快速开发的，并不关心前端框架用的是什么，只要功能能达标，界面不太难看就可以了

对了 不要跟我说那么多～～择快达标才是关键，又不是要抱着睡～～

**Comment by colour10** [comment]
邮件已收到,灰常感谢

**Comment by li272** [comment]
> > 另外您这项目如果是作为开源产品来讲的话，我觉得您应该有更多的亮点，和Laravel-admin定位还是重复的，当然您这项目的亮点就是界面比Laravel-admin漂亮。
> > 关于列表展示这块我觉得如果作为一个后台表格可以线条紧凑明显些，内容多了感觉会看得眼睛累。
> 
> 感谢建议，我会考虑优化表格样式。
> 
> 这个项目确实与laravel-admin重合，但我对很多功能细节都进行了改良和优化，增加了很多非常实用的功能，总的来说就是用的更爽，后续版本也有更重要的升级。后续会重构插件功能，上线插件市场，主要简化插件的安装、更新和卸载的步骤，这些步骤全部都放到界面管理，开发者只需轻轻点击鼠标就行了，找插件也会变得非常简单和方便。



> ### 为何不开发成前后端分离项目？
> 最近有许多同学问我为什么不采用前后端分离方案？现在`vue`和`react`这么好用，为啥还要用`jQuery`呢？回答这个问题之前首先要搞清楚两种方案的优劣势
> 
> #### 前后端分离技术的优势与劣势
> **优势**
> 
> 1. 从用户体验角度来说，前后端分离项目的用户的体验会更好一点
> 2. 从技术角度而言，前后端分离技术现在也已是主流，采用这个方案也更适合我们提升自己的前端技术熟练度
> 
> **劣势**
> 
> 1. 前后端分离技术的学习成本会更高，要求使用者必须有`vue`和`react`经验，否则就要花许多精力去学习才能上手
> 2. 前后端分离技术的引入会使项目功能扩展变得复杂和艰难，可能页面增加一个小功能，也需要单独打包前端资源，这无疑是给自己找麻烦
> 3. 这种前后端技术并不是真正意义的从团队到技术的前后端分离，也就是说如果你的前端不懂PHP代码，基本是无法接手维护你的前端代码的，其实所有工作还是需要后端一个人完成
> 
> #### jQuery技术方案的优势与劣势
> **优势**
> 
> `jQuery`项目的优点就是简单易用，效率高，学习成本极低，上手快； 扩展功能也非常地简单和灵活，基本可以让开发者摆脱冗余的HTML代码。
> 
> **劣势**
> 
> `jQuery`项目从技术角度而言已经有点落伍，属于比较老旧的技术体系。
> 
> #### 总结
> 分析完上面的两种方案的优劣势，你们大概也明白我为啥要采用`jQuery`方案了，这个项目的定位就是一个对**后端开发友好**的项目，目的是要满足大多数人的需求，追求的就是**简单**、**易用**和**高效率**，而不是提升开发者的前端技术水平。
> 
> `jQuery`虽然不是前卫的技术，但是实用性并不差，前后端分离能实现的功能，`jQuery`也一样能实现。而且在这个项目里面，你还能更快、更省事、更容易上手。 如果你是想要提升前端技术，或是展示自己的前端技术水平，那么推荐去尝试下`Laravel nova`。

感谢 jqhph 同学的开源项目！
也感谢 [ghost](https://github.com/ghost) 同学的问题，让我借问题表达我的看法！

说明一下：这里只是表达观点，但并不是带有挟持性的评论，我就是想表达一下我的使用体验：
我的身份是前段开发，会java开发，了解了一点点php，我在这个项目使用中担任的是前端工作：
1、由于这个项目的有的样式是通过注入的方式，使用已将封装好的样式，当界面不符合ui设计的时候，改封装好的样式基本不好改，只能重新在resouress/views/admin里面去重新写页面。
2、我在resouress/views/admin里面的页面，由于使用的样式是layui的样式，因为框架里面使用了layer，导致我使用layui的弹框，因为依赖冲突，出现显示异常的情况。
3、因为我php不咋了解，然后经常问后端，结果后端也要研究半天，有时候会说我也不知道，他也是刚接手的这项目。当时我那个心啊，北风那个飘。我就感觉这个项目的研究成本还是挺大的，
4、我觉得ui样式，最好能用一个就用一个，不然样式冲突了，真的好心累。由与这套框架的ui样式真的好老，我做起来比较吃力。
5、然后我不能理解的是为啥使用了layer，为啥不直接用layui。还用了bootstrap4，这个bootstrap4真的不好用，也可能是我不大会
6、我觉得前后端分离，用起来很方便，可能是因为我一直用的vue，所以接手这个类型的项目有点裂开了。
7、前后端分离也不一定是要前端用vue，也可以直接在view模块中写html的页面，现在大部分的都是前端写前端的代码，后端写后端的代码了。并且我发现做php后端的多多少少都会写前端代码。
8、最后，还是特别感谢大佬的开源！许愿大佬将这个ui都用成layui的样式，感谢感谢！

**Comment by colour10** [comment]
邮件已收到,灰常感谢
