### ISSUE TITLE
模型树页面如何新建和编辑？

### ISSUE THREAD

**Issue by datangkang123** [jqhph/dcat-admin#270]
根据文档的代码，只能显示，无法新增和编辑数据，这个form应该怎样写呢，没找到示例。

```
use Dcat\Admin\Tree;
use Dcat\Admin\Widgets\Form;

class ClassificationController extends AdminController
{
    
    //模型数显示分类
    public function index(Content $content)
    {
        return $content->header('项目分类管理')
            ->body(function (Row $row) {
                $tree = new Tree(new Classification());
                $row->column(12, $tree);
            });
    }
```

**Comment by jqhph** [comment]
新增和编辑跟普通模块一样

**Comment by datangkang123** [comment]
和普通模块一样，无法使用，点击新增，只有提交按钮，没有任何表单。
`    //模型数显示分类
    public function index(Content $content)
    {
        return $content->header('项目分类管理')
            ->body(function (Row $row) {
                $tree = new Tree(new Classification());
                $row->column(12, $tree);
            });
    }
    
    protected function form()
    {
        return Form::make(new Classification(), function (Form $form) {
            $form->display('id');
            $form->text('parent_id');
            $form->text('order');
            $form->text('title');
            $form->display('created_at');
            $form->display('updated_at');
            
        });
    }`

**Comment by datangkang123** [comment]
已解决了，不能用数据仓库Repository，要直接使用Model
