### ISSUE TITLE
工具表单table保存以后计数问题

### ISSUE THREAD

**Issue by QThans** [jqhph/dcat-admin#271]
![image](https://user-images.githubusercontent.com/18275400/85943192-02503a80-b961-11ea-81d2-144598f7699a.png)
![image](https://user-images.githubusercontent.com/18275400/85943195-07ad8500-b961-11ea-8c4d-740bbd9f22ae.png)

新增以后从new_1开始计数了。

**Comment by jqhph** [comment]
没懂这个有什么问题

**Comment by QThans** [comment]
修改的时候新增的数据会在php读数组的时候替代掉了前面的

**Comment by QThans** [comment]
知道原因了。工具表单这边保存table内容的时候不能直接写入 这样会把new_1键写入。。。
对于这个数据处理有对应方法吗？

**Comment by jqhph** [comment]
正常是不会写入new_1的

**Comment by QThans** [comment]
![image](https://user-images.githubusercontent.com/18275400/85943635-dc786500-b963-11ea-90d0-8a0a811f3944.png)
刚没注意，工具表单这边的写入不是很舒服。代码感觉不优雅，先赶进度了。。。
