### ISSUE TITLE
多应用 导入文件之后跳转的bug

### ISSUE THREAD

**Issue by LuMitchell** [jqhph/dcat-admin#272]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 1.5.0

### Description:
多应用bug问题

我在admin 导入成功之后，子页面refresh成了new_admin的页面（菜单及其他的外部的还是原来admin的），url也变成了new_admin的url：test.com/admin/goods（导入前）, test.com/new_admin/goods （导入后）。（手动刷新一下就完全到了 new_admin的界面，因为url已经变成了new_admin）（new_admin已经登录了一个账号）

### Steps To Reproduce:

商品界面有一个导入的按钮
![image](https://user-images.githubusercontent.com/29627681/85948928-40138a00-b986-11ea-8902-0152de09cf48.png)
![image](https://user-images.githubusercontent.com/29627681/85948942-50c40000-b986-11ea-8dc3-d721af5ed389.png)
按钮弹窗
![image](https://user-images.githubusercontent.com/29627681/85948965-718c5580-b986-11ea-8f2b-3464ba194458.png)
GoodImportForm：
![image](https://user-images.githubusercontent.com/29627681/85949053-f8d9c900-b986-11ea-9e84-552f4fedb1d1.png)

**Comment by jqhph** [comment]
可否贴一下配置
