### ISSUE TITLE
工具表单多tab，不能一次提交

### ISSUE THREAD

**Issue by larvacent** [jqhph/dcat-admin#273]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

工具表单走的是 widget ,不是数据表单的父类，所以不能支持tab,使用widget的tab后，多个tab成了，多个表单，不能一次提交，成了多次提交，建议原生支持这块，搞成和 数据表单一致的体验。

**Comment by jqhph** [comment]
已支持这个功能
