### ISSUE TITLE
建议后台配置文件去掉关于上传保存disk的配置

### ISSUE THREAD

**Issue by larvacent** [jqhph/dcat-admin#274]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

本身laravel自带了disk,后台在带一个，在开发的时候需要配置的地方太多了，容易忘也容易出错。建议直接使用框架自带的默认磁盘。

**Comment by jqhph** [comment]
好的，我把默认的disk改为public吧，感谢建议
