### ISSUE TITLE
数据表格行间隔很大，没有固定列的功能，显示效果不太好

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#276]
- Laravel Version: 6.2
- PHP Version: 7.3.4
- Dcat Admin Version: 1.5.2

### Description:
🥰 大大你好🥰 

现有的数据表格，20行数据会超出屏幕大小要往下拖动才能看到底部的横向滚动条。
![](https://i.imgur.com/qZMfcdz.png)

这样用起来感觉挺不方便的，要看到后面的字段总是要滚动到底部，然后拖动横向滚动条。

像悟空CRM的数据表格就很好，固定列的功能，并且行之间非常紧凑，其次展示的行数量再多也限制在屏幕大小之内。
![](https://i.imgur.com/loCChka.png)

悟空CRM演示地址：demo9.5kcrm.net(帐号：18888888888 密码：123456)

我看了看源码，用的是Element-Vue的表格组件 <https://element.eleme.cn/#/zh-CN/component/table#liu-ti-gao-du>
![](https://i.imgur.com/9rwMbeP.png)

**Comment by jqhph** [comment]
这个功能后面会加上，另外dcat是支持表格边框模式的
```php
$grid->withBorder();
```

**Comment by metanoia1989** [comment]
> 这个功能后面会加上，另外dcat是支持表格边框模式的
> 
> ```
> $grid->withBorder();
> ```
> 
> 并且你可以让表格显示10条，就不用拉到底部了

边框模式很好，数据显示更紧凑了。显示10条虽然不用拉到底部，但是分页就比较多了，数量大的时候要分好多页，如果能将表格内容限制在屏幕大小之内，像Element-Vue的表格那样就好了。

总之，谢谢大大的回复。😘

**Comment by jqhph** [comment]
已支持固定列功能，体验跟element差不多，你可以先安装master分支代码体验

**Comment by metanoia1989** [comment]
> 已支持固定列功能，体验跟element差不多，你可以先安装master分支代码体验

👍 👍 👍
