### ISSUE TITLE
求优化一下表格内行内编辑的选中状态，每次很难选中

### ISSUE THREAD

**Issue by LikeNeko** [jqhph/dcat-admin#277]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
不知道为啥放不了图，这里是图的链接⤵️
https://nekoya.oss-cn-beijing.aliyuncs.com/blog/2020-06-29-104533.png

如图所示；编辑框太小了，求优化啊！最好再加一个失去焦点自动保存的可选参数。。在这里先谢过了！

**Comment by jqhph** [comment]
好的，感谢建议

**Comment by gitzwt** [comment]
列表内的点击↓或↑排序有问题

**Comment by jqhph** [comment]
> 列表内的点击↓或↑排序有问题

你是不是设置了默认排序
