### ISSUE TITLE
如何使用数据仓库

### ISSUE THREAD

**Issue by gfd6th** [jqhph/dcat-admin#28]
里面的`get`方法不知道如何使用, 我如下使用会报错

```php
public function get(Grid\Model $model)
    {
        return [
            ['id' => 1],
        ];
    }


// productController.php

use App\Admin\Repositories\Products;
protected function grid()
    {
        return Grid::make(new Products(), function (Grid $grid) {
            $grid->id->sortable();
        }
    }
```

错误
Argument 2 passed to Illuminate\Auth\SessionGuard::__construct() must implement interface Illuminate\Contracts\Auth\UserProvider, null given,

**Comment by jqhph** [comment]
分页和不分页的返回要求是不一样的，请参考

**Comment by gfd6th** [comment]
看不太懂这里
```
public function get(Grid\Model $model)
    {
        return App\User::all();
   }
```
这样是返回不分页的吗?

**Comment by jqhph** [comment]
> 看不太懂这里
> 
> ```
> public function get(Grid\Model $model)
>     {
>         return App\User::all();
>    }
> ```
> 
> 这样是返回不分页的吗?

是的哦，如果不分页才可以这样用。如果需要分页，就要返回laravel的分页器对象
