### ISSUE TITLE
Admin类中建议添加meta方法，或者head方法

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#281]
Admin类调用的asset类中，建议增加meta或者head方法
可以方便我在head中增加meta信息。比如pre-dns-fetch之类的。
还有就是x-pjax-version等。

**Comment by jqhph** [comment]
目前已支持往`head`标签写`html`，请参考文档 http://www.dcatadmin.com/docs/master/section.html

**Comment by neatstudio** [comment]
OK。没注意这个inject的方法。
