### ISSUE TITLE
模型树，checkbox 点击选中时，显示的选中条目数量不对

### ISSUE THREAD

**Issue by YanFengQiLi** [jqhph/dcat-admin#282]
- Laravel Version: 6.18.10
- PHP Version: 7.3
- Dcat Admin Version: 1.5.3

### Description:
**模型树，checkbox 点击选中时，显示的选中条目数量不对**
![1](https://user-images.githubusercontent.com/29242666/86210812-d5da2f80-bba7-11ea-961a-5e7e0b0ea995.png)

**Comment by jqhph** [comment]
感谢反馈

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/86468656-74ae8980-bd6a-11ea-8887-397552f98ca2.png)


是不是你浏览器有缓存呢？我测试是正常的
