### ISSUE TITLE
貌似无法查询 指定时间范围的数据

### ISSUE THREAD

**Issue by 377123** [jqhph/dcat-admin#285]
` $filter->between('created_at', '开始时间')->width(6)->datetime(['format' => 'YYYY-MM-DD']); `
貌似无法查询 指定时间范围的数据  如何破

**Comment by jqhph** [comment]
可以自己写`js`限制

```php
Admin::script(
    <<<JS
$('#{XXX}').data("DateTimePicker").minDate(e.date);
JS
);
```
