### ISSUE TITLE
如何按时间更新统计字段

### ISSUE THREAD

**Issue by felixjing** [jqhph/dcat-admin#288]
### Description:
比如用户列表里自定义了一个字段，这个字段统计了订单数，现在需要可以按时间区间去统计订单数，需要建立一个时间区间选择器，然后在列表显示里获得选择器的内容。

### Steps To Reproduce:
我在filter里自定义了一个数据表没有的字段，但是提交刷选的时候会查询当前表，字段不存在会报错。
是否可以把自定义的查询字段从默认的filer查询中剔除，这样就可以在gird的自定义显示里用\Request::get()获取到时间进行查询统计。

or
其他实现方法

另：有无方法实现按统计数据列（非模型字段）进行排序？

**Comment by jqhph** [comment]
可以提出这个filter中的查询，需要重写数据仓库的`get`方法
```php
public function get(Grid\Model $model)
{
    $query = $model->getQueries()->filter(function ($q) {
        // 这里写你的过滤逻辑
   });

    $model->setQueries($query);

    return parent::get($model);
}
```

**Comment by jqhph** [comment]
其他方法也有，你可以自定义过滤器，这个更加优雅，并且代码可以复用，参考文档 http://www.dcatadmin.com/docs/master/model-grid-filters.html

**Comment by felixjing** [comment]
> 其他方法也有，你可以自定义过滤器，这个更加优雅，并且代码可以复用，参考文档[查询过滤](http://www.dcatadmin.com/docs/master/model-grid-filters.html)

thanks
