### ISSUE TITLE
希望给number currency rate等属性加小数位控制

### ISSUE THREAD

**Issue by wslsq** [jqhph/dcat-admin#289]
如->decimal(2)这样的属性，默认值0

看到form->number方法源码，居然强制转成int了，currency也只有两位，rate好像也不行。
然而要使用多位小数的情景，如区块链行业，动不动十位小数，哪一个都不合适最后只能用text。

谢谢

**Comment by jqhph** [comment]
好的，感谢建议

**Comment by Ynwaspectre** [comment]
2022年了 这个功能加了吗@jqhph ：）

**Comment by Terry-Lzz** [comment]
同问，这个功能加了么？  没有小数位控制的话，有些数据对精度影响很大

**Comment by ame1973** [comment]
同问，很多場景下確實需要小數value

**Comment by laradocs** [comment]
已收到你们的请求！

**Comment by pianzhou2021** [comment]
建议使用
$form->currency('money')->options([
                'digits'  => 16,
            ]);
            
 另外，经测试JS可能最多只支持16位数。多于16位，请按照字符处理
