### ISSUE TITLE
代码工具生成的翻译文件，出现乱码

### ISSUE THREAD

**Issue by cruelwolfking** [jqhph/dcat-admin#29]
Ɖ�机号码
1_1 ____ ____
Ǝ�荐人
0
Ǧ�分
0
VIP到期时间
输入 VIP到期时间
Ɲ�源

新增的时候，由代码工具生成的中文字是乱码

**Comment by jqhph** [comment]
感谢反馈，这个问题已解决，今晚会发布0.9.0版本，到时候更新就好了

**Comment by jqhph** [comment]
新版本v0.9.0已发布
