### ISSUE TITLE
可能算是BUG：代码生成器 

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#297]
如果采用了多项目，admin:app 创建了一个shop
在shop里访问 shop/helpers/scaffold，这时候创建的控制器啥的。还是生成在 admin 目录下。
比较尴尬。
OK，这个可以通过改 控制器的文件名解决，只是默认的还是是App\Admin\Controllers。

但。数据仓库Reposities，却仍然 创建在admin目录下。
理论上是应该在新的shop目录下？或者有个归并的地方？比如App\Reposities ？

不一定算是BUG

**Comment by neatstudio** [comment]
如果，在shop中不能访问，其实不会有这个困扰。如果能够访问了。那这样生成，确实有点困扰

**Comment by jqhph** [comment]
下个版本会优化这个问题，包括数据仓库的类名称设置

**Comment by jqhph** [comment]
已优化这个功能  9497ea695ba180f1f4b41fa528781d337e6d43a6
