### ISSUE TITLE
form::multipleSelect，可以指定最大数量吗？

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#306]
有时候确实在多选的时候会需要。比如TAG，最大5个。

需要有参数进行这样的管理

**Comment by jqhph** [comment]
```php
$form->multipleSelect('xxx')->rules('max:10');
```

**Comment by neatstudio** [comment]
确实可以
但我提一个小bug。multipleSelect的时候，提交过来的数据都会有一个空白的。
比如
```
    $form->multipleSelect('xxx');

    $form->saving(function($form){
        print_r($form->xxx);
    })
```
你会发现
```
    $form->xxx = [1,''];
```
事实上，我在request的时候，就发现
body里就是两条
```
    xxx[]:1
    xxx[]:
```
---
不知道是select 2的bug还是调用的时候产生的。我现在只能判断前处理 $form->xxx = array_filter($form->xxx);

**Comment by jqhph** [comment]
这是select2自己的问题，不需要你做处理，底层会自动处理

**Comment by neatstudio** [comment]
我在save前做关联验证的时候。。遇到这个小坑
两个mulitpleSelect，一个根据另一个的值判断。。。就遇到这个小坑了

**Comment by neatstudio** [comment]
感谢回复。既然 不是BUG，那我还是自己处理一下吧
