### ISSUE TITLE
selectResource弹窗里面如何使用筛选功能？

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#307]
- Laravel Version: 7.11.0
- PHP Version: 7.2.5
- Dcat Admin Version: 1.5.3

### Description:
selectResource 可以加个下拉选框吗？数据量大的时候需要复合查询。

**Comment by jqhph** [comment]
没明白你的意思，下拉选框你可以用select

**Comment by kunrui** [comment]
@jqhph 我想添加一个下拉选框，已经添加了相关代码。但页面上没有效果。

代码如下：
![](https://ftp.bmp.ovh/imgs/2020/07/cab11a02903ca514.png)

实际效果如下：
![](https://ftp.bmp.ovh/imgs/2020/07/cab11a02903ca514.png)

**Comment by kunrui** [comment]
页面并没有出现下拉选项

**Comment by jqhph** [comment]
```php
$grid->showFilterButton();
```

**Comment by kunrui** [comment]
好的，谢谢

建议在设置了filter方法的时候默认显示。
