### ISSUE TITLE
$('#xx-form').form和bootstrap-validator 的 $('#form').validator().on('submit' 这两个方法是不是有冲突？怎么解决？

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#308]
- Laravel Version: 7.16.1
- PHP Version: 7.3.18
- Dcat Admin Version: 1.4

### Description:
$('#xx-form').form({
    validate: true
});

写了上面的方法后，下面的方法就不执行了，不知道是不是这两个方法冲突了？有没有办法解决？

$('#form').validator().on('submit', function (e) {
  if (e.isDefaultPrevented()) {
    // handle the invalid form...
  } else {
    // everything looks good!
  }
})

**Comment by jqhph** [comment]
不知道你为啥要这么用，bootstrap-validator已经集成好了的，`$.form`的使用请参考文档[js组件](http://www.dcatadmin.com/docs/master/js.html)

**Comment by xxkrcn** [comment]
我想增加自己的前端校验，想在$.form的before里用$('#form').validator().on('submit', function (e) 这个方法，当界面的简单校验通过后，在这里执行新增加的前端校验，不知道这样的思路可不可行。

**Comment by xxkrcn** [comment]
@jqhph 谢谢， 我用自定义校验解决问题了
