### ISSUE TITLE
multipleSelect选中问题

### ISSUE THREAD

**Issue by Ambition9186** [jqhph/dcat-admin#309]
- Laravel Version: 7.12.0
- PHP Version: 7.2.9
- Dcat Admin Version: 1.5

### Description:
$form->multipleSelect('source','直播源')
            ->options(function ($source){

            })->config('minimumInputLength', '0')->ajax('/api/sources');

options 返回多个数据 怎么渲染

**Comment by jqhph** [comment]
跟单选一样的格式呀，只不过单选是只返回一个选项，多选就是多个选项

比如
```php
$form->multipleSelect('user_id')->options(function ($id) {
    if ($id) {
        return  User::find($id)->pluck('name', 'id');;
    }
});
```

**Comment by Ambition9186** [comment]
> 跟单选一样的格式呀，只不过单选是只返回一个选项，多选就是多个选项
> 
> 比如
> 
> ```
> $form->multipleSelect('user_id')->options(function ($id) {
>     if ($id) {
>         return  User::find($id)->pluck('name', 'id');;
>     }
> });
> ```

报这个错误Array to string conversion  数据格式返回很多种的 都报错

**Comment by jqhph** [comment]
这个文档有说明啊，多看看文档，要存什么格式你可以自己转化，或者你也可以通过模型修改器更改格式
```php
$form->multipleSelect('user_id')->saving(function ($id) {
    return json_encode($id);
});
```

**Comment by Ambition9186** [comment]
> 这个文档有说明啊，多看看文档，要存什么格式你可以自己转化，或者你也可以通过模型修改器更改格式
> 
> ```
> $form->multipleSelect('user_id')->saving(function ($id) {
>     return json_encode($id);
> });
> ```
好的  麻烦你了 我看下文档去
