### ISSUE TITLE
前端框架可以更换吗？

### ISSUE THREAD

**Issue by krvipsoft** [jqhph/dcat-admin#313]
应客户要求需要用到ant-design-pro这个前端框架，[https://github.com/ant-design/ant-design-pro](url)，dcat-admin可以更换吗？如果可以，那该怎么换呢？请指点！

**Comment by jqhph** [comment]
如果你是部分页面用antpro构建那是支持的，可以参考文档[自定义页面](http://www.dcatadmin.com/docs/master/custom-page.html)；

如果你想全部页面都用antpro，那你还是不要用dcat，自己写吧。
