### ISSUE TITLE
Form saved事件中如何获取模型数据

### ISSUE THREAD

**Issue by MrKaGod** [jqhph/dcat-admin#314]
- Laravel Version: 5.8
- PHP Version: 7.1.3
- Dcat Admin Version: 1.6

### Description:
在saved中打印$form->model()无法获取到数据，$form->model()->username打印为null

打印$form->builder()可以看到model数据

这是什么情况？

```php
$form->saved(function (Form $form) {
            // 查看当前分类是否有顶级
            if ($form->model()->dic_pid != 0) {
                $level = $this->check($form->model()->dic_pid, 2);
                $form->model()->level = $level;
            }

            $form->model()->dic_code = $form->model()->category_id . '_' . $form->model()->level . '_' . $form->model()->dic_id;
            $form->model()->save();
            return redirect(admin_url('dics?cid=' . $form->model()->dic_code));
        });
```

**Comment by jqhph** [comment]
正常的，你有两种方法可以获取到数据
```php
$form->saved(function ($form) {
    // 获取保存后的数据
    $updates = $form->updates();

    // 或者从数据库查
    $updates = Model::find($form->getKey());
});
```

**Comment by MrKaGod** [comment]
获取模型中的数据
$form->saved(function (Form $form) {

    $id = $form->getKey();

    $username = $form->model()->username;

    // 获取最终保存的数组
    $updates = $form->updates();
});


文档中有这样到写法啊

**Comment by jqhph** [comment]
这种写法是获取修改前的数据，新增是没有的

**Comment by MrKaGod** [comment]
好吧好吧，建议增加一下这个方法。今天刚从laravel-admin迁移过来，修改原代码时发现到。。

**Comment by jqhph** [comment]
那你需要改成
$form->updates()

**Comment by MrKaGod** [comment]
我是需要把刚新增或者编辑到数据，二次编辑

**Comment by liucodeing** [comment]
2023了，不知道有没有更新这个问题
直接用$form->model() 还是一样没有数据

用这种方式可以获取model
$form->builder()->form()->repository()->model();//可以

$form->builder()->form()->model();//没有数据
