### ISSUE TITLE
数据表格查询过滤使用过滤器组group搜索之后筛选方式会重复

### ISSUE THREAD

**Issue by xiaoterry** [jqhph/dcat-admin#316]
- Laravel Version: 5.5.49
- PHP Version: 7.3.9
- Dcat Admin Version: 1.6.0

### Description:

![WX20200716-102957](https://user-images.githubusercontent.com/10228607/87619676-5758c280-c74f-11ea-9d87-c9a1fca6ff83.png)

**Comment by jqhph** [comment]
感谢反馈

**Comment by jqhph** [comment]
已修复
