### ISSUE TITLE
后台页面缓存

### ISSUE THREAD

**Issue by cpken** [jqhph/dcat-admin#318]
- Laravel Version: 7.16.1
- PHP Version: 7.4
- Dcat Admin Version: v1.5.3

### Description:

dcat-admin 每次更改了 

```
app/Admin/Controllers/*Controller.php
```

的文件，发现都要等一段时间(以分钟记算)才会发生改变，请问这个是为什么？请问如果解决。

**Comment by jqhph** [comment]
开发环境关闭opcache

**Comment by cpken** [comment]
好的，谢谢。
