### ISSUE TITLE
show/edit/delete的时候，是否可以带上条件？

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#320]
现在都是直接ID操作。find($id);
但事实上，我们需要行级权限，比如我只能改我的数据，不能改其他人的。这时候怎么写？delete呢？

1、/show/{id}，查询的只是ID对应的数据
2、我登录后：user_id = 2，是否可以带入查询 条件： whereUserId(2);
3、因为如果没有参数，意味着我可以直接改浏览器的网址，我就能看到 其他 id的数据，而这些数据并不属于 user_id = 2

---
grid的时候。$grid()->model()->后面可以加查询 条件，但是 show/edit/delete 没有看到有地方加。
文档也没看到（也可能是我漏了）

**Comment by jqhph** [comment]
```php
new Show($id, Model::where(xxx))
```

**Comment by neatstudio** [comment]
edit呢？
我看edit好象不能这样处理。show的时候第二个参数是mode/repostory？

delete没有地方处理啊，只能重写方法？

**Comment by jqhph** [comment]
同样的道理，`delete`用的也是`form`

**Comment by neatstudio** [comment]
就是form的不知道怎么写比较好，用repository吧。带不了条件。用model吧。感觉不太对，怕不能保存（还没有试）

实在不行，我就只能当成行级权限，是不是要写一个中间件拦截一下了，就是这样要处理2次数据

**Comment by neatstudio** [comment]
就是delete方法需要重写了。
或者要看一下，是不是在repository处理了。

**Comment by jqhph** [comment]
> 就是form的不知道怎么写比较好，用repository吧。带不了条件。用model吧。感觉不太对，怕不能保存（还没有试）
> 
> 实在不行，我就只能当成行级权限，是不是要写一个中间件拦截一下了，就是这样要处理2次数据

如果你的数据是model，直接使用model就好了，除非你需要做一些定制功能

**Comment by jqhph** [comment]
> 就是delete方法需要重写了。
> 或者要看一下，是不是在repository处理了。

建议你看一下AdminController的代码

**Comment by neatstudio** [comment]
已经看了，还是决定在repository里处理了。
说白了，要么拦截在 form()->edit()/ form()->destroy() 前，要么拦截在 读取数据前

事实上也应该拦在读取数据前。否则，要修改的人至少已经看到数据了
