### ISSUE TITLE
数据表格过滤支持分组函数吗？

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#321]

**Comment by jqhph** [comment]
支持，你可以写自定义闭包，具体使用可以参考文档查询过滤章节

**Comment by xxkrcn** [comment]
麻烦再帮我看一下，$filter->groupBy('user_id')->sum('salary', function () {
                    dd(123);
                });
里面的dd不会被执行，求和方法应该怎么写？

**Comment by jqhph** [comment]
让你用闭包，你看文档了吗？

```php
$filter->where('search', function ($query) {

    $query->groupBy(xxx);

});
```

**Comment by xxkrcn** [comment]
看了，刚学习，没太看懂
