### ISSUE TITLE
七牛云上传视频（超过50M）就会失败

### ISSUE THREAD

**Issue by Seraphice** [jqhph/dcat-admin#322]
- Laravel Version: 6.#.#
- PHP Version: 7.3.14
- Dcat Admin Version: 1.6.#

### Description:
![image](https://user-images.githubusercontent.com/35662938/87667413-df18ee00-c79c-11ea-8bed-7d7e1e98e4fe.png)
图中视频70M
![image](https://user-images.githubusercontent.com/35662938/87667478-fce65300-c79c-11ea-8b78-d67f0b7af45b.png)

每次在100%进度后会卡一段时间，然后就超时了。Nginx和php.ini都设置了1200s，和3gb的上传限制，请问这是什么原因呢

**Comment by jqhph** [comment]
看看接口返回以及错误日志排查一下，这个限制大概率是七牛云那边对超过50M的文件有限制，你可以在命令行上传试试

**Comment by dfs2214785325** [comment]
![image](https://user-images.githubusercontent.com/35662938/87673077-7f274500-c7a6-11ea-911f-242596ab40d6.png)
发现是等待七牛的回调时间太长了。我在又代码里面设置了set_time_limti(0)，但是表单中还是会出现上传失败的情况，还需要修改什么地方吗（我看了看upload.js里面，好像也没有设置错误等待时间）

**Comment by jqhph** [comment]
> set_time_limti(0)

在`form`方法中加上 `set_time_limti(0)`

**Comment by tjylovezdq** [comment]
请问这个问题解决了吗?
