### ISSUE TITLE
Dcat easy excel 导入功能添加类似maatwebsite/Excel 3.1 使用例子，最好是在gird里面快捷加入

### ISSUE THREAD

**Issue by angelfreedomv** [jqhph/dcat-admin#324]
- Laravel Version:7.2
- PHP Version: 7.4
- Dcat Admin Version: 最新版

### Description:
在文档里面完善一下Dcat easy excel 使用示例，使用其他方法引用到Controller的grid里面。
我的例子 
1.比如BooksImport.php导入类
```php
<?php

namespace App\Imports;

use App\Models\Book;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class BooksImport implements ToModel, WithHeadingRow
{
    /**
     * @param array $row
     *
     * @return \Illuminate\Database\Eloquent\Model|null
     */
    public function model(array $row)
    {
        return new Book([
            'name' => $row['name'],
            'author' => $row['author'],
        ]);
    }
}
```

2. Model 模型 Book.php
```php
<?php

namespace App\Models;

use Dcat\Admin\Traits\HasDateTimeFormatter;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
	use HasDateTimeFormatter;
    //protected $table = 'books';
    //public $timestamps = false;
      protected $fillable = [
        'name', 'author',
    ];
}
```

3.BookController控制器引入 
```php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Exports\BooksExport;
use App\Imports\BooksImport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $books = Book::all();

        return view('books')->with('books', $books);
    }

    /**
     * Import function
     */
    public function import(Request $request)
    {
        if ($request->file('imported_file')) {
            Excel::import(new BooksImport(), request()->file('imported_file'));
            return back();
        }
    }


    /**
     * Export function
     */
    public function export()
    {
        return Excel::download(new BooksExport(), 'books.xlsx');
    }

}
```

### Steps To Reproduce:
希望作者在Dcat esay excel加入类似这样的示例。

**Comment by jqhph** [comment]
数据导出使用laravel-excel可以参考这个 #180

**Comment by jqhph** [comment]
下面贴一下实际使用laravel-excel导入的例子

```php
<?php

namespace App\Admin\Forms;

use Dcat\Admin\Admin;
use Dcat\Admin\Widgets\Form;
use Maatwebsite\Excel\Facades\Excel;

class ImportCreditCardForm extends Form
{
    public function handle(array $input)
    {
        // 下面的代码获取到上传的文件，然后使用`maatwebsite/excel`等包来处理上传你的文件，保存到数据库
        $file = $input['file'];

        // 读取导入文件
        $array = Excel::toArray(new CreditCardImport(), $file, 'local');

        // 你的导入逻辑

        return $this->success('导入完成！');
    }

    public function form()
    {
        $this->text('source','卡渠道')->required()->default('divvy');

        $this->file('file', '请选择文件')
            ->disk('local')
            ->autoUpload()
            ->accept('xlsx,xls,csv');
    }
}

```

**Comment by Huangjunlin** [comment]
你好，我尝试了一下上面的使用laravel-excel导入的例子，不清楚什么原因，程序不走handle方法，可以帮助解答一下吗，谢谢

```php
<?php

namespace App\Admin\Forms;

use App\Imports\AdImport;
use Dcat\Admin\Widgets\Form;
use Illuminate\Support\Facades\Log;
use Maatwebsite\Excel\Facades\Excel;

class ImportForm extends Form
{
    public function handle(array $input)
    {
        Log::error('我已经在处理了');
        // 下面的代码获取到上传的文件，然后使用`maatwebsite/excel`等包来处理上传你的文件，保存到数据库
        $file = $input['file'];

        // 读取导入文件
        $array = Excel::toArray(new AdImport(), $file, 'local');

        // 你的导入逻辑
//        var_dump($array);die;
        return $this->success('导入完成！');
    }

    public function form()
    {
        $this->file('file', '请选择文件')
            ->disk('local')
            ->autoUpload()
            ->accept('xlsx,xls,csv');
    }
}
```

```php
<?php

namespace App\Imports;

use App\Models\Ad;
use Maatwebsite\Excel\Concerns\ToModel;

class AdImport implements ToModel
{

    public function model(array $row)
    {
        return new Ad([
            'title' => $row[0],
            'platform' => $row[1],
            'create_time' => $row[2],
            'end_time' => $row[3],
            'manger' => $row[4],
            'goods' => $row[5],
            'price' => $row[6],
            'remark' => $row[7],
        ]);
    }
}

```

```php
<?php

namespace App\Admin\Controllers;

use App\Admin\Forms\ImportForm;
use App\Admin\Repositories\Ad;
use Dcat\Admin\Form;
use Dcat\Admin\Grid;
use Dcat\Admin\Layout\Content;
use Dcat\Admin\Layout\Row;
use Dcat\Admin\Show;
use Dcat\Admin\Controllers\AdminController;
use Dcat\Admin\Widgets\Alert;


class AdController extends AdminController
{

...


 public function upload(Content $content)
    {
        $description = '必须按照模板格式填写数据。<b>点击下载模板：投放数据导入模板</b>';
        $alert = Alert::make($description, '说明')->info();
        return $content->header('数据上传')
            ->row($alert)
            ->row(function (Row $row) {
                $form = new ImportForm();
                $form->disableResetButton();
                $form->disableSubmitButton();
                $row->column(12, $form);
            });
    }



```

**Comment by jqhph** [comment]
> 你好，我尝试了一下上面的使用laravel-excel导入的例子，不清楚什么原因，程序不走handle方法，可以帮助解答一下吗，谢谢
> 
> ```
> <?php
> 
> namespace App\Admin\Forms;
> 
> use App\Imports\AdImport;
> use Dcat\Admin\Widgets\Form;
> use Illuminate\Support\Facades\Log;
> use Maatwebsite\Excel\Facades\Excel;
> 
> class ImportForm extends Form
> {
>     public function handle(array $input)
>     {
>         Log::error('我已经在处理了');
>         // 下面的代码获取到上传的文件，然后使用`maatwebsite/excel`等包来处理上传你的文件，保存到数据库
>         $file = $input['file'];
> 
>         // 读取导入文件
>         $array = Excel::toArray(new AdImport(), $file, 'local');
> 
>         // 你的导入逻辑
> //        var_dump($array);die;
>         return $this->success('导入完成！');
>     }
> 
>     public function form()
>     {
>         $this->file('file', '请选择文件')
>             ->disk('local')
>             ->autoUpload()
>             ->accept('xlsx,xls,csv');
>     }
> }
> ```
> 
> ```
> <?php
> 
> namespace App\Imports;
> 
> use App\Models\Ad;
> use Maatwebsite\Excel\Concerns\ToModel;
> 
> class AdImport implements ToModel
> {
> 
>     public function model(array $row)
>     {
>         return new Ad([
>             'title' => $row[0],
>             'platform' => $row[1],
>             'create_time' => $row[2],
>             'end_time' => $row[3],
>             'manger' => $row[4],
>             'goods' => $row[5],
>             'price' => $row[6],
>             'remark' => $row[7],
>         ]);
>     }
> }
> ```
> 
> ```
> <?php
> 
> namespace App\Admin\Controllers;
> 
> use App\Admin\Forms\ImportForm;
> use App\Admin\Repositories\Ad;
> use Dcat\Admin\Form;
> use Dcat\Admin\Grid;
> use Dcat\Admin\Layout\Content;
> use Dcat\Admin\Layout\Row;
> use Dcat\Admin\Show;
> use Dcat\Admin\Controllers\AdminController;
> use Dcat\Admin\Widgets\Alert;
> 
> 
> class AdController extends AdminController
> {
> 
> ...
> 
> 
>  public function upload(Content $content)
>     {
>         $description = '必须按照模板格式填写数据。<b>点击下载模板：投放数据导入模板</b>';
>         $alert = Alert::make($description, '说明')->info();
>         return $content->header('数据上传')
>             ->row($alert)
>             ->row(function (Row $row) {
>                 $form = new ImportForm();
>                 $form->disableResetButton();
>                 $form->disableSubmitButton();
>                 $row->column(12, $form);
>             });
>     }
> ```

您禁用了表单的提交按钮，都没提交数据，怎么进`handle`方法

**Comment by Huangjunlin** [comment]
谢谢大大，被自己蠢哭了，这都没看清楚
