### ISSUE TITLE
后面在多级目录下，面包屑会显示不正确

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#328]
- Laravel Version: 7.11.0
- PHP Version: 7.4.8
- Dcat Admin Version: 1.5.3

### Description:
如下图所示：
![](https://ftp.bmp.ovh/imgs/2020/07/f6aba3143ea9082f.png)

**Comment by jqhph** [comment]
这个是正常的，你可以禁用默认的面包屑功能，自定义面包屑
