### ISSUE TITLE
关于 表单 json字段 禁止创建和删除 疑问

### ISSUE THREAD

**Issue by puzzle9** [jqhph/dcat-admin#329]
- Laravel Version: 7.x #.#.#
- PHP Version: 7.4.x #.#.#
- Dcat Admin Version: 1.6.0 #.#.#

### Description:

现在是 

![截图录屏_选择区域_20200721143424](https://user-images.githubusercontent.com/13518196/88021118-7eecc800-cb5f-11ea-85ca-36cf0c6af6fe.png)

我要改成

![截图录屏_选择区域_20200721143444](https://user-images.githubusercontent.com/13518196/88021160-94fa8880-cb5f-11ea-91be-a27c182f7d7c.png)

我改怎么改他这里的值

```
    protected $options = [
        'allowCreate' => false,
        'allowDelete' => false,
    ];
```

![截图录屏_选择区域_20200721143502](https://user-images.githubusercontent.com/13518196/88021173-9e83f080-cb5f-11ea-9394-416eef5a749c.png)

```
            $form->table('body', function (Form\NestedForm $table) {
                $table->tools(function (Form\Tools $tools) {
                     $tools->disableDelete();
                });
                $table->display('uuid');
                $table->number('value');
            });
```

**Comment by jqhph** [comment]
```php
$form->table(...)->options(['allowCreate' => true,]);
```
