### ISSUE TITLE
edit表单的时候, 如果按了回车键, 会发起delete请求

### ISSUE THREAD

**Issue by gfd6th** [jqhph/dcat-admin#33]
如题

**Comment by jqhph** [comment]
感谢反馈，周一或周二会发布新版本，到时候会修复这个问题。

**Comment by jqhph** [comment]
[已修复](https://github.com/jqhph/dcat-admin/commit/2f87e5311d690b222b3760729e6cc48d7ed49749)

**Comment by gfd6th** [comment]
好像还是一样啊, 我的意思是说, form表单编辑的时候, 在input激活的情况下, 按回车, 会跳出删除的提示

**Comment by jqhph** [comment]
同学我只是修复了这个问题，还没有发版哦，等新版本发布了就不会有这个问题了。

**Comment by gfd6th** [comment]
不是单单button改成a?

**Comment by jqhph** [comment]
请等明天新版本，然后更新即可。另外新版本会集成tinyMCE编辑器，也许你会用得上。

**Comment by gfd6th** [comment]
谢谢~
