### ISSUE TITLE
安全扫描提示有 跨站点请求伪造 的安全性问题，请问这个有直接的解决方案吗？我们Laravel 不是自带有CSRF 的吗？

### ISSUE THREAD

**Issue by kunrui** [jqhph/dcat-admin#330]
- Laravel Version: 7.11.0
- PHP Version: 7.4.8
- Dcat Admin Version: 1.5.3

### Description:
如下图所示：
![](https://ftp.bmp.ovh/imgs/2020/07/52a0ff08a813c9f4.png)

**Comment by jqhph** [comment]
laravel的csrf是针对post/put/delete等请求方法的，get请求不包含在内
