### ISSUE TITLE
excel导入

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#333]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
我想在grid工具栏添加一个商品导入的按钮，这个按钮点击之后弹出一个modal选择excel文件，然后提交之后导入。

目前遇到的问题如下：弹出框是这样的
![image](https://user-images.githubusercontent.com/24761416/88159902-8768ff80-cc40-11ea-8b0e-861bd734dc3f.png)
现在选择excel文件之后要先上传才能拿到上传到服务器的文件路径，但是文件的路径没用，提交之后handle是数组，但是没有包含file的resource类型的文件，我怎么能修改上传的方式（用laravel-admin的方式）或者我该怎么解决这个问题呢？不知道我的描述是否清晰？

我的handle是这样的

public function handle(array $input)
    {
        try {
            //$file = env('APP_UPLOAD_URL') . DIRECTORY_SEPARATOR . $input['file'];
           $file = $input['file'];
           
            Excel::import(new GoodsImportModel(), $file, 'oss');

            return $this->success('数据导入成功')->refresh();
        } catch (\Exception $e) {
            Log::error('上传失败！:' . $e->getMessage(), [$e->getTraceAsString()]);
        }
    }

**Comment by jqhph** [comment]
可以参考下以下代码，是一个用户在项目中使用的

```php
 $file = $input['file'];

$array = Excel::toArray(new CreditCardImport(), $file, 'local');
```

**Comment by joey2017** [comment]
> 可以参考下以下代码，是一个用户在项目中使用的
> 
> ```
>  $file = $input['file'];
> 
> $array = Excel::toArray(new CreditCardImport(), $file, 'local');
> ```

好的，我试试，感谢您的回复

**Comment by joey2017** [comment]
# # @jqhph 我的后台是多应用的模式，总后台及商家后台，现在我在商家后台上传excel文件提交表单的时候，获取到的用户信息是总后台的用户（应该说上传和保存的接口都是这样，路由为dcat-api/form/upload和dcat-api/form。tip：这两个路由在哪里注册的呢？我目前还没找到），我已经将总后台和商家后台的guard作了区分，获取用户信息的时候也是用商家的guard，请问一下我怎么能获取商家后台的用户信息？
