### ISSUE TITLE
【建议】二维码字段本地生成

### ISSUE THREAD

**Issue by ShynHan** [jqhph/dcat-admin#334]
- Laravel Version: 7.21.0
- PHP Version: 7.4.8
- Dcat Admin Version: 1.6.0

生成二维码用的是一个线上服务，访问的延迟比较大，可否换成 js 组件生成二维码。

**Comment by jqhph** [comment]
好的，能推荐个好用的组件吗

**Comment by ShynHan** [comment]
![image](https://user-images.githubusercontent.com/12025422/88247847-d317b980-ccd1-11ea-8616-41bc527cda6d.png)
这些是 github 上的前几名，4K star 以上，但是我都没用过，我用过这个
https://github.com/lrsjng/jquery-qrcode，
感觉区别都不大，都是生成简单的二维码

**Comment by jqhph** [comment]
好的

**Comment by jqhph** [comment]
这个功能已添加，感谢建议
