### ISSUE TITLE
编辑的时候 如何重新上传图片？

### ISSUE THREAD

**Issue by shuimohun** [jqhph/dcat-admin#335]
- Laravel Version: 7
- PHP Version: 7.2
- Dcat Admin Version: 1.6.0

编辑的时候如果想重新上传图片，
只能删除原来的图片 才能出来上传按钮，
如果数据库此字段设置不能为空 就会报错
![QQ截图20200723092807](https://user-images.githubusercontent.com/22024311/88245701-bb890280-ccca-11ea-8c29-3993eb461a45.png)

**Comment by jqhph** [comment]
1. 修改图片不一定要删除图片，可以用`disableRemove`；
2. 字段为null报错的，太多方法转换了，建议你仔细看表格基本使用文档

**Comment by gantoday** [comment]
> 1. 修改图片不一定要删除图片，可以用`disableRemove`；
> 2. 字段为null报错的，太多方法转换了，建议你仔细看表格基本使用文档

刚好我也遇到这个问题了。
这里最主要的问题是点击删除图片，马上把修改提交到服务器了。
正常应该是在点击提交的时候，才提交修改。

**Comment by gantoday** [comment]
开发者在删除图片的时候马上就提交修改应该是因为模块有 删除服务器图片文件的 逻辑。
这个逻辑也是比较少见的。常见的后台删掉图片只删引用，文件不删。
当然模块也提供了关闭自动删除功能。

**Comment by gantoday** [comment]
我加上 disableRemove 可以了。不会自动提交图片修改了。
谢谢哥
