### ISSUE TITLE
使用工具表单，hidden 字段放入 tab 布局内，hidden 字段会重复生成

### ISSUE THREAD

**Issue by yun3948** [jqhph/dcat-admin#337]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Dcat Admin Version:1.6.0

### Description:
当使用工具表单，建立了一个新的表单，里面使用了tab 布局。并且每个tab内有一个hidden 字段

### Steps To Reproduce:
代码如下：
 `       

        $this->tab('超级推荐',function(){
            $this->text('花费[]','花费')->required();
            $this->text('展现量[]','展现量')->type('number');
            $this->text('点击量[]','点击量')->type('number');
            $this->text('销量[]','销量')->type('number');
            $this->text('销售额[]','销售额')->type('number');
            $this->text('加购数[]','加购数')->type('number');
            $this->text('收藏数[]','收藏数')->type('number');
            $this->hidden('类型[]')->value('超级推荐');
        });

        $this->tab('超级推荐',function(){
            $this->text('花费[]','花费')->required();
            $this->text('展现量[]','展现量')->type('number');
            $this->text('点击量[]','点击量')->type('number');
            $this->text('销量[]','销量')->type('number');
            $this->text('销售额[]','销售额')->type('number');
            $this->text('加购数[]','加购数')->type('number');
            $this->text('收藏数[]','收藏数')->type('number');
            $this->hidden('类型[]')->value('超级推荐');
        });

`
生成结果如下：
![image](https://user-images.githubusercontent.com/12403724/88249401-f5600600-ccd6-11ea-8c83-c15aa24f9156.png)
请问可能是什么原因造成的？

**Comment by jqhph** [comment]
hidden请放到tab回调外面

**Comment by yun3948** [comment]
> hidden请放到tab回调外面

感谢回复，这个有没有别的办法解决？因为打算使用 hidden 类型的数组下标和 tab 内的数据对应起来，放在外部的话，不是那么直观

**Comment by jqhph** [comment]
没有，你可以放在最顶部

**Comment by yun3948** [comment]
好的 。感谢
