### ISSUE TITLE
对Checkbox组件动画的一点个人建议

### ISSUE THREAD

**Issue by peinhu** [jqhph/dcat-admin#338]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Dcat Admin Version: 1.6.0

### Description:
项目很棒，提点小建议，个人认为checkbox组件选中时“旋转90度再打勾”的特效给人的感觉有点不太稳重，不适合用于一些严肃的中大型商业项目，有的领导和甲方可能会不喜欢，如果能改为直接勾上就好了，可以不用那么多特效动画，个人看法。
![pic](https://user-images.githubusercontent.com/8167724/88257493-68c24180-ccf0-11ea-9d6a-80d57d85453e.png)

**Comment by jqhph** [comment]
你可以自己改css

**Comment by jqhph** [comment]
```php
Admin::style('.vs-checkbox-con .vs-checkbox {
    transform: none
    transition: none
}');
```

**Comment by peinhu** [comment]
好的谢谢
