### ISSUE TITLE
update 到 1.6 後，上傳檔案的上傳鈕不見了，拖移檔案上傳也沒有作用

### ISSUE THREAD

**Issue by arthur0102** [jqhph/dcat-admin#340]
- Laravel Version: 7.21.0
- PHP Version: 7.4.5
- Dcat Admin Version: 1.6.0

### Description:
表單中有一個上傳檔案，之前在 1.5.8 時還能正常顯示，功能也正常。
update 到 1.6.0 後，按鈕不見了，拖移檔案上傳也沒有作用。
![Admin___ImportRecord-2](https://user-images.githubusercontent.com/1409200/88270560-67047800-cd08-11ea-84b0-e1ec6490cd52.png)

Chrome 的開發人員工具，有錯誤訊息如下圖
![Admin___ImportRecord](https://user-images.githubusercontent.com/1409200/88270422-34f31600-cd08-11ea-80f5-bb56ef75109b.png)

請問要怎麼解決？

**Comment by jqhph** [comment]
参考文档版本升级须知，需要重新发布资源并理清浏览器缓存
