### ISSUE TITLE
多应用后台登录用户信息获取

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#341]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
我的后台是多应用的模式，总后台及商家后台，现在我在商家后台上传excel文件提交表单的时候，获取到的用户信息是总后台的用户（应该说上传和保存的接口都是这样，路由为dcat-api/form/upload和dcat-api/form。tip：这两个路由在哪里注册的呢？我目前还没找到），我已经将总后台和商家后台的guard作了区分，获取用户信息的时候也是用商家的guard，请问一下我怎么能获取商家后台的用户信息？

**Comment by jqhph** [comment]
guard的名称不能一样,，`Auth::guard('admin1')->user()` `Auth::guard('admin2')->user()`

**Comment by joey2017** [comment]
> guard的名称不能一样,，`Auth::guard('admin1')->user()` `Auth::guard('admin2')->user()`

我已经区分guard了，总后台用admin，商家的用store。我测试过两个应用的其它页面的打印的用户信息都是正确的，获取到的数据也是对的，就是这种弹窗表单提交的获取到的用户信息是总后台的，是不是跟admin中间件那里有关呢

**Comment by jqhph** [comment]
你是怎么获取用户信息的？如果用的是`Admin::user()`那肯定都是总后台的

**Comment by jqhph** [comment]
你提交的`dcat-api/form`前缀是什么

**Comment by jqhph** [comment]
不同的后台，提交的前缀是不一样的

**Comment by joey2017** [comment]
> 不同的后台，提交的前缀是不一样的

你提交的dcat-api/form前缀是什么 ：前缀分别是总后台admin和商家store，已经区分过了，获取用户信息的时候也是使用Auth::guard('store')->user()这个，打印出来还是admin总后台的用户信息

**Comment by jqhph** [comment]
好的我看看这个问题

**Comment by jqhph** [comment]
确实有问题，已修复，感谢反馈

**Comment by joey2017** [comment]
好的

**Comment by neatstudio** [comment]
更新了吗？我也是遇到这个问题了。
form一直报401

**Comment by jqhph** [comment]
> 更新了吗？我也是遇到这个问题了。
> form一直报401

这两天会发布新版本，等不及的可以先更新maser分支代码

**Comment by yurenzhen** [comment]
> 确实有问题，已修复，感谢反馈

感谢 @jqhph  @joey2017
