### ISSUE TITLE
表单字段动态显示，如果被隐藏的表单有required()将无法提交

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#345]
- Laravel Version: 6.2
- PHP Version: 7.3
- Dcat Admin Version: 1.6.0

### Description:
👍🏼大佬你好👍🏼。表单字段动态显示的功能是没问题的，有一些其他的问题。
* 问题1：如果联动的字段有required()设置为必填了，则被隐藏的字段也需要填写，否则无法提交表单。
* 问题2：被隐藏的联动表单其字段最后也会提交，并且后面的会覆盖前面的。像下面的例子里，主体类型我选择公司，但是最后提交的表单数据，relation_id会是选择的学员ID，并且还有pid字段。

好像这个表单动态显示，只是简单的将不显示的表单加上`display: none`的样式，如果能直接将不显示的表单dom节点移除掉就好了。😁

部分代码如下：
```php
<?php
    protected function form()
    {
        return Form::make(new FinanceRecord(), function (Form $form) {
            $relationTypes = [ Company::class => 0, Student::class => 1 ];
            $companyNames = Company::get()->pluck('company_name', 'id');

            $form->display('id');
            $form->radio('relation_type', '主体类型')
                ->customFormat(function ($value) use ($relationTypes) {
                    return $relationTypes[$value] ?? 0;
                })
                ->saving(function ($value) use ($relationTypes) {
                    return array_search((int)$value, $relationTypes);
                })
                ->when(0, function (Form $form) use ($companyNames) {
                    $form->select('relation_id', '选择公司')
                        ->options($companyNames)
                        ->placeholder('请选择');
                })
                ->when(1, function (Form $form) use ($companyNames) {
                    $form->select('relation_id', '选择学员')
                        ->options(Student::get()->pluck('student_name', 'id'))
                        ->placeholder('请选择');
                    $form->select('pid', '学员所属公司')
                        ->options($companyNames);
                })
                ->options([0 => '公司', 1 => '学员'])
                ->default(0)
                ->required();
    }
```

![](https://i.imgur.com/ph6UeKH.png)

**Comment by jqhph** [comment]
方法有很多，最简单的是用required_if------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;metanoia1989&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月24日(星期五) 上午10:59
收件人:&nbsp;&quot;jqhph/dcat-admin&quot;<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[jqhph/dcat-admin] 表单字段动态显示，如果被隐藏的表单有required()将无法提交 (#345)

**Comment by metanoia1989** [comment]
> 方法有很多，最简单的是用required_if------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;metanoia1989&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年7月24日(星期五) 上午10:59 收件人:&nbsp;&quot;jqhph/dcat-admin&quot;<dcat-admin@noreply.github.com&gt;; 抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题:&nbsp;[jqhph/dcat-admin] 表单字段动态显示，如果被隐藏的表单有required()将无法提交 (#345)

大佬你说的这个有文档吗，我好看一下具体怎么处理。☕

**Comment by jqhph** [comment]
百度 laravel required_if

```php
$form->text()->rule('required_if:xxx');
```

**Comment by jqhph** [comment]
另外文档的这个方法也可以解决字段验证的问题，其实很多功能文档都有，你可以多翻一翻
```php
protected function form()
{
    return Form::make(new Model(), function (Form $form) {
        if (...) { // 验证逻辑
            $form->responseValidationMessages('title', 'title格式错误');

            // 如有多个错误信息，第二个参数可以传数组
            $form->responseValidationMessages('content', ['content格式错误', 'content不能为空']);
        }
    });
}
```

**Comment by metanoia1989** [comment]
> 另外文档的这个方法也可以解决字段验证的问题，其实很多功能文档都有，你可以多翻一翻
> 
> ```
> protected function form()
> {
>     return Form::make(new Model(), function (Form $form) {
>         if (...) { // 验证逻辑
>             $form->responseValidationMessages('title', 'title格式错误');
> 
>             // 如有多个错误信息，第二个参数可以传数组
>             $form->responseValidationMessages('content', ['content格式错误', 'content不能为空']);
>         }
>     });
> }
> ```

😁 这个表单验证的文档我看了，不过没想到这里来。这样的话，在隐藏的表单里就不能直接用`required()`了。👍 谢谢大佬👍

**Comment by f-wangbaoshi** [comment]
使用 required_if 来解决验证问题，但是会出现 一部分表单 是 required（页面上有小红点*显示），有一部分是 必填项 但是没有 *的样式不够统一的问题。期望能解决一下～
