### ISSUE TITLE
数据表格 自定义工具栏按钮类，使用的时候提示无法找到，无法自动发现类

### ISSUE THREAD

**Issue by yun3948** [jqhph/dcat-admin#347]
- Laravel Version: 7.0.x
- PHP Version: 7.2.x
- Dcat Admin Version: 1.6.0

### Description:
按照文档新建新建自定义工具栏按钮类，无法自动发现类，执行了一次 composer update 又可以正常使用

使用的时候 

### Steps To Reproduce:

按照文档，手动新建了一个自定义工具栏按钮类文件，
`app/Admin/Extensions/Tools/StoreChartButton.php`

使用

 `use App\Admin\Grid\Tools\StoreChartButton;  
$grid->tools(new StoreChartButton('vip_store'));`

想请问是哪里的问题？

**Comment by jqhph** [comment]
应该是composer的自动加载规则有点问题，发现这样的情况可以运行`composer dump`重新生成自动加载规则试试

**Comment by yun3948** [comment]
感谢，这个是属于我本地安装的问题吗？每次新建工具栏按钮类都需要执行一次命令吗？

**Comment by jqhph** [comment]
不需要每次执行

**Comment by yun3948** [comment]
好的，多谢
