### ISSUE TITLE
form->useTable 新增没有问题，但在编辑的时候，数据没有回显

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#349]
如题，Version : 1.6

编辑的时候存进去了。
$cast = ['xx'=>'json']，换成array也一样。
在数据库中看到是一条JSON数据，出来应该变数组了。但就是在编辑的时候。table里的数据全是空的。目前还不知道怎么传进去。

nestedForm中使用了select，数据也对，但就是编辑 的时候，页面上没有显示

**Comment by jqhph** [comment]
参考文档表单关联关系

**Comment by neatstudio** [comment]
....居然是因为保存的时候，有个id:new_1。这个比较尴尬。我想想怎么处理
因为我原来是将id用作它用了
