### ISSUE TITLE
请问 有输入框联动吗

### ISSUE THREAD

**Issue by canghaisangtian** [jqhph/dcat-admin#35]
根据用户输入的内容 调用接口 填充 其它组件 目前好像只是看到下拉框有这个

**Comment by jqhph** [comment]
>  调用接口 填充 其它组件
不太明白你的意思哦，目前有下拉选框、树选择器还有弹窗选择器，不知道能不能满足你的需求。

**Comment by jqhph** [comment]
另外下拉选框是支持表单联动的。

如果内置的表单功能不能满足你现在的需求，你可以很轻松地自己扩展任何自己想要的表单，可参考文档[扩展自定义表单](http://www.dcatadmin.com/docs/master/model-form-field-management.html)
