### ISSUE TITLE
颜色选择器

### ISSUE THREAD

**Issue by zsboss** [jqhph/dcat-admin#350]
大佬,什么时候新加一个颜色选择器呢？

**Comment by jqhph** [comment]
有支持bootstrap4的颜色选择器推荐一下吗

**Comment by chiwex** [comment]
Yes. I used this for color picker field : http://mjolnic.github.io/bootstrap-colorpicker/

**Comment by jqhph** [comment]
> Yes.
> 
> https://github.com/itsjavi/bootstrap-colorpicker/

thanks

**Comment by jqhph** [comment]
已增加
