### ISSUE TITLE
一个详情显示Image的小BUG

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#351]
$detail->image->image($serverUrl,$width,$height)

默认如果不设置，就是admin.upload.disk。如果设置为：https://img.xxx.com 
事实上你会发现，如果存储在数据库里是：images/xxx.png
1、列表页，正常
2、编辑页，正常
3、详情页。。。。不正常（其他都在域名后加了 "/" ），而，详情页没有加，变成了https://img.xxx.comimages/xxx.png

**Comment by jqhph** [comment]
感谢反馈
