### ISSUE TITLE
建议增加主内容页侧边栏组件。就是在内容页里再嵌入一个左侧菜单栏

### ISSUE THREAD

**Issue by gantoday** [jqhph/dcat-admin#352]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
就是在内容页里再嵌入一个左侧菜单栏。现在已经有一个左侧菜单栏，建议增加在内容页显示的第二个左侧菜单栏组件。
其实是我做项目要用到，但是自己不会写。哈哈。开发者可以考虑一下，有价值的话可以加上。
谢谢开发者。这个模块很棒，还在研究中。

**Comment by jqhph** [comment]
菜单模板是可以单独更改的，可以参考文档 [区块](http://www.dcatadmin.com/docs/master/section.html)，你说的这个功能后面可以考虑做成插件

**Comment by gantoday** [comment]
![image](https://user-images.githubusercontent.com/7780154/88496302-49c4f780-cfef-11ea-85f5-9ed999a2728c.png)
类似这样的。漂亮
