### ISSUE TITLE
数据表格固定列的问题：行下拉菜单会被隐藏、鼠标右键拉下拉菜单在固定列上无法触发

### ISSUE THREAD

**Issue by metanoia1989** [jqhph/dcat-admin#355]
- Laravel Version: 6.2
- PHP Version: 7.3
- Dcat Admin Version: 1.6.0

# Description:
😁 大佬你好，我使用数据表格的固定列功能时，遇到了一些问题。

## 固定列 + 行操作按钮的下拉菜单
使用`$grid->fixColumns(6, 1)`固定列，行操作按钮使用 DropdownActions **下拉菜单**方式，点击下拉菜单，会被遮盖掉一部分。
![](https://i.imgur.com/SIbAOH7.png)

发现是 `.table-fixed` 设置了 `overflow: hidden`样式，将其注释掉，就能够显示出来了，但是其y轴上由过于长了。
![](https://i.imgur.com/8p0Ed8a.png)
![](https://i.imgur.com/2VIkmAM.png)

## 固定列 + 行操作按钮的鼠标右键显示下拉菜单
使用 ContextMenuActions 鼠标右键显示下拉菜单的时候，只能在中间可以移动的列上弹出菜单，左边跟右边的列都不能弹出菜单。
![](https://i.imgur.com/o8gpOBz.png)

## 固定列 表格底部的缝隙问题
使用固定列时，拖动中间的列，表格底部会有点缝隙。
![](https://i.imgur.com/od518cd.png)

将table-fixed-left的max-height 改成 588px 就好了 
![](https://i.imgur.com/199BKc0.png)

**Comment by jqhph** [comment]
这个问题暂时没找到合适的解决方案
