### ISSUE TITLE
请问在表格表单中，如果有个字段也需要是表格表单要怎么写？

### ISSUE THREAD

**Issue by Lin1274** [jqhph/dcat-admin#356]
![image](https://user-images.githubusercontent.com/52941309/88528476-40f51580-d031-11ea-9a57-37117bf99748.png)
![image](https://user-images.githubusercontent.com/52941309/88528136-cdeb9f00-d030-11ea-8a8f-3bb9347b43ed.png)

**Comment by jqhph** [comment]
表格是不支持嵌套的，这种你只能通过自定义组件的方式自己实现了
