### ISSUE TITLE
更改表格數據同時更改同列其他欄位值？

### ISSUE THREAD

**Issue by minchemo** [jqhph/dcat-admin#357]
- Laravel Version: 7.3.0
- PHP Version: 7.3.0
- Dcat Admin Version: 1.6.0

### Description:

![擷取](https://user-images.githubusercontent.com/22622775/88528517-4b171400-d031-11ea-95a8-fbc9718d2bf1.PNG)

開發者你好，我有個使用上的疑問，文件翻了好久翻不到，代碼改了改還是一直報錯，想問問是否有比較合適的作法？

我想要在行內的post更改發布狀態(status)的時候，也要同時修改消失時間欄位(disappear_at)的值，以下是$form的代碼。

```
$form->switch('status')->saving(function ($v) {
                DB::table('discussion')->where('id', $id)->update(array('disappear_at' => date('Y-m-d H:i:s', strtotime('+1 day', time()))));
                return $v;
});
```

但是 $id 的值試過各種辦法抓不到該列的ID，該怎麼做比較好呢，或有沒有更好的寫法

**Comment by jqhph** [comment]
```php
$form->switch('status')->saving(function ($v) use ($form) {
    DB::table('discussion')->where('id', $form->getKey())->update(array('disappear_at' => date('Y-m-d H:i:s', strtotime('+1 day', time()))));
    return $v;
});
```

**Comment by minchemo** [comment]
解決了！回復好快，感謝哥
