### ISSUE TITLE
请问一下多级联动下拉选框如何实现？

### ISSUE THREAD

**Issue by stevenleeyu** [jqhph/dcat-admin#36]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
系统内置下拉菜单二级联动功能，请参考文档[表单字段使用](http://www.dcatadmin.com/docs/master/model-form-fields.html)。

如果需要三级联动，可参考这个项目的实现https://github.com/fengyuanchen/distpicker。

**Comment by jqhph** [comment]
dcatadmin省市区联动插件 https://github.com/super-eggs/dcat-admin-extensions-distpicker

**Comment by leetotti** [comment]
多级联动  编辑的时候  失去默认值  现在有解决了吗

**Comment by jqhph** [comment]
> 多级联动 编辑的时候 失去默认值 现在有解决了吗

新版本`default`方法第二个参数可以传`true`，这样可以在编辑页面使用默认值功能 `default(xxx, true)`
