### ISSUE TITLE
快捷创建中的缺陷

### ISSUE THREAD

**Issue by cyfflying** [jqhph/dcat-admin#360]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
使用快捷创建，使用$create->mobile('fieldname')并没有实现在数据表单中的输入过滤，需要手工引入@jquery.inputmask，不知道这算不算bug，未验证其他快捷输入类型

**Comment by jqhph** [comment]
感谢反馈，下个版本会修复
