### ISSUE TITLE
设置动态表单提示 when 方法不存在

### ISSUE THREAD

**Issue by Ambition9186** [jqhph/dcat-admin#362]
- Laravel Version: 7
- PHP Version: 7.2.5
- Dcat Admin Version: 2.0

### Description:
Method Dcat\Admin\Form\Field\Radio::when does not exist.

**Comment by jqhph** [comment]
Dcat Admin Version: 2.0 是什么鬼。。这个功能需要把`dcat-admin`升级到`1.6`版本，另外今天晚上会有新版本发布，你也可以晚上再更新

**Comment by Ambition9186** [comment]
> Dcat Admin Version: 2.0 是什么鬼。。这个功能需要把`dcat-admin`升级到`1.6`版本，另外今天晚上会有新版本发布，你也可以晚上再更新

好的  谢谢

**Comment by jqhph** [comment]
新版本1.6.5已发布
