### ISSUE TITLE
multipleSelect 如何设置选中项？

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#364]
options。用的是pluck('name','id')

编辑的时候，因为是这个字段是虚拟字段，需要做2次处理的。设置value的时候是将保存的id取出来。放进去，但没有选中:value([1,2])

不知道怎么写法。看了ajax方法，也只是load options而己。所以一下子不知道怎么设置值了

**Comment by neatstudio** [comment]
value设置不了。我用default....可以了。

**Comment by neatstudio** [comment]
今天再次测试的时候。又不正常了
default用的值在编辑的时候，显示为空。但是新增是正常的。这该让人怎么办？

**Comment by neatstudio** [comment]
直接在From::make里用不正常。
然后在xxx extends Form里使用 $this->multipleSelect，这个是正常的。

一下子不明白原因了。等我排查一下

**Comment by jqhph** [comment]
编辑页面default方法不生效，如果需要设置默认值需要用customFormat方法，具体使用可以参考表单字段使用文档

**Comment by neatstudio** [comment]
widget里的form，调用的是正常的。
直接Form类调用的是不正常的。

**Comment by neatstudio** [comment]
嗯。看到了。确实是这样。我一直错误的理解customFormat是为了在提交的时候的值。

格式化待渲染的数据 (customFormat)...这里的理解有偏差。OK，现在没问题了
