### ISSUE TITLE
请问表单的字段动态显示功能，同个字段需要不同的显示方式要如何做？

### ISSUE THREAD

**Issue by Lin1274** [jqhph/dcat-admin#365]
当我有个相同的字段需要显示两种不同的内容时，需要如何写？我这样写并不能达到预期的效果。

![image](https://user-images.githubusercontent.com/52941309/88748839-9db51500-d184-11ea-99df-e52cf8fff23b.png)

![image](https://user-images.githubusercontent.com/52941309/88748572-eddfa780-d183-11ea-9f81-781512332bad.png)

**Comment by jqhph** [comment]
字段名称不能相同，你可以换个新的名称，然后在`saving`事件中对表单的值进行重新赋值

**Comment by xs47968224** [comment]
> 字段名称不能相同，你可以换个新的名称，然后在`saving`事件中对表单的值进行重新赋值

我说怎么保存不了呢。。。尴尬
