### ISSUE TITLE
同个页面多表格情况下右键弹窗方式,的添加子定义菜单 紊乱

### ISSUE THREAD

**Issue by linechengchen** [jqhph/dcat-admin#369]
[-](url) Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/25653824/88776676-db339580-d1b8-11ea-9fc5-b9d7830e71a2.png)
![image](https://user-images.githubusercontent.com/25653824/88776765-fbfbeb00-d1b8-11ea-824c-2231d6697e66.png)
 点过一次后 编辑2 就变成编辑

**Comment by jqhph** [comment]
多表格情况下先用dropdown代替
