### ISSUE TITLE
权限tree遇到问题

### ISSUE THREAD

**Issue by QThans** [jqhph/dcat-admin#371]
权限Tree支持多少层级？
目前报错：Uncaught TypeError: Cannot read property 'children' of undefined

**Comment by jqhph** [comment]
理论上是无限制的

**Comment by QThans** [comment]
![FireShot Capture 003 - Admin - 权限 - bpm uinge com](https://user-images.githubusercontent.com/18275400/89063722-4b017600-d39b-11ea-9657-83e235959e44.png)

能麻烦看下不，权限tree加载不出来
