### ISSUE TITLE
数据表单里同时使用JSON表单与Ckeditor 4 会遇上冲突

### ISSUE THREAD

**Issue by pkkbkraa** [jqhph/dcat-admin#372]
- Laravel Version: 7.22.4
- PHP Version: 7.2.29
- Dcat Admin Version: 1.#.#

### Description:
<img width="700" alt="截圖 2020-07-29 下午10 14 12" src="https://user-images.githubusercontent.com/7637784/88815910-6f6c1f80-d1ee-11ea-9913-47d6e1bee8cd.png">

**Comment by jqhph** [comment]
请参考文档[表单字段管理](http://www.dcatadmin.com/docs/master/model-form-field-management.html)，需要做一些特殊处理

**Comment by pkkbkraa** [comment]
> 请参考文档[表单字段管理](http://www.dcatadmin.com/docs/master/model-form-field-management.html)，需要做一些特殊处理

已经做过处理了，单独使用ckeditor时是没事的，但是当使用了json表单就会error

<img width="1361" alt="截圖 2020-07-29 下午11 15 13" src="https://user-images.githubusercontent.com/7637784/88818633-7e080600-d1f1-11ea-92d4-6dcb7f27bc7d.png">
<img width="1359" alt="截圖 2020-07-29 下午11 15 45" src="https://user-images.githubusercontent.com/7637784/88818668-86604100-d1f1-11ea-8b2c-771d8d0b6705.png">
