### ISSUE TITLE
How can i be able to add two grid table on the same page

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#373]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

i added two grid table on the same page. when i clicked on the button of the second grid. the first table receives the event instead of the second grid table. For example, whenever i click on the display all button, the first table receives the event.

**Comment by jqhph** [comment]
try this
```php
$grid->setName('grid1');
```

```php
$grid->setName('grid2');
```

**Comment by chiwex** [comment]
Thank you. it is working as i expected
