### ISSUE TITLE
建议增加一种字段类型：创建的时候可以填，编辑的时候不能改

### ISSUE THREAD

**Issue by gantoday** [jqhph/dcat-admin#374]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
创建的时候可以填，编辑的时候不能改的字段很常见。比如登录名，某个标识之类的。
现在的dcat-admin多写几行代码也能实现这个功能。
但是考虑他是常见需求。建议增加一个内置字段类型。

### Steps To Reproduce:
谢谢开发者。

**Comment by jqhph** [comment]
你可以自己扩展，参考

https://github.com/jqhph/dcat-admin/pull/159

**Comment by gantoday** [comment]
看了。感觉很棒。谢谢。

**Comment by gantoday** [comment]
@jqhph 扩展方法之后功能没问题。
但是没有自动补全，并且在编辑器里显示为黄色。
请问这有什么方法解决吗。

**Comment by jqhph** [comment]
你看一下根目录有个ide_helper.php，模仿这个内容自己写一个

**Comment by gantoday** [comment]
@jqhph 谢谢。
再问一下。怎么扩展自定义的表单类型呢？
比如我要增加一个七牛客户端直传的表单类型。
希望在表单里直接这样调用：
> $form->qiniuImage('image')
要怎么实现呢？
