### ISSUE TITLE
多对多能创建，但编辑报错。

### ISSUE THREAD

**Issue by Millyn** [jqhph/dcat-admin#375]
- Laravel Version: 7.22.4
- PHP Version: 7.4.8
- Dcat Admin Version: Master

### Description:
一个简单的多对多关系，3张表。
```
goods_table
id
name

// ----
goods_tag_table
id
name

// ----
goods_has_tag_table
id
goods_id
tag_id
```

给 Goods 定义关系

```
use App\Models\Tag; 
class Goods extends Model
{
    public function tags(): BelongsToMany
    {
        return $this->belongsToMany(Tag::class, 'goods_has_tag', 'goods_id', 'tag_id');
    }
}
```

在 GoodsController  的`form`方法里使用 `multipleSelect` 多选 Tags
```
use App\Models\Tag; 

    protected function form()
    {
        $repository = new Goods(['tags']);
        return Form::make($repository, function (Form $form) {
            $form->display('id');
            $form->text('name');
            $form->multipleSelect('tags')->options(Tag::all()->pluck('name', 'id'));
            $form->display('created_at');
            $form->display('updated_at');
            $form->disableViewButton();
        });
    }
```

这时候，创建 Goods 没问题，表也正常写入，但编辑 Goods 时会报错：

`Array to string conversion` 错误是 数组转 String 时出错？那么请问这块需要什么样的数据结构呢？

这块文档较少，希望可以讨论或丰富下文档的案例。

![image](https://user-images.githubusercontent.com/7987563/88935960-e23fce00-d2b4-11ea-8d70-527162cd81fa.png)
![image](https://user-images.githubusercontent.com/7987563/88935999-ec61cc80-d2b4-11ea-9c1d-ef05c782828d.png)

## 额外问题

我按照文档里 http://www.dcatadmin.com/docs/master/model-relationship.html 的 **多对多** 例子写，在实际过程中会爆出`allNodes`方法不找不到。

**Comment by jqhph** [comment]
数组当然不能直接保存，你需要通过模型修改器或以下方法转换数据格式

```php
$form->multipleSelect('tags')->options(Tag::all()->pluck('name', 'id'))->saving(function ($v) {
    return json_encode($v);
});
```

**Comment by jqhph** [comment]
我按照文档里 http://www.dcatadmin.com/docs/master/model-relationship.html 的 多对多 例子写，在实际过程中会爆出allNodes方法不找不到。

-----

这个是因为你没有看`tree`表单的用法导致的

**Comment by jqhph** [comment]
前面说错了，多对多之所以报错，是因为查出来的数据是一个二维数组，应该改成这样

```php
$form->multipleSelect('roles', trans('admin.roles'))
                    ->options(function () {
                        $roleModel = config('admin.database.roles_model');

                        return $roleModel::all()->pluck('name', 'id');
                    })
                    ->customFormat(function ($v) {
                        // 二维数组转一维
                        return array_column($v, 'id');
                    });
```

**Comment by Millyn** [comment]
> 前面说错了，多对多之所以报错，是因为查出来的数据是一个二维数组，应该改成这样
> 
> ```
> $form->multipleSelect('roles', trans('admin.roles'))
>                     ->options(function () {
>                         $roleModel = config('admin.database.roles_model');
> 
>                         return $roleModel::all()->pluck('name', 'id');
>                     })
>                     ->customFormat(function ($v) {
>                         // 二维数组转一维
>                         return array_column($v, 'id');
>                     });
> ```

谢谢，有效，最近是因为一个项目我接触到该库，真的是太方便了，等项目结束，我希望我能为文档产生一些贡献。 :D
