### ISSUE TITLE
breadcrumb如何设置成全中文

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#377]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
面包屑如何设置成全中文呀？

**Comment by jqhph** [comment]
两个方法

1. 参考文档 [多语言](http://www.dcatadmin.com/docs/master/trans.html)
2. 使用自定义面包屑功能，参考文档[开发前必读](http://www.dcatadmin.com/docs/master/notice.html)

**Comment by joey2017** [comment]
好的哇，是我没仔细看 默认面包屑翻译 那里
