### ISSUE TITLE
在grid的actions闭包里面如何调用当前控制器类的其他方法

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#378]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version:1.6

### Description:
$grid->actions(function (Grid\Displayers\Actions $actions) {
           $this->getAdminer();//这个$this是当前行数据对象，我在这里是否可以调用控制器的其他方法，如果不行，有什么解决办法吗？
        });

**Comment by jqhph** [comment]
```php
$self = $this;

$grid->actions(function (Grid\Displayers\Actions $actions) use ($self) {
    $self->getAdminer();
});
```

**Comment by joey2017** [comment]
试了，报错Method App\Enterprise\Controllers\UserController::form does not exist.       form()方法在UserController里已经定义
