### ISSUE TITLE
我想在Row上扩展一个自定义style的方法，看看可以添加上去吗

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#381]
namespace Dcat\Admin\Layout;

    public function style($style, $content, $width = 12)
    {
        $width = $width < 1 ? round(12 * $width) : $width;
        
        $column = new Column($content, $width, $style);

        $this->addColumn($column);
    }

然后这样使用
                $row->style('padding-right: 65px;', view('XXX'), 10);

**Comment by jqhph** [comment]
有更好的方案，不过这个方法不是很必要

**Comment by Warrens-yg** [comment]
我现在想实现左右的布局，但是bootstrap栅格的话不太好匹配，想着通过style调节，不知道更好的方案是什么，能否具体介绍一下。
