### ISSUE TITLE
请问开启quicksearch后,一对多关系的字段如何查询呢?

### ISSUE THREAD

**Issue by baozilala** [jqhph/dcat-admin#382]
- Laravel Version: 7.22.4
- PHP Version: 7.3.8
- Dcat Admin Version: 1.6.5

### Description:
请问开启quicksearch后,一对多关系的字段如何查询呢?
订单列表和客户列表,其中订单列表中的客户字段储存了客户ID, 在开启quicksearch后尝试着放入client.name字段无法实现,看了文档中的grid和快速搜索,没有找到解决方案,请问有类似问题的朋友有解决方案吗?谢谢

**Comment by jqhph** [comment]
可以写闭包，文档有

```php
$grid->quickSearch(function ($model, $query) {
    $model->where('title', $query)->orWhere('desc', 'like', "%{$query}%");
});
```

**Comment by baozilala** [comment]
看来还是直接把用户信息写入到一个表里比较方便.
感谢 @jqhph 的快速回复.关闭了
