### ISSUE TITLE
请把demo仓库的代码更新到最新版。

### ISSUE THREAD

**Issue by gantoday** [jqhph/dcat-admin#386]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
我下载了demo的代码。运行发现和演示的有点差别。
我是菜鸟，想看看演示的 Expand 里附加 Table 的实现。
所以，想请开发者把demo仓库提交最新版代码。
万分感激。😆

**Comment by jqhph** [comment]
好的

**Comment by gantoday** [comment]
@jqhph 谢谢哥

**Comment by jqhph** [comment]
已更新

**Comment by gantoday** [comment]
@jqhph 我删掉旧的项目，重新clone新的demo代码。
然后执行 composer install。出现问题了：
![image](https://user-images.githubusercontent.com/7780154/89486163-02035480-d7d5-11ea-9549-5de383f110d3.png)

**Comment by jqhph** [comment]
版本兼容有点问题，你可以手动改一下先

**Comment by gantoday** [comment]
@jqhph 那个。。。我不知道怎么改。

**Comment by jqhph** [comment]
已修复，重新拉取一下

**Comment by gantoday** [comment]
谢谢哥
