### ISSUE TITLE
form->table useTable中的表单无法调整宽度 

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#387]
如题
不管是用width/attribute/等等，都无效。。
现在是select框特别小。number框特别长。

**Comment by jqhph** [comment]
这个只能通过自己写css调整了

**Comment by neatstudio** [comment]
试了一下，通过CSS确实可以进行调整了。就是 痛苦了一点。因为是根据form->xxx(name)的name来生成的class。
所幸，table里的元素不会太多，只要写上4~5条也就OK了
