### ISSUE TITLE
我使用工具表单实现网站多tab配置 图片字段有值但无法回显，请教一下

### ISSUE THREAD

**Issue by nianwd** [jqhph/dcat-admin#393]
- Laravel Version: 6.18
- PHP Version: 7.3
- Dcat Admin Version: 1.6.0

### Description:
![image](https://user-images.githubusercontent.com/19748978/89275185-838fa100-d674-11ea-96e6-45dd4822c8cf.png)

![image](https://user-images.githubusercontent.com/19748978/89275554-00bb1600-d675-11ea-89d9-6cd52ad46f9a.png)

**Comment by jqhph** [comment]
图片字段的值需要是一个数组，并且你可以在工具表单的`default`方法返回

**Comment by nianwd** [comment]
> 图片字段的值需要是一个数组，并且你可以在工具表单的`default`方法返回

谢谢大佬，回复好快！
