### ISSUE TITLE
JSON格式字段如何显示自定义字段验证错误信息

### ISSUE THREAD

**Issue by pkkbkraa** [jqhph/dcat-admin#394]
- Laravel Version: 7.22.4
- PHP Version: 7.2.29
- Dcat Admin Version: 1.6.5

### Description:
表单设置成JSON后，加入了校验规则却没显示自定义的错误信息

**Comment by jqhph** [comment]
贴代码看看

**Comment by pkkbkraa** [comment]
<img width="524" alt="截圖 2020-08-05 下午1 01 46" src="https://user-images.githubusercontent.com/7637784/89373719-00298a80-d71c-11ea-8498-8d8a2e67280d.png">
<img width="367" alt="截圖 2020-08-05 下午1 02 27" src="https://user-images.githubusercontent.com/7637784/89373725-061f6b80-d71c-11ea-8440-f898fc48505c.png">

**Comment by jqhph** [comment]
`['email.email' => trans(xxx)]`

**Comment by pkkbkraa** [comment]
改了，仍然是一样的

**Comment by jqhph** [comment]
json和table这种字段比较特殊，那就只能走默认的验证规则翻译文件了。

**Comment by pkkbkraa** [comment]
了解了，感谢您
