### ISSUE TITLE
表单保存提示Array to string conversion

### ISSUE THREAD

**Issue by dwheng** [jqhph/dcat-admin#40]
我用$form->checkbox('t_id','推荐位')->options([1 => 'foo', 2 => 'bar', 'val' => 'Option name']);
点击保存时，提示"Array to string conversion"，求解决方法

**Comment by jqhph** [comment]
checkbox表单保存的数据是array格式，需要自己转换一下。

```php
$form->checkbox('t_id','推荐位')->options(...)->saving(function ($v) {
    return json_encode($v);
});
```

![image](https://user-images.githubusercontent.com/20312339/80184741-ba99f380-863d-11ea-9132-8421149fbcbb.png)
