### ISSUE TITLE
Additional params when upload single/multiple file

### ISSUE THREAD

**Issue by folkevil** [jqhph/dcat-admin#401]
- Laravel Version: 7.x
- PHP Version: 7.4
- Dcat Admin Version: 2.x

### Description:
How can I add additional params using the custom upload URL? For example, I want to upload multiple images and add other information like category_id, tags,...etc

**Comment by jqhph** [comment]
```php
$form->multipleFile(xxx)->url(xxx)->withFormData(['category_id' => xxx]);
```

**Comment by folkevil** [comment]
Sorry for late reply, but how can i get value from other fields in the same form without click submit button (data should attach when uploading file)

**Comment by jqhph** [comment]
Upgrade to the latest version

```php
composer remove dcat/laravel-admin
composer require dcat/laravel-admin:"2.0.12-beta"
php artisan admin:publish --assets --migrations --force
php artisan migrate
```

and 

```php
$form->file('...')
    ->on('startUpload', <<<JS
        function () {
            console.log('start', this);

            this.uploader.options.formData['custom_field'] = $('other field').val();
        }
JS
    )
```

**Comment by folkevil** [comment]
Thanks, you saved my day.
