### ISSUE TITLE
操作日誌異常 ErrorException In Arr.php line 151

### ISSUE THREAD

**Issue by amtbnagios** [jqhph/dcat-admin#403]
- Laravel Version: 6.18.14
- PHP Version: 7.2.31
- Dcat Admin Version: 1.6.0

### Description:
點 操作日誌 今天上午時常出現下面錯誤，但有些分頁可以顯示出數據；
                    下午的時候，操作日誌完全點不出來了，就一直顯示下面錯誤（操作日誌表大約1.6萬條記錄）

ErrorException In Arr.php line 151 :
  array_key_exists() expects parameter 2 to be array, null given

#0 [internal function]: Illuminate/Foundation/Bootstrap/HandleExceptions->handleError(2, 'array_key_exist...', '/data/www/amtbw...', 151, Array)
#1 vendor/laravel/framework/src/Illuminate/Support/Arr.php(151): array_key_exists('_pjax', NULL)
#2 vendor/laravel/framework/src/Illuminate/Support/Arr.php(249): Illuminate/Support/Arr::exists(NULL, '_pjax')
#3 vendor/laravel/framework/src/Illuminate/Support/Arr.php(133): Illuminate/Support/Arr::forget(NULL, Array)
#4 vendor/dcat/laravel-admin/src/Controllers/LogController.php(48): Illuminate/Support/Arr::except(NULL, Array)
#5 vendor/dcat/laravel-admin/src/Grid/Column.php(506): Dcat/Admin/Controllers/LogController->Dcat/Admin/Controllers/{closure}(NULL, Object(Dcat/Admin/Grid/Column))
#6 vendor/dcat/laravel-admin/src/Grid/Column.php(562): Dcat/Admin/Grid/Column->callDisplayCallbacks('{"_token":"1A0K...')
#7 vendor/dcat/laravel-admin/src/Grid.php(433): Dcat/Admin/Grid/Column->fill(Array)
#8 [internal function]: Dcat/Admin/Grid->Dcat/Admin/{closure}(Object(Dcat/Admin/Grid/Column), 'input')
#9 vendor/laravel/framework/src/Illuminate/Support/Collection.php(638): array_map(Object(Closure), Array, Array)
#10 vendor/dcat/laravel-admin/src/Grid.php(436): Illuminate/Support/Collection->map(Object(Closure))
#11 vendor/dcat/laravel-admin/src/Grid.php(929): Dcat/Admin/Grid->build()
#12 vendor/dcat/laravel-admin/src/Support/Helper.php(119): Dcat/Admin/Grid->render()
#13 vendor/dcat/laravel-admin/src/Layout/Column.php(93): Dcat/Admin/Support/Helper::render(Object(Dcat/Admin/Grid))
#14 vendor/dcat/laravel-admin/src/Layout/Row.php(59): Dcat/Admin/Layout/Column->render()
#15 vendor/dcat/laravel-admin/src/Layout/Content.php(285): Dcat/Admin/Layout/Row->render()
#16 vendor/dcat/laravel-admin/src/Layout/Content.php(450): Dcat/Admin/Layout/Content->build()
#17 vendor/dcat/laravel-admin/src/Layout/Content.php(534): Dcat/Admin/Layout/Content->variables()
#18 vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Dcat/Admin/Layout/Content->render()
#19 vendor/symfony/http-foundation/Response.php(205): Illuminate/Http/Response->setContent(Object(Dcat/Admin/Layout/Content))
#20 vendor/laravel/framework/src/Illuminate/Routing/Router.php(749): Symfony/Component/HttpFoundation/Response->__construct(Object(Dcat/Admin/Layout/Content), 200, Array)
#21 vendor/laravel/framework/src/Illuminate/Routing/Router.php(721): Illuminate/Routing/Router::toResponse(Object(Illuminate/Http/Request), Object(Dcat/Admin/Layout/Content))
#22 vendor/laravel/framework/src/Illuminate/Routing/Router.php(681): Illuminate/Routing/Router->prepareResponse(Object(Illuminate/Http/Request), Object(Dcat/Admin/Layout/Content))
#23 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate/Routing/Router->Illuminate/Routing/{closure}(Object(Illuminate/Http/Request))
#24 vendor/dcat/laravel-admin/src/Middleware/WebUploader.php(21): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#25 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/WebUploader->handle(Object(Illuminate/Http/Request), Object(Closure))
#26 vendor/dcat/laravel-admin/src/Middleware/Session.php(19): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#27 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/Session->handle(Object(Illuminate/Http/Request), Object(Closure))
#28 vendor/dcat/laravel-admin/src/Middleware/Permission.php(39): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#29 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/Permission->handle(Object(Illuminate/Http/Request), Object(Closure))
#30 vendor/dcat/laravel-admin/src/Middleware/Bootstrap.php(19): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#31 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/Bootstrap->handle(Object(Illuminate/Http/Request), Object(Closure))
#32 vendor/dcat/laravel-admin/src/Middleware/LogOperation.php(41): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#33 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/LogOperation->handle(Object(Illuminate/Http/Request), Object(Closure))
#34 vendor/dcat/laravel-admin/src/Middleware/Pjax.php(24): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#35 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/Pjax->handle(Object(Illuminate/Http/Request), Object(Closure))
#36 vendor/dcat/laravel-admin/src/Middleware/Authenticate.php(27): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#37 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/Authenticate->handle(Object(Illuminate/Http/Request), Object(Closure))
#38 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#39 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Routing/Middleware/SubstituteBindings->handle(Object(Illuminate/Http/Request), Object(Closure))
#40 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(76): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#41 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Foundation/Http/Middleware/VerifyCsrfToken->handle(Object(Illuminate/Http/Request), Object(Closure))
#42 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#43 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/View/Middleware/ShareErrorsFromSession->handle(Object(Illuminate/Http/Request), Object(Closure))
#44 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#45 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Session/Middleware/StartSession->handle(Object(Illuminate/Http/Request), Object(Closure))
#46 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#47 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse->handle(Object(Illuminate/Http/Request), Object(Closure))
#48 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#49 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Cookie/Middleware/EncryptCookies->handle(Object(Illuminate/Http/Request), Object(Closure))
#50 vendor/dcat/laravel-admin/src/Middleware/Application.php(15): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#51 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Dcat/Admin/Middleware/Application->handle(Object(Illuminate/Http/Request), Object(Closure), 'admin')
#52 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#53 vendor/laravel/framework/src/Illuminate/Routing/Router.php(683): Illuminate/Pipeline/Pipeline->then(Object(Closure))
#54 vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate/Routing/Router->runRouteWithinStack(Object(Illuminate/Routing/Route), Object(Illuminate/Http/Request))
#55 vendor/laravel/framework/src/Illuminate/Routing/Router.php(624): Illuminate/Routing/Router->runRoute(Object(Illuminate/Http/Request), Object(Illuminate/Routing/Route))
#56 vendor/laravel/framework/src/Illuminate/Routing/Router.php(613): Illuminate/Routing/Router->dispatchToRoute(Object(Illuminate/Http/Request))
#57 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(170): Illuminate/Routing/Router->dispatch(Object(Illuminate/Http/Request))
#58 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(130): Illuminate/Foundation/Http/Kernel->Illuminate/Foundation/Http/{closure}(Object(Illuminate/Http/Request))
#59 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#60 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Foundation/Http/Middleware/TransformsRequest->handle(Object(Illuminate/Http/Request), Object(Closure))
#61 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#62 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Foundation/Http/Middleware/ValidatePostSize->handle(Object(Illuminate/Http/Request), Object(Closure))
#63 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(63): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#64 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode->handle(Object(Illuminate/Http/Request), Object(Closure))
#65 vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#66 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(171): Fideloper/Proxy/TrustProxies->handle(Object(Illuminate/Http/Request), Object(Closure))
#67 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(105): Illuminate/Pipeline/Pipeline->Illuminate/Pipeline/{closure}(Object(Illuminate/Http/Request))
#68 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(145): Illuminate/Pipeline/Pipeline->then(Object(Closure))
#69 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(110): Illuminate/Foundation/Http/Kernel->sendRequestThroughRouter(Object(Illuminate/Http/Request))
#70 public/index.php(55): Illuminate/Foundation/Http/Kernel->handle(Object(Illuminate/Http/Request))
#71 {main}

**Comment by jqhph** [comment]
已修复，感谢反馈

**Comment by jqhph** [comment]
可以先更新master分支代码

**Comment by amtbnagios** [comment]
感恩，好快的速度！
我看了一下1.6.0操作日誌的代碼，應該是輸入的參數長度過長，導致admin_operation_log的input欄位存不下那麼長的json數據(尾部被戒掉了），然後json_decode就失敗了，已經把input從text類型修改為longtext了，再觀察觀察！
$input = json_decode($input, true);
$input = Arr::except($input, ['_pjax', '_token', '_method', '_previous_']);
