### ISSUE TITLE
表单 dateRange 字段设为 disable 时，提交时报错

### ISSUE THREAD

**Issue by shirosama** [jqhph/dcat-admin#405]
- Laravel Version: 7.0
- PHP Version: 7.4
- Dcat Admin Version: 1.6.5

### Description:

表单 dateRange 字段设为 disable 时，提交时报错

![批注 2020-08-07 164551](https://user-images.githubusercontent.com/12275809/89627456-820ce580-d8cd-11ea-9e14-62b313906a0a.jpg)

应该是因为 IgnoredFields 取出来变多维数组的原因

![批注 2020-08-07 164434](https://user-images.githubusercontent.com/12275809/89627719-ddd76e80-d8cd-11ea-8098-13657534310c.jpg)

**Comment by jqhph** [comment]
已修复，感谢反馈
