### ISSUE TITLE
请教如何使用阿里的iconfont

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#406]
![image](https://user-images.githubusercontent.com/16422689/89639948-19c7ff00-d8e1-11ea-9c72-295b8ce71882.png)

这样引入后，修改菜单的字体图标icon，没有效果

**Comment by jqhph** [comment]
没用过

**Comment by ygcool** [comment]
已解决。
在bootstrap.php中引入iconfont提供的css、js链接
Admin::css('http://at.alicdn.com/t/xxxx.css');
Admin::js('http://at.alicdn.com/t/xxxx.js');

使用时，需要携带“iconfont ”前缀，例："iconfont icon-users"
