### ISSUE TITLE
关于多应用路由的BIG BUG

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#409]
说明：
多应用路由涉及到auth的。都是叫users.index，不管是哪个应用。

目前只有一个办法，就是路由全部在routes重写，把name覆盖掉。
正常情况下没什么大问题，但是php artisan route:cache 会报错

**Comment by jqhph** [comment]
已修复，感谢反馈

**Comment by neatstudio** [comment]
Unable to prepare route [union/helpers/extensions] for serialization. Another route has already been assigned name [extensions.index].

运行一下：
php artisan roue:cache
还缺 一点点

**Comment by jqhph** [comment]
> Unable to prepare route [union/helpers/extensions] for serialization. Another route has already been assigned name [extensions.index].
> 
> 运行一下：
> php artisan roue:cache
> 还缺 一点点

可以了，重新拉取下代码

**Comment by neatstudio** [comment]
继续。还有BUG。
比如主项目下的resource 是 category，你会生成 category.index.

如果子项目下的resource 也用了category ，你也会生成 category.index ......

**Comment by jqhph** [comment]
这个你可以自己在路由文件中加上别名

**Comment by neatstudio** [comment]
OK。在resource之前的group里加了一个'as'=>'subname.'，解决了，
这时候生成出来的就是“subname.category.index”。类似前缀
