### ISSUE TITLE
grid中的异步模态框中的JS不能执行

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#412]
http://www.dcatadmin.com/docs/master/model-grid-column-display.html
当使用异步功能时。HTML能够正常显示，JS不能执行（PJAX状态下，比如在页面里console.log(123)）
1、如果切换成其他URL，console里显示刚才点击的所有次数的 123
2、刷新当前页，再点击异步，此时只有第一个点击的JS执行了。页面出现123，再点击其他的，JS不执行

JS无论是放在模板里。还是在继承 lazyRenderable的页面里。都一样。
强刷页面就执行一次，PJAX是一次不执行（或者说其实执行了，但效果 未出来，因为切换路由的时候，console里能够全部打印）

**Comment by neatstudio** [comment]
之前应该是正常的。

**Comment by jqhph** [comment]
我有空再看看这个问题

**Comment by jqhph** [comment]
已支持这个功能
