### ISSUE TITLE
刷新按钮导致子表格展开无效

### ISSUE THREAD

**Issue by a245589351** [jqhph/dcat-admin#415]
- Laravel Version: 7
- PHP Version: 7.3.9
- Dcat Admin Version: 1.6.5

### Description:
使用表格展开表格后，在根表格点击刷新按钮，会导致子表格里的展开按钮无效
![bug](https://user-images.githubusercontent.com/17821261/89769848-79681980-db30-11ea-8287-b69141a0da76.gif)

**Comment by jqhph** [comment]
你这个是异步加载？

**Comment by a245589351** [comment]
是异步加载的，子grid继承自LazyRenderable，子grid的展开也是用异步加载的方式，加载孙子级的grid

**Comment by jqhph** [comment]
控制台是否有报错

**Comment by a245589351** [comment]
控制台没有任何报错

**Comment by jqhph** [comment]
Duplicate of #412

**Comment by jqhph** [comment]
已支持这个功能

**Comment by a245589351** [comment]
谢谢，需要使用什么方式可以将改动同步到现有项目中呢？
