### ISSUE TITLE
图片上传保存报object name is empty

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#417]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
图片删除失败，但又无法上传新图片。这个我可以用->disableRemove()和->autoUpload()解决。
图片上传到阿里云oss成功，form表单保存模型数据报“object name is empty”，删除图片也是报“object name is empty”，
![image](https://user-images.githubusercontent.com/24761416/89854603-e1693f00-dbc6-11ea-9a67-326fef065dd2.png)

### Steps To Reproduce:
报错是云上传oss插件报的，请问该怎么解决呢

**Comment by jqhph** [comment]
使用的OSS包有问题，可以试试其他的包，比如 https://learnku.com/articles/42554

**Comment by joey2017** [comment]
> 使用的OSS包有问题，可以试试其他的包，比如 https://learnku.com/articles/42554

好的，经过测试，已经可以，确实是https://github.com/jacobcyl/Aliyun-oss-storage包有问题
