### ISSUE TITLE
行内编辑 + 编辑之后分页跳转问题

### ISSUE THREAD

**Issue by haoqianlei** [jqhph/dcat-admin#418]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Dcat Admin Version: 1.6

### Description:
例如：随便一个列表页编辑第3页，第3行，行内 switch 编辑。将开关打开之后，点击此行编辑操作进入编辑页然后提交，分页自动跳回了第1页，并非第3页。

**Comment by jqhph** [comment]
建议改成弹窗编辑，`$grid->showQuickEditButton();`

**Comment by a1300657068** [comment]
但是只是单单更改一个状态的话，用弹窗编辑是不是有点不友好😂。

**Comment by jqhph** [comment]
那你可以用行内编辑

**Comment by a1300657068** [comment]
其实还是更想使用行内 switch 这个来去编辑这个状态。毕竟这样体验比较好🤦‍♂️
