### ISSUE TITLE
弹窗选择器 新增完成后编辑页面没有默认数据

### ISSUE THREAD

**Issue by 2494911084** [jqhph/dcat-admin#420]
模型关系为多对多，有个中间表。
我在创建完成后，数据库中能够看到数据添加成功，但是编辑时弹窗选择器没有显示默认数据

**Comment by jqhph** [comment]
用法不对，参考文档 [表单关联关系](http://www.dcatadmin.com/docs/master/model-relationship.html)

**Comment by 2494911084** [comment]
> 用法不对，参考文档 [表单关联关系](http://www.dcatadmin.com/docs/master/model-relationship.html)

是多对多不能使用弹窗选择器 还是 多对多可以使用但是是我写错了？

**Comment by jqhph** [comment]
你遇到的应该也是这个问题，下次提问贴上代码

https://learnku.com/laravel/t/48345?#reply155601

**Comment by forwells** [comment]
@jqhph 老哥好, 我遇到的是$form->tags()这个方法的问题
描述:
 article - tags - article_tag中间表
通过`$form->tags('tags')->pluck('name', 'id')->options(Tags::all())` 提交表单后 可以正常通过中间表完成多对多关系的关联保存
但是点击编辑表单时,是不显示已保存的tags值的, 有点麻瓜 想请教一下
贴图:
grid可以正常显示
![image](https://user-images.githubusercontent.com/32950945/162358921-ff788fab-507e-4ff3-b394-166232548913.png)
form则不可以
![image](https://user-images.githubusercontent.com/32950945/162359036-6937a523-6707-442c-a2ec-d5d2825d84e1.png)
form代码段
![image](https://user-images.githubusercontent.com/32950945/162359072-f301cd9d-5d8a-47e5-968e-6bfc76bc041e.png)

然后其实我参考了系统权限(Permission)控制器中HTTP Path的设计 我看那里也没有很特别的设置 但是是正常显示的
