### ISSUE TITLE
编辑页面form表单阻止提交事件

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#421]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
我想在边界页面增加一个弹窗提示，然后确定之后再提交数据，但是目前我绑定的button按钮点击事件无法阻止表单提交，点击提交按钮之后直接保存数据，再弹出提示框，再点弹出框的确认按钮没有发起请求。

$('button.submit').on('click',function(e){
    var form = $(this).parents('form');
    /*form.submit(function(e){
        e.preventDefault();
        alert('it is working!');
        return false;
    })*/
    //e.preventDefault();
    console.log(9999);
    Dcat.confirm('确定要修改信息吗？', '修改地址，营业执照，统一代码，身份证照需要平台重新审核！', function () {
        console.log(8888);
        form.submit();
    });
});

**Comment by jqhph** [comment]
1.6.5版本已经支持弹出确认窗功能
```php
$form->confirm('标题', '内容');
```

**Comment by joey2017** [comment]
> 1.6.5版本已经支持弹出确认窗功能
> 
> ```
> $form->confirm('标题', '内容');
> ```

好的

**Comment by likeke0916** [comment]
如果需要根据表单输入的内容做判断是否弹出确认框应该做？
