### ISSUE TITLE
在filter里,select关联之后,第一个select框选完之后,第二个select框可以默认选空吗?

### ISSUE THREAD

**Issue by jiangyou0998** [jqhph/dcat-admin#422]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.6.5

### Description:
在filter里,select关联之后,第一个select框选完之后,第二个select框可以默认选空吗?

**Comment by jqhph** [comment]
可以多返回一个空的选项

**Comment by jiangyou0998** [comment]
默认为空的问题解决了,但是发现了个新的问题
第二个select框选值之后,点击搜索,刷新出来的页面,第二个select框内容是空的

**Comment by jqhph** [comment]
好的我抽空看看这个问题

**Comment by jqhph** [comment]
已修复，下个版本更新
