### ISSUE TITLE
The image dimensions is invalid. 这个提示为什么改不成中文呢

### ISSUE THREAD

**Issue by Ambition9186** [jqhph/dcat-admin#425]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Dcat Admin Version: 1.6.5

### Description:
上传图片限制最小宽提示时是个英文（The image dimensions is invalid.）  怎么改成中文呢

**Comment by jqhph** [comment]
这个是laravel的字段验证错误信息翻译，你可以使用这个包 https://github.com/overtrue/laravel-lang

**Comment by Ambition9186** [comment]
> 这个是laravel的静态验证错误信息翻译，你可以使用这个包https://github.com/overtrue/laravel-lang

谢谢了  弄好了
