### ISSUE TITLE
数据也多语言话，该如何做才可以？

### ISSUE THREAD

**Issue by ZicLemon** [jqhph/dcat-admin#427]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
可以把翻译数据存数据库，或者存文件

**Comment by ZicLemon** [comment]
> 可以把翻译数据存数据库，或者存文件

比如文章系统，我想做个英文版版的，我之前做到就是新建一张数据表存放英文数据，然后保存的时候分开保存两份数据
但是系统多的时候，就要建立很多表，去不同多系统录入不同多语言版本，我想知道dcat 有没有那种在一个系统里面，然后可以切换语言，输入不同语言多数据，最终达成数据多语言多功能

**Comment by jqhph** [comment]
laravel有这个功能，你可以用`trans`函数，把翻译数据查出来再注入进去就好了

**Comment by ZicLemon** [comment]
> laravel有这个功能，你可以用`trans`函数，把翻译数据查出来再注入进去就好了

自己做还可以，但这功能要做给操作人员，后台自己输入的

**Comment by nianwd** [comment]
@ZicLemon https://github.com/Astrotomic/laravel-translatable  这个可以实现

**Comment by moxuanyuan** [comment]
> @ZicLemon https://github.com/Astrotomic/laravel-translatable 这个可以实现
我也是刚刚研究这个，发现如何整合到dcat，有点难度，主要是编辑form 时，如何更好实现

**Comment by nianwd** [comment]
这个是一对多关联
![image](https://user-images.githubusercontent.com/19748978/90759987-cc518600-e313-11ea-86bb-036821abbdc4.png)
