### ISSUE TITLE
能否支持自定义列展开？

### ISSUE THREAD

**Issue by mmlsx** [jqhph/dcat-admin#429]
能否支持自定义列展开，例如：弹出modal框这这种，和菜单结构一样的，可以多选的那种（像多选盒）

**Comment by jqhph** [comment]
不是有弹窗选择器了吗

**Comment by mmlsx** [comment]
是表格的列字段展示功能能否支持自定义的这种。。。

**Comment by jqhph** [comment]
没明白你的意思

**Comment by zhaoshl** [comment]
> 没明白你的意思

![image](https://user-images.githubusercontent.com/31877333/102036047-d9334180-3dfc-11eb-8b9d-5a460f6f9699.png)
其实提问者的意思就是想在列展开的时候，也能像弹窗选择器那样可以操作，同求！
