### ISSUE TITLE
demo与本地样式

### ISSUE THREAD

**Issue by MrKaGod** [jqhph/dcat-admin#433]
在demo中，“网站设置[异步]”中有个功能，菜单布局sidebar-separate

请问这个东西的布局是在哪里设置的？

**Comment by jqhph** [comment]
这是新版本功能，预计这周内发布，建议watch一下仓库

**Comment by moxuanyuan** [comment]
什么时候发布？

**Comment by jqhph** [comment]
> 什么时候发布？

这次版本更新的内容太多延期了，预计这周三发布
