### ISSUE TITLE
如果实现前台模块？ 

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#436]
我理解laravel admin / dcat-admin 是将前端组件与后台功能抽象成为用后端php代码可定义的组件，
从而简化编写前后端代码的时间。无论是laravel admin 还是 dcat-admin 重点都是放在构建后台系统。
默认开箱已经自带了后台的前端布局，非常适合开发后台系统。但如果一个项目有前后台功能，此时如何用dcat-admin 组件同时开发前后台？我想到的是使用 `Content::full` 这个方法实现前台页面。但是非常笨拙。

我认为dcat-admin可以往通用系统开发方向发展，把当前后台的功能分离成为插件，实现布局、组件、功能分开。

**Comment by jqhph** [comment]
dcat-admin的所有功能都是基于后台页面功能进行设计的，并不适合直接用来构建前台，正如你所说，会显得比较“笨拙”。

前台更适合基于dcat-admin开发后台，然后在此基础上开发适合前台功能的功能组件，也可以做成dcat-admin的插件。
