### ISSUE TITLE
规格选择器重新选择规格后页码依旧保持之前的页码

### ISSUE THREAD

**Issue by LuMitchell** [jqhph/dcat-admin#437]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 1.6.5

### Description:
![image](https://user-images.githubusercontent.com/29627681/90206356-07d0e980-de16-11ea-9940-f3cce96851aa.png)
这个规格选择器重新选择了不会跳到第一页，我翻页之后（比如到第五页）再选择数据就没了（其实还有数据只不过是没那么多页我依旧在第五页）。这样不注意的话会造成很大的误解。
最好重新选择的时候会自动跳到第一页。

### Steps To Reproduce:

跳到末页，再重新选择规格选择器的选项。

**Comment by jqhph** [comment]
已优化这个功能
