### ISSUE TITLE
文档问题：php artisan admin::ide-helper

### ISSUE THREAD

**Issue by smartymoon** [jqhph/dcat-admin#44]
相关页面： http://www.dcatadmin.com/docs/master/model-grid.html
多了一个冒号

`php artisan admin::ide-helper`
`php artisan admin:ide-helper`

**Comment by jqhph** [comment]
好的感谢反馈，我会调整这个错误

**Comment by smartymoon** [comment]
这两天在通读你的文档，发现了一些问题。想试着用文档中的 gitalk 进行反馈，似乎有些使用问题。
如果能调整好的化，读者反馈起来会更方便一些

**Comment by jqhph** [comment]
gittalk应该是可以用的，如果不行的话现在文档在learnku社区也有一份https://learnku.com/docs/dcat-admin/1.x，可以在learnku社区反馈
