### ISSUE TITLE
弹窗选择器 (selectResource)显示已选中的数据失敗

### ISSUE THREAD

**Issue by jiangyou0998** [jqhph/dcat-admin#444]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.6.5

### Description:
![未命名](https://user-images.githubusercontent.com/62862010/90357197-b24e4400-e084-11ea-83e7-29b41b0d4623.png)
#### options返回数据如图,试过直接return '1,2,3'; 依旧没有显示,请问是哪里出问题了?
不用toArray()也试过了.

另外选择用户后提交,数据也成功写到数据库了,只是刚进页面并没有显示已选中数据.

两个表是多对多关系,中间表除了关联的id外,还有别的字段

### Steps To Reproduce:

代码:
```php
      $form->selectResource('users')
                ->path('pages/front_users') // 设置表格页面链接
                ->multiple() // 设置为多选
                ->options(function ($v) { // 显示已选中的数据
                    if (!$v) return $v;

                    $options = collect($v)->pluck('name', 'id')->toArray();
//                    dump($options);

                    return $options;
                });
```

**Comment by jqhph** [comment]
Duplicate of #420
