### ISSUE TITLE
widget table或者其它的组件如何修改td的内容或者样式输出到页面

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#447]
- Laravel Version: 5.8
- PHP Version:7.4
- Dcat Admin Version: 1.6.5

### Description:
我在grid中使用modal table组件的时候，我想修改table下面的td里面的内容输出，目前只看到可以设置table的样式，属性和添加行，没有找到td的修改渲染输出方法，请问该如何操作呢
![image](https://user-images.githubusercontent.com/24761416/90466040-526aa280-e143-11ea-9be2-717080c69dac.png)
我希望这个modal里面显示图片出来

**Comment by jqhph** [comment]
放进table之前的数据先处理好，或者自己写view

**Comment by joey2017** [comment]
> 放进table之前的数据先处理好，或者自己写view

好的，
