### ISSUE TITLE
Easy Excel可以导出数字吗

### ISSUE THREAD

**Issue by jiangyou0998** [jqhph/dcat-admin#448]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.6.5

### Description:
![image](https://user-images.githubusercontent.com/62862010/90496261-2fa6b100-e178-11ea-9bde-1d38e99f843b.png)
导出的excel文件,数字部分的单元格并不是数字,不能直接用于统计,请问有没有办法可以直接导出数字?

**Comment by jqhph** [comment]
用`rows`方法把字段值类型转换一下试试

**Comment by jiangyou0998** [comment]
```php
$grid->export()->xlsx()->filename($filename)->rows(function (array $rows) {
                foreach ($rows as $index => &$row) {
                    foreach ($row as $k => $v){
                        if(is_numeric($v)){
                            $row[$k] = (int)111;
                        }
                    }
                }

                return $rows;
            });
```
## 试了一下,结果还是不行
![未命名](https://user-images.githubusercontent.com/62862010/90605587-29284000-e231-11ea-9357-319f871cdd3f.png)

**Comment by jqhph** [comment]
`easyexcel`底层用的是[box/spout](https://github.com/box/spout)实现的导入导出功能，我在官方文档也没看到有相关类型转换的功能接口，如果不行的话只能换成`laravel excel`了

**Comment by jiangyou0998** [comment]
试了一下,转成csv就没有这个问题了.

**Comment by jqhph** [comment]
我找到这个问题了，easy-excel导出时的类型转换有点问题

**Comment by jqhph** [comment]
升级easyexcel到1.0.3版本就行了

**Comment by jiangyou0998** [comment]
谢谢,我试试
