### ISSUE TITLE
$grid / $form可以增加方法获取原生Eloquent 模型吗？

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#449]
$form->model() 只能是获取数据，有时候有些逻辑还是必须要原生Eloquent 模型处理，例如我用了laravel-translatable https://github.com/Astrotomic/laravel-translatable 实现数据库的多语言，但因为dcat 会将原生Eloquent 模型转换成Repository，从而失去了对laravel-translatable的支持。

**Comment by jqhph** [comment]
可以

```php
$model = $form->repository()->eloquent();
```

**Comment by moxuanyuan** [comment]
> ```
> $form->repository()->eloquent()
> ```

原来如此，谢谢，这些不看代码真的不知的方法

**Comment by moxuanyuan** [comment]
> 可以
> 
> ```
> $model = $form->repository()->eloquent();
> ```

$form->repository()->eloquent()
$grid->model()->repository()->eloquent()

如果两个统一一下就好了
