### ISSUE TITLE
Widget not generate https url

### ISSUE THREAD

**Issue by folkevil** [jqhph/dcat-admin#450]
- Laravel Version: 7.2.x
- PHP Version: 7.4
- Dcat Admin Version: 1.6

### Description:
My project running with https protocol, but some component of DCat not generate/use https, it only uses HTTP method, and cannot load ajax content. For example Example Metrics Widgets using url:

http://domain.com/admin/dcat-api/value

I tried to add force using https to AppServiceProvider but it didn't work.

**Comment by jqhph** [comment]
Add this to your `.env` file
```env
ADMIN_HTTPS=true
```

**Comment by folkevil** [comment]
Thanks, it works
