### ISSUE TITLE
json数据类型，使用list方式展示表单，在关联表时js失效

### ISSUE THREAD

**Issue by ttlmm** [jqhph/dcat-admin#452]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
两张表marketing和marketing_vote(该表中有form字段，类型为json)，
表单中$form->list('marketing_vote.form'); 这样时该组件js失效，无法添加行、删除行。

**Comment by ttlmm** [comment]
![image](https://user-images.githubusercontent.com/2785095/90638610-22fd8800-e260-11ea-9df3-3e1fcb61f586.png)
这个地方的筛选用的class类型。与列名中的 . 冲突了

**Comment by jqhph** [comment]
感谢反馈，后续版本中会修复这个问题

**Comment by jqhph** [comment]
已修复
