### ISSUE TITLE
MAP组件，能否通过其他字段的值获取经纬度？

### ISSUE THREAD

**Issue by neatstudio** [jqhph/dcat-admin#453]
需求：
1、新增的时候，是否可以通过判断指定输入框来获取经纬度？比如Address，当这个值变动的时候，lat/lng能够自动获取经纬度？
2、是否支持输入文字来获取经纬度？或者初始化城市？
      比如，我在上海，如果要录入一个广东的数据，没有初始化，或者不能基于某个字段获取经纬度的话，确实有点麻烦
3、是否可以设定初始化地图的精度？

**Comment by jqhph** [comment]
这个功能需要自己扩展，dcat-admin支持扩展表单字段功能，具体使用可以参考文档表单字段管理
