### ISSUE TITLE
行内编辑 是否可以做到不用点击保存 而是鼠标离开就保存数据呢

### ISSUE THREAD

**Issue by michelleyaoyao** [jqhph/dcat-admin#455]
- Laravel Version: 7.0
- PHP Version:7.3
- Dcat Admin Version:1.6

### Description:

行内编辑  保存按钮太小 。 是否可以做到不用点击保存 而是鼠标离开就保存数据呢

**Comment by jqhph** [comment]
可以基于现有的自己扩展

**Comment by michelleyaoyao** [comment]
能否稍微给个提示呢。 不知道怎么修改呢？非常感谢您

**Comment by jqhph** [comment]
参考文档列的显示和扩展
