### ISSUE TITLE
异步加载数据 首次打开路由时没有去获取数据 刷新一次网页后才显示

### ISSUE THREAD

**Issue by nianwd** [jqhph/dcat-admin#456]
- Laravel Version: 6.18
- PHP Version: 7.3
- Dcat Admin Version: 1.6.5

### Description:
![image](https://user-images.githubusercontent.com/19748978/90750793-e5ecd080-e307-11ea-9b03-08b8e970ad52.png)

第一次打开路由时
![image](https://user-images.githubusercontent.com/19748978/90750618-a6be7f80-e307-11ea-9a19-af1126e0b765.png)

刷新页面后
![image](https://user-images.githubusercontent.com/19748978/90750748-d4a3c400-e307-11ea-91b0-d781cb346c5f.png)

**Comment by jqhph** [comment]
165不支持这种用法，拉取master分支代码或者等新版本发布

**Comment by nianwd** [comment]
是直接覆盖composer包吗
显示这个
![image](https://user-images.githubusercontent.com/19748978/90753157-d327cb00-e30a-11ea-8836-0ebed45be56d.png)

**Comment by nianwd** [comment]
可以了，thanks
