### ISSUE TITLE
多grid  表格导出总是,导出第一个 表格,  设置了setname 也无效

### ISSUE THREAD

**Issue by linechengchen** [jqhph/dcat-admin#465]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by linechengchen** [comment]
Laravel Version: 7
PHP Version: 7.4
Dcat Admin Version:1.6.0

**Comment by jqhph** [comment]
已修复，更新master分支代码即可
