### ISSUE TITLE
图片上传后图片地址为空

### ISSUE THREAD

**Issue by WangQuanTang** [jqhph/dcat-admin#468]
- Laravel Version: 7.2.4
- PHP Version: 7.2.5
- Dcat Admin Version: 1.6

### Description:
图片上传后图片地址为空

### Steps To Reproduce:
```php
$form->image('thumb','项目主图')->uniqueName();
```
提示：需要安装intervention/image来使用image，安装：
`composer require intervention/image`
问题解决，不报错了，但是上传图片后，该字段为空，在浏览器调试和保存回调，这个值均为空，无法获取图片地址。
也配置了本地上传的路径！

**Comment by jqhph** [comment]
图片上传`uniqueName`不需要安装`intervention/image`，并且你这个代码也不可能导致无法保存字段值，检查下是否有其他特殊代码
