### ISSUE TITLE
2.0插件市场很期待，不知道什么时候发布？

### ISSUE THREAD

**Issue by maliang** [jqhph/dcat-admin#476]
想知道大概什么时间会发布，对目前扩展形式兼容么，不兼容的话迁移复杂不复杂

**Comment by jqhph** [comment]
大概是9-10月份会有beta版本出来，对目前扩展方式不兼容，移植不复杂。因为扩展的核心逻辑是不变的，只是安装加载方式变了而已。

**Comment by fpy5627** [comment]
弱弱的问一句，啥时候能发布呢。。
