### ISSUE TITLE
在Action的handle方法中用$.post跳转界面后，浏览器窗口的没有显示跳转后的界面，但是network 的preview里显示跳转后的界面，怎么让浏览器的窗口能显示跳转后的界面？

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#478]

**Comment by jqhph** [comment]
没明白，贴上代码

**Comment by xxkrcn** [comment]
public function handle(Request $request)
    {
        return $this->response()->script(
            <<<JS
                let data = {};
                data['id']    = 1;
                data['name']  = 'zhangsan';
                data['age']   = 20;
                data['grade'] = 80;

                setTimeout(function () {
                    $.post('/admin/student/detail', {'data': data}, function () {
                        
                    });
                }, 300);
JS
        );
    }

**Comment by jqhph** [comment]
谁跟你说$.post是跳转...百度一下吧同学
