### ISSUE TITLE
表单关联关系是否支持morphToMany

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#479]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6.5

### Description:
表单关联关系是否支持morphToMany？我希望在管理后台中使用
$form->multipleSelect('Roles', trans('admin.roles'))
                    ->options(function () {
                        return Role::where('enterprise_id', $this->getAuthUserEnterpriseId())->pluck('name', 'id');
                    })
                    ->customFormat(function ($v) {
                        if (!$v) return [];
                        return array_column($v, 'id');
                    });
我使用的是laravel-permission包，报错信息

![image](https://user-images.githubusercontent.com/24761416/91309852-b34d4700-e7e3-11ea-8657-3b4df7942a94.png)

**Comment by jqhph** [comment]
支持`morphToMany`，跟`belongsToMany`用法一致，另外关联模型在表单中需要换成小写`$form->multipleSelect('roles',)`，具体原因请查看文档；而且options闭包中不允许调用模型方法

**Comment by joey2017** [comment]
好的，在您的提醒帮助下已经实现功能。
