### ISSUE TITLE
table 组件下 select 和json联动问题 

### ISSUE THREAD

**Issue by CherishNA** [jqhph/dcat-admin#48]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
在编辑模式下  table 组件下 select下拉框 数据来源为json格式  但是 select不能联动成功 只能联动json下第一个元素的选项：
对应json：
[{"sort": "10", "classify_id": "28"}, {"sort": "11", "classify_id": "27"}]
classify_id:28关联实体类name为：卖货宣传
classify_id:27关联实体类name为：引流专用

对应展示效果：
![image](https://user-images.githubusercontent.com/23067312/80329777-ed2e3100-8875-11ea-9d50-6de0b1e91c8f.png)

**Comment by CherishNA** [comment]
实体类关键代码：
` protected $casts = [
        'classify' => 'json',
        'home_classify' => 'json',
    ];
  public function getClassifyAttribute($classify)
    {
        return array_values(json_decode($classify, true) ?: []);
    }

    public function setClassifyAttribute($classify)
    {
        $this->attributes['classify'] = json_encode(array_values($classify));
    }


`

**Comment by jqhph** [comment]
没看明白，贴上表单的代码

**Comment by CherishNA** [comment]
`  $form->table('classify', function (Form\NestedForm $table) {
                $table->select('classify_id', '所属分类')->options('/api/placard_classify')->required();
                $table->text('sort', '排序')->rules('required');
            });`

**Comment by jqhph** [comment]
感谢反馈，确实有这个问题，[已修复](https://github.com/jqhph/dcat-admin/commit/c47afd7d7012d449fbfa1d381fc7affc38cc75ec)，请等新版本更新。

**Comment by jqhph** [comment]
新版本v1.2.5已发布，更新升级即可。
