### ISSUE TITLE
在快捷编辑弹窗中使用表单布局采用分栏时，提交会报 CSRF token mismatch. 错误

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#482]
- Laravel Version: 7.24
- PHP Version: 7.2.5
- Dcat Admin Version: 1.7.0

### Description:
表单布局采用分栏时，提交会报 CSRF token mismatch. 错误

### Steps To Reproduce:
如果在数据表单中分栏，如这样，就会复现，取消这个分栏就没问题。很奇怪。

`
$form->column(6, function (Form $form) {
}
`

**Comment by jqhph** [comment]
这个功能我一直在正常使用，贴一下完整的代码看看

**Comment by patrick-zhao-51** [comment]
`/**
     * 创建或编辑表单
     * @return Form
     */
    protected function form()
    {
        return Form::make((new Client())->with(['tagged']), function (Form $form) {

            // 调整所有表单的宽度
            $form->width(9, 3);

            // 如果这样分栏，会报错
            $form->column(6, function (Form $form) {
                $form->text('company_name')
                    ->placeholder('公司名称，如有请填写');
                    ->required();

                $form->text('contact_name')
                    ->placeholder('联系人，如有请填写');

                $form->tel('contact_phone')
                    ->placeholder('主联系电话，将使用在账单编号上，必填项')
                    ->required();

                $form->text('contact_other_phones')
                    ->placeholder('其他联系电话，多个逗号分隔');

                $form->email('contact_email')
                    ->placeholder('电子邮件，多个逗号分隔，必填项')
                    ->required();

                $form->text('contact_full_address')
                    ->placeholder('格式：{街道地址}, {城市}, {省份} {邮编}');
            });

            $form->column(6, function (Form $form) {
                $form->select('user_id')
                    ->options(User::class, 'uid', 'nickname')
                    ->placeholder('可输入关键词查询网站用户，并选择')
                    ->ajax('/api/ajax/remote/user/search');

                $form->select('agency_id')
                    ->options(Agency::class, 'id', 'company_name')
                    ->placeholder('可输入关键词查询广告代理，并选择');

                $form->text('case_no')
                    ->placeholder('相关专案号，填写格式：P.O xxxx 或 Case No xxxxx');

                $form->select('sales_id')
                    ->options(Sales::class, 'id', 'name')
                    ->placeholder('可输入关键词查询业务员，并选择');

                $form->tags('tagged', admin_trans_field('tags'))
                    ->placeholder('请查询并关联客户相关标签，最多五个')
                    ->pluck('tag_name', 'tag_name')
                    ->ajax('/api/ajax/tags/search', 'text');

                $form->textarea('note')->rows(1);

            });

        });
    }`

**Comment by patrick-zhao-51** [comment]
对了，我是在快捷编辑的弹窗中调用这个表单的，不知道和这个有关系吗？

**Comment by jqhph** [comment]
在快捷编辑弹窗中确实有这个问题，感谢反馈

**Comment by jqhph** [comment]
已修复，可以先更新master分支代码

**Comment by patrick-zhao-51** [comment]
谢谢

Jiang Qinghua <notifications@github.com> 于 2020年8月28日周五 03:42写道：
