### ISSUE TITLE
自定义行操作里面可以实现下载文件吗？

### ISSUE THREAD

**Issue by michelleyaoyao** [jqhph/dcat-admin#485]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

        $grid->actions(new PicDownloadAction());

然后 action里面
        return response()->download($zip_file);

返回了一堆字符 。 请问这种需求 怎么做比较好呢？

谢谢您！！

**Comment by jqhph** [comment]
action本身就支持下载文件的操作，具体看文档
