### ISSUE TITLE
请教一个问题，有无可能实现比较复杂的表单形式

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#490]
- Laravel Version: 7.22.4
- PHP Version: 7.2.5
- Dcat Admin Version: 1.7.0

### Description:

请教老大一个问题，有无可能实现一些比较复杂的表单组合形式，因为帐单系统可能需要用到，比如下图这样：

![image](https://user-images.githubusercontent.com/37001660/91612560-aba8b200-e94b-11ea-975b-abcdad695684.png)
![image](https://user-images.githubusercontent.com/37001660/91612581-b105fc80-e94b-11ea-8df6-7760bb5cb71c.png)

是否用 html field 来实现呢，还是用其他的方法，或者可以扩展表单的 field，但目前我还没有找到。

谢谢先。

**Comment by jqhph** [comment]
表单字段扩展，基本什么样的表单都能实现

**Comment by patrick-zhao-51** [comment]
知道了，已经实现，功能确实很强大，谢谢

**Comment by patrick-zhao-51** [comment]
说一下我的做法：扩展了 Form 类，参照 fieldset 的方法添加了一个自己的方法，让几个field 在一行显示，不知道这样是否是好方法。

直接使用 Field 的 extend 好像不能同时处理几个字段，开始想把字段render到HTML字段中，这样倒是可以解析出，但不能获取和传递值，也许使用隐含字段在提交时处理，但那样感觉不是很好，所以采用扩展 Form 的方法实现。

**Comment by jqhph** [comment]
现在还不支持，2.0会上线类似Content的表单布局功能

**Comment by xyxu** [comment]
@patrick-zhao-51 Field 扩展可以实现自动获取和传递值，不过要用到魔术方法。
