### ISSUE TITLE
模态窗 (Modal) Dcat.helpers.asyncRender is not a function

### ISSUE THREAD

**Issue by lizhi9527** [jqhph/dcat-admin#494]
- Laravel Version: 6.18.37
- PHP Version: 7.2.18
- Dcat Admin Version: 1.7.0

### Description:
点击弹窗后一直加载 JS报错
Dcat.helpers.asyncRender is not a function
怀疑是新版本问题  同环境1.6.5 都是正常
大佬给看看

**Comment by jqhph** [comment]
参考文档版本升级须知
