### ISSUE TITLE
再次请教，弹出快速编辑能否设定蒙层

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#495]
- Laravel Version: 7.24
- PHP Version: 7.2.5
- Dcat Admin Version: 1.7.0

### Description:

现在使用快速编辑弹窗，底部没有使用蒙层，页面滚动条可以触发，下面的页面有时候会滚动，并且可以点击下面页面的链接，感觉不是很好，并且弹层和下面页面颜色一样，不是很清晰。

有无可能使用layui的shade？并开启点击蒙层关闭弹窗呢？

或者也可以自己扩展？没看到这方面的文档案。

谢谢先。

**Comment by jqhph** [comment]
参考layer弹出层文档的初始化功能，可以在在bootstrap.php中初始化开启遮罩层试试

**Comment by patrick-zhao-51** [comment]
非常感谢，已经可以启用。

在 bootstrap.php 加载自定义的 js，其中配置 layer 的初始化选项：

`
Dcat.ready(function () {
    layer.config({
        maxmin: true,
        moveOut: true,
        shade: 0.5
    });
});
`

但还有一个问题：点击快速创建按钮时，如果关闭，蒙层不会消失，但点击快速编辑按钮，则没有问题，看了一下源码，区别差了一个：forceRefresh (见下面的代码)，在快速创建中加上这个，问题也解决了。

还有一个问题，如果加上 shadeClose: true，在快速编辑中也没有问题，但快速创建加了 forceRefresh() 好像也还是有问题，点击关闭弹窗，蒙层不会自动消失，再点一下才消失，这还不算严重，严重的是：再点击新建按钮没反应了。不知为何。


laravel/vendor/dcat/laravel-admin/src/Grid/Tools/CreateButton.php
`
        Form::dialog($new)
            ->click(".{$class}")
            ->success('Dcat.reload()')
            ->dimensions($width, $height);
`


laravel/vendor/dcat/laravel-admin/src/Grid/Actions/QuickEdit.php
`
            Form::dialog($title)
                ->click(".{$this->getElementClass()}")
                ->dimensions($width, $height)
                ->forceRefresh()
                ->success('Dcat.reload()');`

**Comment by cokeyang** [comment]
> 非常感谢，已经可以启用。
> 
> 在 bootstrap.php 加载自定义的 js，其中配置 layer 的初始化选项：
> 
> `Dcat.ready(function () { layer.config({ maxmin: true, moveOut: true, shade: 0.5 }); });`
> 
> 但还有一个问题：点击快速创建按钮时，如果关闭，蒙层不会消失，但点击快速编辑按钮，则没有问题，看了一下源码，区别差了一个：forceRefresh (见下面的代码)，在快速创建中加上这个，问题也解决了。
> 
> 另一个问题，如果加上 shadeClose: true，在快速编辑中也没有问题，但快速创建加了 forceRefresh() 好像也还是有问题，点击关闭弹窗，蒙层不会自动消失，再点一下才消失，这还不算严重，严重的是：再点击新建按钮没反应了。不知为何。
> 
> laravel/vendor/dcat/laravel-admin/src/Grid/Tools/CreateButton.php `Form::dialog($new) ->click(".{$class}") ->success('Dcat.reload()') ->dimensions($width, $height);`
> 
> laravel/vendor/dcat/laravel-admin/src/Grid/Actions/QuickEdit.php ` Form::dialog($title) ->click(".{$this->getElementClass()}") ->dimensions($width, $height) ->forceRefresh() ->success('Dcat.reload()');`

 你可以看看dcat-app.js 里面有压缩的 DialogForm.js的代码，搜索forceRefresh，你可以看到有强刷和没有强刷的区别，强刷是销毁layer，非强刷是隐藏layer，在隐藏的时候，忘记了把蒙版层隐藏！改一下即可。
