### ISSUE TITLE
好像 form 的 error 模板有个小 BUG

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#497]
- Laravel Version: 7.24.0
- PHP Version: 7.2.5
- Dcat Admin Version: 1.7.0

### Description:

文件路径：
laravel/vendor/dcat/laravel-admin/resources/views/form/error.blade.php

`
// 原来是这样的，是否没有吧 error 包到 div 中
< div class="help-block with-errors" >< /div >

是否应该这样
< div class="help-block with-errors" >

@if(is_array($errorKey))
    @foreach($errorKey as $key => $col)
        @if($errors->has($col.$key))
            @foreach($errors->get($col.$key) as $message)
                <label class="control-label" for="inputError"><i class="feather icon-x-circle"></i> {{$message}}</label><br/>
            @endforeach
        @endif
    @endforeach
@else
    @if($errors->has($errorKey))
        @foreach($errors->get($errorKey) as $message)
            <label class="control-label" for="inputError"><i class="feather icon-x-circle"></i> {{$message}}</label><br/>
        @endforeach
    @endif
@endif

< /div >
`

**Comment by jqhph** [comment]
不需要包，而且这个现在基本已经用不到了

**Comment by patrick-zhao-51** [comment]
哦，那现在的错误提示是怎么放进去的？

**Comment by patrick-zhao-51** [comment]
@include('admin::form.error')
我看在 field 的模板中都有这个

**Comment by patrick-zhao-51** [comment]
搞明白了，是前端通过JS写到 .with-errors div 的，谢谢
