### ISSUE TITLE
页面js的问题

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#498]
我在A页面中有一个js监听事件，B页面也有触发这个监听的条件，但是并没有这部分代码，但是当我从A页面点击菜单进入B页面的时候，却可以触发A页面的js监听，不知道这个是怎么回事，不知道我说清楚了吗

**Comment by jqhph** [comment]
贴上完整代码

**Comment by Warrens-yg** [comment]
A页面
```
<script>
Dcat.ready(function() {
    $(document).on('click', '.jstree-anchor', function () {
        console.log(123);
        // 假如A页面有这个监听事件
    })
})
</script>
```

B页面
```
// 假如B页面有这个类的标签，在B页面点击的时候也会执行上的监听
<button id="jstree-anchor">按钮</button>
```

**Comment by jqhph** [comment]
正常是不会出现这种情况的，就看你的代码是在哪里加的

**Comment by Warrens-yg** [comment]
是在各自的视图里面

**Comment by Warrens-yg** [comment]
A页面是这样
@extends('include.container-reset', ['expand' => true])
@section('after-scripts')
<script>
    Dcat.ready(function(){
        $(document).on('click', '.jstree', function () {
            console.log(123).
         });
     })
</script>
@endsection

B页面是这样
@extends('include.container-reset', ['expand' => true])
@section('body')
<button class="jstree"></button>
@endsection
@section('after-scripts')
<script>
    Dcat.ready(function(){

     })
</script>
@endsection
我先从菜单进入A页面，然后再进入B页面点击按钮就会触发A页面的监听，但是我如果直接进入B页面点击按钮是不会触发的

**Comment by jqhph** [comment]
$(document).on('click', '.jstree', function () {
            console.log(123).
         });

改成

$('.jstree').on('click', function () {
            console.log(123).
         });

**Comment by Warrens-yg** [comment]
这个是jstree生成的class，第二种方法监听不到

**Comment by jqhph** [comment]
用 setTimeout 不就能监听到了

**Comment by Warrens-yg** [comment]
这招是不是不太好啊，没有其他办法了吗，你刚说正常情况不会这样，我这个是有什么特殊情况导致的吗

**Comment by jqhph** [comment]
dcat admin是单页应用，正常情况不会使用 $(document).on('click', 'xxx', function () {});

**Comment by Warrens-yg** [comment]
那对于我这种需要监听js生成的class的情况只能用settimeout了吗

**Comment by jqhph** [comment]
方法很多，你需要自己发散思维，比如你可以监听tree的上一层div

**Comment by Warrens-yg** [comment]
多谢，我想我可以给每个页面定义一个唯一的父元素
