### ISSUE TITLE
dateRange表单验证问题

### ISSUE THREAD

**Issue by cjango** [jqhph/dcat-admin#499]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
$form->datetimeRange('start_at', 'end_at', '起始时间')
到验证规则的时候迷糊了，这个rules应该怎样写，才能确切的验证 start_at 必须在 end_at 之前， start_at 的一些其他规则

**Comment by jqhph** [comment]
你可以用`responseValidationMessages`，也可以写闭包验证
rules([function ($attribute, $value, $fail) {}])
