### ISSUE TITLE
表单hasMany 上传问题

### ISSUE THREAD

**Issue by Jdonggit** [jqhph/dcat-admin#50]
看文件似乎hasMany暂不支持图片和文件上传表单
目前有需求是否有其他方法可以做到一对多可以上传?

**Comment by jqhph** [comment]
后面会支持的，暂时没有其他方案，你可以自己尝试集成`laravel-admin`的文件上传表单。

**Comment by jqhph** [comment]
hasMany已支持图片和文件上传表单，升级最新版本即可。
