### ISSUE TITLE
form表单 字段的默认值能否根据某个select出来的改变 修改对应的值（从数据库取出来的）

### ISSUE THREAD

**Issue by michelleyaoyao** [jqhph/dcat-admin#501]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

![image](https://user-images.githubusercontent.com/12317120/91736806-d495a500-ebe0-11ea-8a89-a5046ce1eef6.png)

比如我想实现类似这种的。 当选择工序之后 去数据库查工序的基本信息 填入下面的字段 作为各个字段的默认值

**Comment by jqhph** [comment]
可以的，需要写js监听表单值变化

**Comment by michelleyaoyao** [comment]
请问下 有相关档吗？ 没有找到。非常非常感谢

**Comment by michelleyaoyao** [comment]
请问一下 有相关文档吗？还是不太清楚怎么做。 直接加载js 写change事件吗？
