### ISSUE TITLE
一个页面显示两个数据表格的问题

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#503]
我在一个界面显示了两个数据表格，表格显示数据都正常，但是因为两个新增按钮（快速编辑按钮）的路由都是一样的，所以弹出的新增界面（快速编辑界面）也是一样的，想问一下有没有方法可以让两个新增按钮（快速编辑按钮）的路由区分开？

**Comment by jqhph** [comment]
当页面有多个表格的时候需要用 `$grid->setName('xx');` 来区分不同表格；

路由前缀设置可以通过 `$grid->resource('auth/users');` 设置

**Comment by zydroot** [comment]
> 我在一个界面显示了两个数据表格，表格显示数据都正常，但是因为两个新增按钮（快速编辑按钮）的路由都是一样的，所以弹出的新增界面（快速编辑界面）也是一样的，想问一下有没有方法可以让两个新增按钮（快速编辑按钮）的路由区分开？

你好。请问你的问题是怎么解决的。

**Comment by xxkrcn** [comment]
两个数据表格通过$grid->resource('auth/users')方法分别设置两个路由，这样数据增删改的路由就区分开了
