### ISSUE TITLE
规格选择器可以一次清空全部吗?

### ISSUE THREAD

**Issue by jiangyou0998** [jqhph/dcat-admin#507]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.7.0

### Description:
如题,规格选择器选多了之后,有时候不想筛选,只能一个个删除,请问有没有方法可以一次清空全部吗?

**Comment by jqhph** [comment]
鼠标移上去最右边有个垃圾桶图标，点击清除所有

**Comment by jiangyou0998** [comment]
垃圾桶只能清除一个选择器的,如果有多个选择器还是要每一个都按一次垃圾桶

**Comment by jqhph** [comment]
垃圾桶是清除所有的，你是不是有什么地方搞错了

**Comment by jiangyou0998** [comment]
就是有多个选择器,打个比方
一个手机产品
有
品牌
屏幕尺寸
运行内存
分辨率
等等的多个选择器 如果我每个选择器都点了,能一次清空我所有的选择吗?而不是只清空某一行

**Comment by jqhph** [comment]
不支持

**Comment by jiangyou0998** [comment]
谢谢解答
