### ISSUE TITLE
分步表单中add方法必须要连着写

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#509]
multipleSteps、remember、add方法都必须要连着写在一起才行。

如果多个add方法并且代码很多，是很不方便。希望可以改进一下，不用连着写。

**Comment by jqhph** [comment]
你可以不连着写

**Comment by moxuanyuan** [comment]
> 你可以不连着写

把add分开写，会提示` Field type [add] does not exist.`

**Comment by jqhph** [comment]
PHP基础不牢固

```php
$steps = $form->multipleSteps();

$steps->add(...)
```

**Comment by moxuanyuan** [comment]
> PHP基础不牢固
> 
> ```
> $steps = $form->multipleSteps();
> 
> $steps->add(...)
> ```

谢谢，理解了

**Comment by pengwei1986** [comment]
多个数据表可以用这个分布表单吗？怎么操作？
