### ISSUE TITLE
How can I update laravel-admin to dcat-admin?

### ISSUE THREAD

**Issue by fhferreira** [jqhph/dcat-admin#51]
I have an app with laravel-admin https://laravel-admin.org/docs/ can I update to that? 

Congratulations, the app is awesome!

**Comment by jqhph** [comment]
Thanks! Only a few codes need to be changed to migrate laravel-admin application to dcat-admin.

**Comment by fhferreira** [comment]
Oh great. I am using that version "encore/laravel-admin": "v1.7.7" but yours are very interesting and fluid than that with "admin-lte" If you could, create some kind of tutorial to that migration. 

However, thank you for your response.
