### ISSUE TITLE
数据统计卡片如何按照需求传递参数

### ISSUE THREAD

**Issue by 99lucky** [jqhph/dcat-admin#511]
比如，总后台如何查看多个分销商的销售业绩。
我继承了card类，并在初始化函数里加入了参数并传递到了我的类的变量里了，但是在handle函数里却无法读取到这个变量

**Comment by jqhph** [comment]
文档好像有遗漏，我抽空补上

```php
public function handle()
{
      // 接受自定义参数
      $key1 = request('key1');
}

// 传递自定义参数
public function parameters(): array
    {
        return [
            'key1' => '值'
        ];
    }
````

**Comment by 99lucky** [comment]
非常感谢，已经成功解决了

**Comment by lishuai199502** [comment]
请问大佬是怎么解决的，我搞不定了
![image](https://user-images.githubusercontent.com/23136422/123073962-7c6ab080-d449-11eb-8587-b20b67f5c7fe.png)
我这样传不进去
