### ISSUE TITLE
grid 里面的modal 使用的不够灵活，我自己做了一点优化

### ISSUE THREAD

**Issue by privarepan** [jqhph/dcat-admin#512]
- Laravel Version: 7.2.*
- PHP Version: 7.2.*
- Dcat Admin Version: 1.7.0

### Description:
grid 里面的modal 不能设置大小我这里做了一点改良，可以不影响正常使用

### Steps To Reproduce:
vim src\Grid\Displayers\Modal.php
`<?php

namespace Dcat\Admin\Grid\Displayers;

use Dcat\Admin\Contracts\LazyRenderable;
use Dcat\Admin\Grid;
use Dcat\Admin\Grid\Column;
use Dcat\Admin\Support\Helper;
use Dcat\Admin\Widgets\Modal as WidgetModal;

class Modal extends AbstractDisplayer
{
    protected $title;
    protected $modal;
    protected $default_size = 'lg';
    protected $default_delay = 300;

    public function __construct($value, Grid $grid, Column $column, $row)
    {
        parent::__construct($value, $grid, $column, $row);
        $this->modal = WidgetModal::make()->size($this->default_size)->delay($this->default_delay);
    }

    public function title(string $title)
    {
        $this->title = $title;
    }

    protected function setUpLazyRenderable(LazyRenderable $renderable)
    {
        return clone $renderable->payload(['key' => $this->getKey()]);
    }

    public function display($callback = null)
    {
        $title = $this->value ?: $this->trans('title');
        if (func_num_args() == 2) {
            [$title, $callback] = func_get_args();
        }

        $html = $this->value;

        if ($callback instanceof \Closure) {
            $callback = $callback->call($this->row, $this);

            if (! $callback instanceof LazyRenderable) {
                $html = Helper::render($callback);

                $callback = null;
            }
        }

        if ($callback && is_string($callback) && is_subclass_of($callback, LazyRenderable::class)) {
            $html = $this->setUpLazyRenderable($callback::make());
        } elseif ($callback && $callback instanceof LazyRenderable) {
            $html = $this->setUpLazyRenderable($callback);
        }

        $title = $this->title ?: $title;
        return $this->modal
            ->title($title)
            ->body($html)
            ->button($this->renderButton());
    }

    protected function renderButton()
    {
        return "<a href=\"javascript:void(0)\"><i class=\"fa fa-clone\"></i>&nbsp;&nbsp;{$this->value}</a>";
    }

    public function modal()
    {
        return $this->modal;
    }

}
`

**Comment by jqhph** [comment]
你可以覆写默认的`modal`功能，在你的`app/bootstrap.php`中加上

```php
Grid\Column::extend('modal', Modal::class);
```

**Comment by privarepan** [comment]
好的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年9月3日(星期四) 下午2:49
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "潘章一"<373500914@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] grid 里面的modal 使用的不够灵活，我自己做了一点优化 (#512)





 
你可以覆写默认的modal功能，在你的app/bootstrap.php中加上
 Grid\Column::extend('modal', Modal::class);
