### ISSUE TITLE
前台应用里使用了Spatie\Pjax\Middleware\FilterIfPjax中间件导致后台返回422状态码

### ISSUE THREAD

**Issue by nookery** [jqhph/dcat-admin#513]
- Laravel Version: 7.25.0
- PHP Version: 7.4.1
- Dcat Admin Version: 1.7.1

### Description:
前台应用里使用了`Spatie\Pjax\Middleware\FilterIfPjax`中间件导致后台返回422状态码

### Steps To Reproduce:
在现有应用的基础上，安装dcat-admin。
现有应用的`app\Http\Kernel`文件中加载了这个中间件：
```
protected $middlewareGroups = [
        'web' => [
            FilterIfPjax::class,
        ],
    ];
```

打开浏览器的调试控制台，发现如下的Pjax请求都返回了 422 Unprocessable Entity：
```
xxx.com/admin/auth/roles?_pjax=%23pjax-container
```

如果注释掉上述的中间件则正常。

**Comment by jqhph** [comment]
建议你在前台路由文件中加上这个中间件，不要附加在`web`中

**Comment by nookery** [comment]
或者为前台单独新建一个中间件组也是可以的，比如：
```
'web-front' => [
    EncryptCookies::class,
    AddQueuedCookiesToResponse::class,
    StartSession::class,
    ShareErrorsFromSession::class,
    VerifyCsrfToken::class,
    SubstituteBindings::class,
    FilterIfPjax::class,
],
```
