### ISSUE TITLE
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by nookery** [jqhph/dcat-admin#514]
- Laravel Version: 7.25.0
- PHP Version: 7.4.1
- Dcat Admin Version: 1.8.4

### Description:
<img width="1631" alt="WX20200903-172255@2x" src="https://user-images.githubusercontent.com/5194193/92097417-a1cef500-ee0a-11ea-885c-2a92c6359feb.png">

随便点击一个pjax链接导致JS报错：Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

这个问题可能很少能遇到，最后发现竟然是 AdGuard 这个软件引起的，整个软件关掉就正常。
AdGuard 这个软件会在页面右下角增加一个小图标。

其他使用pjax的网站没有报这个错误，可能跟 dcat-admin 的pjax初始化方式有关。

### Steps To Reproduce:

电脑中安装 AdGuard 这个软件并保持开启；
打开 dcat-admin 后台，再页面上点击“主页”，或者其他能发起pjax请求的链接。

**Comment by jqhph** [comment]
AdGuard 是啥

**Comment by nookery** [comment]
去广告、保护隐私的一个软件，不是浏览器插件，随系统启动，过滤所有网络请求。
<img width="342" alt="WX20200904-102615@2x" src="https://user-images.githubusercontent.com/5194193/92192724-32ecad00-ee99-11ea-99fc-bb326ef78689.png">

**Comment by jqhph** [comment]
我有空研究下
