### ISSUE TITLE
如果我想在表头filter的位置添加一个小的table能实现得了吗？

### ISSUE THREAD

**Issue by FrankHay0305** [jqhph/dcat-admin#516]
- Laravel Version: 7.0.*
- PHP Version: 7.2.5
- Dcat Admin Version: 1.4.8

###  如果我想在表头filter的位置添加一个小的table能实现得了吗？
![Windows 7 (备份 1)  Running  2020-09-03 22-00-30](https://user-images.githubusercontent.com/40552998/92118478-7f9c9d80-ee31-11ea-837a-986354f71006.png)

**Comment by jqhph** [comment]
参考文档头部和脚部

**Comment by FrankHay0305** [comment]
已解决
