### ISSUE TITLE
Field 的 default 方法是否有个小 BUG

### ISSUE THREAD

**Issue by patrick-zhao-51** [jqhph/dcat-admin#519]
- Laravel Version: 7.24
- PHP Version: 7.2.4
- Dcat Admin Version: 1.7.1

### Description:
如果把 field 的 default 写在最后，如果 default 为空会报错。

比如：

`
                $form->select('client_id')
                    ->default(null)
                    ->required();

`

laravel/vendor/dcat/laravel-admin/src/Form/Field.php 文件中这个方法是

`
    /**
     * Get or set default value for field.
     *
     * @param mixed $default
     * @param bool  $edit
     *
     * @return $this|mixed
     */
    public function default($default = null, bool $edit = false)
    {
        if ($default === null) {
            if (
                $this->form
                && method_exists($this->form, 'isCreating')
                && ! $this->form->isCreating()
                && ! $this->allowDefaultValueInEditPage
            ) {
                // 是否应该返回 $this
                //return;
                return $this;
            }

            if ($this->default instanceof \Closure) {
                $this->default->bindTo($this->data());

                return call_user_func($this->default, $this->form);
            }

            // 是否也是应该返回 $this
            return $this->default;
        }

        $this->default = $default;
        $this->allowDefaultValueInEditPage = $edit;

        return $this;
    }`

不知道是否是这样。

**Comment by jqhph** [comment]
default不能设置为null，否则就是获取
