### ISSUE TITLE
数据表没有使用无限分级设计,可以使用tree组件吗?

### ISSUE THREAD

**Issue by jiangyou0998** [jqhph/dcat-admin#520]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 1.7.0

### Description:
以前设计的数据表没有使用无限分级,而是一个类别对应一个数据库表.
有三个表
表一是产品的生产部门
表二是产品的类型
表三是具体的产品

关系都是一对多,一个部门有可以生产不同类型的产品,一种类型可以有多个产品
请问可不可以通过tree组件一次性选择多个产品?

**Comment by jqhph** [comment]
tree表单是可以的

**Comment by jiangyou0998** [comment]
文档中未搜索到tree表单,请问有例子或者具体使用方法吗?

**Comment by jqhph** [comment]
可以搜到，自己看文档
