### ISSUE TITLE
可以在弹窗中对关联表数据进行增上改查吗？

### ISSUE THREAD

**Issue by zydroot** [jqhph/dcat-admin#521]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
代码如下：
LinkmenuCateController：
`protected function grid()
    {
        return Grid::make(new LinkmenuCate(), function (Grid $grid) {
            $grid->name->setHeaderAttributes(['style' => 'color:#5b69bc']);
            $grid->toolsWithOutline();
            $grid->id->sortable();
            $grid->name->badge('default');
            $grid->status->bool();

            $grid->column('menu_manage', '菜单管理')
                ->display(function(){
                    return Modal::make()
                        ->lg()
                        ->title('菜单管理')
                        ->body(\App\Admin\Render\Linkmenu::make(['id'=>$this->id]))
                        ->button('<button class="btn btn-white "><i class="feather icon-grid"></i> 菜单管理</button>');
                });
                

            $grid->filter(function (Grid\Filter $filter) {
                $filter->like('name');
            });

            $grid->showViewButton();
            $grid->enableDialogCreate();
            $grid->setDialogFormDimensions('50%', '50%');

            $grid->actions(new ShowLinkmenu());
            $grid->showQuickEditButton();
            //$grid->disableActions();
        });
    }`
Admin\Render\Linkmenu:
`class Linkmenu extends LazyRenderable
{

    public function grid(): Grid{

        return Grid::make(new \App\Admin\Repositories\Linkmenu(), function (Grid $grid)  {
            $grid->setName('linkmenu');

            $grid->model()->where('menuid', '=',$this->id);
            $grid->column('id', 'ID')->sortable();
            $grid->column('name');
            $grid->column('alias');

            $grid->enableDialogCreate();
            $grid->showQuickEditButton();
        });
    }
}`
在弹窗中能正常显示Linkmenu的数据，但是编辑，快捷编辑链接都是 admin/dcat-api/render/1/edit ，无法正常操作；文档看了几遍，没有找到办法，求指导

**Comment by jqhph** [comment]
需要改下路由前缀
```php
$grid->resource('路由前缀');
```

**Comment by zydroot** [comment]
> 需要改下路由前缀
> 
> ```
> $grid->resource('路由前缀');
> ```

感谢，可以点击使用了。不过 新增和 快捷编辑的弹窗操作就都失效了 =。=
