### ISSUE TITLE
dcat-admin 对于千万级别数据的优化

### ISSUE THREAD

**Issue by cpken** [jqhph/dcat-admin#522]
- Laravel Version: Laravel Framework 7.16.1
- PHP Version: PHP 7.4.3 
- Dcat Admin Version: v1.5.3

### 问题描述

目前项目数据量变得多了起来，已经超过千万条记录了，在页面加载的过程中，非常的缓慢，基本是 7 秒以上，请问，有优化方式吗？谢谢。

**Comment by jqhph** [comment]
上千万数据没有索引查询是非常慢的，这种要么分表，要么使用索引搜索
