### ISSUE TITLE
表单默认的required验证提示是繁体的，能修改吗，没找到位置

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#523]
![批注 2020-09-05 164402](https://user-images.githubusercontent.com/46614146/92300566-061ebf80-ef97-11ea-8ff0-610572e413f0.png)

**Comment by jqhph** [comment]
一般这个是跟随`app.locale`参数变化的

**Comment by Warrens-yg** [comment]
其他的内容是跟着`app.locale`变化的,唯独这个required提示不变
![批注 2020-09-06 175409](https://user-images.githubusercontent.com/46614146/92322060-ff14b180-f069-11ea-81a9-f370bba9c141.png)

**Comment by jqhph** [comment]
app.locale 设置为英文，然后浏览器语言也要设置为英文
