### ISSUE TITLE
地图组件 提交表单 无法获取字段

### ISSUE THREAD

**Issue by Vfuryx** [jqhph/dcat-admin#525]
```
<?php

namespace App\Admin\Forms\Settings;

use Dcat\Admin\Widgets\Form;

class Contact extends Form
{
    public function handle(array $data)
    {
        dd($data);
        
    }
    
     public function form()
    {
        $this->confirm('您确定要提交表单吗', 'content');

        $this->map('latitude','longitude', '经纬度')
            ->rules(['required']);
    }
    
    public function default()
    {
        return [];
    }
}

```

![image](https://user-images.githubusercontent.com/16946029/92306249-39297900-efc0-11ea-9891-646d0a5bdb7f.png)

表单有提交到数据
![image](https://user-images.githubusercontent.com/16946029/92306262-52cac080-efc0-11ea-9d05-5f40e866af94.png)

打印为空
![image](https://user-images.githubusercontent.com/16946029/92306267-5fe7af80-efc0-11ea-8a74-ce3416d593d5.png)

**Comment by jqhph** [comment]
什么版本？

**Comment by Vfuryx** [comment]
1.7.1

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/92341592-c7048180-f0f0-11ea-8822-bc881341a6e7.png)
![image](https://user-images.githubusercontent.com/20312339/92341611-d4ba0700-f0f0-11ea-82be-195327be1741.png)

171腾讯地图，测试了下，正常

**Comment by jqhph** [comment]
确实有问题

**Comment by jqhph** [comment]
先用这种方式接收参数吧 `request('latitude')`

**Comment by jqhph** [comment]
已修复，可以先更新master分支代码
