### ISSUE TITLE
请问 laravel-admin 2.0 BEAT 新增的方法会同步到 dcat-admin 吗？

### ISSUE THREAD

**Issue by FanchangWang** [jqhph/dcat-admin#530]
### Description:

请问 laravel-admin 2.0 BEAT 新增的功能会同步到 dcat-admin 吗？比如新的视图渲染机制等~

文档地址--> [laravel-admin 2.0 JS 代码和 PHP 代码分离](https://learnku.com/articles/48845#f1e17f)

**Comment by jqhph** [comment]
这个功能现在也是可以这样使用的

**Comment by jqhph** [comment]
这个功能现在也是可以这样使用的

**Comment by moxuanyuan** [comment]
> 这个功能现在也是可以这样使用的

核心代码可以的话，也分离出来，看着php混夹js代码，是一件很辛苦的事，如同上文中所说，后期的维护成本很高。
