### ISSUE TITLE
保存表单-错误-当前页面已失效

### ISSUE THREAD

**Issue by cpken** [jqhph/dcat-admin#531]
- Laravel Version: 5.6.40
- PHP Version: 7.4.3
- Dcat Admin Version: v.1.7.1

### 说明

每次对表单进行保存的时候，都会提示：
```
对比起，当前页面已失效，请刷新浏览器。
```

![QQ拼音截图20200908152158](https://user-images.githubusercontent.com/38244430/92445993-c39ff180-f1e7-11ea-9f6b-a097a4905dab.png)
`

**Comment by jqhph** [comment]
参考文档版本升级须知

**Comment by cpken** [comment]
执行以下命令，解决问题：
```
$ php artisan admin:publish --assets --force
```
