### ISSUE TITLE
工具按钮在操作后无法正确返回（URL中有自定义参数，会跳刷新时丢失参数）

### ISSUE THREAD

**Issue by LazyBaby** [jqhph/dcat-admin#534]
- Laravel Version: 7.25.0
- PHP Version: 7.4.2
- Dcat Admin Version: 1.7.1

### Description:

在页面A使用工具按钮跳转到页面B(URL中添加了其他参数query)，在B页面使用工具按钮“批量异常处理”（或行工具按钮“异常处理”），弹窗提交处理完成后会刷新B页面，但是B页面的query无法带回，造成B页面数据空白。场景举例：

> 菜单路由为资源路由；
A页面是二级页面；
A页面地址：`/admin/check-tmall/3` ；
A页面工具栏append一个button_A,跳转为B页面，地址为：`/admin/check-tmalls/abnormal-tmall?checkYm=202002&recordId=3` ;

在B页面操作如下：

B页面 -> 行操作（异常处理）-> 提交弹窗表单 -> 成功（或失败）后刷新B页面（success或error方法）丢失参数，B页面地址变成 `/admin/check-tmalls/abnormal-tmall` ;

B页面 -> 批量操作（批量异常处理）-> 提交弹窗表单 -> 成功（或失败）后刷新B页面（success或error方法）丢失参数，B页面地址变成 `/admin/check-tmalls/abnormal-tmall` ;

注：
 - 不仅仅是批量处理，自定义的导入在弹窗结束后也会刷新页面，同样会造成参数丢失。

--- 

我当前的处理办法是在异常处理时的弹窗表单中获取当前页面的REQUEST_URI（可以获取当前页面不包含域名的完整地址），并通过隐藏域提交，然后使用url方法将此参数放入success或error的第二个参数中（redirectTo）

有没有其他办法获取到页面的参数呢？防止弹窗表单成功或失败后刷新页面时丢失参数？

或者有没有其他办法，使我跳转的时候将参数转化为url的绑定参数，例如A页面地址`/admin/check-tmall/3`的结尾'3'，我使用route函数去做绑定没有成功

**Comment by jqhph** [comment]
工具表单实例化的时候可以传入刷新url `$form->setCurrentUrl()`

**Comment by LazyBaby** [comment]
> 工具表单实例化的时候可以重新刷新url `$form->setCurrentUrl(xxx)`

谢谢，测试通过了，之前没有在文档中注意到。
我还有个属于模态窗显示的问题，会重新提交一个问题，麻烦看下。
