### ISSUE TITLE
图标筛选输入框容易卡死

### ISSUE THREAD

**Issue by winter-ice** [jqhph/dcat-admin#536]
- Laravel Version: 7
- PHP Version: 7.2
- Dcat Admin Version: 1.7.2

### Description:
图标筛选输入框容易卡死浏览器

### Steps To Reproduce:
在图标筛选输入框进行输入删除操作几秒钟

**Comment by jqhph** [comment]
没复现出来

**Comment by winter-ice** [comment]
![image](https://user-images.githubusercontent.com/24680921/92673625-185d7c80-f34e-11ea-920b-f598f1885893.png)
就是在这个输入框 进行输入，删除的操作，边输入边删除就会卡死，然后缓一会儿就会好
