### ISSUE TITLE
模态窗显示问题

### ISSUE THREAD

**Issue by LazyBaby** [jqhph/dcat-admin#537]
- Laravel Version: 7.25.0
- PHP Version: 7.4.2
- Dcat Admin Version: 1.7.1

### Description:
如图，截图只是我为了复现当初遇到的问题

![image](https://user-images.githubusercontent.com/15863793/92579884-544a0080-f2c0-11ea-8e94-665ef9b5e694.png)

这里碰到几个问题：
1.通过测试，如果我选择xl的尺寸，只要我要显示比较多的列，同样会出现这个问题
2.点击模态窗上的工具栏中的工具按钮（或行操作按钮），弹出的表单弹窗会出现在模态窗下层，需要关闭模态窗才可以看到（所以截图上并没有显示出来）
3. ~~模态窗上会显示下层的搜索框（这个问题没有复现出来，有可能是我碰巧出现的）~~

**Comment by jqhph** [comment]
你可以自己调整下这个样式，而且文档提供的异步加载表格不是这个样式的

**Comment by LazyBaby** [comment]
> 你可以自己调整下这个样式，而且文档提供的异步加载表格不是这个样式的

好的

**Comment by MAZENAN** [comment]
请问是怎么解决的呢？我也遇到了
