### ISSUE TITLE
Box中tool 能否支持复杂的筛选？

### ISSUE THREAD

**Issue by jiangfeiyu** [jqhph/dcat-admin#541]
- Laravel Version: 8.0
- PHP Version: 7.3.x
- Dcat Admin Version:1.7.3

### Description:
Box中如何能支持类似fitler的选项和后端图表做交互，目前用dropdown只能处理简单的查询，无法处理时间的需求

是否可以使用工具表单来联动？

![微信截图_20200910174019](https://user-images.githubusercontent.com/5492375/92712812-c4be5380-f38c-11ea-81d6-9d0ecacaa2d5.png)

**Comment by jiangfeiyu** [comment]
是否可以使用工具表单来联动？

**Comment by jqhph** [comment]
需要自己实现
