### ISSUE TITLE
上传文件后动态设置表单值，能实现吗？

### ISSUE THREAD

**Issue by zhou0818** [jqhph/dcat-admin#545]
- Laravel Version: 7.x
- PHP Version: 7.2
- Dcat Admin Version: 1.7.0

### Description:

我现在有个需求，上传身份证图片后，通过第三方的文字识别，把身份证填回表单中，就是姓名，身份证号那些。有识别错误的自己修改。看了很久文档也没思路，求指点。

**Comment by jqhph** [comment]
按目前的方法实现会比较麻烦，需要写JS定时器去监听文件上传成功后的隐藏域表单的值，然后拿到上传后的文件路径再去识别显示

**Comment by zhou0818** [comment]
> 按目前的方法实现会比较麻烦，需要写JS定时器去监听文件上传成功后的隐藏域表单的值，然后拿到上传后的文件路径再去识别显示

识别以后的显示也是要用js写进去吗

**Comment by jqhph** [comment]
是的
