### ISSUE TITLE
数据迁移

### ISSUE THREAD

**Issue by zhao0229** [jqhph/dcat-admin#547]
- Laravel Version: 8.0.3
- PHP Version: 7.3.4
- Dcat Admin Version: 1.7.3

### Description:当数据库类型为sql server时，运行数据库迁移报错
[Microsoft][ODBC Driver 17 for SQL Server][SQL Server]当 IDENTITY_INSERT 设置为 OFF 时，不能为表 'admin_permissions' 中的标识列插入显式值

**Comment by jqhph** [comment]
em...没用过`sql server`，如果有解决方案欢迎提交PR~
