### ISSUE TITLE
分步表单数据问题

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#548]
代码截图：https://monosnap.com/file/Z0Vxy110UfkD4fmKs4lEuinC5sHkpK
点击提交按钮后，通过$form->multipleSteps()->fetchStash()获取表单数据，取到的是number的默认值，不是修改后的值，想得到number修改后的值，这个怎么实现？

**Comment by jqhph** [comment]
用 request()->all()
