### ISSUE TITLE
grid 表格宽度自适应问题

### ISSUE THREAD

**Issue by puzzle9** [jqhph/dcat-admin#553]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 1.7.4

### Description:

只有加入 `responsive()` 或 `hide()` 时候才会进行自适应

### Steps To Reproduce:

正常
```
    protected function grid()
    {
        return Grid::make(new School(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('name');
            $grid->column('sort')->responsive();
            $grid->column('updated_at')->sortable();
        });
    }
```
![深度截图_选择区域_20200913212448](https://user-images.githubusercontent.com/13518196/93019145-d4959c00-f607-11ea-9271-a7b1a1b53f0b.png)

显示有误
```
    protected function grid()
    {
        return Grid::make(new School(), function (Grid $grid) {
            $grid->column('id')->sortable();
            $grid->column('name');
            $grid->column('sort');
            $grid->column('updated_at')->sortable();
        });
    }
```
![深度截图_选择区域_20200913212401](https://user-images.githubusercontent.com/13518196/93019144-d2cbd880-f607-11ea-873a-b3865b86ed0a.png)

**Comment by jqhph** [comment]
是的，你也可以手动加css，让表格上一层div显示滚动条即可

**Comment by puzzle9** [comment]
> 是的，你也可以手动加css，让表格上一层div显示滚动条即可

我曾经以为 你会告大手一挥 告诉我 这个功能 我来

**Comment by jqhph** [comment]
> > 是的，你也可以手动加css，让表格上一层div显示滚动条即可
> 
> 我曾经以为 你会告大手一挥 告诉我 这个功能 我来

1.0不会再增加新功能了，2.0可以考虑加上这个

**Comment by zhujingxiu** [comment]
2.0的自适应要怎么操作的，前端控制的吗
