### ISSUE TITLE
数据表格第一次进入如何不显示数据？

### ISSUE THREAD

**Issue by 2494911084** [jqhph/dcat-admin#554]
- Laravel Version: 7.0
- PHP Version: #.#.#
- Dcat Admin Version: 1.7
### Description:
因为数据比较多，想要在数据表格第一次进入时不显示数据，在筛选时再显示数据不知道，这个要怎么办啊 大哥求教

**Comment by jqhph** [comment]
参考文档表格数据源，重写数据仓库的`get`方法
