### ISSUE TITLE
数据导出-报错-提示类型错误

### ISSUE THREAD

**Issue by cpken** [jqhph/dcat-admin#555]
- Laravel Version: 7.16.1
- PHP Version: 7.4.3
- Dcat Admin Version: 1.5.3

### 说明

根据文档使用 数据导出 功能，出现如下错误：

```
TypeError
Argument 3 passed to Dcat\EasyExcel\Exporters\Exporter::writeHeadings() must be of the type array,
 bool given, called in D:\gitee\dcat-admin-demo\vendor\dcat\easy-excel\src\Exporters\WriteSheet.php on line 73
```

项目源码：

```
          $titles = [
                'id'                => 'ID',
                'user_id'           => '用户名',
                ···
            ];
            $grid->export($titles)->rows(function (array $rows) {
                foreach ($rows as $index => &$row) {
                    $user = User::find($row['user_id']);
                    $row['user_id'] = $user->username;
                }

                return $rows;
            })->filename('test-'.date('YmdHis'));
```

### Steps To Reproduce:
![QQ拼音截图20200914110207](https://user-images.githubusercontent.com/38244430/93039398-f465a800-f679-11ea-99c0-4faff90dc043.png)

**Comment by jqhph** [comment]
旧版本没有数据时导出会报错，升级到170或以上版本就行了

**Comment by cpken** [comment]
谢谢，问题解决了。

**Comment by cpken** [comment]
- php 7.4.3
- laravel 7.16.1
- dcat-admin 1.7.4

### 问题描述

增加了数据筛选条件后导出文件报错

```
ErrorException
A non well formed numeric value encountered
```
![1](https://user-images.githubusercontent.com/38244430/93041703-c1beae00-f67f-11ea-82c4-59e420577392.png)
![2](https://user-images.githubusercontent.com/38244430/93041706-c2efdb00-f67f-11ea-8542-2aec9b41890b.png)

**Comment by jqhph** [comment]
好的我看下这个问题

**Comment by cpken** [comment]
我又发现了一个新问题，把目前的此问题与新问题，编辑成了新问题发表了。谢谢。
