### ISSUE TITLE
弹窗表格里面使用规格筛选器条件无效，父级页面会刷新

### ISSUE THREAD

**Issue by cz0634** [jqhph/dcat-admin#556]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 1.7.1

### Description:
在表格表单里面使用规格筛选器，父级页面会增加条件刷新。表格表单内不会刷新数据
![avatar](C://Users//Administrator//Desktop//QQ图片20200914111536.png)

**Comment by jqhph** [comment]
已修复，可以先更新master分支代码
