### ISSUE TITLE
数据导出-问题-筛选后的数据无法导出与导出不符

### ISSUE THREAD

**Issue by cpken** [jqhph/dcat-admin#557]
- Laravel Version: 7.16.1
- PHP Version: 7.4.3
- Dcat Admin Version: 1.7.4

### 问题 1：筛选后的数据无法导出

问题描述：通过条件筛选出来的数据共 20 条，点击导出之后，报错，如下图
![2](https://user-images.githubusercontent.com/38244430/93042897-e36d6480-f682-11ea-91bf-f4ccbbbc35ca.png)
![1](https://user-images.githubusercontent.com/38244430/93042905-e8321880-f682-11ea-9baa-7602f6ba78f2.png)

### 问题 2：筛选后的数据导出不符

问题描述：通过条件筛选出来的数据，点击导出，生成的 Excel 文件的内容与筛选出来的数据不符。

Excel 文件：
![3](https://user-images.githubusercontent.com/38244430/93043112-6e4e5f00-f683-11ea-9d62-04c216721a75.png)

筛选出的数据：
![4](https://user-images.githubusercontent.com/38244430/93043122-77d7c700-f683-11ea-94c0-db977cc8d83e.png)
![5](https://user-images.githubusercontent.com/38244430/93043125-7ad2b780-f683-11ea-984f-e43192cb4cc0.png)

**Comment by jqhph** [comment]
测试了下，并没有重现你的问题，筛选过后导出是正常的
