### ISSUE TITLE
文件上传问题

### ISSUE THREAD

**Issue by dairidong** [jqhph/dcat-admin#56]
我在新项目中使用了 dcat admin，发现文件上传有点小问题。
这是我的代码片段，
![image](https://cdn.learnku.com/uploads/images/202004/29/49344/5PtqDB1aJ3.png!large)

1\. 在编辑页面，保存的时候会发生数据库报错，原因是 file 字段的值为空，但是我并没有对这个字段的文件进行修改操作；
2\. 点击删除文件的按钮，重新上传一个新文件后，不退出编辑页面，直接再上传一个新的文件，保存到数据库的字段会变为 "第一个文件的路径，第二个文件的路径" 这种格式，应该是前端组件的问题。
希望能得到答复和解决

**Comment by jqhph** [comment]
感谢反馈，预计今晚或明早发布新版本，到时候会解决这个问题。

**Comment by dairidong** [comment]
> 感谢反馈，预计今晚或明早发布新版本，到时候会解决这个问题。

谢谢回复，这个模板对我来说功能比laravel-admin要更全一点，希望能越做越好

**Comment by jqhph** [comment]
新版本v1.2.5已发布，更新升级即可，更新日志请查看https://learnku.com/docs/dcat-admin/1.x/v125/8166

**Comment by dairidong** [comment]
@jqhph 你好，主题中的第二问题，我执行完更新步骤后，仍有相同的问题

**Comment by jqhph** [comment]
> @jqhph 你好，主题中的第二问题，我执行完更新步骤后，仍有相同的问题

已经修复，你需要重新发布资源并清除浏览器缓存

**Comment by dairidong** [comment]
> > @jqhph 你好，主题中的第二问题，我执行完更新步骤后，仍有相同的问题
> 
> 已经修复，你需要重新发布资源并清除浏览器缓存

我已经确认过这些步骤都执行过了，单文件上传如主题中所述的操作，还是会变成下图的样子。
![image](https://user-images.githubusercontent.com/48778797/80668478-996d5300-8ad4-11ea-8bc5-aee116e4595a.png)

**Comment by jqhph** [comment]
确实第二个问题还在，我修复下，你后面可以更新master分支代码

**Comment by dairidong** [comment]
> 确实第二个问题还在，我修复下，你后面可以更新master分支代码

感谢您的帮助！

**Comment by jqhph** [comment]
这个问题已修复，我重新发布了1.2.5版本，你需要先退回1.2.0或更低版本，然后清除composer缓存，再重新升级到1.2.5版本即可。
