### ISSUE TITLE
示例代码里的form控制器数据库保存数据成功，但是页面弹出保存失败提示

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#561]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.6.5

### Description:

![image](https://user-images.githubusercontent.com/24761416/93434192-65b38e00-f8fa-11ea-9a28-e40b00c58db2.png)
我想用示例代码里的form控制器设置一些系统参数，我自己写了路由和store保存表单数据，但是，保存成功后（数据已写入数据库），页面弹出如下提示
![image](https://user-images.githubusercontent.com/24761416/93434119-4fa5cd80-f8fa-11ea-940d-c98afe4ca957.png)

我应该怎么自定义返回正确的消息或者怎么禁用系统默认弹出的错误消息

**Comment by jqhph** [comment]
推荐使用工具表单，不需要自己定义路由；你这种方式可以参考正常表单的返回格式

**Comment by joey2017** [comment]
还是用工具表单好了

**Comment by joey2017** [comment]
> 推荐使用工具表单，不需要自己定义路由；你这种方式可以参考正常表单的返回格式

working_hours_unit_price[new_1][min]: 0
working_hours_unit_price[new_1][max]: 5
working_hours_unit_price[new_1][stars]: 1
working_hours_unit_price[new_1][value]: 100
working_hours_unit_price[new_1][_remove_]: 0
working_hours_unit_price[new_2][min]: 10
working_hours_unit_price[new_2][max]: 15
working_hours_unit_price[new_2][stars]: 3
working_hours_unit_price[new_2][value]: 200
working_hours_unit_price[new_2][_remove_]: 0
working_hours_unit_price[new_3][min]: 15
working_hours_unit_price[new_3][max]: 20
working_hours_unit_price[new_3][stars]: 4
working_hours_unit_price[new_3][value]: 250
working_hours_unit_price[new_3][_remove_]: 0
working_hours_unit_price[new_1][min]: 5
working_hours_unit_price[new_1][max]: 10
working_hours_unit_price[new_1][stars]: 2
working_hours_unit_price[new_1][value]: 150
working_hours_unit_price[new_1][_remove_]: 0

form表单table组件，在编辑表单的时候新增一行，增加的键是new_1，这个怎么自定义或者不要和原来的键重复呢

**Comment by jqhph** [comment]
我看下

**Comment by jqhph** [comment]
已修复，可以先更新master分支代码

**Comment by joey2017** [comment]
好的，感谢问题可以很快的及时解决
