### ISSUE TITLE
关闭全屏形式时滚动条消失

### ISSUE THREAD

**Issue by shepherdscribe** [jqhph/dcat-admin#566]
- Laravel Version: 7.24
- PHP Version: 7.2.5
- Dcat Admin Version: 1.7.4

### Description:
当弹出窗口最大化时，然后关闭时，滚动条消失。

### Steps To Reproduce:
1. 最大化任何形式
![s1](https://user-images.githubusercontent.com/62448059/93725139-4ad56800-fbdf-11ea-934c-ad5cfe49f7f2.JPG)
2. 点击关闭
3. 滚动条消失。

**Comment by jqhph** [comment]
哪个部分的滚动条消失了？

**Comment by shepherdscribe** [comment]
嗨，谢谢您的回复。关闭弹出窗口后，背景中的滚动条消失。

**Comment by jqhph** [comment]
确实有问题，感谢反馈

**Comment by shepherdscribe** [comment]
谢谢.
