### ISSUE TITLE
请问一下，怎么不用php artisan serve就能访问到后台页面？谢谢

### ISSUE THREAD

**Issue by xiajinjun** [jqhph/dcat-admin#568]
- Laravel Version: 7.x
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.4

### Description:
谢谢提供这么好的后台管理系统 ，本人对laravel 不熟，请教一下。

在本地可以用php artisan serve命令后，
然后通过 http://127.0.0.1:8000/admin 可以访问后台。

但是传到服务器之后，使用php artisan serve 却不能访问服务器上的后台
http://服务器IP:8000/admin
这个命令也试过了，不行
php artisan serve --host=服务器IP --port=8000

可以不使用php artisan serve，就可以访问后台的方法吗? 谢谢！

**Comment by jqhph** [comment]
参考laravel文档安装章节

**Comment by xiajinjun** [comment]
谢谢，已经解决，
用php artisan serve --host=0.0.0.0
就可以了
