### ISSUE TITLE
分步表单无法编辑的问题

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#569]
文档中明确说了分步表单默认是没有编辑功能，但提供了一种编辑方法，就是编辑时将分步表单转为普通表单形式。本身使用分步表单，一般情况下都是因为表单内容很多才使用分步。如果按文档中的方法，分步一套定义字段代码，编辑又是另一套定义字段代码，这将会是很笨拙很混乱。

我想到的方法是，既然分步表单有`remember`方法，能否在编辑时将数据使用 `stepBuilder->stash()`存入到session中，后端验证时，再根据参数 `ALL_STEPS` 判断是分步验证还是最后一步提交数据。于是写了代码实践，思路是可行，但遇到问题是无法update数据。研究dcat代码后，主要原因是 `Dcat\Admin\Form.php` 第938行 `foreach ($this->builder->fields() as $field) {`，如果将 `$this->builder->fields()` 改为 `$this->fields()` 则可以update 数据。希望作者改进一下。

**Comment by jqhph** [comment]
好的，我会考虑是否在后面的版本中加上编辑功能
