### ISSUE TITLE
有关权限、多语言和版本管理的建议

### ISSUE THREAD

**Issue by yuanshe** [jqhph/dcat-admin#570]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 1.7.4

### Description:

- 权限、菜单相关功能过于复杂，使用起来很别扭。以及一个细节有问题：非 `Administrator` 管理员虽然没有 `helpers` 的权限，但依然会显示 `helpers` 菜单，文档中找不到方法可以为非 `Administrator` 管理员关闭 `helpers` 菜单

- 多语言设计的很不方便。每新建一个后台路由，就要修改 3 ~ 4 处语言包，编辑的内容往往都是同一个翻译。尤其是『默认面包屑翻译』，比如：_"Auth/Users" 的路由，如果将 "users" 翻译为『管理员』，就会污染其它 "users" 的路由，如果仅为了面包屑导航而创建一个控制器语言包，又显得多此一举_
  > 建议增加路由语言包，针对每个路由配置唯一的翻译。菜单、权限、面包屑导航、页面标题等均使用相对应的路由语言包翻译作为默认翻译，同时保留为每一处单独配置翻译的选项

- 菜单、权限等配置无法加入版本管理，只能手动导入导出或在生产环境开发。这虽然是 laravel-admin 的问题，但是希望也能得到解决，因为这个问题对于区分开发环境和生存环境的项目来说是个灾难

**Comment by jqhph** [comment]
1. 菜单和权限目前的方案是最灵活，可适用范围最宽泛的方案，如果你觉得有更好的方案也可以提一下。关于`helpers`的使用文档多处位置有提及，例如常见问题和开发工具；
2. 每个控制器都有对应的语言包，可以在对应的控制器语言包文件中更改；
3. laravel有migration和seeder可以解决菜单和权限的导入问题

**Comment by yuanshe** [comment]
1. 关于 `helpers` 菜单的问题，我并不是问 `helpers` 如何使用，而是对「`helpers 菜单`在没有权限时**不会隐藏**」产生疑问。这点在文档 _[http://www.dcatadmin.com/docs/](http://www.dcatadmin.com/docs/)_ 中并没有提及
   > 我通过查看源码中的 `Dcat\Admin\Layout\Menu::register()` 方法得知，`helpers 菜单` 是**硬编码**在核心代码中的，也就是说目前没有办法可以为 `helpers 菜单` 绑定权限？

2. 基于以下两点原因，我个人依然认为基于路由配置多语言是个不错的方案：
    1. `控制器语言包`并不能避免污染的问题，比如一个项目中很可能出现多个名为 `UserController` 的控制器，诸如此类的名称还有 `GroupController`、`TypeController` 等等，由于语言包并没有携带命名空间，重复名称控制器下的翻译均会相互污染
    2. 现有的语言包策略虽然很灵活，但是却过于繁琐，使用后台系统的初衷就是为了方便快捷。像菜单、权限、页面标题、面包屑导航的翻译，大多数情况下都是相同的，完全没有必要分别定义在多处。（而且貌似现在权限名称还不支持翻译）

3. 使用 migration 和 seeder 定义菜单过于繁琐，不过目前确实也没有更好的方式了。希望后期能实现类似于「后台修改菜单的同时自动导出一个文件，上线再使用 artisan 命令导入」或「修改菜单时自动生成 migration」的功能

**Comment by jqhph** [comment]
1. helpers 菜单只允许在开发环境使用，绑定权限没有意义
2. 我考虑过这个问题，但是这种翻译发生冲突的情况相对来说还是比较少；如果有个别字段确实发生冲突了，那则增加个`key`在控制器中`写死`就行了。菜单的翻译`2.0`会抽出来，至于页面标题、面包屑这些都可以写在`global.php`中

**Comment by yuanshe** [comment]
非常感谢能抽空回复！期待 2.0 能有意想不到的表现
关于 `控制器语言包` 污染的问题，我个人还是希望在后期能有个更规范的方案。毕竟，光是 `Auth/Users` 下的「users」翻译成「管理员」造成的冲突，就够让人别扭了

**Comment by faydanube** [comment]
> 1. helpers 菜单只允许在开发环境使用，绑定权限没有意义

開發工具使用的權限與顯示的設計感非常分裂。
1. 「普通菜單」與「開發工具菜單」被分裂了
2. 「開發工具菜單」的 `顯示` 與 `權限` 是分裂的，顯示在 config 進行配置，權限卻要單獨去 seeder 填充數據庫……
3.  默認也沒有檢測非 local 環境自動隱藏此模塊~~上線的時候，要花精力去關注 admin.php 這個文件的配置項~
4. 不知是否能支持 admin:make 命令，可以直接默認不開啟視圖開發工具即可……
