### ISSUE TITLE
BUG grid里面，只要使用了sortable，在model里面使用select方并指定字段是无效的

### ISSUE THREAD

**Issue by herenet** [jqhph/dcat-admin#573]
官方代码：
![image](https://user-images.githubusercontent.com/568403/94263365-849fc900-ff67-11ea-851a-f59a24b37a45.png)
![image](https://user-images.githubusercontent.com/568403/94263383-8b2e4080-ff67-11ea-8fd0-344c9e9ac331.png)

这里面写死了只能是*，那么在联表查询时就无法使用字段别名。解决方案和应用场景如下图：
重写getGridColumns()方法。
![image](https://user-images.githubusercontent.com/568403/94263404-93867b80-ff67-11ea-8bed-87d34110a4f7.png)

应用场景：
![image](https://user-images.githubusercontent.com/568403/94263435-9c774d00-ff67-11ea-97c8-8dcbbcf2ad95.png)

**Comment by jqhph** [comment]
也可以在`Channel`类中重写 `getGridColumns` 方法
