### ISSUE TITLE
开发插件-数据迁移

### ISSUE THREAD

**Issue by tizipso** [jqhph/dcat-admin#574]
- Laravel Version: 8.*
- PHP Version: 7.4.10
- Dcat Admin Version: 1.7.4

### Description:
php artisan migrate 
无法自动发现扩展包中的「数据库迁移」，如果要执行，必须指定具体文件夹

**Comment by jqhph** [comment]
插件功能2.0版本会有大改动，2.0的beta版本也即将发布，不妨等2.0之后再开发成插件

**Comment by tizipso** [comment]
好吧
