### ISSUE TITLE
获取当前登陆的用户的问题

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#575]
我在编写测试的时候，需要以特定用户登陆，代码如下
```
        $this->actingAs(User::find(2));
```
结果没有问题，我用 `Auth::user()` 检查已经成功以这个角色登陆了，但是用 `admin()->user()` 的方法却无法正确获取到，因为我在 Model 的构造函数中动态设置表名的时候使用了 `admin()->user()` 方法来获取当前登陆用户的信息，所以现在这种情况不知道是什么原因，如果解决不了，我是不是需要把 Model 中的方法换掉

**Comment by Warrens-yg** [comment]
就是在测试的时候输出以下代码跟在模型中输出以下代码，结果完全相反
`
dd(Auth::user(), admin()->user());
`
测试文件中结果是 User, null
模型的构造函数中是 null, User

**Comment by jqhph** [comment]
没用过 `actingAs`，`Auth::user`默认用的不是`admin` ；然后你这个`admin()`函数是什么东西？
