### ISSUE TITLE
我按照教程配置了上传图片，结果上传头像的时候，可以上传成功，服务器文件夹里也能看到，为什么头像在页面显示不出来呢？

### ISSUE THREAD

**Issue by qingma1** [jqhph/dcat-admin#577]
- Laravel Version: 5.8
- PHP Version: 7.2
- Dcat Admin Version: 1.7.3

### Description:

我按照教程配置了上传图片，结果上传头像的时候，可以上传成功，服务器文件夹里也能看到，为什么头像在页面显示不出来呢？
<img width="781" alt="screen_01" src="https://user-images.githubusercontent.com/31962111/94368966-a5a81b80-0119-11eb-8db8-8ff75aa9ca4a.png">

### Steps To Reproduce:

**Comment by jqhph** [comment]
试试 `php artisan storage:link`

**Comment by qingma1** [comment]
可以了，感谢，issue可以关闭啦~~
