### ISSUE TITLE
表单树形菜单id值被替换

### ISSUE THREAD

**Issue by leetotti** [jqhph/dcat-admin#578]
<img width="425" alt="WX20200929-160336@2x" src="https://user-images.githubusercontent.com/12230465/94530226-5d017700-026d-11eb-9d41-98e671665822.png">
<img width="566" alt="WX20200929-160435@2x" src="https://user-images.githubusercontent.com/12230465/94530290-79051880-026d-11eb-8e19-fbf8da43849c.png">
数据库里数据 id 为 1495422702006173986
接过通过表单树形菜单  被转成了 1495422702006174000

**Comment by jqhph** [comment]
提问题描述清楚一些，你做了什么操作？这个表又是怎么回事

**Comment by leetotti** [comment]
表1   分类表  
主要字段   id   name  sort  panret_id
表2  外部分类表(第三方平台获取)
主要字段  id   parent_id  name
表3    分类表对应外部分类表(多对多关系)  表1 一行  可关联  多个表2  例如   表2中  男装  女装  我在表一中统一为服装

关联关系没有任何问题

$form->tree('pospal_category','对应银豹分类')
                ->nodes((new PospalProductCategory())->allNodes())
                ->customFormat(function($v){
                    if(!$v) return [];
                    return array_column($v,"id");
                });
现在使用这个方式  表2的主键  id 在存入关联表时 被替换了 如之前截图所示
