### ISSUE TITLE
checkbox 的option 报错 

### ISSUE THREAD

**Issue by leetotti** [jqhph/dcat-admin#579]
$form->checkbox('pospal_category','银豹分类')->options(PospalProductCategory::top()->pluck('name','id'));
这段代码  在 create时  没有问题
但在修改的时候  报错 报错如下
<img width="797" alt="WX20200929-185018@2x" src="https://user-images.githubusercontent.com/12230465/94549348-a610f580-0284-11eb-8965-224f0229276e.png">

**Comment by jqhph** [comment]
是不是多对多关联关系？

**Comment by jqhph** [comment]
参考表单关联关系文档
