### ISSUE TITLE
外键字段无法调用翻译文件来翻译

### ISSUE THREAD

**Issue by vip68** [jqhph/dcat-admin#580]
- Laravel Version: 6.18.38
- PHP Version: 7.4.9
- Dcat Admin Version: 1.7.4

### Description:
含有外键关联的字段，好像没办法调用lang目录下的文件来翻译
例如`$grid->column('channel.name');`
要在翻译文件里怎么写呢？

**Comment by jqhph** [comment]
```php
return [
    'fields' => [
        'channel' => [
            'name' => '名称'
        ],
    ],
];
```
