### ISSUE TITLE
Action 类使用 make 方法创建实例时链式调用 setKey 方法无法显示功能按钮

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#583]
按照文档的调用方法 `MyAction::make()->setKey($id);` 无法显示功能按钮。

看了源码中的 `setKey` 方法并没有返回 `$this`，在源码中加回 `return $this;` 则可以了

 希望修正，谢谢

**Comment by jqhph** [comment]
好的，感谢建议

**Comment by jqhph** [comment]
已增加这个功能，可以先更新master分支代码

```php
composer update dcat/laravel-admin:"dev-master"
```
