### ISSUE TITLE
分步表单如何获取上一步的输入  以及修改自定义保存

### ISSUE THREAD

**Issue by leetotti** [jqhph/dcat-admin#584]

**Comment by leetotti** [comment]
现在点击下一步  请求的是404  请问 需要单独写一个路由吗

**Comment by leetotti** [comment]
> _No description provided._

我的想法是  根据第一步输入的内容  来动态加载第二部里的  数据 类似于联动 比如我在第一步里 选择了 用户A  在第二部里  我的下来菜单  里  只显示  用户A的收货地址列表

**Comment by jqhph** [comment]
通过session可以获取所有数据，或者`request()->all()`;

修改自定义保存可以通过表单事件saving或者重写数据库store方法
