### ISSUE TITLE
工具栏的按钮可以添加在新增按钮后面吗？

### ISSUE THREAD

**Issue by zhou0818** [jqhph/dcat-admin#589]
- Laravel Version: 8.0
- PHP Version: 7.2
- Dcat Admin Version: 1.7.4

### Description:
工具栏按钮可以往页面右方添加吗？

**Comment by jqhph** [comment]
可以，给按钮加上`class`  `pull-right`

**Comment by zhou0818** [comment]
> 可以，给按钮加上`class` `pull-right`

工具栏的按钮之间的间隔是自动的？看了css没找到margin，pull-right后该怎么设置按钮间隔
