### ISSUE TITLE
在表单中使用多对多的表格，出现__remove__错误

### ISSUE THREAD

**Issue by RayZoey** [jqhph/dcat-admin#59]
- Laravel Version: 7
- PHP Version: 7
- Dcat Admin Version: 1.2
希望实现的页面效果:
![image](https://user-images.githubusercontent.com/24807484/80614126-aa847880-8a70-11ea-988c-8a68c6568f96.png)
订单与项目之间的关系为N:N
中间表:
![image](https://user-images.githubusercontent.com/24807484/80614426-05b66b00-8a71-11ea-8b4f-25368e9dd679.png)

### 错误信息:
```php
exception: "ErrorException"
file: "/Users/ray/shoes-manage/vendor/dcat/laravel-admin/src/Form/Field/Table.php"
line: 73
message: "Undefined index: _remove_"
```

### form部分代码:
```php
            $form->table('item', function (Form\NestedForm $table) {
                $table->select('item_id', '所属分类')->options(function ($id) {
                    $item = Item::find($id);
                    if ($item) {
                        return [$item->id => $item->name];
                    }
                })->ajax('api/item')->required();
                $table->decimal('price', '价格')->required();
            });
```

### OrderModel
```php
    public function item(): BelongsToMany
    {
        $pivotTable = 'order_item'; // 中间表

        $relatedModel = Item::class; // 关联模型类名

        return $this->belongsToMany($relatedModel, $pivotTable, 'order_id', 'item_id');
    }
```

```php
    public function order(): BelongsToMany
    {
        $pivotTable = 'order_item'; // 中间表

        $relatedModel = Order::class; // 关联模型类名

        return $this->belongsToMany($relatedModel, $pivotTable, 'item_id', 'order_id');
    }
```

**Comment by jqhph** [comment]
感谢反馈

**Comment by RayZoey** [comment]
> 感谢反馈

请问目前有类似功能实现可替代的方案吗

**Comment by jqhph** [comment]
也许你可以参考以下这个项目，或许可以帮到你 https://github.com/jade-kun/sku

**Comment by RayZoey** [comment]
> 也许你可以参考以下这个项目，或许可以帮到你 https://github.com/jade-kun/sku

好的，谢谢，其实可以直接使用hasMany方式，但是回显的时候不会有记录
```php
            $form->hasMany('item', function (Form\NestedForm $form) {
                $form->select('item_id')->options(function ($id) {
                    $item = Item::find($id);
                    if ($item) {
                        return [$item->id => $item->name];
                    }
                })->ajax('api/item');
                $form->decimal('price', '价格');
            });
```

**Comment by jqhph** [comment]
> > 也许你可以参考以下这个项目，或许可以帮到你 https://github.com/jade-kun/sku
> 
> 好的，谢谢，其实可以直接使用hasMany方式，但是回显的时候不会有记录
> 
> ```
>             $form->hasMany('item', function (Form\NestedForm $form) {
>                 $form->select('item_id')->options(function ($id) {
>                     $item = Item::find($id);
>                     if ($item) {
>                         return [$item->id => $item->name];
>                     }
>                 })->ajax('api/item');
>                 $form->decimal('price', '价格');
>             });
> ```

你可以试试下面的方法
```php
$form->hasMany()->customFormat(function () {
     // 返回你的数据库查询出来的数据
})
```

**Comment by jqhph** [comment]
> > 也许你可以参考以下这个项目，或许可以帮到你 https://github.com/jade-kun/sku
> 
> 好的，谢谢，其实可以直接使用hasMany方式，但是回显的时候不会有记录
> 
> ```
>             $form->hasMany('item', function (Form\NestedForm $form) {
>                 $form->select('item_id')->options(function ($id) {
>                     $item = Item::find($id);
>                     if ($item) {
>                         return [$item->id => $item->name];
>                     }
>                 })->ajax('api/item');
>                 $form->decimal('price', '价格');
>             });
> ```

回显不显示这个问题应该是你用法有点问题，关联模型需要显式地定义关联名称，具体可参考文档的使用。

**Comment by jqhph** [comment]
这个报错的问题我已经修复了，但`table`字段主要是用来保存`json`数据的，你这种情况需要使用`hasMany`替代。

**Comment by RayZoey** [comment]
> 这个报错的问题我已经修复了，但`table`字段主要是用来保存`json`数据的，你这种情况需要使用`hasMany`替代。

谢谢，我现在更换使用了hasMany
``` order下的form()
            $form->hasMany('item', function (Form\NestedForm $form) {
                $form->select('item_id')->options(function ($id) {
                    $item = Item::find($id);
                    if ($item) {
                        return [$item->id => $item->name];
                    }
                })->ajax('api/item');
                $form->decimal('price', '价格');
            });
```
``` order.model
    public function item(): BelongsToMany
    {
        $pivotTable = 'order_item'; // 中间表

        $relatedModel = Item::class; // 关联模型类名

        return $this->belongsToMany($relatedModel, $pivotTable, 'order_id', 'item_id');
    }
```
数据增加没有问题，但是确实编辑时无法回显，并且没有任何报错，我已经显式定义了关系字段
![image](https://user-images.githubusercontent.com/24807484/80914774-6b13a000-8d80-11ea-9783-95b8a81122e1.png)

![image](https://user-images.githubusercontent.com/24807484/80914778-7b2b7f80-8d80-11ea-9f00-ab5a89d6018e.png)

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/80915116-93040300-8d82-11ea-8928-d5298ae75341.png)
你这个是文档没看完全，表单基本使用的文档建议都过一遍
