### ISSUE TITLE
来回切换页面之后，js不加载

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#591]
A页面加载了js
Admin::js(static::$js);
切换到B页面再切换回来 这个里面的js就不加载了
页面是用过pjax加载的

**Comment by jqhph** [comment]
这个是正常的，初始化的代码不要放在 js 文件里面

**Comment by jqhph** [comment]
用php来举个例子，js文件类似写类的代码，但是实例化的类代码不应该放在类文件中
