### ISSUE TITLE
建議把語言文件的目錄明明為 zh_TW 類似的格式

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#595]
- Laravel Version: 8.10.0
- PHP Version: 7.4
- Dcat Admin Version: 1.7.4

### Description:
建議把語言文件的目錄命名為 zh_TW 類似

參照：
```https://github.com/Laravel-Lang/lang/tree/master/src```
官網的目錄用的是下劃線，為了兼容 Dcat 每次都還要單獨重命名一下資源文件

**Comment by faydanube** [comment]
另外，2.0 什麼時候可以用來開發商業項目哦？暫時還是用建議 1.x 版本？

**Comment by jqhph** [comment]
好的，2.0会调整语言包命名；

2.0的开发工作已经基本完成，改进了很多功能。本周末会发布`beta`版本，建议`watch`一下仓库；

商业项目不急着上线的话可以用2.0。

**Comment by faydanube** [comment]
Thank you for your reply and dedication
