### ISSUE TITLE
tree的儲存$form->isCreating()會判斷為true

### ISSUE THREAD

**Issue by lilashih** [jqhph/dcat-admin#60]
- Laravel Version: 7.8.1
- PHP Version: 7.2.6
- Dcat Admin Version: 1.2.0

### Description:
![image](https://user-images.githubusercontent.com/55920306/80613242-97bd7400-8a6f-11ea-8b5c-e5bbbb42b12e.png)

點擊tree的儲存時$form->isCreating()會判斷為true，可能是因為送出的是post

```php
$form->saved(function (Form $form) {
    dd('$form->isCreating() : '.$form->isCreating());
});
```
![image](https://user-images.githubusercontent.com/55920306/80613907-66917380-8a70-11ea-9f05-4fbe0d761894.png)

### Steps To Reproduce:

**Comment by jqhph** [comment]
感谢反馈

**Comment by jqhph** [comment]
刚才检查了下代码，模型树保存排序的功能是没有带行ID的，所以严格来说这个并不算问题。不知道你想要`saved`事件中用`isCreating`判断做什么？

**Comment by lilashih** [comment]
用來判斷要更新創建者還是編輯者
```php
$form->saved(function (Form $form, $result) {
    if ($form->isCreating()) {
        event(new CreatorUpdated($form->repository()->eloquent(), Admin::user()));
    } else {
        event(new UpdaterUpdated($form->repository()->eloquent(), Admin::user()));
    }
});
```

**Comment by jqhph** [comment]
> 用來判斷要更新創建者還是編輯者
> 
> ```
> $form->saved(function (Form $form, $result) {
>     if ($form->isCreating()) {
>         event(new CreatorUpdated($form->repository()->eloquent(), Admin::user()));
>     } else {
>         event(new UpdaterUpdated($form->repository()->eloquent(), Admin::user()));
>     }
> });
> ```

看你这个像是操作日志，也许可以这样使用

```php
$form->saved(function (Form $form, $result) {
     if (empty($form->getKey()) && $form->isCreating()) {
         // 保存排序操作
      
    } elseif ($form->isCreating()) {
        event(new CreatorUpdated($form->repository()->eloquent(), Admin::user()));
    } else {
        event(new UpdaterUpdated($form->repository()->eloquent(), Admin::user()));
    }
});
```

**Comment by lilashih** [comment]
好的 這樣應該OK 感謝~
