### ISSUE TITLE
scaffold生成代码问题

### ISSUE THREAD

**Issue by lwt33713803** [jqhph/dcat-admin#600]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.0-beta

### 生成代码控制器中的 use Dcat\Admin\Controllers\AdminController; 命名空间错误。

应该是 ：use Dcat\Admin\Http\Controllers\AdminController;

**Comment by jqhph** [comment]
感谢反馈，已修复，请升级到 v2.0.1-beta 版本
