### ISSUE TITLE
权限控制

### ISSUE THREAD

**Issue by tizips** [jqhph/dcat-admin#601]
- Laravel Version: 8.10.0
- PHP Version: 7.4.11
- Dcat Admin Version: 2.0.1-beta

### Description:
是否考虑在角色中加入父级角色，子角色只能添加自身所有的权限

**Comment by jqhph** [comment]
这种需求建议自己扩展比较好，可以通过覆写路由的方式对权限系统进行自定义；也可以通过配置文件禁用默认的权限系统，全部自己实现
