### ISSUE TITLE
表格查询过滤中，关联字段的多选框无法回显选中值

### ISSUE THREAD

**Issue by cyfflying** [jqhph/dcat-admin#603]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
如题

**Comment by jqhph** [comment]
贴下代码看看

**Comment by cyfflying** [comment]
单选可以正常回显
$filter->equal('category.catecode','分类')->select($cate);
这样就不行了
$filter->in('category.catecode','分类')->multipleSelect($cate);

**Comment by jqhph** [comment]
感谢反馈，确实有这个问题，请升级到`v1.7.6`版本

**Comment by cyfflying** [comment]
升级了，有没有个升级说明啊，好像 AdminController换位置了，还有其他一些报错

**Comment by jqhph** [comment]
> 升级了，有没有个升级说明啊，好像 AdminController换位置了，还有其他一些报错

抱歉，刚才选错分支发布了，需要卸载重新安装，并清理下composer缓存`composer clear-cache`
