### ISSUE TITLE
表单 ErrorException : Array to string conversion

### ISSUE THREAD

**Issue by tizips** [jqhph/dcat-admin#606]
- Laravel Version: 8.*
- PHP Version: 7.4.11
- Dcat Admin Version: v2.0.2-beta

### Description:
所有表单都「包含自带」已报错 Array to string conversion
<img width="916" alt="WX20201021-225636@2x" src="https://user-images.githubusercontent.com/19277632/96737849-b41fe500-13f0-11eb-848f-d9e66c35c60d.png">

**Comment by jqhph** [comment]
已修复，卸载重新安装就行，感谢反馈
