### ISSUE TITLE
Failed to load language: zh-CN from url tinymce/langs/zh-CN.js

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#611]
- Dcat Admin Version: 2.0.2

### Description:
使用 tinymce 时，加载的语言文件与 Laravel 默认配置格式不同，建议
「zh-CN.js」重命名为「zh_CN.js」，

同时希望增加繁体版本 zh_TW.js 本地化文件

**Comment by faydanube** [comment]
官方语言包下载地址：https://www.tiny.cloud/get-tiny/language-packages/

**Comment by jqhph** [comment]
好的

**Comment by jqhph** [comment]
先更新2.0分支代码，`composer require dcat/laravel-admin:"2.0.x-dev"`，如果不行的话就指定下`composer.json`里面的`dcat`版本，再升级

**Comment by lgh88** [comment]
->languageUrl(admin_asset('TinyMCE/langs/zh-CN.js'))
工作台没有js报错，zh-CN.js引入 成功  还是显示英文

**Comment by lgh88** [comment]
> ->languageUrl(url('TinyMCE/langs/zh-CN.js'))
> 工作台没有js报错，zh-CN.js引入 成功 还是显示英文

**Comment by lgh88** [comment]
->languageUrl(url('TinyMCE/langs/zh-CN.js'))
工作台没有js报错，zh-CN.js引入 成功 还是显示英文

**Comment by Mis-zhang** [comment]
@lgh88 
language_load: true,
language_url: '/tinymce/js/tinymce/langs/zh_CN.js',
language: 'zh_CN',
