### ISSUE TITLE
关系表在主表中字段翻译

### ISSUE THREAD

**Issue by dd521** [jqhph/dcat-admin#614]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
            // 主表
            $form->display('id');
            $form->text('name');
            $form->text('email');
            $form->text('email_verified_at');
            $form->text('password');
            $form->text('remember_token');
            // 显示一对一数据
            $form->text('profile.mobile', admin_trans_field('mobile'));
            $form->text('profile.avatar', admin_trans_field('avatar'));
            $form->text('profile.age', admin_trans_field('age'));
            $form->text('profile.gender', admin_trans_field('gender'));
            $form->text('profile.birthday', admin_trans_field('birthday'));
            $form->text('profile.address', admin_trans_field('address'));
            $form->text('profile.last_login_at', admin_trans_field('last_login_at'));
            $form->text('profile.last_login_ip', admin_trans_field('last_login_ip'));
            $form->text('profile.status', admin_trans_field('status'));
            // 时间
            $form->display('created_at');
            $form->display('updated_at');

### Steps To Reproduce:

return [
    'labels'  => [
        'Users' => '用户',
        'users' => '用户',
    ],
    'fields'  => [
        // 主表字段
        'name'              => '名称',
        'email'             => '邮箱',
        'email_verified_at' => '验证时间',
        'password'          => '密码',
        'remember_token'    => 'remember_token',
        // 附表字段
        'user_id'           => 'user_id',
        'mobile'            => '手机',
        'avatar'            => '头像',
        'age'               => '年龄',
        'gender'            => '性别',
        'birthday'          => '生日',
        'address'           => '地址',
        'last_login_at'     => '最后登录时间',
        'last_login_ip'     => '最后登录IP',
        'status'            => '状态（0：禁用；1：正常）',
    ],
    'options' => [
    ],
];

怎么使用副表翻译文件？

**Comment by jqhph** [comment]
```php
    'profile' => [
        'mobile' => '手机',
        ...
    ],
```
