### ISSUE TITLE
表单提交时其他表增加数据

### ISSUE THREAD

**Issue by phpyii** [jqhph/dcat-admin#615]
- Laravel Version: 7.28.4
- PHP Version:7.3.4
- Dcat Admin Version:1.7.6

### Description:
表单提交时可以给其他表增加数据吗？而且还得包含在事务里

我觉得可以增加个回调 回调的参数包含当前模型的数据  这个回调里可以增加自己的业务

**Comment by jqhph** [comment]
可以用`saved`事件，不过在事件回调中没法包含事务，如果需要事务的话需要重写数据仓库`store`和`update`方法，具体参考文档表单数据源

**Comment by phpyii** [comment]
好的
