### ISSUE TITLE
orderable()方法，当列表倒序排列时操作结果相反

### ISSUE THREAD

**Issue by wyq2214368** [jqhph/dcat-admin#62]
### 问题描述：
在使用SortableTrait时，如果列表倒序
```
$grid->model()->orderBy('order', 'desc');
$grid->order->orderable();
```
此时点击上移按钮，会执行`eloquent-sortable`的`moveOrderUp`方法，但此时由于列表本身倒序，所以在逻辑上本应该对应`moveOrderDown`方法。

### 可能的处理方法
可能需要对 `Displayers\Orderable` 的 `display` 方法中的html代码部分 ，根据当前model的排序，设置对应的`data-direction` 值

如：
```
<a href="javascript:void(0)" class=" font-14 {$this->grid->getRowName()}-orderable" data-id="{$this->getKey()}" data-direction="{$this->grid->model()->getQueries()
                ->where('method', '=', 'orderBy')
                ->where('arguments.0', 'order')
                ->where('arguments.1', 'desc')
                ->count()}">
</a>
```

或增加 `data-order` 等数据，传递到 `Dcat\Admin\Form` 的 `handleOrderable` 方法后再判断执行 `moveOrderUp` 还是 `moveOrderDown` 方法：

```php
    protected function handleOrderable(array $input = [])
    {
        if (array_key_exists('_orderable', $input)) {
            $updated = $input['_orderable'] == 1 && $input['_order'] == 'asc' // <-------------
                ? $this->repository->moveOrderUp()
                : $this->repository->moveOrderDown();

            return $updated
                ? $this->ajaxResponse(__('admin.update_succeeded'))
                : $this->error(__('admin.nothing_updated'));
        }
    }
```

### 结语

**当然，我没有实际尝试处理此问题，又或者只是我不会用而已。希望能先给个反馈，如果确实是问题，我会进一步看一下，也希望能尽快完善；如果是我文档没有阅读充分，还请指出，谢谢！**

**Comment by wyq2214368** [comment]
目前我仅通过重写SortableTrait的MoveOrderUp和MoveOrderDown，交换他们的名字，来处理该问题。但这样的前提是，所有使用排序的列表都统一倒序，并不是合适的解决方案。

**Comment by jqhph** [comment]
不能这样用呀，排序操作本身就是要求你的列表按规定的顺序排好序。

**Comment by wyq2214368** [comment]
> 不能这样用呀，排序操作本身就是要求你的列表按规定的顺序排好序。

是排好序的，只不过是倒序，一般场景下通常也都是倒序让新的在前边嘛，但目前倒序时，上下的按钮没有对应的调整排序加1还是减1。

比如，在正序时，点击向下按钮，是排序序号+1；在倒序时，点击向下按钮，应该是排序序号-1，但目前依旧是加1，刷新页面后，原本向下移动一行的那条数据，就会变成向上移动了一行。

**Comment by jqhph** [comment]
如果你需要这样的功能，可以自己扩展，现在这个排序功能是不会去做你这种需求的。既然你都要求一个列表按顺序排列，然后又要去按时间或其他字段排序，这种需求本身就不合理或者说不常用，我是没有精力去维护你这种特殊需求的。

**Comment by wyq2214368** [comment]
> 如果你需要这样的功能，可以自己扩展，现在这个排序功能是不会去做你这种需求的。既然你都要求一个列表按顺序排列，然后又要去按时间或其他字段排序，这种需求本身就不合理或者说不常用，我是没有精力去维护你这种特殊需求的。

您好，我没有说要按其他字段排序，说的就是 `eloquent-sortable` 约定的排序字段，目前只在正序时正常，在倒序时结果相反，这明显是不正常的或者说是不完整的，不是我的“特殊需求”，我只是指出该问题。

**Comment by jqhph** [comment]
`eloquent-sortable` 约定的排序就是按它既定的排序展示，并不考虑用它倒序的特殊情况。你要按这个倒序本身就是不在考虑范围的，明白吗？就算是laravel-admin也是没有这样的功能的，这种功能我开发出来意义不大。

**Comment by jqhph** [comment]
一个好的项目，并不是功能越多越好，增加那么多不常用的功能只会让用户觉得臃肿，提高学习成本。更好的设计就是要化繁为简，这个项目本身只需要提供一些常用的功能就行，然后提供一个简单可扩展的接口，让用户能在这个框架基础上扩展自定义这些内容。

很明显你这个需求就是不常用的，完全可以自己扩展实现。
