### ISSUE TITLE
标星和取消标星的列操作报错

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#621]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

Method Dcat\Admin\Repositories\EloquentRepository::eloquent does not exist. 

    public function modelClass()
    {
        return get_class($this->parent->model()->eloquent()->repository()->eloquent());
    }

**Comment by jqhph** [comment]
这个功能是你自己加的吗？

**Comment by zhaoshl** [comment]
这个是文档中的功能


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 下午2:33
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 标星和取消标星的列操作报错 (#621)





 
这个功能是你自己加的吗？

**Comment by jqhph** [comment]
1.x中用

```php
    public function modelClass()
    {
        return get_class($this->parent->model()->repository()->eloquent());
    }
```

2.x中用

```php
    public function modelClass()
    {
        return get_class($this->parent->model()->repository()->model());
    }
```

**Comment by zhaoshl** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 下午3:21
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "赵胜利"<77182507@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 标星和取消标星的列操作报错 (#621)





 
1.x中用
     public function modelClass()     {         return get_class($this-&gt;parent-&gt;model()-&gt;repository()-&gt;eloquent());     }
 
2.x中用
     public function modelClass()     {         return get_class($this-&gt;parent-&gt;model()-&gt;repository()-&gt;model());     }

**Comment by zhaoshl** [comment]
试了一下，2.X版本还是有错误提示！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月30日(星期五) 下午3:21
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 标星和取消标星的列操作报错 (#621)





 
1.x中用
     public function modelClass()     {         return get_class($this-&gt;parent-&gt;model()-&gt;repository()-&gt;eloquent());     }
 
2.x中用
     public function modelClass()     {         return get_class($this-&gt;parent-&gt;model()-&gt;repository()-&gt;model());     }

**Comment by jqhph** [comment]
你没有用模型？

**Comment by zhaoshl** [comment]
> 你没有用模型？

![image](https://user-images.githubusercontent.com/31877333/97675320-1308ec80-1aca-11eb-9014-e3952c3e2bbc.png)
没有使用数据仓库，直接用的数据模型，1.X版本是正常的
