### ISSUE TITLE
树状表格bug

### ISSUE THREAD

**Issue by ajiader** [jqhph/dcat-admin#622]
- Laravel Version: 6.#.#
- PHP Version: 7.2.#
- Dcat Admin Version: 1.7.#

### Description:
// 禁用分页功能，一次性加载所有下一层级节点
$grid->title->tree(true);

按照文档说的设置true 没有效果

**Comment by jqhph** [comment]
这个指的是点击后展开所有下一级节点，如果不开启这个功能的话点击展开下级节点会分页

**Comment by ajiader** [comment]
谢谢大佬回复，我理解错了，以为是模型树那种设置true就是打开页面 所有都出来了   

数据不多的情况下，我想通过配置一次性像模型树那样展开所有，不知道树状表格能否配置
