### ISSUE TITLE
表单html标签引入自定义模板中带有js代码, js无法正常执行，导致页面错误

### ISSUE THREAD

**Issue by jiangfeiyu** [jqhph/dcat-admin#624]
- Laravel Version: 7.0.x
- PHP Version: 7.3.x
- Dcat Admin Version: 2.0.5

### Description:
1.引入admin.customize.content模板
     
     $form->html(view('admin.customize.content', ['data' => $form->isEditing() ? $form->model()->toArray() : []]))->plain();

2.admin.customize.content 中有含有自定义<script> 

3.页面出错 ，1.7.x 版本是正常的
![微信截图_20201027162730](https://user-images.githubusercontent.com/5492375/97275892-7b10c600-1871-11eb-90cc-df952118781f.png)

**Comment by jqhph** [comment]
贴下错误报文以及view的代码

**Comment by jiangfeiyu** [comment]
> 贴下错误报文以及view的代码

@if (count($data))
    <?php
    $language_content = array_combine($data['language'], $data['content']);
    $language_config = config('language.key');
    $language_data = $data['language'];
    ?>
    <div class="form-group mail_content">
        @foreach ($data['language'] as $language)

            <div class="form-group row form-field language{{$language}}">
                <label for="content" class="col-sm-2 asterisk control-label">{{$language_config[$language]}}内容</label>
                <div class="col-sm-8">
                    <div class="help-block with-errors"></div>
                    <textarea name="language-content[]" class="form-control content content-language{{$language}}"
                              rows="5" id="language{{$language}}" placeholder="输入 内容" required="1">{{$language_content[$language]}}
                    </textarea>
                    <span class="help-block">
                        <i class="fa feather icon-help-circle"></i>&nbsp;  用 #### 代替内容中的分钟变量
                    </span>
                </div>
            </div>
        @endforeach
    </div>

@else
    <?php $language_data = ["0"];?>

    <div class="mail_content">
        <div class="form-group row form-field language0">
            <label for="form-field-content" class="col-md-2 asterisk text-capitalize control-label">英语内容</label>
            <div class="col-md-8 language0">
                <div class="help-block with-errors"></div>
                <textarea name="language-content[0]" class="form-control content content-language0" rows="5"
                          id="language0" placeholder="输入 内容" required="1"></textarea>
                <span class="help-block">
                    <i class="fa feather icon-help-circle"></i>&nbsp;  用 #### 代替内容中的分钟变量
                </span>
            </div>
        </div>
    </div>
@endif




<script>
    Dcat.ready(function () {

        let language_map = {!! json_encode(config('language.key'))  !!};
        let language_data = {!! json_encode($language_data)!!};

        $(document).ready(function () {
            let index = 0;
            $('input[name="template_id"]').change(function () {
                $.ajax({
                    url: '/template/rollnotice',
                    type: 'get',
                    data: {id: $('input[name="template_id"]').val()},
                    dataType: 'json',
                    success: function (data) {
                        $.each($('.field_language'), function (checkbox, i) {
                            let index = $(this).val();
                            if ($.inArray(parseInt(index), data.language) >= 0) {
                                if ($(this).is(':checked')) {
                                    $(this).prop('checked', 'checked')
                                } else {
                                    $(this).prop('checked', 'checked').trigger('change');
                                }
                                $('.content-language' + index).html(data.content[index]);
                            } else {
                                $(this).prop('checked', '').trigger('change');
                            }
                        })

                    }
                })
            });
            $('.field_language').on('change', function (event) {
                if ($(this).is(':checked')) {
                    let language = language_map;
                    let className = 'language' + $(this).val()
                    let classNameContent = 'content-language' + $(this).val()
                    let content = '<div class="form-group row form-field ' + className + '"> <label for="content" class="col-sm-2 asterisk control-label">' + language[$(this).val()] + '内容</label> <div class="col-sm-8">   <div class="help-block with-errors"></div><textarea name="language-content[' + $(this).val() + ']" class="form-control content ' + classNameContent + '" rows="5" id="' + className + '"placeholder="输入 内容"required="1"></textarea> </div> </div>';
                    $('.mail_content').append(content);
                } else {
                    let className = 'language' + $(this).val()
                    $('.' + className).remove();
                }
            })
        })

    });
</script>

**Comment by jqhph** [comment]
试了下，功能正常，请仔细检查你的`html`是否多一个或者少一个`div`标签

**Comment by jiangfeiyu** [comment]
> 试了下，功能正常，请仔细检查你的`html`是否多一个或者少一个`div`标签

刚检查了一下 html部分div都是对称的  ，发现js代码里面动态添加的content只要有div标签对 就会把srcipt 原样显示出来 ，
我下午是新建分支升级到2.0.5 ，这部分原来的代码在1.7.3是正常的。

**Comment by jqhph** [comment]
append的HTML代码标签是否对称？先append简单的逐步调试看看

**Comment by jiangfeiyu** [comment]
> append的HTML代码标签是否对称？先append简单的逐步调试看看

嗯 append的内容 我直接改一对空 div 标签 ，马上就是把js原样输出了

**Comment by jiangfeiyu** [comment]
> append的HTML代码标签是否对称？先append简单的逐步调试看看

![Uploading 微信截图_20201027181225.png…]()

**Comment by jqhph** [comment]
确实有问题，等我晚上修复一下

**Comment by jqhph** [comment]
请升级到 2.0.4-beta 版本
