### ISSUE TITLE
[pull request] config.admin.logo 样式微调建议

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#626]
修改前
![image](https://user-images.githubusercontent.com/8817046/97331707-a1a42080-18b4-11eb-94d7-82d3a5542eca.png)
修改后
![image](https://user-images.githubusercontent.com/8817046/97331773-b7b1e100-18b4-11eb-9db7-8cc95019c01d.png)

个人强迫症，总觉得这个没对齐很难受，如果作者也觉得修改后左边对齐更好看的话，可以在下个版本修改图标样式，让 「logo」和导航列表左侧对齐……
文件位于 「vendor\dcat\laravel-admin\resources\views\partials\sidebar.blade.php」
作者大大辛苦。

**Comment by jqhph** [comment]
感觉这个可以自己微调一下，写点css代码就好了

**Comment by faydanube** [comment]
已经自己已调整过了，就是觉得这种上下对齐太难看了，哈哈，没事。close 了
