### ISSUE TITLE
Modal工具类弹窗如何设置按钮样式

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#628]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.4

### Description:
class OfferCommodityImportAction extends AbstractTool{
...
    public function render(){
        $form = OfferCommodityImportForm::make()->payload(['id' => $this->offer_id]);
        return Modal::make()
            ->lg()
            ->title($this->title)
            ->body($form)
            ->button($this->title)**->addHtmlClass($this->style)**;
    }
...
}
![image](https://user-images.githubusercontent.com/31877333/97396132-6b50ba80-1921-11eb-8053-9baff716bc12.png)

**Comment by jqhph** [comment]
`button`方法可以直接传HTML字符

**Comment by zhaoshl** [comment]
button("<div class='" . $this->style . "'>" . $this->title . "</div>")
谢谢！
