### ISSUE TITLE
权限中间件多次调用问题？

### ISSUE THREAD

**Issue by mmlsx** [jqhph/dcat-admin#629]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
中间件做权限过滤的时候，$next ($request) 被调用了两次，导致每个页面调用了两次请求

**Comment by jqhph** [comment]
权限中间件并不会执行两次 `$next ($request)`，如果说页面调用两次请求那可能是操作问题或页面按钮发起请求的`JS`代码有问题

**Comment by mmlsx** [comment]
检查了，没有发现页面操作按钮和JS调用，就正常的使用框架生成的数据表格grid()方法，在页面显示的时候打印日志信息，一次页面请求会打印两次日志，如下图：
![222](https://user-images.githubusercontent.com/22363516/97406558-5e899200-1934-11eb-9de5-b59ca09eaad3.png)
![333](https://user-images.githubusercontent.com/22363516/97406575-63e6dc80-1934-11eb-806f-ef7fa7ac4447.png)

**Comment by mmlsx** [comment]
![222](https://user-images.githubusercontent.com/22363516/97406631-7a8d3380-1934-11eb-92ab-895c51b9fcf7.png)
![333](https://user-images.githubusercontent.com/22363516/97406660-88db4f80-1934-11eb-9df3-963099ff3e73.png)

**Comment by jqhph** [comment]
你的代码有问题，根据你这个截图，两条日志相隔1秒钟，明显不是同一个请求生成的

**Comment by mmlsx** [comment]
@jqhph 这个问题能解决吗？如果不能解决，就会出现调用的时候重复调用的问题，导致页面每次显示的时候，请求两次数据接口，导致不必要的网络资源浪费，目前发现列表显示和编辑数据的时候都会出现这种情况。

**Comment by jqhph** [comment]
正常情况下不会出现这种问题，不知道你做了什么操作，没办法判断

**Comment by jqhph** [comment]
你可以对比演示站点

**Comment by mmlsx** [comment]
是同一个请求，但是不知道为什么，同一个页面刷新请求会有两次，一次没有版本号，一次带有版本号，如图：
![555](https://user-images.githubusercontent.com/22363516/97411399-2f2a5380-193b-11eb-8c2b-6ce0dc162869.png)
这个是同一次页面请求。

**Comment by mmlsx** [comment]
演示站点的版本比较低，我看了没有这种情况

**Comment by jqhph** [comment]
那是你代码的问题，有版本号的是静态资源请求

**Comment by mmlsx** [comment]
找到问题了，在去掉css引入google字体的时候，设置为空字符串的时候，然后页面引入了一个带版本号的空<link href="?v1.7.6">导致的

**Comment by jqhph** [comment]
2.x中已经把谷歌字体下载到本地了
