### ISSUE TITLE
表單有多個editor時只會顯示最後一個

### ISSUE THREAD

**Issue by lilashih** [jqhph/dcat-admin#63]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
因為editor的渲染會先remove掉，所以如果一個表單有多個editor的話就只會顯示最後一個editor

Dcat\Admin\Form\Field\Editor
```php
public function render()
{
    $this->script = <<<JS
    tinymce.remove(); // here
    tinymce.init({$this->formatOptions()})
JS;

    return parent::render();
}
```

**Comment by jqhph** [comment]
感谢反馈

**Comment by jqhph** [comment]
已修复，可先更新master分支代码
