### ISSUE TITLE
请问有关闭列表中 工具栏处 【新增】按钮的方法吗？

### ISSUE THREAD

**Issue by Instrye** [jqhph/dcat-admin#630]
- Laravel Version: 8.*
- PHP Version: &.4
- Dcat Admin Version:v1.7.4 

请问有关闭列表中 工具栏处 【新增】按钮的方法吗？

**Comment by jqhph** [comment]
$grid->disableCreateButton(); 具体参考文档表格基本使用

**Comment by Instrye** [comment]
感谢，因为文档里确实没有这个方法（亦或者没有搜出来），我通过 `createMode('disable')` 临时改的
