### ISSUE TITLE
文件上传成功，但是服务器的文件夹下看不到文件，麻烦帮看一下是什么原因

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#632]
filesystems的配置：
'admin' => [
            'driver'     => 'local',
            'root'       => public_path('uploads'),
            'visibility' => 'public',
            'url'        => env('APP_URL').'/uploads',
        ],

admin配置
'upload' => [

        'disk' => 'admin',
        
        'directory' => [
            'image' => 'images',
            'file'  => 'files',
        ],
    ],

class ImportForm extends Form
{
    public function handle(array $input)
    {
        Log::error('我已经在处理了');
        // 下面的代码获取到上传的文件，然后使用`maatwebsite/excel`等包来处理上传你的文件，保存到数据库
        $file = $input['file'];
       
        // 读取导入文件
        $array = Excel::toArray(new CashierJournalImport(), $file, 'local');

        // 你的导入逻辑
//        var_dump($array);die;
        return $this->success('导入完成！');
    }

    public function form()
    {
        $this->file('file', '请选择文件')
             ->disk('admin')
             ->autoUpload()
             ->accept('xlsx,xls,csv');
    }
}

public function upload(Content $content)
    {
        return $content->full()
            ->row(function (Row $row) {
                $form = new ImportForm();
                $form->form();
                $form->disableHeader();
                $form->disableListButton();
                $row->column(12, $form);
            });
    }

**Comment by jqhph** [comment]
`public` 目录是否有写权限？没遇到过你这种情况，另外工具表单是没有 `disableListButton` 这两个方法的

**Comment by xxkrcn** [comment]
谢谢，问题解决了，建工具表单时，我把Form包引用错了
