### ISSUE TITLE
图片限制尺寸后，上传不符合规定的图片后续一系列错误问题。

### ISSUE THREAD

**Issue by madincwz** [jqhph/dcat-admin#633]
- Laravel Version: 7.21.0
- PHP Version: 7.2.33
- Dcat Admin Version: 1.7.4

### Description:
预期：图片做了限制以后，上传不符合尺寸图片时，提示尺寸错误，不进行数据库修改。

实际：
对图片做了限制，当上传不符合尺寸的图片时，会同时弹出3个提示：
the 封面图 filed is required，
已成功上传1个文件，
the image dimensions is invalid

此时，本条数据已经修改了。把之前有值的图片字段置空了。

代码如下：
`protected function form()
    {
        return Form::make(new Album(), function (Form $form) {
            $form->display('id');
  
            if ($form->isEditing()) {
                $form->display('aid');
                $form->image('pic')->uniqueName()->autoUpload()
                    ->accept('jpg,jpeg')->maxSize(300)->dimensions(['min_width' => 800, 'min_height' => 800,'ratio'=>1])->required()
                    ->disk('qiniuimg');
            }
        });`

**Comment by jqhph** [comment]
先升级到`2.x`版本吧，2.x版本是正常的，升级可以参考文档[1.x升级指南](http://www.dcatadmin.com/docs/2.x/1-x-upgrade.html)
