### ISSUE TITLE
切换语言为简体中文报错，而且不生效

### ISSUE THREAD

**Issue by zhengwenle** [jqhph/dcat-admin#635]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version:  v2.0.5-beta

### Description:
修改app.php文件locale='zh-CN'，后台界面显示依然是英文，访问后台报错，错误信息如下
ErrorException
Illegal string offset 'error_loading' (View: /project/project/laravel8/vendor/dcat/laravel-admin/resources/views/scripts/select.blade.php)

**Comment by jqhph** [comment]
`2.x` 语言包目录命名已改成 `zh_CN`

**Comment by zhengwenle** [comment]
好的，可以了，但是文档上还是zh-CN，希望能及时修改。
