### ISSUE TITLE
can() & cannot() functions conflict with laravel Authorizable trait

### ISSUE THREAD

**Issue by damieneskimo** [jqhph/dcat-admin#636]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: 2.*

### Description:
你好 我安装了laravel 和laravel jetstream，因为将来需要为普通user和商业用户提供注册和登录后的dashboard，所以想着利用jetstream提供的auth和dashboard. 
在admin这块，我用了users table,然后用的是`App\Models\User`, 但在使用`Dcat\Admin\Traits\HasPermissions trait`时 发现里面的`can` & `cannot` methods和laravel Authorizatable trait里的两个同名方法冲突了。不知道大神有没有什么好的建议解决这个问题？谢谢

**Comment by jqhph** [comment]
不在同一个类里面use这两个trait就可以

**Comment by damieneskimo** [comment]
不好意思  我还是没有想太明白  你是建议admin后台和前台dashboard用两个不同的类 `Dcat\Admin\Models`和 `App\Models\User` 但使用同一个users table?

**Comment by damieneskimo** [comment]
因为之前用过laravel的gate和authorisation来保护routes  觉得还是挺好用的  应该蛮多人也在使用  但同时如果用dcat-admin的话还是希望能用到`hasPermissions`这些方便的trait  不知道大神会考虑改方法名  比如像`spatie/laravel-permission`使用`hasPermissionTo`  这样可以和laravel自身的authorisation更兼容？

**Comment by jqhph** [comment]
具体没试过你这种情况，不过有一个方法是肯定能行的，你再创建一个Model专门给后台用，然后继承dcatadmin默认的管理员模型

**Comment by damieneskimo** [comment]
好的 我暂时自己创建了一个`HasPermissions` trait，复制并修改了那两个冲突的方法名，然后引入在`App\Models\User`里，貌似是可以跑起来了，如果有什么问题再请教。多谢
