### ISSUE TITLE
Raido/Checkbox 增加竖排显示

### ISSUE THREAD

**Issue by soarcn** [jqhph/dcat-admin#638]
- Laravel Version: *
- PHP Version: *
- Dcat Admin Version: *

### Description:

Raido/Checkbox 增加竖排显示功能, 可以和admin兼容用 stacked方法

https://github.com/z-song/laravel-admin/commit/00a80ef2202852b5b288ca0bc2094aed8a2074fb

**Comment by jqhph** [comment]
已增加这个功能，等这两天新版本发布即可
