### ISSUE TITLE
下拉选框联动子选项获取不到CODE

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#640]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.5

### Description:
![image](https://user-images.githubusercontent.com/31877333/97671582-79d6d780-1ac3-11eb-911d-ce6cfce60b60.png)
![image](https://user-images.githubusercontent.com/31877333/97671628-92df8880-1ac3-11eb-8ea7-b48b68db77ca.png)

**Comment by jqhph** [comment]
对照文档中的用法，返回格式不对

**Comment by zhaoshl** [comment]
谢谢，我再看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年10月30日(星期五) 下午3:24
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "赵胜利"<77182507@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 下拉选框联动子选项获取不到CODE (#640)





 
对照文档中的用法，返回格式不对

**Comment by zhaoshl** [comment]
> 对照文档中的用法，返回格式不对

![image](https://user-images.githubusercontent.com/31877333/97678050-29b14280-1ace-11eb-9d3c-a6ce03c559ab.png)
![image](https://user-images.githubusercontent.com/31877333/97678091-3f266c80-1ace-11eb-8a37-1352f3011bf5.png)
测试了一下，看来是只能回传id，不能回传code，希望以后能兼容，否则拿到回传id还要查询一次数据库获取CODE

**Comment by jqhph** [comment]
可以的，任意字段都行

**Comment by zhaoshl** [comment]
> 可以的，任意字段都行

->get(['id', DB::raw('name as text')]) 没有问题
->get(['code', DB::raw('name as text')]) 获取不到，<option data-select2-id="..">...</option>
->get([DB::raw('code as id'), DB::raw('name as text')]) 获取到的值一直是0，<option value='0' data-select2-id="..">...</option>

不知道错在哪里了
