### ISSUE TITLE
表单的关联关系支持很复杂的关联嘛

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#642]
这几个表：users、departments、roles
其中users跟departments是多对多关系，也就是有个中间表 department_user
现在需求要 user 在每个 department 中有不同的 role，也就是 用department_user 跟roles 再建立关系，department_user_role 表，这种关系可以实现嘛

**Comment by jqhph** [comment]
没看太明白，如果表单页面的功能能满足就能支持，读写数据可以通过重写数据仓库实现
