### ISSUE TITLE
role_users pivot table timestamps fields not filled when assigning roles

### ISSUE THREAD

**Issue by damieneskimo** [jqhph/dcat-admin#643]
- Laravel Version: 8.12
- PHP Version: 7.4
- Dcat Admin Version: 2.*

### Description:
你好 我发现`role_users` table里的`created_at` & `updated_at`在用户被赋予Role时并没有自动填充，而是null

**Comment by damieneskimo** [comment]
应该在`EloquentRepository`的`updateRelation`方法里加一个`withTimestamps()`:
```
case $relation instanceof Relations\BelongsToMany:
        if (Schema::hasColumns($relation->getTable(), ['created_at', 'updated_at'])) {
             $relation->withTimestamps();
        }
```

我可以提个PR 如果这个问题还没有被解决的话。

**Comment by jqhph** [comment]
你好，我想了一下，感觉这个其实没有太大必要，如果有这种需求的话，可以通过自定义数据仓库的方式写入这两个字段。
