### ISSUE TITLE
action下载路径的一个问题

### ISSUE THREAD

**Issue by xxkrcn** [jqhph/dcat-admin#647]
$this->response()->download('http://127.0.0.1:8000/downloads/a.xls');可以下载public/downloads目录下的文件a，
$this->response()->download('/downloads/a.xls');下载失败，原因是地址中多了一个admin, 即http://127.0.0.1:8000/admin/downloads/a.xls，怎么把admin去掉？

**Comment by jqhph** [comment]
需要传入完整url，如

```php
$this->response()->download(url('/downloads/a.xls'));
```
