### ISSUE TITLE
选项卡表单 (tab)中可以使用多行布局 (row)吗？

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#648]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.5

### Description:
选项卡表单 (tab)中可以使用多行布局 (row)吗？目前测试看还不支持，希望以后能支持

**Comment by jqhph** [comment]
你确定你测试了？2.x中的tab是支持row以及column布局的

**Comment by zhaoshl** [comment]
![image](https://user-images.githubusercontent.com/31877333/97822249-32815e80-1cf0-11eb-9962-46fa9879e848.png)
![image](https://user-images.githubusercontent.com/31877333/97822263-3dd48a00-1cf0-11eb-87b6-40c3231ec803.png)
不好意思，我测试代码不清楚是错在哪里了，求赐教

**Comment by jqhph** [comment]
你截图的这段代码是没问题的，自己看trace报文排查吧

**Comment by zhaoshl** [comment]
谢谢！我再排查一下吧。
$form-&gt;row(function (Form\Row $form) {}
只要加上这个多行就报错！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月2日(星期一) 上午10:07
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 选项卡表单 (tab)中可以使用多行布局 (row)吗？ (#648)





 
你截图的这段代码是没问题的，自己看trace报文排查吧

**Comment by FrankHay0305** [comment]
我也出现这个问题了，不知道问题解决了没有？如果解决了可以贴一下代码

**Comment by zhaoshl** [comment]
> 你截图的这段代码是没问题的，自己看trace报文排查吧

经过多次测试，单独使用表单选项卡（Tab）布局或单独使用行（Row）布局没有问题，如果在表单选项卡（Tab）布局中再使用行（Row）布局，新建表单会报错，编辑表单时没有问题，可能是BUG，请求大神解决！

**Comment by jqhph** [comment]
> > 你截图的这段代码是没问题的，自己看trace报文排查吧
> 
> 经过多次测试，单独使用表单选项卡（Tab）布局或单独使用行（Row）布局没有问题，如果在表单选项卡（Tab）布局中再使用行（Row）布局，新建表单会报错，编辑表单时没有问题，可能是BUG，请求大神解决！

好的

**Comment by jqhph** [comment]
@zhaoshl @FrankHay0305 已修复，请升级到`v2.0.9-beta`版本，具体升级方法请参考文档[更新日志](http://www.dcatadmin.com/docs/2.x/beta-change-log.html)
