### ISSUE TITLE
左上角汉堡包按钮在某些尺寸下会被遮住

### ISSUE THREAD

**Issue by cyfflying** [jqhph/dcat-admin#649]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
比如1024*768宽度，左上角折叠菜单的按钮会被遮挡

**Comment by jqhph** [comment]
没看明白，能否上个截图

**Comment by cyfflying** [comment]
就是红框里这个按钮，时有时无
![1](https://user-images.githubusercontent.com/34729167/97834939-f95ae580-1d13-11eb-8dde-abd2be8f1820.png)
![2](https://user-images.githubusercontent.com/34729167/97834947-fcee6c80-1d13-11eb-8148-85f76a6aae92.png)
![3](https://user-images.githubusercontent.com/34729167/97834953-ff50c680-1d13-11eb-82b9-f78854c9d74a.png)
