### ISSUE TITLE
关联查询，重置查询条件，存在bug。

### ISSUE THREAD

**Issue by zhengwenle** [jqhph/dcat-admin#650]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version:  v2.0.5-beta

### Description:
关联查询，重置查询条件，输入的关键字依然存在，

**Comment by jqhph** [comment]
你是怎么重置的

**Comment by jqhph** [comment]
上代码

**Comment by zhengwenle** [comment]
$grid->filter(function (Grid\Filter $filter) {
                $filter->equal('id');
                $filter->like('provinces.name', '省份');
                $filter->like('cities.name', '城市');
                $filter->like('areas.name', '区县');
            });

**Comment by jqhph** [comment]
已修复，可以先更新2.0分支代码
```bash
composer require dcat/laravel-admin:"2.0.x-dev"
```

**Comment by LEUNGHOTIN** [comment]
> 已修复，可以先更新2.0分支代码
> 
> ```shell
> composer require dcat/laravel-admin:"2.0.x-dev"
> ```

我的版本是2.0.14-beta，这个问题还是会存在.

```
$grid->filter(function (Grid\Filter $filter) {
                $filter->in('product_id','产品')->multipleSelect($this->ProductFilter());
                $filter->in('btandtest.brand_id','品牌')->multipleSelect($this->BrandFilter());
            });
```
