### ISSUE TITLE
安装在二级子目录下无法登录

### ISSUE THREAD

**Issue by dedemao** [jqhph/dcat-admin#651]
- Laravel Version: 8.12.3
- PHP Version: 7.3.10
- Dcat Admin Version: 2.0.5-beta

### Description:
我是安装在web根目录下的二级目录中的，后台网址是这样的：http://127.0.0.1/test/dcatadmin/public/admin/auth/login
在输入账号密码后，显示登录成功，但仍然停留在登录页面。

**Comment by jqhph** [comment]
不支持
