### ISSUE TITLE
卡片419

### ISSUE THREAD

**Issue by MrKaGod** [jqhph/dcat-admin#652]
- Laravel Version: 5.8
- PHP Version: 7.1.3
- Dcat Admin Version: 1.7.7

我在后台首页写了一个卡片的功能，之前是好好的，但是现在只要打开后台首页，就会提示419
![image](https://user-images.githubusercontent.com/20720787/97847785-1a7b0080-1d2b-11eb-8f0a-9ea5d56ffc81.png)
貌似csrf_token丢失了。
这个东西应该在哪里加上？不想全局取消token校验

**Comment by MrKaGod** [comment]
在grid中直接编辑，也会提示419

@jqhph 大大求救

**Comment by jqhph** [comment]
试下 php artisan admin:publish --assets --force

**Comment by MrKaGod** [comment]
ok，解决。谢谢大大
