### ISSUE TITLE
表格标题字段文字如何居中？

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#653]
- Dcat Admin Version: 2.0.5-beta

请问这个标题如何居中？
![Q9_$)VZ%(1DTDTF_XML7)RS](https://user-images.githubusercontent.com/16422689/97871128-f9c4a200-1d4e-11eb-816d-370246497aaf.png)

**Comment by jqhph** [comment]
```php
$grid->addTableClass('table-middle');
```

**Comment by ygcool** [comment]
好像还是不行

![1604324335(1)](https://user-images.githubusercontent.com/16422689/97874540-1911fe00-1d54-11eb-9ab2-3a86aa34fb19.jpg)
![1604324348(1)](https://user-images.githubusercontent.com/16422689/97874547-1adbc180-1d54-11eb-9718-ce84fe721fd6.jpg)

**Comment by jqhph** [comment]
很简单的，不行的话自己写点css
```css
td {
    vertical-align: middle;
  }
```

**Comment by ygcool** [comment]
好的谢谢
