### ISSUE TITLE
表单$show view 两次显示

### ISSUE THREAD

**Issue by linechengchen** [jqhph/dcat-admin#659]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: 2.0

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/25653824/97982133-47ecaa80-1e0e-11eb-8b1d-0fb0e0de6cc1.png)
![image](https://user-images.githubusercontent.com/25653824/97982173-563ac680-1e0e-11eb-90ac-884a65606059.png)

**Comment by jqhph** [comment]
没重现出来，截完整代码看看
