### ISSUE TITLE
tree表格支持导出所有数据吗

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#660]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.7

### Description:
树状表格（带有层级）如何导出所有数据（包含子级）吗？

**Comment by jqhph** [comment]
暂不支持，2.0版本中会优化

**Comment by joey2017** [comment]
> 暂不支持，2.0版本中会优化

顺便提一下，分站权限管理也能优化吗

**Comment by jqhph** [comment]
多应用？

**Comment by joey2017** [comment]
> 多应用？

不是多应用，就是后台城市分站管理。比如一个账号只能管理北京站的数据，另一个只管理上海站，超级管理员管理所有数据

**Comment by jqhph** [comment]
这个功能本身就支持，用下面的代码自己判断

```php
Admin::user()->can(xxx)
```

**Comment by joey2017** [comment]
我明白你说的意思，我只是在想可不可以统一处理数据显示，不用每个控制器都写一样的权限判断和数据过滤查询

**Comment by uuhai** [comment]
树状表格（带有层级）导出所有数据（包含子级），2.0版本没找到说明文档，可以描述一下用法吗？谢谢
