### ISSUE TITLE
升级2.0后，无法打开操作日志路由

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#661]
- Dcat Admin Version: v2.0.5-beta

### Description:
从1.x升级到2.x后，admin/auth/logs这个默认自带路由打开报404，其他都是正常的，请问是我升级错了还是其他什么原因导致? 
感谢作者回复

**Comment by jqhph** [comment]
操作日志移出来做成插件了 https://github.com/dcat-admin/operation-log

**Comment by ygcool** [comment]
原来如此，还以为是升级步骤错了。 非常感谢

**Comment by ygcool** [comment]
不好意思再问下，安装扩展包后，启用了，访问：admin/auth/operation-logs  报如下错误
![image](https://user-images.githubusercontent.com/16422689/98081624-6ad09a80-1eb2-11eb-80d4-e79a170bb5f4.png)

**Comment by jqhph** [comment]
这个需要更新2.0分支最新的代码才可以正常跑，这周会发布新版本

**Comment by ygcool** [comment]
了解
