### ISSUE TITLE
关于Dcat v2.x版本文件分块上传的变化

### ISSUE THREAD

**Issue by yurenzhen** [jqhph/dcat-admin#662]
- Laravel Version: 8.10.0
- PHP Version: 7.3.18
- Dcat Admin Version: v2.0.5-beta

### Description:
Dcat 1.x 的版本, 上传较大的文件, 可以发送多个请求分块上传
我使用的 Dcat v2.0.5-beta 的版本, 上传较大的文件, 发现只发送一个请求, 反而不能分块上传了

**Comment by jqhph** [comment]
`2.x` 默认禁用了分块上传
```php
$form->image(xxx)->options(['chunked' => true]);
```

**Comment by yurenzhen** [comment]
哈哈, 确实像您说的那样, 看来得麻烦更新一下Dcat 2.*关于分块上传这块的文档了, 或许还要更新一下[v1.x版本升级指南].

**Comment by jqhph** [comment]
是的，你不说我都忘了改了这个
