### ISSUE TITLE
2.0.* 分步表单错误

### ISSUE THREAD

**Issue by Aexus** [jqhph/dcat-admin#664]
- Laravel Version: 8.6.0
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.5-beta

### Description:
![image](https://user-images.githubusercontent.com/3403478/98220826-db96b600-1f89-11eb-8cc5-a27ccee28082.png)

### Steps To Reproduce:
按照demo做的分步表单，载入却报错

**Comment by jqhph** [comment]
2.0分步表单已经拆出做成扩展了 https://github.com/dcat-admin/form-step

**Comment by Aexus** [comment]
样式有问题，并且没有 下一步 按钮
![image](https://user-images.githubusercontent.com/3403478/98221989-3f6dae80-1f8b-11eb-9266-9fa605611e49.png)


> 2.0分步表单已经拆出做成扩展了 https://github.com/dcat-admin/form-step

**Comment by jqhph** [comment]
你安装步骤有问题
