### ISSUE TITLE
代码生成器重新创建某个控制器报错

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#665]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.5

### Description:
![image](https://user-images.githubusercontent.com/31877333/98318614-f0bb2580-2019-11eb-92fa-7c4621212d82.png)

我把某个控制器删除，然后重新用代码生成器创建这个控制器，为什么会报错呢？

另外想问一下可以用命令行来创建吗？

**Comment by jqhph** [comment]
你之前是不是生成过composer 类映射文件，重新生成一下自动加载规则就行了
```php
composer dump
```

**Comment by zhaoshl** [comment]
谢谢！确实是这个原因！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月6日(星期五) 上午10:25
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 代码生成器重新创建某个控制器报错 (#665)





 
你之前是不是生成过composer 类映射文件，重新生成一下自动加载规则就行了
 composer dump
