### ISSUE TITLE
路由别名权限无法设置

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#666]
- Laravel Version: 5.8
- PHP Version: 7.4
- Dcat Admin Version: 1.7.6

### Description:
如果上述的方法不能满足需求，HTTP路径还支持填写路由别名，如admin.users.show

这个在路由文件设置好别名之后，在权限设置路径那里无法搜索到路由别名，手动填写上去无法保存

**Comment by jqhph** [comment]
操作问题，文档有说明，输入完后使用 空格 + 回车 键就能确认

**Comment by joey2017** [comment]
确定是操作问题，找了好久没找到文档说明的地方
