### ISSUE TITLE
后台多语言，添加语言到后台路由

### ISSUE THREAD

**Issue by jimmylin66** [jqhph/dcat-admin#667]
- Laravel Version: 7.29.2
- PHP Version: 7.4.5
- Dcat Admin Version: 2.*

### Description:
我需要做一个多语言的cms，当我在后台点击语言链接的时候，我能切换到相对应的语言。
我使用LaravelLocalization插件来实现语言路由的切换：`prefix' => LaravelLocalization::setLocale() . '/' . config('admin.route.prefix')`。
这些在刚刚实现的时候运行良好，但过了一晚之后，当我点击切换语言链接的时候，系统需要验证登录，自动跳转到：`http://cms.test/admin/auth/login`，登录之后会跳转到后台首页：`http://cms.test/admin`。我需要当我点击跳转链接的时候，他会跳转到：`http://cms.test/zh_CN/admin`。如果我硬改跳转路由到：`http://cms.test/zh_CN/admin`，则会重定向过多。请问如何解决跳转到后台首页的问题或者有没有更好的方式实现多语言后台？
![image](https://user-images.githubusercontent.com/9912445/98426916-d6468200-20d5-11eb-8b31-7c5bb5b06d0e.png)

**Comment by jqhph** [comment]
其实没必要在链接上做多语言处理，可以参考[演示站点](http://103.39.211.179:8080/admin/auth/login)的多语言切换方案

**Comment by jimmylin66** [comment]
谢谢！在链接做多语言的确不是一个好的方案。我最后参考演示站点，用了session储存语言更改。
