### ISSUE TITLE
后台的静态文件（包括js组件）怎么应用到前台的blade模版中使用呢

### ISSUE THREAD

**Issue by joey2017** [jqhph/dcat-admin#668]
- Laravel Version: 5.8
- PHP Version:7.4
- Dcat Admin Version: 1.7.6

### Description:

现在后台生成前端js，html，css代码已经很方便了，有没有可能把这个js组件应用到前台的blade模版中呢，这样就不用重新组织或者封装js代码了

**Comment by jqhph** [comment]
不建议这么用，后台加载的静态资源太多，在前台使用的话比较影响体验

**Comment by jqhph** [comment]
如果实在想用，可以用`$content->full()`，具体用法参考文档开发前必读
