### ISSUE TITLE
动作以及表单响应返回错误

### ISSUE THREAD

**Issue by tizips** [jqhph/dcat-admin#670]
- Laravel Version: 8.*
- PHP Version: 7.4.11
- Dcat Admin Version: 2.0.6-beta 58250ab

### Description:
Controller 中直接调用 「Dcat\Admin\Http\JsonResponse」返回 500 错误：TypeError
错误信息：Argument 1 passed to Symfony\Component\HttpFoundation\Response::setContent() must be of the type string or null, object given, called in /Users/tizips/www/blog/vendor/laravel/framework/src/Illuminate/Http/Response.php on line 65

```php

use Dcat\Admin\Http\JsonResponse;

return JsonResponse::make()
            ->success('保存成功')
            ->refresh()
```

**Comment by jqhph** [comment]
控制器中使用需要加上 `->refresh()->send()`

**Comment by tizips** [comment]
已解决
