### ISSUE TITLE
Form表单中如果有字段同时使用default()和disable属性时，表单中的文件或图片字段会提示上传失败

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#671]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.6

### Description:

![image](https://user-images.githubusercontent.com/31877333/98495142-7a1c6300-2279-11eb-815f-2db016e5f02a.png)
![image](https://user-images.githubusercontent.com/31877333/98495215-9ddfa900-2279-11eb-8f8b-b992150cc4c0.png)

以下两种情况：default()属性指定具体值或去掉disable属性 上传文件正常
![image](https://user-images.githubusercontent.com/31877333/98495300-ca93c080-2279-11eb-9785-7d6cf6562531.png)
![image](https://user-images.githubusercontent.com/31877333/98495394-fc0c8c00-2279-11eb-8404-9fb6fa330760.png)

比较奇怪的问题

**Comment by zhaoshl** [comment]
只好舍弃select换成display了

**Comment by jqhph** [comment]
看下上传接口返回以及错误日志是否有报错
