### ISSUE TITLE
关于配置文件中 auth.except 和 permission.except 的问题

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#673]
- Laravel Version: v8.11.2
- PHP Version: 7.4
- Dcat Admin Version: v1.7.6

### Description:
有些页面不需要登录和权限都能打开。按我理解，既然都不需要登录，是不是应该只将页面的url添加到 auth.except 里就可以了，而无需添加到 permission.except 。实际结果是，如果只在auth.except 里设置，不登录是可以访问，但登录后，反而提示‘權限不足’，必须要添加到permission.except 才可以。

我建议优化一下auth.except 和 permission.except之间的逻辑关系，让看起来更符合一般逻辑。

**Comment by jqhph** [comment]
好的，感谢建议
