### ISSUE TITLE
orderable 浏览器报错

### ISSUE THREAD

**Issue by tonswin** [jqhph/dcat-admin#674]
### Description:
`$this->order->orderable;`
点击排序时候 浏览器报错
`Ajax.js:55 Uncaught TypeError: Cannot convert undefined or null to object`

**Comment by jqhph** [comment]
什么版本

**Comment by tonswin** [comment]
@jqhph v2.0.6-beta

**Comment by tonswin** [comment]
@tonswin 
grid-extend.js 227行 
`  url: _this.options.url.replace(':key', key),` 
后面少了一行
`  data: {_orderable:direction},`
