### ISSUE TITLE
工具表单中使用选项卡（Tab）布局，点击选项卡标签无响应

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#675]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.6

### Description:
![image](https://user-images.githubusercontent.com/31877333/98506325-3126d780-2296-11eb-9efb-596a6bf24ccc.png)

**Comment by jqhph** [comment]
这个功能是正常的，检查你的代码

**Comment by zhaoshl** [comment]
> 这个功能是正常的，检查你的代码

http://www.dcatadmin.com/docs/2.x/widgets-form.html
测试了很多次，点击标签仍然响应，使用的是：工具表单->tab选项卡布局 中的示例，继续求助！！！

**Comment by jqhph** [comment]
我测试是正常的，你可以升级到最新版本试试

**Comment by AzureSkyHuHu** [comment]
我也有这个问题..... 版本最新2.17... 弹窗表单 不支持tab  点击标签无响应
