### ISSUE TITLE
form 表单 currency 类型 value取值问题

### ISSUE THREAD

**Issue by lwt33713803** [jqhph/dcat-admin#676]
- Laravel Version: ^8.0
- PHP Version: ^7.3
- Dcat Admin Version: v2.0.2-beta

### Description:

form表单中使用 currency 类型输入框，保存的时候 

```
 General error: 1366 Incorrect decimal value: '$ 1.00' for column *****
```

$ 符号作为value值了

**Comment by jqhph** [comment]
请升级到[v2.0.6](http://www.dcatadmin.com/docs/2.x/beta-change-log.html)
