### ISSUE TITLE
循环调用的action类，如何区分其中的操作

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#677]
需要重写html，并添加对应的监听吗，还是有可以设置的方法，文档没找到合适的属性

**Comment by jqhph** [comment]
贴代码以及你的版本号

**Comment by Warrens-yg** [comment]
^1.7

**Comment by jqhph** [comment]
需要重写`makeSelector`方法，那个key根据你的参数变化就可以了

**Comment by Warrens-yg** [comment]
为什么我在handle中获取不到当前点击的 `$this->bookId` 的值，也设置了对应的     /**
     * @return array
     */
    protected function parameters()
    {
        return [
            'title' => $this->title,
            'bookId' => $this->bookId,
        ];
    }

**Comment by Warrens-yg** [comment]
已解决，应该是用$request获取参数，是我搞错了

**Comment by Warrens-yg** [comment]
必须得重写makeSelector才正确，不知道这其中是什么关系

**Comment by jqhph** [comment]
`makeSelector`的主要作用是防止生成重复的`JS`代码，我后面想想怎么优化这个功能吧

**Comment by Warrens-yg** [comment]
好的
