### ISSUE TITLE
表单select控件, 设置disabled以后, 提交字段内容为空, 设置为readonly, 选项又可以选择

### ISSUE THREAD

**Issue by johnsonxie83** [jqhph/dcat-admin#681]
- Laravel Version: 7.24
- PHP Version: 7.2.11
- Dcat Admin Version: 1.7.4

### Description:
表单编辑页面, select控件设定为disabled, saving事件获取到的内容为null, 随后把disabled修改为readonly, saving事件可以获取到内容, 但是select控件变成是可选状态.
个人的目的是想把select变为不可选, saving事件的时候可以获取到对应的内容, 请问这个有什么办法解决

### Steps To Reproduce:
以下是代码内容:
$form->select('channel_id')->options(url('/channel/list'))->disable();

**Comment by jqhph** [comment]
建议使用 display + hidden

**Comment by johnsonxie83** [comment]
> 建议使用 display + hidden

非常感谢这么快就回复了消息，我这边先按照你的建议调整一下代码，但是还是非常希望能改进一下，因为之前laravel-admin是可以用readonly

**Comment by zhaoshl** [comment]
遇到了同样的问题，希望能够解决；
暂时可以先把select设置为 disabled，在提交前在把它的disabled属性去掉可以实现readOnly一样的功能。

**Comment by johnsonxie83** [comment]
> 遇到了同样的问题，希望能够解决；
> 暂时可以先把select设置为 disabled，在提交前在把它的disabled属性去掉可以实现readOnly一样的功能。

这个是一个好办法，点赞

**Comment by Zdowson** [comment]
> 遇到了同样的问题，希望能够解决；
> 暂时可以先把select设置为 disabled，在提交前在把它的disabled属性去掉可以实现readOnly一样的功能。

请问提交前怎么把属性去掉
