### ISSUE TITLE
页脚能加自定义按钮吗？

### ISSUE THREAD

**Issue by FrankHay0305** [jqhph/dcat-admin#685]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Dcat Admin Version: 1.7.8
### Description:
我想用框架的form表单功能，但是因为业务问题，我必须对form表单是否能提交进行判断，并且需要在提交前加上一些参数。我想自己在页页脚加上一个按钮，这样我可以自行控制什么时候提交，什么情况下提交，并且可以加完参数之后提交，不知道框架是否可以自定义添加参数？

**Comment by jqhph** [comment]
建议你使用工具表单，重写一下view即可

**Comment by FrankHay0305** [comment]
好的，谢谢，问题已经解决了
