### ISSUE TITLE
重写的表单的update方法后，验证不起作用了

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#688]
原因是重写的update方法里没有了使用 Form 类中的 beforeUpdate 方法
![屏幕截图 2020-11-13 160626](https://user-images.githubusercontent.com/46614146/99039175-3358a100-25ca-11eb-9b87-a15378e1c09c.png)
但是在 update 方法中，用`$this->form()->beforeUpdate` 调用不到 Form 类中的这个方法，不知道该怎么处理

**Comment by jqhph** [comment]
没看懂，什么重写update

**Comment by Warrens-yg** [comment]
就是编辑表单的 方法,重写了 Admincontroller 中的这个方法
```
    public function update($id)
    {
        return $this->form()->update($id);
    }
```

**Comment by Warrens-yg** [comment]
因为表单涉及到多表的内容维护，并且不存在关系，所以需要重写

**Comment by jqhph** [comment]
你应该重写数据仓库的update方法，具体参考文档表单数据源

**Comment by Warrens-yg** [comment]
是这样的，多谢，应该是之前理解错误

**Comment by Warrens-yg** [comment]
还有一个问题，一个数据仓库中无法注入其他的数据仓库吗
