### ISSUE TITLE
登录提示419 unknown status

### ISSUE THREAD

**Issue by 2494911084** [jqhph/dcat-admin#689]
- Laravel Version: 8.x
- PHP Version: 7.4
- Dcat Admin Version: 2.x

### Description:
安装未报错，登录提示419 unknown status

**Comment by jqhph** [comment]
请检查安装步骤是否完整，如果安装没问题，则清除浏览器cookie重新登录试试

**Comment by 9oudan** [comment]
我也报错了，同样的版本环境，突然登录就报这个错误
