### ISSUE TITLE
2.0表单布局使用 分块布局 (block) 不显示删除按钮了

### ISSUE THREAD

**Issue by jiutu** [jqhph/dcat-admin#695]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: v2.0.7-beta

**Comment by jqhph** [comment]
在任意一个block闭包内加上

```php
$form->showFooter();
```

**Comment by jiutu** [comment]
没有呢!!!

代码图片:  http://www.s3tu.com/images/2020/11/24/QQ20201125-054514abf82.png
效果图片:  http://www.s3tu.com/images/2020/11/24/QQ20201125-0545294cc80.png
