### ISSUE TITLE
如何在2.0.8中开发一个表单的扩展包遇到问题，是否有稍微详细点的文档或者参考例子呢

### ISSUE THREAD

**Issue by inccleo** [jqhph/dcat-admin#697]

**Comment by jqhph** [comment]
内置的所有表单都可以参考，另外请阅读文档

- [表单字段扩展](http://www.dcatadmin.com/docs/2.x/model-form-field-management.html)
- [扩展开发](http://www.dcatadmin.com/docs/2.x/model-form-field-management.html)

**Comment by inccleo** [comment]
表单扩展自定义组件的方式目前可以实现，但是想做成插件形式不行，看了扩展开发文档并且参考了百度编辑器和日志扩展还是不行呢。

**Comment by jqhph** [comment]
扩展开发教程已经很详细了，建议仔细过一遍文档，另外提问题应该提出具体的问题
