### ISSUE TITLE
form页面的提交方法是否可以自行更改？

### ISSUE THREAD

**Issue by FrankHay0305** [jqhph/dcat-admin#700]
- Laravel Version: 7.2.5
- PHP Version: 7.2
- Dcat Admin Version: 1.7.4

### Description:
我现在有一个复制的功能键，点击复制之后，需要复制当前页面的数据，所以我想要利用编辑页面，当点击复制按钮时，我让页面指向$this->form()->edit($id),之后，我根据条件，把edit页面的action更换了$form->action('/test/copy/store');，但是发现我把action 更换了之后，页面的method 还是put方法，所以没法提交到后台了，请问这个有办法解决吗？

**Comment by FrankHay0305** [comment]
目前我用js,手动更改了

**Comment by jqhph** [comment]
不支持
