### ISSUE TITLE
升级文档可以补充一下

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#705]
全局搜索命名空间 Dcat\Admin\Models\Repositories 并替换为 Dcat\Admin\Http\Repositories

**Comment by Warrens-yg** [comment]
分布表单适用于最新版本吗

**Comment by jqhph** [comment]
参考文档 1.x升级指南

**Comment by jqhph** [comment]
https://github.com/dcat-admin/form-step 分步表单已经移出来开发成扩展了

**Comment by Warrens-yg** [comment]
> 参考文档 1.x升级指南

我看了文档的第三项没有提到这部分，我的代码出错了检查是这个地方的命名空间的问题，所以补充一下

**Comment by Warrens-yg** [comment]
> https://github.com/dcat-admin/form-step 分步表单已经移出来开发成扩展了

我看最近一次提交的commit消息写的是适配2.0.4beta版本，所以想确定一下最新的版本是不是也适用，不过我已经尝试了，目前没有问题，多谢
