### ISSUE TITLE
升级 2.0.8beta 之后，$.post 与 $.ajax 的问题

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#708]
某些地方使用 $.post 发起的请求会出现错误提示，但是改为 $.ajax 发送之后就没有问题了，错误提示如下：
![Google Chrome 2020-11-18 19 38 30](https://user-images.githubusercontent.com/46614146/99519899-c84a0880-29d5-11eb-972a-d28fc070c114.png)

**Comment by jqhph** [comment]
你的用法有问题，第一个参数要传对象

**Comment by Warrens-yg** [comment]
没理解是哪个地方的参数有问题，可以详细说一下吗，代码是这样的
`$.post("{{` url('admin/uploadsAjax/removeFile') }}",{ file: deleteFile,'_token':Dcat.token }) 出现错误
                        // $.ajax({ 正常
                        //     url: "{{ url('admin/uploadsAjax/removeFile') }}",
                        //     type: "POST",
                        //     data: {
                        //         file: deleteFile,
                        //         '_token':Dcat.token
                        //     }
                        // })`
