### ISSUE TITLE
Unable to call model function from Grid display method

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#71]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

i tried using `$this->destination()` to call a method from the grid but it return array of all attributes from the model .

```
$grid->column('destinationdd', trans('admin.destination'))->display(function () {
            return $this->destination();  // a method in a model
 });
```

a Model method

    ```
public function destination()
    {

        return optional(Country::find($this->d_country_id))->name . ' | ' . $this->d_state;

    }
```

**Comment by jqhph** [comment]
You can do it like this

```php
$grid->column('destinationdd')->display(function () {
    return (new Model())->forceFill($this->toArray())->destination();
});
```

**Comment by cyclegtx** [comment]
> You can do it like this
> 
> ```
> $grid->column('destinationdd')->display(function () {
>     return (new Model())->forceFill($this->toArray())->destination();
> });
> ```

这种forceFill的方式会造成，Model的casts报错。比如
```
protected $casts = [
        "report_data"=>"array",
];

$model->report_data;
```
就会报错json_decode() expects parameter 1 to be string。应该是forceFill把已经json_decode的数据直接放到attributes里了，再次cast的的时候就报错了。
在代码里的其他地方是不是用过这种方法forceFill, 我在处理model的deleted事件的时候，尝试调用casts之后的值，导致报错。不得已弃用casts方法，又重新写了对应的 get set方法，在get方法里判断，如果is_array就直接返回不再json_decode。
不能用casts真的变麻烦很多。
