### ISSUE TITLE
 php artisan optimize 报错Unable to prepare route[admin.extensions.index]

### ISSUE THREAD

**Issue by strangebank** [jqhph/dcat-admin#710]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: v2.0.8-beta

### Description:
创建了多应用 (多后台) 执行artisan 的时候 报错
 php artisan optimize
  Unable to prepare route [admin/helpers/extensions] for serialization. Another route has already been assigned name [admin.extensions.index].

**Comment by zhaoshl** [comment]
> * Laravel Version: 8
> * PHP Version: 7.4
> * Dcat Admin Version: v2.0.8-beta
> 
> ### Description:
> 创建了多应用 (多后台) 执行artisan 的时候 报错
> php artisan optimize
> Unable to prepare route [admin/helpers/extensions] for serialization. Another route has already been assigned name [admin.extensions.index].

执行以下命令清空路由时报以上同样的错
php artisan route:cache

**Comment by smartymoon** [comment]
没有多应用，也有这个问题，helper 的路由名重复
laravel-admin/src/Admin.php: 530 行

**Comment by zhaoshl** [comment]
> 没有多应用，也有这个问题，helper 的路由名重复
> laravel-admin/src/Admin.php: 530 行

注释掉laravel-admin/src/Admin.php: 529 行不再报错，希望作者能够解决，坐等新版本....

**Comment by jqhph** [comment]
@smartymoon @zhaoshl 生成路由缓存前先关闭debug模式，这个helpers/extensions路劲是即将废弃的

**Comment by zhaoshl** [comment]
谢谢！确实如此，在生产环境就没有报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月16日(星期三) 上午10:06
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin]  php artisan optimize 报错Unable to prepare route[admin.extensions.index] (#710)





 
@smartymoon @zhaoshl 生成路由缓存前先关闭debug模式，这个helpers/extensions路劲是即将废弃的
