### ISSUE TITLE
暗黑模式下选中的菜单位置异常

### ISSUE THREAD

**Issue by Celaraze** [jqhph/dcat-admin#712]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.0.9

### Description:
打开暗黑模式，选中左侧任意菜单，位置会往左边偏移

![微信图片_20201119164228.png](https://i.loli.net/2020/11/19/lAezHNaXdE9J2mf.png)

**Comment by jqhph** [comment]
好的

**Comment by jqhph** [comment]
已修复，谢谢反馈
