### ISSUE TITLE
表格选择器 (selectTable)的交互问题

### ISSUE THREAD

**Issue by ajiader** [jqhph/dcat-admin#716]
- Laravel Version: 6.#.#
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.#

### Description:
想用 表格选择器 (selectTable) 改成这样的效果  可以支持多级联动  交互      
![image](https://user-images.githubusercontent.com/4979798/99747628-e6b71d80-2b15-11eb-8ffe-88452ed18a67.png)
![image](https://user-images.githubusercontent.com/4979798/99747981-87a5d880-2b16-11eb-845e-5d21f586b714.png)

但是selectTable打开页面是用的grid组件做交互 大佬怎么才能自定义页面 与 selectTable 组件交互

**Comment by jqhph** [comment]
这个功能实现比较复杂，三两句话很难讲清楚，如果有时间可以尝试看看源码，建议先做成select联动

**Comment by yugihuang** [comment]
> 这个功能实现比较复杂，三两句话很难讲清楚，如果有时间可以尝试看看源码，建议先做成select联动

看了select-table.js的源码，能否在提交和取消后触发相应的事件。目前只能监听dialog:close，处理起来挺复杂。
