### ISSUE TITLE
$form->block 里面嵌套 表单字段动态显示

### ISSUE THREAD

**Issue by ahjie** [jqhph/dcat-admin#718]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.0.9

### Description:

$form->block 里面嵌套 表单字段动态显示 
单选组件 能显示   单选框里面的内容无法显示

**Comment by jqhph** [comment]
单选组件是指？

**Comment by ahjie** [comment]
$form->block(8, function (Form\BlockForm $form) {
                    $form->showFooter();
                    $form->hidden('id');
                    $form->text('title');
                    $form->tags('keywords');
                    $form->textarea('description');

                $form->radio('type')
                    ->when(1, function (Form $form) {
                        $form->image('litpic')->uniqueName();  // 这里无法显示
                    })
                    ->when(2, function (Form $form) {

                    })
                        ->options([
                        1 => '店铺',
                        2 => '招聘'
                    ])
                    ->default(1);

                    $form->editor('content');
                });

**Comment by jqhph** [comment]
这个问题已经修复，忘了回复了 #723
