### ISSUE TITLE
Controller 中使用 $this->response() 响应报错

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#719]
这两种写法都报错
```
   return JsonResponse::make()->success('成功！');
   return $this->response()->success();
```
![屏幕截图 2020-11-20 223821](https://user-images.githubusercontent.com/46614146/99806262-1d764d80-2b81-11eb-8cf7-fed22b178c9a.png)

**Comment by jqhph** [comment]
控制器中使用需要加上send方法
```php
 return $this->response()->success()->send();
```

**Comment by Warrens-yg** [comment]
OK，多谢

**Comment by Warrens-yg** [comment]
我用这种是可以的
return JsonResponse::make()->success(trans('admin.delete_succeeded'))->refresh()->send();
但是直接用 
```
$this->response()
```
提示我找不到此方法；
