### ISSUE TITLE
\Dcat\Admin\Admin::guard()->loginUsingId()无效

### ISSUE THREAD

**Issue by Abbotton** [jqhph/dcat-admin#72]
感谢开源这么牛x的扩展包，使用过程中遇到一个问题，`\Dcat\Admin\Admin::guard()->loginUsingId()`和`\Dcat\Admin\Admin::guard()->onceUsingId()`等方法无效，是不是我姿势不对？附代码：
```php
use Dcat\Admin\Admin;

Route::get('/test', function () {
    // Admin::guard()->loginUsingId(1);
    Admin::guard()->onceUsingId(1);
    return redirect('/admin');
});
```

求解答，非常感谢！

**Comment by jqhph** [comment]
实测有效
```php
Admin::guard()->loginUsingId(1);
```

**Comment by Abbotton** [comment]
跳转之后又到了登录界面了。`\Dcat\Admin\Middleware\Authenticate`中间件中，`Admin::guard()->guest()`返回为`true`.

**Comment by jqhph** [comment]
> 跳转之后又到了登录界面了。`\Dcat\Admin\Middleware\Authenticate`中间件中，`Admin::guard()->guest()`返回为`true`.

你这个思路不对呀，`Admin::guard()->onceUsingId(1);`只是在当前请求内有效，并不会把登录数据保存到`session`，所以你跳转的时候就让你到登录界面了

**Comment by Abbotton** [comment]
我的需求是这样，访问指定URL即可登录到后台，不知道有没有好的办法。
我知道`onceUsingId()`只在当前请求内有效，现在把`->onceUsingId(1)`换成`->loginUsingId(1)`也是一样的效果，还是会跳转到登录界面，我还尝试过`->login($user, true)`, 也是一样的。可能我姿势不对，求协助。

**Comment by jqhph** [comment]
我刚才的回复是错的，`loginUsingId`是会保存到session的，你可以尝试这样做

Route::group([
   'prefix' => config('admin.route.prefix')，
    'middleware'    => ['web'],
], function (Router $router) {
    $router->get('api/login', function () {
        Admin::guard()->loginUsingId(1);

        // 这里返回json
        return ['status' => 1];
    });

  $router->get('login', function () {
       // 这里写js请求 /admin/api/login，登录成功用js跳转到 admin后台
    });
});

**Comment by Abbotton** [comment]
非常感谢提供的思路，我刚才又尝试了一下，搞定了，附代码：
```php
use Dcat\Admin\Admin;

Route::get('/test', function () {
-    Admin::guard()->loginUsingId(1);
+    Admin::guard()->loginUsingId(1, true);
    return redirect('/admin');
- });
+ })->middleware('web');
```

**Comment by almas1992** [comment]
> 非常感谢提供的思路，我刚才又尝试了一下，搞定了，附代码：
> 
> ```
> use Dcat\Admin\Admin;
> 
> Route::get('/test', function () {
> -    Admin::guard()->loginUsingId(1);
> +    Admin::guard()->loginUsingId(1, true);
>     return redirect('/admin');
> - });
> + })->middleware('web');
> ```
> 
> [via](https://stackoverflow.com/a/36378606)

要用session认证确实需要加session中间件，在Laravel文档中也有说明的
