### ISSUE TITLE
Alter form created with Form::make(...,function(Form $form) {....})

### ISSUE THREAD

**Issue by shacky** [jqhph/dcat-admin#720]
- Laravel Version: 6.2
- PHP Version: 7.3
- Dcat Admin Version: 2.0.9 beta

### Description:
Cannot alter a form created by code like this:

```php
$form = Form::make(..., function(Form $form) {
...
});
```

I need to alter some fields generated by other controller form method. If there is a callback method to build form like in code above, it's not executed until render is called. I cannot call $form->build() myself, because it's protected method.

~~Can we make this method public and clear $this->callback after call?~~

It's very important for me because I extend Dcat UserController - I add fields like e-mail, add required rule to roles and I fill default values...
In Laravel-admin it worked like this:

```php
    public function form()
    {
        $form = parent::form();
        // here I could call $form->build() if it would be public (but it's wrong idea, see second comment)
        $form->email('email')->rules(['required','unique:app_users,email,{{id}}']);
        ....
        $form->builder()->field('roles')->required();
        ....
        return $form;
    }
```

~~Final build method from Dcat Form would look like this:~~
```php
    /**
     * @return void
     */
    public function build()
    {
        if ($callback = $this->callback) {
            $callback($this);
            $this->callback = null;
        }

        foreach ($this->conditions as $condition) {
            $condition->process();
        }
    }
```
~~I can make pull request - what do you think?~~

**Comment by shacky** [comment]
One more related issue to builder callback...
UserController in Dcat:
```php
    public function form()
    {
        return Form::make(Administrator::with(['roles']), function (Form $form) {
            $userTable = config('admin.database.users_table');

            $connection = config('admin.database.connection');

            $id = $form->getKey(); // here is always null, even if I edit user, so password is always required... etc.
```

**Comment by shacky** [comment]
My only idea is to allow multiple builder callbacks and queue second callback that alters original form...

**Comment by jqhph** [comment]
```php
$form = Form::make(..., function(Form $form) {
    ...

    $this->extendForm($form);
});
```

```php
public function extendForm(Form $form)
{
     parent::extendForm($form);

     ...
}
```

**Comment by shacky** [comment]
Yes, but with above solution **I have to edit _Dcat_ UserController, RoleController** etc... and add there $this->extendForm($form); with empty extendForm method. This is not nice to edit vendor library.
I will make pull request with my solution - please check it :)

**Comment by shacky** [comment]
closing it... will use:
```php
$form->if(true)->then(function(Form $form) {
....
});
```
