### ISSUE TITLE
添加、编辑等按钮怎样附带参数？

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#726]
- Laravel Version: 8.0
- PHP Version:7.3
- Dcat Admin Version: 2.0.9

### Description:
在处理一对多关系的表格中，有时有一些特殊业务需求需要单独添加列表中某一条记录的多个子关系数据，Grid中可以通过request()->pid来获取父级参数，新增按钮以及新增页面中的列表按钮等如何传递参数呢？

参考了以下解决方案，但修改底层代码后每次升级会覆盖，希望能得到更好的解决方案，谢谢！
https://blog.csdn.net/HZX19941018/article/details/109569648

**Comment by jqhph** [comment]
可以通过下面的代码传递参数
```php
$grid->model()->setConstraints([
     'key' => 'value'
]);
```

**Comment by zhaoshl** [comment]
谢谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 上午9:14
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 添加、编辑等按钮怎样附带参数？ (#726)





 
可以通过下面的代码传递参数
 $grid-&gt;model()-&gt;setConstraints([      'key' =&gt; 'value' ]);

**Comment by zhaoshl** [comment]
> 可以通过下面的代码传递参数
> 
> ```
> $grid->model()->setConstraints([
>      'key' => 'value'
> ]);
> ```

继续问一下，删除后的回调刷新怎样附带参数呢？删除之后自动刷新页面地址就没有附带参数了，求解！
