### ISSUE TITLE
固定列遮挡住搜索

### ISSUE THREAD

**Issue by strangebank** [jqhph/dcat-admin#728]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: v2.0.9-beta

### Description:

固定列挡住搜索过滤器

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/5893333/99975447-3418e080-2ddd-11eb-9a58-eb9c5fbe413f.png)

**Comment by jqhph** [comment]
感谢反馈，已修复，这周内会发布新版本
