### ISSUE TITLE
建议在 EloquentRepository 中加入 widthCount 方法。

### ISSUE THREAD

**Issue by ZkfIsYou** [jqhph/dcat-admin#730]
- Laravel Version: 8.13.0
- PHP Version: 7.3.4
- Dcat Admin Version: 2.0.5

### Description:
 update  2.0.5-beta => 2.0.9-beta

### Steps To Reproduce:
升级过程正常，升级后大部分功能正常。
建议在 EloquentRepository 中加入 widthCount 方法。

**Comment by jqhph** [comment]
`withCount`没有必要加在数据仓库，可以用`$grid->model()->withCount([xxx]);`
