### ISSUE TITLE
代码生成器生成的翻译文件问题

### ISSUE THREAD

**Issue by a245589351** [jqhph/dcat-admin#733]
- Laravel Version: 8.0
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.9

### Description:
* 当控制器使用CrowdfundingProductsController.php时，翻译文件的labels会有两个key，CrowdfundingProducts与crowdfunding-products，其中crowdfunding-products应当调整为crowdfunding_products，否则面包屑的翻译会出现异常

**Comment by jqhph** [comment]
你是不是搞反了，这个是需要 中划线 才能翻译吧

**Comment by a245589351** [comment]
文件使用的是中划线，里面的lables得用下划线
![image](https://user-images.githubusercontent.com/17821261/100327568-6d806480-3006-11eb-9a1d-a4cdc278d1ec.png)

**Comment by a245589351** [comment]
我在grid方法做了Request::segments()，代码如下：
![image](https://user-images.githubusercontent.com/17821261/100331489-31033780-300b-11eb-9b30-f25b1bfc7ee1.png)

打印的结果如下：
![image](https://user-images.githubusercontent.com/17821261/100331546-42e4da80-300b-11eb-8afd-4c5babda98b6.png)

导致翻译的时候label使用的是crowdfunding_products
