### ISSUE TITLE
按钮点击没有反应，nginx出现502

### ISSUE THREAD

**Issue by zhengwenle** [jqhph/dcat-admin#734]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version:  v2.0.9-beta 

### Description:
列表有多条数据，点击第一条数据操作按钮没问题，然后点击第二条数据之后的都没任何反应，同时出现nginx502，谷歌浏览器、360浏览器极速模式都是这样，火狐浏览器暂时没发现问题。请看截图。
<img width="1439" alt="WechatIMG3224" src="https://user-images.githubusercontent.com/19216619/100102333-6a6a6480-2e9e-11eb-8a5f-7a65369a6ded.png">
<img width="1420" alt="WechatIMG3229" src="https://user-images.githubusercontent.com/19216619/100102338-6cccbe80-2e9e-11eb-8d89-cdcb529be52c.png">

**Comment by jqhph** [comment]
检查你的nginx配置，这个跟dcat没有什么关系
