### ISSUE TITLE
grid 自定义视图 里面  传进去的参数是哪些  怎么来显示grid的内容

### ISSUE THREAD

**Issue by leetotti** [jqhph/dcat-admin#737]
![image](https://user-images.githubusercontent.com/12230465/100200413-8707aa80-2f39-11eb-910a-558f594a236b.png)
示例中的 这个blade页面是怎么操作的

**Comment by jqhph** [comment]
请参考源码 https://gitee.com/jqhph/dcat-admin-demo

**Comment by leetotti** [comment]
好的 谢谢
