### ISSUE TITLE
表单/详情是否可支持多栏布局

### ISSUE THREAD

**Issue by kevin700523** [jqhph/dcat-admin#74]
感谢 @jqhph 辛苦写了这么好用的框架

问题描述：
表单/详情目前貌似只能做1栏式布局
如果栏位太多会导致页面太长
是否能有如 $grid->filter 里的设置能自订2.3.4栏的布局 (如下图)

![123](https://user-images.githubusercontent.com/16574141/81278416-3b1e1280-9088-11ea-87af-ed28d6a2dbf2.png)

**Comment by jqhph** [comment]
好的，建议你暂时先用tab表单代替

**Comment by jqhph** [comment]
这个功能已支持，升级到最新版本即可。
