### ISSUE TITLE
同样定义的表单，在controller中用request()->all() 能获取到，在repository中获取不到数据

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#741]
$form->checkbox('book['.$bId.'][id]', '账套')
以数组的形式定义的

**Comment by jqhph** [comment]
试试这个 `$form->updates()`

**Comment by Warrens-yg** [comment]
用的就是这个

**Comment by Warrens-yg** [comment]
![Google Chrome 2020-11-26 12 00 19](https://user-images.githubusercontent.com/46614146/100303062-07ccb200-2fdf-11eb-9b21-b9d1fa28b351.png)
这是 $form 中的数据
