### ISSUE TITLE
2.0.9-beta版本中dateRange无法正常使用

### ISSUE THREAD

**Issue by yurenzhen** [jqhph/dcat-admin#742]
- Laravel Version: 8.16.1
- PHP Version: 7.3.18
- Dcat Admin Version: 2.0.9-beta

### Description:
已经执行过: php artisan admin:publish --force
已经清空浏览器缓存.

问题是:  $form->dateRange('extra5', 'extra6', '范围')->rules('required');
表单选择日期范围后提交表单报错: 422代码
{"errors":{"column_name.extra5start":["The column name.extra5start field is required."],"column_name.extra6end":["The column name.extra6end field is required."]},"status":false,"data":[]}

**Comment by jqhph** [comment]
更新下2.0.10-beta试试，你提供的这段在新版本中正常

**Comment by jqhph** [comment]
忘记回复了，这个bug已修复，升级到最新版本就行
