### ISSUE TITLE
如何在详情页面中显示JSON格式的字段？

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#743]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.9

### Description:

```
$form->embeds('column_name', function ($form) {
    $form->text('key1')->required();
    $form->email('key2')->required();
    $form->datetime('key3'); 
    $form->dateRange('key4', 'key5', '范围')->rules('required');
})->saving(function ($v) {
    return json_encode($v);// 转化为json格式存储
});
```

通过以上方法存储的JSON字段，如何在详情页面展示数据？

**Comment by jqhph** [comment]
参考文档数据详情基本使用

**Comment by zhaoshl** [comment]
> 参考文档数据详情基本使用

参考文档使用了如下方式实现，但不是自己想要的效果，怎样实现JSON字段中的数据像表单中的效果一样显示呢？

>             $show->field('column_name')->as(function ($column_name) {
>                 $column_name = json_decode($column_name, true);
>                 $key1 = $column_name['key1'] ?? '';
>                 $key2 = $column_name['key2'] ?? '';
>                 ......
>                 return $key1 . '|' . $key2......;
>             });

**Comment by jqhph** [comment]
参考显示扩展文档，自己实现

**Comment by zhaoshl** [comment]
> 参考显示扩展文档，自己实现

谢谢回复！

**Comment by mengdodo** [comment]
> > 参考显示扩展文档，自己实现
> 
> 谢谢回复！

哈哈哈，我笑喷了

**Comment by zwping** [comment]
https://laravel-admin.org/docs/zh/1.x/model-show-fields#json

**Comment by zwping** [comment]
`$show->extra()->json();`
