### ISSUE TITLE
数据表格动作获取主键ID问题

### ISSUE THREAD

**Issue by huangqiang93** [jqhph/dcat-admin#746]
- Dcat Admin Version: 2.0.9

数据表格动作，在handle中用$this->getKey()获取主键ID，总是获取到列表中最后一条数据到ID

**Comment by jqhph** [comment]
贴一下代码

**Comment by huangqiang93** [comment]
<?php

namespace App\Admin\Actions\Grid;

use Dcat\Admin\Grid\RowAction;
use Dcat\Admin\Actions\Response;
use Dcat\Admin\Traits\HasPermissions;
use Illuminate\Contracts\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use App\Models\TaskList;

class PassReview extends RowAction
{
    /**
     * @return string
     */
    protected $title = '通过审核';


    /**
     * Handle the action request.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function handle(Request $request)
    {
        dd($this->getKey()); //此处打印到数据都是同一个ID
        // TaskList::where('id',$this->getKey())->update(['task_status'=>2]);
        return $this->response()->success('悬赏审核成功！'.$this->getKey())->refresh();
    }

    /**
	 * @return string|array|void
	 */
	public function confirm()
	{
        // return ['Confirm?', 'contents'];
        return ['确定审核通过该悬赏吗?'];
	}

    /**
     * @param Model|Authenticatable|HasPermissions|null $user
     *
     * @return bool
     */
    protected function authorize($user): bool
    {
        return true;
    }

    /**
     * @return array
     */
    protected function parameters()
    {
        return [];
    }
}

**Comment by huangqiang93** [comment]
> 贴一下代码

![image](https://user-images.githubusercontent.com/26532617/100335762-4f1f6680-3010-11eb-8d76-47739bc911db.png)

**Comment by huangqiang93** [comment]
> 贴一下代码

用这种方法：$grid->actions([new CheckRow()]); 添加的动作，无法获取行数据
这样添加：$grid->actions(function (Grid\Displayers\Actions $actions) {
    $actions->append(new CheckRow());
}就没问题

**Comment by jqhph** [comment]
感谢反馈已修复
