### ISSUE TITLE
Form 的tags 不填写提交表单会报错Array to string conversion

### ISSUE THREAD

**Issue by strangebank** [jqhph/dcat-admin#747]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.0.9
form的 input是tag的时候，不填写直接提交会报错Array to string conversion

![image](https://user-images.githubusercontent.com/5893333/100358792-9ec25a00-3031-11eb-964d-061a983f25a8.png)

**Comment by jqhph** [comment]
参考文档常见问题
