### ISSUE TITLE
如何用一个按钮或链接打开新的浏览器窗口，离开后台管理，去做别的事

### ISSUE THREAD

**Issue by running8gubin** [jqhph/dcat-admin#748]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
偶尔想在后台放一几个链接，用来让管理员查看，有没有方法让链接和菜单打开新的窗口，其他打开其他域名的网页

**Comment by jqhph** [comment]
菜单可以配置完整的域名，这样会打开新的标签页
