### ISSUE TITLE
Style Question

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#75]
我苦苦寻找，终于遇到了让我非常喜欢的类型，非常感谢 @jqhph 提供了这么好用的框架

- Laravel Version: 7.0
- PHP Version: 7.3
- Dcat Admin Version: 1.3

### Description:
仪表盘的New Users Char切换选项的时候会造成页面抖动，而其他地方是正常的
![批注 2020-05-08 092542](https://user-images.githubusercontent.com/46614146/81357206-fb9a0980-910d-11ea-80c6-6070b37a94cd.jpg)

**Comment by jqhph** [comment]
感谢支持，这个可能是卡片默认高度跟渲染出来后的不太一致导致的，后面有时间了可以优化优化。另外这个卡片其实只是个demo，你可以直接改的。
