### ISSUE TITLE
希望将`字段选择器`字段显示或隐藏的设置保存到数据库

### ISSUE THREAD

**Issue by AilonHuang** [jqhph/dcat-admin#751]
- Laravel Version: 2.0.9-beta
- PHP Version: 7.4.12
- Dcat Admin Version: 7.29

### Description:
希望将`字段选择器`字段显示或隐藏的设置保存到数据库，用户退出后重新登录保持设置好的字段
如果可以，还希望加入字段顺序调整功能，调整后也是保存到数据库

**Comment by jqhph** [comment]
感谢建议，已支持这个功能
