### ISSUE TITLE
怎样让select默认选中第一个？

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#754]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

怎样让select默认选中第一个？有没有什么方法可以设置呢？

**Comment by jqhph** [comment]
`->default(xxx)`

**Comment by zhaoshl** [comment]
> `->default(xxx)`

谢谢回复！下拉选框联动的情况下，第2个下拉选框的值是动态获取的，这种情况可以默认选中第一个吗？
