### ISSUE TITLE
表单地图 (map)控件，希望能一次标记批量多个坐标

### ISSUE THREAD

**Issue by running8gubin** [jqhph/dcat-admin#762]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
我想在地图上标记一个线路的坐标，用在前端输出一条活动的线路。不知道能不能实现。
一个大的坐标json

**Comment by jqhph** [comment]
这个应该是可以实现的，要研究下地图的用法
