### ISSUE TITLE
html里加上input，input的值插入不了数据库是什么原因

### ISSUE THREAD

**Issue by pengwei1986** [jqhph/dcat-admin#765]
$form->html(function () {
                        Admin::js('/resume/js/load_hycode.js');
                        Admin::js('/resume/js/hgz_hycode.js');
                        Admin::js('/resume/js/hgz_zncode.js');
                        Admin::css('/resumes/zyzn_1.css');
                        return '<input type="text" class="form-control field_expected_position"  id="form-field-expected_position-084Ym" name="expected_position"   placeholder="请选择"  onclick="appendhyznbar(this,\'duoxuan\')" />';
                    }, '期望职位')->help('自定义内容');

post时有获取到这个input的value

**Comment by jqhph** [comment]
你这个代码哪里有input？

**Comment by pengwei1986** [comment]
$form->html(function () {
                        Admin::js('/resume/js/load_hycode.js');
                        Admin::js('/resume/js/hgz_hycode.js');
                        Admin::js('/resume/js/hgz_zncode.js');
                        Admin::css('/resume/css/zyzn_1.css');
                        return '<input type="text" class="form-control field_expected_position"  id="form-field-expected_position-084Ym"  name ="expected_position" data-value="" placeholder="请选择"  onclick="appendhyznbar(this,\'duoxuan\')" />';
                    }, '期望职位')->help('自定义内容');

**Comment by pengwei1986** [comment]
return '<input type="text" class="form-control field_expected_position"  id="form-field-expected_position-084Ym"  name ="expected_position" data-value="" placeholder="请选择"  onclick="appendhyznbar(this,\'duoxuan\')" />';

**Comment by pengwei1986** [comment]
return '<input type="text" class="form-control field_expected_position"  id="form-field-expected_position-084Ym"  name ="expected_position" data-value="" placeholder="请选择"  onclick="appendhyznbar(this,\'duoxuan\')" />';
                    }, '期望职位')->help('自定义内容');

把return后面的屏蔽了

**Comment by siYuanJun** [comment]
一样的，我的也是这样 `$form->hidden('admin_users_id')->value(Admin::user()->id)` 无法给到数据值。
查看页面也是 
![image](https://user-images.githubusercontent.com/46435703/100577262-cc055580-331a-11eb-9938-9f9992438a64.png)  @没有的 ！

**Comment by jqhph** [comment]
在前面加上一行
```php
$form->hidden(xxx);
```

**Comment by pengwei1986** [comment]
提示这个错误Method Dcat\\Admin\\Form\\Field\\Hidden::html does not exist.",

$step->hidden('expected_position')->html(function () {
                        Admin::js('/resume/js/load_hycode.js');
                        Admin::js('/resume/js/hgz_hycode.js');
                        Admin::js('/resume/js/hgz_zncode.js');
                        Admin::css('/resume/css/zyzn_1.css');

                        return '<input type="text" class="form-control" id = "expected_position" value="" name ="expected_position" data-value="" placeholder="请选择"  onclick="appendhyznbar(this,\'duoxuan\')" />';
                    }, '期望职位')->help('自定义内容');

**Comment by pengwei1986** [comment]
现在可以增加了，编辑时不能显示input的值

**Comment by pengwei1986** [comment]
怎么获取值，赋予value


                        return '<input type="text" class="form-control field_expected_position"  id="form-field-expected_position-084Ym" value="'.$form->expected_position.'" name ="expected_position" data-value="" placeholder="请选择"  onclick="appendhyznbar(this,\'duoxuan\')" />';
                    }, '期望职位')->help('自定义内容');
