### ISSUE TITLE
登录页面如何设置背景图？

### ISSUE THREAD

**Issue by jxintao** [jqhph/dcat-admin#768]
- Laravel Version: 8.12
- PHP Version: 7.3
- Dcat Admin Version: 2.*

### Description:
![image](https://user-images.githubusercontent.com/12730585/100580399-cf9bdb00-3320-11eb-82ee-1e6763248195.png)
登录页面如何设置背景图？

**Comment by jqhph** [comment]
参考 https://gitee.com/jqhph/dcat-admin-demo

**Comment by jxintao** [comment]
> 参考 https://gitee.com/jqhph/dcat-admin-demo

demo 里面用的版本是1.*的 直接设置login_background_image就行，2.*的是移除的这个设置吗，有没有其他方式可以实现

**Comment by jxintao** [comment]
？？

**Comment by yurenzhen** [comment]
@所有人, 如以下配置所示:
config/admin.php中的auth.controller => App\Admin\Controllers\AuthController::class;

要更改背景图或者大概登录页面, 可以参考如下方法:
方法①: 直接在App\Admin\Controllers\AuthController::class中添加:
protected $view = 'admin.new_login';//假设你的新视图是 resources/view/admin/new_login.blade.php
你的新登录页面可以复制原始登录页面vendor/dcat/laravel-admin/resources/views/pages/login.blade.php的内容, 然后小改或大改.
参考: Dcat\Admin\Http\Controllers\AuthController

方法②: 写一个新类继承App\Admin\Controllers\AuthController::class, 然后在里面小改或大改, 这时候记得更改config/admin.php中的auth.controller配置值.

**Comment by CherishNA** [comment]
> @所有人, 如以下配置所示: config/admin.php中的auth.controller => App\Admin\Controllers\AuthController::class;
> 
> 要更改背景图或者大概登录页面, 可以参考如下方法: 方法①: 直接在App\Admin\Controllers\AuthController::class中添加: protected $view = '你的新登录页面.blade.php'; 你的新登录页面可以复制原始登录页面vendor/dcat/laravel-admin/resources/views/pages/login.blade.php, 然后小改或大改.
> 
> 方法②: 写一个新类继承App\Admin\Controllers\AuthController::class, 然后在里面小改或大改, 这时候记得更改config/admin.php中的auth.controller配置值.

根据你这个方法修改了登录页面，但是登录的时候直接提示403，然后清除缓存 重启nginx都不可以 都是403

**Comment by mbdmt** [comment]
> 



> > @所有人, 如以下配置所示: config/admin.php中的auth.controller => App\Admin\Controllers\AuthController::class;
> > 要更改背景图或者大概登录页面, 可以参考如下方法: 方法①: 直接在App\Admin\Controllers\AuthController::class中添加: protected $view = '你的新登录页面.blade.php'; 你的新登录页面可以复制原始登录页面vendor/dcat/laravel-admin/resources/views/pages/login.blade.php, 然后小改或大改.
> > 方法②: 写一个新类继承App\Admin\Controllers\AuthController::class, 然后在里面小改或大改, 这时候记得更改config/admin.php中的auth.controller配置值.
> 
> 根据你这个方法修改了登录页面，但是登录的时候直接提示403，然后清除缓存 重启nginx都不可以 都是403

AuthController裡的格式應該是標準view路徑寫法
protected $view = 'admin.login';

admin.login等同resources\views\admin\login.blade.php

**Comment by yurenzhen** [comment]
> > 
> 
> > > @所有人, 如以下配置所示: config/admin.php中的auth.controller => App\Admin\Controllers\AuthController::class;
> > > 要更改背景图或者大概登录页面, 可以参考如下方法: 方法①: 直接在App\Admin\Controllers\AuthController::class中添加: protected $view = '你的新登录页面.blade.php'; 你的新登录页面可以复制原始登录页面vendor/dcat/laravel-admin/resources/views/pages/login.blade.php, 然后小改或大改.
> > > 方法②: 写一个新类继承App\Admin\Controllers\AuthController::class, 然后在里面小改或大改, 这时候记得更改config/admin.php中的auth.controller配置值.
> > 
> > 
> > 根据你这个方法修改了登录页面，但是登录的时候直接提示403，然后清除缓存 重启nginx都不可以 都是403
> 
> AuthController裡的格式應該是標準view路徑寫法 protected $view = 'admin.login';
> 
> admin.login等同resources\views\admin\login.blade.php

感谢!
