### ISSUE TITLE
form hasMany组件下select联动问题

### ISSUE THREAD

**Issue by wk1025** [jqhph/dcat-admin#769]
- Laravel Version: 8.12.0
- PHP Version: 7.4.6
- Dcat Admin Version: 2.0.10-beta

### Description:
在hasMany组件下，product_id select无法实现联动操作，同样的的代码放在hasMany之外可以实现联动。

### Steps To Reproduce:

控制器protected function form()方法

	$form->hasMany('product', ' 产品清单', function (Form\NestedForm $form) {
		
	    $form->select('category_id', '产品分类')->options(Category::all()->pluck('name', 'id'))->load('product_id', '/api/get_product_by_category');
	    $form->select('product_id', '选择产品');

	    $form->currency('price', '产品单价')->symbol('￥');
	    $form->currency('sales_price', '销售价格')->placeholder('销售价格')->symbol('￥');
	    $form->number('total', '数量')->attribute(['style' => 'min-width: 20px']);
	    $form->currency('discount', '折扣')->symbol('%');

	})->useTable();

根据产品分类查询产品信息Api实现

	public function getProductByCategoryId(Request $request) {
        $category_id = $request->get('q', '');
        return Product::where('category_id', $category_id)->pluck('title as text', 'id');
    }

**Comment by jqhph** [comment]
感谢反馈，已修复，今晚或明晚将发布新版本
