### ISSUE TITLE
表格字段有sortable的时候不能导出全部

### ISSUE THREAD

**Issue by stevenleeyu** [jqhph/dcat-admin#77]
- Laravel Version: 7.0
- PHP Version: 7.4
- Dcat Admin Version: 1.2.0

### Description:
字段有sortable的时候不能导出全部，但能导出当前页

### Steps To Reproduce:

url参数:  /admin/stat/active?date=2020-05-04&_sort%5Bcolumn%5D=messages&_sort%5Btype%5D=desc#

代码:
$grid->messages('群消息数')->sortable()->width('100px');
$grid->export();

筛选条件有_sort的时候导出全部

Exception：
Method Illuminate\Database\Eloquent\Collection::orderBy does not exist.

导出全部

**Comment by jqhph** [comment]
感谢反馈，已修复
