### ISSUE TITLE
请教如何在头部或脚部获取当前页数据信息

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#771]
- Laravel Version: 7.x
- PHP Version: 7.2
- Dcat Admin Version: 2.0.10

### Description:
![image](https://user-images.githubusercontent.com/16422689/100687903-0ef61600-3379-11eb-8743-1d233f963775.png)
如图文档中，只是获取了where条件所有的数据，如果要根据用户选择的分页或者排序的数据(简单说就是要获取和当前列表展示的数据一样)，要如何改呢？我把$query->get();改为$query->paginate(); 获取到的分页数据还不一样，求指导，非常感谢

**Comment by jqhph** [comment]
```php
$grid->model()->paginator()->getCollection();
```

**Comment by ygcool** [comment]
非常感谢！
