### ISSUE TITLE
禁用 行选择器 之后 固定列功能展示异常 无法滚动

### ISSUE THREAD

**Issue by shijie1991** [jqhph/dcat-admin#772]
- Laravel Version:8.16.1
- PHP Version:  7.4.2
- Dcat Admin Version:  2.0.10-beta

### Description:
全局禁用 选择器后 固定列功能异常

### Steps To Reproduce:
bootstrap  全局禁用行选择器 
`Grid::resolving(function (Grid $grid) {
    $grid->disableRowSelector();
});`

控制器 使用固定列模式
`$grid->fixColumns(3, -6);`
![1606815041554](https://user-images.githubusercontent.com/11606404/100721947-faf2f880-33fa-11eb-8929-8caca63fdd59.jpg)

**Comment by jqhph** [comment]
这个问题没有复现出来请升级到最新版本从新试试

**Comment by shijie1991** [comment]
已更新最新版本 问题依旧存在

return Grid::make(new Comment(), function (Grid $grid) {

            $grid->tools(new CommentImages());

            $grid->quickSearch('content')->placeholder('搜索评论内容...');

            $grid->fixColumns(3, -6);

            $grid->disableCreateButton();
            $grid->disableViewButton();
            $grid->disableDeleteButton();
            $grid->disableActions();

            $grid->model()->with(['user'])->orderByDesc('id');

            $grid->column('id', 'ID')->sortable();
            $grid->column('user.name', '评论用户')->userName();
            $grid->column('content', '评论内容');
            $grid->column('image', '图片')->display('点击查看')->expand(Image::make());
            $grid->column('like_count', '点赞数量')->sortable();
            $grid->column('reply_count', '回复数量')->sortable();
            $grid->column('level', '评论类型')->filter(
                Grid\Column\Filter\In::make(CommentLevel::MAP)
            )->using(CommentLevel::MAP)->label([
                CommentLevel::COMMENT      => Admin::color()->green(),
                CommentLevel::REPLY        => Admin::color()->indigo(),
                CommentLevel::SECOND_REPLY => Admin::color()->info(),
            ]);

            $grid->column('status', '屏蔽')->filter(
                Grid\Column\Filter\In::make(CommentStatus::MAP)
            )->switch();
            $grid->column('created_at', '创建时间');

            $grid->filter(function (Grid\Filter $filter) {
                $filter->equal('feed_id', '动态 ID');
                $filter->equal('user_id', '用户 ID');
                $filter->between('created_at', '发布时间')->datetime();
            });
        });




> 
![2020-12-23 10 30 48](https://user-images.githubusercontent.com/11606404/102952453-28b6f300-450a-11eb-88a3-fa23c73fc327.gif)

https://user-images.githubusercontent.com/11606404/102952720-bd215580-450a-11eb-8c23-aa11f811e833.mov

**Comment by jqhph** [comment]
你总共才`9`列你用 `3, -6` ？，这明显是你代码的问题

**Comment by shijie1991** [comment]
傻逼了
