### ISSUE TITLE
artisan admin:export --users 生成的Seeder文件异常

### ISSUE THREAD

**Issue by Celaraze** [jqhph/dcat-admin#776]
- Laravel Version: 8
- PHP Version: 7.4
- Dcat Admin Version: 2.0.10

### Description:

执行 `admin:export --users` 后，导出的 seeder 文件底部，出现了不该出现的东西

![QQ图片20201202131643](https://user-images.githubusercontent.com/31471452/100831476-d3ef0200-34a0-11eb-8edc-a0c6ebad82bc.png)

**Comment by jqhph** [comment]
好的，已修复，等下个版本发布
