### ISSUE TITLE
表单 datetime 时区问题 datetime 类字段如何在post之前转换为时间戳秒数

### ISSUE THREAD

**Issue by leeyisoft** [jqhph/dcat-admin#788]
- Laravel Version: Laravel Framework 8.13.0 
- PHP Version: PHP 7.4.10
- Dcat Admin Version:  v2.0.6-beta

### Description:

1 config/app.php 中的timezone配置 为UTC
2 数据库存储的时间int类型 `published_at` int NOT NULL DEFAULT '0' COMMENT '发布时间',
3 后台管理系统（前端东八区）
![image](https://user-images.githubusercontent.com/6138668/101130348-42b59200-363e-11eb-880a-94ac07555d4a.png)
解决办法
4.1 其后提交post的时候通过某种方法把 published_at 的值 “2020-12-04 14:37:20” 在前端转换为 int 类型
4.2 把“客户端后台”的时间附带到后台

**Comment by leeyisoft** [comment]
有不有什么办法 在前端用js在post之家把 “published_at 的值 “2020-12-04 14:37:20” 在前端转换为 int 类型”

**Comment by jqhph** [comment]
````php
$form->datetime(...)->saving(function ($v) {
    return $v ? strtotime($v) : $v;
})->customFormat(function ($v) {
    return $v ? date('...', $v) : '';
});
```

**Comment by leeyisoft** [comment]
@jqhph  这个不正确 
我在标的输入框输入的是 2020-12-31 00:00:00（是东八区的零点）， 
在后台 strtotime($v) 的时候，变成了 1609372800 （我后台默认是UTC）
如下图： 1609372800 的东八区时间为 2020/12/31 8:0:0  所以不对，应该是在Ajax提交表单之前在浏览器里面用js把datetime转为int
![image](https://user-images.githubusercontent.com/6138668/101137741-3f280800-364a-11eb-9acf-2bbe41e7d3e7.png)
