### ISSUE TITLE
同时使用$form->tab()与$form->column 时 $form->hidden() 不能使用了

### ISSUE THREAD

**Issue by FrankHay0305** [jqhph/dcat-admin#789]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Dcat Admin Version: 2.0.8

### Description:
我使用$form->tab布局里面使用了column布局,这个时候，我使用$form->hidden('column') 标签时就不能使用了，但是我去掉column  布局的时候 $form->hidden('column')就可以使用了，这个问题能解决吗？

**Comment by jqhph** [comment]
请贴下代码

**Comment by FrankHay0305** [comment]
Form::make(new AssetRepository(['asset_equipments']), function (Form $form) {
    $activedBook = User::activedBookWithDate();
    $id          = $form->getKey();
    $form->hidden('id');
    $form->tab(__('asset.labels.base_info'), function ($form) use($id){
        $subjects     = SubjectRepository::getSubjectForSelect();
        $departments  = AssetDepartmentRepository::getForSelect();
        $form->column(6, function(Form $form) use ($subjects, $departments){
            $form->text('specification');
            $form->text('storage_location');
        });
        $form->column(6, function(Form $form) use ($subjects){
            $form->select('asset_subject_id')->required()->options($subjects);
            $form->select('depreciation_total_subject_id')->required()->options($subjects);
            $form->select('depreciation_fee_subject_id')->required()->options($subjects);
            $form->text('note');
        });
    })
});

**Comment by jqhph** [comment]
$form->hidden('id'); 应该放在column里面，外面会被忽略

**Comment by FrankHay0305** [comment]
试过放到column里面了，结果是一样的，hidden字段还是显示不出来，只要tab和column同时使用就不行
