### ISSUE TITLE
表单提交错误，接口返回 422 以外的状态码，如何显示提示信息

### ISSUE THREAD

**Issue by ShynHan** [jqhph/dcat-admin#791]
- Laravel Version: 8.17.1
- PHP Version: 7.4.15
- Dcat Admin Version: 1.7.5

### Description:
![image](https://user-images.githubusercontent.com/12025422/101236542-174da880-370d-11eb-9b7c-fb81a2161510.png)

如图，提交表单后，报出 400 错误状态码，错误信息在 message 中，如何让 totar 的提示信息显示 message 中对应的提示信息。
我知道 422 状态码配合 errors 可以对应的错误提示显示到对应的表单字段上，但是并不是所有情况都适合返回 422 状态，
对于 422 以外的状态，如何才能把 message 中的信息 提示出来
我发现列表页发起的 ajax 请求如果报错，会正常提示 message 中的消息。比如 在列表上的快速添加功能

**Comment by jqhph** [comment]
你在表单事件中拦截请求，返回 `$form->error('错误');` ，然后在 `exceptionhandler` 捕获异常，按照这个 `json` 格式返回就行了
