### ISSUE TITLE
请问一下列表页如何自定义选中效果

### ISSUE THREAD

**Issue by xiajinjun** [jqhph/dcat-admin#792]
- Laravel Version: 7.28.4
- PHP Version: 7.3
- Dcat Admin Version: 1.7

### Description:
请问一下列表页如何自定义选中效果？
我想选择一行后，在当前页面的下面，利用 ajax显示出选中行项目的相关信息。

例如：
在项目列表里面，有以下2行信息，
1. 项目1
2. 项目2

选择上面项目1之后，在当前页的下面显示项目1的信息。

项目信息
项目名：项目1
等等

谢谢！

**Comment by jqhph** [comment]
用js监听checkbox表单的change事件，判断选中就执行你的逻辑
