### ISSUE TITLE
showTreeInDialog  没有默认选中

### ISSUE THREAD

**Issue by caoyuyan** [jqhph/dcat-admin#794]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.0

### Description:
$nodes = (new VipPermission())->allNodes();
$grid->column('permission')
                ->showTreeInDialog(function (Grid\Displayers\DialogTree $tree) use ($nodes) {
                    $tree->nodes($nodes);
                });

查询时结果全出,使用后没有默认选中关联结果

a href="javascript:void(0)" class="_permission_2-open-tree" data-checked="" data-val=""

查看页面代码 发现 data-val 为空

**Comment by jqhph** [comment]
请参考文档升级到`2.0.11-beta`版本再试试

**Comment by caoyuyan** [comment]
> 请参考文档升级到`2.0.11-beta`版本再试试

这个问题解决了,我参考你的权限管理,在用户模型的数据仓库里面找到一个get方法,通过这个方法处理后,就能解决了.

赞!

**Comment by mintzhao** [comment]
能说下具体是怎么解决的吗？我也遇到了，我的版本是2.0.17-beta

**Comment by caoyuyan** [comment]
> 能说下具体是怎么解决的吗？我也遇到了，我的版本是2.0.17-beta
你可以看作者权限控制的源码，我记得里面有一个数据仓库里面重写了一个get方法，你按照他的写法从新写一个，就可以了

**Comment by caoyuyan** [comment]
> 能说下具体是怎么解决的吗？我也遇到了，我的版本是2.0.17-beta

就是作者后台的管理员的权限控制的源码
