### ISSUE TITLE
表格行内编辑时表单回调操作代码中是否可以获取到该行其他字段的值呢？

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#799]
- Laravel Version:8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.0.10

### Description:
需求：行内编辑单价，获取该行数量字段，然后在表单回调操作代码中自动计算总价

表格行内编辑时表单回调操作代码中是否可以获取到该行其他字段的值呢？有没有其他解决方案？

**Comment by jqhph** [comment]
```php
$form->model()->字段名;
```

**Comment by zhaoshl** [comment]
非常感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月8日(星期二) 下午4:11
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 表格行内编辑时表单回调操作代码中是否可以获取到该行其他字段的值呢？ (#799)





 $form-&gt;model()-&gt;字段名;
