### ISSUE TITLE
qrcode 使用报错

### ISSUE THREAD

**Issue by day3006** [jqhph/dcat-admin#80]
感觉页面很赞，先使用一下为了下个项目准备
- Laravel Version:6.18.13
- PHP Version: 7.3.4
- Dcat Admin Version: 1.3

### Description:
  //邀请码
            $grid->invite_code->qrcode(function(){
                return $this->url;
            });

### Steps To Reproduce:
Undefined property: App\Admin\Controllers\UserController::$url

**Comment by jqhph** [comment]
感谢反馈，已修复
