### ISSUE TITLE
表单hasMany使用验证之后报错

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#801]
添加验证规则之后，提交表单返回错误，参考下图及代码
![屏幕截图 2020-12-08 181540](https://user-images.githubusercontent.com/46614146/101464148-9f3be880-3981-11eb-824c-d14223c2b802.png)

```
                $form->width(10, 1)->hasMany('auto_transfer_entrys', function (Form\NestedForm $form) use ($subjects) {
                    $form->text('brief')->required();
                    $form->select('subject_id')->addElementClass('subject')->options($subjects)->required();
                    $form->rate('transfer_scale');
                    $form->hidden('created_by')->default(access()->id);
                    $form->hidden('updated_by')->default(access()->id);
                })->useTable();
```

**Comment by Warrens-yg** [comment]
![屏幕截图 2020-12-08 182821](https://user-images.githubusercontent.com/46614146/101465338-2b9adb00-3983-11eb-8778-3ada7f3f4a67.png)
是提交表单的时候多了这个数据导致验证没通过

**Comment by jqhph** [comment]
请附上版本号？然后描述清楚操作步骤

**Comment by Warrens-yg** [comment]
2.0.10-beta

**Comment by Warrens-yg** [comment]
查了一下代码，应该是 NestedForm 不支持 hidden 导致的

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/101559066-41e47d80-39fb-11eb-8a63-3afd5d96c0e9.png)
正常是不会有这种key的数据提交上来的，没有重现出你的问题，另外建议升级到2.0.11版本

**Comment by Warrens-yg** [comment]
好的，这个问题是因为 Form/Row 和 Form\NestedForm 同时使用才出现的，单独使用没有这个问题

**Comment by jqhph** [comment]
所以让你描述清楚问题

**Comment by Warrens-yg** [comment]
好的，我也是后来才发现是这两个同时使用导致的

**Comment by jqhph** [comment]
好的，等我有空试下

**Comment by jqhph** [comment]
感谢反馈，已修复，今天或明天会发布新版本
