### ISSUE TITLE
多个项目下dcat-admin.operation-log会共用

### ISSUE THREAD

**Issue by WangQuanTang** [jqhph/dcat-admin#811]
- Laravel Version: ^8.12
- PHP Version: PHP 7.4.11 (cli)
- Dcat Admin Version: 2.*

### Description:
开发环境使用的是homestead，目录下分别存在两个Dcat项目：test和dcat。按照步骤安装，在dcat中安装扩展，出现test项目中也出现操作日志菜单，并且数据相同，两个项目之前串了的情况。

**Comment by jqhph** [comment]
原因是操作日志这个扩展目前并没有兼容多应用的情况，如果是多应用不如自己写一个操作日志功能，可能会更适合一些
