### ISSUE TITLE
上传图片会新建空数据

### ISSUE THREAD

**Issue by wskeee** [jqhph/dcat-admin#812]
- Laravel Version: 7+
- PHP Version: 7.3+
- Dcat Admin Version: 2.0.11 bate

### 
在使用 `$form->file('solutions_url')->autoUpload()->disk('oss');`
或者 image、multipleFile 上传文件时，会自动创建一条空数据。

### Steps To Reproduce:
如 Post 表有一个solutions_url字段需要记录文件路径，在create 方法内使用
`$form->file('solutions_url')->autoUpload()->disk('oss');`
或者 image、multipleFile 上传文件时，会自动创建一条空 【post】数据。

**Comment by jqhph** [comment]
你可以看看管理员上传头像是否有问题，没有的话则是你代码有问题，提问题请贴上完整的代码

**Comment by wskeee** [comment]
管理员上传头像那里上传没有问题，我在其它没有使用分步表单上传也没有问题。

以下上传方式没有问题
```
$form->multipleFile('poster')->saving(function ($paths) {
                    return json_encode($paths);
                })->autoUpload()->disk('oss');
或者
$form->tab('基本信息', function (Form $form) {
                $form->multipleFile('poster')->saving(function ($paths) {
                    return json_encode($paths);
                })->autoUpload()->disk('oss');
            });
```

使用分步表单就有问题
```
$form->multipleSteps()->remember()->add('基本信息', function (\Dcat\Admin\FormStep\Form $form) {
                $form->multipleFile('poster')->saving(function ($paths) {
                    return json_encode($paths);
                })->autoUpload()->disk('oss');
            });
```

**Comment by jqhph** [comment]
加上 ->autoSave(false)

**Comment by wskeee** [comment]
在那里加？
![image](https://user-images.githubusercontent.com/12245375/101729881-fe216f00-3af3-11eb-9169-e08879447897.png)
【另外】我发现只有在新增时才会有这个问题，编辑不会

**Comment by wskeee** [comment]
```
$form->multipleSteps()
                ->remember()
                ->width('950px')
                ->add('基本信息', function (\Dcat\Admin\FormStep\Form $form) {
                    $form->multipleFile('poster')->saving(function ($paths) {
                        return json_encode($paths);
                    })->autoUpload()->autoSave(false)->disk('oss');
                });
```
加上 ->autoSave(false) 没有效果

**Comment by jqhph** [comment]
实际上2.0.11我自己也有项目用到分步表单，并且也有文件上传功能，并未发现你说到这个问题

**Comment by wskeee** [comment]
【新增】情况问题确实存在，【编辑】情况下暂未发现。

**Comment by jqhph** [comment]
解决方法参考 https://github.com/jqhph/dcat-admin/issues/800
