### ISSUE TITLE
树状表格点击加载的行，添加自定义按钮中使用弹窗无法弹出

### ISSUE THREAD

**Issue by abovesky** [jqhph/dcat-admin#813]
- Laravel Version: 8.12
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.11-beta

### Description:
树状表格点击加载的行，添加自定义按钮中使用弹窗无法弹出

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/5986216/101727604-bc8ec500-3aef-11eb-80af-16860aa8fbc1.png)
控制器：
![image](https://user-images.githubusercontent.com/5986216/101727732-07104180-3af0-11eb-817f-68fcc5a10bf4.png)
行动作渲染弹窗内嵌表格：
![image](https://user-images.githubusercontent.com/5986216/101727926-62423400-3af0-11eb-92ec-3a54347aaaff.png)
表格：
![image](https://user-images.githubusercontent.com/5986216/101727955-7423d700-3af0-11eb-884d-6c513dc32973.png)

**Comment by jqhph** [comment]
异步弹窗表格不是这样用的，参考文档异步组件

**Comment by abovesky** [comment]
我又照文档过了一遍依然不行，顶级节点是没问题的，但是展开后的子节点就不行，初步判断是由于展开子节点是ajax动态加载的html，导致modal绑定无效。
麻烦老大再看看

**Comment by jqhph** [comment]
用`Modal`类是可以的

**Comment by abovesky** [comment]
其他地方用都是没问题的，唯有树状表格子级不行，貌似确实有问题

**Comment by kalepan** [comment]
我也遇到这个问题。 树状表格的子层级是无效的，我使用的是异步弹窗表格。同样不可以

**Comment by kalepan** [comment]
我发现点击后没有少生成了html.
`<div id="modal-r14ac52BcF" class="modal fade Dcat_Admin_Widgets_Modal" role="dialog">`

**Comment by jqhph** [comment]
@kalepan @abovesky 确实有问题，已修复，感谢反馈，可以先更新开发分支代码
```
composer require dcat/laravel-admin:"2.0.x-dev"
```
