### ISSUE TITLE
数据表格导出, 提示Fetched导致一个错误

### ISSUE THREAD

**Issue by marktwovip** [jqhph/dcat-admin#815]
- Laravel Version: 7.24
- PHP Version: 7.4
- Dcat Admin Version: 2.0.11

### Description:
数据表格导出报错, 提示
Argument 2 passed to App\Admin\Controllers\XXX\XXXXController::App\Admin\Controllers\XXX\{closure}() must be an instance of Illuminate\Support\Collection, array given, called in /XXXX/vendor/dcat/laravel-admin/src/Grid/Concerns/HasEvents.php on line 29

这个位置的代码:

           $grid->listen(Grid\Events\Fetched::class, function ($grid, Collection $rows) {
                    $rows->transform(function ($row) {
                        $this->money    += $row['price'];
                        return $row;
                    });
                });

**Comment by jqhph** [comment]
改一下你的参数类型

**Comment by jqhph** [comment]
已修复，本周会发布新版本，感谢反馈
