### ISSUE TITLE
自定义上传、重定向失效

### ISSUE THREAD

**Issue by hedeqiang** [jqhph/dcat-admin#818]
- Laravel Version: 8.18.1
- PHP Version: 7.4.11
- Dcat Admin Version: 2.0.11-beta

### Description:
我想在上传文件成功之后进行页面跳转、刷新，使用重定向未生效

上传文件我自定义了控制器 `uploads/upload`
```php
$this->file('file', '表格文件') ->url('uploads/upload');
```

接着上传成功以后 我想重定向刷新发现并不会生效
```php
return redirect(url('admin/users'))->with(compact('success'));
```

但实际上 F12 看页面已经跳转了。

**Comment by hedeqiang** [comment]
php artisan admin 生成的 action ，重定向无法携带 with 

类似于如下
```php
$this->response()->redirect('users')->with('xxx');
```

**Comment by hedeqiang** [comment]
https://github.com/jqhph/dcat-admin/pull/828

**Comment by jqhph** [comment]
已合并，感谢！
