### ISSUE TITLE
#按需引入JS脚本,自己编写的页面首次点击时资源文件没有载入

### ISSUE THREAD

**Issue by ghost** [jqhph/dcat-admin#82]
- Laravel Version: 5.8.38
- PHP Version: 7.1.33
- Dcat Admin Version: 1.3.0

### Description:
按需引入JS脚本，自己编写的页面首次点击时 资源文件没有载入，需要进行手动刷新操作才可

### Steps To Reproduce:
RoomStatus.php
![图片](https://user-images.githubusercontent.com/24733751/81384958-120f8780-9145-11ea-8d8e-ccf282f8d104.png)
RoomStatusController.php
![图片](https://user-images.githubusercontent.com/24733751/81384985-2784b180-9145-11ea-87c8-a0ddd257820f.png)
view
![图片](https://user-images.githubusercontent.com/24733751/81385257-9d891880-9145-11ea-978c-803ffb70d6be.png)

**Comment by jqhph** [comment]
你的`view`代码有问题，不需要`html`、`head`和`body`，去掉`body`以及外面的标签就行了
