### ISSUE TITLE
如何定义复合主键

### ISSUE THREAD

**Issue by MrKaGod** [jqhph/dcat-admin#820]
公司有一张表为多主键，定义trait HasCompositePrimaryKey之后，增删改是没有问题，但是查询的到时候会报错
Argument 1 passed to Dcat\Admin\Repositories\Repository::setKeyName() must be of the type string or null, array given, called in /vendor/dcat/laravel-admin/src/Repositories/EloquentRepository.php on line 76

@jqhph 大大这该怎么解决

**Comment by jqhph** [comment]
后续版本会支持符合主键功能

**Comment by MrKaGod** [comment]
好吧，谢谢
