### ISSUE TITLE
表单 hasmany 如果$primaryKey 不是默认为id 保存数据就会一直新增

### ISSUE THREAD

**Issue by lvdoubaobao** [jqhph/dcat-admin#821]
- Laravel Version: 8.*
- PHP Version: 7.3
- Dcat Admin Version: 2.*

### Description:
表单的hasmany组件 例如定义
![image](https://user-images.githubusercontent.com/22880817/102000567-ac5f2b80-3d23-11eb-8eef-1d4ed7e972e4.png)

![image](https://user-images.githubusercontent.com/22880817/102000582-d6b0e900-3d23-11eb-83ea-c0fe420aa487.png)
![image](https://user-images.githubusercontent.com/22880817/102000586-e4ff0500-3d23-11eb-8460-7568b1058832.png)
如果$primaryKey='album_id'; 不是默认的id 保存一次表单room_album的数据就会翻盘生成 删除也无效

**Comment by lvdoubaobao** [comment]
我忙着赶工 暂时提交这个问题 以后我会查找原因

**Comment by jqhph** [comment]
```php
$form->hasMany('...', function ($form) {
    // 自定义主键名称
    $form->setRelationKeyName('...');

    ...
});
```

**Comment by lvdoubaobao** [comment]
> ```
> $form->hasMany('...', function ($form) {
>     // 自定义主键名称
>     $form->setRelationKeyName('...');
> 
>     ...
> });
> ```

thank you
