### ISSUE TITLE
如何根据字段值动态设置列表中行的背景颜色？

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#826]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.0.11

### Description:

使用行选择器 (rowSelector)的 
设置选中行的背景颜色
`$grid->rowSelector()->background(Admin::color()->dark20());`
看不到效果

$grid->rowSelector()->circle(false);//报错：Call to undefined method Dcat\Admin\Grid\Tools\RowSelector::circle()

请问有没有其他解决方案？

**Comment by jqhph** [comment]
```php
$grid->rows(function (Grid\Row $row) {
    if ($row->id = 10) {
        $row->setAttributes(['style' => 'background: #ddd']);
    }
 });
```

**Comment by zhaoshl** [comment]
非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jqhph/dcat-admin"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午5:17
收件人:&nbsp;"jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;;
抄送:&nbsp;"赵胜利"<77182507@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jqhph/dcat-admin] 如何根据字段值动态设置列表中行的背景颜色？ (#826)





 $grid-&gt;rows(function (Grid\Row $row) {     if ($row-&gt;id = 10) {         $row-&gt;setAttributes(['style' =&gt; 'background: #ddd']);     }  });

**Comment by zhaoshl** [comment]
> ```
> $grid->rows(function (Grid\Row $row) {
>     if ($row->id = 10) {
>         $row->setAttributes(['style' => 'background: #ddd']);
>     }
>  });
> ```

非常感谢！测试了一下，报一下错误：
`Argument 1 passed to App\Admin\Controllers\OfferCommodityController::App\Admin\Controllers\{closure}() must be an instance of Dcat\Admin\Grid\Row, instance of Illuminate\Support\Collection given, called in D:\phpstudy_pro\WWW\ant.test\vendor\dcat\laravel-admin\src\Grid.php on line 458`

**Comment by zhaoshl** [comment]
补充一下自己的解决办法，不知道是不是最佳的方案

**Comment by newbrash** [comment]
> 补充一下自己的解决办法，不知道是不是最佳的方案
> 
> ```
>             $grid->rows(function (Collection $rows) {
>                 $rows = $rows->each(function ($item, $key) {
>                     if ($item->flag) {
>                         $item->setAttributes(['style' => 'background: #ddd']);
>                     }
>                 });
>             });
> ```

是不是群主新版本改了

**Comment by newbrash** [comment]
> 补充一下自己的解决办法，不知道是不是最佳的方案
> 
> ```
>             $grid->rows(function (Collection $rows) {
>                 $rows = $rows->each(function ($item, $key) {
>                     if ($item->flag) {
>                         $item->setAttributes(['style' => 'background: #ddd']);
>                     }
>                 });
>             });
> ```

看了下源代码，这就是最佳的方案了，感谢
