### ISSUE TITLE
细节小建议：将 PerPageSelector 的样式由 dropdown 改变 dropup

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#829]
`PerPageSelector` 在低部，如果是 `dropdown` 样式，点击后，还需要滚动一下才能看到全部选项。。

我个人是建议使用 `dropup `样式。。

小弟看了一下源码 `PerPageSelector` 类中使用了 `Dropdown` 类生成选项 

小弟感觉要修改几个地方，修改难度很大。。。希望作者可以考虑在 `Grid` ，`PerPageSelector` 和 `Dropdown`  类中增加自定义 `options` 设置样式是`dropdown` 还是 `dropup`。

`The devil is in the details.`

**Comment by jqhph** [comment]
好的，感谢建议，后续版本会优化这个功能
