### ISSUE TITLE
hasMany hasManyTable cannot add new data 不能增加Data

### ISSUE THREAD

**Issue by lam0819** [jqhph/dcat-admin#830]
- Laravel Version: 8.0
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.11beta

### Description:

hasMany Table include hasManyTable/hasMany , 不能增加data

### Steps To Reproduce:

Example code :
$form->hasMany('duties', function (Form\NestedForm $form) {
                $form->hasMany('other_services', function (NestedForm $table) {
                    $table->text('name');
                    $table->currency('amount')->default(0)->symbol('$');
                })->useTable();
});

### Solution Suggest

1. add {{ $columnClass }}  to "add" and "remove"
2. use  $(document).on('click') instead of $(container).on('click')
3. need use $(this).parent().parent().parent() find upper table if #2 agree.

**Comment by jqhph** [comment]
hasMany目前是不支持嵌套使用的
