### ISSUE TITLE
Show - add "rows" relation field doesn't work, because there is already such method

### ISSUE THREAD

**Issue by shacky** [jqhph/dcat-admin#831]
- Laravel Version: 6.2
- PHP Version: 7.4
- Dcat Admin Version: 2.0.11-beta

### Description:
I've got defined relation named "rows" in model. I cannot add it to Show, because there is already the "rows" method in Show class, so "__call" method is not called. There is no public method for relations like we have "field" for adding fields. 

What we could do in Show class to fix it?

1. Create the public method "relation" as an alias to "handleRelationField".
2. Make the "handleRelationField" or the "call" method public.
3. Move code from the "call" method to the "field" method and use it everywhere... replace the "call" method references with "field".
4. ...... ?

As a workaround, I renamed the relation...

**Comment by jqhph** [comment]
```php
$show->relation('rows', function () {
     ...
});
```

**Comment by shacky** [comment]
Yes, indeed there is already such a method - I missed it. Thank you.
