### ISSUE TITLE
树状表格展开报错

### ISSUE THREAD

**Issue by izqx** [jqhph/dcat-admin#836]
- Laravel Version: 8.19.0
- PHP Version: 7.4.3
- Dcat Admin Version: 2.0.11

### Description:
点击标题展开时
`TypeError: Argument 1 passed to Symfony\Component\DomCrawler\Crawler::filter() must be of the type string, null given, called in D:\phpstudy_pro\WWW\blog-2\vendor\spatie\laravel-pjax\src\Middleware\FilterIfPjax.php on line 56 in file D:\phpstudy_pro\WWW\blog-2\vendor\symfony\dom-crawler\Crawler.php on line 748`

![图1](https://pic.downk.cc/item/5fd9cfde3ffa7d37b33cd1ce.png)

但是在F12网络请求栏直接点击这个报错的请求链接是可以正常出现内容的
![图2](https://pic.downk.cc/item/5fd9cffa3ffa7d37b33ceb84.png)

### Steps To Reproduce:
按照文档的方法操作的
![图3](https://pic.downk.cc/item/5fd9dab93ffa7d37b348c69c.png)

**已找到出错原因，和laravel-pjax有冲突，取消中间件`\Spatie\Pjax\Middleware\FilterIfPjax::class`后就可以正常展示了，大佬能否兼容下呢**

**Comment by Warrens-yg** [comment]
是数据问题吧，需要string类型接受到的是null

**Comment by izqx** [comment]
> 
> 
> 是数据问题吧，需要string类型接受到的是null

找到出错原因了，是那个laravel-pjax插件的问题，从中间件注释`\Spatie\Pjax\Middleware\FilterIfPjax::class`后列表就可以正常展示了

**Comment by izqx** [comment]
> 
> 
> laravel-pjax是做什么用的

网站前台我也想用Pjax方式加载就用了这个`laravel-pjax`依赖，但目前来看和树状表格有冲突唉，大佬能优化优化吗🙏

**Comment by jqhph** [comment]
后端路由别加载这个中间件就行了
