### ISSUE TITLE
异步加载表格操作数据

### ISSUE THREAD

**Issue by mateng1210** [jqhph/dcat-admin#837]
- Laravel Version: 6.2
- PHP Version: 7.2
- Dcat Admin Version: 1.7.7

### Description:
请问在异步加载表格，要怎么操作数据。没找到有示例。
如果自己实现 增删改的操作  要怎么刷新 弹窗表格数据。
![image](https://user-images.githubusercontent.com/24752917/102434670-32df7a00-4050-11eb-9308-332517369ab8.png)

**Comment by jqhph** [comment]
不支持
