### ISSUE TITLE
官方文档 2.x 中关于菜单翻译的问题

### ISSUE THREAD

**Issue by imzhi** [jqhph/dcat-admin#838]
- Laravel Version: 6.x
- PHP Version: 7.4
- Dcat Admin Version: 2.x

### Description:

链接：<http://www.dcatadmin.com/docs/2.x/quick-start.html#targeth3-2-6>

在``resources/lang/{当前语言}/admin.php``中

```php
...
// 用_小写并用_替换空格
'menu_titles' => [
    'work_units' => 'Unidades de trabajo'
],
```
按照这个步骤修改了，发现菜单的名称没有变化。

搜了已有的 issues <https://github.com/jqhph/dcat-admin/issues/641>，在 ``menu.php`` 的 ``titles`` 的索引进行新增就可以实现菜单翻译的效果。

请问要在哪里增加 ``menu_titles``？

### Steps To Reproduce:

**Comment by jqhph** [comment]
文档有点问题，2.0的菜单语言包是`resources/lang/{当前语言}/menu.php`
