### ISSUE TITLE
关于select2汉化问题

### ISSUE THREAD

**Issue by jianghang1995** [jqhph/dcat-admin#839]
- Laravel Version: Laravel Framework 8.18.1
- PHP Version: PHP 7.4.7 (cli)
- Dcat Admin Version: v2.0.11-beta

### Description:
汉化包中是带有select2.php,切app.php配置文件已经修改为中文配置
![image](https://user-images.githubusercontent.com/38677424/102465605-d2206380-4088-11eb-9d54-bf629b89e680.png)

**Comment by jqhph** [comment]
已修复，下个版本更新

**Comment by wantp** [comment]
修复方式该不是把select2.php 删掉了吧，所以select怎么做多语言？
