### ISSUE TITLE
数据统计卡片 希望增加时间组件、时间范围筛选

### ISSUE THREAD

**Issue by hedeqiang** [jqhph/dcat-admin#840]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
统计卡片 经常用到时间范围统计，希望增加这个时间范围组件

**Comment by jqhph** [comment]
好的

**Comment by hedeqiang** [comment]
感谢

**Comment by pyx02502** [comment]
请问题主问题解决了吗,想参考一下:joy:

**Comment by hedeqiang** [comment]
时间太久忘记了😂
