### ISSUE TITLE
表单字段动态显示问题

### ISSUE THREAD

**Issue by zsboss** [jqhph/dcat-admin#841]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
$form->radio('radio')
    ->when([1, 4], function (Form $form) {
        // 值为1和4时显示文本框
        $form->text('text1');
        $form->text('text2');
        $form->text('text3');
    })
    ->when(2, function (Form $form) {
        $form->text('text4')->required();
    })
    
    ->options([
        1 => '显示文本框',
        2 => '显示编辑器',
        3 => '显示文件上传',
        4 => '还是显示文本框',
    ])
    ->default(1);
当选择radio等于1的时候  提交表单会报 text4 没有填写， 按正常radio等于2的时候 表单是隐藏状态

**Comment by jqhph** [comment]
需要使用laravel的`required_if`进行验证
