### ISSUE TITLE
树状表格子分类无数据报错！

### ISSUE THREAD

**Issue by black-wind-wu** [jqhph/dcat-admin#843]
- Laravel Version: 8.18.1
- PHP Version: 7.2.9
- Dcat Admin Version: 2.0.11-beta

### Description:
使用树状表格，如果子分类下无数据，报错NotFoundHttpException In Application.php line 1068 
\vendor\dcat\laravel-admin\src\Grid\Concerns\HasTree.php的enableTree方法内的
**`abort(404)`**
修改为

**`return;`**

**Comment by jqhph** [comment]
已优化这个功能
