### ISSUE TITLE
在model::with的情况下filter的到addBinding中的value会变成数组

### ISSUE THREAD

**Issue by FrigidCrow** [jqhph/dcat-admin#844]
- Laravel Version: 7+
- PHP Version: 7+
- Dcat Admin Version: 2.0.11

### Description:
`$this->deviceModel = Device::with(['deviceStatus', 'deviceClass', 'customer']);`
model存在with的情况
`$grid->column('deviceStatus.device_status_name', admin_trans(self::$device_lang . 'fields.device_status_name'))->filter(Grid\Column\Filter\Equal::make()->valueFilter());`

这里使用deviceStatus里的device_status_name, 在filter的时候报错

`trim() expects parameter 1 to be string, array given`

检查了一下, 在vendor/dcat/laravel-admin/src/Grid/Column/Filter/Equal.php里面的addBinding($value, Model $model)这个方法中$value的需要的值是字符串, 上面deviceStatus.device_status_name的值传进去就会变成[0 => 'value']这类数组.

但是用正常非with的列filter就没有问题

**Comment by jqhph** [comment]
类似的代码没有复现出来

**Comment by FrigidCrow** [comment]
我在Device里面写的是, 可能是这块有影响?
`    public function deviceStatus(){
        return $this->hasOne(DeviceStatus::class, 'device_status_id', 'device_status_id');
    }`

**Comment by jqhph** [comment]
没有影响
