### ISSUE TITLE
数据表格事件和导出冲突

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#846]
- Laravel Version: 7.30.0
- PHP Version: 7.2
- Dcat Admin Version: 2.0.11-beta

### Description:
请教下。 表格使用了“数据表格事件”
![image](https://user-images.githubusercontent.com/16422689/102594981-da22e680-410e-11eb-8927-a072e9b612dc.png)

这个， 导出excel就会报错，有什么办法可以解决吗？ 我注释掉表格事件代码，就可以正常导出
![image](https://user-images.githubusercontent.com/16422689/102595012-e3ac4e80-410e-11eb-90c6-474c92c9b5aa.png)

**Comment by jqhph** [comment]
这个问题已经修复，可以先更新2.0开发分支代码或等待新版本发布
