### ISSUE TITLE
表单提交--动态表单问题

### ISSUE THREAD

**Issue by alvin-mxl** [jqhph/dcat-admin#847]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:

```php
$form->select('cate_pid','全部分类')
->when([1,2], function (Form $form) use ($xxx){
$form->select('cate_id','xxx')
->when([5], function (Form $form) {

                    })
                    ->when([6], function (Form $form) {
                     
                    })
                    ->options($xxx);
            })
->when([3,5], function (Form $form) use ($xxx){
$form->select('cate_id','xxx')
->when([12], function (Form $form) {

                    })
                    ->when([16], function (Form $form) {
                     
                    })
                    ->options($xxx);
            })
->options($cate_pids);
```
麻烦问下：这种表单字段动态显示，在编辑的时候，怎么能让它自己根据字段值自动展开，比如数据中cate_id为12，在点击编辑后会自动显示 ->when([12], function (Form $form) {})下的模块

而且在实际使用中，经常会出现第二层的cate_id拿不到值，保存时打印一直是null,有时间又是好的。cate_pid没有任何问题。

**Comment by jqhph** [comment]
不能有同样字段名的字段，第二个`cate_id`需要换个名称，表单动态显示只是控制表单显示或隐藏

**Comment by alvin-mxl** [comment]
> 不能有同样字段名的字段，第二个`cate_id`需要换个名称

嗯嗯 。



> 表单动态显示只是控制表单显示或隐藏

那就没有办法实现了吗？可以可以通过自己写js手动触发下select事件，如果可以form方法里需要怎么写才行，好像直接写不会执行

**Comment by alvin-mxl** [comment]
![image](https://user-images.githubusercontent.com/44891395/102685059-b0ee7d00-4218-11eb-8c30-0b2f5ecae513.png)

这样好像可以  我先自己试试

**Comment by alvin-mxl** [comment]
是我的问题，本身就能动态显示出来。
