### ISSUE TITLE
表单提交--分布表单问题

### ISSUE THREAD

**Issue by alvin-mxl** [jqhph/dcat-admin#849]
分布表单提交，我想在点击下一步后，获取到上一步输入的值，然后以此显示不同的表单字段。求告知怎么能获取到

**Comment by alvin-mxl** [comment]
不管是打开->remember()，在下一步中request()->getSession()->all() 还是直接request()->all(),都拿不到。

**Comment by jqhph** [comment]
开启`remember`之后可以通过`session()->all()`获取到上一步数据，未开启`remember`则需要通过`request()->all()`获取

**Comment by alvin-mxl** [comment]
![image](https://user-images.githubusercontent.com/44891395/103001757-942fad80-4568-11eb-9419-3f3045ce522e.png)
不行啊   不管是用哪种方法，取到的只是这样的。并没有上一个页面表单输入的值。

**Comment by alvin-mxl** [comment]
需要拿到的是像这种值
![image](https://user-images.githubusercontent.com/44891395/103001979-07d1ba80-4569-11eb-9f00-9738c53cb5e8.png)
这种值，直接点下一步，是拿不到的。这里拿到的操作是：在下一步中打断点，上一步中输完内容，点击一次下一步，出现第一张图的打印，再次点击下一步，才会出现此图的内容，也就是需要的结果

**Comment by alvin-mxl** [comment]
![image](https://user-images.githubusercontent.com/44891395/103002422-db6a6e00-4569-11eb-8c2b-94c832e8ccd9.png)

代码如上
