### ISSUE TITLE
form表单编辑图片必须先删除才能重新上传吗

### ISSUE THREAD

**Issue by zljpz** [jqhph/dcat-admin#85]
- Laravel Version: 6.18.13
- PHP Version: 7.2.4
- Dcat Admin Version: 1.3.0

### Description:
1、form表单如何选中图片自动上传？或者直接提交表单的时候自动上传图片
2、标记带图片的记录的时候，如何直接替换图片，难道必须删除图片然后才能重新上传，如果图片字段非空，就会只删了图片，然后代码报错（原因：图片字段不能为null）

**Comment by jqhph** [comment]
1. 不支持
2. 保存值可以通过类似以下方式解决
```
$form->image('xxx')->saving(function ($v) {
    return (string) $v;
})
```
替换图片
```php
$form->image('xxx')->disableRemove();
```
你说的这些文档全都有，请仔细看文档

**Comment by zljpz** [comment]
如果要实现提交表单的时候，先自动上传图片，是不是只能注入js，通过js来模拟点击上传实现呢？

**Comment by jqhph** [comment]
> 如果要实现提交表单的时候，先自动上传图片，是不是只能注入js，通过js来模拟点击上传实现呢？

这个功能我可以后续加上
