### ISSUE TITLE
勾选继续创建后页面变成404

### ISSUE THREAD

**Issue by krvipsoft** [jqhph/dcat-admin#850]
- Laravel Version: 8.19
- PHP Version: 7.3
- Dcat Admin Version: 2.0.11

创建数据时，勾选继续创建，点击提交，跳转地址错误
![image](https://user-images.githubusercontent.com/42866392/102716589-2b55f480-4320-11eb-8f3b-420cd4685246.png)
看了代码
![image](https://user-images.githubusercontent.com/42866392/102716605-46c0ff80-4320-11eb-95ad-a9059eaa0953.png)
变成
![image](https://user-images.githubusercontent.com/42866392/102716614-56404880-4320-11eb-9871-c77bcd4b82b0.png)
是个bug吗？，可以修改下吗？

**Comment by krvipsoft** [comment]
我看bug已经修改，什么时候更新包

**Comment by jqhph** [comment]
今天或明天发布新版本
