### ISSUE TITLE
Multiple Select Table 带翻页的情况，选择不同页面的内容丢失

### ISSUE THREAD

**Issue by gantoday** [jqhph/dcat-admin#851]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
Multiple Select Table 功能，如果我有两页内容，在第一页选择一个，然后翻页到第二页再选择一个。提交保存，只能保存第二页选择的内容，第一页的内容因为翻页丢失了。

### Steps To Reproduce:
在dcat官方的演示中也存在这种情况，可以直接复现：
http://103.39.211.179:8080/admin/form
![image](https://user-images.githubusercontent.com/7780154/102730997-88c66180-4371-11eb-96c7-31250a44976b.png)

**Comment by gantoday** [comment]
感谢开发者关注。
开发者给这个issue添加了enhancement 标签，我觉得这个不是增强，是bug呢？
请问 selectResource 会有这个情况吗。
在准备换成 selectResource 试一试。

**Comment by jqhph** [comment]
感谢反馈，已增加这个功能，本周会发布新版本，也可以先更新开发分支代码

```
composer require dcat/laravel-admin:"2.0.x-dev"
```

**Comment by gantoday** [comment]
非常感谢
