### ISSUE TITLE
使用表格选择器后提交表单报错405

### ISSUE THREAD

**Issue by abovesky** [jqhph/dcat-admin#852]
- Laravel Version: 8.12
- PHP Version: 7.3.9
- Dcat Admin Version: 2.0.11-beta

### Description:
使用表格选择器后提交表单报405错误，去掉后提交表单就正常

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/5986216/102734136-0ee6a600-437a-11eb-9792-5a1282a33707.png)
![image](https://user-images.githubusercontent.com/5986216/102734171-24f46680-437a-11eb-9535-c28fc2a699ed.png)
报错：
![image](https://user-images.githubusercontent.com/5986216/102734232-4b1a0680-437a-11eb-9dcf-50e52e531db6.png)
提交的form data其他字段都不见了，只剩一个multipleSelectTable的字段elements
![image](https://user-images.githubusercontent.com/5986216/102734834-c7611980-437b-11eb-85d0-892eaf3aa02a.png)

**Comment by jqhph** [comment]
提交的url是？

**Comment by abovesky** [comment]
> 提交的url是？

POST  /admin/sections/1
url是正常的

**Comment by jqhph** [comment]
贴上表单完整代码

**Comment by abovesky** [comment]
> 贴上表单完整代码

![image](https://user-images.githubusercontent.com/5986216/102737088-6d635280-4381-11eb-817a-b00ba33a50e9.png)

**Comment by jqhph** [comment]
没有复现这个问题

**Comment by abovesky** [comment]
找到原因了，我把关联名称改一下然后可以了，可能哪里有冲突吧
![image](https://user-images.githubusercontent.com/5986216/102749072-4f581b00-439e-11eb-9f51-25880b6e6a19.png)

**Comment by jqhph** [comment]
好的
