### ISSUE TITLE
用了hasmany的表单在不知道什么原因的情况下提交的时候会跳转到详情，应该是跳转到index才对

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#854]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 2.0.11-beta
有点奇怪的问题

**Comment by Warrens-yg** [comment]
等下个版本我更新之后再看看

**Comment by jqhph** [comment]
这个问题已经修复，感谢反馈
