### ISSUE TITLE
map修改为百度地图出现的问题

### ISSUE THREAD

**Issue by kuki1994** [jqhph/dcat-admin#856]
- Laravel Version: 7.4
- PHP Version: 7.4
- Dcat Admin Version: 1.7.7

Description:
  修改了admin.php里面的map_provider的值，改为baidu
  .env设置BAIDU_MAP_API_KEY
  key都是最新设置的，也设置了域名白名单，还是一直提示百度未授权

**Comment by jqhph** [comment]
已修复，今晚发布新版本
