### ISSUE TITLE
怎样在表单文本框后面增加按钮

### ISSUE THREAD

**Issue by krvipsoft** [jqhph/dcat-admin#857]
![image](https://user-images.githubusercontent.com/42866392/102843501-ac120f00-444c-11eb-9c81-497c846eee58.png)
如图所示，可以说下用dcat怎么实现吗？

**Comment by jqhph** [comment]
参考文档表单字段管理章节

**Comment by krvipsoft** [comment]
能告诉下具体链接吗？没有找到呢？

**Comment by jqhph** [comment]
仅仅只是按钮的话可以通过`append`方法实现

```php
$form->text(...)->append(...);
```
