### ISSUE TITLE
分步表单的问题，提示 Field type [ multipleSteps ] does not exist .

### ISSUE THREAD

**Issue by WPTomo** [jqhph/dcat-admin#858]
- Laravel Version: 8.0.1
- PHP Version: 7.4
- Dcat Admin Version: 2.0.11

### Description:
按照如下文档示例编写内容

```php
$form->multipleSteps()->add('标题', function (Form\StepForm $step) {

    $step->text('username')->rules('required');

    ...
});
```

报错

`Field type [ multipleSteps ] does not exist .`

**Comment by jqhph** [comment]
分步表单是插件，需要单独安装 https://github.com/dcat-admin/form-step

**Comment by forwells** [comment]
@jqhph 大哥 分步表单是不是不能用在异步的工具表单中
