### ISSUE TITLE
php 8.0 情况下 报 must be passed by reference, value given

### ISSUE THREAD

**Issue by hongbinhsu** [jqhph/dcat-admin#859]
- Laravel Version: 8.12
- PHP Version: 8.0
- Dcat Admin Version:  v2.0.11-beta

### Description:
/admin/auth/users 等页面时，出现
ErrorException
Dcat\Admin\Support\Helper::Dcat\Admin\Support\{closure}(): Argument #1 ($text) must be passed by reference, value given

Illuminate\Foundation\Bootstrap\HandleExceptions::handleError
vendor/dcat/laravel-admin/src/Support/Helper.php:330

![image](https://user-images.githubusercontent.com/1223271/102849133-728fd280-4451-11eb-8a41-d3668367a46a.png)

### Steps To Reproduce:
同样的扩展，在php7.4情况下则无此报错；本次测试使用docker-compose 
切换成bincent/php:7.4-fpm-alpine 则无报错， 两个版本的区别在于dockerfile 如下：
bincent/php:8.0-fpm-alpine dockerfile
FROM php:8.0-fpm-alpine

bincent/php:7.4-fpm-alpine dockerfile
FROM php:7.4-fpm-alpine

docker-compose 内容
version: '3' 
services:
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: always 
        volumes:  
            - ./src:/var/www/html
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - php-fpm
        ports: 
            - "80:80/tcp"
            - "443:443/tcp"
    php-fpm:
        image: bincent/php:8.0-fpm-alpine （）
        container_name: php-fpm
        restart: always 
        volumes:  
            - ./src:/var/www/html
        ports:  
            - "9000:9000/tcp"
            -

**Comment by hongbinhsu** [comment]
通过排查发现，preg_replace_callback 回调函数中使用引用地址时都会报错

**Comment by jqhph** [comment]
是的，这个问题已修复，今晚发布新版本
