### ISSUE TITLE
The Url must be an image

### ISSUE THREAD

**Issue by outer199** [jqhph/dcat-admin#863]
- Laravel Version: 6.20.5
- PHP Version: 7.2
- Dcat Admin Version: 2.0.10-beta

### Description:
上传 `.jpg` 图片 报错: The Url must be an image

**Comment by LeeDawson** [comment]
我也遇上了这个坑。我是直接下载官网的demo. 这个demo的版本是 laravel-admin 5.8。这个bug是laravel的validate的锅，升级一下就好了，后面的再有趟坑的可以参考

**Comment by ximengnaikang** [comment]
同遇到这个问题，我是创建了软连接，之后遇到的，正在排查....
