### ISSUE TITLE
如何解决 laravel 未登录状态 Ajax 请求出现 “CSRF token mismatch.” 错误！

### ISSUE THREAD

**Issue by moxuanyuan** [jqhph/dcat-admin#866]
- Laravel Version: 8.17.1
- PHP Version: 7.4.8
- Dcat Admin Version: 1.7.7

### Description:
laravel 未登录状态 Ajax 请求出现 “CSRF token mismatch.” 错误！这个会影响到 dcat 工具表单提交。例如，同时打开两个页面，一个页面中有工具表单，在另一个页面登出，然后切回工具表单页面，提交后，会提示“419 error”，并没有跳转到登陆页面。
learnku论坛上有两个相关贴子https://learnku.com/laravel/t/32467 ，https://learnku.com/laravel/t/32701
按贴子提到的方法，好似没有效果。其中一个方法是在 `App\Http\Kernel.php` 的 `$middlewareGroups` 数组中添加 `\App\Http\Middleware\Authenticate::class`，并放在 `\App\Http\Middleware\VerifyCsrfToken::class` 前，会导至重定向过多。

**Comment by jqhph** [comment]
无法解决，登录会清空session，必然导致419，除非你禁用csrf验证
