### ISSUE TITLE
扩展仓库不存在，显示404

### ISSUE THREAD

**Issue by Abbotton** [jqhph/dcat-admin#87]
rt,扩展仓库什么时候启用？
https://github.com/dcat-admin-extensions

**Comment by jqhph** [comment]
好的，我今天晚上开一下，感谢支持

**Comment by Abbotton** [comment]
好的，最好再建一个微信交流群，我认识的研发用QQ的真的很少了，感谢。

**Comment by jqhph** [comment]
> 好的，最好再建一个微信交流群，我认识的研发用QQ的真的很少了，感谢。

好的，后面会建一个
