### ISSUE TITLE
升级出现错误 Indirect modification of overloaded element of App\User has no effect

### ISSUE THREAD

**Issue by ceo404** [jqhph/dcat-admin#870]
以下是我的代码 Demo

`protected function grid()
    {
        return Grid::make(User::with(['Test', 'Test1']), function (Grid $grid) {
            $grid->model()->where('type', '!=', 13);
            $grid->column('id')->sortable();

            $grid->column('name', "用户名")->expand(function ($grid) {
                return Table::make();
            });
            $grid->column('type', '类型')->using([
                0 => 'Null',
                11 => 'Null',
            ])->label();

            $grid->column('Test.type', '测试版本')->select([
                0 => 'Null',
                1 => 'Null',
            ], true)->width('6%')->help('商户所属版本');
            $grid->column('Test.num', '测试数量')->editable()->help('测试数量');
            $grid->column('Test1.online', '测试状态')->select([
                1 => 'Null',
                2 => 'Null'
            ]);

            $grid->column('Test.expired_time', '测试到期时间')->display(function ($expired_time) {
                if ($expired_time) {
                    if (strtotime($expired_time) < time()) {
                        return '<span class="label" style="background:#ea5455">' . $expired_time . '</span>';
                    }
                    return '<span class="label" style="background:#21b978">' . $expired_time . '</span>';
                }
                return '';

            })->width('7%');

            $grid->column('create_date', '测试创建时间')->display(function ($create_date) {
                if ($create_date != 0) {
                    return date('Y-m-d H:i:s', $create_date);
                }
                return '';
            })->width('7%');
            $grid->column('update_date', '测试更新时间')->display(function ($update_date) {
                if ($update_date != 0) {
                    return date('Y-m-d H:i:s', $update_date);
                }
                return '';
            })->width('7%');

            $grid->filter(function (Grid\Filter $filter) {
                $filter->like('name', '测试用户名');
                $filter->equal('type', '测试类型')->select([
                    11 => 'Null',
                ]);
            });

            //添加自定义按钮
            $grid->actions(function (Grid\Displayers\Actions $actions) {
                $actions->append('<a href="' . admin_url("test?id=" . $this->id) . '" style="cursor: pointer"><i class="fa fa-address-book-o" style="padding-right: 10px;"></i> 测试</a>');
            });
            $grid->disableCreateButton();

        });`

**Comment by ceo404** [comment]
@jqhph 大佬麻烦解答一下

**Comment by jqhph** [comment]
这个问题已修复，请先更新`2.0`开发分支代码，晚上会发布一个修复版本
```
composer require dcat/laravel-admin:"2.0.x-dev"
```
