### ISSUE TITLE
2.0.13 display显示异常

### ISSUE THREAD

**Issue by vip68** [jqhph/dcat-admin#876]
- Laravel Version: 8.11
- PHP Version: 7.4.13
- Dcat Admin Version: 2.0.13

### Description:

在下面这个操作中，调用display时，只要有字符串进行拼接，就会把$this->CreateDate给全部展示出来，而在2.0.12之前的版本则无此bug。

- 2.0.13的bug代码：
```
$grid->column('create_user.Name',)->display(function ($name) {
                return $name . '<br/>' . $this->CreateDate;
            });
```
![bug](https://user-images.githubusercontent.com/28476744/103017817-1aef8500-457f-11eb-9bef-14843ff81787.png)

- 去掉字符串拼接，显示正常，但这样不满足需求
```
            $grid->column('create_user.Name', trans('product-package.fields.CreateLog'))->display(function ($name) {
                return $this->CreateDate;
            });
```
![normal](https://user-images.githubusercontent.com/28476744/103018329-06f85300-4580-11eb-99a6-d6eda5b5987c.png)

**Comment by jqhph** [comment]
已修复，更新2.0开发分支代码
