### ISSUE TITLE
关联表显示图标bug

### ISSUE THREAD

**Issue by vip68** [jqhph/dcat-admin#878]
- Laravel Version: 8.11
- PHP Version: 7.4.13
- Dcat Admin Version: 2.0.13

### Description:
* 关联表显示图标bug，图标时而能正常显示，时而显示异常，查看页面源码，显示异常的位置图片路径为空，或者错乱。
* 而2.0.12之前的版本显示正常
```
    protected function grid()
    {
        return Grid::make(new ProductPackage(['create_user', 'modify_user', 'program_app']), function (Grid $grid) {
            $grid->model()->orderByDesc('ID');
            $grid->fixColumns(3);

            $grid->column('ID')->sortable();
            $grid->column('program_app.Logo')->image();
    }
```
![WX20201224-012142](https://user-images.githubusercontent.com/28476744/103022273-9f91d180-4586-11eb-8577-31af4d32b3d3.png)

**Comment by jqhph** [comment]
无图片的html是怎么样的，复制html元素看看

**Comment by vip68** [comment]
> 无图片的html是怎么样的，复制html元素看看

* 异常代码
![WX20201224-092633](https://user-images.githubusercontent.com/28476744/103048605-25833c00-45ca-11eb-9123-f44a2d7a7fa9.png)

![WX20201224-092536](https://user-images.githubusercontent.com/28476744/103048567-02588c80-45ca-11eb-9da6-9316269d6381.png)

* 这是不加->image()，当做文本显示的内容
![WX20201224-092040](https://user-images.githubusercontent.com/28476744/103048392-6fb7ed80-45c9-11eb-9873-be3c89770d80.png)

**Comment by vip68** [comment]
```html
<td>
                                        <img data-action="preview-img" src="http://localhost/storage/<img data-action=" preview-img'="" style="max-width:200px;max-height:200px;cursor:pointer" class="img img-thumbnail">' style='max-width:200px;max-height:200px;cursor:pointer' class='img img-thumbnail' /&gt;
                                    </td>
```

```html
<td>
                                        <img data-action="preview-img" src="http://localhost/storage/<img data-action=" preview-img'="" style="max-width:200px;max-height:200px;cursor:pointer" class="img img-thumbnail">' style='max-width:200px;max-height:200px;cursor:pointer' class='img img-thumbnail' /&gt;' style='max-width:200px;max-height:200px;cursor:pointer' class='img img-thumbnail' /&gt;
                                    </td>
```

**Comment by jqhph** [comment]
跟 #876 是同个问题，更新2.0开发分支代码再试试
