### ISSUE TITLE
表单动态显示功能在工具表单中无效

### ISSUE THREAD

**Issue by kpsanmao** [jqhph/dcat-admin#879]
- Laravel Version: 6.19.1
- PHP Version: 7.3.4
- Dcat Admin Version: 2.0.13beta

### Description:
表单动态显示功能在工具表单中无效，代码如下：

### Steps To Reproduce:
`public function form()
    {   
        $options = [1 => '显示文本框',2 => '显示编辑器',3 => '显示文件上传',4 => '还是显示文本框',];
        $this->select('select')->when([1, 4], function () {
            $this->text('text1');
            $this->text('text2');
            $this->text('text3');
        })->when(2, function () {
            $this->editor('editor');
        })->when(3, function () {
            $this->image('image');
        })
        ->options($options);
    }`
![11](https://user-images.githubusercontent.com/17693832/103056475-02f81f80-45d8-11eb-8f1a-ede7e852dabe.png)

**Comment by kpsanmao** [comment]
`public function form()
    {   
        $options = [1 => '显示文本框',2 => '显示编辑器',3 => '显示文件上传',4 => '还是显示文本框',];
        $this->select('select')->when([1, 4], function () {
            $this->text('text1');
            $this->text('text2');
            $this->text('text3');
        })->when(2, function () {
            $this->editor('editor');
        })->when(3, function () {
            $this->image('image');
        })
        ->options($options);
    }``

**Comment by jqhph** [comment]
已修复，请先更新2.0开发分支代码 

```
composer require dcat/laravel-admin:"2.0.x-dev"
```

**Comment by kpsanmao** [comment]
> 已修复，请先更新2.0开发分支代码
> 
> ```
> composer require dcat/laravel-admin:"2.0.x-dev"
> ```

收到，谢谢。

**Comment by liaoshengping** [comment]
@jqhph 如果点击到别的菜单是，再进入动态表单还是会出现这种问题，如果把pajax关了就可以，这个要怎么排查？

v2.2.2-beta

![image](https://github.com/jqhph/dcat-admin/assets/24541157/421b7059-8688-4610-b9cc-731631ba781a)
