### ISSUE TITLE
数据表格中列展示下面的 expand 方法导致页面异常

### ISSUE THREAD

**Issue by carlosxu312** [jqhph/dcat-admin#881]
- Laravel Version: 8.13.0
- PHP Version: 7.4.10
- Dcat Admin Version: 2.0.12-Beta

### Description:
使用 `expand` 方法时，页面数据丢失，页面布局混乱

### Steps To Reproduce:
出错页面截图：
![image](https://user-images.githubusercontent.com/25150352/103070854-5fba0100-45fd-11eb-9ff7-4422a544be76.png)
未加 `expand` 方法页面截图：
![image](https://user-images.githubusercontent.com/25150352/103071042-d22ae100-45fd-11eb-8e56-6fb2b8e67fc5.png)

相关代码：
```php
$grid->column('id')->sortable();
$grid->column('wechatUser.realname', '真实姓名');
$grid->column('certification_info', '认证资料')
    ->display('点击查看')
    ->expand(function () {
        $card = new Card(null, $this->certification_info);
        return "<div style='padding:10px 10px 0'>$card</div>";
    });
$grid->column('verify_status')
```

**Comment by jqhph** [comment]
`$this->certification_info`这个里面是什么内容？估计是不完整的HTML字符串
