### ISSUE TITLE
表单更新图片时报错,要加上：use Illuminate\Support\Arr;

### ISSUE THREAD

**Issue by running8gubin** [jqhph/dcat-admin#882]
- Laravel Version: 8.20.#
- PHP Version: 7.4.#
- Dcat Admin Version: 1.7.8

### Description:
表单更新图片时报错：
 Class 'Dcat\Admin\Form\Concerns\Arr' not found {"exception":"[object] (Error(code: 0): Class 'Dcat\\Admin\\Form\\Concerns\\Arr' not found at /mnt/www/cloud-time.marathon8.com/vendor/dcat/laravel-admin/src/Form/Concerns/HasFiles.php:199)
### Steps To Reproduce:
找到这个文件，然后加上：
use Illuminate\Support\Arr;

建议在下一版本中加上这个...

**Comment by jqhph** [comment]
感谢顾叔反馈，可以先更新master分支代码

```
composer require dcat/laravel-admin:"dev-master"
```
