### ISSUE TITLE
表单block布局情况下 使用表单字段动态显示报错

### ISSUE THREAD

**Issue by xumingpeng** [jqhph/dcat-admin#885]
- Laravel Version: 7.29
- PHP Version: 7.3.4
- Dcat Admin Version: 2.0.14-beta

### Description:

数据表单 使用 block 表单布局 使用表单字段动态显示 报错如下：
Argument 1 passed to App\Admin\Controllers\GoodsAptitudeController::App\Admin\Controllers\{closure}() must be an instance of Dcat\Admin\Form, instance of Dcat\Admin\Form\BlockForm given

### Steps To Reproduce:

protected function form()
    {
        return Form::make(new GoodsAptitude(), function (Form $form) {
            $form->block(8, function (Form\BlockForm $form) {
                $form->radio('radio')->when(1, function (Form $form) {
                    $form->text('text1');
                    $form->text('text2');
                    $form->text('text3');
                })
                    ->when(2, function (Form $form) {
                        $form->editor('editor');
                    })
                    ->when(3, function (Form $form) {
                        $form->image('image');
                    })
                    ->options([
                        1 => '未处理',
                        2 => '已处理',
                        3 => '已拒绝',
                    ])
                    ->default(1);
            
            });
        });
    }

**Comment by jqhph** [comment]
参数限制类型不对
