### ISSUE TITLE
兄嘚，官网挂了……

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#889]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
[Dcat Admin官网](http://www.dcatadmin.com)正在进行备案中，在备案期间会关闭网站访问，直至备案完成。在此期间大家可以通过[Learnku中文文档](https://learnku.com/docs/dcat-admin/2.x)查看文档，给大家带来的不便之处敬请谅解，谢谢支持！
