### ISSUE TITLE
官网备案暂停访问，文档查看请前往https://learnku.com/docs/dcat-admin/2.x

### ISSUE THREAD

**Issue by jqhph** [jqhph/dcat-admin#890]
大家好，[Dcat Admin官网](http://www.dcatadmin.com)正在进行备案中，在备案期间会关闭网站访问，直至备案完成。在此期间大家可以通过[Learnku中文文档](https://learnku.com/docs/dcat-admin/2.x)查看文档，给大家带来的不便之处敬请谅解，谢谢支持！

**Comment by faydanube** [comment]
…… 這是在哪備案，用了這麼久。。。

**Comment by anhao** [comment]
…… 這是在哪備案，用了這麼久。。。

**Comment by leslieeilsel** [comment]
…… 這是在哪備案，用了這麼久。。。
