### ISSUE TITLE
multipleSelectTable 翻页无法选中，只能选中当前页

### ISSUE THREAD

**Issue by LEUNGHOTIN** [jqhph/dcat-admin#891]
- Laravel Version: 8.14.0
- PHP Version: 7.3.11
- Dcat Admin Version: 2.0.14

### Description:
表格选择器多选multipleSelectTable，翻页之后就选不上了，只能选中当前页的

**Comment by jqhph** [comment]
#851

**Comment by LEUNGHOTIN** [comment]
> #851

2.0 不是废弃了 selectResource 么？

**Comment by jqhph** [comment]
是的，你这个问题有人反馈过了，后续会优化

**Comment by LEUNGHOTIN** [comment]
好的，十分感谢
