### ISSUE TITLE
前后台路由命名重复，希望后台的命名路由也能自动增加 admin_prefix 前缀

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#892]
![image](https://user-images.githubusercontent.com/8817046/103252977-18938d80-49ba-11eb-8ccb-5e1cf8a0acd5.png)

**Comment by lilashih** [comment]
自己在路由裡用group加上就好了 彈性比較大 我反而不希望加到dcat裡

**Comment by faydanube** [comment]
> 自己在路由裡用group加上就好了 彈性比較大 我反而不希望加到dcat裡

不是個人解決不掉，默認零配置的情況下，命名衝突的確算一個問題。
