### ISSUE TITLE
「BUG」默認 Editor，內容清空時，保存結果不生效「刪除全部內容，保存後內容未刪除」

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#895]
![image](https://user-images.githubusercontent.com/8817046/103257801-af1d7a00-49cd-11eb-9f0a-14473ade5c87.png)

**Comment by jqhph** [comment]
你用的是什么版本？

**Comment by faydanube** [comment]
> 你用的是什么版本？

2.0.14-beta

**Comment by faydanube** [comment]
> 你用的是什么版本？

剛剛直接新建項目，並且全部用默認配置，依然可以觸發此 BUG，清空編輯器內容，保存，存入數據庫的該字段值並沒有被清空，而是保持之前的值。

**Comment by faydanube** [comment]
debug: vendor\dcat\laravel-admin\src\Form.php
有內容時提交：
![image](https://user-images.githubusercontent.com/8817046/103317837-64e8d700-4a67-11eb-9adb-2b13712b2291.png)
清空後提交：
![image](https://user-images.githubusercontent.com/8817046/103317879-8d70d100-4a67-11eb-97ef-0fcc649c23ba.png)

**Comment by faydanube** [comment]
> 你用的是什么版本？
解決了一個多小時，一直在看編輯器官網……最後發現是 dcat 初始化代碼的問題。
可以通過如下方式解決：
注釋掉 vendor\dcat\laravel-admin\resources\views\form\editor.blade.php 中：
```js
  // if (! content) {
  //     content = e.level.fragments;
  //     content = content.length && content.join('');
  // }
```

希望歐哲修復此問題後提交新版本並關閉這個 comment，非常感謝，作者大大辛苦。

**Comment by jqhph** [comment]
好的，你可以先自己重写下这个组件，这个代码还有其他用处，我想想怎么兼容
