### ISSUE TITLE
Unable to hide grid columns

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#896]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: 2.0

### Description:

i can't hide column be default

`
 $grid->column('shipping_category_id', 'Category')->display(function () {
                return $this->category_name;
            })->hide();
`

**Comment by jqhph** [comment]
```php
$grid->showColumnSelector();

$grid->hideColumns(['field1', ...]);
```

**Comment by chiwex** [comment]
thank you. solved the problem
