### ISSUE TITLE
一个页面里面放了两个列表，分页出现混乱，请问有没有好的解决方法，谢谢

### ISSUE THREAD

**Issue by xiajinjun** [jqhph/dcat-admin#898]
- Laravel Version: 7.#.#
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.#
- 
### Description:
请教一下我在一个页面里面放了两个列表，结果分页出现混乱，出错。

页面如下：
——————————————————————————————————————
列表1
A B C D E F G
A B C D E F G
A B C D E F G
A B C D E F G
第一页，第二页

Tab里面的列表
列表2
1 2 3 4 5 6 7
1 2 3 4 5 6 7
第一页，第二页
——————————————————————————————————————
点下面列表2的第二页，会跳到列表1的第二页。

代码如下：

class ProjectController extends AdminController
{
	protected $project_id;

	public function index(Content $content)
    {

        return $content
            ->title('项目管理')
            ->body($this->grid())
            ->body($this->build())
            ->body(function (Row $row) {
                $row->column(12, function (Column $column) {
                   $column->row(new Card(new SubProjectSetting()));
                });
            });
    }
    protected function grid()
    {
        return Grid::make(new Project(), function (Grid $grid) {
......
 });

....

SubProjectSetting.class：

$this->tab('清单', function (Form $form) {
            
            $content=Grid::make(new MyModel(), function (Grid $grid) {

});
            $form->html($content->render());
...

因为把两个列表都放在一个页面上了，所以就在一个页面上出现两个分页，这两个分页是有冲突的，点下面这个MyModel的分页就会出错，请问有没有好的解决方法吗？ 谢谢！

**Comment by jqhph** [comment]
需要给表格设置名称
```php
$grid->setName('test');
```

**Comment by xiajinjun** [comment]
谢谢，太感谢了
