### ISSUE TITLE
「BUG」前登出，後台自動登出；同樣，後台登出，前台也會自動登出

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#899]
- Laravel Version: 8.*
- Dcat Admin Version: 2.0.14

### Description:
記得之前用 Larave-Admin 時通過在
config('admin.route.middleware') 中追加 admin.session 選項可以解決;

同樣的方式 Dcat 無法解決。

類似的問題還有，前後台路由命名相同的問題；比如：
admin/news 和 前台 /news 的命名路由都是 news.index；
同時操作前後台時，頁面跳轉經常會很混

**Comment by jqhph** [comment]
配置参数 `admin.auth.enable_session_middleware` 设置为 `true` 再试试；路由别名你可以自己在路由文件中自定义

**Comment by faydanube** [comment]
> 配置参数 `admin.auth.enable_session_middleware` 设置为 `true` 再试试；路由别名你可以自己在路由文件中自定义
config\admin.php
![image](https://user-images.githubusercontent.com/8817046/103437311-fb341d00-4c60-11eb-95bc-47aff055b68a.png)

增加此配置之已完美解決此問題，建議下個版本可以默認增加此配置。

**Comment by faydanube** [comment]
@jqhph 建议将此配置增加到 admin.php 的默认配置哦。

**Comment by jqhph** [comment]
下个版本会加到默认配置中，并且会调整为 `admin.route.enable_session_middleware`
