### ISSUE TITLE
$form->hasMany Undefined index: _remove_

### ISSUE THREAD

**Issue by BrianBi** [jqhph/dcat-admin#9]
使用$form->hasMany时保存的时候出现Undefined index: _remove_

Form\NestedForm 235 if ($record[static::REMOVE_FLAG_NAME] == 1)

**Comment by jqhph** [comment]
无法重现，可否提供下相关代码。

另外请更新master分支最新代码，最近有些比较大的调整，更新完代码运行`php artisan admin:publish --force`

**Comment by BrianBi** [comment]
Model
class Attribute extends Model
{
    public function attribute_value()
    {
        return $this->hasMany(AttributeValue::class, 'attribute_id');
    }
}
class AttributeValue extends Model
{
    public function attribute()
    {
        return $this->belongsTo(Attribute::class, 'attribute_id');
    }
}

class AttributeRepository extends EloquentRepository
{
    /**
     * @var string
     */
    protected $eloquentClass = Attribute::class;
}

class AttributeValueRepository extends EloquentRepository
{
    /**
     * @var string
     */
    protected $eloquentClass = AttributeValue::class;
}

public function form()
    {
        $form = new Form(new AttributeRepository());
        // $form = new Form(new Attribute());
        $form->display('id', 'ID');
        $form->select('type', 'Type')->options(Attribute::getAttributeType());
        $form->text('name', 'Name');

        $form->hasMany('attribute_value', function (Form\NestedForm $form) {
            $form->text('value');
        });

        $form->display('created_at', 'Created At');
        $form->display('updated_at', 'Updated At');
        $form->disableViewCheck();
        $form->disableViewButton();
        return $form;
    }

**Comment by jqhph** [comment]
没看出问题，更新mater分支下最新版本的代码再试试。
