### ISSUE TITLE
unable to make grid table responsive

### ISSUE THREAD

**Issue by chiwex** [jqhph/dcat-admin#902]
Laravel Version: 8
PHP Version: 7.3
Dcat Admin Version: 2.0

### Description:

$grid->allowResponsive(); method have been removed and unable to make grid table responsive. is there any way to make grid table responsive

**Comment by jqhph** [comment]
Try this
```php
$grid->fixColumn(3, -1);

// or
Admin::style(
  <<<CSS
.table-responsive {
    width: 100%;
    overflow-x: auto;
CSS
);
```

**Comment by chiwex** [comment]
only this one is working

Admin::style(
  <<<CSS
.table-responsive {
    width: 100%;
    overflow-x: auto;
}
CSS
);

thank you
