### ISSUE TITLE
参考demo里的头部导航 网站配置 为啥不起作用啊

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#903]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
说明代码有问题，自己对比下

**Comment by shunhua** [comment]
目前找不到哪里的问题&nbsp; 需要开启啥嘛？我是直接复制demo里面的helpers.php






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jiang Qinghua"<notifications@github.com&gt;; 
发送时间: 2020年12月30日(星期三) 下午4:51
收件人: "jqhph/dcat-admin"<dcat-admin@noreply.github.com&gt;; 
抄送: "vino"<2399315737@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jqhph/dcat-admin] 参考demo里的头部导航 网站配置 为啥不起作用啊 (#903)





 
说明代码有问题，自己对比下

**Comment by jqhph** [comment]
没有什么要开启的，所有代码都在demo源码仓库里面

**Comment by shunhua** [comment]
但是现在发现不了啥问题 有没有具体的流程啥的？

**Comment by shunhua** [comment]
方便的话 加个qq  我发你qq啦

**Comment by jqhph** [comment]
demo用到的功能在文档里面都有
