### ISSUE TITLE
hasmany一对多关联tags标签加了rules(['required']) 后验证不到值

### ISSUE THREAD

**Issue by 15118035159** [jqhph/dcat-admin#905]
- Laravel Version: 7.30
- PHP Version: 7.3.9
- Dcat Admin Version: 从2.0.14-beat升级到2.x-dev后

### Description:
![image](https://user-images.githubusercontent.com/48081338/103355252-c4d39200-4ae8-11eb-897d-f2707ccf9740.png)
![image](https://user-images.githubusercontent.com/48081338/103355280-d4eb7180-4ae8-11eb-8b94-d99a6a7f765c.png)

**Comment by jqhph** [comment]
感谢反馈，已修复
