### ISSUE TITLE
本地可以访问 http://localhost:8000/admin 到线上 nginx环境上 就是404

### ISSUE THREAD

**Issue by ditrue** [jqhph/dcat-admin#907]
### 伪静态的加上了 还是404

**Comment by jqhph** [comment]
请参考laravel项目部署相关文档

**Comment by xiajinjun** [comment]
这个问题研究了许久，解决了
主要是需要做以下两步，供参考：
//enable mod rewrite
a2enmod rewrite

//restart apache
service apache2 restart
<Directory /var/www/html/laravel/public/>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
