### ISSUE TITLE
给不同的表添加了表名之后，分页是没有问题了，但是编辑和删除，还有tab里面的form 无法上传文件

### ISSUE THREAD

**Issue by xiajinjun** [jqhph/dcat-admin#911]
- Laravel Version: #.#.#
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.#

### Description:
请教一下，按照下面链接里面的方法，
https://github.com/jqhph/dcat-admin/issues/898

添加了表名之后，分页是没有问题了，但是第2个表的编辑和删除不可以，给编辑和删除按钮设置了data-url ,但是失效，点了编辑和删除之后，没有跳转到编辑和删除按钮的 data-url, 而是跳到了当前页面的URL，所以出错。请问是否有解决方法，谢谢！

**Comment by jqhph** [comment]
```php
$grid->setResource('路由前缀');
```

**Comment by xiajinjun** [comment]
谢谢！
