### ISSUE TITLE
select要求格式无效

### ISSUE THREAD

**Issue by Derek-FFFFF** [jqhph/dcat-admin#915]
- Laravel Version: 8.12
- PHP Version: 8.0.0
- Dcat Admin Version: 2.0.14-beta

### Description:
按照文档返回select要求的格式，但是却无法实现返回，若是采用paginate方式可以。还有select取消的话会产生这个0 abort，可以取消的么？

![3](https://user-images.githubusercontent.com/10068641/103439798-16138b00-4c7b-11eb-90fc-a26d7975ef5f.png)
![4](https://user-images.githubusercontent.com/10068641/103439801-1875e500-4c7b-11eb-9e2c-153947968c48.png)
![5](https://user-images.githubusercontent.com/10068641/103439802-190e7b80-4c7b-11eb-9591-1c06649ba273.png)

**Comment by jqhph** [comment]
你文档没看完，这个是options传url的格式，ajax的格式不是这个，回去看完整文档吧

**Comment by hiccup711** [comment]
我也遇到相同的问题了，文档中没写清楚，记录一下

使用 `ajax` 加载选项，返回格式需要是以下格式才可以渲染
![image](https://user-images.githubusercontent.com/37573610/120425231-6c0e6b00-c3a0-11eb-987c-e5f1ccc73444.png)

所以在接口返回数据方法中需要使用 `paginate` 方法，不能使用 `get`

正确的返回方式如下

``` php
$q = $request->get('q');
return CaseBase::query()->where('name', 'like', "%$q%")->paginate(null, ['id', 'name as text']);
```
