### ISSUE TITLE
【建议】建议 Dcat\Admin\Grid\Displayers\Label 的 display 方法返回值不要加 '&nbsp;'

### ISSUE THREAD

**Issue by vagra** [jqhph/dcat-admin#918]
现在 Dcat\Admin\Grid\Displayers\Label 的 display 方法返回是这样的：

```
return collect($value)->map(function ($name) use ($background) {
            return "<span class='{$this->baseClass}' {$background}>$name</span>";
        })->implode('&nbsp;');
```

因为有时候我需要横排的标签列表，有时候我需要竖排的标签列表；
当我需要竖排的标签列表时，我通常只要修改 css 样式就可以：
```
#grid-table td > .label {
    display: block;
}
```

但是，由于 display 方法在每个 label 之间插入了一个 `&nbsp;` ，导致 label 竖排时出现空行：
![图片](https://user-images.githubusercontent.com/1576687/103449928-14cd7700-4cea-11eb-98ae-98ea5c091672.png)

所以，建议把最后的 `implode('&nbsp;')` 改为 `implode('')` ，这样竖排时就不会有空行了。
![图片](https://user-images.githubusercontent.com/1576687/103449957-742b8700-4cea-11eb-8e43-b84d98cb5a0c.png)

然后如果嫌横排时 label 之间挤得太紧，如下图，那么调整它的 css 间距即可。
![图片](https://user-images.githubusercontent.com/1576687/103449966-958c7300-4cea-11eb-8aae-8ecdf9783cd4.png)

**Comment by jqhph** [comment]
好的，感谢建议
