### ISSUE TITLE
单击自定义操作按钮如何弹出一个IFrameGrid

### ISSUE THREAD

**Issue by ygcool** [jqhph/dcat-admin#92]
大致需求：增加表格自定义操作按钮，单击后弹出一个iframe，内容根据当前id获取数据，返回表格展示(我想应该是IFrameGrid)

**Comment by ygcool** [comment]
追加说明：当前我是在控制器定义了一个show方法，其中包括了自定义view和IFrameGrid，也可以说是如何自定义操作按钮弹出iframe展示这个show方法的页面

**Comment by jqhph** [comment]
感觉你可以看看这篇文章 https://learnku.com/articles/44139

**Comment by WillieOng-HK** [comment]
我也有类似的需求，但我的是自定义页面， 使用的是 FullCalendar 的JS 控件我也有类似的需求，但我的是自定义页面， 使用的是 FullCalendar 的JS 控件
![image](https://user-images.githubusercontent.com/5966527/138339697-5de8aef7-2bf9-4e71-a9a1-60bdd631683d.png)
我想點擊日期事件后弹出工具表单(Widgets\Form)，已知Full Calendar 的日期点击事件是
```
dateClick: function() {
	// var obj = $(this).find(".feather.icon-edit");
	//if (obj.length == 1) {
	//	obj.trigger("click")
	//}
},
```

但不知道如何唤起工具表单（Grid, Show, Form 的 Tool 中可以使用的）
