### ISSUE TITLE
请问怎么把上传的PDF文件显示在详情页面？

### ISSUE THREAD

**Issue by xiajinjun** [jqhph/dcat-admin#920]
- Laravel Version: #.#.#
- PHP Version: 7.3.#
- Dcat Admin Version: 1.7.#

### Description:
请问怎么把report_file_address这个PDF文件显示在详情页面？

protected function detail($id)
    {
        return Show::make($id, new Report(), function (Show $show) {
            $show->field('report_id');
            $show->field('report_file_address');//<---这是上传的PDF文件的地址， 如果要把这个文件显示在网页里面，怎么弄？

            $show->field('report_name');
            $show->field('created_at');
            $show->field('updated_at');
        });
    }

**Comment by Ynwaspectre** [comment]
同问

**Comment by Ynwaspectre** [comment]
$show->field('inv_no_attachment')->file();  找到了
