### ISSUE TITLE
demo 里的异步表格可以携带查询条件吗？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#924]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
可以携带的话 ，携带格式怎么写的？

**Comment by jqhph** [comment]
跟普通表格一样

**Comment by shunhua** [comment]
怎么一样？写法是啥？或者有没有写法案例

**Comment by shunhua** [comment]
每次别动不动就关闭啊 ，解决完了再关闭  急啥嘞。

**Comment by jqhph** [comment]
参考表格的相关使用文档

**Comment by shunhua** [comment]
你直接说下不是更好吗？额。。

**Comment by jqhph** [comment]
那我还写文档干啥，每次都回答这些基础的问题我不被累死也被烦死了，这么基础的功能你不看文档后面也还会有更多问题

**Comment by shunhua** [comment]
最起码给个链接啊 这。。。。

**Comment by shunhua** [comment]
问题是没找到相关的，合着把问题解决不就好了，为啥非得搞复杂了呢

**Comment by cnxfire** [comment]
// 添加默认查询条件
$grid->model()->where('id', '>', 100);
