### ISSUE TITLE
存在多个 selectTable 时弹窗标题显示错误

### ISSUE THREAD

**Issue by kaijuchin** [jqhph/dcat-admin#926]
- Laravel Version: 7.29
- PHP Version: 7.2.8
- Dcat Admin Version: 2.0.14

### Description:
表单中 selectTable 、 multipleSelectTable 同时存在的情况下，第二个 selectTable 的弹窗标题会取第一个 selectTable 标题

**Comment by jqhph** [comment]
感谢反馈，已修复
