### ISSUE TITLE
批量上传图片和附件第一次传了几张图，提交后再编辑再传图就把上次传的图片文件全部删除了只剩下这次传的图

### ISSUE THREAD

**Issue by canglangbailu** [jqhph/dcat-admin#928]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: v2.0.15-beta

### Description:
批量上传图片和附件又发现了个问题，比如第一次传了几张图，提交后再编辑再传图就把上次传的图片文件全部删除了只剩下这次传的图了

**Comment by jqhph** [comment]
未能复现，请提供表单的代码以及描述清楚操作步骤
