### ISSUE TITLE
查询过滤--->过滤器组 group 异常

### ISSUE THREAD

**Issue by zd520ll** [jqhph/dcat-admin#929]
- Laravel Version: ^7.0 || ^8.0
- PHP Version: ^7.3
- Dcat Admin Version: v2.0.13-beta || v2.0.14-beta || v2.0.15-beta

### Description:
![image](https://user-images.githubusercontent.com/33617803/103497880-dcf73880-4e7d-11eb-9ba7-ed04ad203133.png)
查询过滤--->过滤器组 group

```
$filter->group('rate', function ($group) {
    $group->gt('大于');
    $group->lt('小于');
    $group->nlt('不小于');
    $group->ngt('不大于');
    $group->equal('等于');
});
```

异常

**Comment by jqhph** [comment]
已修复，感谢反馈
