### ISSUE TITLE
如何控制数据表格单元格文字居中？

### ISSUE THREAD

**Issue by vagra** [jqhph/dcat-admin#931]
首先我晓得现在有个 ->bold() 方法可以控制单元格文字粗体，还能加颜色；
但是却没有 ->center() 方法，来控制单元格文字居中。

要知道，在 laravel admin 中，每个单元格，都是有个独立的类名的，以 `column-字段名` 为类名，这样可以很容易在 css 中，定制每个字段的单元格的样式，包括粗体、居中、颜色等等的非常自由。

但是事实上通常我们只需要控制几个特别的字段的单元格样式，所以其实不必给每个单元格都加样式。

那么只要能满足最常用的需求就可以了，那么最常用的需求，除了 bold() ，还应该有 center() ，大概还有文字靠上、靠下还是居中。

如果有现成的快捷方法，就可以不用给这个单元格添加 css 类，省事儿一些。复杂一些的样式控制需求，才给单元格添加 css 类。

**Comment by jqhph** [comment]
文字居中是有现成的方法的，文档也有介绍

```php
$grid->addTableClass(['table-text-center']);
```

**Comment by vagra** [comment]
看了，还可以。

**Comment by vagra** [comment]
噢！
```
$grid->addTableClass(['table-text-center']);
```
这个是针对整个数据表格 $grid 的，我希望的是针对一列单元格的，也就是
```
$grid->column('pub')->center();
或者
$grid->column('pub')->addTdClass(['text-center');
```

**Comment by jqhph** [comment]
其实这些功能都有，很简单，建议多翻翻文档

```php
// 设置td标签HTML属性
$grid->column('email')->setAttributes(['class' => 'text-center'])

// 设标题的html属性
$grid->column('name')->setHeaderAttributes(['class' => 'text-center']);
```

封装成`center`方法
```php
Grid\Column::macro('center', function () {
    return $this->setAttributes(['class' => 'text-center']);
});
```

**Comment by vagra** [comment]
晓得了，谢谢。
