### ISSUE TITLE
后台管理员，使用oss上传图片后 无法保存头像

### ISSUE THREAD

**Issue by dmskys** [jqhph/dcat-admin#934]
- Laravel Version: #.#.#
- PHP Version: #.7.4#.#
- Dcat Admin Version: # v2.0.15 beta .#.#

### Description:
后台管理员，使用oss上传图片后 无法保存头像

**Comment by jqhph** [comment]
看接口返回以及错误日志排查下

**Comment by dmskys** [comment]
> 看接口返回以及错误日志排查下

使用发现版本v2.0.11 beta 可以保存头像 升级到v2.0.15 beta 就不行了！

**Comment by dmskys** [comment]
> > 看接口返回以及错误日志排查下
> 
> 使用发现版本v2.0.11 beta 可以保存头像 升级到v2.0.15 beta 就不行了！

查看post请求发现oss上传成功了 图片也显示了，但是保存数据时，avatar没有传递值给后台保存

**Comment by dmskys** [comment]
> 看接口返回以及错误日志排查下

经过排查是进行版本升级时，浏览器缓存问题，删除浏览器缓存可了！！麻烦升级的时候改变一下资源文件版本号
