### ISSUE TITLE
如何停用快速编辑的重置按钮

### ISSUE THREAD

**Issue by pkkbkraa** [jqhph/dcat-admin#935]
- Laravel Version: 8.0
- PHP Version: 7.4
- Dcat Admin Version: 2.0.15

### Description:
在 form 加上 $form->disableResetButton(); 只能停用一般编辑的重置，快速编辑的仍然存在，可有方式可以拿掉?

**Comment by jqhph** [comment]
默认的快捷编辑没办法禁用，不过可以自己定义弹窗编辑功能，参考文档表单弹窗栏目

**Comment by xiaobing1024** [comment]
我找到办法了，在 `app/Admin/bootstrap.php` 中添加 `css`
``` php

Admin::style('.layui-layer-btn1{display:none!important}');

```
