### ISSUE TITLE
异步设置后台主题颜色的功能好像webuploader覆盖不到, 大佬帮忙看看

### ISSUE THREAD

**Issue by 15118035159** [jqhph/dcat-admin#938]
- Laravel Version: 7.30
- PHP Version: 7.3
- Dcat Admin Version: 2.0.15 - beat

### Description:
![image](https://user-images.githubusercontent.com/48081338/103603468-a850b300-4f49-11eb-8126-be3bf832abb2.png)

![image](https://user-images.githubusercontent.com/48081338/103603565-de8e3280-4f49-11eb-95ae-de884185cd80.png)

![image](https://user-images.githubusercontent.com/48081338/103603668-1eedb080-4f4a-11eb-99f6-8cf7c4caa861.png)

**Comment by jqhph** [comment]
好的

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/103628294-c33b1b80-4f79-11eb-8798-11ebfeba4090.png)
试了下是正常的，你重新发布资源然后清理下浏览器缓存再试试

**Comment by jqhph** [comment]
切换主题后确实有这个问题

**Comment by jqhph** [comment]
已修复，感谢反馈
