### ISSUE TITLE
弹窗形式表单新增点右上角的叉号背景的黑屏没有移除

### ISSUE THREAD

**Issue by Warrens-yg** [jqhph/dcat-admin#942]

**Comment by jqhph** [comment]
默认是没有开启遮罩层的

**Comment by Warrens-yg** [comment]
$grid->enableDialogCreate(); 
只是开启了弹窗就出现了这个问题

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/103644561-8713b500-4f91-11eb-8fe4-e6f7be7f2fce.png)
哪里有遮罩层？？？

**Comment by Warrens-yg** [comment]
这个是有配置控制吗？我都不知道啊

**Comment by jqhph** [comment]
你自己开的吧，参考layerui弹窗的文档

**Comment by Warrens-yg** [comment]
找到了，因为用了layui的其他包导致覆盖掉了
