### ISSUE TITLE
升级后图片可以上传，但是图片路径没办法保存到数据库了

### ISSUE THREAD

**Issue by gengxuliang** [jqhph/dcat-admin#943]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
未能复现，请提供表单的代码以及描述清楚操作步骤

**Comment by gengxuliang** [comment]
Laravel Version: 8.20.1
PHP Version: 7.3.5
Dcat Admin Version:  从2.0.10 升级到 2.0.15

升级完成后，edit和create里面包含图片上传控件，选择图片上传后图片自动上传成功，之后点表单的提交，图片路径没有保存到数据库，从后台在saved回调里面打印图片字段显示为null，（猜测有可能是上传完图片，没有给隐藏的图片字段赋值导致）

**Comment by gengxuliang** [comment]
降级之后就可以成功保存图片，升级后就不可以了

**Comment by jqhph** [comment]
你看下管理员头像上传是否正常

**Comment by gengxuliang** [comment]
以下是表单代码
` /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Form::make(new Block(), function (Form $form) {
            $form->display('id');
            $form->select('key')->options(Block::KEYS)->required();
            $form->text('title');
            $form->url('link');
            $form->number('sort')->max(127)->min(0);
            $form->image('content_image')->maxSize(10*1024)->uniqueName()->autoUpload();
            $form->textarea('content_text');
            $form->editor('content_editor');

            $form->display('created_at');
            $form->display('updated_at');
        });
    }`

**Comment by jqhph** [comment]
你该不会是没有发布资源吧

**Comment by gengxuliang** [comment]
发布了 ， php artisan admin:publish --assets --migrations --force  执行的这个之后， 头像我测试了下， 上传图片成功，服务器上也有这张图片，但是头像没有变

**Comment by gengxuliang** [comment]
问题已经找到，应该是发布资源之后，静态资源有缓存造成的， 多谢
