### ISSUE TITLE
dcat admin 里如果想实时无感异步更新列表数据，该怎么处理好一些呢

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#944]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
最简单的方法就是定时器轮询，用`Dcat.reload()` 可以刷新当前页面，不过当`pjax`加载完成时需要清除定时器，这个你可以百度`pjax`的相关用法

**Comment by shunhua** [comment]
能只刷新 列表页的 内容吗？其他菜单啥的都不动

**Comment by shunhua** [comment]
laravel-echo 结合Dcat admin  可以实现吗？有具体思路吗？

**Comment by shunhua** [comment]
![image](https://user-images.githubusercontent.com/11988030/103971817-7a1bdf00-51a6-11eb-8356-3aad8b2c524b.png)
