### ISSUE TITLE
异步加载 icon图标能换吗？

### ISSUE THREAD

**Issue by shunhua** [jqhph/dcat-admin#946]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
`// 从 v1.6.0 版本起允许在闭包内返回异步加载类的实例
$grid->post->modal(function ($modal) {
    $modal->title('自定义弹窗标题');
- [ ]  **这里面可以自定义icon 图标吗？**

    // 允许在比包内返回异步加载类的实例
    return Post::make(['title' => $this->>title]);
});
`

**Comment by jqhph** [comment]
不支持，后续会增加这个功能

**Comment by shunhua** [comment]
好的
