### ISSUE TITLE
【问题】有没有办法来设置 dcat-box 的宽度？

### ISSUE THREAD

**Issue by vagra** [jqhph/dcat-admin#947]
无论是 grid 还是 show 还是 form 页面，有时候都会有需求，希望 dcat-box 不要占全宽，占一半就够了。

经常是因为一个表格只有很少的几行，占全宽的话太不美观了。
![图片](https://user-images.githubusercontent.com/1576687/103753859-8557f900-5046-11eb-8394-8ca1f93a37cd.png)

如果可以指定 dcat-box 的宽度，那就好看了：
![图片](https://user-images.githubusercontent.com/1576687/103753990-b2a4a700-5046-11eb-9125-61878d788906.png)

现在好像是可以使用 `$grid->addTableClass(['half']);` 这样的方法，通过给 dcat-box 里面的表格赋予宽度来实现，但是不是太好看，因为【新增】等按钮没有跟随表格宽度：
![图片](https://user-images.githubusercontent.com/1576687/103754254-17600180-5047-11eb-9b42-a1328fefe860.png)

如果没有的话，能否新增一个方法，可以设置 dcat-box 的宽度？比方说：
```
$grid->width(8);
$show->width(8);
$form->width(8);
```
这样，能够设置 dcat-box 的宽度为 8/12 。

**Comment by jqhph** [comment]
这个功能应该由栅格布局系统去实现，参考文档开发前必读栏目

**Comment by vagra** [comment]
确实好用啊！覆盖 index() show() 或 edit() 方法即可：

```
use Dcat\Admin\Layout\Content;
use Dcat\Admin\Layout\Row;
...


    public function show($id, Content $content)
    {
        return $content->row(function(Row $row) use ($id) {
            $row->column(10, $this->detail($id));
        });
    }

    public function edit($id, Content $content)
    {
        return $content->row(function(Row $row) use ($id) {
            $row->column(10, $this->detail($id));
        });
    }
```

**Comment by jqhph** [comment]
是的，新手应该多看看文档，我这个章节的名称叫**《开发前必读》**，但是还是很多人都不看
