### ISSUE TITLE
Rate 组件在 StepForm 中设置默认值无效

### ISSUE THREAD

**Issue by zhenxxin** [jqhph/dcat-admin#951]
- Laravel Version: 7.28.4
- PHP Version: 7.4.13
- Dcat Admin Version: 1.7.3

### Description:
当在 StepForm 中设置 Rate 组件的 default 属性无效，默认值始终为 0

### Steps To Reproduce:

Form 中使用正常：
```php
$form->rate('batch_discount', '批量购买折扣')
    ->customFormat(function ($discount) {
        return $discount * 100;
    })
    ->saving(function ($discount) {
        return round_even($discount / 100);
    })
    ->rules('integer|min:0|max:100')
    ->default(95)
    ->help('100-表示无折扣，99-表示9.9折，0-表示免费，以此类推；相亲活动不可用');
```
Form 中使用的效果图：
![Form 中使用的效果图](https://user-images.githubusercontent.com/4496285/103854804-49776f00-50ec-11eb-874d-50f8c0264029.png)

StepForm 中使用不正常：
```php
$form->multipleSteps()
    ->remember()
    ->add('基本信息', function (Form\StepForm $form) {
        $form->rate('batch_discount', '批量购买折扣')
            ->customFormat(function ($discount) {
                return $discount * 100;
            })
            ->saving(function ($discount) {
                return round_even($discount / 100);
            })
            ->rules('integer|min:0|max:100')
            ->default(95)
            ->help('100-表示无折扣，99-表示9.9折，0-表示免费，以此类推；相亲活动不可用');
    });
```

StepForm 的效果图：
![StepForm 的效果图](https://user-images.githubusercontent.com/4496285/103854680-06b59700-50ec-11eb-8bab-8ba248fcab1d.png)

期望的效果：StepForm 中的 Rate 组件的使用效果与在 Form 中的保持一致

**Comment by jqhph** [comment]
在customFormat回调中返回默认值吧

**Comment by zhenxxin** [comment]
在 customFormat 方法中该如何判断返回默认值，还是正常的值呢？
我这边进这个方法的时候，值已经是 0 了。
![image](https://user-images.githubusercontent.com/4496285/103863711-484e3e00-50fc-11eb-9e3e-4a8a9f72d7b5.png)

是因为我的 Model 设置了 `$casts` 导致的吗？
