### ISSUE TITLE
请叫各位我想在$menu->add()动态生成的菜单种添加js事件监听，当用户点击某菜单，会请求数据库在动态生成子菜单

### ISSUE THREAD

**Issue by 562122362** [jqhph/dcat-admin#956]
请问各位我想在$menu->add()动态生成的菜单种添加js事件监听，当用户点击某菜单，会请求数据库在动态生成子菜单
![image](https://user-images.githubusercontent.com/30225668/103971278-10e79c00-51a5-11eb-8ea9-b555c3531b4f.png)

**Comment by 562122362** [comment]
其实我的意式怎么给动态生成的菜单添加class
![image](https://user-images.githubusercontent.com/30225668/103971469-a08d4a80-51a5-11eb-9522-eefbf84fd7c5.png)

**Comment by jqhph** [comment]
那就只有自己渲染菜单模板了，可以参考文档 区块 章节

**Comment by 562122362** [comment]
感谢大佬提供的思路
