### ISSUE TITLE
由于样式原因l导致ogo-mini 空白不可见

### ISSUE THREAD

**Issue by hongbinhsu** [jqhph/dcat-admin#960]
- Laravel Version: 7
- PHP Version: 7.3
- Dcat Admin Version: 2.0.15-bate

### Description:
CSS中 .main-menu .navbar-header .logo-mini
display:none; 导致LOGO不可见

### Steps To Reproduce:
删除 .main-menu .navbar-header .logo-mini中的display:none; 即可

**Comment by jqhph** [comment]
logomin默认就是隐藏的，当菜单栏收缩之后才会显示
