### ISSUE TITLE
Grid 的删除和批量删除 操作后会返回到列表页，丢失get的 筛选状态

### ISSUE THREAD

**Issue by larvacent** [jqhph/dcat-admin#961]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: 2.X

### Description:
Grid 的删除和批量删除 操作后会返回到列表页，丢失get的 筛选状态，view里的删除返回list无可厚非，但是grid的批量操作直接返回list丢失 筛选 是个Bug

**Comment by jqhph** [comment]
已增加这个功能，可以先升级2.0开发分支代码
