### ISSUE TITLE
【BUG】Form\Field\MultipleSelect ，多选下拉框，在没有选中任何项时，多出一行空行。（Firefox only）

### ISSUE THREAD

**Issue by vagra** [jqhph/dcat-admin#967]
Form\Field\MultipleSelect ，多选下拉框，在初始状态，没有选中任何项的状态下，上面多了一行空行，不美观，检查发现多了一行 `<ul>` ，如图（分类栏是单选下拉框）：
![图片](https://user-images.githubusercontent.com/1576687/104261234-0f2d1980-54c0-11eb-94b9-ff0e74416666.png)
![图片](https://user-images.githubusercontent.com/1576687/104261254-18b68180-54c0-11eb-9ac0-b38e0e3c8489.png)

追踪代码，发现问题可能在 `resources\assets\dcat\extra\select-table.js` 文件中：
```
html = `<span class="select2-selection select2-selection--multiple">
 <ul class="select2-selection__rendered">${html.join('')}</ul>
 </span>`;
```

在这里是否有必要加个判断，没有任何项选中时就不显示 `<ul>` ？

补充：
Firefox 下面才有这个问题，Chrome 下面没这个问题。

**Comment by jqhph** [comment]
你的环境问题，没发现这种情况

**Comment by vagra** [comment]
我又安装了一份全新的 dcat ，直接看里面 admin 用户的用户资料里的多选下拉框，发现，清空选项后，也是这个问题：
![图片](https://user-images.githubusercontent.com/1576687/104277122-39430380-54e1-11eb-9207-7eea4a37c88b.png)

**Comment by vagra** [comment]
但 Chrome 上就没这个问题。我清空缓存看看。估计是 select2.js 的缓存问题。

**Comment by vagra** [comment]
下拉菜单的 `<input>` 有个样式 `width=100%` ，把它删除才正常：

![图片](https://user-images.githubusercontent.com/1576687/104278693-f8002300-54e3-11eb-9eb2-5af7de93e67d.png)

**Comment by vagra** [comment]
官方 Demo 站由于没有这个 width=100% ，就正常：
![图片](https://user-images.githubusercontent.com/1576687/104279311-0dc21800-54e5-11eb-8951-a6a117b05a9a.png)

**Comment by jqhph** [comment]
你什么浏览器

**Comment by vagra** [comment]
Firefox 。搜索发现 Firefox 下面确实 `width=100%` 工作不是太对劲儿，有不少反映这个问题的：
https://stackoverflow.com/questions/24769489/firefox-width-100-not-working-as-expected
https://bugzilla.mozilla.org/show_bug.cgi?id=932996

给`<input>` 的父元素 `<span>` 添加一个 `display: inline-block;` 风格才能解决；
如果 display 是 inline ，内层元素的 width=100% 就异常；

或者在自定义 css 文件中重新定义 span 的 css 类可以暂时解决：
```
.select2-search--inline {
    display: inline-block;
}
```

**Comment by jqhph** [comment]
火狐下的确有问题
