### ISSUE TITLE
文件上传的多线程技术实现？

### ISSUE THREAD

**Issue by Alistair-zhong** [jqhph/dcat-admin#97]
### 介绍:

在您的项目中我看到了很多亮点，其中异步文件上传，分块多线程上传是我最需要的。我想向您请教一下在您的项目中是如何实现`多线程上传`的？感谢您的开源分享～～～

1. 我已看到`Dcat\Admin\SupportWebUploader`类中处理分块上传部分
2. 异步上传部分我猜测是使用pjax实现的
3. 多线程处理这部分我没找着.....

我现在刚接触多线程上传，但是限于知识量有限，只能想到swoole、pthreads。

希望您能指点一二，再次感谢您的分享！

**Comment by jqhph** [comment]
这个多线程上传是指前端文件分块上传的时候使用了多线程上传功能，用的是`webuploader`这个插件实现的。

**Comment by Alistair-zhong** [comment]
哦哦，看来是我的理解有误。我这边的应用场景有点不一样，不能直接保存到云端，需要经过服务器转到云端，原因是要做一些特殊的权限校验。关于这样的场景，对于文件从服务器到云端的转存您有什么好的处理方式吗？我能想到的是用异步多线程处理。
