### ISSUE TITLE
xampp localhost安装后，登录admin显示成功，但转不到主界面，一直在登录界面中

### ISSUE THREAD

**Issue by lighter123** [jqhph/dcat-admin#971]
- Laravel Version: 7.30.1
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

### Description:
谢谢共享这个项目，非常好！

xampp localhost安装后，进入public界面，显示laravel界面；输入public/admin/登录admin，显示成功，但转不到主界面，一直在登录界面中；请问是设置问题吗？
![image](https://user-images.githubusercontent.com/49245303/104334053-e60c8900-54bf-11eb-872c-6cb4ad117b17.png)
![image](https://user-images.githubusercontent.com/49245303/104334180-0b999280-54c0-11eb-8dbd-a9dc7819b556.png)
![image](https://user-images.githubusercontent.com/49245303/104334286-27049d80-54c0-11eb-82a4-0e1dd81875a1.png)

**Comment by jqhph** [comment]
目录配置有问题，web目录应该指向public，请仔细查看安装文档
