### ISSUE TITLE
发现个 表格选择器 (multipleSelectTable)编辑页面问题

### ISSUE THREAD

**Issue by 2515104337** [jqhph/dcat-admin#972]
- Laravel Version: 8
- PHP Version: 7.3
- Dcat Admin Version: 2.0.16

### Description:多选框用了异步加载，创建是正常的，而且在异步弹窗也能将选项选上，但在编辑页面没有把选项显示出来
![image](https://user-images.githubusercontent.com/32679198/104337281-43402300-5530-11eb-8db7-a013cbfcc7fe.png)
![image](https://user-images.githubusercontent.com/32679198/104338337-5dc6cc00-5531-11eb-8df8-1aef35c37b2b.png)

https://user-images.githubusercontent.com/32679198/104337876-e729ce80-5530-11eb-875e-7ef5d42ddaed.mov

**Comment by jqhph** [comment]
你代码少了，没有设置显示的代码，看下文档
