### ISSUE TITLE
在控制器form表单提交时，checkbox复选框提交的数组有null值

### ISSUE THREAD

**Issue by RaneeXu** [jqhph/dcat-admin#974]
- Laravel Version: 8.16
- PHP Version: 7.3.24
- Dcat Admin Version: 2.0.16-beta

### Description:
在控制器form表单提交时，checkbox复选框提交的数组有null值，在转成分割字符串或json时也会把null值转换进去。

### Steps To Reproduce:
![checkbox](https://user-images.githubusercontent.com/56422571/104432448-fefe6280-55c3-11eb-8891-24daa0078cd3.jpg)

```php
$form->checkbox('answers', '正确答案')
       ->options(["A" => "A", "B" => "B", "C" => "C", "D" => "D", "E" => "E"]);
```

**Comment by jqhph** [comment]
忽略即可，这个保存的时候会过滤掉
