### ISSUE TITLE
正在新增时如何获取其他字段已经写入的值

### ISSUE THREAD

**Issue by HulkHulk2345** [jqhph/dcat-admin#977]
- Laravel Version: #.#.#
- PHP Version: #.#.#
- Dcat Admin Version: #.#.#

**Comment by jqhph** [comment]
问题描述清楚一点

**Comment by HulkHulk2345** [comment]
`            // 选择计划
            $form->select('id', '计划');
                // 计划详情
                $form->text('plan_type', '计划类型');

            // 根据详情中的计划类型请求第三方接口获取策略选项列表
            $form->radio('method', '策略');`

**Comment by HulkHulk2345** [comment]
@jqhph 
```
            // 选择计划
            $form->select('id', '计划');
                // 计划详情
                $form->text('plan_type', '计划类型');

            // 根据详情中的计划类型请求第三方接口获取策略选项列表
            $form->radio('method', '策略');
```
请问怎么拿到plan_type的值

**Comment by jqhph** [comment]
参考文档表单事件
