### ISSUE TITLE
admin_view()  函数渲染视图，会将<script>中的DOM的闭合标签都扔掉。

### ISSUE THREAD

**Issue by zhpefe** [jqhph/dcat-admin#978]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2

### Description:
admin_view()  函数渲染视图，会将<script>中的DOM的闭合标签都扔掉。
### Steps To Reproduce:
模板 blade.php 中 `<script> var div="<div></div>" </script>`
页面渲染后成为 `<script> var div="<div>" </script>`

**Comment by jqhph** [comment]
请把HTML标签字符串放在`template`标签中，例如

```html
<template class="xxx">
    <div>...</div>
</template>

<script> var div=$('.xxx').html() </script>
```
