### ISSUE TITLE
    $form->currency('xx','添加钱数')->symbol('￥')->rules('required|min:1');    这个大于1000 显示1,000.00  提交

### ISSUE THREAD

**Issue by 377123** [jqhph/dcat-admin#98]
$form->currency('xx','添加钱数')->symbol('￥')->rules('required|min:1');   
   这个大于1000 显示1,000.00  提交就报错就报错  字段类型 decimal(11,2) 900.00 就正常

**Comment by jqhph** [comment]
`currency`字段的使用的确有问题，不过你这个是报什么错？

**Comment by 377123** [comment]
大概意思是 数据类型不一致

**Comment by jqhph** [comment]
已修复，请更新master分支代码
```php
composer update dcat/laravel-admin:"dev-master"
```

**Comment by 377123** [comment]
dev-master  一个页面多个 editor 好了吗

**Comment by jqhph** [comment]
> dev-master 一个页面多个 editor 好了吗

这个早就修复了，建议watch一下这个仓库或者关注群公告，关注新版本发布信息。

**Comment by 377123** [comment]
你说错了吧   composer update dcat/laravel-admin:"dev-master"  没这个分支吧  是不是  composer update dcat/laravel-admin:"master"

**Comment by jqhph** [comment]
> 你说错了吧 composer update dcat/laravel-admin:"dev-master" 没这个分支吧 是不是 composer update dcat/laravel-admin:"master"

如果更新不成功，请手动把`composer.json`中`dcat-admin`的版本改为`dev-master`，然后再运行
```
composer update dcat/laravel-admin
```
