### ISSUE TITLE
左侧菜单会遮挡右侧的区域

### ISSUE THREAD

**Issue by bing15** [jqhph/dcat-admin#982]
- Laravel Version: 6.0
- PHP Version: 7.2
- Dcat Admin Version: 所有版本都会

### Description:
左侧菜单会遮挡右侧的区域

### Steps To Reproduce:
1 .左侧菜单是收起来的状态
![image](https://user-images.githubusercontent.com/13217508/104733602-e59f1700-5779-11eb-8871-484334e34408.png)
2.把鼠标移动到左侧菜单下点击菜单
![image](https://user-images.githubusercontent.com/13217508/104733688-0a938a00-577a-11eb-8edd-3b477b3d866a.png)

**Comment by jqhph** [comment]
adminlte3 fixed模式菜单就是这样设计的
