### ISSUE TITLE
Show\Field 的 image() 方法，天生就是支持多张图片的，但 file() 方法不行。

### ISSUE THREAD

**Issue by vagra** [jqhph/dcat-admin#983]
观察 Show\Field 的 image() 和 file() 方法，发现 image() 天生就是支持多张图片的，因为它会把 $path 作为一个 array 来处理，
所以如果存在多个路径，它自己就会显示为多张图片。

但 file() 却不会这样，当存在多个文件路径时，它就不显示了。

所以：
1、要不要对 file() 方法做一下扩展，让它可以支持多个文件的列表显示？

2、image() 方法其实还不完美，它没法直接处理 json 所保存起来的路径数组（也就是使用 Form 的 MultipleImages 方法上传上来的 Json 格式的图片路径列表），但修改方法很简单就是用 Helper::array() 把 $path 转换一下：
```
$path = Helper::array($path);    // 添加这行
return collect($path)->transform(function ($path) use ($server, $width, $height) { // 改 collect((array) $path) 为 collect($path)
```
这样改一下，images()方法就直接支持多图显示了：
![图片](https://user-images.githubusercontent.com/1576687/104793269-bbcb0c00-57dc-11eb-87b2-befff57a7d70.png)

**Comment by jqhph** [comment]
欢迎提交PR~

**Comment by vagra** [comment]
![图片](https://user-images.githubusercontent.com/1576687/104794560-680ff100-57e3-11eb-8383-0b5ff7ec60cd.png)
搞定，整理好后提交。
