### ISSUE TITLE
[需求]能否提供简单的批量编辑功能和批量删除类似的

### ISSUE THREAD

**Issue by ifelsedo** [jqhph/dcat-admin#989]
- Laravel Version: 8.*
- PHP Version: 7.4.*
- Dcat Admin Version: 2.0.10-beta

### Description:
大佬，如果可以的话，希望提供批量编辑功能，这个还是有点常用的
大致如下图：

![1](https://user-images.githubusercontent.com/20554450/104893590-9130ad00-59ae-11eb-9382-72ccc072c578.jpg)

**Comment by jqhph** [comment]
有批量编辑功能，参考文档 工具栏 -> 批量操作 -> 表单弹窗

**Comment by ifelsedo** [comment]
> 有批量编辑功能，参考文档 工具栏 -> 批量操作 -> 表单弹窗

我看了这样的话需要每个表都得实现一次，不是很理想。另外想要实现图中所示的对选中字段的修改，未选中则不做修改，这个个是最重要的。
