### ISSUE TITLE
下拉选框联动问题

### ISSUE THREAD

**Issue by stevenleeyu** [jqhph/dcat-admin#99]
- Laravel Version: 7.0
- PHP Version: 7.4
- Dcat Admin Version: 1.3.2

### Description:
1.表单添加下拉选框联动保存之后，重新编辑不能恢复已选项
$form->select('live_info.topic_userid', '选择群主(直播)')
                ->options($active_users)
                ->load('live_info.room_sn', '/ajax/room');

2.loads()方法第一个参数数组中不能使用["fieldA.fieldB", "fieldC.fieldD"]
$form->select('live_info.room_sn', '选择群')
->loads(['live_info.lecturer_sn', 'live_info.assistant_sn'], ['ajax/member', 'ajax/member'])；

**Comment by jqhph** [comment]
1.这个问题是修复过的，请贴一下代码

**Comment by jqhph** [comment]
感谢反馈，这个问题已修复，请更新master分支代码
```php
composer update dcat/laravel-admin:"dev-master"
```
