### ISSUE TITLE
「BUG」圖片上傳預覽文字多語言支持

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#992]
- Laravel Version: 8.22.1
- PHP Version: 7.4.13
- Dcat Admin Version: 2.0.16

### Steps To Reproduce:
1，上傳圖片
2，直接在磁盤上刪除圖片資源
3，點擊預覽按鈕，提示文字為簡體中文，設置的環境為 zh_TW。

希望此處的提示語言能夠支持多語言配置。

**Comment by jqhph** [comment]
台湾繁体不是很熟悉，欢迎提交PR~

**Comment by faydanube** [comment]
> 台湾繁体不是很熟悉，欢迎提交PR~

這裡的 "预览失败" 文字要在哪裡進行配置呢？
我目前直接在 public\vendor\dcat-admin\dcat\js\dcat-app.js 中進行的替換，每次發佈都要重新替換一次。

**Comment by jqhph** [comment]
尴尬了，这个忘记使用翻译文件了

**Comment by jqhph** [comment]
已修复，可以先更新2.0开发分支代码
