### ISSUE TITLE
「BUG」中文文件名上傳後，文件名沒有顯示「台灣服務器」

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#993]
- Dcat Admin Version: 2.0.16

步驟見視頻
https://user-images.githubusercontent.com/8817046/104926071-a4f20880-59da-11eb-9c31-ebc3c1d809de.mp4

**Comment by faydanube** [comment]
可以排除 數據庫 的額問題，因為使用 customFormat 函數直接 return '測試.md'; 依然不顯示 . 前面的中文，所以，應該是 webuploader 的 js，在處理字符串時的兼容問題，此問題個人無能力解決。非常抱歉。
@jqhph

**Comment by jqhph** [comment]
好的，感谢反馈，我看看这个问题

**Comment by jqhph** [comment]
![image](https://user-images.githubusercontent.com/20312339/104975168-e44d4300-5a34-11eb-960e-d3bfd1f3ec67.png)
我这边用 `return '測試.md';` 是可以正常展示出来的...你更新2.0开发分支代码试试，需要重新发布资源
```
composer require dcat/laravel-admin:"2.0.x-dev"
```

**Comment by faydanube** [comment]
> ![image](https://user-images.githubusercontent.com/20312339/104975168-e44d4300-5a34-11eb-960e-d3bfd1f3ec67.png)
> 我这边用 `return '測試.md';` 是可以正常展示出来的...你更新2.0开发分支代码试试，需要重新发布资源
> 
> ```
> composer require dcat/laravel-admin:"2.0.x-dev"
> ```

本地是沒有問題的，服務器坐標「台灣」……

**Comment by faydanube** [comment]
> > ![image](https://user-images.githubusercontent.com/20312339/104975168-e44d4300-5a34-11eb-960e-d3bfd1f3ec67.png)
> > 我这边用 `return '測試.md';` 是可以正常展示出来的...你更新2.0开发分支代码试试，需要重新发布资源
> > ```
> > composer require dcat/laravel-admin:"2.0.x-dev"
> > ```
> 
> 本地是沒有問題的，服務器坐標「台灣」……

我私信您服務器

**Comment by jqhph** [comment]
请贴下表单代码看看

**Comment by faydanube** [comment]
> 请贴下表单代码看看

沒有特別的點，只是非常普通的上傳表單。本地沒有問題，但是在台灣的服務器上會不顯示中文。

`
$form->file('file')->autoUpload()->move('news/'.time())->customFormat(function($v) {
    return '上傳測試.md';
});
`

**Comment by jqhph** [comment]
如果把 customFormat 去掉呢？

**Comment by faydanube** [comment]
> 如果把 customFormat 去掉呢？

一樣。本身就應該是直接從數據庫取文件名，只是為了避免猶豫數據庫出問題，才使用 customFormat 測試。同時直接 dd 到的數據也是沒問題的。

服務器信息已經發到您的 QQ 郵箱了呢，具體原因還不知曉，但是目前定位到的範圍應該是 
> public\vendor\dcat-admin\dcat\extra\upload.js 中：
關於中文文件名獲取代碼的兼容問題。可能台灣的作業系統不同吧。但是不知如何解決。

**Comment by jqhph** [comment]
原因应该出在PHP的`basename`函数上，你线上服务器是什么系统，你可以调试下看看

```php
/**
     * @return array
     */
    protected function initialPreviewConfig()
    {
        $previews = [];

        foreach (Helper::array($this->value()) as $value) {
            $previews[] = [
                'id'   => $value,
                'path' => basename($value),
                'url'  => $this->objectUrl($value),
            ];
        }

        return $previews;
    }
```

**Comment by faydanube** [comment]
> ```
>         $previews = [];
> 
>         foreach (Helper::array($this->value()) as $value) {
>             $previews[] = [
>                 'id'   => $value,
>                 'path' => basename($value),
>                 'url'  => $this->objectUrl($value),
>             ];
>         }
> 
>         return $previews;
> ```

![image](https://user-images.githubusercontent.com/8817046/104980642-013c4300-5a42-11eb-91e0-6afd86fee872.png)

debug 結果的確是 basename 不能返回預期的值，要修改哪個文件修復此問題呢？

**Comment by jqhph** [comment]
你服务器是什么操作系统

**Comment by faydanube** [comment]
> 你服务器是什么操作系统

centos 配置的虛擬主機。

phpinfo 頁面：http://yinsong.weipuhost.com/phpinfo

**Comment by jqhph** [comment]
已修复，更新2.0开发分支，重新发布资源
```
composer require dcat/laravel-admin:"2.0.x-dev"
```

**Comment by faydanube** [comment]
Thanks alot!

> 已修复，更新2.0开发分支，重新发布资源
> 
> ```
> composer require dcat/laravel-admin:"2.0.x-dev"
> ```

**Comment by faydanube** [comment]
> 已修复，更新2.0开发分支，重新发布资源
> 
> ```
> composer require dcat/laravel-admin:"2.0.x-dev"
> ```

#993 的解決會併入哪個 beta 版？這決定我下個項目使用 dev 還是 beta?
