### ISSUE TITLE
关于json数组二位数组表单动态添加的bug 删除后 form里面的值不会被删除 依然通过fron表单提交上来了--

### ISSUE THREAD

**Issue by pl1998** [jqhph/dcat-admin#994]
- Laravel Version: 5.7
- PHP Version: 7.3
- Dcat Admin Version: 1.x

### Description:
关于json表单 二维数组的bug

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/43993206/105004894-87bb4980-5a6f-11eb-806e-baa2686faeca.png)

**Comment by jqhph** [comment]
这个是正常的
