### ISSUE TITLE
selecttable单选的出现选择后只显示id

### ISSUE THREAD

**Issue by zhaohongrui** [jqhph/dcat-admin#996]
- Laravel Version:5.8.38
- PHP Version: 7.4.1
- Dcat Admin Version: v2.0.16-beta

### Description:
selecttable单选的出现选择后只显示id，未显示sku，但修改时第一次加载页面会显示sku。
是否和select/i18n/.js?v2.0.16-beta文件缺失有关，核对过github上文件，也没有
![image](https://user-images.githubusercontent.com/33904482/105050581-e5b85300-5aa8-11eb-8cb3-0472562a1a99.png)

```
 $form->selectTable('sku', '选择商品')
                         ->title('商品选择')
                         ->dialogWidth('50%')// 弹窗宽度，默认 800px
                         ->from(GoodsTable::make())//
                         ->model(BaseGoods::class, 'id', 'sku');
```

**Comment by jqhph** [comment]
`selectTable`显示选中的文本与行选择器的设置有关，详细用法请参考`selectTable`的文档

**Comment by jqhph** [comment]
`select/i18n/.js?v2.0.16-beta` 你的语言设置的是什么导致出现这种情况

**Comment by zhaohongrui** [comment]
> `select/i18n/.js?v2.0.16-beta` 你的语言设置的是什么导致出现这种情况

我语言设置的en会出现这种情况，改成zh_CN好使了，感谢

**Comment by zhaohongrui** [comment]
> `selectTable`显示选中的文本与行选择器的设置有关，详细用法请参考`selectTable`的文档

这个我就是按照文档写的，，

**Comment by zhaohongrui** [comment]
> `selectTable`显示选中的文本与行选择器的设置有关，详细用法请参考`selectTable`的文档

哦哦，看到你说的那个了，漏了titleColumn配置，感谢
那id可以自己配置，我想把id换成其他值，但是试了下好像不行
