### ISSUE TITLE
Grid表格字段中如何显示一对多关联数据的总记录数

### ISSUE THREAD

**Issue by zhaoshl** [jqhph/dcat-admin#998]
- Laravel Version: 8.0
- PHP Version: 7.3
- Dcat Admin Version: 2.0.14

### Description:

比如文章列表中的每条记录都对应多条评论，想在列表中显示评论的数量（或者已审核通过后评论数量），该如何实现？
如果用withCount()该如何写呢？求赐教！

**Comment by jqhph** [comment]
参考文档表格基本使用以及数据来源

**Comment by zhaoshl** [comment]
查询了一些资料，不知这样实现是不是最合适的

在列表中使用
`$grid->model()->withCount([‘comments’]);`

参考：
App\Post::withCount('comments')->get();
使用该方法后，会在模型中添加一个comments_count属性，所以你就可以直接访问该属性就可以了得到统计数了。

```
foreach ($posts as $post) {
    echo $post->comments_count;
}
```
你可以像添加约束条件到查询一样来添加多个关联关系的“计数”：
```
$posts = Post::withCount(['votes', 'comments' => function ($query) {
    $query->where('content', 'like', 'foo%');
}])->get();
```

**Comment by jqhph** [comment]
方式有很多，看个人习惯
