### ISSUE TITLE
「問題」如何在 Controller 中設置 grid->actions 的寬度？

### ISSUE THREAD

**Issue by faydanube** [jqhph/dcat-admin#999]
- Dcat Admin Version: 2.0.x-dev

不希望表單列表頁的 actions 被自動換行，
目前解決方案是直接追加 css 到 public\vendor\dcat-admin\dcat\css\dcat-app.css，
然而這種解決方案非常的不優雅~ 個人沒能在文檔中找到相關的描述

**Comment by jqhph** [comment]
没看懂换行是什么意思，建议把入门栏目文档过一遍
```php
Admin::style('div{ ... }');
```

**Comment by faydanube** [comment]
> 没看懂换行是什么意思，建议把入门栏目文档过一遍
> 
> ```
> Admin::style('div{ ... }');
> ```
https://github.com/jqhph/dcat-admin/issues/999#issuecomment-763469351

其他列可以通過 setAttributes 設置屬性，但不知道如何設置 actions 列

**Comment by jqhph** [comment]
空间不够了，有两种方法：一种是显示表格X轴滚动条，这个要自己写css；另外一种是用固定列功能(fixColumn)

**Comment by faydanube** [comment]
> 不用改静态文件，我上面已经说过了，好好看下文档吧
有在使用 Admin::style('div{ ... }');
只是說個別情形要修改 stub 模板的時候，就只能去改 vendor 了。
打擾了
